				<!-- ******************* -->
				<!--   FEATURE ARTICLE   -->
				<!-- ******************* -->
				<!-- <h3>PROPERTY RIGHTS IN THE AGE OF GLOBAL WARMING: <br />A REEXAMINATION</h3> -->
				<h3>Property Rights in the Age of Global Warming:<br />A Reexamination</h3>
				<p class="center"><a href="http://www.lpu.com/attorneys/updegrove.shtml">Andrew Updegrove</a></p>
				<blockquote class="openingquote"><em><strong>Abstract:</strong>  The lesson of the "tragedy of the commons" is that property that is communally owned is doomed to over-exploitation.  This often observed phenomenon is reinforced by current property laws and concepts.  The challenges presented by global warming, the overexploitation of natural resources, and other environmental abuses that can only be solved through international cooperation underlines the urgent need to find new means to avert not only these but future common tragedies as well.  In this article, I suggest ways to reorder our concepts regarding property that may, if embraced, make it more feasible for nations to realize more effective solutions to these seemingly intractable issues.</em></blockquote>
				<p><strong><em>Introduction:</em></strong>  To date, existing governance systems have struggled in their efforts to address challenges such as resource depletion, accelerating species extinction, and global warming.  In each case, these complex and difficult problems are placing unprecedented demands on the mechanisms available to deal with them.  One reason for this difficulty is that in each of these examples, the traditional balancing of interests between individuals, society, and nation states does not easily permit the enactment of the types of laws needed to provide effective solutions. </p>
				<p>In the case of resource depletion, global resources may at the same time be essential, finite, scarce, and extant only within a small number of countries that are often poor, and sometimes ruled by corrupt regimes.  In such a situation, a consumer country has no way to enforce conservation on a country within whose borders those resources exist.  And more often than not, the citizens of the consumer country are more interested in current gratification than in long-term conservation as well.</p>
				<p>Similarly, in many countries around the world, the individual owner of the land upon which an endangered species lives cannot be compelled to protect (or even prevented from destroying) that species.  In some countries where laws do exist to protect the environment, inadequate enforcement and the daily realities of grinding poverty may leave ostensibly protected habitat vulnerable to commercial logging and harvesting by individuals for firewood.  And despite the fact that all countries throughout the world share the same atmosphere and planet and that most have ratified the Kyoto Protocol, there is no way for the signatories to that treaty to compel the United States, which is the largest emitter of green house gases, to abide by the same rules.</p>
				<p>At the national level, one reason why environmental abuse can, and does, occur is because the laws applicable to real property (i.e., land) recognizes more rights in the owners of such property than in those that may be affected by an owner's use of the same property.  The law does, it is true, recognize the ability of government to restrict such rights in various ways.  In recent times , laws have been passed in the United States (for example) to limit further losses of wetlands, and to protect the habitat of endangered species.  </p>
				<p>But the ability to enact and enforce such laws is limited to individual political units, while the threat to be addressed may extend outside, or lie entirely beyond, the borders of those affected.  Over the last two decades, for example, individual American States as well as nations have clashed over the impact of acid rain on the lakes and ponds of the down-wind party to the argument.  And today, entire Pacific island nations are helplessly witnessing the rise of waters that may literally submerge them.  In each case, the impact of the emissions of the affected party may be inconsequential &ndash; as is also its ability to curtail the conduct that threatens it.</p>
				<p>The degree of restriction needed to address such challenges may also extend beyond the political will power of a democratically elected government, even when the problem to be addressed lies entirely within the borders of the political unit in question.  An example of this dynamic can be found in continuing rampant population growth in parts of the United States that are rapidly depleting non-replenishing "fossil" groundwater reserves deposited during the last ice age.  In large part, such growth occurs because the pressure from developers and other businesses is greater than legislators are willing, or even inclined, to withstand.</p>
				<p>The fundamental clash once again involves the balancing of property rights, and the identity of the governments that are empowered to restrict and act in relation to those property rights.  And again, it may prove to be difficult, or even impossible, for effective solutions to be found unless there is an incremental rebalancing, and in some cases a fundamental restructuring, of such rights.</p>
				<p>In this article, I will suggest that increasingly serious environmental issues require us  to revise our thinking in relation to, both domestic as well as international law regarding  the ownership and use of real property .  I will also suggest a conceptual framework within which the rights of individuals, societies and nations may, I believe, be better and more effectively balanced.</p>
				<p><strong><em>Property law dynamism: </em></strong> Property rights are today carefully defined and codified in the written statutes of virtually every nation on earth.  With rare exceptions (e.g., Cuba), these rights are based upon substantially the same macro political theories.  Even where this is not the case (e.g., China), the trend of law is increasingly towards the global norm.  And while the political philosophies of individual nations may vary on where the balance should be set as among the rights of state, society and individual, the laws relating to property ownership do not vary significantly between, for example, a left-leaning Scandinavian country and the more "rights of the individual" focused United States.</p>
				<p>This consensus of national laws might suggest an attainment of legal perfection, were it not for the fact that the current regime of property laws manifestly fails to meet the needs of all citizens in important respects.  In the case of real property, the redistribution of land continues to occur in some countries only through extraordinary and deeply troubling means (most recently in Zimbabwe).  In the case of intangible property, existing copyright laws are proving inadequate to address (or at least enforce) traditional property rights in content during the age of the Internet.  At the same time, and no coincidentally,  wealth in many countries (including the United States) continues to become more concentrated in the hands of the rich at the expense of the poor.</p>
				<p>In fact, property rights have been the subject of ongoing evolution throughout historical times.  In all countries, individual (as compared to communal) rights in land were almost certainly unknown until indigenous cultures abandoned hunter-gatherer lifeways in favor of agriculture.  In some societies, this transition did not occur until the twentieth century, and even in the sparsely populated Europe of the Middle Ages, large sections of territory were known only as "the Wild," with ownership in any individual - even the King - being notional at best.  As recognized by American anarchist Benjamin Tucker, the concept of "property" does not become meaningful until the property in question becomes scarce enough to attract competition over its control.</p>
				<p>Over time, consensus over property law was legally codified, but the duration of that consensus has decreased over time. Witness, for example, the longevity of the following property law regimes: Roman law (maximally, 753 BC to 476 AD), Feudal (some hundreds of years &ndash; there is no consensus on its exact duration), and nationally implemented communism (from first real-world implementation until the beginning of its collapse, less than 70 years).</p>
				<div class="calloutright">
					<p>The state of property law can properly be seen as, at most, a best approximation of the rules that a given society at a given point in time deems to be both necessary and acceptable to keep the peace, and to order its internal affairs.  </p>
				</div>
				<p>Indeed, entirely new forms of property rights have only become codified into law in comparatively recent times.   Patent laws were first enacted in European nations in the 15th century, while the need for the law of copyright did not, as a practical matter, arise prior to the invention of movable type (the first copyright law generally acknowledged as such was England's Statute of Anne, enacted  in 1710).  Similarly, microprocessor designs ("mask works") were first protected by statute in the United States in 1984, and laws relating to domain names are still evolving rapidly, as is the patent law as applied to software and genomics.</p>
				<p>Nor have the political and economic theories defining and justifying property rights been static throughout modern times, with significant differences to be found among philosophers and theoreticians as diverse as Thomas Hobbs, John Locke, David Hume and Karl Marx &ndash; to name only a very few.</p>
				<p>In consequence, the state of property law can properly be seen as, at most, a best approximation of the rules that a given society at a given point in time deems to be both necessary and acceptable to keep the peace, and to order its internal affairs.  The logical extension of such a conclusion is therefore that as conditions change, so must property laws, or existing laws will become progressively less effective, and society will become less stable and more at risk.</p>
				<p><strong><em>Rights of property owners:</em></strong>  At the most basic level of analysis, determining the parameters of property rights involves making a number of determinations, including the following (focusing primarily on rights in real property):</p>
				<ul>
					<li><strong><em>Who is the owner?</em></strong>  Corporate ownership is a comparatively recent legal innovation, while communal, state and individual ownership are ancient.  More recently, the concept of ownership by no one if not by everyone has been recognized.  For example, the oceans, other planets, space and Antarctica have all been designated by treaties and conventions as being areas where the signatory nations have agreed that national ownership cannot be asserted (or where such rights have been limited) and where various types of activities are prohibited. </li>
					<li><strong><em>How long can ownership be maintained?</em></strong>  Ownership of real property can be perpetual, subject to taking by the state for public purposes under applicable eminent domain laws.  Other types of property, such as intangibles, have other rules: the copyright in a work under current law is sustainable for the life of the creator plus a designated number of years, after which it passes into the public domain, and patents can be enforced for a shorter period of time.  But a trademark can be owned in perpetuity.  </li>
					<li><strong><em>What can the owner do with the property? </em></strong> At the highest level, property rights include the right of possession and the right of transfer.  As a practical matter, the starting proposition is generally that an owner can do anything with its property that is not prohibited by law or restricted by a right granted to a third party, and can transfer that property to anyone at any time.</li>
					<li><strong><em>What can an owner not do with its property?   </em></strong> Rights in property can be restricted through various means.  Zoning laws restrict the uses to which land can be put, easements can be granted to third parties that convey rights that may (for example) restrict development, permit utilities or access routes to be placed across the property, and to grant exclusive rights to extract specified, or all, minerals.  In each case, although the owner remains entitled to freely transfer the property in question, these restrictions will "run with the property," and bind successor owners to the property, so long as appropriate easements have been properly recorded in real property registries.  Government imposed restrictions, such as zoning laws, burning bans, and watering restrictions require no such recordation.</li>
					<li><strong><em>Who has the power to restrict a property owners rights?</em></strong>  There are three types of parties traditionally entitled to affect a real property owner's exercise of its rights:  governments (national, state and local), third parties to whom the owner has granted rights of use or enforcement, and abutting or nearby neighbors that bring claims under laws protecting them from "nuisances" or other abuses occurring on the land of another that affect the use, value or enjoyment of their own property.</li>
					<li><strong><em>What are the limits, if any, on those restrictions?</em></strong> Property rights are precious, and are often protected not only by statute, but also by national constitutions that impose limits on the degree to which even governments can restrict them. For example, the 5th Amendment to the United States Constitution provides that: &quot;No person shall be... deprived of life, liberty, or property, without due process of law; nor shall private property be taken for public use, without just compensation,&quot; a limitation extended to the several states through the 14th Amendment, which provides that: &quot;No State shall... deprive any person of life, liberty, or property, without due process of law... &quot;</li>
				</ul>
				<p><strong><em>The current problem: </em></strong> As can be seen from the above brief summary, legal systems do not generally recognize the rights of either a property owner or the state as being absolute.  Instead, an active and dynamic balancing occurs at multiple levels: a constitution imposes gross parameters that can only be changed by overwhelming national consensus, while governments are free to react to current developments through the enactment, amendment, and retiring of laws within these constitutional parameters, and individuals can utilize the courts not only to enforce the laws of nuisance and their rights under easements, but are also entitled to challenge the application or constitutionality of the laws themselves.  </p>
				<p>The result is a system that is subject to constant organic, but usually incremental, change.  Under normal circumstances, this type of gradual evolution is adequate to meet the needs of society.  But when the demands upon that system change dramatically, what then?</p>
				<div class="calloutleft">
					<p>Given that the Kyoto Protocol, with all of its flaws, represents the ultimate mechanism to address global warming that existing systems are capable of delivering, what is to be done?</p>
				</div>
				<p>The challenge of global warming provides an instructive example of how current systems can be inadequate to provide effective solutions to natural resource concerns.  While global warming is now accepted as a scientific fact, the two largest contributors to global warming continue to be largely unrestricted: the United States, because it has refused to become a party to the Kyoto Protocol, and China, because it is subject to far less restrictive terms, in order to permit it to more easily achieve equal economic status with those countries that have created the lion's share of the greenhouse gases already released into the atmosphere.  Moreover, there are no punitive consequences provided for those countries that fail to meet the targets required by the treaty.</p>
				<p>Meanwhile, global warming continues apace.  Given that the Kyoto Protocol, with all of its flaws, represents the ultimate mechanism to address global warming that existing systems are capable of delivering, what is to be done?</p>
				<p>Let us consider the same property related questions discussed above in this context in search of an answer.</p>
				<p><strong><em>Who is the owner? </em></strong> Now that units of atmosphere with acceptable levels of green house gases have become "scarce," to apply Tucker's analysis, a property interest should be recognized in those that wish to protect themselves by avoiding further increases in such gases.  But before there can be a protectible interest, there must be a valid and acknowledged authority to recognize that interest, and to regulate it.   As a result, it becomes necessary to define who is the "owner" of the atmosphere, before we can find a solution.    </p>
				<p>It would appear obvious that if anyone can claim to have an ownership interest in the atmosphere, then everyone must have a claim to be such an owner.  It next logically follows that if everyone owns the atmosphere, then everyone should have an equal right to use the atmosphere, and have an equal say over how it should be protected.  Since the atmosphere is mobile, and a unit of atmosphere over Siberia today may be over Montana a few days later, then it must also be true that everyone has an undifferentiated, joint ownership interest in the entire atmosphere.  </p>
				<p>There are more subtle, but important, ownership question as well: Are individuals the personal owners of the atmosphere by virtue of "homesteading" their personal space, with their governments acting merely as their representatives for practical purposes?  Or is a nation the pro rata proxy owner of the atmosphere on the behalf of all of its citizens, in the manner of public lands held on behalf of all?  </p>
				<p>The most intriguing question may be whether corporations can claim to be owners at all?  If the answer is that individuals own the atmosphere individually and corporations own the atmosphere not at all, then presumably a corporation would have no rights to release greenhouse gases into the atmosphere at all.</p>
				<div class="calloutright">
					<p>Now that global warming has been identified, laws relating to greenhouse gases will need to exist for so long as a global warming threat remains.  In other words, indefinitely.</p>
				</div>
				<p>These questions are also meaningful in constitutional terms, since it could be argued that the U.S. government could not permit an individual's property interest in the atmosphere to be damaged by a corporation" without due process of law," or perhaps that in order for the government to issue an emissions permit to a power plant, the plant owner would first be required to pay  "just compensation" to all individuals whose allocable shares of the atmosphere might be damaged by the operations of the new plant.</p>
				<p><strong><em>How long can ownership be maintained?</em></strong>  Given that one cannot opt out of the effects of global warming (or breathing, for that matter), rights in the atmosphere are presumably perpetual.  Now that global warming has been identified, laws relating to greenhouse gases will need to exist for so long as a global warming threat remains.  In other words, indefinitely.</p>
				<p><strong><em>What can the owner do with the property? </em></strong> In the case of global warming, there are two property-related issues: what can be done to the atmosphere itself, and what can one do on one's property that would affect the atmosphere.  </p>
				<p>With regard to the first property question, traditional law is complex, but for current purposes suffice it to say that a "tenant in common" can exercise full property rights with respect to that property, subject to certain duties to the co-owner discussed below.  With respect to the second, the law is clearer, since laws relating to the regulation of polluters are well developed in many countries.  This assumes, however, that efforts to stem global warming are justified and addressed in the same way that traditional pollution issues have been addressed.</p>
				<p><strong><em>What can an owner not do with its property? </em></strong>A co-owner has various rights against a co-owner under traditional law, including not only the right to recover damages to the value of its property interest, but also the right to share in the income produced by that property (raising interesting questions as a global market in carbon credits begins to grow). Depending upon who is deemed to be the owner of what, it becomes fair to ask whether the owner of a Prius could have a monetary claim for damages against the owner of a Hummer (or its manufacturer) &ndash; and whether someone who doesn't own a car at all could bring a claim against the otherwise ostensibly &quot;green&quot; owner of the Prius.</p>
				<p><strong><em>Who has the power to restrict a property owner's rights?</em></strong>  Global warming obviously requires global remediation.  But there is no global body that represents everyone.  The United Nations is the closest approximation of such an authority, but the United Nations has no power to compel any member nation to become a signatory to a treaty, and enforcement mechanisms under existing treaties have al been weak to nonexistent.</p>
				<div class="calloutleft">
					<p>How does one value the impact of global warming?  Does it merit action, and mild sanctions, equivalent to penalties relating to excessive run off of fertilizers that cause algal blooms in waterways, or the more severe penalties that might relate to toxic wastes that can cause serious harm to health?  </p>
				</div>
				<p>Moreover, unlike water pollution or most air pollution, the legal basis for regulating emissions that lead to global warming might also be seen to be new and unique.  Global warming, after all, is not "local" to either the polluter or the polluted, nor is the point impact of greenhouse gases.  In fact, the deleterious effects of greenhouse gases do not arise until years later, when those gases become globally dispersed at high altitudes. </p>
				<p><strong><em>What are the limits, if any, on those restrictions?</em></strong>  How does one value the impact of global warming?  Does it merit action, and mild sanctions, equivalent to penalties relating to excessive run off of fertilizers that cause algal blooms in waterways, or the more severe penalties that might relate to toxic wastes that can cause serious harm to health?  Will the answer to this question given by someone that lives, for example, in coastal Bangladesh or Point Barrow Alaska, on the one hand, and Geneva, Switzerland or Denver Colorado, on the other, be likely to vary? </p>
				<p><strong><em>A framework for a solution: </em></strong> More effective solutions might be found if several core tenets relating to property rights were to be significantly modified.</p>
				<p><strong><em>Changing the rules: </em></strong> Those differences would result from making several radically different assumptions.</p>
				<ul>
					<li><strong><em>Deal with title and possession separately: </em></strong> Only the rights appurtenant to the possession of real property need be affected by new rules.  No change would be needed to the right to own land, or to exclusively enjoy the economic returns from permitted uses of that property, or the right to ultimately transfer that property.  But the uses to which that property could be put would become subject to new levels of regulation to a greater or lesser extent, depending upon the resource or concern at issue.  </li>
					<li><strong><em>Ignore political boundaries: </em></strong>  Resource boundaries are usually only coincidentally the same as political boundaries.  As a result, those that have an interest in a resource, those that are likely to affect a resource, and those that may be impacted by the abuse of that resource will only by accident fall neatly within the boundaries of any single governmental authority.  Consequently, existing legal authorities may be ill suited to make the best decisions relating to the resources that lie within their boundaries, or unwilling to collaborate on common solutions with neighboring countries, especially at times when relations between them are strained.  Similarly, they may not be the best motivated to enforce those decisions. </li>
					<li><strong><em>Invert the concept of ownership: </em></strong> There are already so many exceptions to the unfettered right of ownership that traditional concepts may be more misleading and harmful than instructive and useful. A given piece of property may already be subject to zoning restrictions, burning bans, watering bans, historic preservation restrictions, , and even gated community restrictions on whether children can visit for extended period of time, leaving very little freedom to the individual owner at all.</li>
					<p>At the same time, local opinions relating to rights of use in public as well as private land can vary dramatically.  For example, those that live in the Pacific northwest of the United States may feel that their right to lumber public lands cannot be taken away, because it would decrease job opportunities.  Others living in many western American states believe that their right to raise cattle on leased public lands should be inviolate, lest the character of their communities change.  Similarly, while it is considered to be perfectly acceptable to hike on ranched Bureau of Land Management land in Arizona, some ranchers that lease BLM land in New Mexico believe that it is within their rights to greet "trespassers" with a shotgun in hand.</p>
					<p>In fact, it might be more realistic and appropriate in a world supporting over 6 Billion people, and thousands more every day, to invert the concept of ownership.  Instead of stating that, "An owner may exercise all rights except for those that have been legally restricted," the law might better provide instead that, "An owner has only those rights that have been legally and locally recognized."  Such rights would never logically include the right to deplete or pollute groundwater, apply fertilizers or chemicals that can seep into aquifers are be carried into public waterways by runoff, cause air pollution, destroy scenic vistas, threaten endangered species, or curtail access to public lands, except to the extent that they had been explicitly negotiated and permitted in a non-discriminatory fashion.  And yet today, many of the actions just named can be taken by landowners to a greater or lesser extent without violation of current law. </p>
					<li><strong><em>Regard ourselves as co-owners: </em></strong>The uses that can be made or based upon land are having greater and greater general impact as population increases, and densities increase.  It is common to say that we hold land and resources "in trust" for those that are yet unborn, but such statements are at best expressions of good intentions by those that feel a moral responsibility.  Resources would be better protected &ndash; as would be the interests of our descendants &ndash; if future citizens were regarded as having current legal rights as co-owners, and if government was obligated to protect these rights, then much more meaningful resource protection systems might be designed and enforced.</li>
					<div class="calloutright">
						<p>There are already so many exceptions to the unfettered right of ownership that traditional concepts may be more misleading and harmful than instructive and useful.</p>
					</div>
					<li><strong><em>Applying these rules:</em></strong>  If these new rules were applied to the questions posed earlier, surprisingly different answers would be suggested, as well as quite different legal rules, authorities and remedies.</li>
					<li><strong><em>Who is the owner? </em></strong> Applying the above concepts to natural resources would result in a very different regulatory model.  For example, with respect to water pollution and aquifer depletion, the "owners" of that water would be those that live within the watershed in question.  No one would have the right to pollute the water in the watershed absent the permission of the watershed authority (which might be international rather than local, if the watershed spanned a national border), and all would have to agree on how the right to tap the underlying aquifer would be apportioned once desired usage exceeded its recharge capacity of the watershed.  In some cases, water sharing treaties already exist, such as the accord entered into in 1944 between Mexico and the United States, relating to the waters of the Colorado, Tijuana, and Rio Grande Rivers.</li>
					<p>With respect to air pollution, the owners would be those affected under normal climactic conditions.  Those living in Pennsylvania, for example, would therefore have legal rights to object to industrial pollution emanating in Ohio that could cause acid rain, and a legal mechanism would need to be provided to protect the rights of downwind interests (e.g., the legislature of Ohio would be bound to give due regard to a petition brought by the Pennsylvania environmental protection authorities, or those same authorities could bring suit in a Federal court to bring redress).</p>
					<p>But with respect to global warming, the same Pennsylvania citizen would look to a global authority for protection.  As earlier suggested, ownership of the atmosphere and the oceans would be universal, and legal mechanisms would be needed to permit anyone, anywhere, to protect their interests by bringing suit against a point source.</p>
					<p>Who would be included in the definition of "owner" of a certain resource would necessarily reflect the beliefs and values of the times and the societies involved, and the answers would therefore change and evolve over time.  For example, should residents of Tennessee have an equal say with those living in towns adjacent to redwood groves growing on federal land in California, when it comes to logging policies relating to the same trees?  Should the answer differ if those trees were growing on California state lands, despite the fact that redwoods can be regarded as part of our common cultural heritage?  And if citizens in Tennessee lay claim to heritage rights in California redwoods, should citizens of Portugal have an equal claim to their preservation as well?  Should it be possible to create a World Heritage Site &ndash; even without the consent of the country within which it is located &ndash; and to bind the host country to protect that site once it was created?</p>
					<li><strong><em>How long can ownership be maintained?</em></strong>  The temporality of ownership would be radically different, if the rights of future generations were to be legally recognized.   Perhaps just as "strict liability in tort" laws have extended liability in the United States to everyone in the production and distribution chain of consumer products, and U.S. "Superfund" laws render anyone that has handled hazardous wastes liable for cleanup costs, regardless of fault, future generations might be entitled to bring claims against then current owners of property that had been exploited in the past in order to remediate the damage done.  The effect would be to curb current abuses, lest the resale value of property be negatively impacted.</li>
					<li><strong><em>What can the owner do with the property?</em></strong>  Only that which is allowed under applicable statute and specific permits.  In effect, a better analogy would be to think of the owner as a lessee that is permitted to enjoy the use of the property subject to the reserved rights of the lessor.</li>
					<li><strong><em>What can the owner not do with its property?</em></strong>  No uses would be permitted that would (a) depreciate the value of the interests of co-owners of the same property,  (b) harm third parties, or (c) adversely affect the interests of future generations.  To the extent that impermissible uses were engaged in, those damaged could bring suit for recovery, whether the affected party was a neighbor, or in some cases a resident in a foreign country.  International treaties would secure these rights.</li>
					<li><strong><em>Who has the power to restrict a property owners rights? </em></strong> Because resource boundaries would rarely match political boundaries, new governmental bodies would be needed, with new powers.  Depending on the resources involved, those bodies would necessarily be local, regional, national and international.  Existing governmental units would presumably serve as, or appoint, representatives to international bodies, and would also be bound to enforce the decisions and laws enacted by those bodies, acting as their agents.</li>
					<li><strong><em>What are the limits, if any, on those restrictions?</em></strong>  Where the resources or impacts in question were international, these limits would presumably be defined in the treaties creating those bodies.</li>
				</ul>
				<p><strong><em>Case study:  a new approach to global warming:</em> </strong> Applying the approach above to global warming would yield a very different result from the Kyoto protocol.  The first step would of course be by far the most challenging:  a sufficient number of nations would need to enter into a treaty under which they agreed in advance to abide by the eventual decisions made, or at least be willing to ratify the treaty upon completion.  That treaty would provide for the following:</p>
				<ul>
					<li><strong><em>Binding application:</em></strong>  Because ownership in the atmosphere would be acknowledged to be universal rather than national, the legal authority of a global body would be appropriate and acknowledged.  The rules passed by that body would be binding upon all signatory countries, and new rules passed, and amendments to old rules, would be similarly binding.</li>
					<li><strong><em>Effective and representative governance: </em></strong> The global body would require a structure and rule set that was recognized as being representative, fair and effective.  This would provide a novel, radical and difficult challenge, but one that would be no more so than the founders of the United States faced when they sought to unite thirteen colonies with very different interests, and had no more recent European model to rely upon than that of ancient Greece.</li>
					<li><strong><em>Right of appeal: </em></strong> Just as the Founding Fathers balanced the powers of the Presidency against those of Congress, and constrained the authority of both through the Supreme Court, an appeals mechanism would be required to provide reassurance to those called upon to ratify participation, and avenue for relief in the case of actual abuse, and a vehicle for evolution and refinement of the equities of the new system through accretive interpretive case law.</li>
					<li><strong><em>Obligatory enforcement: </em></strong> The federal governments of member nations would be best equipped to function as the agents of the global body to enforce its rules.  As such, they would be subservient to the global body, and would not have authority to mitigate or make exceptions, except within such a framework as had been agreed upon by the global body.</li>
					<li><strong><em>International accountability:</em></strong>  The global body would have the power to sanction a failure of a national member to enforce the rules.  That sanction could be applied directly, perhaps through fines, or indirectly, perhaps by authorizing other members to impose trade sanctions.</li>
				</ul>
				<p><strong><em>Summary:</em></strong>  Is such a system workable?  The answer is difficult to predict.  Within the boundaries of an existing nation, such a plan could certainly be implemented, and in some respects already has been.  Internationally, the answer in the short term is likely to be "no," if past experience indicates the current limit of the willingness  of nations to subject themselves to the authority of international bodies.  </p>
				<div class="calloutleft">
					<p>Perhaps only if we begin a fundamental reexamination of property rights will we be able to agree upon the types of compromises required to permit our continued use and enjoyment of natural resources &ndash; and indeed this planet &ndash; on a sustainable, long-term basis.</p>
				</div>
				<p>The observation must naturally follow, however, that if the past must control the future, then the future may prove to be grim.  Ultimately, the threats to the interests of individual countries that may result from a failure to agree to such a system may outweigh the unprecedented cession of hegemony that the system described would require. </p>
				<p>One way to ease the way and hasten the day when global warming and other resource-related concerns can be effectively addressed may therefore be to begin to reexamine traditional attitudes towards property rights.  That reexamination would involve not just the rights of the owner of property to have unrestricted control over it, but of nations to have unconstrained authority over their lands and citizens.  If such a shift in our attitudes towards  the ownership of vital natural resources can be readjusted, I believe that our ability to successfully confront global warming will dramatically increase.   </p>
				<p>Perhaps only if we begin such a reexamination will we be able to agree upon the types of compromises required to permit our continued use and enjoyment of natural resources &ndash; and indeed this planet &ndash; on a sustainable, long-term basis. If this should indeed be the case, then the time to begin is certainly now.</p>
				<p class="center"><em>Comments? </em> Email: <script language="javascript" type="text/javascript">AuConAdd();</script></p>
				<p class="center">Copyright 2007 Andrew Updegrove</p>
