				<!-- ******************* -->
				<!-- FEATURE ARTICLE -->
				<!-- ******************* -->
				<h3>Standards and the Smart Grid:<br />The U.S. Experience</h3>
				<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
				<blockquote class="openingquote"><em><strong>Abstract:&nbsp;</strong>The managers of the aging United States electrical power grid have for some time planned to upgrade it to increase the quality of power on the grid and decrease the risks of power outages.  They have also realized the potential for "Smart Grid" technology to be deployed to turn the existing system into an interactive, two-way energy network that recruits home and business owners to create electricity from alternative energy during off-peak hours that can be sold back into the grid when demand is high.  Such a system can also conserve energy, lower its costs, and better absorb shocks that might otherwise bring down the system.  Growing concerns over national dependence on foreign oil, the increasing costs of permitting and constructing new power generation facilities, and the need to decrease national emissions of greenhouse gasses led Congress to buy into this vision in 2007, when it mandated the creation of a Smart Grid.  The current economic crisis provided a new administration in Washington with the opportunity to dramatically increase funding in the 2009 economic stimulus bill in order to speed the transition to a Smart Grid while producing thousands of new "green" manufacturing jobs.  The operations of a Smart Grid, however, will be dependent on the rapid selection, and often development, of hundreds of new standards of many types.  In this article, I review what a Smart Grid can achieve, the Congressional mandate and funding for the development of the standards needed to enable it, the process being used to select these standards, and the broad range of standard setting organizations that will provide them.</em></blockquote>
				<p><strong><em>Introduction:</em></strong> Since the advent of practical electricity distribution in the 1880s, private and public utilities have delivered electrical power to customers using increasingly complex technology. Over time, independently owned utilities became nationally interconnected and regulated networks, controlled and protected by vastly sophisticated computer networks constructed to monitor usage, settle accounts among power producers and purchasers, and redirect power as needed to meet demand and avoid catastrophic failures. According to one commonly repeated truism, the modern power grid is the most complex machine ever built.</p>
				<p>In the more precise and knowledgeable words of the National Academy of Engineering, the North American power grid is the "supreme engineering achievement of the 20th century." Unfortunately, this is no longer the 20th century, but the 21st, and a 2003 U.S. government report assessing the state of the nation's electric grid concluded that the last century's supreme achievement is now, "aging, inefficient, and congested, and incapable of meeting the future energy needs of the <em>Information Economy</em> without operational changes and substantial capital investment over the next several decades."<sup>1</sup></p>
				<div class="calloutright">
					<p>Until quite recently, the sophistication of domestic user-controlled power consumption technology has rarely exceeded that exhibited by a light dimmer switch</p>
				</div>
				<p>Moreover, the demands that are being placed on the grid today are not only quantitatively greater, but qualitatively different than before.  To the good, new enabling technologies and the Internet are presenting new opportunities for optimization, load leveling and storage that would have been impractical to consider only a few years ago.   At  the  same  time,  governments  are  realizing the degree to which such enabling technology can help realize broader policy goals as well.</p>
				<p>In the 21st century, the government architects of a revamped energy policy now wish to utilize the deployment of Smart Grid technology to help lower our dependence on foreign energy, meet international commitments to decrease our generation of greenhouse gases, and fuel job creation.  At the same time, the new infrastructure that government will help create will be expected to become more secure, more interactive, and even "self healing."</p>
				<p>Moreover, these expectations will be extending beyond the reach of the commercial boundaries of the traditional grid.  Until quite recently,  advances in controllable power technology ended where the power line enters the home.  Once beyond this commercial/domestic interface, electricity enters a "dumb" domain where the sophistication of user-controlled power conservation technology rarely exceeds that capabilities of a light dimmer switch.  Within too many businesses, and often even large enterprises, the reality has been not much different.</p>
				<p>Today, a number of developments and forces are breaking down this stark divide,  including soaring energy costs and the desire for greater national energy independence.  At the same time, the installation of individually owned alternative energy sources is becoming economically viable, and advances in information technology (IT) now permit the ebbs and flows of electricity (in either direction between producer and consumer) to be accurately measured and billed, allowing a customer's account to be adjusted up and down in real time.  Most recently, an ambitious and popular new administration has arrived in Washington just as a global economic crisis reached its peak, providing unprecedented public support for massive public funding of new initiatives intended to avoid economic collapse while creating jobs and infrastructure.</p>
				<p>This confluence of forces has provided the wherewithal for government to not only fund and support, but indeed mandate, the rapid national deployment of "Smart Grid" technology that will allow homes and businesses to become not simply on/off consumers of electric power, but sophisticated partners in increasing national energy efficiency, thus decreasing the need to build new centralized power production facilities, with all of their attendant costs, delays, and local and global environmental impacts, as well as decreasing national dependence on foreign (and especially oil and gas) energy sources.</p>
				<p>Within this vision of the near future, homes and businesses will become not just more efficient consumers of power, but suppliers as well, contributing excess power back into the grid produced by privately owned wind generators, solar arrays, fuel cells, and even hybrid cars, parked and plugged in for the night in the family garage.  Moreover, the systems installed by homeowners will be intelligent and powerful enough to monitor energy costs and allow a customer's home network to automatically shift power usage to off-peak, low cost times of the day, and sell stored power back into the system at the most favorable rates, during high demand peak consumption hours.  Meanwhile, the home system's software will interoperate with the utility's system to calculate and complete the underlying financial transactions.  The result: lower costs for utilities, due to avoiding the cost of building expensive new power plants, and lower electricity rates for all consumers.</p>
				<p>If it is successful in implementing this grand redesign of the American power system, the Obama administration will  not only provide the impetus to create what will become the most complex machine ever built without question, but will also make dramatic progress towards achieving multiple national and international policy goals.</p>
				<p>There are numerous daunting challenges that lie between the present and the successful completion of such a Smart Grid, but one of the most urgent is the need to assemble (and in many cases develop) the hundreds of standards of all kinds that will be needed to allow such a complex network to not only exist between commercial producers, but to extend its intelligence into hundreds of millions of homes and businesses as well.</p>
				<p>In this article, I will provide an overview of the Smart Grid initiative's origins and goals in the United States, and then review the types of standards that will be needed, the history of the U.S. government support for the creation of a Smart Grid, and the principal standard setting organizations (SSOs) that are actively engaged in the development and support of these standards.</p>
				<p><strong>I&nbsp;&nbsp;&nbsp;&nbsp;Origins and Evolution</strong></p>
				<p><strong><em>The Smart Grid concept:</em></strong> Retail electrical distribution had its origins in the United States in the 1880s, and witnessed one of the first great standards wars of the technical age.  On the one side was the direct current alternative that was advocated and first commercialized by Thomas A. Edison, and on the other,  the alternating current system originated by Nikola Tesla et al. and commercialized by George Westinghouse.  Over time, the advantages of AC current prevailed, notwithstanding the heroic, and sometimes even bizarre efforts of Edison to demonize alternating current.<sup>2</sup>  Rapid technical advances and the allure of practical electric light (another Edison innovation) led to the spread of electrical power in urban areas.  The reach of the electrical grid was extended over time, and as measured by square miles of coverage, dramatically so with the economic support provided by the passage of the Rural Electrification Act of 1936.</p>
				<p>Eventually, the various private and public networks became interconnected (and their components more standardized), and distribution and management of electrical power came to be regionally managed in a network of great sophistication.  Simultaneously, the costs and permitting challenges of building large new centralized generating facilities began to skyrocket.  More recently, with the rise of concerns over global warming, politically palatable fuel sources have become fewer in number, and the costs of those fuels and abatement technology has risen as well &mdash; along with demand.  Meanwhile, the fabric of the network itself has grown old and more fallible.</p>
				<p>For all these reasons, the need to upgrade the aging and over-taxed North American power grid has become increasingly evident.  As recently as the turn of the millenium, the near-term ambitions of industry and the U.S. government focused on the initial steps of a very expensive upgrade from a legacy, electro-mechanical system to a digitally based network.  For example, a major report issued by the United States Department of Energy (DOE) Office of Electric Transmission and Distribution in July of 2003 titled, <em>"Grid 2030" A National Vision for Electricity's Second 100 Years</em><sup>3</sup>, invited the reader to:</p>
				<blockquote>Imagine the possibilities: electricity and information flowing together in real time, near-zero economic losses from outages and power quality disturbances, a wider array of customized energy choices, suppliers competing in open markets to provide the world's best electric services, and all of this supported by a new energy infrastructure built on superconductivity, distributed intelligence and resources, clean power, and the hydrogen economy.</blockquote>
				<p>Once this new, superconducting backbone was in place, progress could begin to be made at the customer level.  But under the Grid 2030 vision, it would be almost thirty years before something recognizable as a complete Smart Grid would be in place:</p>
				<blockquote>Grid 2030 is a fully automated power delivery network that monitors and controls every customer and node, ensuring a two-way flow of electricity and information between the power plant and the appliance, and all points in between. Its distributed intelligence, coupled with broadband communications and automated control systems, enables real-time market transactions and seamless interfaces among people, buildings, industrial plants, generation facilities, and the electric network.</blockquote>
				<p>Despite the sobering fact that the first Major Finding of the <em>Grid 2030</em> report was that the existing electrical system was "aging, inefficient, and congested, and incapable of meeting the future energy needs of the <em>Information Economy</em>," the goals of government and industry rapidly became more ambitious at the local as well as the federal level.  Individual states, such as California, and regions, such as New England, began incorporating the type of long-term goals laid out in the <em>Grid 2030</em> report into their near-term goals for electrical system upgrades.  Simply decreasing the incidence and cost of power outages and increasing the quality of the power delivered were no longer regarded as being sufficient.</p>
				<p>Less than four years after the release of the Grid 2030 report, the DOE's Office of Electric Delivery and Energy Reliability delivered an ambitious new report and call to action that envisaged a far faster transition to the Smart Grid of the future.  In that statement, titled <em>A Vision for the Modern Grid</em>, the DOE's National Energy Technology Laboratory Modern Grid Initiative called for an interactive grid that would incorporate locally based alternative energy sources, in-home networks, and even plug-in hybrid automobiles into a single, interactive grid that would blend "the traditional centralized model with one that embraces distributed resources, demand response, advanced operational tools and networked distribution systems."<sup>4</sup></p>
				<p>The 2007 vision document called for a transition to this new grid focused on meeting six "key goals:"</p>
				<ul class="indent1">
					<li><strong><em>The grid must be more reliable</em></strong>. A reliable grid provides power dependably, when and where its users need it and of the quality they value. It provides ample warning of growing problems and withstands most disturbances without failing. It takes corrective action before most users are affected.<br /><br /></li>
					<li><strong><em>The grid must be more secure</em></strong>. A secure grid withstands physical and cyber attacks without suffering massive blackouts or exorbitant recovery costs. It is also less vulnerable to natural disasters and recovers more quickly.<br /><br /></li>
					<li><strong><em>The grid must be more economic</em></strong>. An economic grid operates under the basic laws of supply and demand, resulting in fair prices and adequate supplies.<br /><br /></li>
					<li><strong><em>The grid must be more efficient</em></strong>. An efficient grid takes advantage of investments that lead to cost control, reduced transmission and distribution electrical losses, more efficient power production and improved asset utilization. Methods to control the flow of power to reduce transmission congestion and allow access to low cost generating sources including renewables will be available.<br /><br /></li>
					<li><strong><em>The grid must be more environmentally friendly</em></strong>. An environmentally friendly grid reduces environmental impacts through initiatives in generation, transmission, distribution, storage and consumption. Access to sources of renewable energy will be expanded. Where possible, future designs for Modern Grid assets will occupy less land reducing the physical impact on the landscape.<br /><br /></li>
					<li><strong><em>The grid must be safer</em></strong>. A safe grid does no harm to the public or to grid workers and is sensitive to users who depend on it as a medical necessity.</li>
				</ul>
				<div class="calloutright" style="font-style:normal; line-height:1em;">
					<p><strong>Some U.S. Smart Grid Milestones</strong><br /><br />
					<strong><em>July, 2003:</em></strong> DOE releases <em>"Grid 2030" A National Vision for Electricity's Second 100 Years</em>. Report calls for a gradual transition to Smart Grid technology<br /><br />
					<strong><em>August 8, 2005:</em></strong> Passage of the <em>Energy Policy Act of 2005</em>, which includes new power grid reliability standards and alternative energy incentive funding<br /><br />
					<strong><em>March 2007:</em></strong> DOE releases <em>A Vision for the Modern Grid</em>, with call for an accelerated transition to a Smart Grid<br /><br />
					<strong><em>December, 2007:</em></strong> <em>Energy Independence and Security Act of 2007</em> (EISA) signed into law. NIST appointed to coordinate development of Smart Grid Standards<br /><br />
					<strong><em>June 2008:</em></strong> DOE workshop brings more than 140 government and industry representatives together to discuss EISA Smart Grid goals<br /><br />
					<strong><em>January 8, 2009:</em></strong> President- Elect Obama identifies transition to a Smart Grid as a high priority for hid administration<br /><br />
					<strong><em>March 19, 2009:</em></strong> FERC releases <em>Smart Grid Policy &mdash; Proposed Policy Statement and Action Plan</em> for public comment<br /><br />
					<strong><em>April 13, 2009:</em></strong> NIST names Dr. George W. Arnold as first National Coordinator for Smart Grid Interoperability<br /><br />
					<strong><em>April 28&ndash;29, 2009:</em></strong> Reston, Virginia workshop to select first Interoperability Frameworks standards attracts 400 participants<br /><br />
					<strong><em>May 18, 2009:</em></strong> Secs. Chu and Locke announce increased funding for development of Smart Grid Standards and demonstration projects, and announce selection of first 16 proposed standards<br /><br />
					<strong><em>May 19&ndash;20, 2009:</em></strong> Stakeholder Summit held in Washington, DC<br /><br />
					<strong><em>September 2009:</em></strong> Target date for release of Preliminary Roadmap for development of Interoperability Framework</p>
				</div>
				<p>Underlying this high level vision lurked daunting technical challenges, as hinted later in the same document.  The envisioned grid would be "self healing," and able to "handle problems too large or too fast-moving for human intervention."  It would also be capable of supporting two-way communications with remote devices, and of monitoring and analyzing remote conditions.  It would provide the tools to upgrade in-home systems in order to make possible new conservation programs that would "motivate consumers to be an active grid participant" and "include them in grid operations."</p>
				<p>The plan also sought to transition a system based and dependent upon traditional "spinning wheel" generating sources that distributed power where and as needed into a more diversified marketplace where businesses and consumers would buy "plug and play" devices that would provide ubiquitous power generation and storage capabilities to the grid, thereby lowering central power generation demands, decreasing power loss over long distance transmission, leveling peak power demands, and lowering national dependence on foreign energy sources.</p>
				<p>In order to achieve these complex goals, not only would new technologies need to be created and deployed into homes and businesses, but the more than 3,100 existing commercial power suppliers, most of whom currently employ proprietary IT systems (whether home grown or purchased), would need to upgrade their software and hardware to make them both compliant and interoperable.  Compared to the upgrade of the telecommunications system at a time when it was owned by a singe company (AT&amp;T), just the coordination aspects of such a task would be enormous.  Moreover, given the fact that the economic life of commercial scale generating facilities is 40 years, utilities would not wish to make expensive mistakes, especially if state regulators might not allow them to pass the costs of such failed experiments through to their customers via rate increases.</p>
				<p>While many of these new capabilities had been contemplated in the 2003 document, their wide spread implementation was slated to occur in later phases of a multi decade program.  Now, their implementation would be rolled out far sooner and  more aggressively.  Moreover, with typical American confidence in the power of free markets to work wonders, those envisioning the Smart Grid of the future believed that given the right technology, standards, and regulatory environment, the marketplace would do the rest.  Accordingly, the 2007 vision statement includes as one its seven "defining characteristics" the belief that:</p>
				<blockquote>[The] Modern Grid will enable markets to flourish. Open-access markets expose and shed inefficiencies. The Modern Grid will enable more market participation through increased transmission paths, aggregated demand response initiatives and the placement of energy resources including storage within a more reliable distribution system that is closer to the consumer.</blockquote>
				<blockquote>Parameters such as energy, capacity, rate of change of capacity, congestion, and resiliency may be most efficiently managed through the supply and demand interactions of markets. By reducing congestion, the modernized grid expands markets; it brings together more buyers and sellers. Consumer response to price increases felt through real time pricing will mitigate demand, driving lower-cost solutions and spurring new technology development. New, clean energy related products will also be offered as market options.</blockquote>
				<p><strong><em>Bush administration legislation:</em></strong> With increasing calls for energy independence and abatement of greenhouse gas emissions, and few easy ways to address either pressing need, Congress was moved to enact legislation that would both mandate as well as support a variety of energy-related initiatives, from new automotive fleet mileage caps to transitioning from incandescent light bulbs to more efficient lighting technologies by 2020.  Congress also largely bought into the DOE's latest plan for aggressively moving to Smart Grid technology, and included $100 million in funding per year to support the transition process.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Energy Independence and Security Act of 2007 (EISA):</em></strong> The result of the confluence of these forces was the passage of the aptly named <em>Energy Independence and Security Act of 2007</em>, which was signed into law by President George W. Bush on December 19th of that year.<sup>5</sup> Title XIII of that free-ranging package of initiatives<sup>6</sup> is simply titled "Smart Grids," and in the first section of that Title, Congress declared that it is the "policy of the United States to support the modernization of the Nation's electricity transmission and distribution system..[to become] a Smart Grid." The same section declares that the elements that "characterize a Smart Grid" are as follows:</p>
				<ul class="indent1">
					<li class="numbers">Increased use of digital information and controls technology to improve reliability, security, and efficiency of the electric grid.<br /><br /></li>
					<li class="numbers">Dynamic optimization of grid operations and resources, with full cyber-security.<br /><br /></li>
					<li class="numbers">Deployment and integration of distributed resources and generation, including renewable resources.<br /><br /></li>
					<li class="numbers">Development and incorporation of demand response, demand-side resources, and energy-efficiency resources.<br /><br /></li>
					<li class="numbers">Deployment of 'smart' technologies (real-time, automated, interactive technologies that optimize the physical operation of appliances and consumer devices) for metering, communications concerning grid operations and status, and distribution automation.<br /><br /></li>
					<li class="numbers">Integration of 'smart' appliances and consumer devices.<br /><br /></li>
					<li class="numbers">Deployment and integration of advanced electricity storage and peak-shaving technologies, including plug-in electric and hybrid electric vehicles, and thermal-storage air conditioning.<br /><br /></li>
					<li class="numbers">Provision to consumers of timely information and control options.<br /><br /></li>
					<li class="numbers">Development of standards for communication and interoperability of appliances and equipment connected to the electric grid, including the infrastructure serving the grid.<br /><br /></li>
					<li class="numbers">Identification and lowering of unreasonable or unnecessary barriers to adoption of smart grid technologies, practices, and services. <em>[Sec. 1301]</em></li>
				</ul>
				<p>While only the ninth element addresses standards by name, the viability of each of the other elements in fact relies on the existence and implementation of appropriate standards, often of many types.</p>
				<p>Among other mandates, Title XIII of EISA requires the formation of a Smart Grid Advisory Committee and a Smart Grid Task Force; requires DOE to carry out a program of research, development and demonstration; provides 20% matching funds for qualifying Smart Grid Investment Costs within that program; and assigns primary responsibility to the Director of the National Institute of Standards and Technology (NIST) to "coordinate the development of a framework that includes protocols and model standards for information management to achieve interoperability of smart grid devices and systems," the scope of which is to be "flexible, uniform and technology neutral."</p>
				<p>In order to meet the oxymoronic objective of "flexible uniformity," NIST is directed under EISA:</p>
				<blockquote>&hellip;to consider the use of voluntary uniform standards for certain classes of mass-produced electric appliances and equipment for homes and businesses that enable customers, at their election and consistent with applicable State and Federal laws, and are manufactured with the ability to respond to electric grid emergencies and demand response signals by curtailing all, or a portion of, the electrical power consumed by the appliances or equipment in response to an emergency or demand response signal, including through &mdash;<br /><br />(A) load reduction to reduce total electrical demand;<br /><br />(B) adjustment of load to provide grid ancillary services; and<br /><br />(C) in the event of a reliability crisis that threatens an outage, short-term load shedding to help preserve the stability of the grid;&hellip; <em>[Sec. 1305(b)(3)]</em></blockquote>
				<p>The legislation charges NIST with commencing development of the Framework within 60 days of the enactment of the legislation in collaboration with other named governmental units, and to:</p>
				<blockquote>&hellip;provide and publish an initial report on progress toward recommended or consensus standards and protocols within 1 year after enactment, further reports at such times as developments warrant in the judgment of the Institute, and a final report when the Institute determines that the work is completed or that a Federal role is no longer necessary. <em>[Sec. 1305(c)]</em></blockquote>
				<p>Congress appropriated $5,000,000 per year to NIST for the fiscal years 2008 through 2012 for this purpose, and also authorized the institution of rulemaking proceedings to:</p>
				<blockquote>&hellip;adopt such standards and protocols as may be necessary to insure smart-grid functionality and interoperability in interstate transmission of electric power, and regional and wholesale electricity markets. <em>[Sec. 1305d)]</em></blockquote>
				<p><strong><em>Obama administration legislation:</em></strong> While the endorsement in EISA for the creation of a Smart Grid as contemplated by the 2007 Vision document was strong, the funding provided was weak in comparison to the scope of the  task.  The likelihood of deploying a fully functioning Smart Grid even by 2030 might therefore have been in doubt, but for the election of President Obama in 2008 in the midst of a severe and spreading economic crisis.  The technically-oriented new president had already expressed his commitment to pursue a variety of energy-related initiatives, including implementing the Smart Grid.  On January 8, several weeks before his inauguration, President Elect Obama announced the main points of the recovery and investment plan that he would propose in response to the economic crisis, and identified the transition to a Smart Grid as a "high priority" element of his administration's move towards energy independence.  His ability to secure Congressional funding support to realize upon this initiative was augmented by the urgent need to address the seemingly imminent collapse of the global financial system.</p>
				<p>The new president's plan to address the economic situation included an ambitious government spending and jobs creation bill intended to upgrade the nation's crumbling infrastructure as well as promote new jobs-creating "green" industries.  When President Obama signed the American Recovery and Advancement Act of 2009 (ARAA) into law in February, it included a $4.5 billion appropriation to support the transition to a national Smart Grid.  The vision laid out in the 2007 document and already underway as a result of EISA could now proceed with robust funding support, as well as the credibility of a new and firmly committed administration behind it.</p>
				<p>The high degree of importance associated by the Obama Administration with the Smart Grid initiative was underlined by a landmark meeting the new president hosted in the White House on May 18, 2009.  In that meeting, Mr. Obama brought together over 70 CEOs and other industry leaders to enlist their support and commitment to creating and implementing the standards needed to ensure the successful implementation of the Smart Grid on the ambitious timeline called for by the President.</p>
				<p><strong><em>NIST Initiatives:</em></strong> NIST was already moving forward on the Interoperability Framework mandated by EISA, publicly supported Secretary of Commerce Gary Locke and DOE Secretary Steven Chu.  On April 13, Dr. George W. Arnold, a seasoned standards veteran and the former Chairman of the American National Standards Institute (ANSI) was named the first National Coordinator for Smart Grid Interoperability.  A series of multi-day workshops and high level meetings were held in April and May of 209 to draft an interim Interoperability Framework Roadmap intended to facilitate the completion of the Interoperability Framework in three phases.  Meanwhile, demonstration projects would continue apace to be approved and funded.</p>
				<p>On May 18, 2009, Secretary's Chu and Locke announced the public release for comment of the first 16 standards proposed for inclusion in the Interoperability Framework, based on the input gathered during a workshop held in Reston, Virginia on April 28-29 that drew 400 participants  They also announced that NIST would now have $10 million to support its work in the current fiscal year to accelerate completion of the Interoperability Framework, and that the matching funds allocated under EISA to support Smart Grid development and demonstration projects would be dramatically increased as well: from $20 to $200 million for the Investment Grant Program, and from $40 to $100 million for demonstration projects.<sup>7</sup></p>
				<p>The 16 standards offered for adoption in this first phase (see the Appendix to this article) were selected from the many Smart Grid-appropriate standards already in use.  They had been developed by a broad range of consensus processes, including four standards globally adopted by the International Electrotechnical Commission (IEC); three by the Institute of Electrical and Electronics Engineers (IEEE), an ANSI accredited SSO with a global membership; one American National Standard, approved by ANSI; four standards developed by a total of five consortia (two consortia collaborated on one standard) with global memberships; one standard by NIST, and one standard by a government supported laboratory.</p>
				<p>NIST's plans for the balance of the year include releasing a draft of the Preliminary Interoperability Roadmap in September, and the formation of a Smart Grid Panel of industry experts that will act as an advisory group to help define the standards that do not now exist, and identify the most appropriate, existing SSOs to enlist to rapidly fill the gap through an open, consensus process.</p>
				<p>In connection with creating the charter and  work plan for that panel, NIST has reviewed the government's experience working with another ongoing public/private effort to achieve an ambitious standards-dependent goal: the development and deployment of a national Electronic Health Record system.  As with the Smart Grid initiative, the move towards EHR's was endorsed by the previous administration and supported by Congress,  which mandated a move to EHRs and provided limited funding for that purpose.  As with the Smart Grid, the Obama Administration not only endorsed the EHR initiative, but included dramatically greater funding to support it in the 2009 economic stimulus bill, giving greater credibility to achieving a significant national implementation of EHRs by 2014.</p>
				<p>Like the Smart Grid initiative, the success of EHRs will be heavily dependent upon the universal implementation of a large number of standards (many of which do not yet exist) created by a wide range of SSOs.  In order to address this need, an Electronic Records Standards Panel, administered by ANSI, was formed in mid-decade.  That panel comprises a wide variety of experts from the multiple categories of stakeholders interested in the development, deployment and use of EHRs.  The EHR panel not only developed profiles of the standards that would be needed to enable EHRs, but actively supported working groups to develop new standards where needed.</p>
				<p>NIST expects its Smart Grid Interoperability Standards Panel to be formed in September at the commencement of the second phase of its development of the Interoperability Framework.  NIST will instruct the new panel to follow the EHR panels' lead in helping to determine which standards should be included in the final Interoperability Framework, but not to assist in their development.  That task will be allocated to existing SSOs.<sup>8</sup></p>
				<p><strong><em>The Interoperability Framework Roadmap</em></strong> The development of the Interoperability Framework will be completed under a Roadmap that is now in the process of preparation.  The work to be done and deliverables to be completed under the Roadmap are being divided into three phases.  The first phase will end with the finalization of the initial list of baseline standards drawn from those already in existence that directly (i.e., that relate to energy) or indirectly (e.g., that relate to IT network security) address Smart Grid needs, and the approval of the preliminary draft of the Roadmap itself.  In point of fact, there will never be a final draft, in the sense that the Roadmap by necessity will be a "living" document that will evolve over time as field needs and technology each continue to evolve after the Interoperability Framework itself enters maintenance mode.</p>
				<p>While standards will play a central role in enabling the Smart Grid, it is recognized that more will be needed to create the practical reality of a "plug and play" system. As a result, (and as contemplated by EISA), additional policies, models and other tools will be needed to describe architectures, implementation best practices and more.  Documents of this type will continue to be added during the second phase of the process described in the Roadmap.</p>
				<p>It is also recognized that standards often cannot (and in fact should not) be written in such detail as to ensure that interoperability is automatic.  In order to ensure compatibility in the field, especially for products that consumers will buy, conformity tests and a conformity testing infrastructure will be therefore be developed during the third Roadmap phase, so that product samples can be tested to determine whether they demonstrate interoperable performance.  Products that are tested to be compliant can then be appropriately branded to guide customers in their purchasing decisions.</p>
				<p><strong><em>The Interoperability Framework:</em></strong> The current scope of the framework represents the continuing evolution of the Smart Grid concept from the origins described above.  It addresses the six areas deemed to be most important to government and industry in creating a Smart Grid (the first four are of particular interest to the Federal Energy Regulatory Commission, which oversees the interstate bulk sale and transmission of electrical power):</p>
				<ul class="indent1">
					<li><strong><em>Demand Response,</em></strong> which (among other things) will seek to level the loads placed upon the electrical grid by allowing users and producers to react to price fluctuations and shape their behavior accordingly.<br /><br /></li>
					<li><strong><em>Wide-area situational awareness,</em></strong> which will seek to avoid power outages and brownouts.<br /><br /></li>
					<li><strong><em>Electric storage,</em></strong> which once again will level demands by allowing power to be stored when available in excess and then bled back into the grid when demand exceeds supply.  With the hoped-for proliferation of user-owned alternative energy devices, such as solar arrays, wind generators and hybrid card, the intelligent and reliable management of highly distributed storage will become especially important.<br /><br /></li>
					<li><strong><em>Electric transportation,</em></strong> which will become increasingly complex, as the number of power generating nodes becomes vastly more numerous, and the power produced by these nodes  becomes more variable.<br /><br /></li>
					<li><strong><em>Advanced metering infrastructure,</em></strong> which will provide the essential link between the home network and the Smart Grid.  This area subsumes a large number of standards, from wireless and powerline data links within the home and between the home and the network, data formats, enabling financial transactions, and much more.<br /><br /></li>
					<li><strong><em>Distribution grid,</em></strong> representing the further evolution of what is already an amazingly complex system to accommodate the vast clouds of increasingly complex data that will now flow across the country as (for example) a homeowner in Fresno, California opts to buy "green power" that is credited against the electricity fed into the grid by wind generator atop the lobster coop building on the waterfront of Vinalhaven, Maine.</li>
				</ul>
				<p><strong><em>Challenges:</em></strong> While the <em>Grid 2003</em> report focused in the near term on traditional "big engineering" goals, such as proving the feasibility of creating, and then deploying a national superconducting energy transmission backbone, the Interoperability Framework includes a strong focus on seemingly less ambitious, but in fact as, or more, challenging deployments.  For example, in order to allow the "markets to flourish" and for consumers to "participate in the grid" (including by having the ability to buy from "green" power sources, if they so desire, at higher per KW rates), home appliances and HVAC systems, hybrid cars, utilities and businesses will all need to be able to interoperably exchange data that would identify the source and price of power as it fluctuates moment by moment, and also support the real-time purchase and billing (or deferral of purchase) of that power until the parameters entered by the end user have been met.</p>
				<p>Similarly, a grid that for a century was increasingly based upon a tightly interconnected array of large, centralized, robust, well maintained generation facilities will now need to incorporate tens of thousands, and perhaps eventually millions, of power sources and power storage nodes, almost all of which will deliver variable (e.g., wind, solar and stored) rather than constant and controllable power.  Moreover, to a greater or lesser extent, these microgenerating sources will lie beyond the influence of those that must ensure the adequacy at every moment of the grid itself.</p>
				<p>There will be many IT challenges involved in implementing, managing and maintaining such a vast and sophisticated system even after the architectures, standards, and protocols that will enable it have been agreed upon.  These challenges will include dealing with the innate complexity of the system, processing and storing the vast amounts of data that will be produced, and ensuring the security of the entire system against cyber attack.  The security aspects are of particular concern, because not only will financial data need to be protected against criminals, but individual  homes that sell power back into the system will need to be protected against cyber attack by terrorists or national enemies.  Otherwise, the entire grid could be brought down if a sufficiently able and determined hacker or foreign power were to succeed in shutting down the alternative energy generators atop millions of American homes.</p>
				<p><strong>II&nbsp;&nbsp;&nbsp;&nbsp;Areas of Standardization</strong></p>
				<p>Given the complexity and scope of a Smart Grid, it is hardly surprising that a very broad range of standards will be involved in enabling one.  In some cases, the standards are already developed and widely deployed,  while in others they are only now being specified.</p>
				<p><strong><em>Starting points:</em></strong> The likelihood of standards actually existing for a particular Smart Grid purpose is a product of three primary dynamics: the state of the art in the technology in question, the length of time that commercial opportunities have existed to drive the development of standards to enable profitable sales of new products and services, and the degree to which general purpose standards can be repurposed to meet Smart Grid goals.</p>
				<p>An apt description of these three factors can be found in the area of advanced metering infrastructure.  In order for the individual homes to be interactively connected to the Smart Grid, a number of elements are needed, including the following:</p>
				<ul class="indent1">
					<li>A wired and/or wireless link between the home and the grid that conforms to recognized standard(s)<br /><br /></li>
					<li>Data schema and formats for the information that needs to be exchanged between the home network and the Smart Grid network in order to complete transactions, report on system conditions, and so on<br /><br /></li>
					<li>Common interface standards shared by "smart" appliances, thermostats and alternative generating and storage devices so that they "plug and play" with the Smart Grid when they are connected<br /><br /></li>
					<li>A home network capable of controlling and collecting data from appropriate electrical devices by wired or wireless means</li>
				</ul>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Linkage:</em></strong> Using the first element as an example, we find that a great deal of work has already been done in this area, with the result that there are already a variety of standards, technologies and vendors available to choose from in order to integrate the home into the Smart Grid.  This is in part because the "last mile" transmission of data has been a major issue for a variety of service vendors for some time, and especially for those that are in competition to sell broadband services (e.g., Internet and video access).  Because the telecom companies that owned the traditional "twisted pair" copper connection between the consumer and the telephone networks inexplicably declined for many years to offer a high bandwidth solution, there was a great incentive for others to come up with solutions, such as bundling Internet access with cable television packages, delivery of data via satellite dish, and even across the power line owned by the utility company, which also connected the consumer to a national grid.</p>
				<p>Other types of vendors also had a need to be able to exchange information with the consumer, and one of the industries that had a particularly strong desire for such a channel of communication happened to be electrical utility companies themselves, which desired to avoid the costs of sending meter readers, on a monthly basis and on foot, to read the physical meters attached to individual homes.  As a result, multiple vendors developed wireless hardware and software to permit the remote reading of meters on a "drive  by" or other basis, thus creating a linkage between the customer and her electric supplier that was, if desired, independent of the telecommunications network.</p>
				<p>Further, because the wireless industry has grown rapidly, the number of standards created to transmit wireless information has burgeoned.  Today, there are a wide variety of wireless standards that have been optimized for multiple purposes, each with its own sets of requirements and constraints relating to factors such as distance of transmission, amount and type of data to be communicated, and power limitations.  These standards are also created and maintained by a variety of well-established SSOs that each focus on a particular standard, or family of standards, such as the IEEE (WiFi), the BlueTooth SIG, and the NFC Forum (Nearfield Communications).  New organizations continue to be formed, such as the Wavenis Open Standards Alliance, which develops wireless standards specifically to communicate with devices such as smart electric meters.  And in many cases, the wireless standards developing SSOs (or their promotional affiliates, as in the case the WiFi Alliance) that exist already have well developed certification programs in place.  As a result, they and the adopters of their standards should be able to readily adapt to the conformance testing requirement that will later be required under phase III of the Interoperability Framework Roadmap.</p>
				<p>Accordingly, there are already multiple vendors with experience in cost effectively creating, installing and maintaining meters that can monitor and pass along information to an external network, as well as a rich ecosystem of SSOs capable of delivering the standards that they need.  At the same time, the IT industry is developing important supporting technologies, such as the ability to update software via powerline, wired or wireless connection.  The intelligence of electric meters will therefore be easier to upgrade after the first meters are installed.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Other elements:</em></strong> A similar picture can be found to a greater or lesser extent in the case of each of the other elements noted above.  For example, under the data category, a variety of XML-based data format standards have been developed by the Organization for the Advancement of Structured Information Standards (OASIS) for a number of purposes, including by intelligent meters, and to engage in transactions.  OASIS has already chartered additional working groups to create new standards that will be tailored precisely to the needs of in-home Smart Grid systems.</p>
				<p>In the area of controllers, much work has already been done for the commercial market, and LEEDS standards and certification for energy efficient building construction and management have gained great traction in the last several years.  And in the area of home networks, there are several active organizations developing standards and profiles for both wireless networks (including mesh networks, that link together the tags of multiple devices and sensors to pass along data) and powerline networks, able to transmit information using the in-wall electrical system of the home itself.</p>
				<p>As a result, NIST was able to select its first set of Interoperability Framework standards and related materials from an ample supply of standards developed by a wide variety of SSOs, taking into account the suitability of their processes and maintenance capabilities, as well the suitability of the standards themselves.  Going forward, the choices will narrow in some areas of need as the needs to be addressed become more cutting edge, but it seems that NIST currently expects that capable and appropriate SSOs are already in existence that will be willing to develop the totally new standards that will be needed to complete the Smart Grid.</p>
				<p><strong>III&nbsp;&nbsp;&nbsp;&nbsp;Players</strong></p>
				<p>Due to the number of industries involved in power generation, management, distribution and use, and the number of areas of standardization that will be invoked in constructing a Smart Grid, there are many public and private organizations with a valid interest in helping select and create the standards and related tools that will be added to the Interoperability Framework.  Due to the amount of federal money available in the short term, and the size of the market for Smart Grid related products and services in the long term, the number of companies interested in having an impact on the final composition of the Interoperability Framework is far greater.</p>
				<p>The following is an overview of some of the principal public bodies and private industry groups that are participating in the development of the Interoperability Framework, and the standards that will populate it.</p>
				<p><strong><em>Government:</em></strong> Many government agencies will be impacted by, and will wish to comment on, the Smart Grid.  For example, the Department of Homeland Security will be concerned over whether the Smart Grid will be properly secured against cyber attack, and EISA mentions Homeland Security by name as an agency whose input the Secretary of Commerce is to seek in preparing the reports to Congress required by Section 1302 of Title XIII.  Additionally, within a single agency (e.g., the Department of Commerce), some units (e.g., NIST) will have direct responsibility for Smart Grid matters.  Moreover, many government agencies and sub units are active members of the SSOs that have developed and will develop standards that will be included in the Interoperability Framework.  Accordingly, the following is only a high level sampling of the government bodies that have been directly and actively involved in developing and deploying the Interoperability Framework.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Department of Energy:</em></strong> Under EISA, the DOE has overall responsibility for the Smart Grid.  Individual parts of DOE are also mentioned by name, and given specific duties.  They are:</p>
				<ul class="indent1">
					<li><strong><em>The Office of Electricity Delivery and Energy Reliability (OEDER):</em></strong> OEDER is co-charged (with the Smart Grid Task Force) with reporting to Congress on a regular basis regarding "the status of Smart Grid deployments and any regulatory or government barriers to continued deployment." <em>[Sec. 1302]</em><br /><br /></li>
					<li><strong><em>Smart Grid Advisory Committee:</em></strong> This committee of eight or more individuals is to represent both the full range of Smart Grid technical expertise as well as all public and private stakeholders in advising the government on Smart Grid matters, including, "the evolution of widely-accepted technical and practical standards and protocols to allow interoperability and inter-communication smart grid-capable devices&hellip;" <em>[Sec. 1303(a)]</em><br /><br /></li>
					<li><strong><em>Smart Grid Task Force:</em></strong> This group is to be made up exclusively of federal employees of "the various divisions" of OEDER that have Smart Grid transition responsibilities.  Its mission is to ensure "awareness, coordination and integration" of Smart Grid matters, including "development of widely-accepted smart grid standards and protocols;&hellip;" <em>[Sec. 1303(b)]</em><br /><br /></li>
					<li><strong><em>National Institute of Standards and Technology:</em></strong> The Director of NIST is given, "primary responsibility to coordinate the development of a framework that includes protocols and model standards for information management to achieve interoperability of smart grid devices and systems" with the input of FERC, OEDER, the Smart Grid Task Force, the Smart Grid Advisory Committee, and "other relevant Federal and State agencies" and private industry <em>[Sec. 1305(a), (a)(1) and (a)(2)]</em></li>
				</ul>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Federal Energy Regulatory Commission (FERC):</em></strong> When Smart Grid standards are selected, FERC can incorporate compliance requirements based on those standards into regulations, as appropriate to Smart Grid needs, and consistent with its statutory authority.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Other Federal groups:</em></strong> A variety of government units have played visible public roles in the development of Smart Grid initiatives and reports, including the National Energy Technology Laboratory (which authored the 2007 Vision report), and the Lawrence Berkeley National Laboratory, which developed one of the standards included in the first list of standards recommended for inclusion in the Interoperability Framework.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Intergovernmental groups:</em></strong> The Federal agencies are also assisting the States and industry in working towards EISA goals.  For example, FERC and the National Association of Regulatory Commissions (NAURUC) have jointly sponsored the Smart Grid Collaborative as a forum within which federal and state regulators can discuss Smart Grid related matters of mutual interest.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Private Sector:</em></strong> There are a multitude of organizations of all types, and ad hoc alliances of organizations, that are providing input and deliverables to the Smart Grid project.  They fall into the following main categories:</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Non-governmental organizations:</em></strong> The government at times relies on non-profit laboratories and other organizations with expertise in energy related matters that provide advice and services to the government.  For example, NIST earlier contracted with the Electric Power Research Institute, Inc. (EPRI) to assist it in writing an interim report on Smart Grid architecture and a standards roadmap.  EPRI also supports a variety of other Smart Grid related projects and initiatives, including the EPRI Intelligrid Consortium and the Open AMI Task Force.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Standard Setting Organizations:</em></strong> The full range of SSOs are active in the creation of standards relevant to Smart Grids, and their role is a recognized and essential element of the Smart Grid transition envisioned by Congress in EISA.  Several SSOs (IEEE and NEMA) are mentioned by name in Title XIII, Section 1305(a)(2) of EISA).  About 15 of these SSOs will play an important role in supplying the standards that will  populate the Interoperability Framework.<sup>9</sup> These organizations include:</p>
				<ul class="indent1">
					<li><strong><em>De jure SSOs:</em></strong> Standard setting organizations that have open and inclusive eligibility policies, and conform to certain process norms such as decision by consensus and the availability of a right to appeal decisions are often referred as "<em>de jure</em>" bodies.  Both global standards organizations that accept membership at the national level and nationally accredited organizations of this type will supply standards for the Smart Grid.  They include:</li>
				</ul>
				<ul class="indent2">
					<li><strong><em>American National Standards Institute (ANSI):</em></strong> While ANSI is a non-profit membership organization and not a branch of government, it is internationally recognized as the de facto representative of the United States in standards matters, and as the official representative of the U.S. in international standards organizations such as ISO.  The United States government also frequently looks to ANSI for standards related guidance and assistance (e.g., ANSI administers the Electronic Health Record Standards Panel funded by Congress).  ANSI also accredits the process and rules of U.S. standards organizations, including many of those that have or will develop standards that will be selected for inclusion in the Interoperability Framework, and adopts standards developed by other SSOs as "American National Standards," one of which is included in the first 16 standards preliminarily accepted by NIST for the Smart Grid.<br /><br /></li>
					<li><strong><em>American Society of Heating, Refrigeration, and Air-Conditioning Engineers (ASHRAE):</em></strong> ASHRAE is an ANSI accredited standard setting organization with a long history (it was founded in 1894) and a large membership of individuals (51,000) that in more recent years has become international in membership and incorporated sustainability into its mission.<br /><br /></li>
					<li><strong><em>Institute of Electrical and Electronics Engineers (IEEE):</em></strong> While IEEE is headquartered in the United States and accredited by ANSI, it has a global membership of hundreds of thousands of individuals (corporations can join as well).  It hosts hundreds of working groups, include several that develop wireless standards.  Its standards are among the first to be preliminarily selected for the Interoperability Profile, and it is mentioned by name in EISA.<br /><br /></li>
					<li><strong><em>International Electrotechnical Commission (IEC):</em></strong> One of the oldest standards organizations in existence, with roots that extend back to the earliest days of the power industry.  Representation in the IEC is at the national level.  Its standards are among the first to be preliminarily selected for the Interoperability Profile.  Its standards cover a variety of Smart Grid relevant areas, such as IEC61850, substation automation architecture standard, and IEC 61970/61968, the Common Information Model (CIM), which provides common semantics to be used in converting data into information.<br /><br /></li>
					<li><strong><em>National Electrical Manufacturers Association (NEMA):</em></strong> NEMA is an ANSI accredited organization founded in 1926.  Unlike ASHRAE and IEEE, membership is at the corporate level.  Its members primarily manufacture products used in the generation, transmission and distribution, control, and end-use of electricity.</li>
				</ul>
				<ul class="indent1">
					<li><strong><em>Consortia:</em></strong> Many hundreds of standards development organizations have been formed over the last two decades in the IT, and to a lesser extent, the communications technology (CT) industries, typically with names such as "consortia," "alliances," "forums," "associations," or "SIGS" (for "Special Interest Group"); typically they are grouped together under the single categorical name of "consortia."  Most of these organizations have not sought <em>de jure</em> status via accreditation on  a national basis, although many have become well respected on an international basis.  Some consortia focus on a single standard, while others have become institutionalized, and host dozens, or more, simultaneous working groups at a time, usually within a single domain of recognized competence.  The membership in such organizations is sometimes national, but more typically international.  The standards they adopt are sometimes adopted by global standards organizations such as the IEC and the International Organization for Standardization (ISO).  Those certain or likely to have their standards included in the Interoperability Framework include the following:</li>
				</ul>
				<ul class="indent2">
					<li><strong><em>HomePlug Powerline Alliance (HLA):</em></strong> HLA is a consortium with membership at corporate level.  As its name suggests, the HLA develops standards that allow information to be transmitted via the in-wall wiring of a home or other building by any compliant device plugged into a wall outlet.  Other standards organizations are developing standards for the transmission of data, and even enable Internet connectivity, via external power lines as well.  Together with the ZigBee Alliance (see below), it has created a profile that was adopted by NIST as one of the first recommended Interoperability Framework standards.<br /><br /></li>
					<li><strong><em>Organization for the Advancement of Structured Information Standards (OASIS):</em></strong> OASIS is an international consortium with individual, corporate, government and academic members.  It develops standards with a focus on Internet commerce, but has a very wide scope within that category.  It is particularly well known for developing non-energy specific standards based on XML that will nonetheless  be useful for Smart Grid purposes.  It also hosts working groups that are targeted at Smart Grid implementations, such as its Energy Interoperability technical committee.<br /><br /></li>
					<li><strong><em>Zigbee Alliance:</em></strong> ZigBee is a corporate membership consortium developing and promoting a low-power, wireless standard for home network monitoring and control.  It is intended for a variety of products.  Together with the HomePlug Powerline Alliance, it created a profile that was adopted by NIST as one of the first recommended Interoperability Framework standards.</li>
				</ul>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Other Non-Profits:</em></strong> A variety of other groups representing every conceivable category of stakeholders in the energy ecosystem in every possible way (e.g., trade associations, lobbying groups, and so on) is taking an active interest in the Smart Grid, and in some cases in its standards as well.  There are also a large number of initiatives that have been launched to address specific elements of the Smart Grid, due to the amount of funding that has been made available by DOE and under EISA.  A few of the large number of the groups that have been formed expressly to address Smart Grid issues, or that have an interest in this area at the federal level (there are many other groups that are regionally or state focused), are as follows:</p>
				<ul class="indent1">
					<li><strong><em>The Advanced Grid Applications Consortium (GridApp):</em></strong> An organization formed in 2004 with support from the DOE Office of Electricity in conjunction with funding from member utilities.   GridApp provides a fast-track process for engineering development, demonstration and validation of selected high-impact technologies for the electric utility industry.<br /><br /></li>
					<li><strong><em>Edison Electric Institute (EEI):</em></strong> The trade association for shareholder-owned utility companies.<br /><br /></li>
					<li><strong><em>GridWise:</em></strong> Funded by DOE/OEDER, GridWise activities include the GridWise Alliance and the GridWise Architecture Council.<br /><br /></li>
					<li><strong><em>GridWise Alliance:</em></strong> A consortium of public and private members supporting Smart Grid goals.  The Alliance entered into a Memorandum of Understanding with the DOE in 2004, and submits comments to FERC and other government offices on behalf of its members on a regular basis.<br /><br /></li>
					<li><strong><em>GridWise Architecture Council (GWAC):</em></strong> The GWAC is a coalition whose members include representatives of utility and IT companies, universities and research organizations. It is mentioned by name in EISA Title XIII, Sec. 1305(a)(2) as an example of the organizations whose input the Director of NIST should solicit.  It recently released a report stating that the deployment of deployment of the Smart Grid could create as many as 280,000 jobs over the next four years.<br /><br /></li>
					<li><strong><em>North American Energy Standards Board (NAESB):</em></strong> NAESB is a trade association with a very large corporate membership.  It serves gas as well as electric utility companies.</li>
				</ul>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Ad Hoc groups:</em></strong> Various stakeholders in the marketplace have also joined to develop, or been commissioned by one industry participant to assist in the development, of input for Smart Grid development.  For example, IBM and the Carnegie Mellon Software Engineering Institute have created their own roadmap for the transition to the Smart Grid, called The Smart Grid Maturity Model.</p>
				<p><strong>IV&nbsp;&nbsp;&nbsp;&nbsp;Conclusions</strong></p>
				<p>The specification, development and adoption of standards to make the grand vision of a national Smart Grid a reality represents an unparalleled private-public challenge.  While there are technical antecedents for such an effort (most obviously, the upgrading of the telecommunications infrastructure), no such initiative in the past has involved so diverse a mix of industries, with such divergent realities and approaches to their respective businesses.</p>
				<p>Even the contemporaneous and equally ambitious effort to deploy electronic health records (EHRs) nationally pales in comparison, due to the fact that transition to a Smart Grid will require a larger number of standards to be agreed upon, and the technical areas in which those standards will operate are more diverse.</p>
				<p>But at the same time, the simultaneous launch of several complex and ambitious standards-dependent efforts by the Obama administration &mdash; in the Smart Grid, in health care and reimbursement, in open government, and in cybersecurity &mdash; provides a unique opportunity for the public and private sectors to leapfrog ahead in the collaborative discipline of complex standards development and deployment.</p>
				<p>Until now, government has usually played a largely passive role in the development of standards, allowing private industry to lead the way.  But private efforts are better suited to solving narrow and specific problems, leading to many standards, poorly coordinated.  Where complex problems must be urgently solved that must invoke hundreds of disparate standards to be identified, harmonized and, most importantly, broadly adopted, the private industry based process that develops consensus-based standards on an opt-in basis is less well suited to the task.</p>
				<p>Through these simultaneous efforts, both the government, through involvement by multiple agencies, and the private sector, through the hands-on experience of multiple industries, will benefit from a unique opportunity to experiment, through trial and error, to learn how government and industry can best work together to solve the technology-based challenges of today and tomorrow.  Given the breadth of approaches being taken, which range from the enormous financial incentives (and then penalties) that will be used to bring EHRs on to the desktops of private physicians, to the commercial opportunities presented by implementation of the Smart Grid, followed by eventual regulations, there will be many lessons to be learned.</p>
				<p>Not all of these efforts are likely to be successful, at least initially.  But when the dust settles, the benefits should be multidimensional in scope.  It is to be hoped that not only will the very significant investment of public and private funds yield up a Smart Grid that actually meets the many industry and policy goals that have been set out for it, but that the private and public sectors will have learned a new way to work together to solve complex, standards based challenges.</p>
				<p>If this latter goal is achieved, the lessons learned in the rapid rollout of the Smart Grid and the other ambitious standards-dependent initiatives of the Obama administration can, and presumably will, be applied in the future to the numerous and equally complex challenges that will certainly lie ahead.  If so, the development of this new public-private standards development partnership may prove to be more beneficial and long lasting than even the transition to a national Smart Grid.</p>
				<p class="center">Copyright 2009 Andrew Updegrove</p>
				<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
				<div class="hr" style="margin: 1em 100px 1em 100px;"></div><hr />
				<p><strong>End Notes</strong></p>
				<p><sup>1</sup> <a href="http://www.climatevision.gov/sectors/electricpower/pdfs/electric_vision.pdf">"Grid 2003" A National Vision for Electricity's Second 100 Years</a>, United States Department of Energy, Office of Electric Transmission and Distribution (July 20023), p iii., at http://www.climatevision.gov/sectors/electricpower/pdfs/electric_vision.pdf Unless otherwise noted, all on line resources cited were last accessed on June 4, 2009.</p>
				<p><sup>2</sup> Edison helped electrocute a hapless elephant at Coney Island in 1988 that had been "condemned" for killing three people, although the elephant's real crime appeared to have been its availability to be the subject for a publicity stunt. It's owner, Luna Park, needed publicity, and Edison needed a dramatic way to demonstrate the supposed dangers of alternating current. See, Topsy and the Standards War, at http://www.consortiuminfo.org/standardsblog/article.php?story=20061011081114524.</p>
				<p><sup>3</sup> <a href="http://www.climatevision.gov/sectors/electricpower/pdfs/electric_vision.pdf">"Grid 2030" A National Vision for Electricity's Second 100 Years</a>. U. S. Department of Energy Office of Electric Transmission and Distribution (July 2003), p. i at http://www.climatevision.gov/sectors/electricpower/pdfs/electric_vision.pdf The report summarizes the findings and results of the National Electric System Vision Meeting, Washington, D.C., held on April 2 &ndash; 3, 2003.</p>
				<p><sup>4</sup> National Energy Technology Laboratory, for the United States Department of Energy, Office of Electricity Delivery and Energy Reliability, <a href="http://www.netl.doe.gov/moderngrid/docs/A%20Vision%20for%20the%20Modern%20Grid_Final_v1_0.pdf">A Vision for the Modern Grid</a> (March 2007), at http://www.netl.doe.gov/moderngrid/docs/A%20Vision%20for%20the%20Modern%20Grid_Final_v1_0.pdf</p>
				<p><sup>5</sup> Energy Independence and Security Act of 2007, Title XIII, Sections 1301 &mdash; 1306</p>
				<p><sup>6</sup> The Smart Grid sections of the Act apparently mark the transition from core legislation to rider land. Title XIV is titled, "Pool and Spa Safety."</p>
				<p><sup>7</sup> <a href="http://www.energy.gov/news2009/7408.htm">Joint Press Release</a>, United States Depts. of Commerce and Energy, Locke, Chu Announce Significant Steps in Smart Grid Development," May 18, 2009, at <a href="http://www.commerce.gov/NewsRoom/PressReleases_FactSheets/PROD01_007985">http://www.commerce.gov/NewsRoom/PressReleases_FactSheets/PROD01_007985</a>. The Department of Energy later issued a <a href="http://en.wikipedia.org/w/index.php?title=Notice_of_Intent&amp;action=edit&amp;redlink=1#Notice%20of%20Intent%20(page%20does%20not%20exist)">Notice of Intent</a> and a draft <a href="http://en.wikipedia.org/wiki/Funding_Opportunity_Announcement#Funding%20Opportunity%20Announcement">Funding Opportunity Announcement</a> (FOA) its <a href="http://en.wikipedia.org/wiki/Smart_Grid_Investment_Grant_Program#Smart%20Grid%20Investment%20Grant%20Program%20(page%20does%20not%20exist)">Smart Grid Investment Grant Program</a> stating that grants will be provide in amounts of $500,000 to $20 million for smart grid technology deployments, and that grants of $100,000 to $5 million will be provided for the deployment of grid monitoring devices. Matching grants may cover up to 50% of a project's cost. A further $615 million may become available to support demonstrations of regional smart grids, utility-scale energy storage systems, and grid monitoring devices.</p>
				<p><sup>8</sup> See the interview of Dr. George W. Arnold that appears in this issue for further details on NIST's plans for facilitating the development of the additional standards needed to complete the Interoperability Profile.</p>
				<p><sup>9</sup> Arnold interview, <em>ibid</em>.</p>
				<div class="hr" style="margin: 1em 100px 1em 100px;"></div><hr />
				<h3>APPENDIX</h3>
				<h3>Initial Smart Grid Interoperability Standards<br />Framework, Release 1.0</h3>
				<table class="apr09table">
					<tr>
						<td><strong>Standard</strong></td>
						<td><strong>Application</strong></td>
						<td><strong>SSO</strong></td>
						<td><strong>SSO Type</strong></td>
					</tr>
					<tr>
						<td>AMI-SEC System Security Requirements</td>
						<td>Advanced metering infrastructure (AMI) and Smart Grid end-to-end security</td>
						<td><a href="http://osgug.ucaiug.org/default.aspx" target="_blank">OpenSG Users Group</a></td>
						<td>Consortium</td>
					</tr>
					<tr>
						<td>ANSI C12.19/MC1219</td>
						<td>Revenue metering information model</td>
						<td><a href="http://ansi.org/" target="_blank">American National Standards Institute (ANSI)</a></td>
						<td>De Jure</td>
					</tr>
					<tr>
						<td>BACnet ANSI ASHRAE 135-2008/ISO 16484-5</td>
						<td>Building automation</td>
						<td><a href="http://ashrae.org/http:/ashrae.org/publications/detail/16396" target="_blank">American Society of Heating, Refrigerating and Air-Conditioning Engineers (ASHRAE)</a></td>
						<td>De Jure</td>
					</tr>
					<tr>
						<td>DNP3</td>
						<td>Substation and feeder device automation</td>
						<td><a href="http://www.dnp.org/" target="_blank">DNP Users Group</a></td>
						<td>Consortium</td>
					</tr>
					<tr>
						<td>IEC 60870-6 / TASE.2</td>
						<td>Inter-control center communications</td>
						<td><a href="http://www.iec.ch/" target="_blank">International Telecommunications Commission (IEC)</a></td>
						<td>De Jure</td>
					</tr>
					<tr>
						<td>IEC 61850</td>
						<td>Substation automation and protection</td>
						<td><a href="http://www.iec.ch/" target="_blank">IEC</a></td>
						<td>De Jure</td>
					</tr>
					<tr>
						<td>IEC 61968/61970</td>
						<td>Application level energy management system interfaces</td>
						<td><a href="http://www.iec.ch/" target="_blank">IEC</a></td>
						<td>De Jure</td>
					</tr>
					<tr>
						<td>IEC 62351 Parts 1-8</td>
						<td>Information security for power system control operations</td>
						<td><a href="http://www.iec.ch/" target="_blank">IEC</a></td>
						<td>De Jure</td>
					</tr>
					<tr>
						<td>IEEE C37.118</td>
						<td>Phasor measurement unit (PMU) communications</td>
						<td><a href="http://ieee.org/web/standards/home/index.html" target="_blank">Institute of Electrical and Electronics Engineers (IEEE)</a></td>
						<td>De Jure/ANSI Accredited</td>
					</tr>
					<tr>
						<td>IEEE 1547</td>
						<td>Physical and electrical interconnections between utility and distributed generation (DG)</td>
						<td><a href="http://ieee.org/web/standards/home/index.html" target="_blank">IEEE</a></td>
						<td>De Jure/ANSI Accredited</td>
					</tr>
					<tr>
						<td>IEEE 1686-2007</td>
						<td>Security for intelligent electronic devices (IEDs)</td>
						<td><a href="http://ieee.org/web/standards/home/index.html" target="_blank">IEEE</a></td>
						<td>De Jure/ANSI Accredited</td>
					</tr>
					<tr>
						<td>NERC CIP 002-009</td>
						<td>Cyber security standards for the bulk power system</td>
						<td><a href="http://www.nerc.com/" target="_blank">North American Electric Reliability Corporation (NERC)</a></td>
						<td>De Jure/ANSI Accredited</td>
					</tr>
					<tr>
						<td>NIST Special Publication (SP) 800-53, NIST SP 800-82</td>
						<td>Cyber security standards and guidelines for federal information systems, including those for the bulk power system</td>
						<td><a href="http://www.nist.gov/index.html" target="_blank">National Institute of Standards and Technology (NIST)</a></td>
						<td>Government Agency Institute</td>
					</tr>
					<tr>
						<td>Open Automated Demand Response (Open ADR)</td>
						<td>Price responsive and direct load control</td>
						<td><a href="http://drrc.lbl.gov/" target="_blank">DOE/Berkeley Laboratory/Demand Response Research Center (DRRC) </a></td>
						<td>Government Agency Funded Laboratory</td>
					</tr>
					<tr>
						<td>OpenHAN</td>
						<td>Home Area Network device communication, measurement, and control</td>
						<td><a href="http://www.ucaiug.org/default.aspx" target="_blank">UCA International Users Group</a></td>
						<td>Consortium</td>
					</tr>
					<tr>
						<td>ZigBee/HomePlug Smart Energy Profile</td>
						<td>Home Area Network (HAN) Device Communications and Information Model</td>
						<td><a href="http://zigbee.org/" target="_blank">ZigBee Alliance</a><br /><a href="http://www.homeplug.org/home" target="_blank">Homeplug Powerline Alliance</a></td>
						<td>Consortium<br />Consortium</td>
					</tr>
				</table>