				<!-- ******************* -->
				<!--  FEATURE ARTICLE  -->
				<!-- ******************* -->
				<h3>Behind the Curve: Addressing the Policy Dependencies of a "Bottom Up" Standards Infrastructure</h3>
				<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
				<blockquote class="openingquote"><em><strong>Abstract:&nbsp;</strong>The United States government has historically relegated the role of standards development to a private-industry driven process, first, by creating its own "government unique" specifications for procurement purposes, and since 1995, by committing to utilize the standards developed in the private sector. The result is that the U.S. government is today largely dependent upon the standards that the private sector chooses to develop. With the increasing digitization of all things, the Obama administration will find that many standards needed to achieve its goals do not yet exist, and also that government does not have the tools to create them. In this article, I review the forces that led to this state of affairs, assess the resources the government already has available to address new standards needs, and make recommendations on how those resources, and others that can easily be created, could be integrated to provide much-needed standards solutions within reasonable time frames.</em></blockquote>
				<p><strong><em>Introduction:&nbsp;</em></strong>Barack Obama will unquestionably take office as the most technology savvy president in U.S. history, as demonstrated by his skillful use of Internet-based tools to build, fund, and promote his candidacy. Not surprisingly, the same awareness and comfort with technology that supported the Obama campaign also informed his platform as well. Early on, the then senator revealed a technology-based "<a href="http://www.barackobama.com/pdf/issues/technology/Fact_Sheet_Innovation_and_Technology.pdf">innovation agenda</a>"<sup>1</sup> in a position paper he fittingly announced at Google's main campus in Mountain View, California in November of 2007. The <a href="http://www.barackobama.com/2007/11/14/obama_unveils_innovation_agend.php">press release</a><sup>2</sup> issued by his campaign that day promised that under Obama's guidance, his administration would:</p>
				<blockquote>&hellip;connect and empower Americans through technology. The comprehensive plan will ensure the full and free exchange of information by protecting the openness of the internet and encouraging diversity in media ownership, create a transparent and connected democracy by opening up government to its citizens, modernize our communications infrastructure, employ technology and information to take on the challenges facing America, and improve our nation's competitiveness.</blockquote>
				<p>Obama's prepared remarks expanded on this vision, promising to:</p>
				<blockquote>&hellip;use technology to help achieve universal health care, to reach for a clean energy future, and to ensure that young Americans can compete &mdash; and win &mdash; in the global economy. If America recommits itself to science and innovation, we can lead the world to a new future of productivity and prosperity&hellip;. That's what we can do if we seize this moment.</blockquote>
				<p>The senator also promised to create a transparent government, open to citizen inspection and even direct participation, stating:</p>
				<blockquote>To seize this moment, we have to use technology to open up our democracy. It's no coincidence that one of the most secretive Administrations in history has favored special interests and pursued policies that could not stand up to sunlight. As President, I'll change that. I'll put government data online in universally accessible formats. I'll let citizens track federal grants, contracts, earmarks, and lobbyist contacts. I'll let you participate in government forums, ask questions in real time, offer suggestions that will be reviewed before decisions are made, and let you comment on legislation before it is signed. And to ensure that every government agency is meeting 21st century standards, I'll appoint the nation's first Chief Technology Officer.</blockquote>
				<p>More specifically, the Obama innovation agenda committed to guarantee the network neutrality of the Internet, preserve on-line privacy, and provide next-generation broadband access to all Americans (among other goals), and to apply technology-based solutions to a broad range of issues, from lowering healthcare costs to developing clean energy technologies, while simultaneously increasing national competitiveness, creating new jobs, reforming the patent system, and much more.</p>
				<p>Clearly, these were ambitious goals, presenting all of the usual challenges of gaining Congressional approval, committing funding, and successfully managing the through the details of implementation. But beneath the surface there were less obvious technical challenges relating to the new realities of the Internet. Unlike prior initiatives that could be implemented by and within a single government agency, providing transparency in government will require interoperability between the records and Web sites of all agencies and any popular technology used by citizens. Other elements of the plan will require interoperability among many government agencies, each of which today to a greater or lesser extent remains a distinct silo of systems and information.</p>
				<p>Similar challenges will arise outside of government systems, if the promise of driving up to $77 billion per year out of health costs through the conversion of paper-based systems to "electronic health records" is to be achieved. Realizing such a vision will require adoption of common standards-based technology not only by governmental agencies such as the Veterans Administration and the administrators of programs such as Medicare and Medicaid, but by millions of healthcare providers and their employers as well.</p>
				<p>Even in the area of clean technology and climate control, subtle challenges will arise. How will the results of such endeavors be measured, and their success or failure be determined? What thresholds of activity should be required to qualify for tax incentives? Who will provide the answers, develop the testing tools, perform the tests, and vouch for the results?	</p>
				<div class="calloutright">
					<p>The underlying reality is that the ambitious promises of the Obama administration will be dependent upon the rapid development and deployment of a great variety of standards and supporting infrastructure</p>
				</div>
				<p>In fact, almost all of the goals of the Obama innovation agenda will need to rely on the existence of a multitude of standards &mdash; performance standards, environmental standards, and accessibility standards, and standards to achieve interoperability across all types of real and virtual networks, between platforms, among data formats, and between citizen's mobile phones, laptops and desktops and their government's Web sites. Knowing whether these standards have been effectively implemented will often require the development of test suites, the recruitment of test labs and certification authorities, and the registration and administration of certification marks. Achieving the full promise of some aspects of the agenda will also require new ways of rating standards as well, in order to make eGovernment truly transparent, vendor neutral and universally accessible.</p>
				<p>But where will all of these standards come from, and who will decide which to use and which not? Who will develop those tests and administer them? How will the healthcare and telecom industries be persuaded to adopt the standards chosen? And how quickly can all of this be made to happen, lest the promises made languish unfulfilled?</p>
				<p>The underlying reality is that the ambitious promises of the Obama administration will be dependent upon the rapid development and deployment of a great variety of standards and supporting infrastructure. Unfortunately, the United States government is ill-equipped to meet this challenge, due to a variety of historical factors. In order to succeed in delivering on its promises, the Obama administration will therefore need to recognize this dependency immediately, and promptly begin planning ways to address the standards gaps that must be filled.</p>
				<p>In this article, I will examine the historical roots for this situation, review some of the realities that will challenge the achievement of discrete goals, identify the available tools at the Administration's disposal to meet these challenges, and finally recommend how these resources and new tools can be integrated to permit the Obama administration to achieve its technology-related goals.</p>
				<p><strong>I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The United States and Standards Development</strong></p>
				<p><strong><em>The rise of private standards development.</em></strong> Although the authority to determine standards of weights and measures is reserved to Congress under the very first Article of the U.S. Constitution, the involvement of government in standards other than weights and measures lagged the explosion of standards development that began in the late nineteenth century, notwithstanding the creation in 1901 of the National Bureau of Standards as a non-regulatory agency under the Department of Commerce. Since 1988, that Bureau has been known as the National Institute of Science and Technology (NIST), charged with the mission, "to promote U.S. innovation and industrial competitiveness by advancing measurement science, standards, and technology in ways that enhance economic security and improve our quality of life." But with an annual budget of under $1 billion, NIST's activities are limited to a variety of important, but discrete areas, only some of which are standards related.</p>
				<p>Instead, the development of standards in the U.S. evolved along two parallel tracks: one serving the needs of government procurement, and the other the increasingly voracious requirements of private industry for safety (elevators, boilers), construction (building codes), interoperability (screw threads, plumbing fixtures), performance standards (electrical, mechanical), and much more. These requirements were met by a rapidly expanding list of multipurpose trade associations and focused standards organizations created by industry itself, and government was increasingly happy to reference the output of such organizations in safety and other regulations in lieu of assuming the burden of determining such subject matter itself.</p>
				<p>With time, the proliferation of such organizations led to confusion and inconsistent quality of output. In response, five of these organizations (their current names are IEEE, ASME, ASCE, AIME and ASTM International) invited the Departments of War, Navy and Commerce to join them in creating a new organization they called the American Engineering Standards Committee. The mission of that organization was to act as, "impartial national body to coordinate standards development, approve national consensus standards, and halt user confusion on acceptability." Today, that organization is known as the American National Standards Institute (ANSI).<sup>3</sup></p>
				<p>Despite the involvement of three government agencies in the formation of ANSI, government procurement followed a different path, with government agencies drafting their own "government unique" specifications, upon which qualified contractors would then bid. The inevitable result was that while competition drove down the cost of goods built to private industry standards, the price of government-procured goods spiraled upwards, due to factors such as lack of cost consciousness in the creation of government specifications, and the lack of competition among bidders in contrast to the general marketplace.</p>
				<p>Congress eventually acted in 1995 to resolve this system by requiring government to use private industry standards in procurement whenever possible, thereby becoming increasingly able to buy commercial off the shelf (COTS) goods far more frequently rather than costly custom-built products. That legislation was called the National Technology Transfer and Advancement Act of 1995, 15 U.S.C. &sect; 3701 ("NTTAA"). Under the NTTAA, the Federal agencies were also required to actively participate in the activities of standards development organizations (SSOs), and to report annually to NIST on both their uptake of SSO standards as well as their participation in SSO activities, coordinated by a new Interagency Committee on Standards Policy.</p>
				<p>In 1998, the Office of Management and Budget (OMB) updated an already existing document called Circular A-119 to provide additional guidance to the Federal agencies on implementing the NTTAA.<sup>4</sup> In the years that followed, the conversion within the federal agencies from government-unique standards to industry standards was impressive.<sup>5</sup></p>
				<p><strong><em>Consequences of private standards leadership.</em></strong> While the NTTAA was successful from a budgetary point of view, it further reinforced the primacy of private industry in standards development. Today, the number of government personnel actively engaged in standards strategy and development is quite small, both as a percentage of all government agency personnel and as a percentage of all participants in SSOs. The result is that the problems that SSOs choose to address through the development of standards, and the processes they use to develop them, are largely determined by the profit opportunities perceived by vendors that for the most part fund, staff and drive the standards development process.<sup>6</sup></p>
				<div class="calloutright">
					<p>Rather than creating the standards itself, government continues with great frequency to simply reference the standards that private industry has developed to serve its own needs.</p>
				</div>
				<p>The willingness of government to look to industry for its standards development needs is hardly surprising, given the generally market-driven political philosophy that typifies American government policy in general, and the dislike for regulation exhibited by one party (and industry) in particular. As a result, government has come to rely on private industry standards not only to serve the products that the Federal agencies purchase, but also as the grist for a huge number of regulations and codes relating to safety, construction and other areas of governmental interest. Rather than creating the standards itself, government continues with great frequency to simply reference the standards that private industry has developed to serve its own needs.</p>
				<p>The relative detachment of the United States government from standards development manifests itself internationally as well as domestically. Unlike many nations that have agency or quasi-governmental bodies that represent them in global standards organizations such as the International Organization for Standards (ISO) and the International Electrotechnical Commission (IEC), the United States is represented directly in the former by ANSI, and indirectly by the same organization in the latter via the United States National Committee of the IEC. In neither case was ANSI officially appointed to that role by the U.S. government. Instead, in the absence of an official entity, ISO and IEC admitted the private industry organization that had become internationally recognized over time as the de facto voice of standardization in the United States by default.<sup>7</sup></p>
				<p>Not surprisingly, the model for standards development as it exists in the United States today (and some other countries) is usually referred to as a "bottom up" approach, in contrast to the "top down" methodology practiced in many other countries around the world, under which government plays a far more dominant role.<sup>8</sup></p>
				<p>There are several direct consequences of this "bottom up" model for standards development that are of current relevance:</p>
				<ol>
					<li><strong><em>Scope of interest:</em></strong> In contrast to "top down" governments, the U.S. agencies tend to interact with standards primarily as consumers, rather than as developers or strategists. As a result, the depth and breadth of government knowledge and sophistication regarding standards development and problem solving is less extensive.<br /><br /></li>
					<li><strong><em>Available solutions:</em></strong> Because government is less involved in deciding what problems to solve, it is largely dependent on what problems private industry decides to address. This limits standards solutions to those that can generate new opportunities and the highest profits for industry rather than solving the problems that might be of greatest national priority.<br /><br /></li>
					<li><strong><em>Stakeholder representation:</em></strong> Because standards development is time consuming and expensive, representation of non-vendor interests is comparatively light. The process in some SSOs can be opaque, and even secretive, making it less easy for other stakeholders to have visibility into how the standards that will ultimately affect them are developed.</li>
				</ol>
				<p>The net result today is that federal agency involvement with standards is predominantly at the consumer level, and Congressional awareness of standards in areas such as ICT (as compared to safety) is very low.</p>			
				<p><strong>II&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Challenges for the Obama Administration</strong></p>
				<p><strong><em>Limitations of the bottom up system:</em></strong> Unfortunately for the Obama administration, the nation's bottom up standards system is not likely to make timely delivery of the standards solution demanded by a variety of Obama's initiatives. There are additional reasons beyond those already noted for this conclusion, including the following:</p>
				<div class="calloutright">
					<p>Unfortunately for the Obama administration, the nation's bottom up standards system is not likely to make timely delivery of the standards solution demanded by a variety of Obama's initiatives.</p>
				</div>
				<p><strong><em>Standards silos:</em></strong> Standards continue to be set within individual SSOs that have variously broad or narrow domain competencies. But the problems that need to be solved are becoming increasingly complex, as a result of the convergence of multiple technologies and the linking of widely distributed systems via the Internet. A classic example of both dynamics in action is a "smartphone," which may include voice, audio, video, WiFi, Bluetooth, Web browsing, input/output jacks, GIS capability, and much more &mdash; every one of which is a standards-based capability. These standards come from different SSOs, each with a different intellectual property rights (IPR) policy that reflects that organizations specific tolerances for royalty payments and license terms, and each standard was originally developed to address a certain range of business cases that may quickly become outdated. Sometimes such standards can be fit together well, and other times not.</p>
				<p>The problem is compounded when multiple standards are available to perform the same task. Increasingly, vendors are finding it necessary to create entirely new SSOs for the purpose of creating "profiles" of standards to be implemented by multiple types of vendors (e.g., printer and cellphone manufactures) to perform tasks as ostensibly simple as wirelessly printing a snapshot from a cell phone. Many of the tasks called for by the Obama plan are far more complex.</p>
				<p><strong><em>Scoping and timing:</em></strong> Standards are developed primarily to serve the particular needs of those that contribute the time and money to develop them, and that hope to profit from them. Given the press of time and the need for vendor buy-in, the Obama administration will be dependent on existing SSOs to provide most of the standards needed to implement policy goals. First, however, the standards needed must be identified, the SSOs competent to develop them identified, and the members of those specific SSOs competent to develop them recruited to the task &mdash; a process that the government has only rarely engaged in in a systematic way before to achieve broad policy goals, as compared to fulfilling discrete procurement needs. Only when these tasks have been accomplished, however, can the actual development process begin, which will rarely take less than a year, and often significantly longer.</p>
				<p><strong><em>The need for "Civil ICT Standards:"</em></strong> Goals such as transparency in government cannot rely on garden variety standards that are value, but often not vendor, neutral. Independent of the opportunities for participation in government that the Internet can provide, the need to drive down government costs will continue to provide incentives to government to redeploy services (sometimes exclusively) via the Internet that have historically been provisioned in person. At the same time, an increasingly large percentage of the population each year is moving towards exercising its rights of free speech and free association on line, rather than in person. The result is that the exercise of our hard-won civil rights is increasingly occurring in the virtual, rather than the real world.</p>
				<p>In consequence, governments need to recognize the existence of what I refer to as "Civil ICT Rights," as well as the vital role that standards must play in guaranteeing that we may continue to enjoy our core civil rights in the increasingly digital world of the future. This subset of standards (logically, "Civil ICT Standards") will need to meet special criteria in order to perform their appointed task, and these criteria are not normally taken into account in the course of normal standards development. They include the following:</p>
				<ol>
					<li><strong><em>Platform neutrality:</em></strong> After hurricane Katrina, users of Apple computer software were unable to reach some government Web sites that hosted much needed emergency information, because those sites were accessible only to those using Internet Explorer. Citizens will expect to have the freedom to use whatever hardware and software they wish when they interact with government. Accordingly, government Web sites will need to be accessible via all popular operating systems and browsers, and will need to supply information in open data formats supported by popular software.<br /><br /></li>
					<li><strong><em>Cost:</em></strong> Obama's pledge is to provide on-line access to government to all citizens, automatically bringing the question of cost into play, and again raising the question of platform neutrality. With the declining cost of mobile Internet devices, "mini" laptops and other platforms running Linux and open source software, transparent government Web sites, records and on-line services will need to be served by standards that are free of the types of economic and licensing restrictions that would prevent them from being implemented in such lowest cost solutions.<br /><br /></li>
					<li><strong><em>Inclusivity:</em></strong> Government sites will also with to be sensitive to matters relating to gender, age, language skills, cultural diversity, literacy, numeracy, and IT literacy.<br /><br /></li>
					<li><strong><em>Accessibility:</em></strong> All citizens will need to be able to access government Web sites and obtain all government information, regardless of their physical handicaps.<br /><br /></li>
					<li><strong><em>Privacy and security:</em></strong> Individual information in government custody will need to be available to the individual and protected from unauthorized parties.<br /><br /></li>
					<li><strong><em>Archival storage:</em></strong> As government records become increasingly rare in paper form, it will become essential that data is stored in the open data formats that are most likely to be supported far into the future.</li>
				</ol>
				<p>Transparent government can only be achieved, therefore, by developing and implementing standards that meet the stringent Civil ICT Standards criteria described above. Today, however, there is no widely accepted set of criteria that describe how such a standard should be created, nor for the process values (e.g., who may participate, who may review the work in process, who may vote on the result, and so on) by which it is developed.<sup>9</sup></p>
				<p><strong><em>Lack of coherence:</em></strong> Commencing about 30 years ago, the IT industry began to opt out of the traditional standard setting infrastructure. That infrastructure had evolved over the previous 100 years to comprise hundreds of SSOs, most of which (in the United States) were periodically audited and accredited by ANSI as complying with certain process and IPR rules. In addition to voting United States interests in international organizations such as ISO, ANSI performed a variety of other functions within this global, de jure standards infrastructure, including facilitating the global adoption of U.S. originated standards by ISO and IEC.</p>
				<div class="calloutright">
					<p>Together, consortia today comprise a parallel universe of global (although often U.S. industry dominated) SSOs, many of which are as process oriented and prolific as their traditional peers.</p>
				</div>
				<p>The departure of IT industry (and to a lesser extent, the communications industry) was motivated in part by impatience with the often slow process of the traditional SSOs, and in part by a desire to exercise greater influence over development results. The solution some major IT vendors settled upon was to form new organizations that came to be most often referred to as "consortia." Initially, these organizations focused on a single standard, but with time, some broadened their work plans and became institutionalized. Together, they today comprise a parallel universe of global (although often U.S. industry dominated) SSOs, many of which are as process oriented and prolific as their traditional peers.</p>
				<p>Such consortia have proliferated hugely, and today number in the many hundreds. Together, they now develop the majority of the standards that fuel innovation in the IT, and to a lesser extent, the CT industry. But they also overlap, and frequently create competing standards (often deliberately, to serve the strategies of one vendor or group of vendors over another). Such coordination as exists among consortia, and between consortia and traditional SSOs, arises as a result of networks of variously formal and informal liaison relationships. Virtually all of this activity takes place outside the ambit of ANSI, and without any government involvement, except to the extent that individual agencies may participate as members.</p>
				<p><strong><em>Global dependencies:</em></strong> By definition, ICT standards call for global implementation. Due to considerations of cost and competition, it will make little sense to develop standards utilized only by government agencies, and no sense at all to require individual citizens to buy products that are based upon government-unique standards. Unfortunately, unlike individual countries (such as China) or regions (such as the European Union) where governments play a very active role in guiding the standards development process, the U.S. government has exercised, and is capable of exercising today, little influence over the development of standards. At best, it must therefore look to what efforts, complementary to administration goals, other governments may be exerting, and ride the coattails of those initiatives.<sup>10</sup></p>
				<p><strong>III&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Resources and Recommendations</strong></p>
				<p>How, then, is the Obama administration to be able to hit the ground running on its ambitious goals? Fortunately, while a coordinated "top down" standards-aware infrastructure is not in place, many (although not all) of the pieces necessary to take top down actions do exist. What is needed is a conscious plan to optimize and integrate these resources towards a common purpose, augmented as necessary with a few additional tools.</p>
				<p><strong><em>Available Resources:</em></strong> Any inventory of available resources, and how they might be optimized to support government standards-related policy goals, would include the following:</p>
				<p><strong><em>National Institute of Standards and Technology (NIST):</em></strong> As earlier noted, the greatest reservoir of expertise relating to standards and their implementation in useful technologies exists within this agency. Currently, NIST self-describes itself as follows:</p>
				<blockquote>
					<strong>NIST's mission:</strong><br />To promote U.S. innovation and industrial competitiveness by advancing measurement science, standards, and technology in ways that enhance economic security and improve our quality of life.<br /><br />
					<strong>NIST's vision:</strong><br />NIST will be the world's leader in creating critical measurement solutions and promoting equitable standards. Our efforts stimulate innovation, foster industrial competitiveness, and improve the quality of life.<br /><br />
					<strong>NIST's core competencies:</strong><br />
					<ol>
						<li>Measurement science</li>
						<li>Rigorous traceability</li>
						<li>Development and use of standards</li>
					</ol>
				</blockquote>
				<p>But under the hood of this rational summary, NIST pursues what at first glance appears to be an eclectic mix of roles, ranging from making available an astonishing array of "Standard Reference Materials" to be used by industry and science as direct comparison standards for purity and other physical qualities, to maintaining one of the world's most accurate clocks (a cesium-based timepiece upon which the nation's official time is determined), to administering the Malcolm Baldridge National Quality Award program.<sup>11</sup></p>
				<p>But within this broad range of activities there is broad competence in an equally broad area of standards, and close connections with industrial and scientific processes of all kinds. NIST is periodically called upon to support specific standards-related needs identified by government, such those involving Homeland Security.</p>
				<ol>
					<li><strong><em>Recommendation:</em></strong> Any effort to optimize government's ability to utilize standards to support policy goals should draw upon NIST's expertise and competencies. Given the breadth of its involvement with industry, express mission to support standards, and existing responsibility under the TTAA to compile and report data to Congress on standards adoption by all Federal agencies, NIST would provide the most logical existing agency to coordinate activities on a government-wide basis.</li>
				</ol>
				<p><strong><em>E-Government Act of 2002:</em></strong> This legislation seeks to achieve a variety of transparency in government goals that are similar to those called for in the Obama plan, including the following:<sup>12</sup></p>
				<ol>
					<li>To promote use of the Internet and other information technologies to provide increased opportunities for citizen participation in Government.<br /><br /></li>
					<li>To promote interagency collaboration in providing electronic Government services, where this collaboration would improve the service to citizens by integrating related functions, and in the use of internal electronic Government processes, where this collaboration would improve the efficiency and effectiveness of the processes.<br /><br /></li>
					<li>To promote the use of the Internet and emerging technologies within and across Government agencies to provide citizen-centric Government information and services.<br /><br /></li>
					<li>To make the Federal Government more transparent and accountable.<br /><br /></li>
					<li>To provide enhanced access to Government information and services in a manner consistent with laws regarding protection of personal privacy, national security, records retention, access for persons with disabilities, and other relevant laws.<br /><br /></li>
				</ol>
				<p>The e-Gov initiative has also created the Federal Enterprise Architecture, which includes a variety of Reference Models useful in enabling interoperability and achieving other goals of the Act.<sup>13</sup></p>
				<ol>
					<li><strong><em>Recommendation:</em></strong> The E-Government initiative is the logical foundation upon which to build for all purposes involving increasing transparency of government and direct participation by the public. While much work remains to be done, the legislative authority for a broader program of action than is currently underway already exists. Specific undertakings should include reviewing and updating the Federal Enterprise Architecture to meet the goals for transparency set forth in the Obama administration's agenda, and to require the use of Civil ICT Standards. The European Interoperability Framework should provide a valuable reference in this process.<sup>14</sup></li>
				</ol>
				<p><strong><em>Federal Chief Information Officers Council:</em></strong> This body was created during the Clinton administration via Executive Order. It's existence was codified into law under the E-Government Act of 2002, with the following purpose:</p>
				<blockquote>The Chief Information Officers Council is the principal interagency forum to assist CIOs in realizing their mandates to ensure the rapid and effective implementation of information management and information technology (IM/IT) solutions within each agency and to create a more results-oriented, efficient, and citizen-centered Federal government. The CIO Council works to improve agency practices related to the acquisition, modernization, use, sharing, and performance of Federal government information resources.</blockquote>
				<p>The CIO Council is charged with a number of interoperability-related goals. More specifically, it is also directed to work with NIST and the Administrator of the Office of Electronic Government and Information Technology (OMB):</p>
				<blockquote>&hellip;to develop recommendations on information technology standards developed under section 20 of the National Institute of Standards and Technology Act (15 U.S.C. 278g-3) and promulgated under Section 11331 of Title 40, and maximize the use of commercial standards as appropriate, including the following:</blockquote>
				<ol>
					<li>Standards and guidelines for interconnectivity and interoperability as described under section 3504<br /><br /></li>
					<li>Consistent with the process under section 207(d) of the E-Government Act of 2002, standards and guidelines for categorizing federal government electronic information to enable efficient use of technologies, such as through the use of extensible markup language<br /><br /></li>
					<li>Standards and guidelines for federal government computer system efficiency and security</li>
				</ol>
				<p>If it did not already exist, such a body would clearly need to be created in order to achieve the standards-related goals of the new administration.</p>
				<ol>
					<li><strong><em>Recommendation:</em></strong> The CIO Council provides the logical point of contact for all standards-based initiatives to be deployed throughout the Federal agencies. Such actions should be directed not only at increasing interoperability and the exchange of information, but also to use the procurement power of the government to further other standards related goals.</li>
				</ol>
				<div class="calloutright">
					<p>ANSI receives no government funding to underwrite its participation in, and economic support of, these global and regional bodies, and operates on a current annual budget of $22 million, derived from membership dues, sales of standards, and other activities.</p>
				</div>
				<p><strong><em>American National Standards Institute (ANSI):</em></strong> In addition to its international activities, ANSI provides a wide variety of important services in support of standards development and implementation, including auditing and certifying SSOs that apply to it for that purpose, hosting fora, conferences and committees, publishing standards and standards related materials, providing education and training services, and promoting the importance of standards and standards development. In addition to representing the United States directly in ISO, and indirectly in the IEC, it represents the United States regionally in the Pacific Area Standards Congress (PASC) and the Pan American Standards Commission (COPANT). ANSI receives no government funding to underwrite its participation in, and economic support of, these global and regional bodies, and operates on a current annual budget of $22 million, derived from membership dues, sales of standards, and other activities. It currently describes its mission as follows:</p>
				<blockquote>To enhance both the global competitiveness of U.S. business and the U.S. quality of life by promoting and facilitating voluntary consensus standards and conformity assessment systems, and safeguarding their integrity.</blockquote>
				<p>ANSI's membership comprises industry, non-profits (including scores of SSOs), government agencies, colleges and universities, international bodies, and individuals.</p>
				<p>While ANSI provides a central meeting place for the traditional standards development community of accredited SSOs, it does not currently fulfill that role for the hundreds of consortia that have sprung up over the last thirty years in the ITC industry, in part because of the reticence of these global organizations to appear even more U.S. centric than many of them are already perceived to be.</p>
				<ol>
					<li><strong><em>Recommendation:</em></strong> In the view of this writer, ANSI is currently underutilized by the United States government, which draws upon its expertise erratically rather than systematically. With minimal government assistance and funding ANSI could easily serve as a point of greater coordination between government and traditional SSOs to rapidly pursue administration goals. And, if specifically appointed to that task, ANSI could also serve as a designated point of contact with consortium SSOs seeking to become involved in specific government initiatives.<br /><br />
					The best current example for such a relationship between government policy goals and ANSI can be found in ANSI's administration of the Healthcare Information Technology Standards Panel (HITSP), under contract with the Department of Health and Human Services. The HITSP Web site describes its mission as follows:<br /><br />
					[T]o serve as a cooperative partnership between the public and private sectors for the purpose of achieving a widely accepted and useful set of standards specifically to enable and support widespread interoperability among healthcare software applications, as they will interact in a local, regional and national health information network for the United States.<br /><br />
					Since its foundation in October of 2005, HITSP has pursued an ambitious range of activities through multiple technical, business and liaison committees, and provides perhaps the best model for pursuing complex standards-related government policy goals with minimal funding.<sup>15</sup></li>
				</ol>
				<p><strong><em>OMB Circular A-119:</em></strong> As earlier noted, this Circular was amended to support the Technology Transfer and Advancement Act. More specifically, it, "establishes policies on Federal use and development of voluntary consensus standards and on conformity assessment activities." In the breach, however, its utility as a tool to prefer one industry standard over another has been limited, given the absence of any neutral way of rating the SSOs that create standards.</p>
				<ol>
					<li><strong><em>Recommendation:</em></strong> OMB A-119 was last amended in February of 1998. In order to maximize the achievement of policy goals such as transparency in government, it should be appropriately amended to track any policy related requirements designated by the new administration, particularly as regards citizen-facing federal agency Web sites and hosted applications.</li>
				</ol>
				<p><strong><em>The FTC and the DOJ:</em></strong> Together, these two regulatory agencies both enforce the antitrust laws, as well as assist the marketplace in understanding what activities are, and are not, permissible to engage in under those laws.  During the Bush administration, both the Federal Trade Commission (FTC), and to a lesser extent, the Department of Justice (DOJ) demonstrated a commendable interest in learning how to better support the pro-competitive effects of standards development and adoption.  Among other supportive activities, the FTC prosecuted companies such as Rambus Technologies for alleged abuses of the standards development process, and Chairman Deborah Platt Majoras and other members of her staff made public efforts to allay industry concerns over amending SSO rules to permit, or require, patent claim licensing terms at an earlier and more useful stage in the development process.  These actions have been very useful in allaying unnecessary concerns over the potential liability that might attach from participating in the standards development process, and have encouraged SSOs to amend their intellectual property rights policies to permit, or require, such <em>ex ante</em> disclosure of patent licensing terms.</p>
				<ol>
					<li><strong><em>Recommendation:</em></strong> Although the FTC is an independent agency, the Obama administration can and should encourage the Department of Justice to dedicate added resources to conducting additional hearings to gather input on the needs of the standards development community, to providing useful guidance to the standards development community regarding pro-competitive standards development practices, and to prosecuting those that abuse the standards development process, thereby undermining its integrity.</li>
				</ol>
				<p><strong><em>Patent and Trademark Office (PTO):</em></strong> The PTO (subject to the interpretive power of the relevant federal courts) determines what inventions can and cannot be patented. Over time, the rigor of its review of patent applications has varied, both as a result of court decisions and acts of Congress, as well as in reaction to the amount of funding available to deploy a sufficient number of patent examiners to the task of vetting the ever-increasing flood of patent applications.</p>
				<p>A special challenge has been presented in recent history by the decision to permit the patenting of inventions implemented in software. Such inventions are by their nature harder to deal with, not only due to their virtual and sometimes abstract nature, but also due to the increased difficulty of searching for the "prior art" represented by earlier inventions that, if known, would result in the rejection of such inventions. This, combined with a limited time budget for the processing of each patent application, a shortage of patent examiners with the needed experience, and standing pressure to approve, rather than disapprove, new applications has resulted in an industry-wide consensus that software patents are too easy to get, and too difficult and expensive to successful challenge.</p>
				<p>While recent court decisions have made patents both harder to obtain and easier to challenge, a patent reform bill that would be more effective and far-reaching has thus far failed to pass both houses of Congress. A call for patent reform was included in the Obama innovation and technology policy proposal.</p>
				<ol>
					<li><strong><em>Recommendation:</em></strong> Poor quality patents present special problems for the development and adoption of standards, because their proliferation makes it harder for SSOs to do what is already very difficult: provide the marketplace with standards that can be implemented on a reasonable and non-discriminatory (and ideally free) basis. The recent increase in the number and activity of companies the sole business of which is to acquire and assert patents in order to reap licensing fees (so-called "patent trolls") has exacerbated this problem, as idle patents that might otherwise lie unnoticed on corporate shelves come into the possession of companies with the budgets and business model to assert them.<br /><br />Besides tightening up the patent system in general, the Obama administration should encourage, and fund, the reexamination of questionable patents claims asserted against standards implementers, especially when those patents are asserted after the marketplace has already become "locked in" through wide implementation of the standard in question.</li>
				</ol>
				<div class="calloutright">
					<p>In order to avoid slowing down the achievement of administration goals, two new mechanisms would be useful for informing and coordinating these efforts, one internal, and one external to government.</p>
				</div>
				<p><strong><em>New Resources:</em></strong> While clearly there are a variety of resources already in place that can be harmonized and optimized to support the identification, development and adoption of standards, they are not likely to be sufficient for the task of rapidly enabling the implementation of complex technology-based policy goals. In order to avoid slowing down the achievement of administration goals, two new mechanisms would be useful for informing and coordinating these efforts, one internal, and one external to government. They are as follows:</p>
				<p><strong><em>Standards Advisory Council (SAC):</em></strong> Although existing IT staff at various agencies may be knowledgeable regarding specific types of standards at the technical level, they would not be expected to be as well versed regarding the social and other dimensions that a policy-aware standards agenda should incorporate. In fact, in the case of transparency in government, decisions remain to be made regarding important issues such as platform neutrality, ensuring the availability of open source as well as proprietary alternatives, privacy and security. Before specific standards implementation decisions can be made, a framework for selecting them based upon such decisions will be needed. While the process of developing appropriate criteria is well advanced elsewhere, the dialogue on such matters is only now beginning in the United States, and at the state level.</p>
				<p>In order to rapidly address issues such as these, a new advisory group will be needed that brings together not only those versed in technical matters, but also advocates of open source software, open information, and open standards, and experts in related domains, such as intellectual property and best practices in standards development. Such a group would advise the new Chief Technology Officer that Obama has announced he will appoint, and serve as a resource to the CIO Council and Congressional staff.</p>
				<p><strong><em>Standards for Standards Body:</em></strong> It will be easier to set the criteria for Civil ICT Standards and revise OMB Circular A-119 than it will be for an agency CIO to know a qualified standard when she sees one. In order to support policy goals, therefore, a new type of private sector body will be needed that can set "standards for standards" and for the processes that create them. Such a body would perform the following functions:</p>
				 <ol>
					<li>Through consensus, create criteria for open standards processes in general, and more strict criteria for creating Civil ICT Standards. The existence of a neutral, trusted developer and custodian for a single set of criteria, referenced by governments globally, will help avoid the type of fragmentation in public procurement that would make life difficult for vendors, and make it difficult or impossible for interested governments to find standards that meet their policy needs.<br /><br /></li>
					<li>Certify the processes of the SSOs that meet the criteria established, thus providing not only a trusted third party verification mechanism, but also an incentive for SSOs generally to improve the quality of their processes.<br /><br /></li>
					<li>Maintain a registry of standards produced by certified SSOs, thus facilitating the creation of government interoperability frameworks.</li>
				</ol>
				<p>Such a body could be formed quickly and maintained inexpensively. Its governance structure should ensure that the interests and opinions of all categories of stakeholders would be heard and taken into account.<sup>16</sup></p>
				<p><strong>IV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Summary</strong></p>
				<p>The increasing importance of the Internet to almost everything that government does serves to expose the dependencies of government on a standards development, adoption, testing and certification infrastructure that has historically been beyond its control. Unless the United States government develops strategies to address its reliance on this largely private sector dominated infrastructure, government will increasingly find that it will be blocked, or at least delayed, in the fulfillment of a variety of technology-dependent policy goals.</p>
				<p>While it should be unnecessary to radically depart from the bottom up reality that has evolved and predominated standards development in the United States for over a hundred years, it will be necessary for government, and particularly for the Executive Branch, to optimize and harmonize existing government resources, as well as provide incentives, through the exercise of the power of procurement, to the private sector to help achieve standards related policy goals.</p>
				<p>The Obama administration finds itself on the cusp of this reality, as it hopes to achieve significant technology-based policy goals. Only by identifying existing dependencies and acting quickly and creatively to address them will it be able to achieve its goals in timely fashion, and not be impeded by the lack of standards that are both technically sufficient, and policy appropriate.</p>
				<p class="center">Copyright 2008 Andrew Updegrove</p>
				<p>End Notes</p>
				<p><sup>1</sup> <a href="http://www.barackobama.com/pdf/issues/technology/Fact_Sheet_Innovation_and_Technology.pdf">Barack Obama on Innovation and Technology</a>, November 14, 2007, at http://www.barackobama.com/pdf/issues/technology/<br />Fact_Sheet_Innovation_and_Technology.pdf. This, and all other on-line resources cited in the notes to this article were accessed the week of November 24, 2008.</p>
				<p><sup>2</sup> <a href="http://www.barackobama.com/2007/11/14/obama_unveils_innovation_agend.php">Obama Unveils Innovation Agenda at Google</a>, November 14, 2007, at http://www.barackobama.com/2007/11/14/<br />obama_unveils_innovation_agend.php</p>
				<p><sup>3</sup> For a brief history of ANSI and the evolution of its mission over time, see <a href="http://www.ansi.org/about_ansi/introduction/history.aspx?menuid=1">ANSI: Historical Overview</a>, at http://www.ansi.org/about_ansi/introduction/history.aspx?menuid=1</p>
				<p><sup>4</sup> OMB, Federal Participation in the Development and Use of Voluntary Consensus Standards and in Conformity Assessment Activities, Circular A-119, Revised (Feb. 10, 1998), <a href="http://www.whitehouse.gov/OMB/circulars/a119/a119.html">available at</a> http://www.whitehouse.gov/OMB/circulars/a119/a119.html.</p>
				<p><sup>5</sup> NIST reported that through 2001, Federal agencies had already replaced at least 1,412 government unique standards with non-government standards, and also used thousands of additional non-government standards. NIST also reported that in 2001, Federal agencies actively participated in at least 847 separate standard setting activities, and collectively were known to still utilize only 54 government unique standards. The five Federal agencies that then used the largest numbers of standards (Department of Energy, Health and Human Services, Housing and Urban Development, Department of Transportation and the National Aerospace and Science Administration) collectively utilized over 3,071 voluntary consensus standards in their procurement activities, and had directed 1,270 of their employees to participate in the activities of SSOs. Kevin McIntyre and Michael B. Moore, NIST, Fifth Annual Report to the Office of Management and Budget on the Implementation of Public Law 104-113 and OMB Circular A-119 ( Oct. 2002).</p>
				<p><sup>6</sup> For a more in depth review of modern U.S. standards policy, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/jan05.php#feature">A Work in Process: Government Support for Standard Setting in the United States: 1980 &ndash; 2004</a>, ConsortiumInfo.org, Consortium Standards Bulletin, Vol. IV, No. 1, January 2005, at <a href="http://www.consortiuminfo.org/bulletins/jan05.php#feature">http://www.consortiuminfo.org/bulletins/jan05.php#feature</a></p>
				<p><sup>7</sup> The United States is directly represented in the International Telecommunication Union (ITU), which is a treaty organization operating under the aegis of the United Nations.</p>
				<p><sup>8</sup> Proponents of the U.S. model point out that it tends to be more market responsive and nimble, while critics contend that it can be more susceptible to vendor influence, less socially aware, and more prone to lead to duplicative standards. A classic and much studied example of the two systems and their outcomes involves "2G" wireless telephony. In the U.S., the government allowed the market to decide which standards-based technology would ultimately win out among four contenders, while Europe chose to annoint one approach from the beginning. See, for example, Gandal, Neil, Salant, David, and Waverman, Leonard, <a href="http://www.ictregulationtoolkit.org/en/Publication.2807.html">Standards in Wireless Telephone Networks</a>, Telecommunications Policy, Volume 27, Issues 5-6, June-July 2003, Pages 325-332 at http://www.ictregulationtoolkit.org/en/Publication.2807.html</p>
				<p><sup>9</sup> For a more in depth description of this topic, see, Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/feb08.php#feature">A Proposal to Recognize the Special Status of "Civil ICT Standards,"</a> ConsortiumInfo.org, Standards Today, Vol. VII, No. 2, February &ndash; March 2008, at http://www.consortiuminfo.org/bulletins/feb08.php#feature</p>
				<p><sup>10</sup> Perhaps the most impressive effort in this regard is the work of the unwieldy-named Interoperable Delivery of European eGovernment Services to public Administrations, Business and Citizens, invariably referred to by its acronym: IDABC. The IDABC is now in the process of finalizing the third draft of a comprehensive pan-European IT plan known as the European Interoperability Framework for pan-European Government services (EIF). Information on this impressive document and its origins can be found <a href="http://ec.europa.eu/idabc/en/document/2319">here</a>: http://ec.europa.eu/idabc/en/document/2319</p>
				<p><sup>11</sup> The many committees, services, laboratories and activities of NIST are indexed at its <a href="http://www.nist.gov/">home page</a>: http://www.nist.gov/. For a light hearted appreciation of the bewildering array of Standard Reference Materials that NIST has seen fit to make available, see my previous Consider This piece, titled <a href="http://www.consortiuminfo.org/blog/considerthis.php?ct=29">For Your Reference</a>, ConsortiumInfo.org, Consortium Standards Bulletin, Vol. VI, No. 6, June 2005, at http://www.consortiuminfo.org/blog/considerthis.php?ct=29</p>
				<p><sup>12</sup> The eGov initiative Web site can be found <a href="http://www.whitehouse.gov/omb/egov/">here</a>: http://www.whitehouse.gov/omb/egov/. The complete text of the Act can be found <a href="http://frwebgate.access.gpo.gov/cgi-bin/getdoc.cgi?dbname=107_cong_public_laws&amp;docid=f:publ347.107.pdf">here</a>: http://frwebgate.access.gpo.gov/cgi-bin/getdoc.cgi?dbname=107_cong_public_laws&amp;docid=f:publ347.107.pdf</p>
				<p><sup>13</sup> The Web page for the FEA, and links to the various Reference Models and other resources, can be found <a href="http://www.whitehouse.gov/omb/egov/a-1-fea.html">here</a>: http://www.whitehouse.gov/omb/egov/a-1-fea.html</p>
				<p><sup>14</sup> See Note 11.</p>
				<p><sup>15</sup> The specification working groups (13 as of this writing) can be viewed at the HITSP <a href="http://www.hitsp.org/">Web site</a>, at http://www.hitsp.org/. Additional <a href="http://www.hitsp.org/background.aspx">background</a> on its formation can be found at http://www.hitsp.org/background.aspx</p>
				<p><sup>16</sup> The timing for the formation of such an entity is particularly opportune, as there is great dissatisfaction with the failure of ISO/IEC JTC1 in the wake of the very contentious and controversial adoption process by that committee of ISO/IEC 26500, an open document format standard based on OOXML, a Microsoft specification. Four emerging country National Bodies filed appeals in response to the ultimate adoption of OOXML. Those appeals were rejected, exacerbating already inflamed emotions.</p>