				<!-- ******************* -->
				<!--   FEATURE ARTICLE   -->
				<!-- ******************* -->
				<h3>"Openness" and the Pursuit of Knowledge</h3>
				<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
				<blockquote class="openingquote"><em><strong>Abstract:&nbsp;</strong>Until the advent of the Internet, the acquisition of knowledge was a linear process, with the discoveries of one innovator only becoming available to be built upon by the next after being reported to, evaluated by, and eventually published in a journal of repute. Similarly, the process of creation of collaborative works was largely limited to individuals that were physically in one location, due to the need for real time communication. Not surprisingly, the legal rules, tools and practices that evolved over time reflected this sequential and insular process of creation, tilting the balance of rights towards the creators, in part because the opportunities for societally beneficial, real-time sharing were limited. Now that those limitations have fallen away, creators of all types are voluntarily relaxing their ownership rights in order to mutually enjoy the benefits of greater access, faster development, and more useful collaboration. In this article, I review some of the many ways and domains in which this revolution is occurring, highlight some of the legal tools that innovative individuals have created in order to facilitate this process, and offer thoughts on how these important developments in the acquisition and sharing of knowledge can best be encouraged to thrive in the future.</em></blockquote>
				<p><strong><em>Introduction:&nbsp;</em></strong>Throughout human history, the expansion of knowledge has been linear and accretive: in pre-history, individuals acquired and shared information, and to the limited extent possible passed that knowledge along to the next generation. But since knowledge could not be recorded, it was at constant risk of loss or corruption. Moreover, this dependence on oral transmission limited the complexity of knowledge that could be transmitted through the "lowest common denominator" of understanding of each human link in the chain. Impressive advances could be easily lost &mdash; as occurred 50,000 years ago, when the descendents of the first humans to reach Australia lost the technology to make sea voyages. Some of their descendants, settling on isolated islands off shore from their new home, even lost the ability to make fire.</p>
				<p>The invention of writing crucially allowed knowledge to expand much more rapidly, since discoveries could now not only be preserved in faithful detail and built upon by others, but also shared more widely across both space and time. Moreover, because the peoples that used writing also lived in town-based, hierarchical societies, classes of people now existed with the desire and time to learn. With some of the best minds of the times now able to stand on the shoulders of their predecessors, and in turn "speak" to the best and the brightest of the next generation, the increasing pool of knowledge could be utilized to create much more complex types of learning based upon abstractions, through reasoning and inference. Wars and catastrophes could still set knowledge back dramatically within any single society, but with the dispersion of knowledge there was greater likelihood that some of the unique discoveries of one culture would be communicated to another, sustaining society linked through trade or alliance. The result of writing and communication was therefore that the preservation of knowledge had at last become less ephemeral, and the capacity to create new knowledge more robust.</p>
				<p>Though the process of knowledge creation and preservation now led to great advances in complex disciplines such as mathematics, philosophy and astronomy, the process of advancement remained largely linear, slow, and accretive. This, because the utilization of information beyond small communities of scholars remained mediated by the need to write down and then physically transport the results to those that might take the next intuitive leap. The use of Latin (in the West) and Arabic (in the Islamic world) facilitated the sharing of ideas across international borders, but the limited travel infrastructure of the day ensured that even this process remained painfully slow.</p>
				<p>In the modern era, advanced transportation systems began to hasten knowledge exchange, as postal systems became more reliable and swift, and as more scholars and experts could travel farther and more frequently to exchange and debate the fruits of their research first hand. With the invention and deployment of modern voice-based telecommunications technologies, verbal exchanges of summarized data, if not detailed research, became possible as well.</p>
				<p>While these changes were historically dramatic, their impact was evolutionary, rather than revolutionary, since the exchange of information between geographically separate researchers and thinkers in the same disciplines was still likely to be occasional and episodic, rather than constant and seamless. As a result, researcher B would usually not have full access to the discoveries of researcher A until A's research had been submitted, evaluated, edited and at length published in a scientific journal, unless both A and B happened to be in trusted, personal communication. Thus, while the fidelity and range of knowledge transmission increased, the cycle of its reuse remained painfully slow.</p>
				<p>A less obvious limitation of the technologies of the times was the impracticality of assembling collaborative communities across distances that could work on the same projects simultaneously. Those with the knowledge and ability to achieve impressive results through collaboration were thus constrained to work in comparative isolation, sometimes unknowingly working on the same problems, and even conducting the same experiments, that others were tackling at the same time. This separation encouraged rivalry rather than collaboration, further inhibiting the free exchange of discoveries until primacy of discovery could be established through disclosure in a respected journal.</p>
				<p>Similarly, the roles of research and development remained largely separate, in part because those trained in the exploitation of new ideas were not likely to be direct participants in the types of communities that engaged in pure research.</p>
				<p>With the advent of the Internet and the Web and the increasing adoption in the wired world of English as a successor to Latin and Arabic, many of these age-old logistical constraints have fallen away. Today, it is possible for individuals from around the world to form communities large and small that are able to not only immediately share facts, research, insights and hard results, but work concurrently on the same projects as well. The benefits of such real-time access to valuable data has encouraged many in the scientific community to become more open in consequence. It has also allowed communities of like-minded individuals to form that could never have reached critical mass in the past, when the pool of similarly interested and skilled individuals from which such a community could be formed was limited to those in geographical proximity.</p>
				<p>In this article, I will describe some of the ways in which both individuals as well as these new technically enabled communities are transforming the ways in which knowledge is acquired and shared. More importantly, I will explore how the promise of these Web-enabled processes is providing incentives to adjust traditional ideas regarding the proper balance to be struck between the intellectual property rights (IPR) of individual owners and those of collaborative communities and end users. Finally, I will review some of the new legal tools and organizational structures that have been created in order to more fully realize the revolution in knowledge sharing and advancement that modern telecommunications technologies make possible.</p>
				<p><strong>I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Needs of Linear vs. Real-Time Processes</strong></p>
				<p><strong><em>Laws for a linear process:</em></strong> For most of historical times, there was no need for a legal system to protect IPR, because even if the labors of creation were great, the benefits to the creator were often low. For example, in the academic world, recognition as the originator of a discovery or theory conveyed status and opportunity, but that value could be secured simply by providing a means whereby recognition as the first to discover could be established. This could be accomplished through presentation of papers at meetings of scientific societies, and through publication in journals.</p>
				<p>Where value was greater, as in the case of manufacturing processes, rights to practice inventions for many years was protected simply through secrecy, enforced either individually, or collectively, in guilds.</p>
				<p>But as an industrial society began to take shape, greater profits could be lost if imitators unsaddled by the costs of research and development could swiftly and cheaply "knock off" the easily understood physical world inventions of the times. In the case of works of authorship, expanding literacy rates increased the market for written materials dramatically, a need which advances in printing technology easily satisfied. Predictably, literary piracy became rampant.</p>
				<p>The result was the development in modern times of legal systems that were concerned primarily with protecting the rights of innovators, inventors and authors, as compared to competitors and consumers. Still, in the case of inventions and works of authorship, there was recognition that the benefits to society of unfettered use were sufficiently significant that the control granted to inventors and authors over their creations should be finite rather than perpetual, with the period of exclusive enjoyment to be somehow appropriate to the labor and creativity invested.</p>
				<p>The rights given to creators and inventors among the various forms of intellectual property also took into account the unique characteristics of the works in question. In the case of patents and copyrights, limits were imposed on the duration of the owner's right to exclude others from free use of their invention, idea, or work. Patent rights were assigned the shortest period of enjoyment, because the scope of the protection is most broad, representing a state-granted monopoly to practice the concept of an invention, rather than to produce a single, specific implementation of the innovation.</p>
				<p>The exclusive publication rights granted under copyright are much narrower, protecting only the actual expression of the author (e.g., the words themselves, as compared to the underlying ideas), and the duration of exclusivity protected by law was therefore permitted to be longer. But even in the case of a novel, poem or essay, law makers decided that unfettered republication rights must necessarily pass eventually into the public domain.<sup>1</sup> In contrast, it was deemed appropriate for the exclusive rights in a trademark or service mark to be perpetual, because the cost to society of granting such exclusive rights is low. Still, there are limitations on the specific words that can become a trademark or service mark,<sup>2</sup> and the rights secured by a mark are also limited to the domain in which the product or service is actually offered (e.g., computer software).</p>
				<p>Over time, the laws that evolved to reflect this balancing of interests has become increasingly uniform throughout the world. This was achieved through the refinement and wide adoption of a succession of treaties that apply to the principle forms of intellectual property recognized at law today (copyright, trademark and patent). These international agreements that treaty parties conform their internal laws to the requirements of the treaty (e.g., the Berne Convention) and may also mandate the enforcement of those same laws against infringers (e.g., the Agreement on Trade Related Aspects of Intellectual Property Rights (TRIPS), which is binding on members of the World Trade Organization (WTO)).</p>
				<p>In the main, this legal regime has served developed nations well, and emerging nations therefore generally fell in step as they joined the global economy, adopting the same legal concepts, and with time, becoming party to many of the same treaties. At the dawn of the Internet era, the IPR legal infrastructure could therefore be viewed as a comprehensive, relatively mature global system, well attuned to the slowly evolving realities, values and needs of the societies the framework had been created to serve.<sup>3</sup></p>
				<p><strong><em>The digital challenge:</em></strong> The legal framework we know today evolved to serve the needs of a physical world, however. Those active in the virtual world soon found that the licenses and practices that had developed in the past seemed too constraining to serve the types of activities in which they were now technically able to engage. For example, the ability to place works of authorship on line and allow them to be manipulated collaboratively from anywhere in the world presented both opportunities as well as new issues. Such behavior had never before been contemplated in a world where single authors created complete works that were then referenced in the writings of later authors. Not surprisingly, copyright laws were in some respects at best unhelpful, and at worst limiting.</p>
				<p>Moreover, some communities that began to form around Internet-enabled opportunities reached different conclusions about what should change, and how. This was due in part to the fact that the range of subject matter opportunities was so broad (e.g., computer code development versus scientific research), but also because the motivations of the individuals that most publicly framed the resulting dialogue varied widely as well. In many respects, this dialogue assumed the need and the justification to revise the traditional balancing of rights between IPR owners and IPR users.</p>
				<p>The result has been a still-emerging, and often spirited, debate over whether existing IPR laws need to change. At the same time, there has been a dynamic process of reapplying existing laws in new and often imaginative ways, in order to adapt the existing rule set to meet the needs and opportunities of our increasingly on-line world without the need for amending underlying laws at all.</p>
				<p><strong>II&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Open Revolution</strong></p>
				<p>At the heart of this modern revolution in thinking is the concept of "openness." While this still-evolving term has come to mean different things in different contexts (and often even within the same context, depending upon who is providing the definition), at minimum it recognizes that a greater good can be achieved through the simultaneous or early sharing of information than by keeping it secret until formal publication, in the case of research, or perpetually, in the case of source code or other technical information. Often, it also includes free and unrestricted rights of reuse, for some, or for all purposes. The methodologies and legal tools that have been created to achieve these goals are therefore directed at enabling a greater degree of visibility, access, and reusability than in the past.</p>
				<p>The following is a sampling of some of the more prominent "open" methodologies and rule sets that have arisen in the wake of the digital revolution:</p>
				<p><strong><em>Free software:</em></strong> The concept of "free software" was conceived by Richard Stallman in 1983, before the Internet became widely used by other than academics. As proposed by Stallman, the designation "free" refers to freedom of access and reuse rather than a requirement that such rights be conveyed at no cost (although in fact most such software is also made available free of charge).<sup>4</sup> This distinction underlines the fact that something new is at issue here, rather than the traditional concerns that copyright was intended to protect. Instead of seeking to protect rights of economic exploitation, the rules that apply to free software are intended to ensure what amounts to rights of common ownership, largely independent of economic motivations. As a result, these rules are intended to guarantee the rights to use, copy, study, modify, and to share the original and any modified versions of the software in question with others.</p>
				<p>In a sense, the software code is considered to be less a work of authorship, than a collection of ideas that can be shared, evolved and built upon, just as knowledge and research has traditionally been shared in academic circles. Intriguingly, copyright law has been repurposed to help create licenses to assure this new set of goals. That said, it is important to note that the concept of free and open software relates to the rights of developers and technically savvy users rather than everyday users that are not technically able to enjoy the rights that free software embodies.</p>
				<p>The goals embodied by free software were codified in the "Four Freedoms" that Richard Stallman proposed and the Free Software Foundation published as a definition of free software in 1986. Those freedoms, with introductory explanation, are as follows:</p>
				<blockquote>Free software is a matter of the users' freedom to run, copy, distribute, study, change and improve the software. More precisely, it refers to four kinds of freedom, for the users of the software:</blockquote>
				<ol>
					<li>The freedom to run the program, for any purpose (freedom 0).<br /><br /></li>
					<li>The freedom to study how the program works, and adapt it to your needs (freedom 1). Access to the source code is a precondition for this.<br /><br /></li>
					<li>The freedom to redistribute copies so you can help your neighbor (freedom 2).<br /><br /></li>
					<li> The freedom to improve the program, and release your improvements to the public, so that the whole community benefits (freedom 3). Access to the source code is a precondition for this.<sup>5</sup></li>
				</ol>
				<p>The purpose of these rules is novel: in terms of more traditional works of authorship, it would be as if an author of a short story wished to allow any reader to rework her story and then share it with others &mdash; or even sell it &mdash; provided that those she sold it to were permitted the rights to do exactly the same thing. In short, the definition first specifies a very broad set of freedoms, but then imposes a set of restrictions on the recipient of those freedoms, in order to ensure their extension to others.</p>
				<p>The utilization of this definition was intended to create a sort of public commons of software. That goal has been impressively achieved, in part because unlike many types of historically shared property, free software is protected by licenses that prevent the public engaging in the type of behavior that too often results in the "tragedy of the commons" (that is, a tendency among those entitled to share in the commons to overexploit it for their own advantage until the resource is exhausted, before someone else does). A free software license is therefore self consciously both a social contract as well as a set of legal rules.<sup>6</sup></p>
				<p><strong><em>Open source software:</em></strong><sup>7</sup>  Open source software embraces most of the same objectives as free software, but emphasizes its attributes in a somewhat different fashion. Like the Free Software Foundation, there is a non-profit organization (in this case the Open Source Institute<sup>8</sup>) that controls the definition of open source software, and which also maintains a (near identical) list of licenses that OSI has approved as meeting its own definition. These licenses provide a wide range of rule sets from which a developer may choose when making software available.</p>
				<p><strong><em>Open hardware:</em></strong> In a few cases, "open hardware" is also being created. Current examples include semiconductor designs (Sun's SPARC architecture and the Power.org architecture)<sup>9</sup> and even mobile telephone handsets (OpenMoko is creating a line of fully open source mobile phones, based upon both a mobile Linux operating system as well as handsets of its own design).<sup>10</sup></p>
				<p><strong><em>Open development:</em></strong> Just as vendors realized long ago that open standards could help create larger markets faster, platform vendors are now realizing that making their platforms as open as possible can foster the development of a wide range of products and services by independent software vendors (ISVs) to the mutual benefit of all, and most particularly of the platform vendor itself. As a result, even traditionally closed and controlling vendors, such as telecommunications companies, are now competing to open up their (often Linux-based) mobile telephone operating systems in order to encourage ISVs to make the use of mobile phones more interesting and attractive. Already, several major vendor as well as community efforts have been launched, each with a different approach, and with a different member composition:<sup>11</sup></p>
				<ol>
					<li><strong>LiMo (for Linux Mobile) Foundation</strong>, formed in January 2007 primarily by handset vendors. LiMo was founded to "create an open, Linux-based software platform for use by the whole global industry to produce mobile devices&hellip;enabling a rich ecosystem of differentiated products, applications, and services from device manufacturers, operators, ISVs and integrators."<sup>12</sup><br /><br /></li>
					<li><strong>Open Handset Alliance,</strong><sup>13</sup> announced on November 5, 2007. OHA is spearheaded by Google, and was supported by 33 additional members at launch, including mobile handset makers, application developers, some mobile carriers and chip makers. Like LiMo, OHA is developing a Linux-based open mobile platform, in this case called Android.<br /><br /></li>
					<li><strong>Moblin.org,</strong><sup>14</sup> the Mobile and Internet Linux project, launched by Intel in July of 2007 as an open source project. Moblin is focused more broadly than LiMo and OHA, focusing on "mobile Internet devices," a more heterogeneous category than simply handsets. Canonical, the developer of the Ubuntu Linux distribution, is working on an operating system in support of the project.<br /><br /></li>
					<li><strong>GNOME Mobile &amp; Embedded Initiative,</strong><sup>15</sup> announced in April of 2007, and focused on the GNOME Linux-based operating system<br /><br /></li>
				</ol>
				<p><strong><em>Open standards:</em></strong> The definition of open standards is at once the oldest as well as the (currently) most disputed. In traditional standard setting circles, "openness" was achieved through a rule set that sought to ensure that all "stakeholders" (i.e., not only those that implement standards, but also governments and those affected by standards as well) had access to the process, that consensus would drive decisions, that an appeals process would be provided, and that the IPR of a single stakeholder would not unreasonably stand in the way of the common good whenever that result could be achieved.</p>
				<p>With the rise of the information and communications technology, however, this rule set began to become more constraining, for a variety of reasons, and particularly so in the case of software. Those reasons include the proliferation of patent "thickets," the convergence of technologies in single devices (such that a mobile telephone, for example, may infringe upon hundreds of patents as a result of complying with necessary standards), and the increasing deployment of open source software under licenses with terms that may not be satisfied when standards are implemented that were developed under traditional IPR policies.</p>
				<p>The result has been an ongoing debate over the definition of what should constitute an "open standard," and particularly over what the IPR terms of the policies should be under which such standards are developed.<sup>16</sup></p>
				<p><strong><em>Open content:</em></strong> The concept of open content is in many ways similar to open source and free software, but made generic to serve any type of copyrightable work, whether it be text, graphic, audio or video. As with software, a set of legal terms serving this concept has been proposed and become widely adopted as a result of the efforts of articulate visionaries that have (once again) created a non-profit entity to serve that vision. The most prominent advocate in this case is Stanford Law School professor <a href="http://en.wikipedia.org/wiki/Lessig">Lawrence Lessig</a>, and the resulting institution is called the Creative Commons.<sup>17</sup></p>
				<p>The goal of the Creative Commons is to encourage wider reuse of copyrightable works by providing easy to use, free legal tools that creators can use to provide such rights, for such purposes, and to such types of users, as they wish. This is accomplished through a series of plain language licenses (now translated into 43 languages) that make it easy for creators to make their work as freely and easily available as they wish. As explained at the Creative Commons Web site:</p>
				<p>In the words of Thomas Jefferson, "He who receives an idea from me, receives instruction himself without lessening mine; as he who lights his taper at mine receives light without darkening me." An idea is not diminished when more people use it. Creative Commons aspires to cultivate a commons in which people can feel free to reuse not only ideas, but also words, images, and music without asking permission &mdash; because permission has already been granted to everyone.<sup>18</sup></p>
				<p>We use private rights to create public goods: creative works set free for certain uses. Like the free software and open-source movements, our ends are cooperative and community-minded, but our means are voluntary and libertarian. We work to offer creators a best-of-both-worlds way to protect their works while encouraging certain uses of them &mdash; to declare "some rights reserved."<sup>19</sup></p>
				<p>The licenses themselves are visually coded to symbolically indicate the significant terms that each contains, making it easy for anyone to select the licensing approach most to their liking. The terms and their associated symbols are as follows:</p>
				<table border="0" cellpadding="0" cellspacing="0">
					<tr>
						<td valign="top" style="padding:0px 10px 0px 15px;"><img src="apr08/apr_icon1.gif" width="28" height="28" border="0" alt=""></td>
						<td valign="top" style="padding:0px 20px 15px 0px;"><p><strong>Attribution.</strong> You let others copy, distribute, display, and perform your copyrighted work &mdash; and derivative works based upon it &mdash; but only if they give credit the way you request.</p></td>
					</tr>
					<tr>
						<td valign="top" style="padding:0px 10px 0px 15px;"><img src="apr08/apr_icon2.gif" width="28" height="28" border="0" alt=""></td>
						<td valign="top" style="padding:0px 20px 15px 0px;"><p><strong>Noncommercial.</strong> You let others copy, distribute, display, and perform your work &mdash; and derivative works based upon it &mdash; but for noncommercial purposes only.</p></td>
					</tr>
					<tr>
						<td valign="top" style="padding:0px 10px 0px 15px;"><img src="apr08/apr_icon3.gif" width="28" height="28" border="0" alt=""></td>
						<td valign="top" style="padding:0px 20px 15px 0px;"><p><strong>No Derivative Works.</strong> You let others copy, distribute, display, and perform only verbatim copies of your work, not derivative works based upon it.</p></td>
					</tr>
					<tr>
						<td valign="top" style="padding:0px 10px 0px 15px;"><img src="apr08/apr_icon4.gif" width="28" height="28" border="0" alt=""></td>
						<td valign="top" style="padding:0px 20px 15px 0px;"><p><strong>Share Alike.</strong> You allow others to distribute derivative works only under a license identical to the license that governs your work.<sup>20</sup></p></td>
					</tr>
				</table>
				<p>Because the Creative Commons has created and maintains the source documentation for the licenses in three forms &mdash; plain language, legal "fine print," and machine-readable code that can be detected by search engines &mdash; a creator can place her work under the Creative Commons license of her choice in a matter of minutes.</p>
				<p>The licenses provided by the Creative Commons have been very widely adopted, not only with respect to specific works, but also to all of the material at individual blogs, in photo collections at sites such as Flickr, and in many other situations on the Web. As a result, the Creative Commons has helped facilitate not only the reuse of much of the most easily available content, but also the workings of collaborative projects. Other projects, such as the Wikipedia, utilize the GNU Free Documentation License, which was created for a similar purpose.<sup>21</sup></p>
				<p><strong><em>Open data:</em></strong> The concept of open data is intended to encourage and enable broad availability of non-textual data of various, usually scientific types (e.g., genomic and mapping data). Due to the high economic value of much data of this type, and the fact that scientific data tends to be created in non-profit institutions and for-profit labs that are in each case subject to ownership policies relating to IPR, the articulation and adoption of open data is thus far less advanced. However, the value of making data rapidly and widely available on the Internet in formats allowing it to be rapidly searched and integrated is obvious.</p>
				<p><strong><em>Open access:</em></strong> Open access is a practice that relates to both open data and open content. The term was coined at a meeting held in Budapest in December of 2001 that led to the issuance of a call to action referred to as the Budapest Open Access Initiative.<sup>22</sup> Those that drafted the Initiative document recognized that there was great opportunity to be gained by returning to the historical practice of freely sharing scientific data and learning, so that the academic and scientific communities at large could benefit from, and build upon those contributions. In order to achieve those goals, the Initiative recommended both self publishing by researchers and authors (which it called Self-Archiving)<sup>23</sup> as well as the conversion of journals to on-line, searchable resources (which it referred to as Open Access Journals).</p>
				<p>This call to action was met with enthusiasm. As of this writing, the Directory of Open Access Journals lists 1151 journals searchable at the article level, exposing a total of 184,817 articles in all to search engines and direct searches.<sup>24</sup></p>
				<p><strong>III&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lessons Learned and Next Steps</strong></p>
				<p>As can be appreciated from the high level overview of open methodologies offered above, the very brief existence of the Internet and the Web has led to broad appreciation of the benefits that can arise from greater visibility and collaboration. The examples given also demonstrate a great deal of creativity in using traditional legal tools in an effort to facilitate and encourage such activity. In each case, these tools have been created to address a desire to rebalance the traditional rights of creators and inventors with those that wish to build upon their efforts.</p>
				<p>It is important to note that while this willingness to share is to some extent based upon moral or ethical grounds, it is also firmly rooted in self interest. In every case noted above, those that are willing to give more also anticipate getting more, with this new potential made possible by the global reach of the Internet and the searchable nature of the Web. In consequence, it would appear that the trend towards openness is likely to be fundamental and sustaining, rather than a passing fad.</p>
				<p>It is important to recognize the magnitude of this revolution, because it indicates that another fundamental shift &mdash; this time in law, or at least in legal tools &mdash; is both warranted as well as desirable, in order to capitalize on the benefits that increased sharing can offer. To date, these benefits have sometimes been trivialized, with proponents of legal change pointing only to (for example) pop cultural "mashups" of audio and video clips on YouTube. While such activities are certainly not trivial to those involved in the arts, they do not represent the examples most likely to head off the legions of lobbyists that could be expected to descend upon legislators if changes were feared that would apply equally to semiconductor chip designs, the text of best selling novels and the formulations of blockbuster pharmaceuticals.</p>
				<p><strong><em>What can be gained:</em></strong> Changes of any nature to existing laws will require strong justifications. It is therefore useful to summarize some of the ways that a liberalization of laws and practices can benefit society, as well as provide off-setting benefits to IPR owners as well. Consider, for example, the benefits that can accrue from the following:</p>
				<ol>
					<li><strong><em>More rapid development of projects of all types,</em></strong> due to the ability of more like-minded individuals to join in collaborative communities than before, and from greater freedom to reuse and incorporate the work of others<br /><br /></li>
					<li><strong><em>More rapid scientific discoveries,</em></strong> because information can be accessed and searched immediately upon disclosure on line, and then used as the basis for further discoveries<br /><br /></li>
					<li><strong><em>Greater opportunities for those in emerging societies,</em></strong> as a result of a more level playing in research and development, through free and unrestricted access to more data, software and open content<br /><br /></li>
					<li><strong><em>Greater ease of entry for new businesses in developed societies,</em></strong> resulting from lower barriers to entry through use of open technologies, data, content and other material<br /><br /></li>
					<li><strong><em>Reduced prices and greater profits,</em></strong> as a result of widely shared development costs</li>
				</ol>
				<p>Many of these benefits are already being realized. But some impediments remain, chiefly in the area of patents, but also under copyright law.</p>
				<p><strong><em>What may need to change:</em></strong> As already demonstrated by the development and widespread use of FOSS, open source and Creative Commons licenses, a great deal of creativity has already been invested in adapting old tools to serve new uses. But there are limits to how far this process can be taken. The following are examples of areas in which legislative action, organic evolution through the courts, or additional non-profit organizations might be useful:</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Fair use:</em></strong> Traditional fair use doctrines have permitted only extremely limited reuses of copyright material. Currently, only a few words can be safely reused in most situations, and not a great deal more even where (as in literary reviews) more extensive excerpts can be incorporated. At the same time, the degree of tolerance for reuse in the breach is changing, in some cases dramatically, as content owners often reap indirect financial rewards as a result of such borrowing. Examples of such practices include news links at blogs that include news article outtakes that often exceed fair use length, but then provide a link back to the content owner's site, thereby driving traffic and enhancing revenues. In some cases, such reuse is even desired and encouraged as part of modern marketing campaigns.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Software patents:</em></strong> The current state of U.S. patent law as it relates to software seems to please just about no one, although there is a wide variety of opinion on how the law and the operations of the United States Patent and Trademark Office (PTO) should change. Leaving aside calls to abolish patent protection for software entirely, there is consensus that patents are too easy to get, and too hard and expensive to challenge when they have been improperly granted. Any progress in cutting down on the density of so-called "patent thickets" would provide at least some incremental relief.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Increased use of non-assertion covenants:</em></strong> A commitment made by a patent owner that it would not assert its "essential claims" against compliant implementations of a given standard has been a permissible alternative to agreeing to providing an implementation licenses on RAND terms in some standards organizations for many years. More recently, such pledges have been made in connection with FOSS and open source software as well. In principle, such promises are much better than a commitment to license, since no action on the part of the beneficiary of the pledge is required at all, and because it is apparent to all that everyone benefits to exactly the same degree (as compared to the licensing situation, where specific terms are usually known only to the parties on a license by license basis).</p>
				<p>But pledges, like license commitments, do have some limitations, such as variations in terms, and difficulty of enforcement against later owners of the patents in question. These weaknesses could be solved, in the first instance, by an organization that maintained a list of pledges that had been found to meet minimum standards for FOSS licensing, and in the second instance, by setting up a registry with the PTO that would allow a patent to be permanently encumbered with the obligation assumed, much as a mortgage filed with a registry of deeds enables an enforceable obligation to be imposed on a successor owner of real property.</p>
				<p><strong>IV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Summary</strong></p>
				<p>During the years of the Internet Bubble, it was fashionable to observe that the Internet had "changed everything." That observation seemed na&iuml;ve and without basis by 2001. But with time it has become apparent that the Internet really has changed some things in a fundamental and permanent way. One of those things is the way in which knowledge can be created and shared.</p>
				<p>There is ample evidence that this more limited observation is sound, and that much can be gained by taking appropriate action to encourage and facilitate the ways in which the Internet can be utilized for the purpose of sharing information as widely and quickly as possible, and collaboratively building upon that information in as unrestricted a fashion as possible.</p>
				<p>This process is already well along, through the organic efforts of a wide variety of both visionaries as well as lesser mortals, who together are creating and promoting new tools that have already enjoyed wide and successful adoption. This grass roots process will no doubt continue, and may in fact be best suited to realizing the potential of a wired world for some time to come. While this experimental process continues, restraint on the part of legislatures, and a willingness to be open minded on the part of the courts, may provide the best route to eventually settling on a new balance between the IPR rights of creators and inventors, on the one hand, and re-users and end-users on the other.</p>
				<p>When that process is complete, the more traditional process of law making and treaty drafting can step in to memorialize and formalize the solutions worked out in the trenches, based on the wisdom gained through the rough and tumble of the marketplace.</p>
				<p class="center">Copyright 2008 Andrew Updegrove</p>
				<p>End Notes</p>
				<p><sup>1</sup> The duration of a copyright depends in part on the nature of the work and other factors, and is additionally complicated with respect to individual works by changes to the copyright laws over the years. Most recently in the United States the duration of a copyright was lengthened by 20 years under The Copyright Extension Act. That legislation was responsive to the vigorous lobbying efforts of major content owners, and particularly of the Walt Disney Corporation, the owner of a certain iconic cartoon character that was in imminent danger of falling into the public domain. The Copyright Extension Act therefore stands out as one of the clearest examples of truly "Mickey Mouse legislation."</p>
				<p><sup>2</sup> For example, a trademark may not be merely "descriptive." Otherwise, a cutlery vendor (for example) might trademark a word such as "knife," leaving its competitors with no way to identify their own competing products. In contrast, a trademark may be "suggestive" of the nature or virtues of a product, allowing a knife to bear a trademark such as "Chef's Delight."</p>
				<p><sup>3</sup> "Relatively mature" does not mean "final." For example, the <a href="http://www.wipo.int/documents/en/diplconf/distrib/94dc.htm">World Intellectual Property Organization (WIPO) Copyright Treaty</a> was adopted on December 20, 1996. It has since been implemented in varying forms in signatory nations such as the United States (in the <a href="http://en.wikisource.org/wiki/Digital_Millennium_Copyright_Act">Digital Millenium Copyright Act</a>, or DMCA) and in the European Union (in <a href="http://209.85.215.104/search?q=cache:zAgslAkJwjkJ:eur-lex.europa.eu/LexUriServ/LexUriServ.do%3Furi%3DCELEX:32001L0029:EN:HTML+%22eu+copyright+directive%22&amp;hl=en&amp;ct=clnk&amp;cd=4&amp;gl=us&amp;client=firefox-a">Directive 2001/29/EC</a> of the European Parliament and of the Council of 22 May 2001 on the Harmonisation of Certain Aspects of Copyright and Related Rights in the Information Society). This evolutionary process will undoubtedly continue.</p>
				<p><sup>4</sup> Perhaps as a reflection of the settings in which revolutionary concepts are often conceived, this distinction is invariably articulated as follows: "free (as in speech), not free (as in beer)."</p>
				<p><sup>5</sup> The application of this definition in practice can be quite complex, as indicated by the supplemental notes that accompany the free software definition at the Free Software Foundation Web site, which can be found <a href="http://www.gnu.org/philosophy/free-sw.html">here</a>: http://www.gnu.org/philosophy/free-sw.html</p>
				<p><sup>6</sup> The novelty of the goals propounded by Stallman are reflected in the name he gave to the license intended to secure his four freedoms, which he named a "copyleft" license. The most prominent copyleft license is the GNU General Public License (GPL), utilized by Stallman's GNU project, and thousands of other software development projects around the world, including the Linux kernel. Version 3 of the GNU Public License was released in 2007 after extensive input, discussion and debate.</p>
				<p><sup>7</sup> There are various nuances and variations in the terminology used to describe open software, including "free and open source software" (FOSS) and "free/libre open source software" (FLOSS).</p>
				<p><sup>8</sup> OSI was founded in 1998 by Bruce Perens and Eric S. Raymond, in part in an effort to make the concept of open source software less threatening to the commercial marketplace. The current, lengthy list of licenses (many rarely used) that have been submitted and approved by OSI may be found <a href="http://opensource.org/licenses/alphabetical">here</a>: http://opensource.org/licenses/alphabetical</p>
				<p><sup>9</sup> Sun open sourced the SPARC architecture in March of 2006. Interested engineers can participate in the further evolution of the architecture through the <a href="http://www.opensparc.net/">OpenSPARC Initiative</a>, which maintains a Web site <a href="http://www.opensparc.net/">here</a>: http://www.opensparc.net/ <a href="http://www.power.org/home">Power.org</a> was established by IBM and supporting companies in 2004 to develop open standards, guidelines, best practices and certifications to support IBM's Power Architecture. Its Web site is here: http://www.power.org/home</p>
				<p><sup>10</sup> <a href="http://www.openmoko.com/">OpenMoko</a> was announced by First International Computer (FIC) in 2006. Its Web site can be found at: http://www.openmoko.com/</p>
				<p><sup>11</sup> On March 6, 2008, Apple's Steve Jobs announced his own, more limited and controlled effort at attracting ISVs to the iPhone platform. Under the Apple plan, ISVs can gain access to the necessary technical information to create applications to run on the iPhone, which Apple will then market through a new ""App Store" that it will host. I have doubts whether this more controlling effort will be as successful as the other, more open mobile efforts, as I discussed in a March 7, 2008 blog entry at The Standards Blog titled <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20080307054430261&amp;">Steve Jobs Endangered Second Act</a>, at http://www.consortiuminfo.org/standardsblog/article.php?story=20080307054430261&amp;</p>
				<p><sup>12</sup> "Welcome to LiMo," at: <a href="http://www.limofoundation.org/welcome-to-limo.html">http://www.limofoundation.org/welcome-to-limo.html</a> accessed May 28, 2008.</p>
				<p><sup>13</sup> The home page for the <a href="http://www.openhandsetalliance.com/">Open Handset Alliance</a> can be found here: http://www.openhandsetalliance.com/</p>
				<p><sup>14</sup> The <a href="http://www.moblin.org/">Moblin.org</a> Web site can be found at: http://www.moblin.org/</p>
				<p><sup>15</sup> The <a href="http://www.gnome.org/mobile/">Gnome Mobile Web</a> site can be found at: http://www.gnome.org/mobile/</p>
				<p><sup>16</sup> One of the most cited discussions of open standards attributes is <a href="http://www.csrstds.com/openstds.pdf">Open Standards Requirements</a>, by Ken Krechmer, at http://www.csrstds.com/openstds.pdf The <em>International Journal of IT Standards and Standardization Research</em>, Vol. 4 No. 1, January &ndash; June 2006. Krechmer's lists of attributes is sufficiently comprehensive, however, that very few standards organizations would likely to satisfy it.</p>
				<p><sup>17</sup> The <a href="http://creativecommons.org/">Creative Commons</a> Web site can be found at: http://creativecommons.org/</p>
				<p><sup>18</sup> Excerpted from "<a href="http://wiki.creativecommons.org/Legal_Concepts">Legal Concepts,</a>" Creative Commons, accessed May 18, 2008, at http://wiki.creativecommons.org/Legal_Concepts</p>
				<p><sup>19</sup> Excerpted from "<a href="http://wiki.creativecommons.org/Legal_Concepts">About,</a>" Creative Commons, accessed May 18, 2008, at http://wiki.creativecommons.org/Legal_Concepts</p>
				<p><sup>20</sup> Excerpted from "<a href="http://creativecommons.org/about/license/">License Your Work,</a>" Creative Commons, accessed May 18, 2008, at http://creativecommons.org/about/license/</p>
				<p><sup>21</sup> The <a href="http://www.gnu.org/copyleft/fdl.html">text of this license</a> may be found at the GNU Project Web site at http://www.gnu.org/copyleft/fdl.html (accessed May 18, 2008). There are a number of other, less widely used open content licenses.</p>
				<p><sup>22</sup> The <a href="http://www.soros.org/openaccess/read.shtml">text of the Initiative</a> can be found at http://www.soros.org/openaccess/read.shtml (accessed May 18, 2008).</p>
				<p><sup>23</sup> Self-Archiving has been facilitated by the formation of the <a href="http://www.openarchives.org/">Open Archives Initiative</a>, which develops standard for that purpose. The home page of this organization can be found at: http://www.openarchives.org/ (accessed May 18, 2008).</p>
				<p><sup>24</sup> The <a href="http://www.doaj.org/">index</a> of the Directory of Open Access Journals can be found at http://www.doaj.org/ (accessed May 18, 2008).</p>