AutoClose = 1
foldersTree = gFld("<p>Report</p>")
f1 = insFld(foldersTree, gFld("<p>General Statistics</p>","General_Statistics.htm"))
insDoc(f1, gLnk("<p>Summary</p>", "General_Statistics.htm#Summary"))
f2 = insFld(foldersTree, gFld("<p>Activity Statistics</p>","Activity_Statistics.htm"))
insDoc(f2, gLnk("<p>Daily</p>", "Activity_Statistics.htm#Daily"))
insDoc(f2, gLnk("<p>By Hour of Day</p>", "Activity_Statistics.htm#By_Hour_of_Day"))
insDoc(f2, gLnk("<p>By Day of Week</p>", "Activity_Statistics.htm#By_Day_of_Week"))
insDoc(f2, gLnk("<p>By Month</p>", "Activity_Statistics.htm#By_Month"))
f3 = insFld(foldersTree, gFld("<p>Access Statistics</p>","Access_Statistics.htm"))
insDoc(f3, gLnk("<p>Pages</p>", "Access_Statistics.htm#Pages"))
insDoc(f3, gLnk("<p>Files</p>", "Access_Statistics.htm#Files"))
insDoc(f3, gLnk("<p>Directories</p>", "Access_Statistics.htm#Directories"))
insDoc(f3, gLnk("<p>Entry Pages</p>", "Access_Statistics.htm#Entry_Pages"))
insDoc(f3, gLnk("<p>Exit Pages</p>", "Access_Statistics.htm#Exit_Pages"))
insDoc(f3, gLnk("<p>Paths</p>", "Access_Statistics.htm#Paths"))
insDoc(f3, gLnk("<p>File Types</p>", "Access_Statistics.htm#File_Types"))
f4 = insFld(foldersTree, gFld("<p>Visitors</p>","Visitors.htm"))
insDoc(f4, gLnk("<p>Hosts</p>", "Visitors.htm#Hosts"))
insDoc(f4, gLnk("<p>Top-Level Domains</p>", "Visitors.htm#Top_Level_Domains"))
insDoc(f4, gLnk("<p>Countries</p>", "Visitors.htm#Countries"))
insDoc(f4, gLnk("<p>US States</p>", "Visitors.htm#US_States"))
insDoc(f4, gLnk("<p>Cities</p>", "Visitors.htm#Cities"))
insDoc(f4, gLnk("<p>Organizations</p>", "Visitors.htm#Organizations"))
insDoc(f4, gLnk("<p>Authenticated Users</p>", "Visitors.htm#Authenticated_Users"))
f5 = insFld(foldersTree, gFld("<p>Referrers</p>","Referrers.htm"))
insDoc(f5, gLnk("<p>Referring Sites</p>", "Referrers.htm#Referring_Sites"))
insDoc(f5, gLnk("<p>Referring URLs</p>", "Referrers.htm#Referring_URLs"))
insDoc(f5, gLnk("<p>Search Engines</p>", "Referrers.htm#Search_Engines"))
insDoc(f5, gLnk("<p>Engines and Phrases</p>", "Referrers.htm#Engines_and_Phrases"))
insDoc(f5, gLnk("<p>Search Phrases</p>", "Referrers.htm#Search_Phrases"))
insDoc(f5, gLnk("<p>Search Keywords</p>", "Referrers.htm#Search_Keywords"))
f6 = insFld(foldersTree, gFld("<p>Browsers</p>","Browsers.htm"))
insDoc(f6, gLnk("<p>Browsers</p>", "Browsers.htm#Browsers"))
insDoc(f6, gLnk("<p>Operating Systems</p>", "Browsers.htm#Operating_Systems"))
insDoc(f6, gLnk("<p>Spiders</p>", "Browsers.htm#Spiders"))
f7 = insFld(foldersTree, gFld("<p>Errors</p>","Errors.htm"))
insDoc(f7, gLnk("<p>Types</p>", "Errors.htm#Types"))
insDoc(f7, gLnk("<p>404 Errors</p>", "Errors.htm#404_Errors"))
insDoc(f7, gLnk("<p>Other Errors</p>", "Errors.htm#Other_Errors"))
