				<!-- ******************* -->
				<!-- FEATURE ARTICLE -->
				<!-- ******************* -->
				<h3>How Open Must an<br />Open Government Platform be?</h3>
				<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
				<blockquote class="openingquote"><em><strong>Abstract:&nbsp;</strong>The advent of the Internet and the realization of the promise of open standards presents challenges as well as opportunities to governments.  Internally, these technological tools can provide the means to finally allow information locked in disparate proprietary "silos" to pass freely between all units and levels of government.  Externally, they can provide cheaper and better ways to serve the public, providing not only traditional services more efficiently, but enabling new types of openness and interactivity as well.  Achieving either of these goals individually would be difficult, and providing both simultaneously is challenging indeed, in part because providing government services on line raises new issues that must be addressed relating to vendor neutrality, physical and economic accessibility, data preservation, and much more.  Governments are only now confronting these new issues.  Those that deal with them effectively and rapidly will not only provide better services to their citizens sooner, but ensure that their substantial investments in upgrading legacy systems will be best rewarded.</em></blockquote>
				<p>Fulfilling a campaign pledge, President Barack Obama has committed his administration to providing an "unprecedented level of openness in Government," and called upon all of his heads of Executive Departments and Agencies to, "work together to ensure the public trust and establish a system of transparency, public participation, and collaboration&hellip;[in order to] strengthen our democracy and promote efficiency and effectiveness in Government."<sup>1</sup></p>
				<p>Consistent with an ability to understand and utilize technology that was well-demonstrated in the course of his campaign, Mr. Obama has stated his intention to make full use of technology, and particularly Internet-based technology, to permit citizens to access information and interact with government.</p>
				<p>Deploying information technology (IT) effectively will prove to be more difficult from the Oval Office than from the campaign trail, however, due to a number of significant challenges, many of which are well recognized. These hurdles include the comparatively basic level of most in-place government Web-based services, the fact that technology continues to develop at a rapid pace, the difficulties of deploying IT (or indeed any) policy across many government agencies, and the reality that, like so many other complex and long-extant enterprises, the Federal government comprises a bewildering archipelago of proprietary, legacy systems that are only gradually being transitioned into a more interoperable, coherent whole.</p>
				<p>Adding to these infrastructural challenges is a lack of consensus over the boundaries of the field upon which the game of "open government" should be played. True, there are general expectations based upon past practices, but the exact locations of the goal posts have typically shifted from administration to administration, with some presidents acting more secretively than others. Similarly, while the Federal Freedom of Information Act grants a legal right to public access to appropriate documents, some administrations and agencies have interpreted this law more narrowly than others, requiring citizens and journalists to seek access via the courts to materials that at other times might have been produced without argument under other presidents.</p>
				<div class="calloutright">
					<p>Deploying state of the art information technology effect-tively will prove to be more difficult from the Oval Office than from the campaign trail</p>
				</div>
				<p>Physical world issues like these involve subjective interpretations, but the underlying issues are at least well understood at law and in public discourse. Introducing technology into the equation, though, introduces new questions that have to a large extent not as yet been addressed in the courts (or confronted only in loosely analogous, rather than similar, situations). Such issues are only now becoming part of the public dialogue over how interaction between the governors and the governed should occur.</p>
				<p>The questions that technology raises involve issues such as whether citizens should be constrained to use certain software or hardware platforms, or even the products of specific vendors, in order to access and use government sites and services, the degree of effort that governments should invest in ensuring that their Web sites are as state of the art as possible with respect to accessibility standards, what level of privacy and security governments owe to their citizens' data, how long such data must be preserved, and what document formats should be mandated to ensure that result.</p>
				<p>These decisions are complicated by issues of cost (technology is expensive), difficulty (designing openness into a system adds an extra level of complexity), security (how to protect non-public information, and the information of individuals, from non-privileged users), and integration (governments are simultaneously wrestling with the challenge of making a host of proprietary, legacy systems interoperable). Ideally, governments will wish to support not two systems but one for both internal and external purposes to the greatest extent practical and consistent with the maintenance of security.</p>
				<p>But the rewards of taking up this challenge can also be great. They include the prospect of providing better service to citizens, improved efficiency and lower technology costs for governments over time, and the ability to promote social and commercial policy by providing (via the very substantial magnitude of government procurement) attractive incentives for vendors to make their own products more interoperable and accessible. In many ways, the goal to enable what has often been referred to as "eGovernment" is comparable to another ambitious goal of the Obama administration: to deploy a nationally interoperable healthcare system based upon "electronic health records." In the near term, the challenges and the costs of such transitions will be enormous. But in the long term, the efficiencies and cost savings promise to be far more substantial &mdash; if the technical challenges are properly addressed and public expectations are satisfied.</p>
				<p>In this article, I will review some of the principal technology-related topics that have been identified under the heading of "open government" and discussed (more vigorously abroad than in the United States) to date, as well as the standards-related tools that can be used to address these issues. I will also describe the goals and current status of one of the most sophisticated efforts underway today in this domain: the European Union-based initiative known as the <em>Interoperable Delivery of European eGovernment Services to public Administration, Business and Citizens</em> (IDABC). The IDABC provides a well documented, impressively reasoned, and detailed example of how a government can modernize its IT systems to provide not only internal interoperability among multiple governmental units, but a high degree of openness to its citizens and a way to advance public policy as well.</p>
				<p><strong><em>Legacy systems and changing expectations:</em></strong> Not so long ago, digital information resided on discrete, proprietary systems, typically made up of hardware and software procured from a single vendor, often supplemented by costly custom software. The most successful vendors were understandably well content with this state of affairs, because the resulting barriers to switching to another vendor were very substantial. Certainly this situation was less than ideal, but it was nonetheless tolerable, because although a customer's valuable information was trapped within the proprietary formats and databases its vendor provided, that information was usually only of internal relevance (e.g., payroll and sales data). To the limited extent that data needed to be shared externally, paper provided an adequate means of transfer (or at least so it seemed in the absence of any viable alternative).</p>
				<p>In the days before the Web and the Internet provided a practical means to break down data room walls, citizens themselves had little reason to be concerned over a world where public data, like private data, lived in such proprietary walled gardens. At most, the impact of the old paradigm on the public was indirect, involving difficult to investigate issues such as efficiency and cost-effectiveness.</p>
				<p>Today, of course, much has changed. From the technical perspective, once dominant vendors, such as IBM, have lost some of their near-monopoly positions in key product areas, leading them to champion open rather than closed systems as a way to lower the switching costs of customers they hope to acquire. At the same time, other vendors, like Microsoft, have successfully acquired equal, if not greater, monopolies in areas such as operating systems and office productivity suites.</p>
				<p>More importantly, the technical means of achieving real interoperability within networks assembled from the products of multiple vendors, and between networks owned by multiple parties, have become far more credible in the last fifteen years. The tools enabling this transition include not just the Internet, but a multitude of technical standards (e.g., Ethernet, http, html, XML, and many more), new design and delivery concepts such as service oriented architectures (SOA) and the provision of software as a service (SAAS)), and the infrastructural buildout needed to support an ever-expanding Internet and the Web.</p>
				<p>The landscape has changed from the citizens' point of view as well, because technology has now become not only more visible, but accessible and non-threatening to the majority of those living in modern societies. Not surprisingly, governments now wish to interact with citizens via the Web, in part to provide better services, and in part to provide those services at lower cost. Citizens are increasingly eager to take advantage of these services, to save time, to gain greater access to hitherto difficult to obtain information, and to make their opinions known.</p>
				<div class="calloutright">
					<p>Even as technology provides the means to achieve true interoperability, it magnifies the challenges to attaining it.</p>
				</div>
				<p>Indeed, the rise of technology gives government little, if any, choice in the matter, because the volume and types of data that citizens, businesses and governments create and consume have exploded. Instead of creating only text and numerical data, we now create documents of many other types, including presentations and spreadsheets (in each case both editable and fixed), graphics, audio and video files, and much more &mdash; often in the same electronic file. Most dauntingly, we now wish to exchange such information across public, private, national and social boundaries &mdash; all while preserving a broad array of choices in hardware, software and service providers.</p>
				<p>Driving our desire to do so is the continuing power of the network effect: the name economists use to recognize the fact that the larger and more efficient a network is, the more valuable it becomes. In the case of information and communications technology (ICT) networks, that value can be found in multiple ways, including increased efficiency (e.g., being able to enter data once, rather than every time we visit a new Website), access to expanding resources (by permitting more people to access and/or add to common data repositories), better decision making (through real-time information sharing and communication), and greater convenience (through remote access).</p>
				<p>As the size and nature of such networks expand, of course, so also does the challenge of achieving interoperability across them to satisfy market forces and emerging regulatory requirements.<sup>2</sup>  Indeed, even as technology provides the means to achieve interoperability, it magnifies the challenges to attaining it in part due to the speed with which underlying technologies continue to evolve, and in part because the enormous profit opportunities at stake provide incentives for one vendor to promote its technology as the basis for standardization over its competitor's.</p>
				<p><strong><em>Interoperability and social policy:</em></strong> Small wonder, then, that most market participants give little weight to achieving social goals in the process of developing and deploying the standards that enable interoperability. And yet such goals are important, including ensuring equal access to those of limited means, accommodating those with disabilities, and maintaining competition in the marketplace. That commercial interests give little attention to such concerns, while regrettable, is not surprising. But for governments to ignore them would be inexcusable. Unless due regard is given to these needs, valuable civil rights may be prejudiced or lost, as governments increasingly move their activities from the physical to the virtual world.<sup>3</sup></p>
				<div class="calloutright">
					<p>That commercial interests give little attention to such accessibility concerns, while regrettable, is not surprising. But for governments to ignore them would be inexcusable.</p>
				</div>
				<p>Many governments are aware of the benefits of achieving broad and effective interoperability both within and among their networks, as well as between those networks and the ICT assets of their citizens, but only some have considered the potential for pursuing policy goals through the exercise of targeted ICT procurement. As governments continue to convert paper-based systems and face to face services to ICT based storage and online provisioning, ensuring effective interoperability passes from a desirable goal to an essential requirement.</p>
				<p><strong><em>Transition tools:</em></strong> The short shelf life of modern ICT technology provides a more rapid, if still difficult, means for governments and other large enterprises to transition from isolated legacy systems to interoperable enterprise-wide networks. Since new hardware and software must be replaced or upgraded every few years, the old can theoretically be swapped out for the new, although doing so while the same systems remain in operation presents challenges. The means of accomplishing this feat is through the careful development and deployment of tools that not only describe the desired interoperability end state and the standards needed to enable it, but also facilitate the gradual migration from the old systems to the new.</p>
				<p>Governments utilize the same techniques that complex commercial enterprises use to bring legacy systems under control, such as designing and adopting "interoperability frameworks" that define and mandate the architectures into which new technology purchases must fit and the standards that they must support. The results should be lower costs, increased efficiency, and interoperability not only within, but among, agencies &mdash; usually for the first time. Where increasing transparency and interaction is also a goal, the same tools should be designed to ensure that appropriate information can be accessible to, and freely exchangeable with, citizens as well.</p>
				<p><strong><em>Special challenges:</em></strong> Governments have special challenges not shared by commercial enterprises when they seek to establish inter-governmental (e.g., among agencies, states, nations, and/or municipalities) as well as intra-governmental interoperability. These challenges are often exacerbated by the incredibly Byzantine collection of proprietary, legacy systems that many governments have accumulated over the years.<sup>4</sup> These additional dimensions can greatly multiply the difficulty of agreeing upon, designing and deploying the solutions needed to achieve success.</p>
				<p>For large governmental units, interoperability challenges will therefore often be quantitatively different from those encountered by all but the largest commercial enterprises.<sup>5</sup> In the first instance, government ICT systems can be extremely large &mdash; more vast than those of even the greatest multinational corporations. They can also be more architecturally diverse, where each department has exercised independence in ICT procurement over several decades. The difficulties of making progress in such a case are multiplied when achieving public goals requires the exchange of data not only with external private industry partners, but also with a diverse host of public sector partners, such as states, municipalities, first responders, and more.</p>
				<p>Governments have interoperability needs that are qualitatively different as well. For example, while a corporation may need to retain records for ten years at most, a government must plan to preserve some categories of documents indefinitely, resulting in the need to develop and utilize format standards that will hopefully be accessible a hundred or more years into the future. Similarly, while a private company may concern itself only with communicating with those market segments that it regards as most attractive, a government should make its information and services accessible to all of its citizens, rich and poor, well educated and otherwise, able-bodied and disabled. Proactively, it may also wish to exercise its procurement power in such a way as to provide incentives for industry to move in directions that the government deems to be socially beneficial.</p>
				<p>For better or worse, the awareness of such special needs and the inadequacy of current systems to meet them has only begun to emerge in the last several years. As a result, governments are only beginning to consider what special retooling efforts are incumbent upon them. Acting on these needs, once realized, is complicated by factors such as cost, the low level of familiarity of most legislators technical matters, and the lobbying efforts of vendors that may have more to lose than to gain by progressive government action.</p>
				<p>Nonetheless, awareness is rising in many parts of the world, both regionally (as in the European Union), nationally (as in Malaysia, South Africa, Brazil, India, and a variety of other primarily emerging countries), and within individual provinces, states, and even municipalities.<sup>6</sup> Some of these efforts have emerged as recently as last year, while others, such as those in the EU, have been ongoing for many years. The latter in particular provide useful examples that other governments would do well to examine and emulate to a greater or lesser extent, as best suits their individual policy goals and political sensibilities.</p>
				<div class="calloutright">
					<p>For large governmental units, interoperability challenges will often be quantitatively different from those encountered by all but the largest commercial enterprises.</p>
				</div>
				<p><strong><em>A case study: the IDABC:</em></strong> One of the most ambitious and interesting efforts to achieve both internal interoperability as well as efficient and open government/citizen interaction bears an imposing title: the <em>Interoperable Delivery of European eGovernment Services to public Administration, Business and Citizens</em> (IDABC) programme of the European Commission (EC). While the IDABC programme is but one of a number of completed and ongoing efforts to be found throughout the world at all levels, it may well be the most sophisticated and well advanced of these efforts. The reasons can be found in the unique political, economic and social history of the European Union itself. This history has led to a far greater level of government awareness in Europe, in comparison to (for example) the United States, of the value that standards can, and at times must, play in achieving commercial and social objectives. The program of the IDABC is also notable for the degree to which it incorporates open source software into its political and practical consideration.</p>
				<p><strong><em>The Vision of a Common Market (and more):</em></strong> One of the great commercial and social successes of the post-World War II era has been the ongoing rationalization and liberalization of commerce, monetary systems and travel within an expanding (first European Economic Community, and subsequently) European Union. Many challenges have been encountered and met in that process, with some having a higher public profile than others.</p>
				<p>One of the less-visible hurdles the architects of the EU faced as they worked towards the creation of a common market involved deconstructing the many standards-based barriers that European nations, like other countries around the world, had created in order to give preferential treatment to the goods of their domestic industries over foreign products. That process was also constructive, as new regional standards-based strategies and institutions were created to promote European trade abroad.<sup>7</sup></p>
				<p>The result was the creation of what is the most sophisticated regional standards infrastructure in the world today. Unlike other such organizations (e.g., the <a href="http://www.copant.org/English/index.asp">Pan-American Standards Commission</a>, commonly known as COPANT), economic as well as political goals served to incentivize EU-wide standards activities, to stronger and more sustaining effect. The resulting benefits to the nations of the EU have been numerous, extending beyond the central goal of facilitating internal trade. One indirect result, often noted with some grumbling elsewhere in the world, is the ability of EU members states to exercise disproportionate influence in "one nation, one vote" standards bodies such as the ISO, IEC and ITU, and also to identify standards goals of common interest and concern that can then be jointly addressed, to the benefit of European industry.<sup>8</sup></p>
				<p><strong><em>The vision of an interoperable Europe:</em></strong> Although some of the grander political dreams of pan-European proponents have not been realized (e.g., an EU Constitution has not thus far garnered the necessary votes to be adopted), the EC has moved well beyond purely trade related goals. In consequence, the need to achieve interoperability both horizontally as well as vertically among governmental entities has arisen in a way not found elsewhere, driven in part by the increasing level of services provided at the EU level to member states and their constituents. The complexity of the interoperability challenges of providing such "Pan-European eGovernment Services" (PEGS), and the essential role of standards in doing so, is suggested by this definition of PEGS:</p>
				<blockquote>Cross-border public sector services supplied by either national public administrations or EU public administrations provided to one another and to European businesses and citizens, in order to implement community legislation, by means of interoperable networks between public administrations.<sup>9</sup></blockquote>
				<p>The difficulty of providing PEGS and the sophistication required to parse out (even linguistically) how to do so are illustrated by the way in which the definition of "interoperability" has evolved over the last several years in IDABC documents. In 2004, a key document defined that word to mean:</p>
				<blockquote>[T]he ability of information and communication technology (ICT) systems and of the business processes they support to exchange data and to enable the sharing of information and knowledge.<sup>10</sup></blockquote>
				<p>By 2008, the political, commercial and technical challenges of achieving consensus around cross-border interoperability had risen, as demonstrated by the new definition for interoperability to be found in a comment draft relating to the revision of the same document:</p>
				<blockquote>[T]he ability of disparate and diverse organizations [principally administrations] to interact towards mutually beneficial and agreed common goals, involving the sharing of information and knowledge between the organizations via the business processes they support, by means of the exchange of data between their respective information and communication technology (ICT) systems.<sup>11</sup></blockquote>
				<p>Moreover, the same comment draft goes on to observe:</p>
				<blockquote>It is also worth noting that interoperability is neither ad-hoc, nor unilateral (nor even bilateral) in nature. Rather, it is best understood as a <strong><em>shared value of a community</em></strong> [emphasis in the original].<sup>12</sup></blockquote>
				<p>Uniquely in the world (at least since the collapse of the Soviet Union), the EU represents a region where enabling standards-based interoperability among and within sovereign nations must rise to the level of a core policy priority. This level of importance, conjoined with the multi-layered, multi-national context within which this policy is being pursued, has led to a similarly unique sensitivity to both the political as well as the technological nuances and complexity of the challenges at hand. Discussions relating to "openness" and "interoperability" therefore a level of awareness of non-technical concerns that is not commonly encountered in dialogues in governments elsewhere in the world &mdash; and rarely, if ever, in the United States.</p>
				<p>While the EU's situation is unique, its special challenges have led it to consider policy dimensions that the designers of public interoperability frameworks elsewhere should rightly consider. What follows is a brief review of some of the history and elements of the IDABC's work programme.</p>
				<p><strong><em>The IDABC and its projects:</em></strong> The need to achieve EU-wide interoperability was recognized at the Seville Summit, held in June of 2002, at which the members of the EU adopted the "eEurope Action Plan 2005."<sup>13</sup> Specifically, the Plan directed the European Commission, "to issue an agreed interoperability framework to support the delivery of pan-European eGovernment services to citizens and enterprises," which came to be called the <em>European Interoperability Framework for Pan-European eGovernment Services</em> (and more briefly as simply the "EIF"). The plan also specified that the framework was to be, "based on open standards and encourage the use of open source software."<sup>14</sup></p>
				<p>The first version of the EIF was released in 2004, and the second version is now in a state of active preparation. In July of 2008, a lengthy "Draft document as basis for EIF 2.0" ("Comment Draft") was released for public comments during a comment period that closed in September of the same year. This document will serve as one of the significant inputs in upgrading the first version of the EIF.</p>
				<div class="calloutright">
					<p>The IDABC Comment Draft is intriguing in the way that it provides a real-time map of how European thinking on interoperability continues to evolve</p>
				</div>
				<p>The Comment Draft is intriguing in the way that it provides a real-time map of how European thinking on interoperability continues to evolve in tandem with emerging public opinion against the backdrop of events such as the failure of the European Constitution and new patent legislation to be adopted, the burgeoning success of open source software, and publicly reported investigations and prosecutions of proprietary vendors for anticompetitive behavior by the European Commission.<sup>15</sup></p>
				<p>The EIF is but one of a suite of related deliverables in process, including the <em>European Interoperability Strategy</em> (EIS), the <em>European Interoperability Architecture Guidelines</em> (EAIG) and the <em>European Interoperability Infrastructure Services</em> (EIIS). Together they are intended to:</p>
				<blockquote>&hellip;provide the basic technical requirements of consumers of eGovernment services, cover the lifecycle from strategy through to operations, and provide IT vendors and suppliers with reliable information on their costumers' needs in this area.</blockquote>
				<p><strong><em>EIF Principles and "Open Standards:"</em></strong> The EIF is more informative than the typical private sector interoperability framework, perhaps by reason of the fact that the powers of the IDABC vis-&agrave;-vis the Member States are only advisory in nature. As a result, the EIF comprises goals, detailed discussions, and a total of 17 recommendations, some of which are designated as "organizational," "semantic" or "technical." The interoperability goals of the EIF are further informed by a set of "underlying principles," intended to serve a range of both universal, as well as EU-specific, social values and objectives. Those principles are <em>Accessibility, Multilingualism, Security, Privacy (Personal Data Protection), Subsidiarity</em>,<sup>16</sup> <em>Use of Open Standards, Assess the Benefits of Open Software</em>, and <em>Use of Multilateral Solutions</em>. These principles, as stated in Recommendation 2 of EIF 1.0, "should be considered for any eGovernment services to be set up at a pan-European level."<sup>17</sup></p>
				<p>These principles can be divided into several categories: including those that any properly motivated government should want to adopt on principal (e.g., accessibility), those that, for technical reasons, they would need to adopt (open standards), those to which it should adhere in order to be responsible custodians of their citizens data (privacy and security), and those that, for economic reasons as customers, they might wish to adopt (use of open source software).</p>
				<p>However, these same principles involve (or can involve) other policy decisions as well: does a government want: to drive further development of accessibility features in additional products; to ensure that the standards it supports are vendor neutral; to encourage the further development generally of open source software?</p>
				<p>The answers to those questions will vary, based upon the trade and social policies of the government in question, the degree to which lobbyists affect its decisions, and (in the case of the EU), sensitive and evolving relations between Brussels and Member States. Some decisions (such as supporting multilingualism) may be givens in some situations, and politically charged in others. What is particularly interesting and instructive about the IDABC's work is the degree to which so many of these questions (some subtle), and others (such as subsidiarity) have been considered and addressed.</p>
				<p>While other governments will be unlikely to find it appropriate to adopt principles that are identical in all cases to those articulated in the EIF, the IDABC's work provides a very instructive model deserving of close attention for the degree to which its drafters have comprehended the types of social, commercial and political dimensions that a government ICT policy can incorporate to not only satisfy a government's obligations and maximize the efficiency of its own procurement activities, to pursue its policy goals as well.</p>
				<p>Each of the principles set forth in the EIF could be considered to be relevant to a larger definition of "open standards," at least to the extent that they are dependent upon standards to enable them (e.g., Web-based accessibility relies on a number of standards, as does the ability of a document format to accommodate reading from right to left, or the Unicode to incorporate linguistic character sets). Perhaps because so many common open standards criteria are picked up in other principles, the definition of Open Standards that appears in the EIF is comparatively narrow.</p>
				<p>That said, the text of the "Use Open Standards" principle in EIF 1.0 is instructive:</p>
				<blockquote>The following are the minimal characteristics that a specification and its attendant documents must have in order to be considered an open standard:</blockquote> 
				<ol>
					<li>The standard is adopted and will be maintained by a not-for-profit organisation, and its ongoing development occurs on the basis of an open decision-making procedure available to all interested parties (consensus or majority decision etc.).<br /><br /></li>
					<li>The standard has been published and the standard specification document is available either freely or at a nominal charge. It must be permissible to all to copy, distribute and use it for no fee or at a nominal fee.<br /><br /></li>
					<li>The intellectual property - i.e. patents possibly present - of (parts of) the standard is made irrevocably available on a royalty free basis.<sup>18</sup></li>
				</ol>
				<p>The most notable element of the definition above,  from a market perspective, is the last, which precludes any need to pay royalties to a patent owner in order to implement a standard that meets these "minimal characteristics."  This is a dramatic departure from traditional practice, as the intellectual property policy rules of each of the "Big I's" (ISO, IEC and ITU), whose standards have in the past been of greatest interest to governments, all permit a patent owner to require payment of a "reasonable royalty" if its patent would be infringed.</p>
				<p>The IDABC appears determined to press further rather than retreat from this position.  The basis document for the next version of the EIF takes pains to flesh out the intention of the brief statement quoted above:</p>
				<blockquote>Since the publication of version 1 of the EIF, several practical cases have however shown the necessity to clearly point out the extent of this definition and to clarify its applicability&hellip;</blockquote>
				<ol>
					<li>Open standards or technical specifications must allow all interested parties to implement the standards and to compete on quality and price. The goal is to have a competitive and innovative industry, not to protect market shares by raising obstacles to newcomers.  Also, we want to be able to choose open source solutions or proprietary solutions on the basis of price/quality consideration&hellip;<br /><br /></li>
					<li>This definition reflects a consumer's viewpoint, with his needs uppermost in mind&hellip;<sup>19</sup></li>
				</ol>
				<p>The requirement of free implementation and the preference for open source software provide examples of two of the types of motivations referred to above at work.  The first is the self interest of government as a customer, desiring access to the widest choice of products at the lowest cost (open standards allow multiple vendors to develop competing products, providing more alternative products with more value-added, differentiating features while driving down prices; open source software is often free, usually resulting in a lower total cost of ownership throughout the life of the product).</p>
				<div class="calloutright">
					<p>The commitment of the Obama administration to bring a new level of transparency and par- ticipation to government offers an opportunity to achieve what was promised, but not delivered, by the Bush administration.</p>
				</div>
				<p>The second motivation derives from a policy goal, because government purchasing represents a large enough sales opportunity to incentivize standards developers to create standards that will qualify for recommended EU procurement purposes.  Once these standards become widely adopted, citizens can buy the same products, and enjoy the same wider choices and lower costs &mdash; all through the exercise of the "soft" power of procurement, rather than the heavy hand of government regulation.</p>
				<p><strong><em>Next Steps:</em></strong> The commitment of the Obama administration to bring a new level of transparency and participation to government offers an opportunity to achieve what was promised, but not delivered, under the E-Government Act of the Bush administration, adopted in 2002.  Indeed, the promises of President Obama are in large part simply elaborations of the goals of the prior Act, which read as follows:</p>
				<ol>
					<li>To promote use of the Internet and other information technologies to provide increased opportunities for citizen participation in Government.<br /><br /></li>
					<li>To promote interagency collaboration in providing electronic Government services, where this collaboration would improve the service to citizens by integrating related functions, and in the use of internal electronic Government processes, where this collaboration would improve the efficiency and effectiveness of the processes.<br /><br /></li>
					<li>To promote the use of the Internet and emerging technologies within and across Government agencies to provide citizen-centric Government information and services.<br /><br /></li>
					<li>To make the Federal Government more transparent and accountable.<br /><br /></li>
					<li>To provide enhanced access to Government information and services in a manner consistent with laws regarding protection of personal privacy, national security, records retention, access for persons with disabilities, and other relevant laws.<sup>20</sup></li>
				</ol>
				<p>Similarly, the E-Government act included provisions to bring about interoperability within government as well.  Given that the statutory basis for action is in place, with origins across the aisle from the President's party, the opportunity for progress is apparent.</p>
				<p>The question is whether the new president, beset with so many seemingly more urgent issues, will proceed with greater determination than his predecessor.  Hopefully, that will be the case, given that attaining the reality of open government is dramatically less expensive, far less technically challenging, and administratively much simpler (for example) than transitioning to an efficient, cost effective national system of electronic health records (EHRs).  Making the transition to open government is one of the few important policy goals that President Obama can actually delegate.</p>
				<p>There is a very real danger that the design of open government systems under the Obama initiative will be treated as a purely technical exercise, to be carried out by IT staff that will be primarily concerned with achieving interoperability among agencies, with public access arising in their thinking as a purely technical veneer to be dealt with as an afterthought.  As demonstrated by the example of the IDABC's EIF, such a neutered technical exercise risks not only failing to ensure equal accessibility, but would also fail to take advantage of other policy goals that the administration might wish to further at little, if any, additional cost.<sup>21</sup></p>
				<p>What the open government challenge shares with the EHR challenge is the fact that both are standards-dependent, and that neither will succeed unless the proper standards are available and selected before deployment exists.  If the wrong standards are chosen, and if the policy goals identified are too limited, then the results will suffer proportionately.</p>
				<p>Where open government and EHRs diverge is that in the former case, the standards are largely available, while in the latter many remain to be developed.  But in each case,  the process must begin by properly defining the goals that the standards must serve.  Those goals are comparatively clear in the EHR context.  They are less so (or at least consensus has been difficult to achieve) in the case of open government, as demonstrated by the failure of bills in multiple states across multiple legislative sessions to establish rules regulating to use of even a single type of standards (open document formats).</p>
				<p>What is urgently needed is a public dialogue about the social and policy goals that open government IT platforms should support, so that the actual work of selecting standards and making procurement decisions can proceed in an informed and efficient manner.  Otherwise, we may find ourselves repeating the same exercise under the next administration once again.</p>
				<p class="center">Copyright 2009 Andrew Updegrove</p>
				<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
				<p><strong>End Notes</strong></p>
				<p><sup>1</sup> <a href="http://www.whitehouse.gov/the_press_office/TransparencyandOpenGovernment/">Memorandum for the Heads of Executive Departments and Agencies</a>, Subject: Transparency and Open Government, at <a href="http://www.whitehouse.gov/the_press_office/TransparencyandOpenGovernment/">http://www.whitehouse.gov/the_press_office/TransparencyandOpenGovernment/</a> and subsequently reproduced in the Federal Register. All on-line material cited in this article was accessed on April 7, 2009.</p>
				<p><sup>2</sup> A current example on the regulatory front involves XBRL (for "Extensible Business Reporting Language"), one of the vast and still increasing set of XML-based standards. The Securities and Exchange Commission in the United States is requiring public reporting companies to transition to reporting financial information in this format so that it can be more easily searched, compared, and repurposed.</p>
				<p><sup>3</sup> I have written at length in the past on the risks that this transition can pose to the exercise of civil rights, such as freedom of expression, freedom of association, and the ability to interact with government. I refer to these freedoms, as exercised on-line, as "Civil ICT Rights," and to the standards that are essential to protect them as "Civil ICT Standards," and have argued that the process and rules regulating the development of such standards should themselves be held to a higher and more rigorous standard in consequence. See, for example, my article "<a href="/bulletins/feb08.php#feature">A Proposal to Recognize the Special Status of 'Civil ICT Standards</a>,'" appearing in Standards Today, Vol. VII, No. 2 (February &ndash; March 2008) at http://www.consortiuminfo.org/bulletins/feb08.php#feature.</p>
				<p><sup>4</sup> Peter Quinn, the Massachusetts CIO that pioneered adoption of the OpenDocument Format (ODF) standard by governments, was fond of observing that if a proprietary system had ever existed, the Massachusetts Executive Agencies had certainly bought at least one of them.</p>
				<p><sup>5</sup> By way of example, the Executive Agencies of the Commonwealth of Massachusetts, a small state by U.S. standards, utilize over 50,000 desktop systems spread across more than a dozen agencies, each with its own budget and procurement authority. Moreover, unlike a private sector CIO, the Massachusetts CIO may only issue guidelines, and not mandatory procurement requirements.</p>
				<p><sup>6</sup> The recent competition between proponents of ODF and Microsoft's competing XML-based standard, commonly referred to as "OOXML" (for Office Open XML), has provided the most visible sampling of government action in this regard). Both ODF and OOXML have been adopted by ISO/IEC JTC 1 as document format standards). Bills to impose rules for assessing document format standards, such as ODF and OOXML, have been introduced in more than a half dozen U.S. states (mostly without success). Internationally, adoption of ODF is tracked by the ODF Alliance, which <a href="http://www.odfalliance.org/press/Release20081222-annual-report-odf-2008.pdf">reports</a> (as of the end of 2008) that a total of 16 national and 8 provincial governments have either required or recommended use of ODF. See <a href="http://www.odfalliance.org/press/Release20081222-annual-report-odf-2008.pdf">http://www.odfalliance.org/press/Release20081222-annual-report-odf-2008.pdf</a></p>
				<p><sup>7</sup> The new institutions created include officially recognized (but independent) organizations such as the <a href="http://www.etsi.org/website/homepage.aspx">European Telecommunications Standards Institute</a> (ETSI), founded in 1988 by the European Conference of Postal and Telecommunications Administrations and recognized by the European Commission, the <a href="http://www.cen.eu/cenorm/homepage.htm">European Committee for Standardization</a> (CEN), formed in 1961 by the National Bodies of the then members of the EEC and EFTA, and unofficial bodies such as the <a href="http://www.ebu.ch/en/">European Broadcasting Union</a> (EBU), established in 1950.</p>
				<p><sup>8</sup> Europe's progress in aerospace standards is an example. EU efforts to advance the interests of local aerospace companies have been supported by the development of a wide variety of standards by European standards organizations. The result is that it is generally conceded that Europe has taken the lead away from the United States in aerospace standardization. See, Updegrove, Andrew, <a href="/bulletins/july05.php#feature">Standards in Space: an Industry and a Process at a Crossroads</a>, ConsortiumInfo.org, Consortium Standards Bulletin, Vol. IV, No. 7, July 2005, at <a href="/bulletins/july05.php#feature">http://www.consortiuminfo.org/bulletins/july05.php#feature</a></p>
				<p><sup>9</sup> Draft document as basis for EIF 2.0, 15/07/08, p.5, at <a href="http://ec.europa.eu/idabc/servlets/Doc?id=31508">http://ec.europa.eu/idabc/servlets/Doc?id=31508</a> (accessed August 2, 2008)</p>
				<p><sup>10</sup> <a href="http://ec.europa.eu/idabc/servlets/Doc?id=19529">European Interoperability Framework for Pan-European eGovernment Services v. 1.0</a>, European Commission 2004, Section 1.1.2, p. 5, at <a href="http://ec.europa.eu/idabc/servlets/Doc?id=19529">http://ec.europa.eu/idabc/servlets/Doc?id=19529</a> (accessed August 2, 2008).</p>
				<p><sup>11</sup> Draft document as basis for EIF 2.0, Ibid.</p>
				<p><sup>12</sup> Ibid</p>
				<p><sup>13</sup> For earlier EU actions recognizing the importance of the "pan European dimension of eGovernment" and the role of interoperability in pursuit of that goal, see Section 1.2 of the Framework.</p>
				<p><sup>14</sup> Version 1.0 of the <a href="http://ec.europa.eu/idabc/servlets/Doc?id=19529">European Interoperability Framework for Pan-European eGovernment Services</a> (2004) can be found at <a href="http://ec.europa.eu/idabc/servlets/Doc?id=19529">http://ec.europa.eu/idabc/servlets/Doc?id=19529</a></p>
				<p><sup>15</sup> Whether all changes have real substance is open to question. By way of example, one suggested goal for EIF 2.0 reads as follows, followed by the analogous goal included in EIF 1.0:</p>
				<blockquote>New: To support the European Union's strategy of providing user-centered eServices by facilitating the interoperability of services and systems between public administrations, as well as between administrations and the public (citizens and enterprises), at a pan-European level.</blockquote>
				<blockquote>Old: To serve as the basis for European seamless interoperability in public services delivery, thereby providing better public services at EU level.</blockquote>
				<p><sup>16</sup> Subsidiarity is an EU term recognizing a requirement that decisions must be made by the governmental unit that is as "close as possible" to the citizen. Hence, unless a decision is one that has already been reserved to the EU, it should be taken at the national, regional or local level, unless it would be more effectively taken at the EU level. As applied in EIF 1.0, "The guidance provided by the European Interoperability Framework is concerned with the pan-European level of the services. In line with the principle of subsidiarity, the guidance does not interfere with the internal workings of administrations and EU Institutions. It will be up to each Member State and EU Institution to take the necessary steps to ensure interoperability at a pan-European level."</p>
				<p><sup>17</sup> While length constraints limit the discussion above to the "use open standards" principal, each of the other principles is worth careful attention.</p>
				<p><sup>18</sup> The most analogous provision in the United States can be found in OMB Circular A-119, which generally requires government agencies to specify (with various exceptions) "voluntary consensus standards" when they are available instead of "government unique standards" in procurement orders. The most significant difference between the two definitions, from a commercial point of view, is the EIF exclusion of royalties; OMB A-119 follows the traditional practice of recognizing a patent owners right to charge a "reasonable royalty" for an infringing implementation of a standard, Office of Management and Budget <a href="http://www.whitehouse.gov/omb/circulars/a119/a119.html">Circular No. A-119</a>, Section 4.1, at <a href="http://www.whitehouse.gov/omb/circulars/a119/a119.html">http://www.whitehouse.gov/omb/circulars/a119/a119.html</a></p>
				<p><sup>19</sup> IDABC, <a href="http://ec.europa.eu/idabc/servlets/Doc?id=31597">Draft document as basis for EIF 2.0</a>, Section 8.4, p. 61, European Community 2008, at http://ec.europa.eu/idabc/servlets/Doc?id=31597</p>
				<p><sup>20</sup> The complementary goals, as set forth in President Obama's Memorandum to Heads of Agencies and Departments, read as follows:</p>
				<p><em>Government should be transparent</em>.  Transparency promotes accountability and provides information for citizens about what their Government is doing.  Information maintained by the Federal Government is a national asset. My Administration will take appropriate action, consistent with law and policy, to disclose information rapidly in forms that the public can readily find and use. Executive departments and agencies should harness new technologies to put information about their operations and decisions online and readily available to the public. Executive departments and agencies should also solicit public feedback to identify information of greatest use to the public.</p>
				<p><em>Government should be participatory</em>. Public engagement enhances the Government's effectiveness and improves the quality of its decisions. Knowledge is widely dispersed in society, and public officials benefit from having access to that dispersed knowledge. Executive departments and agencies should offer Americans increased opportunities to participate in policymaking and to provide their Government with the benefits of their collective expertise and information. Executive departments and agencies should also solicit public input on how we can increase and improve opportunities for public participation in Government.</p>
				<p><em>Government should be collaborative</em>.  Collaboration actively engages Americans in the work of their Government. Executive departments and agencies should use innovative tools, methods, and systems to cooperate among themselves, across all levels of Government, and with nonprofit organizations, businesses, and individuals in the private sector.  Executive departments and agencies should solicit public feedback to assess and improve their level of collaboration and to identify new opportunities for cooperation.</p>
				<p><sup>21</sup> The basic question is whether those that make the decisions will place the civil servant, or the citizen, first. I recently attended a panel discussion at a conference in Europe, where a government speaker noted the difficulties his country was encountering in deploying a "single sign on" requirement that would permit any citizen to access any government Web site using the same user name and password. Despite the costs and complexities involved, his government had taken the enlightened approach that the government should accommodate its citizens, and not the other way around. What decision will the United States make, when faced with the same litmus test decision?</p>