				<!-- ******************* -->
				<!--   FEATURE ARTICLE   -->
				<!-- ******************* -->
				<h3>ODF vs. OOXML<br />and the Future of the Great Powers of IT</h3>
				<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a><sup>1</sup></p>
				<blockquote class="openingquote"><em><strong>Abstract:&nbsp;</strong>Great companies, like great national powers, compete aggressively &mdash; not for territory and resources, but for customers and cash. Just as countries fall into hierarchies of power and alliances for long periods of time based upon their respective advantages at the beginning of such periods, or the outcome of wars, multinational corporations often succeed in establishing themselves in power positions that must be jealously defended. In both cases, the factors upon which dominant positions were originally established inevitably change even as their competitors become increasingly determined to supplant the incumbents. Today, the information technology (IT) marketplace may be on the verge of a fundamental reordering of its "Great Powers" as new technologies (e.g., Software as a Service) and new strategies alter the landscape upon which Microsoft's dominance has to date been based. This article examines the conflict being waged between Microsoft and its commercial rivals over document format standards, attempting to examine the underlying forces, motivations, strategies, and possible outcomes that this contentious standards war helps reveal.</em></blockquote>
				<p><strong><em>Introduction:&nbsp;</em></strong>Perhaps the most significant development in the information technology industry over the last thirty years has been the degree to which a single company &mdash; Microsoft &mdash; has succeeded in achieving dominance.  During that short period of time, a startup company founded by two college dropouts attained a level of influence in software equal to that which IBM already enjoyed in hardware on the date that Microsoft was launched.  With over $50 billion in revenues today, Microsoft has become by far the largest software company in the world today, and wields by far the greatest influence over the user experience on the desktop.</p>
				<p>This enviable position has been attained in part through Microsoft's strategic role as the owner of the most popular operating system in use today (Windows) and as a result of the enormous profits it reaps from its monopoly position in office productivity software (through its Office suite, which includes the Word word processing, Excel spreadsheet, and PowerPoint spreadsheet software, among other tools).  Overall, Microsoft's office software division generated almost one third of total revenues in 2007, and contributed a disproportionately high $10 billion in profits to the bottom line.  The profits of this division have helped underwrite Microsoft's ongoing efforts to expand into a wide variety of other products in services, in many cases with mixed success, at best.</p>
				<p>Today, however, Microsoft's hegemony is being threatened on a number of fronts, largely as a result of fundamental technical, political and societal changes in the marketplace itself.  Not unlike the way in empires have historically risen, only to eventually become threatened by new forces, Microsoft is becoming increasingly vulnerable to a number of systemic changes that are undercutting the unique advantages that it has enjoyed since achieving dominance in the operating system and office suite software markets.</p>
				<p>To extend that analogy, just as international tensions and nationalist aspirations undermined the stability of Europe in the years preceding World War I, market forces in the IT industry today are building to a point where a radical restructuring of the landscape may be at hand, leading to a rebalancing of powers after a period of commercial conflict.  Those forces include the rise of new and powerful companies (like Google) that are able to deploy increasingly powerful Internet-based technologies that threaten the desktop paradigm that has provided the foundation for Microsoft's traditional strength.  Older companies that are eager to find a means to challenge the entrenched market incumbent at last are willing to adopt strategies based on new technologies and business models, such as the deployment of software as a service (SaaS) to similar affect.</p>
				<p>At the same time, accumulated resentments on the part of consumers seeking wider choices, governments seeking greater control over their archives, and even what might appropriately be called new ideologies involving "openness" in standards and software licensing terms are providing the impetus for the equivalent of a popular uprising at the level of the end user.</p>
				<p>One of the challenges that Microsoft faces today that typifies this tense competitive landscape arises from changing customer expectations regarding the formats in which documents of all types are created.  In 2005, an XML-based standard called OpenDocument Format (ODF), was approved by the Organization for the Advancement of Structured Information Standards, more commonly known as OASIS.  The purpose of ODF is to enable compliant software to create text, spreadsheet, presentation documents that can be opened, edited and saved by other ODF compliant software.  Later the same year, OASIS submitted ODF to ISO/IEC JTC1 for adoption, which followed in May of 2006.</p>
				<p>Microsoft, which has been a member of OASIS since before the ODF Technical Committee was formed (and had a representative on the OASIS Board of Directors throughout most of the period during which ODF was developed) opted to neither join in the development effort, nor to implement ODF after it was approved as an OASIS standard.  Instead, it developed and implemented its own XML-based format, which it called Office Open XML (OOXML).  In late 2005, Microsoft submitted OOXML to Ecma, another standards body, which adopted the specification in 2006 and, as planned, submitted it for consideration by ISO/IEC JTC1, so that if approved it would enjoy equal status with ODF in the eyes of customers.</p>
				<p>Unlike ODF, which was rapidly approved without objection, however, the progress of OOXML through ISO/IEC JTC1 has been contentious and, thus far, unsuccessful (a final decision will be made in March of 2008 following a week-long meeting in Geneva, Switzerland to address 3522 comments registered during a five month review period in 2007).  OOXML's difficulties have been based in part on its technical imperfections, end user objections and Microsoft's own at times heavy handed conduct.  But the level and effectiveness of resistance to OOXML has also been fueled by the significant resources dedicated to that effort by a variety of Microsoft's competitors, and most visibly by IBM.</p>
				<p>The conflict between the proponents of ODF, on the one hand, and of OOXML, on the other, has presented one of the most public standards wars in the history of the IT industry.  In this article, I will review some of the changes in the competitive landscape that have led each side to choose open document formats as a field upon which to fight one of the first great battles that may fundamentally change the balance of powers in the IT industry.</p>
				<p><strong>I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A Changing IT Landscape</strong></p>
				<p>Why has it taken so long for Microsoft's competitors to mount a serious attack against Office, and why have they decided that the time is now ripe to make the expenditure of time, resources, and strategic investment needed to make a credible assault?  There are a variety of reasons, some of which are new, and some of which represent long-standing issues, and others that have only lately become more critical.</p>
				<p><strong><em>Monopoly cost/benefit ratio for the customer:</em></strong> Microsoft has enjoyed a more than 90% market share in operating systems supporting the desktop and in office productivity software for many years.  While on its way to achieving that dominance, concerted efforts were made by many of its competitors (e.g., Apple, IBM, Digital Equipment, Sun Microsystems and many other system vendors), sometimes individually and sometimes collectively, to protect their existing businesses from erosion.  Similarly, the new software developers that initially dominated the productivity software market (e.g., Software Arts, Lotus Development Corporation, and WordPerfect) eventually became marginalized by Microsoft's success in applications, based in part on the fact that it controlled access to its operating system products, as well as their release schedule.</p>
				<p>In both cases, Microsoft's market power eventually reached a point where competing to break its monopoly position offered too little likelihood for success to justify the investment &mdash; at least during the continuance of the technological and market conditions under which Microsoft had achieved hegemony over the desktop.</p>
				<p>For a time, conditions did remain more or less constant, and in the initial years of Microsoft's ascent, there was much for customers to gain as well.  Most obviously, the existence of a <em>de facto</em> "standard" platform had many benefits.  That platform comprised a matched set of microprocessor (the Intel family of microprocessors launched with the 8086) and operating system (Microsoft DOS, eventually followed by Windows), which, atypically, was made available to multiple vendors, providing the incentive for the successful launch of many independent software vendors and the rapid proliferation of new software products that added value to the ownership of a computer.  With time, the availability of competitively priced and increasingly powerful "personal computers" from scores of vendors brought the cost of owning a computer at home as well as using one at work within the reach of most families.</p>
				<p>Moreover, up until the time when Microsoft achieved its monopoly power, new versions of Microsoft products, with new and improved features, were released on a frequent basis.  Often, Microsoft would add new features at no additional cost that previously could be found only in products that had to be purchased from its competitors.  Those products, not surprisingly, usually disappeared.</p>
				<p>As competition disappeared, so too did the incentive for Microsoft to issue new releases of its products.  Internet Explorer, which had gone through multiple versions while Microsoft was seeking to eliminate Netscape as a competitor, languished for almost seven years before it was next updated with a major release &mdash; and then only when Mozilla's market share topped 10%.  The release cycles of both Windows and Office slowed as well, and as a result, the value proposition for the customer of participating in a monopolized marketplace decreased.</p>
				<p>The result is that the customer now finds itself in a situation where Microsoft has the ability to maximize prices while minimizing investment in its own products, because there is no effective competition to either drive prices down, or innovation up.  In such a scenario, the costs in reduced competition and innovation can begin to outweigh the value of a de facto, single-vendor controlled standard, and raises the perceived value of consensus-based standards able to break the monopoly.</p>
				<p><strong><em>Effectiveness of product evolution:</em></strong> While Microsoft prides itself on its software development skills and its commitment to its customers, it is not immune from the usual effects and temptations that lack of competition inevitably produces.  Just as IBM was criticized in the 1980s and early 1990s for taking its customers for granted and defining quality by IBM's terms, rather than by its customers needs, Microsoft is able to decide which new features it will offer, how they should be engineered, when they should be released, and how best to craft them to Microsoft's maximum benefit from the standpoint of (among other things) maintain the lock in of its customers.</p>
				<p>Currently, Microsoft is encountering significant market resistance from those same customers, few of which have thus far chosen to upgrade to either Vista, Microsoft's newest operating system release, or to Office 2007.  Many purchasers of new computers are also requesting that the prior versions of each product be installed rather than the most current releases.  Indeed, some analysts are recommending that current Office 2003 users never upgrade to either product at all.  A recent example is a study just completed by Becta, the British Educational Communications and Technology Agency, which advised that "the costs of upgrading are significant, and the benefits unclear," notwithstanding the billions of dollars and thousands of years of engineering effort that Microsoft has invested in producing these new releases.</p>
				<p>Vista and Office 2007, whether separate or apart, also require significant user training.  Ironically, OpenOffice, the most popular of the ODF compliant competitors of Office, has a look and feel that is remarkably similar to Office.  The result is that it should be much easier for an existing Office user to learn, and therefore cheaper for their employer to train them, to convert to OpenOffice than to Office 2007.  Moreover, OpenOffice is free, and StarOffice 8, the enhanced version sold by Sun with support, is much more inexpensive than Office.</p>
				<p>The result is that it will be risky for Microsoft to discontinue selling either Windows XP (its availability has already been extended once) or the existing version of Office, because at least some purchasers of new computers may prefer to use OpenOffice rather than learn to use Office 2007, especially if they have previously downloaded a free copy of OpenOffice in order to open odt files received from others.</p>
				<p><strong><em>What is a "document?"</em></strong> Until the advent of the Internet and the Web, the concept of a document was largely unchanged from pre-IT times, although the means of producing a final, printed copy had changed, and the complexity and appearance of the final product was evolving rapidly.  Because the result was a physical copy, the office suite as we know it evolved into a monolithic product, for multiple good reasons: ease and economy of purchase and installation, and the ability to update data seamlessly between related documents (e.g., text documents and embedded or independent spreadsheets).</p>
				<p>For the decades of the PC revolution, the result was that the computer skills of many users were largely limited to knowing how to use the single product that satisfied the great majority of their needs.  Not surprisingly, they grew attached to their office suite.  Basing such products on proprietary formats made the lock in complete, as it became difficult to exchange documents between different systems or to permanently migrate existing documents to a new system, without loss of fidelity.</p>
				<p>With the rapidly expanding ways in which we now use the Internet and the Web, however, less and less of the text that an individual produces in the course of a given day are input using an office suite or standalone word processor at all, and especially so for younger users.  Instead, text is typed into instant messaging windows, email, Wikis and, increasingly, software resident on mobile devices.  The results are multiple:</p>
				<ol>
					<li><strong><em><u>Psychological independence</u>:</em></strong>  The days when the prospect of using a word processor other than Word would provoke anxiety are over.  Ordinary users find themselves regularly using new online software all the time, and are becoming increasingly comfortable with that experience.<br /><br /></li>
					<li><strong><em><u>Actual independence</u>:</em></strong> Just as many individuals are abandoning their landlines entirely, first purchasers of inexpensive computers that come preloaded with OpenOffice or Corel WordPerfect may feel no compunction to buy even an inexpensive copy of Word at all, due not only to their comfort level with alternatives, but also because they do not expect to make far less use of that software than did the end users of a decade ago.<br /><br /></li>
					<li><strong><em><u>Document management</u>:</em></strong> As more and more information is recorded through mobile devices, government and business CIOs are facing the daunting task of managing that information.  The value of traditional, desktop-produced documents is therefore declining as a percentage of the whole, and the value of being able to store, search and access data created on the fly in the most cost effective manner increases.<br /><br /></li>
					<li><strong><em><u>Operating system independence</u>:</em></strong> In the past, virtually all document creation was performed on two operating systems: Windows and Apple's current system, and Office was available on both.  Now, however, Linux is predominating as the operating system of choice on mobile phones, which are becoming increasingly "smart."  Initiatives such as Google's Android project will encourage significant development on these platforms, and many of these applications will be ODF based (several Google Apps already are).  If the solutions created for mobile devices that are based on ODF are of higher value, then additional pressure will be exerted in some businesses to converting desktop software to ODF compliant alternatives.  This year, after many false starts, Linux will also be making greater inroads on the desktop, now that more user-friendly versions, such as Ubuntu, and extremely inexpensive computers, such as those recently offered at Wal-Mart by Everex, are becoming available.</li>
				</ol>
				<p><strong><em>Change in competitor strategies:</em></strong> The objectives and strategies of Microsoft's competitors have changed in important ways:</p>
				<ol>
					<li><strong><em><u>Market size</u>:</em></strong> Microsoft acquired its dominant position at a time when vendors sought to "own" their customers, and during which the state of technology made it possible to do so.  However, with the advent of the Internet, truly open systems have become not only feasible, but much more in demand by customers.  They have also made it more difficult to achieve monopoly power and to maintain it.  As significantly, the size of the marketplace has become larger by orders of magnitude, making the attractiveness of having a piece of the pie as attractive today as having the whole pie a decade ago.  The result is that it is as attractive to open a market today as it was to control it in the past.<br /><br /></li>
					<li><strong><em><u>Business models</u>:</em></strong> Some of Microsoft's most powerful competitors (e.g., IBM) are changing their strategies to be much more services oriented, allowing them to benefit as much, or more, from markets with many competing products than from markets that they dominate with their own products.  The usual differential between profit margins on the sale of services versus the sale of products is diminished by the decrease in R&amp;D expense, while opportunity increases with the growth of the market available, and much of the risk passes to those still producing products upon which the services are based, so long as the services are widely based.<br /><br /></li>
					<li><strong><em><u>The rise of open source software</u>:</em></strong> After more than a decade of gestation, open source software (OSS) has become a trusted, pervasive reality in the marketplace.  Today, it would be difficult, if not impossible, to find any enterprise of any size that does not run multiple OSS programs, and Microsoft itself has a cooperative marketing relationship with Novell, which distributes a Linux distribution that has the second largest market share after rival Red Hat.  Increasingly, Microsoft's competitors are sharing R&amp;D expenses with a community of developers, placing them at a competitive cost advantage.  Customers are increasingly comfortable with OSS as well, regardless of whether the total cost of ownership (TCOE), after taking into account training and support, is less than the cost of comparable proprietary products.<br /><br /></li>
					<li><strong><em><u>New economic strategies</u>:</em></strong> As Microsoft's competitors have become comfortable with a goal of breaking Microsoft's monopoly without becoming monopolists themselves, they have come to an interesting realization: it can be as beneficial to give away replacements for Office as it can be to seek to outcompete Office with comparably priced competitive products.  Both Google, with its free (to small users) on-line Google Apps, and IBM, with its new, free on-line Symphony office suite, are seeking to supplant Office with no, or little, immediate revenue return.  Instead, they will benefit indirectly in multiple ways, with the biggest prize being the prospect of freeing up as much as possible of the IT budgets of large enterprise and small to medium enterprise (SME) users that currently fuels Microsoft's $16 billion in annual business software sales.<br /><br /></li>
					<li><strong><em><u>Architectural models</u>:</em></strong> After many years of discussion, increases in in broadband connections, decreases in the costs of servers, and other advances have now made the provisioning of SaaS a realistic alternative to customers.</li>
				</ol>
				<p>Microsoft, of course, could take advantage of the same trends and opportunities, but only at the risk of cannibalizing and/or weakening its own business.  To date, it has made some forays into open source software, and has publicly announced that it is working on Web based services.  Its historical practice, however, has been to see how the market develops, and then try and overtake the early entrants.  Whether that strategy will succeed in this new industry transformation, remains to be seen.</p>
				<p>Regardless of what Microsoft does or does not choose to do, its competitors can for the first time in  more than a decade see not only the means by which Microsoft's hold might be weakened, but more ways in which those competitors can directly and indirectly benefit.  Making an investment in promoting the advance of ODF therefore makes sound business sense to a variety of vendors, some of which have been more visible in their efforts in this regard than others.</p>
				<p><strong>II&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Catalyst for Action</strong></p>
				<p>In August of 1914, it was the violent act of a single individual that released the tensions that had been building in Europe for decades.  The result was war.  In a not totally dissimilar fashion, it was the decision of a single customer in August of 2005 that triggered a series of actions on the part of many of Microsoft's competitors, building on a history of accumulating frustrations and taking advantage of technological changes in the marketplace.  The immediate result was the transformation of ODF from an almost unknown standard into the rallying point for a small army of competitors eager to change the established order of the desktop.  That customer was the government of Massachusetts.<sup>2</sup></p>
				<p>The decision taken by the CIO and the Secretary of Administration and Finance of Massachusetts was made after a full year of deliberation and consultation with vendors, including Microsoft.  Although Microsoft had assumed earlier in the year that the Information Technology Division (ITD) would conclude that its OOXML formats would meet its definition of "open standards," the ITD reversed that decision over the summer.  Since Microsoft had already announced that it would not implement ODF, this meant that Office could no longer be used on the more than 50,000 desktops maintained by the ITD after January of 2008, the effective date of the policy decision.</p>
				<p>The decision was widely publicized, and caught the attention of other government CIOs.  It also caught the immediate interest of Microsoft's principal competitors.  Despite the later decision by Massachusetts to continue to use Office after Ecma adopted OOXML, the issue of open formats had been thrust into the spotlight, as well as the technical and commercial differences between ODF and OOXML.  The result was that both the importance of open formats, as well as the credibility of ODF, had become widely known.</p>
				<p>It is not surprising that the first large enterprise to opt for ODF was a government, although the benefits of ODF for governments are no different than for commercial or home users.  The awareness and importance of those benefits for government purchasers, however, was much higher, for several reasons:</p>
				<ol>
					<li><strong><em><u>Equal access and freedom of decisions</u>:</em></strong> As governments, like all other businesses, increasingly move their operations online, the question of endorsement of proprietary solutions becomes sensitive.  While a commercial entity may for its own convenience decide to accept (for example) only Word documents, or optimize its Web site only for use by visitors using Internet Explorer, citizens are becoming increasingly unhappy with governments that make similar decisions.  Indeed, when certain relief sites were set up in just that way in the wake of Katrina, some survivors using Mozilla or Safari as their only browser found themselves at a potentially life-threatening disadvantage.  Governments are therefore increasingly becoming committed to ensuring that no citizen should be denied equal access to government services based upon their IT choices, or forced to purchase products that have been, for all practical purposes, endorsed by government.  Governments are also increasingly sensitive to the need to ensure that government services meet the highest accessibility standards as well, and for similar reasons.<br /><br /></li>
					<li><strong><em><u>Long term access</u>:</em></strong> The ability to serve citizens on line, to create and archive documents electronically, and to take advantage of the other benefits of modern information and communications technology (ICT) is as seductive for governments as they are for private industry.  Moreover, governments are now beginning to plan the process of digitizing (and destroying) their vast archives of hard copy documents, and are therefore coming to realize the ephemeral nature not only of the media upon which electronic documents are maintained, but of the formats within which they are created.  Already, most government purchasers have suffered through at least one migration (most often from WordPerfect to Word), and are cognizant of the fact that, absent agreement upon open formats, documents created today may become totally unavailable in a surprisingly short period of time &mdash; much less in 100 years.<br /><br /></li>
					<li><strong><em><u>"Openness" awareness</u>:</em></strong> Many governments in Europe and elsewhere around the world (although not yet in the United States to the same extent) are becoming increasingly aware of, and partial to, adopting IT regimes that emphasize "openness" in multiple ways, including vendor independence as well as the ability to use OSS as widely as possible.  The less rigid requirements of ODF, as compared to OOXML (which maps to Office in very great detail) are therefore more philosophically attractive to such governments, especially as ODF has already been implemented by many OSS as well as proprietary office suite products.<br /><br /></li>
					<li><strong><em><u>Antitrust concerns</u>:</em></strong> Although the federal and state regulators in the United States have largely backed off of Microsoft in recent years, some governments abroad, and particularly in the EU, continue to keep Microsoft under active, and even increasing scrutiny.  Indeed, one reason that Microsoft has publicly given for opening up OOXML is in order to satisfy EU regulators.<sup>3</sup>  Independent of actual violations of antitrust laws, agencies and individual legislators in some countries continue to have a less friendly attitude towards Microsoft than towards some of its competitors.<br /><br /></li>
					<li><strong><em><u>Emerging and third world countries</u>:</em></strong> A number of nations find ODF compliant software attractive purely on price terms.  OpenOffice, the most advanced of the free, open source software (OSS) office suites that are compliant with ODF, has enjoyed particular success, with over 100 million copies downloaded from OpenOffice.org as of September 2007.  When used in connection with the free Linux operating system, the cost savings are even more dramatic, bringing increasing price pressure on Microsoft to gain as well as keep such customers.  In China, Microsoft has dropped the license fees for a basic Windows/Office package for students to an astonishing $3 per desktop.  The launch of the "One Laptop per Child" (OLPC) program, which uses OSS exclusively in order to provide an innovative, child-friendly laptop for only US $188, has invoked an aggressive marketing program by Intel directed at selling inexpensive, Windows based laptops to students in emerging countries.  Presumably, Intel has driven a hard bargain on the operating system for its own, under $400 "classmate" laptop.</li>
				</ol>
				<p><strong>III	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OOXML's Prospects in ISO/IEC JTC1</strong></p>
				<p>After the initial decision in Massachusetts, Microsoft opted to push its OOXML specification through the standards adoption process at the maximum speed possible, in an effort to neutralize the impact of the anticipated adoption of ODF by SC 34, the ISO/IEC JTC1 committee with authority over standards of this type.  Microsoft also decided to document OOXML in great detail, with the intention of describing all formatting aspects of Office-generated documents.  However, the  final result included many features deemed to be objectionable by reviewers when OOXML became publicly available, including dependencies on other Microsoft technology not described in the specification.  In some cases, OOXML also replicated Microsoft-unique features that did not conform to existing ISO/IEC standards, as well as at least one ancient "bug" that had long existed in Office, replication of which would be required in order to comply fully with OOXML.</p>
				<p>The first step chosen by Microsoft was to offer OOXML to Ecma, a European-based standards organization with a limited membership and a special relationship with ISO/IEC (Ecma is the sole entity that enjoys "Class A Liaison" status with ISO).  Ecma agreed to produce a specification that was faithful to the architecture that Microsoft was using as the basis for Office 2007, and commissioned a Technical Committee with the following Scope:</p>
				<blockquote>The goal of the Technical Committee is to produce a formal standard for office productivity applications within the Ecma International standards process which is fully compatible with the Office Open XML Formats. The aim is to enable the implementation of the Office Open XML Formats by a wide set of tools and platforms in order to foster interoperability across office productivity applications and with line-of-business systems. The Technical Committee will also be responsible for the ongoing maintenance and evolution of the standard.[emphasis added]<sup>4</sup></blockquote>
				<p>The new Technical Committee was also charged with five objectives, two of which were as follows:</p>
				<ol>
					<li class="numbers">Guarantee continuous use of the existing base of Microsoft Office documents without losing any of the functionalities [The page now reads:<br /><br /></li>
					<li class="numbers">Document all the options, properties, formatting, layout and other information of the existing Microsoft Office document base using the W3C XML 1.0 language<sup>5</sup></li>
				</ol>
				<p>After reformatting, the specification submitted by Microsoft was over 6,000 pages in length. It was adopted in that form by Ecma, and then submitted to ISO/IEC JTC1 for "Fast Track" consideration and adoption.</p>
				<p>OOXML failed to be approved at the end of a contentious process, in part because a large number of the 3,522 comments submitted could have been avoided through greater care in documenting the specification, greater willingness by Microsoft to implement existing ISO/IEC standards when it designed Office, and greater willingness to make technical concessions at the outset that would be inconvenient for Microsoft to implement. During the ISO/IEC review period, events were closely watched by open source and open standards supporters, who reported instances of alleged irregularities in a number of National Bodies. In one case, Microsoft admitted that one of its employees had offered marketing incentives to business partners that agreed to join the Swedish committee and vote in favor of OOXML. The Swedish vote was eventually thrown out by its chair, due to the fact that at least one member of the committee cast more than one vote.</p>
				<p>These reports and the failure of OOXML to be approved at the end of the normal review period earned negative publicity for Microsoft, as well as the ill will of some participants in the National Body processes in many countries. ODF, on the other hand, received an additional seven months to enjoy its status as an already-approved global standard. At the same time, however, members of some National Bodies complained that they had received too much attention from opponents of OOXML as well as proponents of that specification.<sup>6</sup></p>
				<p>Between the time that the Fast Track voting period closed on September 2 and today, Ecma has been working with Microsoft to develop a proposed resolution for each comment registered during the Fast Track period. On February 25 &mdash; 29 of this year, a Ballot Resolution Meeting (BRM) will be held in Geneva, Switzerland, at which delegations of eligible National Bodies will consider the "dispositions" proposed.</p>
				<p>As summarized by Alex Brown, the Convener appointed to manage the BRM,<sup>7</sup> those resolutions will largely fall into three categories:</p>
				<ol>
					<li>Straightforward acceptance (everyone agrees on the comment, its NB-proposed remedy is adopted as is);<br /><br /></li>
					<li>Modified acceptance (the gist of the comment is accepted, the proposed response differs from that originally suggested);<br /><br /></li>
					<li>Non-acceptance/non-response (the comment is not accepted).</li>
				</ol>
				<p>Brown hopes to expedite the process by submitting non-controversial dispositions for adoption in batches, where resolutions are expected to be non-controversial. However, delegates at the BRM will not have had a great deal of time to review some of the proposed resolutions; although batches of dispositions have been periodically posted to a password-protected website since December (each disposition, however, is a separate PDF file), a composite report of all proposed dispositions was not made available to the BRM delegates until January 14, 2008.</p>
				<p>After the BRM's work is completed, the eligible National Bodies will have one month to confirm or change their prior votes (any vote, whether to approve, withhold approval or abstain, can be changed to either of the other two alternatives). If the final count meets the complicated test used by JTC1,<sup>8</sup> then OOXML will become a global standard with equal status to ODF. Whether or not that will happen will depend in part upon the following variables:</p>
				<ol>
					<li><strong><em><u>Concessions generally</u>:</em></strong> First and foremost will be to what extent Microsoft is perceived to have accommodated the comments that have been registered. If Microsoft appears to have made a good faith effort to make changes that it will presumably implement in Office 2007, and especially changes that will take real effort on its part to implement, then much of the unhappiness generated by its tactics during the Fast Track review period may be offset.<br /><br /></li>
					<li><strong><em><u>Specific concessions</u>:</em></strong> Individual comments were registered by individual National Bodies. And while many National Bodies made similar comments, whether or not the specific changes requested by any one National Body have been accommodated to its satisfaction will have bearing on its final decision regarding approval.<br /><br /></li>
					<li><strong><em><u>Conduct</u>:</em></strong> During the Fast Track process, which involved multiple meetings in many countries and an influx of many new participants, a great deal of information reached blogs and journalists. Since the end of the review period, however, any lobbying activities of Microsoft, on the one hand, and the opponents of OOXML, on the other hand, has occurred largely behind the scenes, and little information has reached the public thus far. Accordingly, whether the 120 delegates (minus Ecma representatives) that are admitted to the BRM will be feeling friendly to Microsoft and OOXML or the opposite is unknown, but may be significant, depending upon how the contestants have comported themselves in the previous several months.<br /><br /></li>
					<li><strong><em><u>Events at the BRM</u>:</em></strong> What happens behind the closed doors may also remain largely unknown, as no reporters will be admitted and no transcript will be made available to the public. Because according to Alex Brown the BRM cannot be extended, one of the most important questions will be whether it will be possible for all significant comments to be successfully resolved during the week permitted for that process. If this does not occur, then open issues may remain that may lead some National Bodies to withhold approval that might otherwise have been granted.</li>
				</ol>
				<p>Will OOXML be approved? As of this writing, none of the directly involved participants that this author has contacted has a prediction in which s/he has confidence, and indeed with the proposed dispositions being made available so recently to the BRM delegates, any such predictions would be premature. Alex Brown offered the following assessment in a blog entry he wrote on December 15, 2007, during the return flight from Kyoto, where the last SC34 meeting prior to the BRM was held:</p>
				<blockquote>No neutral observer is being so foolish as to predict what will happen &mdash; on the long flight home I was pondering this and found (possibly as a result of too much in-flight Sake) a Haiku coming to mind which seemed to sum this up:</blockquote>
				<blockquote>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>Six thousand pages,<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And five days in Geneva;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Maybe it will pass.</em><sup>9</sup></blockquote>
				<p>Moreover, events are continuing to evolve rapidly as this article is being written. In the first week of January, journalists learned that Microsoft engineers had issued a "service pack" to the users of Office 2003, the product it hopes to replace with Office 2007. Users that dutifully updated their software found that the service pack had intentionally disabled their ability to open documents created by a wide variety of older document suites &mdash; including some prior versions of Office &mdash; due to "security concerns." The news was surprising, in light of the fact that Microsoft's major rationale for proposing OOXML rather than adopting ODF was because of the necessity of preserving access to, and the fidelity of, the "billions and billions" of documents already created by its customers using older versions of Office. A workaround solution proposed by Microsoft was extremely complex, and if performed incorrectly could render a PC unusable. Instead, Microsoft recommended a simple solution &mdash; upgrade to Office 2007.<sup>10</sup></p>
				<p>On January 14, the European Commission <a href="http://europa.eu/rapid/pressReleasesAction.do?reference=MEMO/08/19&amp;format=HTML&amp;aged=0&amp;language=EN&amp;guiLanguage=en">announced</a> that it was launching two new antitrust investigations into Microsoft's conduct, only a few month's after Microsoft settled a nine year dispute after losing an appeal in the European Court of First Instance. One investigation was in response to a 2006 complaint brought by the European Committee for Interoperable Systems (ECIS), an organization that includes Microsoft competitors such as IBM, Sun, and Oracle as members. That investigation will look into whether Microsoft's actions in relation to OOXML are intended to preserve its dominant market position. A press release issued by the regulators reads in part as follows:</p>
				<blockquote>As regards interoperability, in its Microsoft judgment of 17 September 2007, the Court of First Instance confirmed the principles that must be respected by dominant companies as regards interoperability disclosures. In the complaint by ECIS, Microsoft is alleged to have illegally refused to disclose interoperability information across a broad range of products, including information related to its Office suite, a number of its server products, and also in relation to the so called .NET Framework. The Commission's examination will therefore focus on all these areas, including the question whether Microsoft's new file format Office Open XML, as implemented in Office, is sufficiently interoperable with competitors' products.<sup>11</sup></blockquote>
				<p>It was later the same day that Ecma <a href="http://www.ecma-international.org/news/TC45_current_work/Proposed%20dispositions%20for%20National%20Body%20comments%20on%20DIS%2029500%20complete.htm">announced</a> that it had made the Proposed Disposition of Comments document available to National Body representatives &mdash; and also that the document is 2,300 pages long &mdash; more than one third the length of the OOXML specification itself. As Eric Lai, a journalist who has followed the ODF-OOXML story from its beginning, wryly noted, "by comparison, the Concise Oxford English Dictionary runs 1,681 pages."<sup>12</sup></p>
				<p>All of these ongoing developments will provide a rich backdrop for the secret deliberations of the BRM delegations as they meet behind closed doors in Geneva one month from now. After all of the theatrics, press releases, newly launched investigations and spin, the delegates will at last begin to discuss whether Microsoft has moved far enough to gain their approval, how well conceived the proposed dispositions are &mdash; and whether the delegates have had time to digest all 2,300 pages of proposals in time to debate them at all.</p>
				<p><strong>IV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Future of ODF and OOXML</strong></p>
				<p>As might be assumed from the factors reviewed earlier in this article, the future prospects of OOXML and ODF are not likely to be markedly different, regardless of whether OOXML is or is not adopted by ISO/IEC JTC1. This is not only because formal approval by JTC1 will only be of real significance to a fairly small subset (primarily governments) of all customers, but also because the forces that inspired Microsoft's competitors to so actively promote ODF will remain.</p>
				<p>That said, the progress of ODF, and then OOXML, through the standards process has served well to bring public attention to the importance of open document formats in general, and to the differences between ODF and OOXML, both technically and strategically, in particular. The success of ODF to date has also forced Microsoft to provide far more visibility into its formats than would otherwise have been the case, and the first reports of changes agreed to in the Disposition of Comments document also suggest that Microsoft has made a number of compromises that it would not otherwise have been likely to have offered.</p>
				<p><strong><em>Forces of Change:</em></strong> While predictions in a situation such as this are not apt to be of highly reliable, here are some of the factors that I believe will affect the ultimate future of these two standards in the marketplace:</p>
				<p><strong><em>The other XML standard:</em></strong> While ODF and OOXML have been competing in the west, China has been developing its own XML-based open document standard in the east. That standard, called Uniform Open Document Format, or UOF, has been under development since 2003, and was adopted by China as a national standard last year. UOF is protected by seven patents,<sup>13</sup> and vendors will need to pay an as-yet to be disclosed royalty to implement it. China has been guarded in its discussions with both ODF and OOXML proponents, although discussions are ongoing with each. Microsoft has launched an open source project at Sourceforge to develop a converter, similar to an earlier project it launched at the same site to develop an ODF-OOXML converter. At minimum, China can be expected to continue to use its UOF standard as a powerful bargaining chip with Microsoft regarding pricing and licensing terms for Office distribution in the P.R.C.</p>
				<p><strong><em>SaaS:</em></strong> While "renting" software on the Internet has been promoted as a business model for years, its time appears to have finally arrived. This is a result of a number of factors, from the spread of broadband access to the commitment of major vendors like IBM and Google to SaaS as both a business model as well as a strategic weapon. As more and more documents become created on line rather than using Office, the legacy power of Office will weaken, and especially so if most of these documents are based upon ODF than OOXML. Currently, both Google Docs and IBM's Symphony support ODF.</p>
				<p><strong><em>The prospect of a multi-platform world:</em></strong> As earlier noted, during the first decades of the IT age, the value of a single hardware/software platform was so great that other vendors were willing to embrace the "WinTel" platform, and end users were willing to live with an environment controlled by a single vendor. Today, however, many things have changed: users have become more sophisticated, open source software has become more pervasive, respected vendors are reentering the operating system (via Linux) and office suite marketplaces, governments have become less comfortable with the concept of requiring their citizens to use a single environment, and &mdash; most importantly &mdash; open standards offer a path to true cross-platform and cross-product interoperability. The result is that to many end-users, the benefits of a single-vendor environment no longer seem to outweigh the loss of alternative products, innovation and price competition that a multi-vendor environment can provide. The Becta report makes particularly fascinating reading in this regard, due to its determination to provide the British educational system with more vendor competition and students with the ability to "round trip" documents between home and school, as well as to ensure that "free to use" software is included as an option for such use.</p>
				<p><strong><em>Antitrust investigations:</em></strong> At least initially, Microsoft is being conciliatory in its response to the new EU probes, stating publicly that it is "committed to ensuring" that it is fully compliant with European law and the ruling handed down in September by the European Court of First Instance. Microsoft had promised to vigorously contest the earlier EU action, and followed through on that promise for nine years. Microsoft's business thrived as a result of that approach, more than offsetting fines in excess of 1 billion Euros that were levied against it. But as the SaaS model and other forces increasingly threaten its historical business models, it may at some point conclude that its traditional strategy of using typing arrangements between its operating systems and its applications software may no longer make economic sense.</p>
				<p><strong><em>Emerging Markets:</em></strong> While Microsoft claims an installed base of 500 million Office customers, billions of new computer users will link to the Internet in the next decade. None of those users has legacy documents, and many, if not most, of them will use a mobile device as their first computer. The software that is loaded on those devices when they are delivered will therefore have an impact on the future product affinities of their users. Just as Microsoft was able to swiftly wipe out the initially dominant Netscape browser simply by bundling Internet Explorer, for free, in the first computers that most users owned, mobile device vendors and telecommunications providers will have great influence over how the documents of the future are created. With increasing price competition and the fact that most such devices are now based on Linux, Microsoft will at minimum need to cut prices deeply to make its products viable on such devices. It may be that the profit to be made on mobile texting software may not be sufficient to justify proprietary solutions at all.</p>
				<p><strong><em>The Linux desktop:</em></strong> Prices are also working against Microsoft on the desktop, as Everex and other vendors are now selling Linux-based PCs for $400 or less. For purchasers seeking bargain boxes, a free copy of OpenOffice is likely to be far more appealing than even the cheapest version of Office. Third world buyers will be likely to be similarly price conscious, whether buying Linux-based or Windows based systems.</p>
				<p><strong><em>Possible outcomes:</em></strong> In the long term, there are several possible outcomes:</p>
				<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>1. ODF fades away</em></strong>. Given the rather startling success of ODF in a short period of time,<sup>14</sup> this seems unlikely, but remains a possibility, especially if OOXML is adopted by ISO/IEC JTC1, allowing Microsoft to provide a more convincing business case to its government customers to continue to use Office.</p>
				<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>Result:</em></strong> If the government market is lost, ODF will lose some of its economic viability. In that event, it may remain primarily the darling of open source projects, with Microsoft's major competitors seeking other means to erode Microsoft's market share.</p>
				<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>2. OOXML plays the dominant role</em></strong> in a multi-revisable format marketplace, due to the ongoing effect of Microsoft's historically dominant role. ODF continues to be used in a variety of products, especially those used on-line, those that are free, and those targeted at government customers.</p>
				<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>Result:</em></strong> In this scenario, the developers of ODF-based products would go to great lengths to ensure their ability to open and save Office documents without loss of fidelity, as well as to satisfactorily re-export them in OOXML formats. Early reports of the Ecma disposition document indicate that more interoperability information will be supplied in any final version of OOXML, and the news of the new EU investigation may provide added pressure to improve the ability of ODF-compliant products to "round trip" documents with Office 2007.</p>
				<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>3. Use of ODF continues to gain ground</em></strong> as ODF-compliant products follow a trajectory similar to Mozilla Firefox, which continues to gain market share at the expense of Internet Explorer. This outcome would be likely to occur in Europe and emerging countries if the strong community support behind ODF continues to grow, and if the outlook expressed by the Becta report becomes widely adopted.</p>
				<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>Result:</em></strong> Microsoft would find itself under increasing pressure from its own customers to improve their ability to trade documents between Office and ODF-compliant products. While this could occur through Microsoft natively supporting ODF &mdash; as Office 2007 does with every other format in common use today &mdash; Microsoft may find it wiser to propose that ODF and OOXML (and, ideally, UOF as well) be "merged" into a single format, which would allow it to assert greater influence over the future development of that standard.</p>
				<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>4. ODF becomes dominant</em></strong> in the marketplace without merging with OOXML. It is hard to imagine this being the near term outcome. However, the future of SaaS introduces a significant wildcard into the equation. If Microsoft miscalculates spectacularly in devising its business strategy, or suffers a monumental loss in an antitrust action, it might have no choice but to convert to ODF at some point in the future.</p>
				<p><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>Result:</em></strong> Microsoft would need to compete in the office suite marketplace in a way that it has not faced in many years.</p>
				<p><strong>V&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Conclusions</strong></p>
				<p>The unexpected success of ODF in the marketplace is a symptom of fundamental shifts in a maturing IT ecosystem, characterized by increasingly sophisticated and demanding end users, resurgent competition, new enabling technologies, and other forces that are largely beyond Microsoft's control.</p>
				<p>History teaches that monopolies in the marketplace, like empires in the broader world, are rarely sustainable over long periods of time, and ultimately fall victim to both external attack and internal weaknesses. The degree to which Microsoft's competitors have embraced, and many Microsoft customers and national governments alike have resonated, with ODF are strong indications that the foundations upon which Microsoft's historical dominance has been based may at last be weakening.</p>
				<p>ODF is not in itself likely to topple Microsoft from its enviable throne. But the very public example of ODF, as played out in public view, has brought new attention to the value that true competition in the marketplace can offer, as well as to the fact that life without a single "de facto" standard might be not only conceivable, but desirable. When conjoined with the equally forceful currents of open source software and SaaS, Microsoft will be likely to face increasingly frequent challenges in the future from ever more determined competitors, similar to that posed by ODF.</p>
				<p>The ODF experience therefore offers not only a successful model upon which Microsoft's competitors will likely base other strategic initiatives in the future, but also a business case that will be studied in business schools, and by economists, for many years to come.</p>
				<p>How that conflict plays out will determine who will be the Great Powers of the IT industry for the next twenty years.</p>
				<p class="center">Copyright 2008 Andrew Updegrove</p>
				<p>End Notes</p>
				<p><sup>1</sup> The author is legal counsel to OASIS, the developer of ODF, and has written extensively in support of that standard.  However, he had no direct involvement in the adoption of ODF, and the opinions expressed in this article are his alone.  His <a href="http://www.consortiuminfo.org/standardsblog/index.php?topic=20051116124417686">blog entries</a> on ODF and OOXML can be found at http://www.consortiuminfo.org/standardsblog/index.php?topic=20051116124417686</p>
				<p><sup>2</sup> For an in depth, contemporaneous account based upon interviews with many of the direct participants, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/sep05.php#feature">Massachusetts and OpenDocument: A Brave New World?</a> ConsortiumInfo.org, Consortium Standards Bulletin, Vol. IV, No.9, September 2005, at http://www.consortiuminfo.org/bulletins/sep05.php#feature, as well as other articles to be found in the same issue.</p>
				<p><sup>3</sup> As it happens, unsuccessfully.  As discussed later in this article, the European Commission announced on January 14, 2008 that it was launching two new investigations into Microsoft's conduct, one involving its OOXML-based efforts to impede interoperability between Office and competing products.</p>
				<p><sup>4</sup> Ecma International, TC45 &mdash; <a href="http://www.ecma-international.org/memento/TC45.htm">Office Open XML Formats Technical Committee page</a>, at http://www.ecma-international.org/memento/TC45.htm, accessed January 16, 2008.</p>
				<p><sup>5</sup> The text as quoted is in the form that originally appeared at the Ecma TC45 page. The <a href="http://www.ecma-international.org/memento/TC45.htm">current text</a> states the first objective in different form, and no longer displays the second, and can be viewed at http://www.ecma-international.org/memento/TC45.htm, accessed January 16, 2008</p>
				<p><sup>6</sup> This pressure began to be felt even before the OOXML review process began, leading South Africa to call for action. The following is the verbatim text of National Body Contribution ISO/IEC JTC 1 N 8494, titled South Africa Comments on the PAS Process, and dated February 2, 2007:</p>
				<blockquote>South Africa is concerned about what seems to be a growing number of standards submitted under the PAS process that, although publically [sic] available, do not seem to have any measure of regional or even national consensus. These therefore tend not to have been referred to any of the JTC 1 sub-committees, and have obviously not been discussed at [sub-committee] level.</blockquote>
				<blockquote>Our experience is that the result of this is then a round of intense lobbying by various other stakeholders for us to vote negatively on the PAS. Often these other groups take the trouble to compile a list of contradictions that are also widely distributed in order to justify the request for the negative vote.</blockquote>
				<blockquote>A recent example is the proposed PAS on Open XML/ODF.</blockquote>
				<blockquote>It is our opinion that the submission of such "standards" directly to JTC 1 via the PAS route, where the standard has not been discussed within the relevant SC, was never the intention of the PAS System. The fact that some consortium has published a document that they refer to as a standard does not automatically imply that it has any sort of widespread industry acceptance. The fact that the publisher might claim international usage or acceptance is not longer a valid reason in these days of large multinationals, and the SABS [South African Bureau of Standards] has previously been approached by local branches of multinationals to vote in support of such PAS submissions, even if we have no local industry involvement or membership in the appropriate JTC 1 SC.</blockquote>
				<blockquote>As result of this, South Africa will tend to vote negatively on all future PAS submissions to JTC 1 where they have not been appropriate SC. We would like to ensure that proper consideration be given to the PAS by technical experts. If the standard is indeed well known within the industry then this process might be very short.</blockquote>
				<blockquote>This will be a change from our previous tendency to 'abstain' where we had no direct knowledge of the submission.</blockquote>
				<p>See Updegrove, <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20070218154733420&amp;">South Africa and the PAS Process: A Plague o' Both Your Standards</a>, The Standards Blog, February 20, 2007, at http://www.consortiuminfo.org/standardsblog/article.php?story=20070218154733420&amp; South Africa kept its promise, and later voted against adoption of OOXML.</p>
				<p><sup>7</sup> Brown, Alex, <a href="http://www.adjb.net/index.php?entry=entry080107-183411">OOXML: DIS 29500 Ballot Resolution Meeting (BRM) Approaches</a>, There is no end, but addition (Blog), January 7, 2008, at http://www.adjb.net/index.php?entry=entry080107-183411 accessed January 13, 2008.</p>
				<p><sup>8</sup> An explanation of the voting process may be found at Updegrove, Andrew, <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20070831151800414">The ISO/IEC Voting Process on OOXML Explained (and What Happens Next)</a>, ConsortiumInfo.org, The Standards Blog, August 31, 2007, at http://www.consortiuminfo.org/standardsblog/article.php?story=20070831151800414 accessed January 13, 008.</p>
				<p><sup>9</sup> Brown, Alex, <a href="http://www.adjb.net/index.php?entry=entry071215-123604">Back from Kyoto</a>, There is no end but addition, December 15, 2007, at http://www.adjb.net/index.php?entry=entry071215-123604, accessed January 15, 2008.</p>
				<p><sup>10</sup> See the links to multiple articles collected at Updegrove, <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20080103134307872">At a Loss for Words</a>, ConsortiumInfo.org, The Standards Blog, January 3, 2008, at http://www.consortiuminfo.org/standardsblog/article.php?story=20080103134307872 accessed January 15, 2008. As some ODF proponents noted with amusement, an easier (and free) alternative is simply to download a copy of OpenOffice, which can not only open the old formats in question, but export them again in Word .doc form.</p>
				<p><sup>11</sup> European Commission, <a href="http://europa.eu/rapid/pressReleasesAction.do?reference=MEMO/08/19&amp;format=HTML&amp;aged=0&amp;language=EN&amp;guiLanguage=en">Antitrust: Commission initiates formal investigations against Microsoft in two cases of suspected abuse of dominant market position</a>, January 14, 2008, Reference:  MEMO/08/19, at http://europa.eu/rapid/pressReleasesAction.do?reference=MEMO/08/19&amp;format=HTML&amp;aged=0&amp;<br />language=EN&amp;guiLanguage=en accessed January 15, 2008.  See also Updegrove,  <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20080114105017559">EU Opens Two New Investigations Against Microsoft &mdash; One Involving OOXML</a>, ConsortiiumInfo.org, The Standards Blog, January 14, 2008, at http://www.consortiuminfo.org/standardsblog/article.php?story=20080114105017559, accessed January 15, 2008.</p>
				<p><sup>12</sup> Lai, Eric,  <a href="http://www.computerworld.com/action/article.do?command=viewArticleBasic&amp;articleId=9057238">Ecma makes Open XML changes in bid to swing ISO votes</a>, ComputerWorld.com, January 14, 2008, at http://www.computerworld.com/action/article.do?command=viewArticleBasic&amp;articleId=9057238 accessed January 15, 2008.</p>
				<p><sup>13</sup> Personal communication to the author of a member of the Chinese working group that developed UOF.</p>
				<p><sup>14</sup> For a summary of ODF successes during the end of 2007, see the  <a href="http://www.odfalliance.org/resources/AnnualReport2007.pdf">ODF Annual Report 2007</a> issued by the ODF Alliance, at http://www.odfalliance.org/resources/AnnualReport2007.pdf</p>