<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Consortiuminfo.org Consortium Standards Journal &mdash; December &ndash; January 2009</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta name="description" content="While standard setting has been an important aspect of industrial society for over a hundred years, the formation of unofficial, fast-acting standard setting and promotional consortia is a more recent phenomenon which is only now beginning to be seriously studied" />
<meta name="keywords" content="standard setting, promotional consortia, structuring of consortia, standardize, intellectual property policies, procedures, founding company, model, best practices, promoter/adopter structurer, joint venture, IPR, " />
<meta name="author" content="Andrew Updegrove" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/screen.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/journal.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/toolsets.css" />
<!-- ALTERNATE -->
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/default.css" title="default" />
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/large.css" title="large" />
<!-- ********* -->
<link rel="home" title="home" href="http://www.consortiuminfo.org" />
<script type="text/javascript">AC_FL_RunContent = 0;</script>
<script type="text/javascript" src="/scripts/AC_RunActiveContent.js"></script>
<script type="text/javascript" src="/scripts/styleswitcher.js"></script>
<script type="text/javascript" src="/scripts/obfuscate.js"></script>
<style type="text/css" title="text/css">
.dec08table {
border: 1px solid #000000;
border-collapse: collapse;
}
.dec08table td {
font-family: Verdana, Helvetica, sans-serif;
font-size: 12px;
border: 1px solid #000000;
border-collapse: collapse;
}
</style>
</head>
<body id="bulletin">
	<!-- ****************** -->
	<!-- ACCESSIBILITY  -->
	<!-- ****************** -->
	<?php include '../includes/accessibility.php'; ?>
	
	<!-- SEARCH FORM -->
	<form class="search" name="form1" method="get" action="http://search.Blossom.com/query/320">
	
	<!-- ************* -->
	<!-- MASTHEAD  -->
	<!-- ************* -->
	<?php include 'includes/masthead_journal.php'; ?>
	
	<!-- *********** -->
	<!-- BANNER  -->
	<!-- *********** -->
	<div id="banner">
		<div class="left">
			<p><a href="/">Home</a> &gt; <a href="/bulletins/">Standards Today</a> &gt; December &ndash; January 2009</p>
		</div>
		<div class="right">
			<p><input type="text" name="key" /><input type="submit" name="Submit" value="Search" /> <a href="/search/">Advanced</a></p>
		</div>
		<div class="clear"></div>
	</div>
						
	<!-- ************** -->
	<!-- MAIN BODY  -->
	<!-- ************** -->
	<div class="JournalContent">
	<!-- SKIP/START CONTENT LINK -->
	<a name="startcontent" id="startcontent"></a>
		
		<!-- SIDEBAR CONTENT AREA -->
		<div class="AllSidebar">
			<div>
				<?php include '../includes/clients.php'; ?>			
			</div>
			<div class="AllNav">
				<p class="AllNavLink">&raquo;&nbsp;<strong><a href="/bulletins/archive.php" style="border-top:0px;">Journal Archive</a></strong></p>
			</div>
			<div class="AllNav">
				<p class="AllNavLink">&raquo;&nbsp;<a href="/bulletins/pdf/dec08/dec08.pdf">Download PDF</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="mailto:?subject=Standards%20Today&amp;body=http://www.consortiuminfo.org/bulletins/dec08.php">Email this issue</a></p>
			</div>
			<?php include '../includes/toolsets.php'; ?>
		</div>
		
		<!-- BODY CONTENT AREA -->
		<div class="JournalMain">
			<h1>Standards Today</h1>
		
			<!-- ************* -->
			<!-- INDEX -->
			<!-- ************* -->
			<div id="tableofcontents">
			<h2>December &ndash; January 2009<br /><span class="volumeinfo">Vol VIII No 1</span></h2>
			<h3>The Electronic Health Record Standards Challenge</h3>
			<!-- INDEX ITEM -->
			<p><span class="section">EDITOR'S NOTE:</span><br /><span class="title"><a href="#editorsnote" title="Editors Note" accesskey="1">First the Standards, then the Solution</a></span></p>
			<p>After Congress signs off on the c. $825 billion Economic Stimulus bills, some of those billions will go towards implementing Electronic Health Records.  The temptation will be to begin spending that money immediately. The trick will be in spending it on the right projects first.<br /><a class="pdf" href="/bulletins/pdf/dec08/dec08_editorsnote.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">EDITORIAL:</span><br /><span class="title"><a href="#editorial" title="Editorial" accesskey="2">Getting EHR Standards Right</a></span></p>
			<p>The Obama Administration has no end of challenges to look forward to. One of the trickier ones involves something called "Electronic Health Records," and the standards that make them work.<br /><a class="pdf" href="/bulletins/pdf/dec08/dec08_editorial.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">FEATURE ARTICLE:</span><br /><span class="title"><a href="#feature" title="Feature Article" accesskey="3">A Guide to Electronic Health Standards and the Challenges Ahead</a></span></p>
			<p>Standards organizations and governments have been working on Electronic Health Records for many years.  In this article I describe the complexities that make the creation of EHRs difficult, survey the current state of the EHR art, describe the public and private organizations most involved in EHR development, and recommend next steps needed to ensure that the national deployment of EHRs will be successful.<br /><a class="pdf" href="/bulletins/pdf/dec08/dec08_feature.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">INTERVIEW:</span><br /><span class="title"><a href="#interview" title="Interview" accesskey="4">View from the Trenches: An Interview with HL7's Charles Jaffe, M.D.</a></span></p>
			<p>One of the oldest and most important Electronic Health Record standards development organizations is Health Level 7 (HL7).  HL7 and Chuck Jaffe, its CEO, are at the center of U.S. efforts to complete the design of EHR standards, and in this in-depth interview he describes what's working, what's not, and what needs to happen next if the Obama administration's drive to implement EHRs is to succeed.<br /><a class="pdf" href="/bulletins/pdf/dec08/dec08_interview.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">STANDARDS BLOG:</span><br /><span class="title"><a href="#blog" title="Standards Blog" accesskey="5">19 Standards Organizations Support Rambus Brief</a></span></p>
			<p>Last December the U.S. Federal Trade Commission petitioned the Supreme Court to hear why the FTC believes Rambus Incorporated needs to be punished. Nineteen friends of the court and I agree<br /><a class="pdf" href="/bulletins/pdf/dec08/dec08_blog.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">CONSIDER THIS:</span><br /><span class="title"><a href="#considerthis" title="Consider This" accesskey="6">Standards of Patient Care</a></span></p>
			<p>Once there was a time when a doctor sat at a patient's bedside, able to provide more comfort than cure. Today, it's all about the cure, and the patient sometimes seems to be forgotten.  As we commit to require Electronic Health Records for all, we need to be sure that the patient doesn't disappear forever into the digitized data<br /><a class="pdf" href="/bulletins/pdf/dec08/dec08_considerthis.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">MONDAY WITNESS:</span><br /><span class="title"><a href="#mondaywitness" title="Monday Witness" accesskey="7">Inauguration Day &mdash; January 20, 2009 </a></span></p>
			<p>Inaugural speeches are very fine things to behold, full of high ideals and glowing promises &mdash; but then the hard work begins. Most presidents can deliver a fine speech, but only a few deliver on their promises. Here's hoping.<br /><a class="pdf" href="/bulletins/pdf/dec08/dec08_mondaywitness.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p class="center"><a class="pdf" href="/bulletins/pdf/dec08/dec08.pdf">Download PDF of this issue</a></p>
			<div class="hr"></div><hr />
			</div>
		
			<!-- ************* -->
			<!-- EDITOR'S NOTE -->
			<!-- ************* -->
			<a name="editorsnote" id="editorsnote"></a>
			<h4>EDITOR'S NOTE:</h4>
			<h3>First the Standards, then the Solution</h3>
			<p>In the last issue <strong><em>Standards Today</em></strong>, titled <a href="http://www.consortiuminfo.org/bulletins/oct08.php">A Standards Agenda for the Obama Administration</a>, I described the standards-based dependencies of the technology agenda earlier announced by president-elect Obama.  That agenda provides for the creative use of technology to advance a number of important policy goals, such as achieving transparent government, equal access to the Internet, and reducing costs of healthcare.  In this issue, I focus more closely on the significant role that standards will play in achieving one of (now) President Obama's greatest challenges &mdash; lowering healthcare costs, while at the same time keeping a campaign promise to provide universal health coverage.</p>
			<p>As these words are being written, the US Congress is debating the final terms of a stimulus bill that will result in the expenditure of $825 billion (or more) of public funds on a wide array of initiatives intended to address an equally challenging goal: resurrecting an economy that seems inexorably headed towards its worst performance since the Great Depression.</p>
			<p>One of those initiatives included in the stimulus bill would make the final push towards national implementation of something called "Electronic Health Records," or "EHRs."  EHRs are digitized patient records that capture a patient's medical history, treatment and other data in real time, making it available to authorized care givers and researchers, insurers, and the patient herself. EHRs are devilishly complex to design, because they must satisfy an almost impossible set of competing requirements.</p>
			<p>The benefits promised by EHRs include dramatic reductions in healthcare costs, fewer medical errors, higher quality medical care, and more productive research results in the health sciences.  But the up-front costs of deploying such a system on a national basis are dramatic as well.  It is estimated that the expenditure of well over one hundred billion of dollars will be required over the next five years.</p>
			<p>Due to the great benefits and enormous costs of this effort, it would be really great if it all worked, after it was deployed and paid for, and that's what this issue is all about.</p>
			<p>In my <strong><em>Editorial</em></strong>, <a href="#editorial">Getting EHR Standards Right</a>, I expand on the challenge, and the importance of not rushing headlong into implementation before fine tuning the standards that will make or break the success of EHRs.  In the <strong><em>Feature Article</em></strong>, <a href="#feature">A Guide to Electronic Healthcare Record Standards and the Challenges Ahead</a>, I review the history of EHR development to date, describe the many significant challenges to designing effective EHRs, survey the organizations developing EHRS, provide a timeline of significant government action, and finally provide recommendations regarding the remaining steps that need to be taken before actual deployment begins, in order to ensure that the great promise of ubiquitous EHR deployment is achieved.</p>
			<p>Next, I'm very pleased to provide a lengthy <strong><em>Interview</em></strong> with Dr. Charles Jaffe, the Executive Director of Health Level 7 (HL7), one of the oldest standards development organizations creating EHR standards. HL7 standards are a cornerstone of all EHR frameworks in development and use today, and Chuck's perspective on what still needs to be done is a must read for those interested in what lies ahead. The interview is appropriately titled <a href="#interview">View from the Trenches: an Interview with HL7's Charles Jaffe, M.D.</a>, and it is a sobering read.</p>
			<p>This issue's <strong><em>Standards Blog</em></strong> returns to an topic that I have followed and supported for over five years: the ongoing litigation involving Rambus Incorporated, a company that has by turns been successful and unsuccessful in avoiding liability for allegedly "gaming" the standards development process for its own profit.  I have filed numerous pro bono "friend of the court" briefs involving Rambus in the past in defense of the integrity of the standards development process, and in December of last year I did so once again: this time with the Supreme Court.  The title of the blog entry indicates the breadth of the support I was able to gather in this endeavor: <a href="#blog">19 Standards Organizations Support Rambus Brief</a>.</p>
			<p>For my <strong><em>Consider This</em></strong> essay, I return to the healthcare theme, and point out that there is more to the patient than digitized data alone.  The piece is entitled <a href="#considerthis">Standards of (Patient) Care</a>.</p>
			<p>I close this issue with a piece from my <strong><em>Monday Witness</em></strong> series, which focuses on the ethical and moral, rather than the technical, standards of the day.  It is entitled <a href="#mondaywitness">Inauguration Day &mdash; January 20, 2009</a>. In it, I reflect on inaugural addresses past and present, and look forward with guarded optimism to the next four years.</p>
			<p>As always, I hope you enjoy this issue.  But whether you do or don't, it's always good to hear from you.  You can reach me at andrew.updegrove@gesmer.com.</p>
			<!-- ************* -->
			<div class="credit">
				<p>Andrew Updegrove<br />Editor and Publisher<br />2005 ANSI President's<br />Award for Journalism</p>
				<div class="clear"></div>
			</div>
			<p class="note">The complete series of Consortium Standards Bulletins can be accessed on-line at <a href="/bulletins/">http://www.consortiuminfo.org/bulletins/</a>. It can also be found in libraries around the world as part of the EBSCO Publishing bibliographic and research databases.</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p> 
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ************* -->
			<!-- EDITORIAL -->
			<!-- ************* -->
			<a name="editorial" id="editorial"></a>
			<h4>EDITORIAL:</h4>
			<h3>Getting EHR Standards Right</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<p>On January 20, a new show opened in Washington D.C. After eight years under one administration, the curtain cascaded down on one set of policies, and a moment later rose to unveil a new administration, with new ideas, new priorities, and a new agenda.  Included in that agenda is a commitment to embark on a five year quest to dramatically decrease the cost of healthcare &mdash; by investing as much as $50 billion dollars of public funds in the design and deployment of something called "electronic health records," or EHRs.</p>
			<div class="calloutright">
				<p>Readers of this eJournal, but not the public at large, will be immediately aware that the foundation for the DHR vision is standards</p>
			</div>
			<p>As of this writing, $20 billion of that amount is included in the current House draft of the Economic Stimulus bill called for by the new administration.  The full cost of EHR implementation, including private expenditures, has been estimated to be $156 billion over five years, not including $20 billion in operational costs.  With such a price tag, the promise of EHRs had best be realized, or the new administration will have some significant explaining to do.</p>
			<p>At its most basic conceptual level, an EHR is to a medical chart what an electronic spreadsheet is to its paper analog.  And indeed, the roots of the EHR can be traced back to the concept of "computerized patient record" technology that would allow a doctor to enter notes with a stylus on a tablet PC.  But the value of these early records was only realized by the hospital that hosted the proprietary system to which the tablet was linked.  When the patient left the hospital, his data was left behind, unavailable even to the physician that had entered the data when she returned to her own off-site office.  Nor could the data be accessed by any other physician elsewhere in the future, or by the emergency room staff of any other hospital to which the patient might be taken in the future.  Instead, islands of isolated data were created by each physician and facility in technically idiosyncratic fashion, and maintained in proprietary systems, never the twain to meet.</p>
			<p>The result is that we are constantly filling out new questionnaires in doctors' offices and waiting days or weeks for paper copies of records to be printed by one care giver to be mailed, hand delivered or faxed to another.  In emergencies, we are apt to be cared for by medical staff that have no access to vital facts relating to our medical history at all, perhaps with unfortunate and avoidable consequences.  Meanwhile, our care providers are weighted down with expensive, tedious and duplicative record keeping.</p>
			<p>The ultimate goal of health information technology is therefore a medical record in which a patient's medical information will accumulate over a lifetime as a succession of care givers contribute it.  That data will be accessible from anywhere, and at anytime, by those to whom the patient wishes to give access.  Because everyone will enter and access the data in the same way, the quality of care should increase, the incidence of avoidable mistakes should decline, data input and storage and other costs will decrease, insurers will be able to verify claims more accurately and make payment more speedily, and patients will have greater control over their own medical information.  With appropriate provision for protection of patient privacy, masses of invaluable, comparable data would also become available to researchers to speed the advance of new treatments and medications.</p>
			<div class="calloutright">
				<p>Whether wide uptake of EHR technology and real savings are achieved quickly will in great measure result from how well the standards that enable EHRs are selected, assembled and integrated into actual systems.</p>
			</div>
			<p>But in order for this eHealth nirvana to be attained, millions of hospitals, doctors’ offices, emergency responder units, insurers and others will need to purchase and install the software and other technology needed to create, maintain and exchange EHRs, and their personnel will need to be trained to use them.  All of this can only be achieved at great cost of both public and private funds.</p>
			<p>Readers of this eJournal, but not the public at large, will be immediately aware that the foundation for this entire vision is standards &mdash; taxonomies to ensure uniformity of data input, identifiers for authentication, security requirements for authorization and maintenance, protocols to enable communication between systems, data formats to ensure long term accessibility, and much more.  Upon this foundation must rest other standards tools &mdash; frameworks, profiles, reference implementations, and guidance documents.  Indeed, the blueprint for a successfully deployed, national EHR infrastructure must by definition be a complex and carefully constructed hierarchy of standards.</p>
			<p>Designing and deploying this standards-based infrastructure will be comparable in scope and scale to designing and deploying the Internet, minus the requirement to build the telecommunications backbone that is now already in place. But unlike the "opt in" Internet, to which users gradually migrated in increasing numbers over two decades as the Web's capabilities grew and its lure became more seductive, EHR technology must be adopted very widely before cost savings begin to outweigh expenditures.  Unless that happens quickly, it will be many years before meaningful savings are achieved.</p>
			<p>Whether wide uptake of EHR technology and real savings are achieved quickly will in great measure result from how well the standards that enable EHRs are selected, assembled and integrated into actual systems.  Unfortunately, the history of ambitious standards projects has not always been a happy one, and for every grand success like the World Wide Web there is a well intended POSIX that fails to achieve its hoped-for destiny.  Moreover, the record of EHR deployment success to date, both within individual hospitals as well as in national programs abroad, has been mixed.</p>
			<p>The lesson to be learned, then, is that we had better get the standards right, both from a real world as well as a technical perspective.  If the standard suites mandated do not solve real problems in ways that work for care givers, vendors and other stakeholders, then this ambitious and worthwhile endeavor will be doomed from the outset, and an enormous amount of money will have been squandered.</p>
			<p>Getting the standards right is possible, but will not always be easy.  As with any other government initiative involving vast amounts of money, those with the most to gain will have the greatest incentives to steer decisions to their advantage.  Those in government who do not have deep expertise in standards development but may find themselves charged with achieving rapid results will be hard pressed to know which recommendations to follow.  Finally, until the standards are finalized, the greater part of the funding available cannot be spent.  All of these forces will work against making the best decisions in the time necessary to make them.</p>
			<p>The Obama administration should therefore pursue its EHR agenda with as much caution as speed, and with deliberation as well as determination.  Because once these important infrastructural decisions have been made, it will be difficult indeed to turn back.</p>
			<!-- ************* -->
			<p class="center">Copyright 2009 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!-- FEATURE ARTICLE -->
			<!-- ******************* -->
			<a name="feature" id="feature"></a>
			<h4>FEATURE ARTICLE:</h4>
			<?php include '../bulletins/dec08/dec08_featureinc.php'; ?>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!-- INTERVIEW  -->
			<!-- ******************* -->
			<a name="interview" id="interview"></a>
			<h4>INTERVIEW:</h4>
			<h3>View from the Trenches: an<br />Interview with HL7's Charles Jaffe, M.D.</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<img class="imgleft" src="dec08/dec08_img4.jpg" alt="" width="175" height="193" border="0" />
			<p>The number of standard setting organizations (SSOs) from which specifications have been drawn to create Electronic Health Records (EHRs) are legion, due to the complex nature of these goal.  Some of the standards utilized are generic, and common to any sophisticated Internet-enabled commercial system.  Others are specific to science, but usable generally in paper as well as information technology (IT) based health care systems.  Only a few SSOs, however, have taken up the challenge of developing the major components essential and unique to EHRs.  One of the oldest and most important is Health Level 7, more commonly referred to as HL7.</p>
			<p>HL7 has been at the center of global EHR development since 1987, as well as a key player in the more recent U.S. efforts to design and implement a national EHR system by 2014, a commitment made by President George W. Bush in his State of the Union Address in January of 2004.</p>
			<p>With the Obama Administration's pledge to meet that commitment, and to direct massive amounts of funding towards ensuring its success, it is critical that the standards needed to support this ambitious goal are not only available, but the right tools for the job as well.</p>
			<p>In this interview, HL7 CEO Charles Jaffe, M.D. shares his perspective on what's been accomplished, what remains to be done, and where the critical decisions that will lead to success or failure in creating a national EHR system must be made.</p>
			<p><strong>I.&nbsp;&nbsp;Overview Questions</strong></p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Please tell me what the historical role of HL7 has been in the standards area.</em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> HL7 was founded at the University of Pennsylvania 22 years ago in order to facilitate the exchange of administrative data. It rapidly evolved into the standards by which clinical data is shared in hospital and ambulatory settings. In order to support a broader range of stakeholders, HL7 adopted the development requirements of the American National Standards Institute (ANSI). The adoption of HL7 specifications and the associated standards development process soon became the foundation of healthcare IT infrastructure around the world, and today is embraced by affiliates in 35 countries. By virtue of charter agreements and far-reaching cooperative initiatives, HL7 has formed major development initiatives with other global standards development organizations, including ISO and CEN (European National Standards body), clinical research bodies, such as CDlSC (Clinical Data Interchange Standards Consortium) and the US FDA, government agencies including the National Library of Medicine, Canada Health Infoway, National Health Service Connecting for Health (UK), terminology developers such as International Health Terminology Standards Development Organization (IHTSDO / SNOMED CT) and LOINC (Laboratory), pharmacy standards developers (NCPDP), as well as international profiling organizations (IHE / Integrating the Healthcare Enterprise).</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> What are the current standards maintained by HL7, and what purposes are they intended to serve?</em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> Briefly stated, they are specifications to support interoperability. Messaging  is the more traditional area for which HL7 is recognized and is embodied in the Version 2 family of standards. These specifications support interoperability for greater than 95% of the hospitals and healthcare systems in the United States. Version 3, which began more than a decade ago, provides a model-based development system and insures a higher level of interoperability. Within Version 3 lies the Clinical Document Architecture (CDA), which provides both the higher level of interoperability and the persistence of common documents or clinical templates. HL7 has also developed functional and interoperability models for EHRs and for Personal Health Records (PHR). Concurrently, HL7 is creating a Services Oriented Architectural (SOA) framework as well as the definition of a SOA-based Enterprise Architecture that supports all HL7 products.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> What categories of stakeholders are active in HL7 today?</em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> In addition to those stakeholders identified in question 1, above, HL7 is also supported by academic institutions, system and electronic health record vendors, system integrators, hardware and software technology developers (such as IBM, Intel, and Microsoft), clinical research institutions (including the NIH / National Cancer Institute) and pharmaceutical companies, quality institutes and privacy advocate organizations, national healthcare standards organizations, as well as national and international professional medical, nursing, informatics and other healthcare (dental, pharmacy, veterinarian) societies. HL7 also has important relationships with granting bodies (Robert Wood Johnson Foundation and the Rockefeller Foundation) as well as with the World Health Organization.</p>
			<p><strong>II.&nbsp;&nbsp;The Task Ahead</strong></p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Where do things stand at this moment in Congress relating to EHR legislation?</em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> At this moment, there is a high level of flux in the plans for both the Recovery Act (stimulus package) and long-range investment. The proposals brought forth by the Senate and the House differ in their language and intent. At the same time, the approach to creating stimulus packages reflects the divergent economic philosophies of the Democrats and Republican platforms. Nonetheless, there is bi-partisan support for healthcare reform and healthcare IT as a vehicle for improving quality, diminishing medical errors, and suppressing the upward spiral of healthcare costs.</p>
			<p>In the current legislation, both houses of Congress support a strong central body to oversee national initiatives for healthcare IT (Office of the National Coordinator) and healthcare IT standards (Healthcare IT Standards and Policy Committees). The funding, both near-term and long range, is significant. Dollars will be devoted to infrastructure, standards, and the goal of the Administration is to provide some form of interoperable healthcare records for all Americans within five years.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Does it appear that the legislation in process is addressing the same challenge that, for example, HITSP was created to address, or has the goal changed to require something new or additional, and if so, in what ways?  (Are these the right ways?)</em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> It appears that the goal of accelerated development of healthcare IT standards and technology remains. It is unclear to me at this time if the process will undergo some fundamental rethinking. Various legislative packages provide for different infrastructure, although it appears that the burden of administrative responsibility will rest with the Office of the National Coordinator for Healthcare IT (ONCHIT) and the National Institute of Standards and Technology (NIST). The pathway to standards development is not clearly defined within the legislation, although provisions for oversight are important in all of the packages.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> At a high level, what are the categories of standards and related tools that will be needed to make EHR's possible?</em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> Electronic Health Records that share institutional or in some cases system-wide health information have been broadly deployed in hospitals and large ambulatory clinics and group practices  There is still a significant need for certified EHR systems in small group and independent physician practices where most clinical information is still maintained on paper. Examples of successful implementation exist within the Veterans Health Administration and within Kaiser Health System. These are not complete, not portable, and not easily scalable in other environments. The national goal of sharing data and achieving true interoperability has many obstacles, however. The standards needed for the process are only one of them. Certainly one of them is a strong business case (or value case) for data exchange. Public health demands, clinical research requirements and cost mitigation are issues that make a compelling case. Other hurdles include increasing privacy demands, infrastructure deficiencies, the lack of a national patient identifier, as well as vocabulary and terminology ambiguity. Even the most successful of these in Canada and England have been marked by missteps and complex priority decisions. Perhaps one of the most significant impediments to implementation in the US is the disparity between the beneficiaries of EHRs and the stakeholders (physicians and providers) who are required to bear the costs.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> How many of these categories of tools are available today?</em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> If, by tools, you mean the technology that now may be considered electronic health records, there are many. They have varied objectives, cost structures and breadth of implementation. If you mean fully-implemented electronic health records, with full integration with lab and x-ray, for example, and providing robust decision support, the penetration is very limited. If you mean stand-alone electronic medical record solutions, or electronic personal health record implementations, or even electronic prescribing systems, the adoption is higher, albeit modestly so. Even if the technology and funding hurdles were overcome, there would be significant remaining barriers related to policy considerations, including provisions for opt-in/opt-out of respective systems. For example, in some metropolitan regions in the Northeast, some patients live in one state, work in another, and receive significant healthcare in a third.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Which other standard setting organizations (SDOs) do you see as being most important (i.e., technically competent, well enough established, and robust enough to do what needs to be done)?</em></p> 
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> Like the question above, the answer implies significant political ramifications. In addition, some SDOs are global, while others are very US-centric. Globally, ISO remains a critical arbiter of standards. CDISC is the pre-eminent standard for clinical research. Among the vocabulary standards, there are several important players. SNOMED CT (from IHTSDO) may be the most important in the English speaking world, but the International Classification of Diseases (from WHO; ICD 9 in the US, ICD in the rest of the world) and LOINC (Logical Observations: Identifiers, Names, Codes for labs) are widely used for some data exchange in the US. NCPDP (National Council for Prescription Drug Programs) for pharmaceuticals in the US.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Where work still needs to be done, do you see voids where no qualified standards organization exists to meet the need?  What are those areas? </em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> There is not a lack of standards, there are, in fact, too many standards and too many organizations writing them. There are some standards that are easy to implement or easy to understand, but which lack coherence, scalability, or broad adoption, while others are difficult to understand or cumbersome to write code for implementation. Some organizations write specifications or artifacts that are useful but painfully limited. Some are built on strict models and development frameworks to improve interoperability. Others meet the needs of the specific domain but are incapable of being used to share data with our healthcare environments. Some are meant to be international while others are simply realm-specific. Perhaps the most difficult challenge is to bind the standards to structured vocabularies to ensure that there is the unambiguous transfer of meaning. And as always, most lack the tools to adequately facilitate implementation.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> The US has always been more of a vendor-driven, "bottom up" rather than a government directed,  "top down" standards development system.  What role do you think government needs to play in order to accomplish this broad, complex and accelerated process? </em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> From the perspective of HL7, the US government must provide the funding to support the development of standards and conformance testing. Among the other English-speaking countries, we trail far behind in providing the federal leadership and resources for healthcare standards creation and management. For more than a decade in the UK and nearly as long in Canada, we have seen far-reaching federal management of healthcare resources that greatly overshadow the efforts of US agencies and organizations. While Canada and the UK have approached this process very differently, both have achieved significant progress to enable healthcare IT to improve the delivery of care and reduce its cost. The philosophy articulated in the very early hours of the new Administration is focused on reversing that position and committing the needed resources to this complex process.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Are there other governments abroad that are moving to implement EHRs?  Who are they, and what can we learn from them? </em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> As noted earlier, both the UK and Canada have taken bold steps to develop healthcare IT infrastructure and implementation. With any ground-breaking initiative, mistakes have been made. Certainly, the business model of each cannot be easily reconfigured to the US environment because of the central payer system in those countries. As the US Federal agencies (principally CMS) gradually exceed the 50% level of healthcare funding in our country, that concern becomes less problematic. In addition, the UK and Canada have recognized many of the shortcomings of their respective approaches and have made even more significant efforts to mitigate them. The US can learn a great deal from the experiences of these countries.</p>
			<p><strong>III.&nbsp;&nbsp;The Major Challenges</strong></p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Do we have a chicken and egg problem here?  Can we productively spend $10 billion the first year, or do we have to get farther down the road with the standards before we can spend money at this scale without wasting it?</em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> I don’t think we can wisely spend one hundred cents of every investment dollar. Mistakes will be made, but we need bold initiatives to prevent continued erosion of our healthcare delivery and further escalation in the rate of our healthcare expenditures.  It has been over a decade since the Institute of Medicine issued its landmark report, To Err is Human, which detailed the deficiencies in our healthcare system.  This startling condemnation was followed two years later by <em>Crossing the Chasm</em>, which provided recommendations to remedy some of the most significant problems.  Not much progress has been made since then to rectify the problems in our delivery process which lead to the erosion of the quality of care. Of course, the expenditure of such large sums cannot be accomplished without significant oversight. Success needs to be clearly defined and metrics for success must be established. Nonetheless, the amount of the proposed funding is not out of proportion with the per capita resources dedicated to healthcare delivery in the UK and Canada.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Do we have consensus on the standards approach to take, or will even that take time to achieve?  How about the architectures upon which the standards must be based? </em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> There is a growing consensus to the approach we must take, but it is far from unanimous. Without exception, every effort and initiative is hampered with self-interest and complex fiscal philosophies. In the past, the US has relied almost exclusively on the marketplace to drive decision making. As the percentage of our GDP devoted to healthcare skyrockets beyond 16%, we no longer need to ask questions about the efficiency of the marketplace. We can no longer commit over 20% of our healthcare dollar to administration nor can we accept the fact that the most affluent nation in the world trails twenty other countries in the delivery of healthcare quality. The commitment of the Federal government to healthcare IT for improving our delivery system is the first step for which no price tag can be assigned.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Does Congress have the expertise to finalize the legislation that will launch the program, or could they use more help in understanding the standards based issues? </em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> I don't believe that Congress will ultimately codify specific standards or programs within its broad legislative agenda. I expect them to provide broad objectives and identify the agencies to translate that agenda into an action plan. Early drafts of the legislation have carefully articulated certain stakeholder groups and important guidelines (such as privacy). Ironically, the draft of the legislation from the House Ways and Means Committee fails to mention two important stakeholders: physicians (care providers in general) and standards development organizations.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> Is five years a reasonable period of time for this project &mdash; to not only develop the standards, but also design the products, widely deploy them in the marketplace, and train medical personnel to use them?  If not, what would be reasonable? </em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> Five years is very ambitious on any budget. I don't believe we have the manpower to install and maintain the necessary technology and systems even if the funding were available to pay for all of it. One of the HL7 goals is the acceleration of training of individuals to provide these skill sets. Perhaps the biggest obstacle is the human factor. What incentive (carrot or stick) will we provide to caregivers to promote adoption of these technologies that will surely alter workflow, re-prioritize incentives, and perhaps restructure the way we represent knowledge.</p>
			<p><em><strong>AU:&nbsp;&nbsp;&nbsp;&nbsp;</strong> What are the most critical standards-related first steps to be taken, in your judgment, to make sure that the EHR initiative proves to be successful? </em></p>
			<p><em><strong>CJ:&nbsp;&nbsp;&nbsp;&nbsp;</strong></em> For HL7, the most vital task is the addition of professional staff with high levels of technical expertise to the cadre of dedicated volunteers who make standards development possible. Secondly, we must change the funding model of our organization so that we no longer rely upon voluntary contributions and membership fees to dictate the limits of the reach. Lastly, we must rededicate ourselves to responding to the needs of the government agencies that rely so much on the productivity of our organization, whether or not these requirements are consistently and clearly articulated.</p>
			<p>In a more global environment, the US government can learn from the experiences, both positive and less so, from other countries that have paved the way for healthcare information interoperability. In many instances, other government agencies have cooperated with and benefited from the expertise of the HL7 rank and file. While the technology may not be immediately transferable, the experience on many fronts certainly is.</p>
			<!-- ************* -->
			<p class="center">Copyright 2009 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!-- STANDARDS BLOG  -->
			<!-- ******************* -->
			<a name="blog" id="blog"></a>
			<h4>STANDARDS BLOG:</h4>
			<h3>19 Standards Organizations<br />Support Rambus Brief</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<h6>&nbsp;&nbsp;&nbsp;&nbsp;Date: December 24, 2008<br />&nbsp;&nbsp;&nbsp;&nbsp;<span class="views">Views: 2,506</span></h6>
			<img class="imgleft" src="dec08/dec08_img1.gif" alt="" width="320" height="238" border="0" />
			<p>Yesterday I filed a pro bono amicus curiae ("friend of the court") brief with the United States Supreme Court in support of the Federal Trade Commission's petition for writ of certiorari in its suit against Rambus Technologies. I'm pleased to report that 19 standard setting organizations (SSOs), representing over 13,300 members, joined as amici curiae supporting this brief; the list of participants appears later in this blog entry.  As noted in the brief itself, these SSOs:</p>
			<blockquote><em>&hellip;represent a broad range of SSOs that participate in the standard setting process, and each is greatly concerned by the adverse effects that it anticipates will result from the [lower court reversal of the FTC's sanctions of Rambus].  Those effects will reach virtually all aspects of modern society, commerce, education and government, because all of these interests rely heavily upon the efficient development and broad adoption of standards by the private sector.<br /><br />The pervasiveness of standards, and of the potential reach of the decision on petition, is indicated by the range of focus of the amici curiae that have joined in this brief.  They include SSOs that develop standards or support standards development in sectors as diverse as defense, consumer electronics, photography, on-line learning, geospatial information, credit "smart" cards and a broad array of computer system products and services.</em></blockquote>
			<p>In agreeing to be parties to the brief, these organizations demonstrated their concern over maintaining the integrity of the standards development process, as well as their belief that SSOs, their members, and non-members alike must be able to rely upon the support of the courts when they believe that SSO intellectual property rights (IPR) policies have been violated.  (I outlined the facts and disputes underlying the Rambus case in <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20081214113930139">this blog entry</a> ten days ago.)</p>
			<p>The final list of amici is as follows:</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;ADVANCED MEDIA WORKFLOW ASSOCIATION (AMWA)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;CONSUMER ELECTRONICS ASSOCIATION (CEA),</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;GLOBALPLATFORM INC.</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;IMS GLOBAL LEARNING CONSORTIUM, INC. (IMS)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;INTERNATIONAL IMAGING INDUSTRY ASSOCIATION, INC. (I3A)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;IPC, ASSOCIATION CONNECTING ELECTRONICS INDUSTRIES</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;LINUX FOUNDATION</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;MIDI MANUFACTURERS ASSOCIATION</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;MOBILE PRINTING AND IMAGING CONSORTIUM, INC.</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;OPEN GEOSPATIAL CONSORTIUM, INC. (OGC)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;OPENSAF FOUNDATION</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;ORGANIZATION FOR THE ADVANCEMENT OF STRUCTURED<br />&nbsp;&nbsp;&nbsp;&nbsp;INFORMATION STANDARDS (OASIS)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;PICMG-PCI INDUSTRIAL COMPUTER MANUFACTURERS GROUP, INC. (PICMG)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;SOCIETY OF MOTION PICTURE AND TELEVISION ENGINEERS (SMPTE)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;THE SOFTWARE DEFINED RADIO FORUM, INC.  (SDR FORUM)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;THE OPEN GROUP (TOG)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;VIDEO ELECTRONICS STANDARDS ASSOCIATION (VESA)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;VMEBUS INTERNATIONAL TRADE ASSOCIATION (VITA)</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;XBRL INTERNATIONAL, INC.</p>
			<p>The brief itself can be viewed on line <a href="http://www.gesmer.com/mcleseminar/pdfuploads/Amicus Brief - Advanced Media, et al., Amicus Brief, FTC v. Rambus.pdf">here</a>, and the Summary of Argument is as follows:</p>
			<blockquote><em>The purpose of this amicus brief is not to make legal arguments, but to acquaint the Court with information supporting a decision by the Court to allocate its limited time to consideration of the legal questions at issue. In brief, amici curiae wish the Court to understand the increasing dependency of all aspects of society, commerce and government on standards, and the fragility of the process by which such standards are developed. Amici curiae believe that the type of conduct that the FTC found Rambus Incorporated (Rambus) to have engaged in, if allowed to go unredressed, would severely undermine and jeopardize the continued existence of that fragile process.<br /><br />
			Standards are vital to government procurement, national competitiveness, and the efficiency and safety of society. Standards are created by voluntary, self-governing organizations that have no effective enforcement power to police the conduct of their members. In the information and communications (ICT) sector, the implementation of standards often results in the infringement of the patents of members and/or non-members. If the owners of these patent claims are only willing to license their claims selectively, or on unreasonable or discriminatory terms, then severe consequences will follow, including unreasonable costs to end-users, unfair discrimination against individual industry participants, and often the complete failure of the standard in question. While such a result cannot easily be avoided in the case of a patent claim owned by a non-participant in the standard setting process, it would be highly inequitable for a patent owner to deceptively exploit its participation in an SSO to ensure such a result for its own benefit.<br /><br />
			The value and importance of standards in the modern world is profound. As an example, the Department of Commerce concluded in 2004 that standards affect an estimated 80 percent of world commodity trade. U.S. Department of Commerce, Standards and Competitiveness &mdash; Coordinating for Results 1 (May 2004). In the ICT sector, the role of standards is particularly crucial, as vital infrastructural elements such as telecommunications, the Internet and the Web literally cannot exist without common agreement on, and universal implementation of, enabling protocols and other standards.<br /><br />
			Moreover, private sector standards are often incorporated by reference into laws. But unlike public laws and regulations, standards are developed within a process that is not only self-regulating, but also largely unsupervised, except by those that directly participate. As a result, the success or failure of private sector standards development is highly dependent upon trust. If those that participate conclude that abusing the system is too easy to accomplish, and that such abuse is too lightly punished if discovered, then the entire system can find itself in danger of collapse, because the risks of participation and adoption of standards become greater than the benefits to be gained. Were such a collapse to occur, virtually no aspect of society would be immune from the consequences.<br /><br />
			More specifically, amici curiae wish to acquaint the Court with the following facts, as developed in greater detail in the arguments that follow:<br /><br />
			1. Interoperability standards and other technical specifications play a vital and essential role in all aspects of modern society, commerce, government, and indeed, virtually every other aspect of our modern, networked world. With the increasing utilization of the Internet to support and enable finance, emergency response, homeland security, defense, healthcare, government services, education, communications, entertainment and much more, the efficient development and ongoing maintenance of hundreds of new ICT standards each year is becoming especially critical.<br /><br />
			2. In enacting the National Technology Transfer and Advancement Act of 1995 (NTTAA), Pub. L. No. 104-113, 110 Stat. 775 (1996), Congress instructed each Federal agency to utilize standards created by SSOs in preference to "government unique" standards to the extent "practicable." In so doing, Congress deferred to the private sector to supply the tens of thousands of standards upon which the operations of government, and the implementation of its policies, must rely. In contrast to the government-supported process that is followed in many other nations, the United States depends upon representatives of industry, academia, consumers and government to participate, at their own cost, in hundreds of non-profit SSOs to develop standards for the good of all.<br /><br />
			3. Since the enactment of the NTTAA, government has become far more dependent upon standards to achieve its goals. Examples of current top-level policy areas that will be heavily dependent upon the rapid development of essential ICT and other standards include homeland security, electronic records for healthcare, E-Government and global warming.<br /><br />
			4. SSOs adopt IPR policies that are intended to identify patent claims that would be "necessarily infringed" by an implementation of a standard under development, and to ensure that such "necessary claims" will be made available to all would-be implementers under at least RAND terms. Absent such knowledge and commitments, a patent owner may gain a degree of monopoly power over the implementation of a standard that can be greatly abused, to the detriment of consumers.<br /><br />
			5. The standards development process relies heavily on a presumption of trust, and specifically on the assumption that members will honor their obligations under IPR policies. If that trust can be violated with impunity, then there is more for participants to lose than to gain by participating, and the very existence of the standards development infrastructure can become in danger of collapse.<br /><br />
			6. Due to budget constraints and other concerns, SSOs are not capable of enforcing their rules in court. Because of the great cost of patent infringement litigation, it is extremely expensive for SSO members, and others that adopt standards, to defend themselves when IPR policy rules are violated.<br /><br />
			7. SSOs, their members, those that adopt standards, and those that rely upon the standards they produce, therefore need to be able to rely on the courts to defend, regulators to robustly enforce, their interests when standards development participants betray their duties of trust and violate IPR policy rules.<br /><br />
			8. If the decision of the Circuit Court stands, then the integrity and viability of the standards development process will be endangered, at great cost to society, to the national interest, and to those that have made the substantial investment in time and money, and undertaken the business risk, to participate in good faith in the development of standards.<br /><br />
			The antitrust laws are particularly important to preserving the integrity of the standards development process. Unlike contract and fraud remedies available under state laws, the antitrust laws are national in scope, and therefore provide greater predictability of result. They also permit both public (via the regulators) and private (by aggrieved parties) action, and are specifically constructed to protect competition. If the courts decline to enforce the integrity of standard setting when such laws are violated, then the option of "gaming" the system will become more attractive to SSO members. As a result, additional litigation will reach federal and civil courts, discouraging companies from adopting the standards in question, and over-burdening those courts.<br /><br />
			Given the rapid pace of innovation in standards-dependent areas such as the technology and telecommunications sectors and the increasing dependence of the world on the products of such innovation, amici curiae strongly support granting certiorari in this case.</em></blockquote>
			<p>There are several other amicus briefs being filed, one by JEDEC, the SSO that hosted the process underlying the dispute itself.  Another has been filed on behalf of four high tech companies that rely heavily on standards (HP, Cisco, Sun and Oracle), another by CCIA, a trade association that focuses on policy issues, and still another is expected to be filed by two law professors.  Each of these will argue the points of law that they hope the Court would consider.  My partner, Lee Gesmer, is collecting all of the amicus briefs as they are filed, as well as those of the parties themselves, at this <a href="http://www.scribd.com/group/69175-ftc-v-rambus-certiorari-petitions-and-amicus-briefs">ScribD page</a>.  But first, the Court has to agree to take the case, and that's where the SSO amicus brief comes in.</p>
			<p>Whether the Supreme Court chooses to take the case is, of course, always a long shot.  Lee points out in his own <a href="http://www.masslawblog.com/2008/12/amici-briefs-supporting-supreme-court-review-in-ftc-v-rambus/">blog entry</a> (which provides a good overview of the legal significance of the Rambus case), that:</p>
			<p>Persuading the Supreme Court to review a case is harder than getting into Harvard. In its most recent term the Court decided about 70 cases, out of over 7,000 appealed.</p>
			<p>Hopefully, the arguments made in the SSO brief, and the impressive list of organizations on the cover, will incrementally raise those odds.  I appreciate their support, and their willingness to associate their names with this brief.</p>
			<!-- ************* -->
			<p class="center"><em>Bookmark the Standards Blog at <a href="/newsblog/">http://www.consortiuminfo.org/newsblog/</a> or set <br />up an RSS feed at <a href="/rss/">http://www.consortiuminfo.org/rss/</a></em></p>
			<p class="center">Copyright 2009 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<img src="dec08/dec08_img2.gif" alt="" width="450" height="750" border="0" />
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--  CONSIDER THIS  -->
			<!-- ******************* -->
			<a name="considerthis" id="considerthis"></a>
			<h4>CONSIDER THIS:</h4>
			<h3><span class="red">#56</span> Standards of Patient Care</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<img class="imgleft" src="dec08/dec08_img5.jpg" alt="" width="175" height="155" border="0" />
			<p>There are not a few commentators that would tell us that the latter half of the 20th century will best be remembered as the Computer Age, a time when advances in information technology truly transformed the way we live our lives.  If medical science continues to advance at current rates, I believe that the first half of this century will as likely be recalled as the Age of Life Science &mdash; the time when our lives were transformed at the metabolic level.  Indeed, on every front, whether it be genomics or oncology, neurology or stem cell research, reports of dramatic discoveries arrive almost daily, many suggesting the promise of cures that only a short time ago would have seemed little short of miraculous.</p>
			<div class="calloutright">
				<p>There is art as well as science to healing.  And so it is that there are, human standards for health care that cannot be quantified, and should not be forgotten.</p>
			</div>
			<p>With these advances has come a mighty proliferation of medical specialties, technology and tools. The hospital of today veritably swarms with health care providers, and hitherto unitary disciplines continue to speciate with an energy that would astound Charles Darwin. At their beck and call are a host of room-sized diagnostic tools developed by their engineering peers, and no modern hospital can now compete for business unless it is chockablock full of CAT Scan, MRI, PET Scan and other wildly expensive machinery that peers into the body to extract information hitherto unavailable, often illuminated by exotic dyes and radioactive imaging agents.</p>
			<p>Happy the modern citizen must be, then, to live in this age of science and specialists; how fortunate to be at the center of so much science, technology and expert attention.</p>
			<p>Happy and fortunate indeed.  That is, unless that citizen actually has to be in a hospital, beset upon by those swarms of specialists, and constantly wheeled through forbidding corridors to the nether regions of the facility to be splayed under, inserted inside, or (worse yet, as I am informed by patients of the feminine persuasion) have sensitive parts of her body mashed between the frigid plates of an infernal medical device delivering images that too often hold prospect of only worse to come.</p>
			<p>But at least with so much exquisitely trained attention, the quality of the care must be of the highest, and unfortunate outcomes lower than ever before.  Right?  Right?</p>
			<p>Well.  (How to say delicately?)  Ah yes &mdash; here we are.</p>
			<p>Let us consider this:</p>
			<p>Back in the Dark Ages of Medicine (i.e., just before that Computer Age we were discussing a little while ago), only about a dozen medicines &mdash; most of ancient, herbalist origin &mdash; were of known efficacy in the ages-old battle against disease.  Aspirin to treat fever, inflammation and pain (Native Americans chewed willow bark to extract the same active agent); quinine to suppress malarial attacks (the Quechua Indians of Peru used cinchona bark to quell fevers and tame chills &mdash; and invented tonic water in the process); opium from poppies to alleviate physical pain (some employed the substance to address other types of pain); digitalis from foxglove for heart arrhythmia; mercury in its elemental form as a brutal treatment for syphilis ("spend a night with Venus, and a lifetime with Mercury").  A handful of other medicines completed the pharmacopoeia of efficacious remedies throughout most of our national existence, from Colonial time until World War II.  Those compounds, and a few early vaccines &mdash; most notably for hydrophobia (rabies) and smallpox.</p>
			<p>Eventually, and thank heaven, the blessings of ether were discovered for surgery.  No longer, at last, was the measure of a surgeon's skills his ability (there were no "hers" in the surgical theatres of the time) to cut a patient for the stone in less than seven minutes.  Around the same time, the importance of antiseptic care was appreciated, and patients at last became more likely to survive a hospital stay than not.</p>
			<p>But while anatomy and principles of public health became better understood, the causality of non-infectious diseases like cancer and the nature of debilitating heredity diseases remained locked in black boxes of mystery, until Watson and Crick cracked the lid.  Worse, a host of implacable maladies now virtually unknown to modern society harvested their victims year by year: scarlet fever, diphtheria, pertussis (whooping cough), measles, mumps, tetanus, rheumatic fever, the dreaded summer visit of the polio virus, and more.  Together, these grim and common diseases culled the children of families everywhere.  Indeed, any American above the age of 80 who came from a large family would as likely as not be able to tell you of the loss of one or more or siblings to these scourges.</p>
			<p>In these still-recent days before the advent of penicillin and sulfa drugs, decoded DNA and modern cytology, there was only so much that a doctor (like my grandfather) could do.  Indeed, the principle role that a physician could play in the case of infectious or hereditary disease was to visit the sick at their homes, try to make them comfortable, and predict for their families with some degree of accuracy what would happen next.  Almost as the shaman of primitive societies was brought by the family to mediate between the real and the spirit world on behalf of the afflicted, doctors before the age of modern medicine too often could only share what they knew from observation, and like their patients, patiently wait.</p>
			<p>The result was a special bond between patient, family and physician &mdash; with the patient and doctor at the center, both engaged in a conjoint, often powerless struggle with forces largely beyond their control.  A good doctor was therefore humble, knowing the limits of his ability to influence the outcome.  With so little to offer by way of efficacious care, the ability to give comfort and courage was as important as the limited ability to take curative action.  And with so few investigative tools available &mdash; all of which could be carried in the legendary doctor's black bag (my father still had one for house calls when I was young) &mdash; the physician's powers of visual and tactile observation in days gone by were acute; much more so than those of today's lab-dependent doctors.  As Lewis Thomas reminisced in his wonderful book, <a href="http://www.amazon.com/Youngest-Science-Medicine-Watcher-Alfred-Foundation/dp/0140243275/ref=pd_bbs_sr_1?ie=UTF8&s=books&qid=1233170060&sr=8-1">The Youngest Science: Notes of a Medicine-Watcher</a>, a physical exam performed by a skilled physician could be a beautiful, as well as an informative, thing to behold.</p>
			<div class="calloutright">
				<p>Somehow, we have become possessors of (or perhaps possessed by) a vastly expensive and too-often fallible medico/pharma/insurer/industrial complex.</p>
			</div>
			<p>Today, almost all of that world is gone from the modern American medical scene.  Instead of the single physician visiting the patient at home, or visiting the hospitalized patient twice a day, there is now a post-operative care team that commonly includes the surgeon, anesthesiologist, pain-control physician, plastic surgeon, oncologist, medical attending physician, multiple interns, and more.  Each treats a piece of the patient for a few minutes out of the day, and each may contribute to the chart.  Mistakes &mdash; thousands of them every year and many of them fatal &mdash; are made.</p>
			<p>Almost as regrettably, from the standpoint of effective treatment, none of the attending physicians really "knows" the complete patient, because each is a specialist, and so much has been delegated to so many other professionals to whose professional judgment each must, to some degree, defer. Such a system could conceivably work if the entire school of physicians swam together through the hospital on twice-daily rounds, but of course they do not.  Instead, each must follow the breadcrumbs of the others via common review of the paper and/or electronic medical record of the patient, supplemented by occasional one-on-one consultations.</p>
			<p>And, perhaps, a few words with the patient.  But the number of doctors that sit on the end of the bed, or put a reassuring hand on the shoulder, is fewer year by year.  With the proliferation of specialties, it is easy for a medical student to find one where patient skills might seem to no longer matter so much (but of course they always do, to the patient).  As one physician recently said to me, "There are only two types of oncologists: saints and jerks."</p>
			<p>The patient, it seems, is no longer truly at the center of the health care concept.  Instead, it seems that role has been taken by the reimbursable "disease condition"  around which vital signs, laboratory tests, scans and specialists orbit.</p>
			<p>Somehow, we have become possessors of (or perhaps possessed by) a vastly expensive and too-often fallible medico/pharma/insurer/industrial complex.  When in its custody, the patient (no matter how sick) is awakened every four hours, night and day, to have vital signs taken, and at least once a day (usually at 5:00 AM), to be pointed at and discussed upon by a resident with multiple interns in tow as part of the hospital's medical training program.  When the appointed hour finally comes, the patient is delivered (by wheelchair) back to the street, often too soon for ideal care and comfort, due to the outrageous costs of so much Balkanized attention.</p>
			<p>How did we arrive at such a pass, where the humanity and well being of the patient has receded so far beyond the horizon, to be replaced by some cold and clinical abstraction of the word "care?"  And what of the future, when the doctor need not even visit the hospital room to review a chart?  In the imminent future of electronic health records, will the patient find herself speaking not to a doctor at her bedside, but to an image on the television hanging high on the wall, as each specialist makes his "rounds" via video link as expeditiously as possible, sitting at his remote computer terminal, patient records displayed on a second screen?</p>
			<p>A ridiculous suggestion?  Perhaps.  But things tend to happen once they can &mdash; and especially so when they become more cost-effective than the ways of the past.</p>
			<p>If we are to pull back in time from such an Orwellian future of patient "care," we need to remember that there is still an art as well as a science to healing.  The time is now, if indeed it is not already too late, to recognize that there are human standards for health care that cannot be quantified, and should not be forgotten.</p>
			<!-- ************* -->
			<div class="clear"></div>
			<p class="center">Copyright 2009 Andrew Updegrove</p>
			<p class="center">Read more <strong><em>Consider This&hellip;</em></strong> entries at: <a href="/blog/">http://www.consortiuminfo.org/blog/</a></p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!-- MONDAY WITNESS  -->
			<!-- ******************* -->
			<a name="mondaywitness" id="mondaywitness"></a>
			<h4>MONDAY WITNESS:</h4>
			<h3>Inauguration Day &mdash; January 20, 2009</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<blockquote><em>I ask you to share with me today the majesty of this moment. In the orderly transfer of power, we celebrate the unity that keeps us free. Each moment in history is a fleeting time, precious and unique. But some stand out as moments of beginning, in which courses are set that shape decades or centuries. This can be such a moment.</em></blockquote>
			<img class="imgleft" src="dec08/dec08_img6.jpg" alt="" width="200" height="147" border="0" />
			<p>When I was much younger, still in school, I was fortunate enough to receive a ticket to a Presidential inauguration.  It was a good ticket, allowing me to stand not a hundred yards from the podium where the new president would stand as first he was sworn in, and then as he delivered his inaugural address. </p>
			<p>Then, as now, it was a time of uncertainty, with wars both cold and hot raising tensions internationally and inflaming passions at home.  The campaign just ended had been divisive, as had the primaries preceding it.  There was much to weigh down the shoulders of a new president as he waited to take his oath of office, and many reasons to doubt his ability to deliver on the vision for the future that he would share. </p>
			<p>The address that I heard that day was eloquent and high-minded.  In it the new President asked:</p>
			<blockquote><em>What kind of nation we will be, what kind of world we will live in, whether we shape the future in the image of our hopes, is ours to determine by our actions and our choices....If we succeed, generations to come will say of us now living that we mastered our moment, that we helped make the world safe for mankind. This is our summons to greatness.  I believe the American people are ready to answer this call.</em></blockquote> 
			<p>As I recall it, the day was gray, with lowering clouds and a threat of rain, matching the national mood that it would be the new President's task to lift.  Underscoring the uncertainties of the day, platoons of armed National Guards stood at parade rest every fifty yards along the iron fence that surrounded us, as we faced the East Portico of the Capitol, where inaugurations were then held.  At the same interval atop every building with a sight line of the podium stood a sharpshooter, scanning the crowd. Above, helicopters criss-crossed the sky.</p>
			<p>It was, after all, a time not only a time of war abroad, but of unrest and assassinations at home. The President who spoke that day had promised to "bring us together," and the need to achieve that goal was great, both politically as well as socially.  His predecessor had left office with abysmal approval ratings, dragged down by a war that had overshadowed all of the great hopes he had nurtured, and his successes as well.  A substantial percentage of the electorate could not wait to witness his departure. </p>
			<p>The electorate was, in a word, exhausted, and the need to restore unity great.  Addressing this somber truth, this is what he said: </p>
			<blockquote><em>The simple things are the ones most needed today if we are to surmount what divides us, and cement what unites us. To lower our voices would be a simple thing. In these difficult years, America has suffered from a fever of words; from inflated rhetoric that promises more than it can deliver; from angry rhetoric that fans discontents into hatreds; from bombastic rhetoric that postures instead of persuading. We cannot learn from one another until we stop shouting at one another &mdash; until we speak quietly enough so that our words can be heard as well as our voices.</em></blockquote>
			<p>Then, as now, the contrasts that day were stark &mdash; between the opportunity for the new President to achieve grand results, and the certainty that, almost immediately, events and forces as yet unknown would inevitably work to thwart him.  Would he be able to rise to the challenge?  Would he have within him the force of character, the reserves of strength and dispassionate judgment to hold true to his purpose, and deliver upon the hopes of those that had elected him?  Would he even remember those promises, and remain true to those hopes?  Or would he allow himself to be distracted and seduced by the trappings of power?  This is what he said: </p>
			<blockquote><em>For its part, government will listen. We will strive to listen in new ways &mdash; to the voices of quiet anguish, the voices that speak without words, the voices of the heart &mdash; to the injured voices, the anxious voices, the voices that have despaired of being heard.  Those who have been left out, we will try to bring in. Those left behind, we will help to catch up. For all of our people, we will set as our goal the decent order that makes progress possible and our lives secure.</em></blockquote>
			<p>There was, of course, no way to tell that day whether these promises would be kept.  Only the slow, day by day unwinding of a new administration would reveal whether this leader would rise to the challenge, and not succumb to the centripetal forces of politics that would constantly stand in the way of achieving these  high ideal.  Of course, he promised that he would stand fast: </p>
			<blockquote><em>As we reach toward our hopes, our task is to build on what has gone before &mdash; not turning away from the old, but turning toward the new. In this past third of a century, government has passed more laws, spent more money, initiated more programs, than in all our previous history. In pursuing our goals of full employment, better housing, excellence in education; in rebuilding our cities and improving our rural areas; in protecting our environment and enhancing the quality of life &mdash; in all these and more, we will and must press urgently forward.</em></blockquote>
			<p>As importantly, I wondered, would he be able to inspire the nation, to gather not only the political support of the electorate but also to recruit its active assistance in doing what needed to be done?  Too many Americans had become jaded or cynical, too demoralized to even make their voices heard.  To them, he said: </p>
			<blockquote><em>Our greatest need now is to reach beyond government, and to enlist the legions of the concerned and the committed. What has to be done, has to be done by government and people together or it will not be done at all. The lesson of past agony is that without the people we can do nothing; with the people we can do everything.</em></blockquote>
			<p>Of course, in those days, issues of domestic racial and social injustice were even more urgent.  Most of the post World War II laws enacted and social programs deployed to address those concerns had either just been created or lay still in the future.  The urgency to move forward in these areas was felt palpably by millions of Americans on a daily basis.  Of this crisis, he said: </p>
			<blockquote><em>This means black and white together, as one nation, not two. The laws have caught up with our conscience. What remains is to give life to what is in the law: to ensure at last that as all are born equal in dignity before God, all are born equal in dignity before man.</em></blockquote>
			<p>Internationally, it was the age of the "Ugly American."  In many quarters, the United States was regarded as arrogant and indifferent, too often concerned only with its own well being and self-interest.  In the eyes of many in the first world and third world alike, we were insensitive to the cultures and callous to the concerns of others, unable to recognize or appreciate the realities of those different from ourselves.  And locked in the embrace of an enduring Cold War, we viewed every nation not as a potential ally, but as yet another battleground upon which a proxy war for hearts and minds must be won in a global war of ideologies.  That day, the new President pledged himself to bring change.  He said: </p>
			<blockquote><em>As we learn to go forward together at home, let us also seek to go forward together with all mankind. Let us take as our goal: where peace is unknown, make it welcome; where peace is fragile, make it strong; where peace is temporary, make it permanent. After a period of confrontation, we are entering an era of negotiation. Let all nations know that during this administration our lines of communication will be open. We seek an open world &mdash; open to ideas, open to the exchange of goods and people &mdash; a world in which no people, great or small, will live in angry isolation. We cannot expect to make everyone our friend, but we can try to make no one our enemy&hellip;</em></blockquote>
			<p>All of these concerns, and more, were in the air that inauguration day of so long ago.  And all of the hopes of those both present and at home, both in this country and of many abroad, were, for that moment and on that day, invested in the man that stood at the podium, hand on bible, assuming the awesome duties of the U.S. presidency.  He closed his inaugural address with these words: </p>
			<blockquote><em>We have endured a long night of the American spirit. But as our eyes catch the dimness of the first rays of dawn, let us not curse the remaining dark. Let us gather the light. Our destiny offers, not the cup of despair, but the chalice of opportunity. So let us seize it, not in fear, but in gladness &mdash; and, "riders on the earth together," let us go forward, firm in our faith, steadfast in our purpose, cautious of the dangers; but sustained by our confidence in the will of God and the promise of man.</em></blockquote>
			<p>To me, the inspiring words quoted above sound as if they could have been spoken by Barack Obama.  I expect &mdash; and indeed hope &mdash; that what we hear today will be much the same.  Sadly, though, the day that I attended the inauguration was January 20, 1969, exactly 40 years ago today.  And the man that gave the speech was Richard M. Nixon, about to begin his first term in the White House.  </p>
			<p>On that gray and threatening day lay the prospect of both endless promise and depths of danger too awful to contemplate.  Had Nixon been true to the vision he shared that day, had he been able to find within himself the strength of character and the clear and selfless vision that the tasks at hand demanded, all could have been so very different. </p>
			<p>Like all Americans, as well as many people around the world, I will be listening to the inaugural speech of Barack Obama today with the greatest of anticipation and hope.  Four decades ago, everyone hoped that Richard Nixon would succeed, but few that had followed his career were inspired to believe that day that he would succeed.  </p>
			<p>As then, our times today are dark, and the way ahead is unclear.  But unlike those dark days of the 1960s, this is a time of true celebration and genuine inspiration.  Not because the times are less troubling, but because the President elect is less troubled.  Unlike the paranoid and conflicted Nixon, Barack Obama seems at ease with himself, and projects an ability to selflessly lead.  Never before in my lifetime has there been such a wave of hope converging upon a single leader, nor such a confluence of goodwill from all sides. </p>
			<p>When the crowds disperse from the Capitol today, the hopes and dreams of millions will be left on the slender shoulders of this largely untested President.  He will  carry those burdens every day of his presidency, and their weight will be great. </p>
			<p>Whether Barack Obama will be able to maintain the clarity of vision and calmness of spirit that elevated him above the other candidates remains to be seen.  Many of his most talented predecessors have allowed themselves to be dragged down by events, enmired in crises, or embroiled in scandals.  The odds against his success will be great as well. </p>
			<p>But there is much about the man that promises well.  During the difficult days that are sure to lie ahead, perhaps it will help Mr. Obama if he reads his own inaugural address from time to time.  There he may find what it takes to keep his compass true, and his convictions strong.  </p>
			<p>Like so many others, my hopes and dreams and prayers for his success &mdash; and ours &mdash; will be with him.</p>
			<!-- ************* -->
			<p class="center"><em>You can read the full text, and hear Nixon deliver his first inaugural address <a href="http://watergate.info/nixon/inaugural-speech-first.shtml">here</a>.</em></p>
			<p class="center"><em>A video of Obama's inaugural speech can be viewed and heard <a href="http://www.whitehouse.gov/blog/inaugural-address/">here</a>.</em></p>
			<p class="center">Copyright 2009 Andrew Updegrove</p>
			<p class="center"><em>Read more <strong><a href="http://www.consortiuminfo.org/standardsblog/index.php?topic=3584">Monday Witness</a></strong> entries at:<br />http://www.consortiuminfo.org/standardsblog/index.php?topic=3584</em></p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />

		</div>
	</div>
<div class="clear"><br /></div>
<!-- *********** -->
<!-- FOOTER  -->
<!-- *********** -->
<?php include '../includes/footer.php'; ?>
</form>
</body>
</html>