<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Consortiuminfo.org Consortium Standards Journal &mdash; February &ndash; March 2008</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta name="description" content="While standard setting has been an important aspect of industrial society for over a hundred years, the formation of unofficial, fast-acting standard setting and promotional consortia is a more recent phenomenon which is only now beginning to be seriously studied" />
<meta name="keywords" content="standard setting, promotional consortia, structuring of consortia, standardize, intellectual property policies, procedures, founding company, model, best practices, promoter/adopter structurer, joint venture, IPR, " />
<meta name="author" content="Andrew Updegrove" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/screen.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/journal.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/toolsets.css" />
<!-- ALTERNATE -->
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/default.css" title="default" />
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/large.css" title="large" />
<!-- ********* -->
<link rel="home" title="home" href="http://www.consortiuminfo.org" />
<script type="text/javascript">AC_FL_RunContent = 0;</script>
<script type="text/javascript" src="/scripts/AC_RunActiveContent.js"></script>
<script type="text/javascript" src="/scripts/styleswitcher.js"></script>
<script type="text/javascript" src="/scripts/obfuscate.js"></script>
</head>

<body id="bulletin">
	<!-- ****************** -->
	<!--   ACCESSIBILITY    -->
	<!-- ****************** -->
	<?php include '../includes/accessibility.php'; ?>
	
	<!--   SEARCH FORM   -->
	<form class="search" name="form1" method="get" action="http://search.Blossom.com/query/320">
	
	<!-- ************* -->
	<!--   MASTHEAD    -->
	<!-- ************* -->
	<?php include 'includes/masthead_journal.php'; ?>
	
	<!-- *********** -->
	<!--   BANNER    -->
	<!-- *********** -->
	<div id="banner">
		<div class="left">
			<p><a href="/">Home</a> &gt; <a href="/bulletins/">Standards Today</a> &gt; February &ndash; March 2008</p>
		</div>
		<div class="right">
			<p><input type="text" name="key" /><input type="submit" name="Submit" value="Search" /> <a href="/search/">Advanced</a></p>
		</div>
		<div class="clear"></div>
	</div>
	
	<!-- ************** -->
	<!--   MAIN BODY    -->
	<!-- ************** -->
	<div class="JournalContent">
	<!-- SKIP/START CONTENT LINK -->
	<a name="startcontent" id="startcontent"></a>
		
		<!-- SIDEBAR CONTENT AREA -->
		<div class="AllSidebar">
			<div>
				<?php include '../includes/clients.php'; ?>			
			</div>
			<div class="AllNav">
				<p class="AllNavLink">&raquo;&nbsp;<strong><a href="/bulletins/archive.php" style="border-top:0px;">Journal Archive</a></strong></p>
			</div>
			<div class="AllNav">
				<p class="AllNavLink">&raquo;&nbsp;<a href="/bulletins/pdf/feb08/feb08.pdf">Download PDF</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="mailto:?subject=Standards%20Today&amp;body=http://www.consortiuminfo.org/bulletins/feb08.php">Email this issue</a></p>
			</div>
			<?php include '../includes/toolsets.php'; ?>
		</div>
		
		<!-- BODY CONTENT AREA -->
		<div class="JournalMain">
			
			<h1>Standards Today</h1>
			
			<!-- ************* -->
			<!--     INDEX     -->
			<!-- ************* -->
			<div id="tableofcontents">
			<h2>February &ndash; March 2008<br /><span class="volumeinfo">Vol VII No 2</span></h2>
			<h3>Recognizing "Civil ICT Rights" And Civil ICT Standards</h3>
			<!-- INDEX ITEM -->
			<p><span class="section">EDITOR'S NOTE:</span><br /><span class="title"><a href="#editorsnote" title="Editors Note" accesskey="3">What Just Happened?</a></span></p>
			<p>The "Fast Tracking" of OOXML is over. Now it's time to clean up.<br /><a class="pdf" href="http://consortiuminfo.org/bulletins/pdf/feb08/feb08_editorsnote.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">EDITORIAL:</span><br /><span class="title"><a href="#editorial" title="Editorial" accesskey="4">BRM Blowback</a></span></p>
			<p>In the last issue's editorial, I predicted that the confidential OOXML Ballot Resolution Meeting would fail to achieve its objectives.  I was both right and wrong: there was only time to discuss and, as needed, revise a small percentage of the c. 900 substantive comments registered last year &mdash; but as of this point in time, it appears that OOXML may have been adopted anyway.  Whether or not the final vote count indicates that OOXML has won, the credibility and integrity of the  formal standard setting system certainly lost.<br /><a class="pdf" href="http://consortiuminfo.org/bulletins/pdf/feb08/feb08_editorial.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">FEATURE ARTICLE:</span><br /><span class="title"><a href="#feature" title="Feature Article" accesskey="5">A Proposal to Recognize the Special Status of "Civil ICT Standards"</a></span></p>
			<p>The history of humanity demonstrates an ongoing evolution in the balancing of the rights of the individual with those of society.  Only in modern times have many of the civil rights we hold to be most dear become recognized and protected by law.  With many of these rights now being exercised virtually through the use of information and communications technology (ICT) rather than in person, care must be paid to ensure that these rights are not diminished or endangered.  In order to protect such "Civil ICT Rights," we will need to take special care in developing "Civil ICT Standards."<br /><a class="pdf" href="http://consortiuminfo.org/bulletins/pdf/feb08/feb08_feature.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">STANDARDS BLOG:</span><br /><span class="title"><a href="#blog" title="Standards Blog" accesskey="6">Tracking the Man with the Gavel: Alex Brown on the BRM</a></span></p>
			<p>In advance of the Ballot Resolution Meeting in Geneva charged with resolving open issues with OOXML, pundits speculated about how Convenor Alex Brown would grapple with the seemingly impossible task.  Alex gave some indications of his strategy at his blog, and also offered this prediction: "This will be no love-in." He was right.<br /><a class="pdf" href="http://consortiuminfo.org/bulletins/pdf/feb08/feb08_blog.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">WAR OF THE WORDS:</span><br /><span class="title"><a href="#warofwords" title="War Of The Words" accesskey="7">Chapter 4: Eric Kriss, Peter Quinn, and the ETRM</a></span></p>
			<p>In this chapter, the architects of the decision to adopt ODF &mdash; and not Microsoft’s OOXML &mdash; begin to plan the visionary "Enterprise Technical Reference Model" that would eventually incorporate that decision.<br /><a class="pdf" href="http://consortiuminfo.org/bulletins/pdf/feb08/feb08_warofwords.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">CONSIDER THIS:</span><br /><span class="title"><a href="#considerthis" title="Consider This" accesskey="7">Steve Jobs' Endangered Second Act</a></span></p>
			<p>It is a truism of American life that you only get one chance to Have it All. Steve Jobs' first chance at dominating a computer platform died at the hands of Bill Gates in the early 1980s, in large part because Gates was willing to license his technology to clone makers while Jobs was not. Now comes Apple's wildly popular iPhone: will Steve Jobs enjoy a second act with this new platform even more successful than the first &mdash; or only a replay, and for the same reasons?<br /><a class="pdf" href="http://consortiuminfo.org/bulletins/pdf/feb08/feb08_considerthis.pdf">Download PDF</a></p>
			<p class="center"><a class="pdf" href="/bulletins/pdf/feb08/feb08.pdf">Download PDF of this issue</a></p>
			<div class="hr"></div><hr />
			</div>
		
			<!-- ************* -->
			<!-- EDITOR'S NOTE -->
			<!-- ************* -->
			<a name="editorsnote" id="editorsnote"></a>
			<h4>EDITOR'S NOTE:</h4>
			<h3>What Just Happened?</h3>
			<p>In our last issue, OOXML (a/k/a Ecma 376, a/k/a DIS 29500) was packing its bags to head for Geneva, there to be pored over behind closed doors by c. 120 standards professionals from around the world. With some 1,100 comments to consider (c. 900 substantive, and the remainder non-controversial editorial clean ups), they knew that their task would not be easy. It wasn't.</p>
			<p>As I write these words, the votes are being tallied from the thirty day final voting period on OOXML, which closed at midnight, Geneva time, on Saturday, March 29.  More properly stated, what is being tallied are the votes that changed, since re-voting is not required.  If votes are changed with a sufficiently positive net effect, OOXML will have been adopted by ISO/IEC JTC1.  At this moment in time, someone in Geneva knows whether OOXML has been approved, but the public does not.  But on April 2, ISO plans to announce the vote, at which point the rest of the world will learn the result as well.</p>
			<p>As of now, I have been able to determine, through public and private sources, that enough votes have changed to approve OOXML &mdash; unless enough as yet undisclosed votes have shifted in the other direction (my running tally can be found <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20080329071456170">here</a>; as of this moment in time, 22 out of 87 eligible National Bodies are recorded there, and OOXML has a margin of victory equal to three votes under the more difficult of the two tests used to determine success or failure).  Already, however, that margin is eroding, as Norwegian Ministry of Trade has already filed a <a href="http://blogs.freecode.no/isene/2008/03/31/norwegian-committee-chairman-to-iso-count-the-vote-as-no/">formal protest</a> with ISO &mdash; asking that its own vote be disregarded, pending the results of in internal investigation.</p>
			<p>But the vote itself is  only one of two bottom line stories. The other is "what does it all mean?" And that's what this issue is all about.</p>
			<p>In my <strong><em>Editorial</em></strong>, I focus on the collateral damage that the formal standards development and adoption system has suffered during the Fast Track adoption of OOXML &mdash; an over 6,000 page specification.  That process has been marred by many allegations of improprieties (most frequently "stacking" of committees, but also fun and games with rules, and one confirmed case of financial incentives being provided to business partners to help ensure the desired vote in Sweden), undue pressure applied by vendors, and more.</p>
			<p>In the penultimate step, the Ballot Resolution Meeting in Geneva predictably had time to actively debate and, as necessary, revise only a small percentage of all proposed resolutions.  Accounts of the meeting varied wildly, as did the claims relating to its success or failure.  Since the meeting was held behind closed doors and memorialized by only skeletal minutes, there is no way for the public to know exactly what happened, who to believe, or what it all means.  It may come as no surprise, therefore, that my Editorial calls for a thorough review by a neutral committee, and for that committee to recommend appropriate rules to ensure a better result the next time such a contentious situation arises, as it surely will.</p>
			<p>In the <strong><em>Feature Article</em></strong> for this issue, I focus on the accelerating transition from in-person to on-line exercise of civil rights, and note that to date we have given insufficient attention to ensuring that these precious rights are not compromised as their exercise grows increasingly dependent on information and communications technology (ICT).  I suggest a new term to recognize this new reality, and refer to them as "Civil ICT Rights."  I also note that in many important respects &mdash; as is the case with document format standards &mdash; these rights may only be protected by standards &mdash; which I logically refer to as "Civil ICT Standards."  Using the just-completed OOXML process a business case, I make the case that the development of such Civil ICT Standards requires greater attention and protection, so that our Civil ICT Rights can also be protected and preserved.</p>
			<p>My <strong><em>Standards Blog</em></strong> selection seems, from this remove, to be almost a nostalgic, Edenic, "Before the Fall" reminiscence: written before the Ballot Resolution Meeting, it describes the daunting task that BRM Convenor Alex Brown would face in Geneva, and how he planned to deal with that challenge.</p>
			<p>I also include another sample chapter from <strong><em>War of the Words</em></strong>, my ongoing eBook project chronicling the ODF-OOXML contest from its early days.  The included chapter tells the story of how the architects of the decision by Massachusetts to adopt ODF, but not OOXML, for its Executive Agencies' exclusive use moved towards that decision.</p>
			<p>I close, as usual, with my <strong><em>Consider This</em></strong> essay, which departs from the document format theme to reflect upon opportunities seized and, perhaps lost, in another closely contested and enormously strategic race: the global contest to dominate the "smartphone" platform.  Will Steve Jobs not only take the early lead this time, but also continue to dominate the Smartphone marketplace?  Or will he once again lose his advantage, through asserting too great a degree of proprietary control?  In this essay, I give my view.  Only time, of course, will tell.</p>
			<p>Meanwhile, it's an awesome cool tool.</p>
			<p>As always, I hope you enjoy this issue.</p>
			<!-- ************* -->
			<div class="credit">
				<p>Andrew Updegrove<br />Editor and Publisher<br />2005 ANSI President's<br />Award for Journalism</p>
				<div class="clear"></div>
			</div>
			<p class="note">The complete series of Consortium Standards Bulletins can be accessed on-line at <a href="http://www.consortiuminfo.org/bulletins/">http://www.consortiuminfo.org/bulletins/</a>. It can also be found in libraries around the world as part of the EBSCO Publishing bibliographic and research databases.</p>
			<p>Sign up for a <strong><em><a href="http://www.consortiuminfo.org/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p> 
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ************* -->
			<!--   EDITORIAL   -->
			<!-- ************* -->
			<a name="editorial" id="editorial"></a>
			<h4>EDITORIAL:</h4>
			<h3>BRM Blowback</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<p>The last issue of <em>Standards Today</em> was titled, <a href="http://www.consortiuminfo.org/bulletins/jan08.php">ODF vs. OOXML on the Eve of the BRM</a>. That issue focused on the Ballot Resolution Meeting (BRM) about to be held in Geneva, Switzerland as the penultimate act in the Fast Track approval process of DIS 29500, the specification submitted by Ecma and based upon Microsoft's OfficeOpen XML document formats (OOXML).</p>
			<p>My editorial in that issue was prophetically titled <a href="http://www.consortiuminfo.org/bulletins/jan08.php#editorial">The Overwhelming of ISO/IEC JTC1</a>, due to the fact that only one week had been allocated to resolving more than 1,100 separate comments (some 900 of them substantive) that had been registered by National Bodies from around the world during the voting period that failed to approve OOXML during the initial balloting period in mid-2007.</p>
			<p>Without exception, every fear that I raised in that editorial was realized, and worse.  Here is a sampling:</p>
			<blockquote><em>Prior concern:</em> "Due to the 6,000 page length of OOXML, not all problems are likely to have been identified during the formal review period.  But any deficiencies in OOXML discovered after September 2, according to the JTC1 Directives <a href="http://www.adjb.net/index.php?entry=entry080107-183411">as cited by Brown</a>, are "out of scope," and may not be addressed at the BRM. Instead, they must await resolution in the next review cycle (i.e., years in the future)."</blockquote>
			<blockquote><em>Reality:</em> Far from worrying about addressing new concerns, there was (as expected) insufficient sufficient time to interactively discuss and, as necessary, revise the vast majority of old comments.  One consequence was that addressing even many of the concerns submitted in 2007 were deferred to resolution during a future "maintenance phase" of the specification.</blockquote>
			<blockquote><em>Prior concern:</em> "It does not appear at this time as if the resolutions proposed by Ecma will be made available at a public Web site before the BRM, if ever. Consequently, the 500 million users of Office and the legions of independent software vendors whose software must be used in conjunction with Office will have no opportunity to convey their opinions to the delegates that will nominally represent their interests at the BRM."</blockquote>
			<blockquote><em>Reality:</em> Not only did those who were not involved have the opportunity to access the proposed resolutions for review, but one official delegation complained that it had not been able to consider any proposed resolutions other than those offered in response to their own comments.</blockquote>
			<blockquote><em>Prior Concern:</em> "The final vote on OOXML will follow the conclusion of the BRM, whether or not all comment resolutions have been resolved. It appears that if the vote is in favor of adoption, unresolved comments will not be dealt with, if ever, until the next review cycle."</blockquote>
			<blockquote><em>Reality:</em> Only a small percentage of the c. 900 substantive resolutions were interactively discussed and, as necessary, revised.  The remainder was disposed of in a process that allowed each delegation to vote upon each resolution that it wished to weigh in on, and to make a blanket choice of "approve," "disapprove" or "abstain" as to the balance, if desired.  The time permitted for voting on all c. 900 proposed resolutions (comprising well over 1,000 pages of text) was less than 24 hours.<br /><br />Confronted with this impossible task, only six delegations chose to approve and four chose to disapprove.  Of the remainder, 18 chose "abstain" &mdash; and four chose not to register a position at all.  As one delegate stated in the meeting, "If this was all that would be permitted, I would have preferred to have stayed at home and had two weeks to consider how to vote."  Despite the fact that in the ordinary course all resolutions would be discussed, during as many meetings as needed, OOXML proponents announced that the BRM "<a href="http://blogs.msdn.com/jasonmatusow/archive/2008/02/29/the-open-xml-ballot-resolution-meeting-brm-was-an-unqualified-success.aspx">was an unqualified success</a>."</blockquote>
			<blockquote><em>Prior Concern:</em> "No outsiders will be allowed to attend the BRM, nor will any transcript be prepared and made available."</blockquote>
			<blockquote><em>Reality:</em> Only a skeletal summary of the actions discussed and resolutions adopted was made available.  Moreover, those in attendance were requested not to discuss anything that transpired during the BRM with anyone outside the meeting, either during the course of the meeting or afterwards.  Not surprisingly, the result is that widely different accounts were posted even by those who had attended the BRM, ranging from the pronouncement by one delegate that the BRM had been "<a href="http://www.tbray.org/ongoing/When/200x/2008/02/29/BRM-narrative">complete, utter, unadulterated bullshit</a>," and the statement by another that "<a href="http://blogs.msdn.com/brian_jones/archive/2008/02/29/brm-is-done-time-to-sleep.aspx">The process really worked (it was very cool)</a>."  (I have provided links and excerpts from the accounts of nine delegates from 7 countries <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20080309054524379#others">here</a>, and much more original source material <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20080309054524379">here</a>, so that those that are interested can form their own judgment.)</blockquote>
			<p>In the absence of a detailed official record or the admission of the press or any other neutral third party, those around the world whose lives will be impacted by the final result can only scratch their heads and wonder what just happened, and who to believe.</p>
			<p>While every first hand account applauded the efforts of Convenor Alex Brown and of the delegates at making the best of the situation and achieving the greatest degree of improvement in DIS 29500 possible, the result by anyone's account was the submission for final voting of a specification that had received less attention and collaborative effort to improve its quality than would typically be the case under any other circumstance.</p>
			<p>And there was more to come.  During the thirty day voting period that immediately followed, accusations of abuse of process at the National Body level once again abounded.  And once again, accounts of what actually happened varied widely.  Here is a sample, posted by Geir Isene at his blog on March 30.  In it, he gives his version of <a href="http://blogs.freecode.no/isene/2008/03/30/promoting-the-repair-shop-philosophy/">what happened</a> when the appropriate committee met in Norway to decide whether or not to change its vote on OOXML:</p>
			<blockquote>March 28th: Meeting in the Norwegian Standards Institute (Standard Norge).</blockquote>
			<blockquote>Purpose: To decide the final vote for Norway on whether the document format OOXML should become an international standard.</blockquote>
			<blockquote>The meeting: 27 people in the room, 4 of which were administrative staff from Standard Norge.</blockquote>
			<blockquote>The outcome: Of the 24 members attending, 19 disapproved, 5 approved.</blockquote>
			<blockquote>The result: The administrative staff decided that Norway wants to approve OOXML as an ISO standard.</blockquote>
			<blockquote>Their justification: "Standard Norge puts emphasis on that if this [OOXML] becomes an ISO/IEC standard, it will be improved to better accommodate the users' needs."</blockquote>
			<blockquote>This translates to: "Yes, we know the standard is broken, 79% of our technical committee have told us. But we hope that it someday will be repaired by someone. And we'll be happy to help if someone can give us the resources."</blockquote>
			<blockquote>Alright, the Norwegian Standards Institute is moving away from adopting quality standards to promoting a repair shop philosophy.</blockquote>
			<p>Needless to say, such accounts do not inspire confidence in those that must live with the decisions made by those with the authority to make them.  Nor did the news on March 31 that the Chairman of the same committee had just sent a formal protest to ISO, that included the following language:</p>
			<blockquote>Because of this irregularity, a call has been made for an investigation by the Norwegian Ministry of Trade and Industry with a view to changing the vote.</blockquote>
			<blockquote>I hereby request that the Norwegian decision be suspended pending the results of this investigation.</blockquote>
			<p>The <em>denouement</em> of this ongoing drama is that at the end of the thirty day voting period, a sufficient number of National Bodies &mdash; including Norway &mdash; appear to have changed their votes to secure the final adoption of OOXML (the formal announcement may not be made until just after this issue is delivered).</p>
			<p>Without assigning blame to either the proponents or opponents of OOXML, two questions that demand answers must be posed:  Is this any way to conduct the process whereby the global standards upon which governments and society rely are developed and adopted?  And if not, what will be done about it?</p>
			<p>It is impossible to avoid the conclusion that the credibility and integrity of the formal standards development process has suffered serious damage as a result of what has just transpired.  While that process may serve perfectly well under less contentious circumstances, reforms are obviously needed to address those exceptional circumstances in which greater protections are needed.</p>
			<p>In order for the credibility of the traditional system to be restored, a thorough review of the just completed DIS 29500 Fast Track process should be immediately commissioned.  That review should include recommendations for reform that would include, but not be limited to, suggesting revisions to the rules relating to Fast Track and PAS submissions, new National Body and ISO/IEC JTC1 rules relating to transparency and conflicts of interest, and providing for circuit breakers and corrective actions that could be invoked the next time such a process has clearly run off the rails.</p>
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="http://www.consortiuminfo.org/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--   FEATURE ARTICLE   -->
			<!-- ******************* -->
			<!-- NOTE: Pull          -->
			<!-- ******************* -->
			<a name="feature" id="feature"></a>
			<h4>FEATURE ARTICLE:</h4>
			<?php include '../bulletins/feb08/feb08_featureinc.php'; ?>
			<p>Sign up for a <strong><em><a href="http://www.consortiuminfo.org/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--   STANDARDS BLOG    -->
			<!-- ******************* -->
			<a name="blog" id="blog"></a>
			<h4>STANDARDS BLOG:</h4>
			<h3>Tracking the Man with the Gavel:<br />Alex Brown on the BRM</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<h6>Date: January 30, 2008<br /><span class="views">Views: 2,368</span></h6>
			<img class="imgright" src="/images/odf.gif" alt="" width="50" height="50" border="0" />				
			<p>As many of you are aware, Alex Brown will be the "Convenor" of the OOXML Ballot Resolution Meeting (BRM) that will run from February 25 through 29 in Geneva, Switzerland.  Alex has a variety of unenviable tasks, including:</p>
			<p>Trying to interpret various standing Directives and other ISO/IEC JTC1 rules and practices that were created for what might be described as kinder, gentler times (not to mention for shorter specifications).</p>
			<p>Figuring out how to process c. 1,000 comments (after elimination of duplicates) during a 35 hour meeting week, without the currently contemplated possibility of an extension.</p>
			<p>Herding 120 cats, some of which will have strong opinions on individual points, others of which will have alternating suggestions on how to resolve a given point,  and many of whom may be just plain bewildered, due to the lack of time to be fully prepared.</p>
			<p>For better or worse, the rules that Alex will be interpreting and applying are not as comprehensive, and certainly not as detailed, as the situation might demand to put everyone on exactly the same page regarding what should (or at least could) be done at many points in time.  As a result, knowing how Alex's thoughts are shaping up is both interesting and important.  To his credit, he has been generous about sharing those thoughts, and often how he arrived at them, at his blog, which can be found <a href="http://www.adjb.net/index.php">here</a>.</p>
			<p>While I've often linked to Alex's blog and have had a permanent link in the "Blogs I Read" category for some time, I'd like to point to Alex's latest entry, which covers several important points that others have recently blogged on.  In many cases, Alex comes out differently than some others that have stated firm opinions, and since Alex has the gavel, his opinion will be the one that counts.</p>
			<p>Alex's latest blog entry was posted yesterday, and is titled <a href="http://www.adjb.net/index.php?entry=entry080129-223209">Tracking OOXML issues</a>, and here are some of the things that I found instructive.</p>
			<p>For example, last week I posted a blog entry where I noted the difficulty that delegates would have preparing for the BRM, given the number of comments and the lengthy proposed dispositions document (2,300 pages).  Rick Jelliffe took issue with that, posting the following in a <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20080117130300657#comments">comment</a>:</p>
			<blockquote>Third, a reviewer for a national body will be primarily interested in the comments from that body. In most cases, the NBs comments are much less than 100 comments.</blockquote>
			<blockquote>Fourth, within each National Body, different members of the committees (and delegations) have different interests and strengths, so of course there is a division of labour.  There will be touchstone issues for each reviewer that they will often check thoroughly, and flip through the responses to issues that don't interest them or which are out of their expertise. There will also be some die-hard reviewers who will want to read all the responses, but they would not be the majority, for a large standard.</blockquote>
			<blockquote>Where did you get the idea that every person needs to understand every part of every response? That is not the way things work in large standards, it is committee work.  Why don't you join an international standards committee, so you can enhance your excellent prose with experience? I am sure everyone would benefit. Among other things I noted this is hardly a normal standards situation, that some delegations will consist of only one individual, who will therefore need to cover all comments, that many National Bodies (NBs) were indeed interested in the comments of other NBs, and that the dispositions of comments can cause new issues, which can be of concern (something Rob Weir <a href="http://www.robweir.com/blog/2008/01/what-every-engineer-knows.html">wrote about</a> a few days ago here).</blockquote>
			<p>So there you have the view of two pundits.  What's the real story?  Here's what the man with the gavel has to say:</p>
			<blockquote>The work however does not end there as the UK must finalise its view on other NBs' comments too. As the JTC 1 Directives explicitly state, the reason why all NB comments are distributed is to allow all NBs to form an opinion on all of them:</blockquote>
			<blockquote><blockquote style="font-size:100%">Upon receipt of the ballot results, and any comments, the SC Secretariat shall distribute this material to the SC NBs [&hellip;] The NBs shall be requested to consider the comments and to form opinions on their acceptability. (13.6)</blockquote></blockquote>
			<blockquote>By extension, of course, NBs shall naturally be considering Ecma's responses to these comments too. It is this considered national position that delegations will be taking to Geneva:</blockquote>
			<blockquote><blockquote style="font-size:100%">NBs [&hellip;] shall appoint to the ballot resolution group one or more representatives who are well aware of the NB's position. (13.7)</blockquote></blockquote>
			<blockquote>So, NBs need to do their homework so that delegations arriving at the BRM in Geneva are fully briefed. The delegation should ideally know their national position on all 1,000 or so distinct comment/responses that could be discussed. It is the responsibility of the delegation to faithfully represent their national position (not individual divergent delegate views), and to be prepared to respond to any fresh issues that arise in line with guidance their NB has given them.</blockquote>
			<p>The point of the above isn't to show that I'm right and Rick is wrong, but rather that it doesn't matter &mdash; what matters is what Alex thinks, and also what the Directives say, and not what people may be used to in previous, less contentious settings where having a copy of the Directives at your elbow, and then acting in strict compliance with them (or at least to the best of one's good faith interpretation) is not as important.  And that's why I'm going out of my way to point you to Alex's blog, so that you can keep current with how his planning is progressing for the BRM.</p>
			<p>Here are some other significant items from Alex's latest blog entry:</p>
			<blockquote>Given the five day time limit of the BRM, a frequently asked question is: how can 1,000 issues be addressed in the time, even if NBs already know what their position is? The answer, I think, must lie in paper voting. I am sure that the overwhelming majority of meeting resolutions will be decided by voting (as allowed for by the JTC 1 Directives), and delegations will be given lengthy voting papers allowing them to approve, abstain, or disapprove for any proposed resolution. The voting papers are likely to have three kinds of proposed resolution listed on them:</blockquote>
			<blockquote><blockquote style="font-size:100%">Verbatim responses from Ecma's proposed disposition of comments (as contained in the document published by SC 34 as N 980)<br />Ecma responses that have been amended by the BRM<br />Fresh responses arising from BRM discussion</blockquote></blockquote>
			<blockquote>for the latter two types, consensus might well be reached during in-session discussion, in which case there is obviously no need to put the proposed resolution to the additional test of a redundant vote.</blockquote>
			<p>Anyone who has had to bother with paper voting in a crowd will know that even this will be quite time consuming.  Hence, the definition of what "consensus" means will likely become quite important.  Here's what Alex has to say on that point:</p>
			<blockquote>In ISO (and as adopted by JTC 1), the word "consensus" has a specific meaning:</blockquote>
			<blockquote><blockquote style="font-size:100%">[&hellip;] general agreement, characterised by the absence of sustained opposition to substantial issues by any important part of the concerned interests and by a process that involves seeking to take into account the views of all parties concerned and to reconcile any conflicting arguments. Consensus need not imply unanimity.</blockquote></blockquote>
			<blockquote>Different meeting chairs take different approaches to determining consensus. In general, if the existence of consensus is not beyond doubt on any issue at the BRM, it will be deferred to paper balloting alongside the undiscussed issues.</blockquote>
			<p>So what happens when the clock runs out, especially if not all 1,000 comments have been addressed to the satisfaction of the NB delegates?</p>
			<p>I asked Alex that question in a <a href="http://www.adjb.net/comments.php?y=08&amp;m=01&amp;entry=entry080124-124941">comment</a> to his preceding blog entry, which he answered as follows:</p>
			<blockquote>I'm curious how the decision was made to take one week, without provision for an extension? Clearly, no one wants to spend forever discussing one standard, but other than the practical reality that five days is the space between two weekends, there doesn't seem to be any magic to that amount of time.</blockquote>
			<blockquote><blockquote style="font-size:100%">[Alex] The decision to schedule the BRM strictly as a five-day meeting was taken at a very high level within ISO/IEC. I am informed that such timetabling has happened before.</blockquote></blockquote>
			<blockquote>Certainly, having a deadline will help people focus, but deciding in advance the amount of time that can be spent doesn't seem to serve anyone very well otherwise. It seems that with this much to cover, you're as like as not going to be able to cover everything to everyone's satisfaction.</blockquote>
			<blockquote><blockquote style="font-size:100%">[Alex]  You're right in that some people from both "sides" consider 5 days too little. However, on the other hand some standards veterans think this DIS is taking quite enough time already, thank you very much!</blockquote></blockquote>
			<blockquote>If that's the case, some people are going to be unhappy, no matter which way the final vote comes out &mdash; either proponents will be unhappy, if DIS 29500 fails because some NB's think it's not "done," or opponents (and neutrals) will be unhappy, because they think that the standard is now adopted, even though it's not "done." And the process itself is shown to be inadequate to the challenge as well.</blockquote>
			<blockquote><blockquote style="font-size:100%">[Alex]  Ecma chose to fast track the DIS, knowing perhaps more than anyone about both the spirit and the letter of the Fast Track process. In the end, it's up to the NBs whether the DIS gets passed or not, and a consideration of whether the process is adequate is a perfectly legitimate question they can ask themselves in making their decision, as this <a href="http://www.jtc1sc34.org/repository/0932.htm#q4-5">FAQ item</a> makes clear.</blockquote></blockquote>
			<p>I found Alex's last comment particularly interesting from a strategic point of view.  As I've repeatedly noted in a variety of prior blog entries over the past two years, Microsoft has adopted a high risk strategy by pushing OOXML so aggressively through the Ecma, and then the ISO/IEC JTC1 process.  Already, it's received one set back, in that its failure to gain approval in the first voting period has resulted in much bad press, and a seven month delay (through the expiration of the second consideration period, which will end on March 30).</p>
			<p>If those extra months had been invested in a voluntary extension of the Fast Track period, perhaps more comments could have been resolved to everyone's satisfaction prior to the BRM.  On March 30, we'll find out whether this pedal to the floor strategy succeeds or backfires, because if not enough votes change to the plus column, than any reconsideration of OOXML will take a very long time under JTC1 rules.</p>
			<p>Until then, Alex's blog is the place to stay in touch with What Happens Next.  Hopefully, he will still be in as good cheer at the end of the day on February 29 as he was when he closed his latest blog entry, as follows:</p>
			<blockquote>This will be no love-in: I am expecting some hard work and high-quality technical discussion!</blockquote>
			<p>I'll give odds he's right on the first point.  It will be interesting to see if his hopes are fulfilled on the second.</p>
			<p class="center">Bookmark the Standards Blog at <a href="http://www.consortiuminfo.org/newsblog/">http://www.consortiuminfo.org/newsblog/</a> or set <br />up an RSS feed at <a href="http://www.consortiuminfo.org/rss/">http://www.consortiuminfo.org/rss/</a></p>
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="http://www.consortiuminfo.org/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--   NEW AT CONSORTIUM    -->
			<!-- ******************* -->
			<a name="warofwords" id="warofwords"></a>
			<h4>WAR OF THE WORDS:</h4>
			<h3>Chapter 4:  Eric Kriss, Peter Quinn and the ETRM</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<p><em>This is the fourth chapter in a real-time eBook writing project I launched and <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20071125145159900">explained</a> in late November.   Constructive comments, corrections and suggestions are welcome.  All Microsoft product names used below are registered trademarks of Microsoft.</em></p>
			<p>By the end of December 2005, I had been blogging on ODF developments in Massachusetts for about four months, providing interviews, legal analysis and news as it happened.  In those early days, not many bloggers were covering the ODF story, and email began to come my way from people that I had never met before, from as far away as Australia, and as near as the State House in Boston.  Some began with, "This seems really important &mdash; what can I do to help?"  Others contained important information that someone wanted to share, and that I was happy to receive.</p>
			<p>One such email arrived just before Christmas in 2005.  In its entirety, it read:</p>
			<blockquote>Enjoy reading your consortiuminfo blog &hellip; keep it up.<br />Happy New Year,<br />Eric Kriss</blockquote>
			<p>This was a pleasant and welcome surprise.  Until the end of September, Eric Kriss had been the Massachusetts Secretary of Administration and Finance, and therefore Peter Quinn's boss.  Together, they had conceived, architected and launched the ambitious IT upgrade roadmap that in due course incorporated ODF into the state's procurement guidelines.</p>
			<p>Naturally I responded to Kriss's email, and suggested that perhaps he might consider granting me an interview. The answer was "no."  But over the next several months Eric was nonetheless willing to help me out from time to time when I needed insight into current events as they evolved &mdash; as they began rapidly to do, beginning with the abrupt resignation of Peter Quinn less than a week later.</p>
			<p>Eric usually responded to my questions with single sentence emails or pointers to material already available on line.  His reluctance to share more than might be deemed appropriate after serving in government was as frustrating as it was admirable.  Inevitably, the exchange reminded me of Bob Woodward's erratic interactions with the gnomic source he called "Deep Throat" during the Watergate era.  But early in April I received an email from Eric that included not only several helpful links, but this message as well:</p>
			<blockquote>Also, I've been thinking about your offer of an interview and perhaps the time is right.</blockquote>
			<p>We settled on a time and place, and a few weeks later I was waiting for Eric in the lobby of a business hotel on Route 128, looking out over the offices of technology companies large and small.</p>
			<p>When Eric arrived, my first reaction was to wonder if someone faking his email address had spoofed me.  I had never seen his picture, but knew that he was 57, had helped Mitt Romney in 1983 launch what grew to be a $50 billion private equity fund, and had also served in state government before, serving in Massachusetts Governor Weld's administration from 1991 through early 1993.  That first time around, he had been both the Chief Financial Officer of Massachusetts as well as its Assistant Secretary of Administration and Finance.  In between, he had been CEO of several very successful technology based companies, two of which he had founded.  Others he had been brought in to turn around &mdash; and did.  But the person shaking my hand looked twenty years younger, and was wearing a T shirt, sneakers and jeans &mdash; hardly the stereotypical Bain Capital, Beacon Hill type.</p>
			<p>Had I done my homework more thoroughly, I would not have been surprised, as Eric Kriss is a man of many parts, most of which aren't usually found in the same package.  In addition to the stints in coat and tie, he had written many articles, reviews and anthologies, authored four books on music (three or which focused popular piano styles), produced and performed on a Grammy Award-nominated <a href="http://www.amazon.com/dp/B00064VQQM">album</a>, and recorded a CD of his own music.  Depending on the year, you could find him as either the CEO of a major Victoria's Secret lingerie supplier, or the Managing Editor of <em>Shuttle, Spindle &amp; Dyepot</em>, a glossy quarterly for craft weavers. In other words, not someone who would be likely to feel constrained by the usual boundaries of state government and finance, let alone document formats.</p>
			<p>As we settled in, Kriss told me that he had never expected to reenter public service after leaving the Weld administration in 1993.  But some time after he merged a company he led called <a href="http://www.bizjournals.com/boston/stories/1997/06/09/story7.html">MediQual</a> into a larger company, the phone rang.  It was his old friend Mitt Romney, telling him he was now running for governor.  Kriss agreed to help out, and in March of 2002 became Romney's chief policy advisor, working up stands on topics like education reform, tax policy, and "smart growth."  After Romney was elected governor in November of 2002, Kriss led the transition team.  Perhaps inevitably, in January of 2003 he found himself part of the administration, sitting in the same offices he had expected never to return to a decade earlier.  Only this time he was not Assistant Secretary of Administration and Finance, but Secretary, responsible for $25 billion operating, and $2 billion capital, annual budgets.</p>
			<p>As numbers and a title like that would suggest, the Secretary of Administration and Finance wore many hats.  The former entrepreneur, editor, turn around specialist, musicologist and fund manager was now responsible for overseeing an equally diverse range of functions, including tax collection, collective bargaining, purchasing,  construction and real estate &mdash; and the state's information technology (IT) infrastructure.</p>
			<p>Kriss wasn't trained as an engineer himself, but he did have a strong background in technology-based, fast-growing companies, and most recently had founded a Web development he still operates today.  Consequently, he was comfortable with IT, and with what goes into purchasing, scaling and managing IT.  He also knew how important IT systems were to any enterprise, and particularly to those that dealt with large amounts of information &mdash; like MediQual, which had been a medical data management company.  Governments, with their millions of records containing data on everything from legislation to voter data to entitlement programs, were even more data intensive, and therefore IT dependent.  In his new role, Kriss knew that he would have ultimate responsibility to the governor and the voters for how well those systems functioned in the service of the electorate.</p>
			<p>One of the people he quickly got to know was Peter Quinn.  When he met Quinn, Quinn's title was "Commissioner of the Information Technology Division" (ITD), a vague and uninformative title.  Kriss recalled from his Weld administration days that whenever the then-Commissioner of the ITD was introduced to someone, the inevitable reaction was a blank stare.  The first time Kriss and Quinn entered a meeting, Kriss therefore decided to utilize what he described to me as, "the general ability of executive heads to make up the titles they wish."  As he and Quinn shook hands with their guests, Eric introduced Peter as "the state's CIO."  In fact, the position did not then legally exist (it does now).  But life for both of them was easier from then on, because Quinn's real role in the administration was immediately clear.</p>
			<p>Peter Quinn was also a newcomer to state government, having come aboard during the last months of the previous administration.  Peter's job, regardless of title, was managing the IT structure of the twenty agencies of the Executive Branch of state government.  The CIO title, however, implied greater control than was in fact the case.  In Massachusetts, each of these agencies not only created and managed its own budget, but also had the authority to purchase whatever IT goods and services it wished within its budget, once approved.  As a result, while Peter had responsibility for making sure that over 50,000 state employees could communicate and create and use information, the equipment that supported all of those desktops was an unbelievable hodge-podge of computers, software and other technology that had accumulated over the last twenty years.  Or, as Quinn, liked to say, "If any computer manufacturer that was ever in existence had ever made something &mdash; well, we had one of those.</p>
			<p>All of which was hardly surprising, nor too different from what Kriss had expected.  He knew how purchasing was done in Massachusetts from his previous stint on Beacon Hill, and also done enough consulting to know that most governments spend only about 1% of their budgets on IT systems, as compared to the 5 &mdash; 7% large businesses dedicated to the same purpose.  And yet governments were far more information intensive than the great majority of private sector enterprises of comparable size.  Moreover, governments were mindful of the benefits of stability, and were typically much slower to migrate from existing systems to newer technologies.  Understandable or not, Kriss thought the IT infrastructure in Massachusetts was out of date and ripe for an overhaul.</p>
			<p>Quinn thought so as well.  Like Kriss, he had spent most of his life in private industry, primarily in the financial sector.  Most recently, he had been CIO of a company that managed shareholder records for mutual funds, and was used to better-integrated systems.  Kriss thought Quinn was a "breath of fresh air" compared to what he had expected, and the two hit it off immediately.</p>
			<p>Soon, they were talking about what they could do together to modernize the systems for which they were responsible.  Clearly, the state's IT infrastructure needed upgrading and rationalizing.  With a new governor happy to cultivate a tech-savvy image and to let a trusted lieutenant have his head, why not do the job right?  Instead of simply replacing this computer and that, why not assume a clean slate, and leapfrog from the funky systems they had inherited to the type of infrastructure that an information age government should have?</p>
			<p>As Kriss recounted the tale (and as I struggled to keep up with my note taking), it was clear that even three years later he was excited by the opportunity that he and Quinn had embraced.  What had captured their imaginations was not the mundane task of reconfiguring a vast, out of date patchwork system into something more state of the art, but of designing the type of architectural model upon which such a system could be built &mdash; in Massachusetts or anywhere else.  At the core of such an architecture would be two fundamental building blocks: "open source software," and "open standards."  The rules for using those building blocks would be laid out in a master plan, which would function going forward as a living, periodically updated framework that they would call the Enterprise Technical Resource Model, or "ETRM."  And although neither was an expert in either open source or open standards, they were excited by the prospect that they believed these tools offered to achieve two crucial end states: "interoperability" and "vendor independence."</p>
			<p>Those aims were important for achieving certain central goals that were becoming both popular in IT circles as well as feasible in the marketplace.  One of those goals was to make it easier for one agency to trade information with another.  Such a capability might seem obvious, until the mongrel nature of the state's IT infrastructure was taken into account.  Nor was Massachusetts alone in that regard, as state and national governments around the world were struggling with the same mixed environments of systems that individual vendors like IBM, HP, Sun and others had sold them over the decades, each in an effort to lock in its customers.  Each of these systems was "proprietary" rather than "open," meaning that they were built to unique designs that made it difficult for the systems sold by one vendor to operate with the systems of others.  In fact, even systems within a single agency often couldn't communicate with each other, either, because some equipment had been purchased from one vendor at one point in time to perform a particular function, while other vendors had fulfilled other discrete requirements.  None of these vendors, of course, had any reason to make communication between its wares and those of its competitors simple.</p>
			<p>Open standards promised a way to ameliorate this situation, because if two systems used the right standards, they were each referred to as "open systems," and could communicate with each other &mdash; becoming, in IT-Speak, "interoperable."  In truth, it was rarely, if ever that simple, but using open standards as pervasively as possible could make it far easier for IT managers to enable their systems to "talk" to each other.  And that would save a great deal of time and money.</p>
			<p>Kriss and Quinn believed that using open source software, instead of proprietary software, would also reap large rewards.  In this case, proprietary referred to software that had to be used as it was delivered from the vendor, because the vendor not only withhold the type of computer code ("source code") that would make changing the software comparatively easy, but also made the software available under a license agreement that prohibited the customer from making any changes.</p>
			<p>Having access to source code would have benefits for the state beyond the freedom to make changes to software whenever it wanted to.  To begin with, Massachusetts could continue to maintain that software even if the original developer no longer supported it, or had gone out of business.  In short, the state would have become "vendor independent," because it no longer needed to worry about being abandoned by a vendor, or forced to continue to purchase upgrades it didn't really want.  Moreover, once an enterprise had converted all its systems to open standards and open source software, it would have far more choices in the marketplace, and therefore could drive harder bargains between vendors, because it could fulfill the same need with more alternative products and services from more vendors.</p>
			<p>That concept captured the visionary sides of Kriss and Quinn's personalities.  But if they had spent more time in civil service, they might have been less optimistic about their ability to pursue such an ambitious goal in a political environment.  After all, not only would they need to invade the turf of multiple career civil servants (some of whom worked in departments that did not report to Kriss), but they would need the cooperation of legislators that had little or no acquaintance with technology at all.  Also, it was an open secret that their boss, Mitt Romney, viewed the State House simply as the launch pad for a run at the White House.  His appointees, as a result, weren't likely to be long-term forces to be reckoned with.</p>
			<p>Finally, and most fatefully (as they would learn), while overhauling the State's IT systems would benefit some large and powerful IT vendors, by definition it would also take business away from others.  Those vendors not only had lobbyists, but plenty of money to spend on them.  As Peter Quinn in particular would later learn, rocking the government procurement boat was not something to be undertaken lightly.</p>
			<p>But in 2003, that was a lesson yet to be learned in the future.  For now, Eric Kriss and Peter Quinn could enjoy planning the government enterprise of the future, meeting out of the limelight with their staffs on Beacon Hill in Boston.  When Kriss had accepted Mitt Romney's invitation to join the new governor's administration, he had promised himself that his stay in government would be short &mdash; just one year.  But before he knew it, one year had turned into three as the ETRM slowly took shape.</p>
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="http://www.consortiuminfo.org/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--    CONSIDER THIS    -->
			<!-- ******************* -->
			<a name="considerthis" id="considerthis"></a>
			<h4>CONSIDER THIS:</h4>
			<h6>March 7, 2008</h6>
			<h3><span class="red">#53</span> Steve Jobs' Endangered Second Act</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<p>In his later years, the American Jazz Age author F. Scott Fitzgerald ruefully observed that "There are no second acts in American Lives." That now-famous verdict was based upon the personal experience of the once celebrated author, by then a self-described "Hollywood Hack," reduced to writing B movie scripts for much-needed current income.</p>
			<p>If there is a current exception to Fitzgerald's axiom in the world of technology, it must certainly be Steve Jobs.  The company he founded in a garage with partner Steve Wozniak quickly seized the lead in the PC revolution, reaching $100 million in revenues by 1980.  Later the same year, Apple launched the largest IPO since Ford Motor Company went public.  But the introduction of the IBM PC and the rise of Microsoft wrought a reversal in Apple's fortunes, and in May of 1985, the man he had recruited to be his mentor ousted Jobs from his own company.</p>
			<p>The rest, of course, is the stuff of which legends are made.  Jobs attempted to vindicate his vision in 1985 by founding a new company that he unsubtly dubbed NeXT Computer.  But NeXT never found its market: by 1993, it had sold only c. 50,000 machines.  Then, at last, Jobs' fortunes began to improve.</p>
			<p>In 1996, NeXT was acquired by Apple, which had itself been largely wandering in the wilderness during the intervening years.  By acquiring NexT, Apple not only obtained the rights to a new operating system, but it reacquired Jobs as well.  Moreover, not long after leaving Apple, Jobs had bought an animation studio from LucasFilms for $5 million, plus a $5 million cash infusion into the studio itself.  He later renamed that studio Pixar, and it went on to become wildly successful, making Jobs a very wealthy man twice over.</p>
			<p>With the fantastic success of the iPod and iTunes, the successful launch of the tectonically innovative iPhone and the rejuvenation of Mac sales, Jobs now seems poised on the cusp of proving Fitzgerald wrong to the point of stomping on the author's grave.  But will he in fact pull it off, leading Apple to dominate the mobile platform of the future after surrendering the emerging PC platform of the past to his rivals?</p>
			<p>Given Jobs' announcements of yesterday, I'm afraid that history may be about to repeat itself instead.  Here's why (or, to employ my usual phrase, "Consider this&hellip;").</p>
			<p>Yesterday, Jobs made a number of impressive iPhone related <a href="http://www.apple.com/pr/library/2008/03/06iphone.html">announcements</a>, most significantly (for business users) disclosing that Apple had entered into an agreement with Microsoft whereby the iPhone will support Microsoft Exchange.  Jobs contends that the result, along with further details, will allow Apple to more directly challenge Research in Motion's (RIM) dominant BlackBerry mobile device.  If so, this would permit Apple to have the same impact on its competitors in the business space that it is already having in the consumer world, and perhaps more so, since the penetration of mobile devices in the business world is still much smaller than the spread mobile phones among consumers.</p>
			<p>Jobs also revealed news of major appeal to consumers as well, announcing a new release of the iPhone operating system, and here is where I fear he may be making a fatal misstep.  But first, the good news:  Apple will embrace the innovation of independent software vendors (ISVs), providing them the technical information to create iPhone-based apps, and also a ready distribution channel as well.  From the press release:</p>
			<p>The iPhone 2.0 software release will contain the App Store, a new application that lets users browse, search, purchase and wirelessly download third party applications directly onto their iPhone or iPod touch. The App Store enables developers to reach every iPhone and iPod touch user....Users can download free applications at no charge to either the user or developer, or purchase priced applications with just one click. Enterprise customers will be able to create a secure, private page on the App Store accessible only by their employees. Apple will cover all credit card, web hosting, infrastructure and DRM costs associated with offering applications on the App Store....</p>
			<p>The iPhone SDK provides a reliable, fast and secure way to create innovative applications for the iPhone and iPod touch. In addition to the rich set of iPhone OS APIs, the iPhone SDK also provides advanced tools for creating native iPhone and iPod touch applications including: Xcode&reg; for source code editing, project management and graphical debugging; Interface Builder with drag and drop interface creation and live preview; Instruments to monitor and optimize iPhone application performance in real time; and the iPhone Simulator to run and debug applications.</p>
			<p>All of which sounds beyond wonderful, not only for Apple, but for ISVs and Apple's enthusiastic customers as well.  But now the bad news:  the devil is in the ellipses.  Here's a part of the language that I did not include in the extract above:</p>
			<p>Developers set the price for their applications &mdash; including free &mdash; and retain 70 percent of all sales revenues&hellip;.Third party iPhone and iPod touch applications must be approved by Apple and will be available exclusively through the App Store.</p>
			<p>And now you can begin to see why I think that rather than standing on the verge of an unprecedentedly successful second act, Jobs may be about to stage a replay of the same mistakes of three decades ago.  Will developers wish to tie themselves to the whims of Steve Jobs, the same way they did 25 years ago to Bill Gates &mdash; and pay a toll for the privilege of doing so to boot?  Or will they spend their time working to support more open platforms, such as Android, where there will be less control, no toll booth, and multiple channels of distribution?  Haven't they all been there before?</p>
			<p>Unfortunately, it appears that Steve Jobs learned the wrong lessons the first time around, and is fighting the last war rather than the next one.  Apple failed in the early 1980s in large part because the IBM PC platform provided what at the time was a remarkably open platform for ISVs, as well as an ever-growing potential customer market as more and more personal computer buyers flocked to the "WinTel" platform instead of Tandy, Commodore &mdash; or Apple.</p>
			<p>Soon, this "virtuous cycle" of more platforms attracting more applications attracting more customers (and back around again) became a juggernaut that no computer manufacturer could challenge with a proprietary alternative.  Instead, the name of the game became to simply play the game better.  While Apple's fortunes fell, Compaq and Dell became ascendant, soon eclipsing Apple in both business and consumer sales.  Eventually, Apple flirted with allowing its products to be cloned, it was too little and too late, and Jobs reversed the experiment in any event upon his return.</p>
			<p>I find yesterday's announcements particularly unfortunate, because Jobs really does have a chance for a "do-over" here,  but only if he understands the opportunity.  Just as the PC revolution allowed new venturers to unseat IBM, we are on the dawn of another unparalleled shift.  I recently described that opportunity in a piece I called <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20080214181714496">Going Mobile: the Year of the Smartphone Startup</a>. In that piece, I observed:</p>
			<p>2008 will usher in a multiyear period of opportunity for entrepreneurs and investors. The dynamics will echo two boom periods of the past &mdash; the rapid expansion of the PC marketplace in the early 1980s, and the Internet explosion of the late 1990s. The device that will most robustly deliver on these antecedents is the smart phone, initially deployed (like the first personal computers) with many competing operating systems, and now able (like the PCs of the Internet boom) to satisfactorily access the Internet and the web.</p>
			<p>In many ways, however, this boom will be better. Unlike the early, anemic, expensive PCs that people had never used before, a smart phone is simply a much more versatile telephone &mdash; something a billion people already own. With a decade of Internet and web experience behind us, there will be far fewer failed efforts to determine what people really will and won't do online. And these mobile devices will be able to perform new tricks, using as many as nine separate on-board radios to interact with an ever-expanding "Internet of things," such as ATMs, film kiosks, movie posters and much more.</p>
			<p>But there is one extremely important difference this time around: now we live in an open IT world.  If Jobs fights yesterday's war the way that Bill Gates did &mdash; by trying to create an ecosystem with Apple firmly entrenched at its center &mdash; ISVs will simply go elsewhere.  Crucially, there are only so many iPhones in use today.  The prize is simply not yet large enough to offset the costs to ISV independence to lure the best of them in and keep them there exclusively.</p>
			<p>Already, various flavors of Linux are destined to power the majority of mobile devices, and the Google Android project aims to provide developers with greater independence as well. Not long ago, even the dominant telecommunications carriers grudgingly came to realize that they are better served (assuming they still have a choice) by opening their phones to independent software vendors than by shutting them out.</p>
			<p>If Steve Jobs is to truly prove F. Scott Fitzgerald wrong, he needs to realize that the game &mdash; and the rules &mdash; have changed.  Will that happen?  Unfortunately, I'm not optimistic.  Jobs seems constitutionally rooted in proprietary strategy, and to date has only been capable of incrementally opening the door a crack at a time in the same way as Microsoft &mdash; and for Apple's benefit alone.</p>
			<p>As I have opined before, this seems to me to be a tragic flaw in Jobs' leadership.  Certainly Apple is the unparalleled leader in innovation and design for the consumer market among the majors.  Were Jobs to truly open the Apple platform, it seems likely to me that Apple could enjoy a substantial and sustaining lead in an explosively growing market space.  How much better to be king of a much larger and more profitable hill as the acknowledged master of the game, rather than a latter day, unsuccessful adopter of the Bill Gates play book?  Unless Steve can get through the openness knothole, I fear that his chance at a truly successful second act will be squandered.</p>
			<p>The choice, of course, is his.  We need not worry too much on his account, though, as the remaining years of his career are certain to end more happily than F. Scott Fitzgerald's.</p>
			<p>After all, Jobs owns a studio.</p>
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p class="center">Read more <strong><em>Consider This&hellip;</em></strong> entries at: <a href="http://www.consortiuminfo.org/blog/">http://www.consortiuminfo.org/blog/</a></p>
			<p>Sign up for a <strong><em><a href="http://www.consortiuminfo.org/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
		</div>
	</div>
<div class="clear"><br /></div>
<!-- *********** -->
<!--   FOOTER    -->
<!-- *********** -->
<?php include '../includes/footer.php'; ?>
</form>
</body>
</html>