<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Consortiuminfo.org Consortium Standards Journal &mdash; October &ndash; November 2008</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta name="description" content="While standard setting has been an important aspect of industrial society for over a hundred years, the formation of unofficial, fast-acting standard setting and promotional consortia is a more recent phenomenon which is only now beginning to be seriously studied" />
<meta name="keywords" content="standard setting, promotional consortia, structuring of consortia, standardize, intellectual property policies, procedures, founding company, model, best practices, promoter/adopter structurer, joint venture, IPR, " />
<meta name="author" content="Andrew Updegrove" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/screen.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/journal.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/toolsets.css" />
<!-- ALTERNATE -->
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/default.css" title="default" />
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/large.css" title="large" />
<!-- ********* -->
<link rel="home" title="home" href="http://www.consortiuminfo.org" />
<script type="text/javascript">AC_FL_RunContent = 0;</script>
<script type="text/javascript" src="/scripts/AC_RunActiveContent.js"></script>
<script type="text/javascript" src="/scripts/styleswitcher.js"></script>
<script type="text/javascript" src="/scripts/obfuscate.js"></script>
</head>

<body id="bulletin">
	<!-- ****************** -->
	<!--   ACCESSIBILITY    -->
	<!-- ****************** -->
	<?php include '../includes/accessibility.php'; ?>
	
	<!--   SEARCH FORM   -->
	<form class="search" name="form1" method="get" action="http://search.Blossom.com/query/320">
	
	<!-- ************* -->
	<!--   MASTHEAD    -->
	<!-- ************* -->
	<?php include 'includes/masthead_journal.php'; ?>
	
	<!-- *********** -->
	<!--   BANNER    -->
	<!-- *********** -->
	<div id="banner">
		<div class="left">
			<p><a href="/">Home</a> &gt; <a href="/bulletins/">Standards Today</a> &gt; October &ndash; November 2008</p>
		</div>
		<div class="right">
			<p><input type="text" name="key" /><input type="submit" name="Submit" value="Search" /> <a href="/search/">Advanced</a></p>
		</div>
		<div class="clear"></div>
	</div>
						
	<!-- ************** -->
	<!--   MAIN BODY    -->
	<!-- ************** -->
	<div class="JournalContent">
	<!-- SKIP/START CONTENT LINK -->
	<a name="startcontent" id="startcontent"></a>
		
		<!-- SIDEBAR CONTENT AREA -->
		<div class="AllSidebar">
			<div>
				<?php include '../includes/clients.php'; ?>			
			</div>
			<div class="AllNav">
				<p class="AllNavLink">&raquo;&nbsp;<strong><a href="/bulletins/archive.php" style="border-top:0px;">Journal Archive</a></strong></p>
			</div>
			<div class="AllNav">
				<p class="AllNavLink">&raquo;&nbsp;<a href="/bulletins/pdf/oct08/oct08.pdf">Download PDF</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="mailto:?subject=Standards%20Today&amp;body=http://www.consortiuminfo.org/bulletins/oct08.php">Email this issue</a></p>
			</div>
			<?php include '../includes/toolsets.php'; ?>
		</div>
		
		<!-- BODY CONTENT AREA -->
		<div class="JournalMain">
			<h1>Standards Today</h1>
		
			<!-- ************* -->
			<!--     INDEX     -->
			<!-- ************* -->
			<div id="tableofcontents">
			<h2>October &ndash; November 2008<br /><span class="volumeinfo">Vol VII No 4</span></h2>
			<h3>A Standards Agenda For The Obama Administration</h3>
			<!-- INDEX ITEM -->
			<p><span class="section">EDITOR'S NOTE:</span><br /><span class="title"><a href="#editorsnote" title="Editors Note" accesskey="1">All for the Want of a (Standardized) Horseshoe Nail</a></span></p>
			<p>With all of the challenges that await it, the Obama administration will need all of the help &mdash; and standards &mdash; it can get. <br /><a class="pdf" href="/bulletins/pdf/oct08/oct08_editorsnote.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">EDITORIAL:</span><br /><span class="title"><a href="#editorial" title="Editorial" accesskey="2">Technology, Innovation and the Challenge of the Missing Standards</a></span></p>
			<p>Barack Obama has articulated a sophisticated and powerful technology-based agenda. But much of that agenda will require standards that either do not yet exist, or have not yet been implemented. The new administration will have to act quickly to fill the gap, and will need new strategies to make its standards ends meet.<br /><a class="pdf" href="/bulletins/pdf/oct08/oct08_editorial.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">POLICY:</span><br /><span class="title"><a href="#policy" title="Policy" accesskey="3">10 Standards Recommendations for the Obama Administration</a></span></p>
			<p>Here are ten standards-based recommendations that can help Barack Obama keep the technology-based promises of his campaign.<br /><a class="pdf" href="/bulletins/pdf/oct08/oct08_policy.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">FEATURE ARTICLE:</span><br /><span class="title"><a href="#feature" title="Feature Article" accesskey="4">Behind the Curve: Addressing the Policy Dependencies of a "Bottom Up" Standards Infrastructure</a></span></p>
			<p>In contrast to many other nations, the United States employs a "bottom up" standards development process that is driven by industry rather than government. That system permits new products and services to be swiftly introduced into a competitive marketplace, but leaves government with little ability to address its own technology needs, or to advance standards-related policy goals. In this article, I trace the origins of the current system, highlight its shortcomings, and suggest ways that government can achieve its goals without reshaping a process that is otherwise working well.<br /><a class="pdf" href="/bulletins/pdf/oct08/oct08_feature.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">STANDARDS BLOG:</span><br /><span class="title"><a href="#blog" title="Standards Blog" accesskey="5">The Lion in Winter &mdash; or is it Spring? Ted Kennedy Addresses the Democratic Convention</a></span></p>
			<p>The surprise appearance at the Democratic convention of the legendary senator from Massachusetts supplied more than an emotional moment for the faithful. It also allowed a living witness to the idealism of the past to inspire those in the present to envision a future where great deeds could be done again.<br /><a class="pdf" href="/bulletins/pdf/oct08/oct08_blog.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">CONSIDER THIS:</span><br /><span class="title"><a href="#considerthis" title="Consider This" accesskey="6">All Politics are Tribal: the Myth of "One Citizen, One Vote"</a></span></p>
			<p>If the concept of "one citizen, one vote" is such an irrefutable, inalienable standard of human rights, why do we fight so hard against it?<br /><a class="pdf" href="/bulletins/pdf/oct08/oct08_considerthis.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">MONDAY WITNESS:</span><br /><span class="title"><a href="#mondaywitness" title="Monday Witness" accesskey="7">John McCain's Elephant Man Moment</a></span></p>
			<p>It's easy to get carried away in the heat of the moment of a closely contested campaign, whether you're the candidate or only one of the crowd. Now that the dust of the election has settled, it's time for us all to take a good look in the mirror and see if we like what we see.<br /><a class="pdf" href="/bulletins/pdf/oct08/oct08_mondaywitness.pdf">Download PDF</a></p>
			<!-- INDEX ITEM -->
			<p><span class="section">WHAT'S NEW AT CONSORTIUMINFO.ORG</span><br /><span class="title"><a href="#whatsnew" title="What's New" accesskey="8">The New Look of the News</a></span></p>
			<p>The <a href="/news/">Standards News Portal</a> was launched in February of 2002. It's been updated on a daily basis ever since to bring you the most important news about standards, how they are created, and how they affect your business and your life. Now the Standards News Portal has a new clean look and additional tools to help you keep current on today's news and also access the more than 4,800 categorized articles that comprise what may be the most extensive archive of its kind.<br /><a class="pdf" href="/bulletins/pdf/oct08/oct08_whatsnew.pdf">Download PDF</a></p>
			<p class="center"><a class="pdf" href="/bulletins/pdf/oct08/oct08.pdf">Download PDF of this issue</a></p>
			<div class="hr"></div><hr />
			</div>
		
			<!-- ************* -->
			<!-- EDITOR'S NOTE -->
			<!-- ************* -->
			<a name="editorsnote" id="editorsnote"></a>
			<h4>EDITOR'S NOTE:</h4>
			<h3>All for the Want of a (Standardized) Horseshoe Nail</h3>
			<p>It's unlikely that anyone would truly relish confronting the matters that await Barack Obama on inauguration day.  From wars to economic collapse, there will be much to occupy the attention of the new administration, each challenge seemingly more intractable and urgent than the next. But lurking somewhere down there in the weeds of policy implementation lies the unsettling question of whether the standards needed to implement the new administration's grand goals will be waiting for him. Unfortunately, in many cases, the answer will be "no." What's a new president to do?</p>
			<p>That's what this issue is all about. So if you happen to be visiting with the president-elect, be sure to lend him your copy.</p>
			<p>In the <strong><em>Editorial</em></strong>, I lay out the problem, highlight what needs to be done at a high level, and make the case for rapid action. In the <strong><em>Policy</em></strong> piece that follows, I make ten specific recommendations for actions that can be rapidly and inexpensively taken in order to avoid the new administration being held back for want of the standards-based solutions upon which some of its important policy goals must rely.</p>
			<p>I provide a more detailed description of the underlying problem in this month's <strong><em>Feature Article</em></strong>, in which I review the implications of the "Bottom Up" standards development system that the United States has evolved in tune with its traditionally hands-off approach to the marketplace. In doing so, I demonstrate how such an approach leaves the United States less able to act quickly to accomplish technology-related policy goals, and how it may be at a competitive disadvantage internationally as a result.</p>
			<p>Next, I include three essays with a seasonally political theme. In my <strong><em>Standards Blog</em></strong> selection, I focus on Ted Kennedy's surprise appearance at this year's Democratic convention, and the hopes for the future that it inspired. The Kennedy piece is followed by this month's <strong><em>Consider This</em></strong> essay, in which I reflect on how curiously difficult democracies find it to really believe in the concept of "one citizen, one vote." And finally, in this installment of the <strong><em>Monday Witness</em></strong>, I recall an incident that occurred during the presidential campaign just ended to examine how standards of ethics and conduct can suffer during the heat of a hard-fought campaign.</p>
			<p>I close this issue with a pointer to the recently revamped ConsortiumInfo.org <strong><em>Standards News Portal</em></strong>, highlighting its new features and cleaner, easy to use look and fee. If you're not already a regular visitor to that part of the site, perhaps you'll become one soon.</p>
			<p>Hopefully, all of the above will provide much food for standards-related thought as the days countdown to the inauguration of Barack Obama. As always, I hope you enjoy this issue.</p>
			<!-- ************* -->
			<div class="credit">
				<p>Andrew Updegrove<br />Editor and Publisher<br />2005 ANSI President's<br />Award for Journalism</p>
				<div class="clear"></div>
			</div>
			<p class="note">The complete series of Consortium Standards Bulletins can be accessed on-line at <a href="/bulletins/">http://www.consortiuminfo.org/bulletins/</a>. It can also be found in libraries around the world as part of the EBSCO Publishing bibliographic and research databases.</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p> 
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ************* -->
			<!--   EDITORIAL   -->
			<!-- ************* -->
			<a name="editorial" id="editorial"></a>
			<h4>EDITORIAL:</h4>
			<h3>Technology, Innovation and the Challenge of the Missing Standards</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<p>Barack Obama promises to be the most technologically attuned U.S. president ever. More than a year ago, he released a policy statement on technology and innovation that detailed his plans to employ state of the art technology to pursue a broad spectrum of goals, such as increasing national competitiveness, providing next-generation broadband access for all, creating a "transparent and connected democracy," decreasing health care costs, acting to prevent global warming, and lowering American dependence on foreign oil. In pursuit of these goals, he also promised to appoint the nation's first Chief Technology Officer.</p>
			<div class="calloutright">
				<p>The current standards development infrastructure was never designed to create the suites of closely integrated standards that will be needed to solve the types of complex problems embedded in the Obama technology and innovation agenda</p>
			</div>
			<p>These are worthy and important goals. Like the other commendable promises the president-elect has made, they will be difficult to realize, for reasons both obvious and subtle. The obvious challenges include a crowded and ambitious agenda, the difficulties of achieving political consensus, and above all, the overarching urgency of addressing a global economic meltdown that demands attention above all else.</p>
			<p>But there are subtle hurdles that are equally daunting, if less visible. They include the need to develop a multitude of new information and communications technology (ICT) standards in record time, utilizing a standards creation process that is at best loosely coordinated, frequently contentious, and almost completely independent of government influence or control. Moreover, the current standards development infrastructure was never designed to create the suites of closely integrated standards that will be needed to solve the types of complex problems embedded in the Obama technology and innovation agenda. But while the challenge of creating standards-based solutions may be uninteresting from a policy perspective, an inability to perform in this pursuit may present as serious an impediment to success as any failure to secure requisite funding or garner sufficient Congressional support.</p>
			<p>Consider just the following examples from the Obama technology and innovation platform:</p>
			<ol>
				<li><strong><em>Lower Health Care Costs by Investing in Electronic Information Technology Systems:</em></strong> The administration proposes to invest $10 billion a year for five years in order to "move the U.S. health care system to broad adoption of standards-based electronic health information systems, including electronic health records." Success in this endeavor could save up to $77 billion in annual health care costs, according to a Rand Corporation study.<br /><br /></li>
				<li><strong><em>Invest in Climate-Friendly Energy Development and Deployment:</em></strong> The administration proposes to spend $150 billion over ten years to "enable American engineers, scientists and entrepreneurs to advance the next generation of biofuels and fuel infrastructure, accelerate the commercialization of plug-in hybrids, promote development of commercial-scale renewable energy, and begin the transition to a new digital electricity grid."<br /><br /></li>
				<li><strong><em>Create a Transparent and Connected Democracy:</em></strong> The president-elect hopes to use, "cutting edge technologies to&hellip;create a new level of transparency, accountability and participation for America's citizens," and also to make not current, but next-generation broadband Internet access available to all.</li>
			</ol>
			<p>What these goals (and many other others) have in common is a dependency on a bewildering array of yet to be developed standards in diverse technologies that will be needed to enable the solutions themselves, or to measure and/or regulate their results. Moreover, each goal comprehends a variety of complex technical (and often scientific) domains, as well as diverse business dynamics. To give but a single example, providing next generation broadband access to all will not only require creating the standards that make such access feasible, but also persuading multiple layers of commercial interests to implement and deploy them, in some cases thereby thwarting the business strategies of global corporations that have already invested billions in competing solutions.</p>
			<p>Compounding the problem is the reality that In virtually no instance is there a single standard setting organization (SSO) with the demonstrated competence to provide all of the standards needed to meet the requirements of the goal in question. By way of example, converting to a national system of electronic health records will require standards-based forms, data formats and schema, privacy and security protocols, and much more. As a result, suites of existing and yet to be developed standards will need to be assembled into profiles to address the use cases identified in each instance before the actual work of deploying the technology needed to achieve the goal in question can even commence.</p>
			<p>Happily, a public-private initiative called the Health Information Technology Standards Panel (HITSP) was formed in 2005 to begin work on this challenge, providing not just a head start on this aspect of the administration's innovation plan, but also a model of the type of creative solution that will be needed to address other standards-dependent goals as well.</p>
			<p>But these other dependencies still need to be identified, and their solutions defined and deployed. The administration is therefore faced with the uncomfortable choice of cobbling together imperfect and partial solutions using the tools at hand, or marking time until the standards are developed to fill the gaps and detailed profiles are designed to provide robust solutions. In each case, this will require a methodical process of achieving both technical as well as business consensus. If the administration takes the easy route based on existing tools, it will guarantee inefficient use of public funds and under delivery of results. But if it pursues the best technical solution in too slow a fashion, it will risk saddling the new administration with a reputation for promising more technology-based progress than it can deliver.</p>
			<p>The situation is exacerbated by America's traditional preference for a "bottom up" standards development infrastructure that is driven largely by industry initiative rather than government priorities. In contrast, the European Union has a decades long history of centralized, standards based planning, a variety of regional standards bodies purpose-built to address government priorities, and a record of success in utilizing standards to further both social and trade policies.</p>
			<p>In the absence of such an existing alignment of government and standards development, the Obama administration will need to break new ground if it wishes to achieve its goals in an effective fashion. And it will have to act quickly, from the ground up. The key tasks will be as follows:</p>
			<ol>
				<li class="numbers">For each policy goal, assess the interoperability and other standards-related requirements needed to achieve that goal.<br /><br /></li>
				<li class="numbers">Perform a "gap analysis" to determine which standards are available, and which must be developed, taking into account any special criteria (e.g., security, accessibility for those with physical handicaps, etc.) that may apply in a government setting, as well as the competitive forces that may complicate adoption and broad implementation.<br /><br /></li>
				<li class="numbers">Where a standard does not exist, develop a strategy for its rapid development within an existing standard setting organization (SSO) or, as necessary, in a new one created for that purpose.<br /><br /></li>
				<li class="numbers">Where complex suites of integrated standards will be required to provide a solution, create a new public/private initiative, such as HITSP, to provide that solution.<br /><br /></li>
				<li class="numbers">Adopt and deploy a new standards policy across all Federal agencies to ensure the consistent and efficient deployment of the new standards-based solutions.</li>
			</ol>
			<p>This is no small work order, especially if a consistent methodology is to be applied (as it should) across all agencies, in order to ensure maximum efficiency and achievement of policy goals.</p>
			<p>But compared to the other challenges that face the Obama administration, this task is pedestrian, requiring only prompt recognition of the need, and care in designing and executing the program that needs to follow. In the article that follows, <a href="#policy">10 Standards Recommendations for the Obama Administration</a>, I offer a series of proposals that would enable the new administration to hit the ground running.</p>
			<p>While this list may appear long, the good news is that these recommendations can not only be easily acted upon utilizing existing legislative authority, but little cost would be involved. Not one recommendation involves a major new initiative. Taken together, they would have the added benefit of reinvigorating domestic standards development, thereby supporting renewed innovation, and helping close the competitive gap between the United States and the more standards-aware governments of (for example) Europe.</p>
			<p>More to the point, the new administration will have little choice but to address the standards-related dependencies of its aggressive and commendable policies. Whether it does so by following the recommendations laid out below, or by pursuing some other course of action, it will need to move swiftly. Otherwise, for the want of so simple a tool as a standards strategy, the achievement of its ambitious and high-minded policy goals may ultimately lie just beyond its grasp.</p>
			<!-- ************* -->
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ************* -->
			<!-- POLICY -->
			<!-- ************* -->
			<a name="policy" id="policy"></a>
			<h4>POLICY:</h4>
			<h3>10 Standards Recommendations for the Obama Administration</h3>
			<p>The goals of the Obama administration are in tune with &mdash; but in some technical respects, ahead of &mdash; the technological times. As discussed in the <a href="#editorial">Editorial</a> to this issue, unless certain standards-related dependencies are promptly addressed, the timely achievement of the president-elect's innovation and technology policy will be jeopardized. But, as examined in the <a href="#feature">Feature Article</a> of this issue, the government does not have the historical competency to address these dependencies. What, then, is the new administration to do?</p>
			<p>The following is an integrated suite of recommendations that could be implemented quickly and inexpensively, and without Congressional action. Of the ten proposals, the first is most urgent, as the advisors assembled in this step would provide the experience, guidance and active assistance needed to implement the recommendations that follow.</p>
			<p><strong><em>1. Create a Standards Advisory Council (SAC):</em></strong> Due to the breadth of standards related issues underlying the administration's goals and the relative lack of existing government engagement in the standards arena, the new administration should recruit a council of neutral standards experts versed not only in technical and scientific matters, but also in the legal, trade policy and social impacts and opportunities that a sophisticated standards strategy can provide. Such a council should comprise existing experts drawn both from within government where available (e.g., from Defense, NIST, and Homeland Security), as well as from academia, law and other relevant disciplines. The SAC would advise and be chaired by the newly appointed administration CTO. It would also serve as an available resource for the Federal CIO Council (made up of the CTOs of the Federal agencies) and for Congressional committees.</p>
			<p><strong><em>2. Make maximum use of NIST:</em></strong> At present the government has islands of standards expertise in various agencies. Only one agency, however, includes standards as an area of primary focus and responsibility. That agency is the National Institute of Standards and Technology (NIST), operating under the authority of the Department of Commerce. Like many agencies, NIST has seen its influence (and budgets) rise and fall with the change of administrations. Now is the time to capitalize on its expertise and existing infrastructure to educate administration members, to provide a coordinating function both among agencies and with industry, and to act as the mechanism to jumpstart new standards activities.</p>
			<p><strong><em>3. Make greater use of ANSI:</em></strong> The American National Standards Institute is the internationally acknowledged representative of the U.S. in a variety of international standards activities, but its involvement with Congressional staff and domestic government agencies has historically been relatively light, due to the limited role that government has taken in standards-related affairs. Especially in the near term, ANSI could provide a coordinating function with accredited domestic and global SSOs to accelerate the delivery and adoption of standards in targeted areas. ANSI currently administers a variety of "panel" activities in specific domains where the breadth of standards activities &mdash; as well as the number of SSOs and stakeholders involved &mdash; is great, or where a new technology with broad industry appeal is emerging. One such panel, the Health Information Technology Standards Panel, is already addressing eHealth standards, under contract with the Department of Health and Human Services. Other current ANSI panels are addressing areas such as Homeland Security, and ID Theft and Prevention and ID Management. ANSI could provide a valuable role in managing additional standards panels supporting other key areas of administration focus.</p>
			<p><strong><em>4. Reenergize implementation of the E-Government Act of 2002:</em></strong> As with electronic health standards, there is an existing statutory and administrative foundation upon which some of the Obama administration's goals to enable a transparent and connected democracy can be based. The existing structure created under the e-Gov Act should be rapidly evaluated and retooled aggressively to not only implement administration goals, but to assess, and as necessary, incentivize the creation of the standards needed to achieve goals of transparency and citizen connectivity.</p>
			<p><strong><em>5. Recognize the existence of "Civil ICT Standards:"</em></strong> Today, freedom of speech, freedom of association and freedom to interact with government are each increasingly being exercised on line rather than in person, converting our hard-won traditional civil rights into virtual "civil ICT rights." Only by deploying appropriate technical standards can governments ensure that any citizen, using any technology and software, and regardless of physical disabilities, can continue to enjoy these freedoms. Such "civil ICT standards" are the equivalent of a bill of ICT rights, and should therefore be developed in open, transparent processes that guarantee vendor neutrality, minimum cost to implement, and maximum utility. Adoption of such standards at all government Web sites will be essential for the success of the administration's goal to provide transparent government.</p>
			<p><strong><em>6. Create a More Policy-Aware Agency Interoperability Framework:</em></strong> The enormous economic power of government procurement can have huge impact on the standards that industry adopts. Without recourse to regulation, adopting a government-wide interoperability framework that (for example) exclusively implements Civil ICT Standards for document format and platform neutrality, as well as accessibility for those with physical disabilities, would provide great incentives to industry to raise the bar in socially-aware standards development generally, as well as ensure the broad adoption of specific Civil ICT Standards outside of the government marketplace.</p>
			<p><strong><em>7. Support the Formation of a "Standards for Standards" Body:</em></strong> ISO and IEC, the current global standards bodies involved in the creation of IT standards, do not consider part of their role to be to guarantee the openness of the standards development process, the quality of the technical standards adopted, or the vendor and platform neutrality of their work product. Instead, these bodies provide the venue within which standards are developed or voted upon by National Body representatives, which individually determine their rules of operation. As a result, there is no trusted source to rely upon to evaluate standards, or the SSOs that create them, for purposes of government procurement. A "Standards for Standards" organization could be easily and quickly launched, with a governance structure that guarantees that all stakeholders are fairly represented, that appropriate criteria are created, and that trustworthy results are made available. The existence of such a neutral "rating agency" would provide a competitive incentive among all SSOs to increase transparency, improve process values, and decrease vendor influence.</p>
			<p><strong><em>8. Revise OMB Circular A-119:</em></strong> There is already a framework in place that is intended to guide government standards-related procurement, known as OMB Circular A-119. However, in the years since its adoption the role of ITC standards development has increasingly been taken over by industry consortia instead of traditional, accredited SSOs. A-119 should be updated to expressly give equal status to consortium-developed standards, as well as to enforce and coordinate with the standards goals noted above (for example, to require implementation of Civil ICT Standards where applicable, and to restrict procurement to standards, where available, that have otherwise been certified by the Standards for Standards body referred to above).</p>
			<p><strong><em>9. Direct the DOJ to Support the Development of Open Standards:</em></strong> The regulatory agencies can do much to encourage &mdash; or inhibit &mdash; the development of standards. By providing further written guidance in areas such as the <em>ex ante</em> disclosure of patent licensing terms and by prosecuting those that "game" the standards development process, the Department of Justice can facilitate the more rapid development and adoption of much-needed standards with less fear of later "patent hold up" situations.</p>
			<p><strong><em>10. Aggressively Promote Patent Reform:</em></strong> The administration's platform already incorporates the goal of patent reform, but it should be recognized that for a variety of reasons the proliferation of poor-quality patents is of special concern in standards development. First is the fact that a standard, once widely adopted, "locks in" the marketplace, because it becomes extremely expensive to switch to an alternative approach. Second, in areas (such as the Web, the Internet and areas in which open source software predominate), the imposition of royalties or restrictive licensing terms can be extremely problematic. With the proliferation of patents and the increasing density of patent "thickets" in core areas of technology, creating high quality standards that are free of such encumbrances is becoming increasingly difficult.</p>
			<p>For additional background and detail on these recommendations, see the article that follows, titled <a href="#feature">Behind the Curve: Addressing the Policy Dependencies of a "Bottom Up" Standards Infrastructure</a>.</p>
			<!-- ************* -->
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--   FEATURE ARTICLE   -->
			<!-- ******************* -->
			<a name="feature" id="feature"></a>
			<h4>FEATURE ARTICLE:</h4>
			<?php include '../bulletins/oct08/oct08_featureinc.php'; ?>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--   STANDARDS BLOG    -->
			<!-- ******************* -->
			<a name="blog" id="blog"></a>
			<h4>STANDARDS BLOG:</h4>
			<h3>The Lion in Winter &mdash; or is it Spring?<br />Ted Kennedy Addresses the Democratic Convention</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<h6>Date: August 25, 2008<br /><span class="views">Views: 1,277</span></h6>
			<img class="imgleft" src="oct08/oct08_img1.jpg" alt="" width="281" height="168" border="0" />
			<p>For those of us who are of a certain age, the 1960s were an era not to have been missed.  Indeed, they were a time when idealism seemed to be a responsibility of citizenship, rather than an idle pursuit.  As John Kennedy, Robert Kennedy and Martin Luther King spoke out in words that captured the heart as well as the mind, more and more fell in behind. Their goals and ideals demanded to be your goals and ideals, and all of the lofty aims they espoused seemed to be as achievable as they were morally imperative.</p>
			<p>And then, of course, the house of cards began to tumble in, through a succession of events that everyone that lived through them remembers all too well &mdash; not just remembers, but remembers frozen and captured in the amber of a terrible series of still images &mdash; where you were, and what you were doing.  And then, after what seemed an endless moment, the numbing horror of what came next, as if the camera had begun rolling once again.</p>
			<p>I was at school in fifth grade when John Kennedy was shot.  Suddenly, all of the teachers disappeared from all of the class rooms, and stood whispering in the hall.  Then, all of the children behind all of the windows in all of the classrooms of the parochial school across the alley were suddenly on their knees praying.  And then we were sent home, without explanation, to be given the news by our parents in whatever way they thought best.</p>
			<p>When I was in ninth grade the least surprising but perhaps the most unjust event occurred, with the assassination of one of the greatest and most courageous men of my time.   The date was April 4, 1968, and the place, Memphis, Tennessee.  I was in London, England when I heard the news that the Reverend Martin Luther King had been assassinated.  For days, the first four pages of every London paper were awash with news, pictures, and tales of anguish from the scores of American cities that went up in flames and rioting, borne of the outrage that spewed from this latest, outrageous injustice, of fears once again fulfilled fears, and dreams once more taken away.  It seemed like the country must explode, or collapse.</p>
			<p>And it almost did, but for the outreach of those that tried to bridge a chasm that threatened to yawn ever wider until it consumed everyone on either side.</p>
			<div class="calloutright">
				<p>Idealism, it seems, too soon gave way to cynicism, and those that later preached similar messages almost always sounded as if they were only mouthing the words of ancient songs whose melody had been long forgotten</p>
			</div>
			<p>One of those that reached the farthest that wrenching summer was Bobby Kennedy, at the time campaigning for the Democratic nomination for the presidency.  On the day of King's assassination he landed in Indianapolis, Indiana, where he was scheduled to speak to a crowd gathered in a poor black neighborhood.  His staff urged him not to speak, but he insisted.  As he took the stage, he realized that his audience had not yet heard the news of King's assassination. But he rose to the occasion, speaking extemporaneously and saying in part:</p>
			<blockquote>What we need in the United States is not division; what we need in the United States is not hatred; what we need in the United States is not violence and lawlessness, but is love and wisdom, and compassion toward one another, and a feeling of justice toward those who still suffer within our country, whether they be white or whether they be black.<br /><br />(Interrupted by applause)<br /><br />&hellip;But the vast majority of white people and the vast majority of black people in this country want to live together, want to improve the quality of our life, and want justice for all human beings that abide in our land.<br /><br />(Interrupted by applause)<br /><br />Let us dedicate ourselves to what the Greeks wrote so many years ago: to tame the savageness of man and make gentle the life of this world.</blockquote>
			<p>An unusual man, to be sure.  A Harvard graduate with rolled up sleeves that could break the news to a stunned black audience that a white man had just assassinated the greatest black leader of the century, and then quoted Aeschylus as if it was the most natural thing to do on such an occasion.  And yet still he was able, through his simple eloquence and the shared experience of tragedy, to connect with a blue collar crowd dealing with emotions unimaginable to few that had not experienced such a sudden, terrible loss.  All in six short minutes and 12 seconds of speaking from the heart, while everywhere else in America cities were already beginning to burn.</p>
			<p>Two months later, of course, it was his turn to fall.  He had just given his victory speech in the dark, early hours of the morning to a room of joyous supporters after winning the California primary, a victory that seemed to guarantee him the Democratic nomination.  As the cameras remained trained on him, you could see him being pulled in one direction by the Secret Service, anxious to escort him from the pressing crowd.  But he turned to leave by a different door instead, stepping into the waiting gun sight of Sirhan Sirhan, out of the present, and into history.</p>
			<p>I heard that news a few hours later, early on the morning of June 4, 1968 while getting ready for school.  I rushed down to turn on the black and white TV, and saw that rock of mid-Twentieth century middle America, Walter Cronkite, visibly shaken and near tears, trying to put into words the shock and loss and outrage and injustice of what had, once again, been taken away from a family and a nation in an incomprehensible, irrational, momentary act of a single incomprehensible, irrational individual.</p>
			<p>His brother, Edward Kennedy, the last of the four sons that had seemed destined for greatness, delivered his eulogy, unforgettably ending with these words, spoken in a quavering voice:</p>
			<blockquote>My brother need not be idealized, or enlarged in death beyond what he was in life; to be remembered simply as a good and decent man, who saw wrong and tried to right it, saw suffering and tried to heal it, saw war and tried to stop it.<br />Those of us who loved him and who take him to his rest today, pray that what he was to us and what he wished for others will some day come to pass for all the world.<br /><br />As he said many times, in many parts of this nation, to those he touched and who sought to touch him:<br /><br />"Some men see things as they are and say why. I dream things that never were and say why not."</blockquote>
			<p>Those times could be tragic, but they were also inspiring, and I would not have missed them.  I was in London when Reverend King was shot because, together with my mother, brother and sister, we were reuniting with my father, who on his way home from Viet Nam.  In tune with those same times, he had been serving as an unpaid volunteer physician for civilians, arriving in Saigon the night before the Tet Offensive exploded all around him.  We didn't hear from him then for two weeks, until one night a volunteer ham radio operator, also in the service of others, searched the ether for another unknown volunteer, who in turn found another, in order to help someone separated from his family in a time of emergency reconnect with his loved ones and tell them that he was alive, and safe, and that he loved them.  All via an ephemeral daisy chain of compassion stretching halfway around the globe.</p>
			<p>For a few minutes we could speak, awkwardly trying to remember, but usually forgetting, to punctuate our hurried sentences with "over" and "out" to make the most of the short time available before the radio operators gently interrupted, so that they could connect another family across half a dark world of silent space.</p>
			<p>It's been a long time now since those heady, troubled days.  Idealism, it seems, too soon gave way to cynicism, and those that later preached similar messages almost always sounded as if they were only mouthing the words of ancient songs whose melody had been long forgotten.  Lyndon Johnson made much of Bobby Kennedy's and King's civil rights dreams become law, but his presidency sank in the morass that was Viet Nam.  Another morass, this time called "Watergate" took down his successor, and between the war and the scandal, idealism seemed to be at best a naive pursuit, and in Washington, a hollow joke.</p>
			<p>Until this year, that is, when it seems as if the old cards of idealism are improbably but credibly being put in place once again, this time by a young black senator born in the first year of Jack Kennedy's unfinished presidency.  And I, like many others (both in this country and abroad), feel like I am hearing from Barack Obama something real that I have been waiting for a very long time to hear again.</p>
			<div class="calloutright">
				<p>When at last the welcoming cheers died down, the speech he delivered was brief &mdash; five minutes perhaps.  It was heard by a crowd that seemed barely able to breathe once he began to speak, mindful that this opportunity would likely be their last to see the old lion in his element and feeling the fire of inspiration and a goal to be attained.</p>
			</div>	
			<p>It is true that with the passage of time Obama has been revealed to be more political than pure idealists would prefer.  But so, of course, were Jack, and Martin, and Bobby, each of whom had personal as well as public failings  But also, as with them, Obama's politics seem the servant to the ideals, rather than the other way around.  Most importantly, there seems to be an innate decency and genuineness in the man that shines through with conviction.</p>
			<p>It was a long-delayed delight to hear Michele Obama and her brother tonight, articulate, self confident, engaging and inspiring, standing in front of thousands of cheering delegates on the way to nominating the first black to run for president as the candidate of a major party. Their words, and the crowds embracing response, made it seem as if we may well stand once again on the verge of bringing the dream of a just, equal and hopeful future closer to realization.  What a luxury it would be after 45 years, and especially after the last 8, to feel as if we are enthusiastically dedicated again to something beyond national self interest, beyond individual self interest, beyond self interest for the sake of self interest.</p>
			<p>But the highlight of the evening for most, I am sure, was the appearance of Senator Ted Kennedy.  Until the last minute, it was uncertain whether he would be strong and well enough to speak. <em>[Update:  It was later revealed that he had a serious kidney stone attack the night before requiring hospitalization.]</em>  But when the appointed moment arrived, out he walked.  Unbowed, almost undiminished, and clearly delighted to be there, he took the stage smiling and waving after a tribute by Caroline Kennedy, followed by a video tribute of family flashbacks and footage of the Senator and grandchildren rejoicing in the vitality of a timeless day spent sailing on the home waters of Cape Cod Bay.</p>
			<p>When at last the welcoming cheers died down, the speech he delivered was brief &mdash; five minutes perhaps.  It was heard by a crowd that seemed barely able to breathe once he began to speak, mindful that this opportunity would likely be their last to see the old lion in his element and feeling the fire of inspiration and a goal to be attained.</p>
			<p>The Senator spoke confidently and with evident pleasure, with the same familiar timbre that has resonated in the halls of the Senate for 45 years, albeit tonight with some hoarseness and an occasional quaver in his voice at the end of a sentence.  But the famous energy, drive and spirit were clearly undiminished, if not taxed by too long a speech.  And he looked bluff and beefy as ever, though it was hard to miss the furrowed neck of an old man, lost inside a collar several sizes too large.  Only when he turned his head to the right could it be noticed that the familiar mane of white hair was a comb over, unsuccessfully attempting to conceal the half of his scalp that had been shaved clean for surgery only weeks before.</p>
			<p>As he warmed to the task, the cameras, of course, focused not only on anonymous faces in the crowd, but also on those of family members present &mdash; Caroline, rejoicing in the present and her uncle's evident pleasure at being there; Maria Shriver, distraught and on the verge of tears, hanging on every triumphant word but clearly focusing on the uncertainties of the future.</p>
			<p>The words were as wonderful and inspiring as ever, keeping faith over all the intervening years with the goals of those long-gone days of Camelot.  But this year, they seem not a quaint echo of a half-forgotten past, but a credible bridge from that past to a future that can reaffirm the selfless idealism of the 1960s, giving power to a wave that this time may wash higher on the beach of social justice than last time, and carry on a tradition that for too long has lacked the famous vigor of his brother's presidency.</p>
			<blockquote>He said: <em>I'll be there in January</em> to see Obama sworn in, and few were willing to doubt it.<br /><br />And he said: <em>For me, this is a season of hope</em>.  And that, <em>I stand here in hope</em>.  And also that, <em>If we set our compass true, we will reach our destination</em>.  And if he could hope and believe such things, than surely, the crowd knew, they could, too, and that they would willingly once more hope and believe such things as well.<br /><br />And he promised, this time echoing his brother Jack: <em>The torch has been passed once again to a new generation</em>.  And that it had been passed, <em>For you and for me</em>.<br /><br />And, finally, quoting the closing words of the speech he had made at another Democratic convention many years ago, conceding defeat and marking the end of his own presidential ambitions, he promised that, <em>The work begins anew, the hope rises again, the dream lives on</em>.</blockquote>
			<p>And so it does, for us. If we are willing to believe it, too.</p>
			<!-- ************* -->
			<p class="center"><em>Bookmark the Standards Blog at <a href="/newsblog/">http://www.consortiuminfo.org/newsblog/</a> or set <br />up an RSS feed at <a href="/rss/">http://www.consortiuminfo.org/rss/</a></em></p>
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--    CONSIDER THIS    -->
			<!-- ******************* -->
			<a name="considerthis" id="considerthis"></a>
			<h4>CONSIDER THIS:</h4>
			<h3><span class="red">#55</span> All Politics are Tribal:<br />The Myth of "One Citizen, One Vote"</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<img class="imgleft" src="oct08/oct08_img2.jpg" alt="" width="150" height="98" border="0"  style="margin:7px 10px 3px 0px;" />
			<p>Certainly the concept of "one citizen, one vote" must be the bedrock upon which all democratic theory and protections are based. Indeed, any government would presumably have to grant the validity of this tenet, lest its own validity be questioned. After all, at the end of the day, when all else is stripped away, the debatable and the subjective, the polemical and the political, is this not the one undeniable standard upon which everyone must agree, the fundamental principle of natural law that philosophers of any persuasion must certainly unite in supporting?</p>
			<p>And yet&hellip;</p>
			<p>Down through the millennia and even into the present, this simple, seemingly irrefutable standard of equality and representative government has proven to be almost impossible to establish in any democracy as a practical fact.</p>
			<p>Now why, exactly, must this be? First, let's consider the evidence, using the United States as an example, and beginning, as they say, at the beginning. Which in this case is the Declaration of Independence. The ringing and splendid language of that document includes the following:</p>
			<blockquote><em>We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.</em></blockquote>
			<p>There seems to be a troublesome word in that otherwise inspirational cornerstone of liberty, however. That word, of course, is "men", and the Founding (note bene) Fathers used that term advisedly. Male slaves need not apply for voting rights, either. And, as time would tell, a variety of other impediments to exercise one's democratic rights would be erected as well, including property and education restrictions, poll taxes, and more.</p>
			<p>Only incrementally (one might say grudgingly) and across the gulf of almost two centuries of ostensibly democratic government did even the nominal reality of "one citizen, one vote" come into gradual focus, first with the Fifteenth Amendment to the Constitution, in 1870, which sought to bar the States from using an individual's race, color or prior status as a slave as a bar to exercising the right to vote. Next came the Nineteenth Amendment, extending the franchise to women &mdash; but not until 1920. Then the Twenty-Third Amendment came to the rescue of the citizens of the District of Columbia, giving them in 1961, granting them a number of Electoral College votes equal to those held by the least populous state. Poll taxes were not outlawed until the enactment of the Twenty-Fourth Amendment, in 1964, in connection with a series of long-overdue and much needed voting rights laws that sought to finally extend equal voting rights in fact, as well as Constitutionally, to all, and particularly to those of color. The final voting related Constitutional amendment (to date) lowered the voting age to 18, in 1971.</p>
			<p>So there we are, at last, yes?</p>
			<p>But in fact, no. Why? Because next we must look at what happens after we cast our vote, and for whom.</p>
			<div class="calloutright">
				<p>Down through the millennia and even into the present, the simple, seemingly irrefutable standard of "one citizen, one vote" has proven to be almost impossible to establish in any democracy as a practical fact.</p>
			</div>
			<p>At the national level, we have three primary rights: to vote for members of the lower house of Congress (the House of Representatives) and for the upper house (the Senate), and also for the President. Our right to be represented in the lower house comes arithmetically closest to achieving the ideal of one citizen, one vote, since the 435 seats in that house are apportioned (and decennially reapportioned) based on population. But the Senate is populated by two representatives from each state, from the smallest (Wyoming, with just 493,782 citizens in 2000) to the largest (California, with 33,871,648 in the same year).</p>
			<p>Thus, while the tiny population of Wyoming had but a single representative in the House compared to mighty California's 53, it enjoyed the vocal support of the same number of senators as its giant near-neighbor. By that measure, the vote of a single citizen hailing from the windswept plains of Wyoming on November 4 of this year was equivalent to almost 70 voters visiting the polls in sunny California. One citizen, one vote indeed.</p>
			<p>And what of the presidency? There, of course, we encounter that quaint artifact of Colonial times known as the Electoral College, which can, and more than once has, elected a president that did not garner the majority of the popular vote (it used to be even worse, but don't ask).</p>
			<p>So how did we get to where we are today, and does it matter?</p>
			<p>At the heart of the matter, I believe, is the question of how we apply the simple word "us." If everyone within a given polity identified closely with every other citizen in that same political unit, then each would be likely to trust every other citizen equally, and therefore be willing to cede equal influence to them over their own destiny.</p>
			<p>The problem, of course, is that people don't. Instead, consciously or unconsciously we subdivide the population into a small number of "us" and a variety of other groups that by definition become "them." The bigger, more diverse, and more geographically distributed the pool of voters, the more types and the less familiar the nature of the pools of "them" become, if only through ignorance and suspicion. And once we have separate a national pool of voters into us and them, we begin to worry about how we will protect "us" against the suspect motives and goals of "them." The rest, as they say, is history (in this case electoral).</p>
			<p>The concept of us and them extends back into the dimmest reaches of time, when bands of closely related hunter gatherers needed to rely upon each other utterly for their very survival. Occasionally, such a band would inevitably encounter an unrelated collection of mortals in the dark of the woods. "They" would be speaking strange words and would represent competition for scarce resources. They might (who could know?) be capable of anything. Perhaps we are genetically programmed to be suspicious of all who are "not like us," predisposed to expect the worst from "them," and unconsciously biased towards creating governmental structures that recognize the fear of what "they" may do. More rationally, those that have had it within their power to structure governments may have been aware of the fact that "they" may need protection from "us" as well.</p>
			<img class="imgright" src="oct08/oct08_img3.jpg" alt="" width="300" height="215" border="0" />
			<p>Perhaps it is time to update the famous observation of that legendary Speaker of the House, <a href="http://en.wikipedia.org/wiki/Tip_O%27Neil">Tip O'Neil</a>, and conclude that all politics are tribal as well as local. Sad to say, much as we may continue to pay lip service to the high minded concept of "one citizen, one vote," lip service it will doubtless remain till that distant day when at last we regard all of our fellow citizens to be members of the same, great and democratic tribe.</p>
			<!-- ************* -->
			<div class="clear"></div>
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p class="center">Read more <strong><em>Consider This&hellip;</em></strong> entries at: <a href="/blog/">http://www.consortiuminfo.org/blog/</a></p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--   MONDAY WITNESS    -->
			<!-- ******************* -->
			<a name="mondaywitness" id="mondaywitness"></a>
			<h4>MONDAY WITNESS:</h4>
			<h3>John McCain's Elephant Man Moment</h3>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<h6>Date: October 12, 2008<br /><span class="views">Views:  1,351</span></h6>
			<img class="imgleft" src="oct08/oct08_img4.jpg" alt="" width="163" height="255" border="0" />
			<p>Election campaigns bring to mind &mdash; usually ruefully &mdash; standards of many types. Among them are the levels of civility, truthfulness, and fair play that we wish candidates would exhibit when they compete for our votes. But as the day of final electoral reckoning approaches, the gulf between the standards we favor and the conduct we observe on the hustings tends to widen rather than narrow. To my mind, nothing demonstrates a lack of character in a candidate as the degree to which he or she is willing to slander an opponent.</p>
			<img class="imgright" src="oct08/oct08_img5.jpg" alt="" width="204" height="254" border="0" />
			<p>Holding candidates accountable to reasonable standards of conduct and character in this respect has become more problematic of late, in part because candidates and their parties keep developing new ways to distance themselves from sordid practices, while still reveling in their results. Some of these tactics have become sufficiently notorious to contribute new names to the lexicon of electoral dirty tricks. The 2004 campaign, for example, gave us a new verb: to "<a href="http://en.wikipedia.org/wiki/Swiftboat">Swiftboat</a>," meaning to spread disinformation through an organization that has pretensions to credibility, and also denies any connection to the campaign of the candidate the disinformation assists. The name, of course, derives from the ostensibly ad hoc association of war veterans that sought to impugn the war record of Democratic candidate John Kerry, a decorated Viet Nam war hero. Most recently, we have a new adjective &mdash; "<a href="http://www.nytimes.com/2008/10/11/washington/11rove.html?_r=1&amp;em">Rovian</a>" &mdash; derived from the name of former Bush political mastermind Karl Rove. This word is used to condemn (although sometimes with grudging admiration) conduct that is both artful and wrong &mdash; such as collaborating with Swiftboaters (yes, there is a noun form as well).</p>
			<p>By design, Rovian Swiftboat tactics are difficult to pin on the candidates that benefit from their use. This allows the candidate to seem to float above the unsavory muck while still enjoying its predictable results ("Of course, I would never have said such a thing, but you know&hellip;"). Still, as with any other foray into the exercise of subjective morality, a candidate cannot totally avoid becoming sullied by the same dirt, unless he or she immediately and consistently condemns the lies, as well as those that have promoted them.</p>
			<p>Outing Swiftboating and other Rovian tactics, of course, can lose the benefit of the lies, and the art is therefore for a candidate to avoid being placed in a position where they must either endorse, or condemn, the statements that they know to be false. When that effort fails, a candidate may suddenly find him or herself publicly caught short in front of a mirror that forces them to see things about themselves that they have been unwilling to confront before.</p>
			<div class="calloutright">
				<p>Suddenly, McCain's face falls, as if he finally realizes three things all at once: the absurd falsehood of the statement he has just heard; the role that his own campaign has played in bringing this woman to her statement; and finally, that a man that has repeatedly said that he would rather lose a campaign than lose a war had somehow seriously lost his way.</p>
			</div>
			<p>John McCain found himself in just that position this week in a manner that I'll return to at the end of this blog entry. When he did, I could not help recalling <a href="http://en.wikipedia.org/wiki/The_Elephant_Man_(film)">The Elephant Man</a>, a much acclaimed 1980 film directed by David Lynch. That movie dramatizes the true story of <a href="http://en.wikipedia.org/wiki/Joseph_Merrick">Joseph Merrick</a>, a horribly deformed and sensitive individual rescued from a Victorian-era freak show by a well to do physician named <a href="http://en.wikipedia.org/wiki/Sir_Frederick_Treves,_1st_Baronet">Sir Frederick Treves</a>. Lynch takes substantial liberties with historical facts to explore, through the role of Treves, questions of integrity, responsibility and personal motivation that could not be more germane to the events we are witnessing in the closing weeks of the United States presidential campaign.</p>
			<p>The central question that underlies Lynch's film is whether Treves is truly acting in the best interests of Merrick, or whether he is exploiting the Elephant Man of the freakshow for his own personal benefit. Which individual, the director asks, is truly deformed &mdash; the innocent condemned by birth to be an object of visual horror, or the privileged physician, who provides Merrick with a safe place to live, but also makes him available to the social elites that come to gape at Merrick's horribly deformed face and form. In effect, Treves steps more humanely into the role of Bytes, the brutal freakshow owner that provided Merrick with a marginal living at the cost of displaying him to the mob. As the plot unfolds, Treves's star in society rises in direct proportion to the increasing celebrity of his ward. Meanwhile, the luminaries of fashionable society that Treves introduces to Merrick trade pleasantries with the now-dandified Merrick over tea &mdash; and horrified comments at his expense as soon as they leave.</p>
			<p>In one scene, Treves catches his own reflection in a mirror hung in the entryway to his home. He is brought short by the sudden appearance of his image before his eyes, and studies his face, as if for the first time, to determine whether what others see on the surface is truly representative of what lies beneath. The image of his wife then appears next to his own, and they engage in everyday greetings, while Treves's sidelit image appears in contrast not only with the glowing face of his saintly wife, but also within its own silhouetted features &mdash; starkly recalling the virtuous and the reprehensible, and the light and dark in his own soul- two facets of the same individual, sharply defined and opposed and yet inseparable.</p>
			<p>Lynch is not shy in forcing both Treves as well as the movie goer to confront the responsibility of his, and by extension our, actions. In what is (to me) the most haunting scene of the film, Treves sits in the dark of the evening in his lamplit study, selecting books to lend to Merrick. He pauses in his task to gaze at a copy of Mary Shelley's Frankenstein, another metaphoric tale that juxtaposes moral purity with physical deformity. He places the volume back on the table, saying, "You stay with me." The <a href="http://corky.net/scripts/elephantMan.html">script</a> continues as follows</p>
			<blockquote>ANNE TREVES (calling from the next room): Dinner will be served, shortly, dear. (getting no response, she enters.)<br /><br />
			ANNE: More romances for John?<br /><br />
			FREDERICK TREVES (far away): Hmmm?<br /><br />
			ANNE: &hellip; Freddie! What's the matter? You've been like this all evening.<br /><br />
			FREDERICK: Oh&hellip; I've just been thinking about something that man Bytes said.<br /><br />
			ANNE: Oh, Freddie. What could that wretched vampire say to upset you?<br /><br />
			FREDERICK: That I am very little different from him.<br /><br />
			ANNE: Oh that's absurd, Frederick. No, no Frederick, that's all wrong!<br /><br />
			John is happier and more fulfilled now than he has ever been in his entire life. And, that is completely due to you!<br /><br />
			FREDERICK: But why did I do it? What was this all for? So John Merrick could live out his last days in peace and comfort? Or so I could become famous?<br /><br />
			ANNE: Frederick, just what is it that you are saying?<br /><br />
			FREDERICK: &hellip; Am I a good man or am I a bad man?<br /><br />
			ANNE: Oh Frederick. (she holds her profoundly distraught and troubled husband in her arms)</blockquote>
			<p>The Elephant Man metaphor works so powerfully in part because of the visual contrast between the spiritually pure but horrific looking Merrick and the proper and privileged, but morally troubled Treves. The former struggles with rejection at the hands of an imperfect society that counts appearances over character, while the latter luxuriates in the approval of the social peers that reward him despite the morally compromised game they recognize he is playing. Because Treves is both self aware as well as vulnerable to temptation, we watch the conflict play out before our eyes even as we are challenged by our own visceral reactions to the inhuman face that The Elephant Man displays to the world.</p>
			<p>John McCain had his own Elephant Man moment this week, when he, like Treves, was forced to face up to the moral consequences of a campaign that has too often been marked by a stream of Rovian Swiftboat allegations launched against his opponent. These statements have associated Obama with terrorism, the covert practice of Islam, and even Arabic heritage. Each of these pieces of disinformation has been cynically promoted in an effort to destroy the Democratic candidate's credibility in the eyes of the type of voters that would find the practice of Islam or the fact of Arabic heritage to be as morally deformed as the practice of terrorism. Nor have all such assertions been of a Swiftboat nature, as McCain's running mate, Sarah Palin, has sought to paint Obama as a terrorist sympathizer through association with a founder of the Weather Underground &mdash; who is now a respected university professor and a recent recipient of Chicago's Citizen of the Year Award.</p>
			<div class="calloutright">
				<p>Making the correct decisions will require us all to look inside ourselves to determine whether what we ask for from our government is right and just and for the benefit of all, or simply hypocritically self-serving, and disguised in disinformation of our own.</p>
			</div>
			<p>Specifically, McCain's moment occurred as he faced crowds of supporters that have been whipped up to believe things that McCain well knows not to be true. Visibly taken aback on camera as Town Hall participants made more and more outrageous claims about Obama to his face, McCain found himself confronted with the need to ask himself the Treves question: "Am I a good man or a bad man?"</p>
			<p>Here are <a href="http://www.youtube.com/watch?v=Kf6YKOkfFsE">three video clips</a> of an increasingly uncomfortable McCain, trapped in the YouTube eye, in the harsh moral silhouette of the moment. In the third, he is looking an older woman directly in the eye. When she says that she doesn't trust Obama, McCain smiles, and nods vigorously in agreement.</p>
			<p>But then everything goes all wrong. The woman struggles with the reason. "Because&hellip;" she says, "Because&hellip;he's an Arab." Suddenly, McCain's face falls, as if he finally realizes three things all at once: the absurd falsehood of the statement he has just heard; the role that his own campaign has played in bringing this woman to her statement; and finally, that a man that has repeatedly said that he would rather lose a campaign than lose a war had somehow seriously lost his way. In that moment, the self-image that McCain holds in his own mind's eye, of the maverick war hero riding to his country's defense in its hour of need, must have suddenly morphed into the morally deformed image of a man whose ambitions had perverted his principles. There and then, you could see the question flicker across McCain's face: "Am I a good man&hellip;or a bad man?"</p>
			<p>To his credit, McCain made the right choice in the moment. He took the microphone back from the woman, and looking down humbly at the ground, saying, "No Maam," in a voice that almost added, "They&hellip;I&hellip;have misled you." Obama, he was forced to admit aloud, is a "decent family man" who should note be feared, but respected, and treated with respect. Many in the crowd booed in response, not seeing the picture in McCain or Obama that they wished to see. Unlike McCain in that moment, they failed to realize that the moral deformity at issue was in themselves, and not in the history or the character of the object of their scorn.</p>
			<p>Perhaps when the dust of this election has settled and the ballots have been tallied, some of them will have their own Elephant Man moments, and take a closer look at their own principles and motivations to determine whether they like what they see. Many, I fear, will not.</p>
			<p>That, of course, would be a great pity, because regardless of the outcome of the current election, we as individuals, and all of us collectively as a society, will have many difficult decisions of principle to make. Making the correct decisions will require us all to look inside ourselves to determine whether what we ask for from our government is right and just and for the benefit of all, or simply hypocritically self-serving, and disguised in disinformation of our own.</p>
			<p>A poem by Isaac Watts that Merrick often used to close the letters he sent during the final few happy years of his short life (he died at the age of 27) might assist us all in our own processes of self appraisal. That poem reads as follows:</p>
			<p class="center"><em>Tis true my form is something odd,</em></p>
			<p class="center"><em>But blaming me is blaming God.</em></p>
			<p class="center"><em>Could I create myself anew,</em></p>
			<p class="center"><em>I would not fail in pleasing you.</em></p>
			<p class="center"><em>If I could reach from pole to pole,</em></p>
			<p class="center"><em>Or grasp the ocean with a span,</em></p>
			<p class="center"><em>I would be measured by the soul,</em></p>
			<p class="center"><em>The mind's the standard of the man.</em></p>
			<!-- ************* -->
			<p class="center"><em>Bookmark the Standards Blog at <a href="/newsblog/">http://www.consortiuminfo.org/newsblog/</a> or set <br />up an RSS feed at <a href="/rss/">http://www.consortiuminfo.org/rss/</a></em></p>
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
			<!-- ******************* -->
			<!--   WHAT'S NEW AT CONSORTIUMINFO.ORG   -->
			<!-- ******************* -->
			<a name="whatsnew" id="whatsnew"></a>
			<h4>WHAT'S NEW AT CONSORTIUMINFO.ORG:</h4>
			<h3>The New Look of the News</h3>
			<p>Since February of 2002, the <a href="/news/">Standards News Portal</a> has been updated on a daily basis to bring you the most important news about standards, how they are created, and how they affect your business and your life. The Standards News Portal also allows you to search and read all of the 4,793 articles that have been added to the Portal's database since its launch, constituting perhaps the largest archive of its type in existence. You can sort the database by topic, by date, and by 26 topical and geographic subcategories using the tools you can find at the <a href="/news/archive.php">Standards News Portal Archive</a> page. For a wry and topical view of the news, you can also browse through the hundreds of <a href="/news/quotes.php">Quotes of the Day</a> that I have selected and archived over the last six years.</p>
			<p>Recently, the Standard News Portal was given a complete overhaul to make it easier and more rewording to use, with a new, cleaner look, additional subcategories, and new search tools. As before, it aggregates not only the news, but also blog entries and the Quote of the Day, making it the perfect bookmark if you want to keep in touch with what's happening in the world of standards. As with the other sections of this site, the news you will find at the Standards News Portal relates not only to new standards and how they are created, but also how they affect your business and the world around you.</p>
			<p>As with everything else at ConsortiumInfo.org, the Standards News Mortal is available free of charge for the benefit not only of my firm's many consortium and other standards clients, but for the standards community at large as well.</p>
			<p>Needless to say, standards are even more important now than they were when the Standards News Portal was first introduced. With each passing year, more and more of everyday life, business and government is being experienced and conducted on line. As new issues, such as confronting global warming, developing clean energy and protecting Homeland Security grow more important, so also do the standards upon which such activities must rely. How standards are developed, by whom, and for what purposes, therefore impacts us more completely and directly by the day.</p>
			<p>Whether or not you have been a regular user of the Standards News Portal in the past, take a moment to <a href="/news/quotes.php">check it out now</a> at http://www.consortiuminfo.org/news/</p>
			<p class="center">Copyright 2008 Andrew Updegrove</p>
			<p>Sign up for a <strong><em><a href="/subscribe/2.php?addentry=1">free subscription</a></em></strong> to <strong><em>Standards Today</em></strong>.</p>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
			<div class="hr"></div><hr />
			
		</div>
	</div>
<div class="clear"><br /></div>
<!-- *********** -->
<!--   FOOTER    -->
<!-- *********** -->
<?php include '../includes/footer.php'; ?>
</form>
</body>
</html>