				<!-- ******************* -->
				<!--   FEATURE ARTICLE   -->
				<!-- ******************* -->
				<h3>Government Policy and "Standards &mdash; Based Neo-Colonialism" </h3>
				<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
				<blockquote class="openingquote"><em><strong>Abstract:</strong> From the sixteenth through the nineteenth centuries, European powers colonized most of the rest of the world in order to exploit the natural resources, inexpensive labor, and new markets that became available in the wake of the great voyages of discovery. These comparativley more developed nations were able to do so in part as a result of their superior technology and capital resources. Today, the developed world and its institutions are sometimes criticized for "neocolonial" activities that allow them still to exploit, or unduly influence, their former colonies. One manner in which multinational corporations can engage in similar conduct is through their control of the patents that underlie many important standards. When such standards bear royalties, the patent owners can relegate emerging nations to low-cost job shops that are able to build products, on order and at low profit margins, for foreign brands, but not to sell similar products under their own brands at higher profit margins. The predictable result is the development by nations (most notably China) of duplicative "home grown" standards. Unless greater efforts are made to avoid royalties and other restrictive terms in standards-related patent licenses, it is therefore likely that increasing numbers of standards wars will break out in the future, obstructing international trade. In this article, I explore the roots of this phenomenon, and suggest ways in which the situation might be redressed.</em></blockquote>
				<p><strong><em>Introduction:</em></strong> The great Age of Discovery launched by Portugal's Henry the Navigator in the 15th century opened up an ever-expanding new world to Europeans. As each expedition penetrated further to the south, new curiosities were discovered, and in 1488, Bartholomeau Dias finally rounded the Cape of Hope. Only a few years thereafter, Columbus, for Spain, and Vasco Da Gama, for Portugal, opened the way to the Indies &mdash; both West and East, and in the years that followed detailed coastlines progressively emerged out of the blank areas long marked as terra incognita on western charts.</p>
				<p>These explorers were closely followed by merchants, who in turn were supported by naval and military forces sufficient to protect them as they sought the spices, precious metals and other desirable commodities that were the original inspiration for the voyages of exploration. In due course, the new regions opened up to trade became attractive markets for European goods as well.</p> 
				<p>The endgame of this process became the active extension of the sovereignty of individual European nations over subject territories throughout the world, in what came to be called colonialism. The actual mechanisms employed varied, with some colonies becoming the homes of large numbers of European emigrants and others being controlled as dependencies or exploited through trading outposts. But in each case, the European power that had succeeded in establishing its rights on the ground could extract the colony's renewable as well as finite resources using the cheaper labor of the indigenous people themselves. At the same time, the colonial power obtained a largely captive market for its own finished goods.</p>
				<p>Over time, the colonial tide was turned, and the subject territories achieved self-government. In some cases, local control was complete, as in North America, while in other areas, such as the former Belgian Congo, the former colonizer retained significant economic control in what came to be called a process of "neocolonialism."</p>
				<p>Today, neocolonialism remains an emotional topic, in situations as diverse as African nations accusing the International Monetary Fund of asserting undue control over their economies and France decrying the encroachment of all things American on Gallic culture and language.</p>
				<p>Perhaps it is not surprising, then, that the development of standards should have the potential to become a subject of contention as well, due to the profound impact that standards have on global trade, and the fact that international economic treaties impose obligations relative to them as well.</p>
				<p>In this article, I will discuss the basis for such concerns. I also suggest certain modifications to the current international standard setting infrastructure that could provide a more equitable and appropriate system for emerging as well as first world nations in our increasingly globalized world.</p>
				<p><strong><em>The current system:</em></strong> The operation of today's <em>de jure</em> standards system in some ways replicates the United Nations. Nominally, all nations may participate and vote, but most of the standards that are voted upon still originate from the industries of the developed nations. More tellingly, most of the patents that may be infringed by the implementation of the standards that are adopted are also controlled by corporate owners in those countries. This is particularly the case in high-tech areas such as consumer electronics and information and communications technology (ITC).</p>
				<p>Moreover, as vendors in emerging countries strive to achieve equal status with corporations based in what are often their former colonial masters, they may run afoul of treaty obligations as well. In the case of communications, the treaty organization known as the International Telecommunication Union, or ITU, dominates. And if a nation wishes to accede to the World Trade Organization (WTO), it encounters the <a href="http://www.wto.org/english/docs_e/legal_e/17-tbt.pdf">Agreement on Technical Barriers to Trade</a> (ATBT).<sup>1</sup> One focus of that agreement is to prevent nations from excluding or disadvantaging foreign goods through the creation of artificial standards-related barriers. Such barriers can include requiring compliance with unnecessary domestic standards that overlap with already existing global standards, and conformity testing requirements that are unnecessary and burdensome.</p>
				<p>Unfortunately, while the ATBT is targeted at avoiding one problem, it can also create another when the implementation of an already-adopted global standard necessarily infringes upon a royalty-bearing patent. Nominally, such a problem would be internationally neutral, since the patent will have a single owner that may only levy royalties on a reasonable and non-discriminatory basis. But in a consolidated marketplace such as consumer electronics, the multinational corporations that already control most of the marketplace are likely to have cross license agreements in place that lower, or eliminate, the per-item royalties that may be payable among them on many types of standardized technology.<sup>2</sup></p>
				<p>The result for an emerging nation can be harsh. On the one hand, it may enjoy the benefits of a skilled and much lower cost workforce, and therefore be able to secure the manufacturing contracts to produce goods for sale under the brand of the foreign contract party. But at the same time, the patent royalties that would be payable if it built similar goods under its own brand may be prohibitively high. As a result, it may be restricted as a practical matter to manufacturing such products only for foreign corporations, which will reap much higher profits on the eventual sale of the goods than those earned by the off-shore manufacturer itself.</p>
				<p>This is the situation that China faces today, especially after acceding to the WTO. As a result it has adopted a policy of utilizing foreign standards that can be implemented without payment of royalties, while developing so-called "home grown" standards for products when it feels that the royalties and other license terms demanded by foreign corporations are overly burdensome.<sup>3</sup></p>
				<p>This unequal situation in some ways parallels the colonial experience of the same countries. For most of the 20th century, former colonial powers and other modern nations enjoyed a significant lead over emerging nations in technical design expertise, productive capacity, capital resources and workforce skills. These factors provided already developed nations with overwhelming commercial advantages, just as the European powers had earlier enjoyed decisive economic, military and technological leads over many of the societies that they came to control through direct possession (as in the majority of cases) or to greatly influence (as in China) through other means.</p>
				<p>And just as those European powers could (and did) divide the undeveloped world among themselves, the multinational corporations of today can (and do) form commercial alliances involving patent cross licenses, comarketing activities and other agreements that increase their competitive advantages over their smaller competitors.</p>
				<p><strong><em>The potential for IPR neocolonialism:</em></strong> The influence of a corporation can be amplified dramatically in the case of a given product niche due to the fact that it has the right to file a patent anywhere in the world &mdash; and indeed everywhere in the world &mdash; to protect most types of inventions.<sup>4</sup> In the case of a narrow patent, this right may be of limited import. But if that same patent is necessarily infringed by a globally adopted standard, then the filings securing that patent have the ability to replicate with startling thoroughness the impact of territorial colonialism, and at breathtakingly lower cost.</p> 
				<p>For example: in the past, a nation interested in the cheap labor, rich natural resources and large market potential of a territory available for colonization would need to embark upon a long and difficult series of steps to reap the benefit of such control, of which the following are merely the highpoints:</p>
				<ol>
					<li>Conquer or otherwise achieve influence over the target territory</li> 
					<li>Secure the new colony militarily through the establishment and maintenance of military and police garrisons</li> 
					<li>Create an administrative, transportation and commercial infrastructure capable of supporting resource extraction, keeping the peace, and managing export and import funcitons</li> 
					<li>Recruit (and in some cases import), train and supervise a labor force to extract the resources in question and distribute manufactured goods</li> 
					<li>Defend the colony against internal uprisings and external rivals</li>
				</ol>
				<p>While the potential rewards of such a process were great, the costs and risks of acquisition were also substantial. Nor were the results always certain, especially if a rival power coveted the same territory. Moreover, many of a colonizer's own people usually died in the process of securing, defending, and simply surviving in such colonies.</p>
				<p>In contrast, a modern multinational company can secure most, or all, of the same advantages at vastly lower cost and commercial risk, through the exercise of its greater level of experience, resources and patents.</p>
				<p>A single example clearly makes the point. Consider the inventors of the technology underlying a modern DVD player. Such a player implements many standards, including, most obviously, the DVD format itself. Today, virtually all DVD players are built in Pacific Rim countries, such as China. DVD players can be made a a very low cost using China's abundant, inexpensive labor force, and at a very low profit for the owner of the Chinese manufacturing plant. They are then sold throughout the world, under foreign brand names, by the companies that hold the patents on the underlying standardized technology. They are also sold in China itself, again at a greater profit than is reaped by the Chinese manufacturer that produced them, who clearly cannot afford to pay the c. $20 in royalties that would be payable on a device with a retail price of c. $49.</p>
				<p>Because the content that must be purchased<sup>5</sup> in order to make the DVD player useful has been created using the same format, the foreign patent owner has effectively "colonized" China with respect to both DVD players and content. Without ever having to take control of the Chinese market physically, it can now harvest Chinese resources (China's labor force) from afar, and it can also control the Chinese market with respect to its purchasing (of DVD players). Indeed, the multinational corporation that owns the patent need not even export its goods to the market that it has colonized. Instead, it can simply make its DVD players close to the customer, enjoying a larger profit due not only to lower costs of production, but to reduced transportation costs as well.</p>
				<p><strong><em>The backlash:</em></strong> The predictable result is that any emerging country &mdash; and especially one that has already experienced traditional colonial rule &mdash; will be unlikely to submit to such treatment in the long term. As earlier noted, China in particular has been chaffing under the effects of the current regime, and has a number of advantages at its disposal that it can use to counter the disproportionate power bestowed by the embedding of royalty-bearing patents in standardized products.</p>
				<p>First and foremost is the enormity of the Chinese marketplace itself. If goods built to a Chinese standard are as good or better than those that implement a global standard, and are cheaper besides, then it is not likely that the Chinese marketplace will find products built to the foreign standard to be attractive, all other things being equal.</p>
				<p>In the first, widely publicized clash between a domestic and a foreign standard, the Chinese government asserted that the globally-adopted WiFi standard was deficient, particularly as respects its security capabilities, in comparison to the comparable features of the Chinese WAPI specification &mdash; which was protected by multiple Chinese patents. The Chinese government announced that all laptops to be sold in China would be required to be WAPI compliant, and also that only a limited number of Chinese vendors would receive the required patent licenses. Foreign companies would need to contract with those licensees to build compliant chipsets, and domestic manufacturers would enjoy a significant cost advantage due to the impact of related taxes.<sup>6</sup></p>
				<p>The second significant advantage enjoyed by China is the control exercised by the government over the still largely centrally controlled economy. In the case of regulated areas such as telecommunications, the government has the right to grant licenses to telecom carriers &mdash; and to specify what standard those licenses must implement. Once again, China has developed its own 3G mobile phone standard (called TD-SCDMA). At least some of the first round of 3G licenses will be written on this standard when the next generation of handsets are sold into this largest of all cell phone markets. And once again, a portfolio of Chinese patent claims read on that standard. Foreign telecom vendors will be required to pay royalties on those patents &mdash; perhaps once again at a higher rate than domestic manufacturers.<sup>7</sup></p>
				<p>China's size matters in a third way as well. As in any other country, the government is a very significant purchaser of goods and services, as well as the other side of many transactions in which the citizenry must participate, such as transactions involving documents. Here, too, there is now a Chinese standard in place, called the Unified Office Format (UOF). And once again, there are claims in seven separate patents that read on compliant implementations of that standard. China's licensing intentions have not yet been announced, but it is anticipated that foreign vendors will be required to obtain royalty-bearing licenses in order to implement the standard. Moreover, China voted in ISO/IEC JTC1 against adoption of the XML document standard based upon Microsoft's OfficeOpen XML formats in the round of balloting that closed on September 2 of this year.<sup>8</sup></p>
				<p>Nor are these the only examples. China also now has, or shortly will have, its own video as well as audio compression standards for use on DVDs,<sup>9</sup> two mobile television standards,<sup>10</sup> and multiple home-grown distributions of Linux, among other home grown standards and open source software.</p>
				<p>While China has gone farthest in creating home grown standards in reaction to royalty-bearing foreign-origin standards, it cannot be assumed that other nations may not embark upon similar programs in the future. Most obviously, India has a population that now exceeds 1 billion individuals, a vibrant technology industry, and increasingly large numbers of middle and upper class consumers. Many countries around the world, including Brazil, Malaysia and many others have shown increasing interest in open source software, in large part to avoid dependency on, and lock in by, the proprietary products developed by dominant vendors such as Microsoft.</p>
				<p><strong><em>The problem:</em></strong> It would be highly regrettable if fragmentation in ICT standards becomes more widespread just as open standards become more credible and in demand than they have ever been before. And yet presumably this is exactly what will happen, unless the standards that are adopted by both the accredited and the unaccredited standards processes consistently avoid high royalties and/or undesirably restrictive licensing terms. It will be equally likely that a new rush to patent offices worldwide will occur, both defensively as offensively, if core standards are too often so encumbered.</p>
				<p>Already, there is evidence of such activity, with the number of patents being filed in (for example) China dramatically increasing on a year to year basis. Such escalation in a global war of standards, patents and royalties would severely undercut not only prospects for pervasive interoperability, but globalization and the efforts of the WTO to avoid barriers to the free flow of goods and services.</p>
				<p>Unfortunately, finding a resolution to this problem runs afoul of long-held tenets of the traditional standard setting infrastructure. That regime has long recognized the validity of IPR, and has sought to find a balance between honoring the rights of inventors to receive fair value for the implementation of their inventions with the need to make such inventions available to standards implementers on acceptable terms.</p>
				<p>Historically, that balancing has been possible, in part because most stakeholders could be found in modern countries that were at a roughly similar stage of economic and technological development, and had equal access to participation in the standards development process. Indeed, many vendors participated in standard setting activities with the goal of reaping royalties or other benefits from the inclusion of their patented technology in the standards that were developed. Where the large vendors had all been building up their patent portfolios over long periods of time, there was rough parity of position in the marketplace, and the costs of licensing could be built into the pricing of the goods that the marketplace was willing to buy.</p>
				<p>With the entry of so many new companies into the marketplace in emerging countries, however, the patent landscape is woefully disproportionate, placing new vendors at a huge disadvantage, with piracy by small vendors often being the result in some nations. But as these economies mature and piracy is gradually eradicated, the imbalance returns. Even as large a company as Lenovo will be hard pressed to acquire patent portfolios in western nations to rival those of Pacific Rim rivals such as NEC or Samsung, let alone western behomeths like IBM, Phillips Electronics or Siemens.</p>
				<p>If parity can never be reached through this means, then, how can a level playing field be found in order to remove the incentive to engage in an endless series of standards wars?</p>
				<p><strong><em>A possible solution:</em></strong> The logical, if not necessarily easy, solution would be to drive global standard setting towards royalty-free, and otherwise reasonable and non-discriminatory, terms (sometimes referred to as "RAND-Zero" (or simply RANDZ) as in "zero cost"). Obviously, this would require a rebalancing of the rights of IPR owners and implementers, at least as regards those that choose to participate in the development of the standards themselves. But how can this be achieved?</p>
				<p>The most effective means would be for all standards organizations to convert to mandate RANDZ licensing of essential patent claims. That outcome, however, would likely result in many large patent owners simply refusing to participate in standard setting at all, thus plaicing their patent portfolios out of reach and still likely to be infringed.</p>
				<p>A less radical and more feasible step would be to encourage individual countries to adopt a policy that requires government purchasing of products that implement RANDZ standards whenever those standards are available. Already there are nations that show a purchasing preference or requirement for products that implement ISO/IEC adopted standards, and the commercial impact of this preference on vendors can be easily recognized in the marketplace, notwithstanding the fact that ISO/IEC adoption has little or no impact on sales in large markets, such as the United States.<sup>11</sup></p>
				<p>Were such a policy to be adopted by many nations, the purchasing power at play would be very considerable. The resulting benefits would also be substantial, and could include favorable impacts in each of the following areas:</p>
				<ol>
					<li>Greater competition in the marketplace, due to greater cost parity between competitors</li>
					<li>More innovation, due to greater incentives to compete on additional functionalities and services lying above the standardized design layer</li>
					<li>Lower barriers of entry, especially for small companies that lack the patents needed to cross license with other companies in order to equalize their cost of goods</li>
					<li>Freer global trade, due to reducing the incentives to create "home grown" standards</li>
					<li>Fewer trade disputes between nations involving technology-based products</li>
					<li>More rapid development of larger global markets based upon single standards</li>
					<li>Less game playing in the standard setting process, due to there being fewer benefits to reap from embedding patents</li>
					<li>Greater economic opportunities for entrepreneurs and workers in emerging nations, through the creation of more and better paying jobs</li>
					<li>Faster rising salaries in emerging nations, benefiting not only workers and families in those nations, but decreasing the attractiveness of exporting production jobs from developed nations</li>
					<li>Greater political stability and expectations for democratic reforms as the standard of living rises in developing nations</li>
					<li>Decreasing incentives for illegal imigration into developing nations</li>
				</ol>
				<p><strong><em>Summary:</em></strong> Of course, simply changing government purchasing policies would hardly solve all of the world's problems overnight. But as the value of technology-based products and services continues to grow, as it surely will, a greater and greater percentage of the gross national products and jobs of all nations, both developed and developing, will be dependent on how quickly the standards upon which those products and services are based are developed, and how uniformly they are adopted.</p>
				<p>Market forces that lend to the creation of (otherwise) superfluous standards should therefore be countered whenever possible if truly free markets and global trade are to be encouraged. By going to the IPR-based core of some "neocolonialist" market forces and excising the motivation for duplicative standards, many damaging standard wars might be averted, and positive results encouraged.</p>
				<p class="center">Copyright 2007 Andrew Updegrove</p>
				<p>End Notes</p>
				<p><sup>1</sup> The Agreement on Technical Barriers to Trade can be downloaded at http://www.wto.org/english/docs_e/legal_e/17-tbt.pdf The WTO maintains a <a href="http://www.wto.org/english/tratop_e/tbt_e/tbt_e.htm">general resource page</a> with additional information and links at http://www.wto.org/english/tratop_e/tbt_e/tbt_e.htm</p>
				<p><sup>2</sup> It would be logical to ask whether such practices are in fact "non-discriminatory," at least when examined in the context of a single standardized product. I am not aware that this argument has successfully been made with respect to any standard, and such practices appear to be accepted as consistent with a RAND licensing commitment.</p>
				<p><sup>3</sup> China has developed many such standards, with mixed success on the implementation side. They include alternative standards in areas such as wireless communication, video compression, document formats, and 3G telephones. For more on China's standards efforts in this regard, <em>see</em> Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/apr05.php#feature">The Yin and Yang of China's Trade Strategy: Deploying an Aggressive Standards Strategy Under the WTO</a>, the ConsortiumInfo.org <em>Consortium Standards Bulletin</em>, Vol. IV, No. 4, April 2005, and sources cited therein, <em>at</em> http://www.consortiuminfo.org/bulletins/apr05.php#feature.</p>
				<p><sup>4</sup> Software is a notable exception. While inventions implemented in software became generally eligible for patent protection in the United States by the early 1990s, software that executes business tasks remains generally unpatentable in Europe, despite repeated and ongoing efforts by industry efforts to reverse this rule.</p>
				<p><sup>5</sup> Or pirated, as the case may be. But in either case, the result is the same.</p>
				<p><sup>6</sup> The reaction from western manufacturers such as Intel and Texas Instruments was energetic and decisive: each announced that it would not sell wireless chipsets into the Chinese market until the policy was reversed. The resulting trade dispute was escalated to the highest levels of government, and eventually defused (although not finally resolved) when the deadline for WAPI adoption was indefinitely postponed. It has still not been finally resolved. For further details, see <em>The Yin and Yang of China's Trade Policy: Deploying an Aggressive Standards Strategy Under the WTO</em>, cited above.</p>
				<p><sup>7</sup> For a detailed and current update on the status of TD-SCDMA and China's overall domestic licensing intentions, <em>see</em> Asakawa, Naoki, <a href="http://techon.nikkeibp.co.jp/article/HONSHI/20070725/136763/">TD-SCDMA: More Standards to Come, Nikkei Electronics Asia</a>, August 2007, at http://techon.nikkeibp.co.jp/article/HONSHI/20070725/136763/</p>
				<p><sup>8</sup> Shortly before China cast its vote in JTC1, several English text articles were released by China's official Xinhua News Agency with titles like <a href="http://english.people.com.cn/90001/90778/90858/90864/6233599.html">Microsoft's 'Monopoly' Comes Under Fire</a>. See Updegrove, Andrew, <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20070817070419313">OOXML, ODF and UOF: What's Up in China?</a>, ConsortiumInfo.org, The Standards Blog, August 17, 2007, and other sources cited therein, at http://www.consortiuminfo.org/standardsblog/article.php?story=20070817070419313.
				<p><sup>9</sup> See Garg, Sachin, <a href="http://www.c10n.info/archives/668">China's AVS Specifications Available</a>, the Data Compression News Blog, September 4, 2007, <em>at</em> http://www.c10n.info/archives/668. According to this entry, implementing the new Chinese standards will be far cheaper than using the western standards: only 13 cents, in comparison to a typical $2.50 license payment per unit based upon MPEG-2 compression technology.</p>
				<p><sup>10</sup> See Yoshida, Junko, <a href="http://www.eetimes.com/news/latest/showArticle.jhtml?articleID=201804774">China Narrows Final Mobile TV Spec to CMMB, TDBM</a>, EETimes, September 7, 2007, <em>at</em> http://www.eetimes.com/news/latest/showArticle.jhtml?articleID=201804774</p>
				<p><sup>11</sup> A current example can be found in the effort that Microsoft is dedicating towards adoption of its OOXML formats by ISO/IEC JTC1, following the earlier adoption of the OASIS OpenDocument Format by the same committee. This is especially significant given the near-total monopoly that Microsoft Office enjoys in the global marketplace.</p>