<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
<style type="text/css">
<!--
.style10 {font-family: Arial, Helvetica, sans-serif; color: #000000; font-size: 16px; font-weight: bold; }
.style2 {font-family: Arial, Helvetica, sans-serif;

	font-size: 12px;
}
-->
</style>
</head>

<body>
<p align="center" class="style10"><strong>THE ROLE OF GOVERNMENT IN ICT STANDARDIZATION</strong></p>
<blockquote>
  <p align="center" class="style10"><font size="2" face="Arial, Helvetica, sans-serif"><strong><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></strong></font></p>
  <table width="436" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
      <td width="436" valign="top" class="style2"><strong><em>Abstract:</em></strong><em>&nbsp;</em><em>Governments interact with standards in many ways: as developers, when they draft regulations; as adopters, when they reference private sector standards in laws and regulations; as influencers, when they exercise their vast procurement powers in the marketplace, and when they send representatives to participate in private sector standard setting organizations; and as end-users, when they utilize standards-based products.  The role that a given government decides to play in relation to standards varies, depending upon the subject matter of the standard, and also among governments, and over time.  To date, governments have not as often acted as developers or adopters in the area of information and communications technologies (ICT) as they have in traditional areas of interest, such as public health and safety.  However, with the redeployment of a vast range of essential services (including government services) over the Internet, the digitization of public records, and the increased use of information technology in the work place, it is incumbent upon governments to reevaluate their relationship to ICT standards, and decide what roles they wish to play in ensuring that standards development and uptake best serves the public interest.  In this article, I seek to facilitate that process, by reviewing the various roles that government can play, using accessibility standards (broadly construed) as an example.</em></td>
    </tr>
  </table>
</blockquote>
<p>&nbsp;</p>
<p class="style2"><strong class="style10"><em>Introduction: </em></strong>Over the last hundred years, a fairly predicable allocation of responsibility for standards has emerged among government and industry.  Typically, government assumes primary responsibility in areas such as health, public safety and ensuring the equality of access to basic rights and opportunities.  When a government acts, it provides laws and regulations defining minimum standards, specifies consequences for failing to meet those standards, and enforces those standards through the courts.  The common theme among these standards is that government generally concerns itself with those areas where the potential harm to the citizen from non-compliance can be  highest. </p>
<p class="style2">Private industry tends to be  most active in what might be considered to be elective standards, or specifications  that are used where the non-commercial stakes are much  lower.&nbsp; For example, the physical  dimensions of a light bulb socket in a lamp, and the gauge of the electrical  wiring in the wall that supplies the current to that lamp, are all physical  standards developed by accredited standards development organizations  (SDOs).&nbsp; Most aspects of the light  socket standard are intended solely to ensure that a light bulb purchased from  one manufacturer can be used in a lamp fabricated by another (an interoperability  standard), and vendors comply with the standard not because they must, but  because it makes good commercial sense for them to do so.&nbsp; In contrast, the gauge standards for the  wiring in a wall have been created (again by SDOs) in order to provide reliable reference points  for determining the load that can be placed on that wiring without generating  dangerous amounts of heat.&nbsp; In the  United States, gauge standards achieve the force of law when they are  incorporated by reference into local building codes from coast to coast.</p>
<p class="style2">Government and industry thus  often work hand in hand, with governments taking advantage of the efforts of  SDOs and unaccredited organizations (consortia) to develop useful and  appropriate standards, and adopting those standards as the reference points for  regulation.&nbsp; As a result, standard  setting organizations that are both accredited as well as unaccredited  (collectively, &quot;SSOs&quot;) fulfill a kind of quasi-public role in  supporting government.&nbsp; This occurs not  only in areas such as health and safety, where governments adopt the standards  that SSOs create, but also in more elective situations, where society benefits  from the development and broad adoption of interoperability and performance  standards for use in less critical areas, and government plays no part at all.</p>
<p class="style2">But where should the lines  be drawn between these three layers of standard setting?&nbsp; How should governments determine when they  should preempt the field entirely (e.g., in setting automotive safety  standards), where they should adopt industry standards (e.g., by incorporating  SSO standards into building codes), and when they should leave everything to  the SSOs themselves (as is the case with almost all information technology  standards)?&nbsp; And how should governments  decide when the boundary lines between those three layers should change, as  technology, societal practices, and other variables evolve over time?</p>
<p class="style2">Moreover, are there limits  that governments should apply to their ability to impose standards?&nbsp; Conversely, are their situations where  governments should use standards, not to protect the populace, but to advance  social agendas, or to encourage certain types of behavior?</p>
<p class="style2">One area where questions  such as these are being asked with increasing frequency may be loosely referred  to as &quot;accessibility,&quot; a domain that  involves a broad array of practices that  until very recently have always involved face to face communications and  paper-based records.&nbsp; Now, these same  communications are increasingly being transacted via the Internet, and the  resulting records are archived in electronic media.&nbsp; This transformation creates enormous opportunities and  efficiencies, but at the same time gives rise to new concerns of significance,  and can exacerbate traditional risks and concerns as well.&nbsp; </p>
<p class="style2">For example, when a doctor  created a typical paper-based record a decade ago, that record existed only in  that physician's file cabinets, except to the extent that she sent a photocopy  to a known recipient, that in turn maintained physical custody of the record,  or destroyed it.&nbsp; Today that same  record, which might contain not only highly confidential medical information,  but also the name, birth date and social security number of the patient, will  likely be created in electronic form on the physician's server (hopefully  protected by a robust firewall), and then rapidly propagate to the servers of a  hospital, a radiologist, an oncologist, an insurance company &ndash; and perhaps  others.&nbsp; Moreover, if the patient needs  urgent medical attention while on a skiing vacation, a doctor in Vail, Colorado  may need immediate, secure access to that same record.&nbsp; Fifty years later, the same data may be  wanted for diagnostic purposes by a descendant of the same patient.</p>
<p class="style2">In this article, I will  review the direct and indirect roles that governments have historically played  in relation to standard setting, and how these roles may relate to the  differing challenges that ICT presents on an ever-evolving basis today.&nbsp;  I will then use the example of accessibility standards to explore what  types of roles government might choose to play in connection with ICT, both from  the traditional perspective of protecting health and safety, as well as in new  or more elective roles related to advancing social agendas.&nbsp; Finally, I will recommend specific actions  that government might take to maximize its effectiveness in these roles.</p>
<p class="style10"><strong>I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Direct Government Involvement</strong></p>
<p class="style2">Governments can influence  the development and uptake of standards in a variety of ways.&nbsp; The following are the most important modes  of engagement that government has traditionally employed.</p>
<p class="style2"><strong class="style10"><em>Procurement:</em></strong>&nbsp; The most  obvious ways that governments can influence standard setting are first, through  its enormous procurement power, and second, through direct participation in  consensus based standards organizations.&nbsp;  In the United States until 1995, the former was by far the  dominant  role at the federal level, with the latter being far less important.&nbsp; Most United States federal government  agencies fulfilled many of their purchasing requirements by requiring that  bidders build to &quot;government unique&quot; specifications.&nbsp; However, these specifications did not  necessarily become adopted outside of the government domain, due to factors  such as differing levels of cost consciousness between the public and private  sectors,  design features that are  unique to government needs, and more rigorous performance requirements  that were not always of equal appeal in the general marketplace. </p>
<p class="style2"> Over  time, the inefficiencies of government unique specifications-based procurement  became  obvious, in comparison to buying products in the open market that  were based upon consensus standards.&nbsp; In  response, Congress decided to both improve its own purchasing practices as well  as bolster the private development of standards through the passage of the National  Technology Transfer and Advancement Act of 1995 (&quot;NTTAA&quot;), which  explicitly promotes voluntary consensus standards for regulation and  procurement by the U.S. government. <a href="#1">1</a> <a href="#_ftn1" name="_ftnref1" title="" id="_ftnref1"> </a>&nbsp;</p>
<p class="style2">  Following  the passage of the NTTAA, Federal agencies were required to use non-government  unique standards whenever possible, and also to actively participate in the  development of those standards. As a result, the long-standing roles of the  federal government came to be reversed.&nbsp;  Thereafter, its specification drafting influence dramatically diminished,  while its level of participation in the consensus standard setting process as  dramatically increased. In 1998, the Office of Management and Budget  (OMB) updated its already issued Circular A-119 to provide additional guidance  to the Federal agencies on implementing the NTTAA.<a href="#_ftn2" name="_ftnref2" title="" id="_ftnref2"> </a> <a href="#2">2</a> </p>
<p class="style2"> Whether  or not the overall impact of the federal government increased, decreased or  stayed the same as a result of the passage of the NTTAA would be difficult to  determine without an empirical study.&nbsp;  On the one hand, procurement of products built to government-unique  specifications dramatically decreased.&nbsp;  On the other hand, government procurement of consensus standards based  products increased by a roughly proportionate amount, and its direct participation in SSOs increased  by orders of magnitude.<a href="#_ftn3" name="_ftnref3" title="" id="_ftnref3"> </a> <a href="#3">3</a> </p>
<p class="style2"> Despite the fact that the  United States federal government now sets standards with far less frequency,  its direct participation and buying power can nevertheless have a significant impact on the  success or failure of a given  standard.&nbsp; For example, when a government  agency adopts a new standard, it can convey additional credibility to that  specification, resulting in broader and more rapid uptake of the standard than  might otherwise occur.<a href="#_ftn4" name="_ftnref4" title="" id="_ftnref4"> </a> <a href="#4">4</a> </p>
<p class="style2"><span class="style10"><strong><em>Legislation:</em></strong>&nbsp;</span> The most  decisive role that a government can play in the standards space is to intervene  by imposing its own standard (i.e., a law or regulation).&nbsp; One would expect that this is most likely result when new technologies replace old ones in areas of traditional  government concern.&nbsp; In the case of ICT,  this has already occurred as legislatures struggle with issues such as spam,  where the analogies to junk mail, junk faxes and telemarketing are obvious and  the legislative precedents are comparatively clear.&nbsp; Similarly, responding to identity theft via the Internet can rely  to a significant extent on earlier decisions based on the theft of credit card  and other data by more traditional means.&nbsp;  But setting laws to control behavior (e.g., by setting criminal  penalties for phishing) is different than intervening to influence the technical  standards that can lower crime by augmenting security (i.e., by making phishing more  difficult).&nbsp; </p>
<p class="style2">Some areas of actual  communications technology (such as radio and televisions frequencies) have been  the subject of domestic regulation (in the United States, via the Federal  Communications Commission, FCC).&nbsp;  Regulation of the multiple new types of wireless standards that are now  regularly emerging therefore arises naturally within existing regimes and  systems.</p>
<p class="style2"><strong class="style10"><em>International treaties:</em></strong>&nbsp; Most  international collaboration on ICT standards occurs through non-governmental  entities, such as the Joint Technical Committee 1 (JTC 1) of ISO and the IEC.&nbsp; But  there are exceptions, such as the International Telecommunication Union (ITU),  a venerable organization with a more than century long history that now  operates as a treaty organization under the auspices of the United  Nations.&nbsp; Participation in the ITU is by  institutional representatives appointed by national governments.&nbsp; </p>
<p class="style2">Treaties can also utilize,  bolster or regulate activity in relation to consensus-based standards.&nbsp; The most powerful example of this activity  is the Agreement on Technical Barriers to Trade (ATBT), enacted under the World  Trade Organization in 1995.&nbsp; Under that  treaty, governments are prohibited (among other restrictions) from using  unreasonable conformance testing or unnecessary national standards as tactics  to impede or prevent the import and sale of foreign products.<a href="#_ftn5" name="_ftnref5" title="" id="_ftnref5"> </a> <a href="#5">5</a></p>
<p class="style10"><strong>II&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Indirect Government Involvement</strong></p>
<p class="style2">Standard setting is time  consuming, and requires expert input.&nbsp;  Some nations (such as China) pursue a so-called &quot;top down&quot;  approach and maintain extensive standard setting infrastructures at the  national level.&nbsp; Others, such as the  United States, rely heavily on the private sector to do the work of prioritizing  projects and designing standards, through a &quot;bottom up&quot; process  utilizing SSOs to  achieve their goals.&nbsp; Among the nations  that follow this approach, greater influence is given to commercial players, resulting  (proponents of this approach believe) in more timely, responsive and effective  standards.&nbsp; An added benefit of this approach is the fact  that tax dollars are saved, because the costs of standards production are  shifted to industry.<a href="#_ftn6" name="_ftnref6" title="" id="_ftnref6"> </a> <a href="#6">6</a> </p>
<p class="style2"><span class="style10"><strong><em>Areas of standards  concern:</em></strong>&nbsp;</span> When a government decides that it will not  set the standards in certain domains that are nonetheless of significance to  policy or traditional governmental roles (I will call them &quot;areas of  standards concern&quot;), many questions arise.&nbsp; From a practical perspective, how should government staff and  maintain expertise and lines of communication in areas in which it does not  have direct involvement?&nbsp; Also, how can  government still influence the standards that are set in those sectors?&nbsp; For nations that prefer the top down  approach, should exceptions to that approach be made, and if so, how will  decisions to do so be made, and by whom?&nbsp; </p>
<p class="style2">For example, if the private  sector is to predominate in areas that are not sufficiently crucial  to warrant  regulation, but are nonetheless significant enough to warrant government concern,  should government intervene if needed standards do not materialize within a  reasonable period of time?&nbsp; If  government does intervene, should it do so as a catalyst to nudge the private  sector into action, or should it preempt the field entirely, developing the  needed standards itself, and then enacting them into law?&nbsp; </p>
<p class="style2">Examples of areas of  standards concern are not hard to find. Three current standards domains in  which government has decided to become more actively involved are first  responder standards, data sharing standards, and electronic healthcare  standards.</p>
<p class="style2"><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;First responder standards:</em></strong>&nbsp;</span> Five and a half years ago, the 9/11 attacks  exposed the tragic lack of effective standards  to permit first responders  to communicate with each other.&nbsp; Multiple  efforts were launched within many SSOs to address this gap.&nbsp; The American National Standards Institute  (ANSI) created the <a href="http://www.ansi.org/standards_activities/standards_boards_panels/hssp/overview.aspx?menuid=3">Homeland  Security Standards Panel</a> in February of 2003 to help coordinate standards  activities in this and related areas with the efforts of the newly formed  Department of Homeland Security.&nbsp; On May  19, 2004, Secretary of Homeland Security Tom Ridge highlighted the lack of appropriate  standards in his <a href="http://www.ansi.org/news_publications/news_story.aspx?menuid=7&amp;articleid=687">testimony  to the 9/11 Commission</a>.<a href="#_ftn7" name="_ftnref7" title="" id="_ftnref7"> </a> <a href="#7">7</a> </p>
<p class="style2">But despite these  activities, enormous gaps remain in the ability of police, fire and other  emergency forces in adjacent communities to communicate effectively when  coordination is essential.</p>
<p class="style2"><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Data sharing standards:</em></strong>&nbsp;</span> The failure of the FBI and the CIA to share  key data has&nbsp; been identified as one  failing that helped to enable the events of 9/11 to occur.&nbsp; In an effort to avoid future lapses in the   integration of intelligence and actions among relevant agencies, a new  cabinet-level agency named the Department of Homeland Security was created to  oversee, and improve coordination between, agencies able to assist in defending  homeland security. </p>
<p class="style2">But inter-agency rivalries  were not the only cause for poor data sharing.&nbsp;  In fact, the federal government maintains information in a very large  number of IT &quot;silos&quot; that have been created through non-coordinated IT  purchasing. The result is  great  difficulty in data sharing among, and even within, individual agencies.&nbsp; An example  of the challenges that result from the historical creation of such disparate  systems can be appreciated from the following elementary data formatting  example:</p>
<blockquote>
  <p class="style2">The task of bridging hundreds of formerly stove-piped systems is  enormous. Every system has its own way of formatting data and defining the  meaning of database terms. For instance, one system may use the term  &quot;FirstName&quot; and another the term &quot;FName&quot; to specify a  person's first name in a database. In other cases, different systems may use an  identical label to represent different data. &quot;CNum&quot; may mean  &quot;case number&quot; in one system and &quot;catalog number&quot; in  another.<a href="#_ftn8" name="_ftnref8" title="" id="_ftnref8"> </a> <a href="#8">8</a> </p>
</blockquote>
<p class="style2"><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;eHealth standards:</em></strong>&nbsp; </span>The enormous costs of medical care have  focused attention on deriving ways to gain efficiencies and cut costs.&nbsp; In December 2003, Congress passed the Medicare Prescription  Drug, Improvement, and Modernization Act, <a href="#9">9</a> <a href="#_ftn9" name="_ftnref9" title="" id="_ftnref9"> </a> under which the Commission on Systemic Interoperability was created, with the  charge of developing a strategy to make healthcare information instantly  accessible at all times, by consumers and their healthcare providers. <a href="#10">10</a> <a href="#_ftn10" name="_ftnref10" title="" id="_ftnref10"> </a>&nbsp; One mechanism adopted to further that goal was the  creation in late 2005 of the Healthcare Information Technology Standards Panel  (HITSP), which operates under a contract administered by the Office  of the National Coordinator for Health Information Technology (ONC).&nbsp; HITSP is administered by ANSI in cooperation  with strategic partners including the Healthcare Information and Management  Systems Society (HIMSS), the Advanced Technology Institute (ATI) and Booz Allen  Hamilton.<a href="#_ftn11" name="_ftnref11" title="" id="_ftnref11"> </a> <a href="#11">11</a> </p>
<p class="style2">As the examples above  demonstrate, government has not hesitated to engage with the standard setting infrastructure through a variety of means  when it became convinced that achieving an ICT standards solution was  important.&nbsp; Regrettably, the examples  given also demonstrate how the progress of such efforts  can be slow indeed, as often as not.</p>
<p class="style10"><strong>III&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ICT Standards and Social Agendas</strong></p>
<p class="style2">Just as governance occurs at  multiple levels (local, state, federal, and to a limited but growing extent,  internationally), the ability to pursue social agendas arise at the  same levels as well.&nbsp; Many of these  agendas could, but thus far usually have not, embraced or utilized ICT  standards, although the opportunities of doing so are increasing.&nbsp; But as our dependency on the Internet and  digitized information continues to increase, it may prove to be difficult or  impossible to advance such agendas at all without using standards as tools.</p>
<p class="style2">As noted above, governments  have begun supporting and influencing the development of ICT standards in new  ways.&nbsp; To date, most such action has  been oriented towards achieving generic technical, as compared to specific  social goals, but the initiatives directed towards eHealth standards noted  above are an example of a turn in this direction.</p>
<p class="style2">Where standards can be shown  to be relevant to achieving identified social goals, how great a departure  would it be for governments to employ them to this purpose?&nbsp; After all, from one perspective, there is a  great deal of vacant space between attending an arcane technical meeting and  (for instance) increasing the value of distance learning for K-12 students.&nbsp; Why should governments consider digging so  deep?</p>
<p class="style2">In truth, this is not as  strange or unusual a concept as it may at first seem.&nbsp; Consider the following examples of government action in one area  that is intended to achieve results in another:</p>
<ul type="disc">
  <li class="style2"><span class="style10"><strong><em>Tax credits, deductions, and other special       provisions:</em></strong>&nbsp;</span> Federal and state tax codes have been       used to influence more types of social goals than could be summarized in a       paper many times the length of this article, from the development of       alternative energy, to supporting tax exempt entities of all kinds, to promoting       home ownership.&nbsp; More locally,       municipalities frequently give tax abatements to provide incentives to       build job-creating facilities in their areas.</li>
</ul>
<ul type="disc">
  <li class="style2"><strong class="style10"><em>Government contracting:</em></strong>&nbsp; Federal       and state regulations have been used to preferentially create opportunities       for minority owned, women-owned, and other types of entities.</li>
</ul>
<ul type="disc">
  <li class="style2"><span class="style10"><strong><em>Loan programs:</em></strong></span>&nbsp; Federal       and state loan, and loan guarantee, programs help provide financing to the       same types of businesses, as well as to support small businesses       generally.</li>
</ul>
<ul type="disc">
  <li class="style2"><span class="style10"><strong><em>Employment</em>:</strong>&nbsp;</span> Affirmative action hiring policies can       be found at many levels of government.</li>
</ul>
<ul type="disc">
  <li class="style2"><span class="style10"><strong><em>Research and development:</em></strong>&nbsp;</span>       Governmental agencies provide billions of dollars of support for       basic research in universities and other venues that is  not directed       at achieving immediate, identified government goals.&nbsp; In contrast, direct economic support by       government in the United States for standard setting activities is almost       non-existent.&nbsp; Indeed,       participation by government representatives in consortia is almost invariably       at discounted rates, as compared with the fees required for participation       by private industry.</li>
</ul>
<p class="style2">In contrast, direct economic support by  government in the United States for standard setting activities is almost  non-existent.&nbsp; Indeed, participation by  government representatives in consortia is almost invariably at discounted  rates, as compared with the fees required for participation by private  industry.&nbsp; As a result, government  participation in consortia is in fact subsidized by the other members of these  SSOs, rather than the reverse.</p>
<p class="style2">Given the above examples, why  should government  not consider utilizing ICT standards to achieve social goals as well, and  dedicate an appropriate amount of resources to that result?&nbsp;&nbsp;  Assuming that the questions of &quot;why&quot; and &quot;whether&quot;  have been addressed adequately, attention should then logically turn to the  questions of &quot;when&quot; and &quot;how.&quot;</p>
<p class="style2"><span class="style10"><strong>IV.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Accessibility  standards</strong></span></p>
<p class="style2">One area where government interest in ICT  standards would be particularly apt falls under the category of  &quot;accessibility,&quot; broadly defined.&nbsp;  Increasingly, the ability to use all functions of whatever computer  system (operating system, browser and applications) an individual citizen may  own or have access to in order to utilize the Internet is becoming essential to  virtually all aspects of modern life.&nbsp;  Not only is this true with respect to managing one's personal affairs,  but also to obtain information from, and interact with, government as well.&nbsp; Similarly, gaining access to the job market  on an equal basis with others increasingly requires the ability to utilize  ICT.&nbsp;</p>
<p class="style2"> In short, a person is severely  impacted in living in a modern first-world country if she does not have access  to, and the physical ability to use, ICT of many types.&nbsp;  For someone in the third world, the inability to access or use such  technology may foreclose  the only available hope of benefiting from the broader  opportunities of the wider world.</p>
<p class="style2">To date, many governments  have been largely uninvolved in such questions, even where there are clear analogs  to traditional government action.&nbsp;  Consider from this perspective the following differential examples  between the regulation of ICT practices and other types of conduct.</p>
<p class="style2"><span class="style10"><strong><em>Access for those with disabilities:</em></strong>&nbsp;</span> In the  United States, buildings with public access are subject to federal and state  rules intended to ensure that those with disabilities can enter, pass between  floors, and use essential services such as rest rooms, all without undue  difficulty. <a href="#12">12</a> <a href="#_ftn12" name="_ftnref12" title="" id="_ftnref12"> </a>&nbsp; In contrast, there has thus far been little  legislation or court action directed at ensuring that those with disabilities  will not be the subject of discrimination and unequal opportunity when it comes  to utilizing ICT to access essential information, services and opportunities.&nbsp; Indeed, governments themselves have  sometimes been slow to assign a high priority to accessibility in their  procurement of ICT for use by their own employees.&nbsp; The following are examples of recent events that highlight the  evolution of thought in this area:</p>
<p><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Procurement:</em></strong>&nbsp;</span> <span class="style2">In Massachusetts,       the most significant argument leveled against adoption of a rule requiring       the procurement of products supporting the OpenDocument Format (ODF) was       that such products did not provide the same degree of accessibility for       those with disabilities as Microsoft Office.&nbsp; This charge was acknowledged by the Information Technology       Division (ITD), and a variety of efforts were mounted in cooperation with       leaders of the community of the disabled to address the issue.&nbsp; As a result of these actions and the efforts       of private sector developers, Massachusetts was able to meet its       originally planned conversion date (January 1, 2007) and begin deploying       ODF-compliant software, using &quot;plug ins&quot; to permit those with       disabilities to continue to use Office until ODF-compliant products had       closed the accessibility gap with their Microsoft product complements.<a href="#13">13</a></span></p>
<p><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</em></strong><span class="style10"><strong><em>Private       industry:</em></strong></span>&nbsp;<span class="style2"> In February of 2006, the National       Federation of the Blind brought suit in California against retail giant       Target Corporation, charging that Target.com Web pages did not support       available accessibility standards.&nbsp;       As a result, the blind could not successfully make purchases at the       Target Website, because (for example) images could not be identified and       described using screen reader software, nor could a purchase be completed       without the use of a mouse.&nbsp;&nbsp; The       suit was brought under the California Unruh Civil       Rights Act, the California Disabled Persons Act and the federal Americans       with Disabilities Act, and immediately commanded nationwide       attention.&nbsp; Not long after, a       Federal District Court judge denied Target's motion to dismiss, holding       that such a suit could be properly brought under existing law.&nbsp; <a href="#14">14</a></span></p>
<p class="style2">The prospect of widespread liabililty  for inaccessbility of Websites may seem novel in the abstract, but in fact the  World Wide Web Consortium (W3C) has already created a variety of standards that can be  implemented to bring Websites to a greater level of accessibility &ndash; either  voluntarily, or perhaps with time, as a result of government regulation.<a href="#_ftn15" name="_ftnref15" title="" id="_ftnref15"> </a><a href="#15">15</a> </p>
<p class="style2">Will specific regulations be required  to ensure appropriate Web accessibility?&nbsp;  Using the United States as an example, the Target case is of special  interest, as the plaintiffs brought suit under existing anti-discrimination  laws, and the judge in the Federal District Court in which the case  is being tried has, as a preliminary finding, concluded that this is appropriate.&nbsp; Accordingly, it may be that existing laws  may prove adequate to the task.&nbsp; </p>
<p class="style2">On the other hand, reaching ultimate  certainty in that regard can take years, if different courts reach different  conclusions.&nbsp; If that occurs, it would  require action by the Supreme Court to ultimately resolve such inconsistencies  &ndash; which it could decline to do for some time.&nbsp;  Even if the Supreme Court were to intervene, it may choose to limit its  holdings to the specific facts and issues presented, which might or might not  prove to be dispositive on broader questions.</p>
<p class="style2">As a result, action by Congress could  serve to shortcut the process by conclusively amending existing laws to provide  specific guidance, or by passing new laws extending current protections to  relevant ICT-based settings.</p>
<p class="style2"><span class="style10"><strong><em>Technical Accessibility:</em></strong>&nbsp; </span>Prior to the ICT revolution, government  facilities and information were available to all, either by visiting or calling  a government office, or by writing to the government and requesting  information.&nbsp; In each case, the means to  do so (whether they be public transportation, the mails or the telephone) were  available to all.&nbsp; But with government  enthusiastically embracing the Web, new questions arise, such as what  obligation governments should have to make their information and services  available to all, regardless of the technical platform and applications that  citizens may choose to use?</p>
<p class="style2">The most common questions that arise in  this area involve browsers and text applications.&nbsp; Government Web sites that provide information that can only be  read easily (or at all) in Internet Explorer (and not, for example, Firefox), or opened in  Word (and not Apple applications or ODF-compliant software) provoke angry  responses from happy users of those products.&nbsp;  When the information in question is vital and needed on an urgent basis  &ndash; as occurred following the Katrina disaster on the Gulf Coast of the United  States - this question transcends convenience, and goes to the core of a  government's responsibilities to its citizens.</p>
<p class="style2"><span class="style10"><strong><em>Document Accessibility:</em></strong>&nbsp;</span> The decision of the Massachusetts ITD to  adopt ODF (and not the Microsoft OfficeOpen XML format, also known as OOXML) in  August of 2005 immediately brought the question of long-term accessibility of  documents before the public eye.&nbsp; At the  heart of the matter was the responsibility of government to ensure that public  records should be available not only in the near term, but over long periods of  time, regardless of whether the proprietary products in which they were  originally created maintain backwards compatibility, or remain in existence at  all.</p>
<p class="style2">Following the ITD's decision, a variety  of state, local and federal governments around the world took up the issue, and  an increasing number of governments and others are either investigating, or  have already moved to purchase or require ODF-compliant products. <a href="#16">16</a> <a href="#_ftn16" name="_ftnref16" title="" id="_ftnref16"> </a>&nbsp; The level of government interest in ODF has  been augmented in part by the formation of an organization called the <a href="http://www.odfalliance.org/mission.php">ODF Alliance</a>, which was  formed for the specific purpose of educating policy makers about ODF, and  promoting its uptake. <a href="#17">17</a> <a href="#_ftn17" name="_ftnref17" title="" id="_ftnref17"> </a>&nbsp; The Alliance was announced on March 3, 2006,  with 36 founding members.&nbsp; As of the date of this  writing, its membership has swelled to several hundred members around the  world, including government representatives at all levels, non-profits, open  source software organizations, corporations, and others.</p>
<p class="style2"><span class="style10"><strong><em>International equality of access:</em></strong>&nbsp;</span> The ability to gain access to the  Internet and the Web (and with the ever-expanding  data density of interactive Web  content, broadband access) is becoming increasingly significant on a national  as well as an individual basis.&nbsp; In  part, such access is a matter of national investment and priority setting, but  it is also a matter of international action (or inaction) as well: large  sections of Africa, for example, cannot yet gain broadband access, because the  international fiberoptic cables needed to provide it have not yet been laid.<a href="#_ftn18" name="_ftnref18" title="" id="_ftnref18"> </a>&nbsp; <a href="#18">18</a> </p>
<p class="style2">Accessibility issues are not uniquely the  province of  national governments, however.&nbsp;  Globally, an entirely different set of issues comes into play, some of  which are infrastructural, and some of which are uniquely standards-dependent.&nbsp; The following are standards-based examples  of ways in which international commercial and government collaboration are  needed in order to ensure provision of equal access to all citizens of the  world:</p>
<p><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Domain name support:</em></strong>&nbsp; </span><span class="style2">The allocation of domain       names and the control of the root directories of the Internet has been a       topic of heated discussion almost from the creation of the Internet       Corporation for Assigned Names and Numbers (ICANN).&nbsp; While the root directories are       insignificant in size, they offer the technical ability to literally turn       off a country's access to the Internet.&nbsp;       Similarly, ICANN plays a role in deciding how many unique Website       addresses are available to any given nation.<a href="#19">19</a> </span></p>
<p><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</em></strong><span class="style10"><strong><em>Character support:</em></strong>&nbsp; </span><span class="style2">Information that is entered       in one character set needs to be convertible into other character sets in       order for that data to be exchanged internationally without       limitation.&nbsp; At the most basic       level, all currently utilized written languages must be supported by the       infrastructure of the Internet in order to guarantee equal access to       all.&nbsp; This need is particularly       acute at present, given that the great majority of data currently on-line has       been input in first-world langauges, and in particular in English.&nbsp; In order to permit full academic and       historical collaboration, the character sets of archaic languages (e.g.,       Babylonian) must be digitized as well.&nbsp;       One of the great unsung teams of heros of the Internet labors for       the relatively unknown Unicode Consortium, which has worked for years to       accomplish the Herculean task of digitizing all existing and historical       character sets. <a href="#20">20</a> </span></p>
<p><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</em></strong><span class="style10"><strong><em>Language support:</em></strong>&nbsp;</span> <span class="style2">Like countries (which are identified by       three letter codes under a standard maintained by ISO), languages need       identifiers as well.&nbsp; And like       character sets, codes are needed for lost languages as well as for those       that are spoken today.&nbsp; Or, as       described by the registrar of ISO 639-3, <em>Codes for the representation of names of languages,</em> &quot;ISO 639-3 attempts to provide as complete       an enumeration of languages as possible, including living, extinct,       ancient, and constructed languages, whether major or minor, written or       unwritten.&quot;<a href="#_ftn21" name="_ftnref21" title="" id="_ftnref21"> </a>&nbsp; <a href="#21">21</a> These codes are used, among other       purposes, for specifying languages at Websites, identifying interpreter       needs, and for research cross checking.&nbsp;       The latest revision of ISO 639-3 (released in February of 2007)       increased support from just 478 languages to 7,546 &ndash; although this number       is still short of the ultimate goal.</span></p>
<p class="style10"><strong>V&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Future</strong></p>
<p class="style2"> Representative governments, being the servants rather  than the masters of their citizens, tend to be reactive rather than proactive  by nature.&nbsp; It is therefore hardly  surprising that governments have not yet given great attention to the new  realities and challenges of ICT at the level of the standards that in part  enable these technologies.&nbsp; But as the  importance of ICT increases and public interest groups take ever-greater notice  of this reality, government will need to be increasingly knowledgeable about  the role of ICT standards, and the mechanisms by which they are created.</p>
<p class="style2"> How should government react to this anticipated  reality?&nbsp; And should its reaction be  different when using standards to advance social policy, as compared to  technical, goals?</p>
<p class="style2"><span class="style10"><strong><em>Areas of standards concern:</em></strong>&nbsp;</span> Using the examples already explored in this  article, here are some of the situations that government will need to  consider:</p>
<p class="style2"><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Document formats:</em></strong>&nbsp;</span> There are billions of electronic documents  in existence today, some of which are no longer easily accessible due to  abandonment of the applications in which they were created. What guarantee will  there be that documents created today will be accessible tomorrow, and what  role should governments play in achieving that goal?&nbsp; More specifically:</p>
<ul>
  <li class="style2"><strong class="style10"><em>Procurement:</em></strong>&nbsp; Should government limit its own procurement to applications that  support open standards in order to provide greater incentives for such  standards to be created? If so, should this policy be applied in some, or all  situations?&nbsp; </li>
  <li class="style2"><span class="style10"><strong><em>Social policy:</em></strong>&nbsp;</span> Should governments concern themselves only with their own  information needs, or should they take an interest in the long-term  accessibility of information generally, and therefore seek to influence the  behavior of information users generally?&nbsp; </li>
  <li class="style2"><span class="style10"><strong><em>Public accessibility:</em></strong>&nbsp;</span> What document formats should governments  make available to its citizens?&nbsp; Does  supporting a proprietary format represent an endorsement of that format and its vendor-owner?&nbsp; Does the failure by a government to  support a format fail that portion of the citizenry that utilizes that  format?&nbsp; How can such concerns be  balanced with economic and other resource issues?</li>
</ul>
<p class="style2"><strong class="style10"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Accessibility for those  with disabilities:</em></strong>&nbsp; Clearly, ICT  accessibility is of crucial and increasing importance to full participation in  society.&nbsp; But how should governments  respond to this emerging reality?&nbsp;  Consider the following questions:</p>
<ul>
  <li class="style2"><span class="style10"><strong><em>Analogs:</em></strong></span>&nbsp;  Are ICT accessibility issues different in meaningful, as compared to  simply mechanical, ways from their analogs in the physical world?&nbsp; If they are not, then existing laws may  serve to meet the need.&nbsp; If they are in fact different,  then amendments to existing laws, and/or new laws, will be needed.</li>
  <li class="style2"><span class="style10"><strong><em>Cost/benefit ratios:</em></strong>&nbsp;</span> Are the costs associated with accommodating  the needs of those with disabilities in the virtual, as compared to the  physical world, significant (in either direction)?&nbsp; If so, should this indicate the need for any differences in laws or  penalties?</li>
  <li class="style2"><span class="style10"><strong><em>Coverage:</em></strong>&nbsp;</span>  Should ICT-related standards requirements be more broad or narrow in  their coverage than existing laws?</li>
  <li class="style2"><strong class="style10"><em>Responsibilities:</em></strong>&nbsp; Who should create the standards upon which  ICT-related regulations  rely?&nbsp;  Should they be regulators, SDOs, or any SSO with domain expertise?</li>
</ul>
<p class="style2"><strong class="style10"><em>Issues of standards concern:&nbsp; </em></strong>In addressing areas of standards  concern, subsidiary issues will also need to be considered, including the  following:</p>
<p class="style2"><span class="style10"><strong><em>Definitions</em></strong>: </span>If  governments are to take greater interest in standards, what type of standards  should they find to be acceptable?&nbsp; This  gives rise to additional questions:</p>
<ul>
  <li class="style2"><span class="style10"><strong><em>&quot;Open standards:&quot;</em></strong>&nbsp;</span> Current government procurement law in the  United States, as codified in OMB Circular A-119, favors the use of widely  adopted standards, but does not state a  preference between those adopted  by stringent consensus processes and those specifications that become <em>de  facto</em> standards purely as a result of wide usage.&nbsp; Should only standards that meet certain threshold requirements of  process, lack of proprietary control, or other criteria be used for certain  purposes, and if so, which purposes? If so, what should the requirements be,  given that opinions vary widely on what an &quot;open standard&quot; should  mean?</li>
  <li class="style2"><span class="style10"><strong><em>Uniformity:</em></strong>&nbsp;</span> If every state and national government were to adopt its own  definition of an open standard, it would defeat the purpose of having standards  at all, since vendors would simply not bother to meet so many disparate requirements,  other than in the non-elective case of procurement &ndash; with the result that  governments would simply be reverting to the use of &quot;government unique  specifications.&quot;<a href="#_ftn22" name="_ftnref22" title="" id="_ftnref22"> </a> <a href="#22">22</a> </li>
</ul>
<p class="style2"><span class="style10"><strong><em>Standards infrastructure:</em></strong>&nbsp;</span> If governments conclude that ICT standards  are of increasing significance to the public interest, how can they ensure that  an adequate and timely supply of such standards is available, without  undertaking to develop such standards themselves?&nbsp;  And under what criteria should SSOs be differentiated, if at all?</p>
<p class="style2"> The traditional standards infrastructure evolved  around national standards bodies that created standards that were in turn  adopted by quasi-governmental, global standards organizations.&nbsp; However, in information technology, most  standards are set by non-accredited rather than accredited organizations, and  in communications technology the number is increasing as well.&nbsp; </p>
<p class="style2"> Historically, many governments  around the world have preferred, or required, the use of standards approved by  global standards bodies, such as ISO and IEC.&nbsp;  Happily, ISO/IEC JTC 1 offers the Publicly Available Standards (PAS)  process as an avenue for consortium-based standards to advance to approval as  ISO/IEC standards.&nbsp;&nbsp; But given that  consortia are usually global in membership to begin with, is there a need for a  second layer of global approval that adds time and effort, but may or may not  add additional quality control?</p>
<p class="style2"><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Representation:</em></strong>&nbsp; </span>The accredited standards world espouses  equality of access to all stakeholders in the standards process.&nbsp; However, that ideal is often hard to achieve  in practice, due to the time and resources needed to participate in the  standard setting process.&nbsp; Lack of  consumer interest can provide a challenge to broad representation of  stakeholders as well.&nbsp; If standards are  to be used to further social agendas, should some greater level of attention be  given to  achieving broader participation in SSOs?&nbsp; Or perhaps some other form of safeguard is  needed to vet standards at the legislative level?</p>
<p class="style2"><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Certification:</em></strong>&nbsp;</span> If ICT standards become more legally significant,  a greater need will arise for effective certification of compliant  products.&nbsp; However, as a generalization,  compliance with information technology standards is less frequently, and less  stringently, tested than compliance with other types of products where (for  example) safety is a concern.&nbsp; This is  in part due to lack of demand, and in part due to the high costs of creating  industrial strength compliance tests relative to the funds that vendors are  willing to invest in standards-related collaborative activities. <a href="#23a">23</a> &nbsp; If compliance becomes a legal necessity,  then testing and certification will become more important.&nbsp; The costs of such added activities will  presumably impact product prices.</p>
<p class="style2"><strong class="style10"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Funding:</em></strong>&nbsp; Standards development, conformity assessment  and participation costs in the United States are currently borne almost  entirely by SSO participants and vendors.&nbsp;  If governments that endorse the bottom up process want non-profits and  the public sector to continue to provide needed standards, then such  governments should consider whether some measure of public funding should be  supplied to help support this process.</p>
<p class="style10"><strong>VI&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Summary  and Recommendations</strong></p>
<p class="style2"><strong class="style10"><em>Summary:</em></strong>&nbsp;  Ensuring that appropriate ICT standards are available to meet the needs  of modern society, and that those standards are in fact adopted, is a  legitimate (and perhaps overdue) area of concern for governments to  consider.&nbsp; While private industry may in  many, or even most, respects voluntarily act to provide the standards needed,  it does not necessarily follow that this will occur in all cases, or as quickly  as may be needed, or in as effective a fashion as may be needed to achieve  appropriate social goals.<br />
ICT &quot;areas of standards concern&quot; are many,  including eHealth, homeland security, accessibility, public records, emergency  response, and much more.&nbsp; Moreover,  standards-related work and regulations that have already been accomplished in  the physical world must now be replicated in the virtual world.&nbsp; This task needs to be informed by, but not  limited to, using the existing body of laws, regulations and standards and the  decisions underlying them as guidance.&nbsp;  Where necessary, amending old regulations, and in some cases, the  passage of new laws or the launching of new programs will likely be necessary.</p>
<p class="style2"><span class="style10"><strong><em>Recommendations:</em></strong>&nbsp;</span> As a result, federal, state, and local  governments should reevaluate what their roles and responsibilities in relation  to ICT standardization should be.&nbsp; The  following recommendations are intended to assist in embarking upon such a  study.</p>
<p class="style2"><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Recognition:</em></strong>&nbsp;</span> Governments should affirmatively recognize  the importance of ICT standards in many areas, including ensuring full  participation in, and access to government, and achieving equality of  opportunity in education and employment.</p>
<p class="style2"><span class="style10"><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Public records:</em></strong>&nbsp;</span> Governments should ensure that all public  records are created, available, and archived in formats that ensure, to the  greatest extent possible, practical long-term preservation and access.</p>
<p class="style2"><strong class="style10"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Competence:</em></strong>&nbsp; Legislators, regulators and Congressional  and agency staff need to be aware of ICT technologies, realities and  needs.&nbsp; Existing government resources  may not be adequate to this task.&nbsp;  Increased funding for the National Institute of Standards and Technology  (NIST), relevant Congressional subcommittees and personnel in some agencies may  be needed in order to properly support decision makers and administrators.</p>
<p class="style2"><strong class="style10"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Infrastructural support:</em></strong>&nbsp; Virtually no money trickles from the top  down to support the bottom up standards development process upon which US  society and commerce depends today.&nbsp; A  small amount of funding could have very significant impact, if directed at  discrete projects, such as funding testbeds upon which standards can be based, the creation of best practices, and other inexpensive projects.</p>
<p class="style2"><strong class="style10"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Underwriting certification  testing:</em></strong>&nbsp; Conducting  certification tests can provide revenues to SSOs, but only after the test  suites upon which the tests are based have been funded and created.&nbsp; A modest &quot;evergreen&quot; fund (perhaps  $40 million) could provide low-interest loans to SSOs that could be used to  create test suites.&nbsp; The loans could  then be repaid, using profits derived from certification testing using the test  suites so created.</p>
<p class="style2"><strong class="style10"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</em></strong><strong class="style10"><em>Standards availability:</em></strong>&nbsp; Consortia charge high membership feels and  make their standards available for free, while SDOs charge less to participate,  and sell their standards.&nbsp; Where the input  of consumers&nbsp; and/or the availability of  standards without charge is important to the public interest, government should  consider a process whereby an SSO could apply for offsetting funds, in order to  allow consumers and others to participate in consortia without charge, and to  make SDO standards available without cost.</p>
<p class="style2"><strong class="style10"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Open standards definition:</em></strong>&nbsp; A common definition of open standards should  be developed that would ideally be used by all governments, both federal and  state, for procurement and social agenda purposes.&nbsp; This would enable vendors to efficiently create and support  standards processes that meet the common definition.&nbsp; Such a definition should be high-level and not detailed, to avoid  gratuitous and harmful restriction on flexibility where flexibility is needed,  and should be agnostic as to nature of SSO (i.e., accredited or nonaccredited),  so as not to exclude the consortia that set the majority of ICT standards. </p>
<p class="style2"> The list of recommendations is hardly exhaustive of the actions  that governments should consider.&nbsp; But  it should be sufficient to facilitate the commencement of a dialogue on that  topic.&nbsp; Hopefully, such a discussion  among interested parties may be launched in the not too distant future. </p>
<p class="style2"><a href="/subscribe/"><img src="/images/subscribe-csb.gif" alt="subscribe" width="130" height="25" border="0" /></a></p>
<p align="center" class="style2"><em>Comments? </em> Email: <script language="javascript" type="text/javascript">AuConAdd();</script></p>
<p align="center" class="style2"> Copyright 2007 Andrew Updegrove </p>
<p class="style2"><strong>End Notes</strong></p>
<div>
  <div class="style2" id="ftn1"><br />
  <a href="#_ftnref1" name="_ftn1" title="" id="_ftn1"> </a> <a name="1" id="1"></a>1. National  Technology Transfer and Advancement Act of 1995, 15 U.S.C. &sect; 3701 (1995). </div>
  <div id="ftn2">
    <p class="style2"><a name="2" id="2"></a><a href="#_ftnref2" name="_ftn2" title="" id="_ftn2"> </a> 2. OMB,  Federal Participation in the Development and Use of Voluntary Consensus  Standards and in Conformity Assessment Activities, Circular A-119, Revised  (Feb. 10, 1998),<em> available at </em>&lt;<a href="http://www.whitehouse.gov/OMB/circulars/a119/a119.html" target="_off">http://www.whitehouse.gov/OMB/circulars/a119/a119.html</a>&gt;.</p>
  </div>
  <div id="ftn3">
    <p class="style2"><a name="3" id="3"></a><a href="#_ftnref3" name="_ftn3" title="" id="_ftn3"> </a> 3. In  that regard, it is worth noting that while government participation in  consortia and SDOs has increased, government agencies rarely if ever join a consortium  at the higher and more influential levels of membership that usually control  strategy.&nbsp; Even when government  representatives do take board seats, they frequently abstain from voting. </p>
  </div>
  <div id="ftn4">
    <p class="style2"><a name="4" id="4"></a><a href="#_ftnref4" name="_ftn4" title="" id="_ftn4"> </a>4. An  excellent current example is provided by the near-contemporaneous announcement  by both Wal-Mart and the United States Department of Defense that each would  require certain of its suppliers to adopt and deploy RFID technology in their  deliveries.&nbsp; For more on the recent evolution  of United States government standards policy, <em>see</em> Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/jan05.php#feature">A Work in  Progress: Government Support for Standard Setting in the United States: 1980 &ndash;  2004,</a> ConsortiumInfo.org, Consortium Standards Bulletin, Vol. IV, No. 1,  January 2005, at &lt;  http://www.consortiuminfo.org/bulletins/jan05.php#feature&gt;, and sources  cited therein.</p>
  </div>
  <div id="ftn5">
    <p class="style2"><a href="#_ftnref5" name="_ftn5" title="" id="_ftn5"> </a> <a name="5" id="5"></a>5. The text  of the ATBT can be<a href="http://www.wto.org/english/docs_e/legal_e/17-tbt_e.htm"> found</a> at  &lt; http://www.wto.org/english/docs_e/legal_e/17-tbt_e.htm &gt; (accessed  March 3, 2007).&nbsp; For more on the WTO's  activities to prevent technical barriers to trade, see its <a href="http://www.wto.org/english/tratop_e/tbt_e/tbt_e.htm">activity page</a> on  that topic, and the many links and resources that can be accessed there, at  &lt;http://www.wto.org/english/tratop_e/tbt_e/tbt_e.htm&gt; (accessed March 3,  2007).</p>
  </div>
  <div id="ftn6">
    <p class="style2"><a href="#_ftnref6" name="_ftn6" title="" id="_ftn6"> </a> <a name="6" id="6"></a>6. Where, of  course, they are passed on to consumers and other end-users.&nbsp; The net result is therefore that the costs  are not avoided by taxpayers, but simply reallocated through a different  formula.&nbsp; The top-down vs. bottom-up  debate is long-standing and energetic.&nbsp;  For a discussion of the two philosophies, as manifested by the United  States and China, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/apr05.php#trends">Top Down, or  Bottom Up?&nbsp; A Tale of Two Standards  Systems</a>, ConsortiumInfo.org, Consortium Standards Bulletin, Vol. IV, No. 4,  April 2005, at &lt; http://www.consortiuminfo.org/bulletins/apr05.php#trends&gt;.&nbsp; A recent example of the approach in action  with respect to a single product area is provided by the paths taken to develop  and deploy cellular phone technology.&nbsp;  In Europe, a &quot;top down&quot; approach led to the early adoption of  a single standard that came to be adopted almost everywhere in the world  (except in the United States), providing seamless geographic services to those  using phones compliant with the resulting GSM standard.&nbsp; In the United States, a market driven  approach led to competing standards and near-term incompatibilities between  carriers, but also to the eventual adoption of a standard that some believe to  be technically superior to the GSM standard.&nbsp;  The cellular phone example has been widely examined from this perspective.&nbsp; For an alternative view of the same history  &ndash; contending that results are more likely to be based upon openness of  architecture &ndash; see Rice, John and Galvin, Peter, <a href="http://www-i4.informatik.rwth-aachen.de/%7Ejakobs/siit99/proceedings/Rice.doc">The  Development of Standards in the Mobile Telephone Industry and Their Effect on  Regional Industry Growth</a>,2000, at  &lt;http://www-i4.informatik.rwth-aachen.de/%7Ejakobs/siit99/proceedings/Rice.doc&gt;.</p>
  </div>
  <div id="ftn7">
    <p class="style2"><a href="#_ftnref7" name="_ftn7" title="" id="_ftn7"> </a><a name="7" id="7"></a>7.  American National Standards Institute, <em><a href="http://www.ansi.org/news_publications/news_story.aspx?menuid=7&amp;articleid=687">9-11  Commission Hearing Calls for Standards in Areas of Emergency Response</a>,</em> May 19, 2004, at  &lt;http://www.ansi.org/news_publications/news_story.aspx?menuid=7&amp;articleid=687&gt;. </p>
  </div>
  <div id="ftn8">
    <p class="style2"><a href="#_ftnref8" name="_ftn8" title="" id="_ftn8"> </a> <a name="8" id="8"></a>8. Kurlander, Neil. <a href="http://xml.sys-con.com/read/175403.htm"><em>Out of Step - NIEM and N-DEx:&nbsp; Two national data-sharing initiatives face  major challenges</em></a>.&nbsp;  XMLJournal.com, January 25, 2007 at &lt;  http://xml.sys-con.com/read/175403.htm&gt; (accessed February 27, 2007).  Efforts are ongoing to bridge the gaps between these islands of data.&nbsp; Two initiatives discussed in the same  article are the National Information Exchange Model (NIEM) and the National  Data Exchange (N-DEx).</p>
  </div>
  <div id="ftn9">
    <p class="style2"><a href="#_ftnref9" name="_ftn9" title="" id="_ftn9"> </a><a name="9" id="9"></a>9. <a href="http://frwebgate.access.gpo.gov/cgi-bin/getdoc.cgi?dbname=108_cong_bills&amp;docid=f:h1enr.txt.pdf">Law  No. 108-173, 117 Stat. 2066</a>.&nbsp; The full  text of the Act can be found at &lt;  http://frwebgate.access.gpo.gov/cgi-bin/getdoc.cgi?dbname=108_cong_bills&amp;docid=f:h1enr.txt.pdf&gt;  (accessed March 3, 2007).</p>
  </div>
  <div id="ftn10">
    <p class="style2"><a href="#_ftnref10" name="_ftn10" title="" id="_ftn10"> </a> <a name="10" id="10"></a>10. On  October 28, 2005, the Commission announced the release of a report, making many  standards and certification based recommendations, titled <em>Ending the  Document Game: Connecting and Transforming Your Healthcare Through Information  Technology</em>.&nbsp; These recommendations  may be found at &lt; http://endingthedocumentgame.gov/report.html&gt;, and the <a href="http://endingthedocumentgame.gov/report.html">complete report</a> at &lt;  http://endingthedocumentgame.gov/report.html&gt;</p>
  </div>
  <div id="ftn11">
    <p class="style2"><a href="#_ftnref11" name="_ftn11" title="" id="_ftn11"> </a> <a name="11" id="11">11. </a>On January 23, 2007, U.S. Department of Health and Human Services (HHS)  Secretary Michael O. Leavitt announced his acceptance of thirty (30) consensus  standards recommended by HITSP.&nbsp; <em>See: <a href="http://www.ansi.org/news_publications/news_story.aspx?menuid=7&amp;articleid=1413&amp;source=whatsnew020507">HHS  Secretary Leavitt Accepts Recommendations from Healthcare Information  Technology Standards Panel (HITSP)</a></em>, ANSI.org,  January 25, 2007 at  &lt;http://www.ansi.org/news_publications/news_story.aspx?menuid=7&amp;articleid=1413&amp;source=whatsnew020507&gt;  (accessed February 27, 2007).</p>
  </div>
  <div id="ftn12">
    <p class="style2"><a href="#_ftnref12" name="_ftn12" title="" id="_ftn12"> </a> <a name="12" id="12"></a>12. Building  owners were not as a rule required to upgrade their facilities upon the passage  of these laws.&nbsp; However, modifying such  a &quot;grandfathered&quot; structure subjected the building to the upgrading requirement,  and all new buildings subject to these laws are required to comply with  accessibility regulations at the time of completion.</p>
  </div>
  <div id="ftn13">
    <p class="style2"><a href="#_ftnref13" name="_ftn13" title="" id="_ftn13"> </a> <a name="13" id="13"></a>13. While  ODF-compliant products were justifiably criticized by members of the community  of the disabled when the ITD announced its initial support of ODF 1.0 in 2005,  that situation had changed dramatically by February 2007, due to actions taken  by OASIS working groups, the ITD, and the developers of the plugin software, as  reported in the February 13, 2007 OASIS press release announcing the adoption  of ODF version 1.1.&nbsp; See, <a href="http://xml.coverpages.org/OpenDocumentV11-Announce200702.html">OpenDocument  Version 1.1 an OASIS Standard</a>, at  &lt;http://xml.coverpages.org/OpenDocumentV11-Announce200702.html&gt;.</p>
  </div>
  <div id="ftn14">
    <p class="style2"><a href="#_ftnref14" name="_ftn14" title="" id="_ftn14"> </a> <a name="14" id="14"></a>14. National  Federation for the Blind v. Target Corporation, Northern District of California Case No. C 06-01802  MHP.&nbsp; The order can be <a href="http://www.dralegal.org/downloads/cases/target/062_order_deny_PI_grant_part_MTD.txt">found</a> at &lt; http://www.dralegal.org/downloads/cases/target/062_order_deny_PI_grant_part_MTD.txt&gt;.&nbsp; An overview, the complaint, a press release,  and other information can be found at the NFB's Website at <a href="http://www.dralegal.org/cases/private_business/nfb_v_target.php">this page</a>:&nbsp; &lt;  http://www.dralegal.org/cases/private_business/nfb_v_target.php&gt;. </p>
  </div>
  <div id="ftn15">
    <p class="style2"><a href="#_ftnref15" name="_ftn15" title="" id="_ftn15"> </a> <a name="15" id="15"></a>15. The <a href="http://www.w3.org/WAI/">W3C Accessibility Initiative Web page</a> can be  found at: &lt; http://www.w3.org/WAI/&gt;.</p>
  </div>
  <div id="ftn16">
    <p class="style2"><a href="#_ftnref16" name="_ftn16" title="" id="_ftn16"> </a><a name="16" id="16"></a>16.  In  response to the growing interest in ODF by governments, particularly in Europe,  Microsoft announced in the fall of 2005 that it would contribute the OOXML  specification to Ecma, a European standards organization.&nbsp; ODF (originally developed by OASIS, a  consortium) was preliminarily approved by ISO/IEC in May of 2006, and became an  official standard later the same year.&nbsp;  Meanwhile, OOXML was approved by Ecma in early December, becoming  Ecma-376, and weighing in at over 6,000 pages (in contrast to ODF's c. 800  pages).&nbsp; As this article is being  written, Ecma-376 is under consideration by the ISO/IEC JTC 1 under the  &quot;Fast Track&quot; process.&nbsp; For  much more on the competition between ODF and OOXML, see the September 2005  issue of the Consortium Standards Bulletin, titled <a href="http://www.consortiuminfo.org/bulletins/sep05.php">Massachusetts and  OpenDocument:&nbsp; The Commonwealth Leads  the Way</a> (Updegrove, Andrew, Vol. IV, No. 9), at &gt;  http://www.consortiuminfo.org/bulletins/sep05.php&gt;, and the many blog  entries that can be found in the <a href="http://www.consortiuminfo.org/standardsblog/index.php?topic=20051116124417686">OpenDocument  file</a> at Updegrove, Andrew, ConsortiumInfo.org, <a href="http://www.consortiuminfo.org/standardsblog">The Standards Blog</a>,  September 17, 2005 to date, at &lt; http://www.consortiuminfo.org/standardsblog/index.php?topic=20051116124417686&gt;.&nbsp; Links to virtually all primary resources can  be found in these blog entries.</p>
  </div>
  <div id="ftn17">
    <p class="style2"><a href="#_ftnref17" name="_ftn17" title="" id="_ftn17"> </a><a name="17" id="17"></a>17.  The  mission of the ODF Alliance is more specifically stated in part as  follows:&nbsp; &quot;&hellip;To enable the public sector  to have greater control over and direct management of their own records,  information and documents, the ODF Alliance seeks to promote and advance the  use of OpenDocument Format (ODF) as the primary document format for  governments.&nbsp; The alliance works globally  to educate policymakers, IT administrators and the public on the benefits and  opportunities of the OpenDocument Format, to help ensure that government  information, records and documents are fully and natively accessible across  platforms and applications, even as technologies change.&quot;&nbsp; <a href="http://www.odfalliance.org/mission.php">Mission Statement of the ODF  Alliance</a>, at &lt; http://www.odfalliance.org/mission.php&gt; (accessed  March 3, 2007).</p>
  </div>
  <div id="ftn18">
    <p class="style2"><a href="#_ftnref18" name="_ftn18" title="" id="_ftn18"> </a><a name="18" id="18"></a>18.  Perhaps  the starkest current example of disparities in access among countries due to  the decisions of local governments can be found by comparing conditions in the  two Koreas.&nbsp; While South Korea currently  has one of the highest per-capita broadband access rates (ranking number 4  globally, with 26.4% of all inhabitants enjoying broadband access as of June  2006), North Korea has one of the lowest.&nbsp;  A list of most-connected countries and related data can be found at  Organization for Economic Co-operation and Development (OECD) at <a href="http://www.oecd.org/document/9/0,2340,en_2825_495656_37529673_1_1_1_1,00.html">this  Web page</a>: &lt;  http://www.oecd.org/document/9/0,2340,en_2825_495656_37529673_1_1_1_1,00.html&gt;</p>
  </div>
  <div id="ftn19">
    <p class="style2"><a href="#_ftnref19" name="_ftn19" title="" id="_ftn19"> </a> <a name="19" id="19"></a>19. The topic  of address allocation has some sensitivity. In the days before address needs  began to grow explosively (and before ICANN was created), IBM was assigned 33 <em>million</em> addresses, Stanford was awarded 17 million, and the entire Peoples Republic of  China was magnanimously awarded just 9 million.&nbsp; The situation was later  rectified by ICANN, but the continuing indirect control of ICANN by the United  States through the oversight power reserved to the US Department of Commerce  continues to generate concern among some nations, and annoyance among  others.&nbsp; For a fuller discussion of the  ICANN controversy, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/nov05.php#feature">WSIS, ICANN  and the Future of the Internet</a>, ConsortiumInfo.org, Consortium Standards  Bulletin, Vol. IV, No. 11, November, 2005, at &lt; http://www.consortiuminfo.org/bulletins/nov05.php#feature&gt;,  and sources cited therein.</p>
  </div>
  <div id="ftn20">
    <p class="style2"><a href="#_ftnref20" name="_ftn20" title="" id="_ftn20"> </a> <a name="20" id="20"></a>20. The <a href="http://unicode.org/">Unicode Consortium</a> Website can be found at <a href="http://unicode.org/">http://unicode.org/</a>&gt;.&nbsp; Two appreciation of the Unicode Consortium  and its mission that I have written previously are <a href="http://www.consortiuminfo.org/blog/blog.php?ID=4">Savoring the Unicode</a>,  ConsortiumInfo.org, Consider This, October 29, 2003, at &lt; <a href="http://www.consortiuminfo.org/blog/blog.php?ID=4">http://www.consortiuminfo.org/blog/blog.php?ID=4</a>&gt;  and <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20061017163856508&amp;">The  Unicode Standard 5.0: An Appreciation</a>, the Standards Blog, October 17,  2006, at &lt; http://www.consortiuminfo.org/standardsblog/article.php?story=20061017163856508&amp;&gt;.</p>
  </div>
  <div id="ftn21">
    <p class="style2"><a href="#_ftnref21" name="_ftn21" title="" id="_ftn21"> </a><a name="21" id="21"></a>21.  <a href="http://www.sil.org/iso639-3/default.asp">SIL International Website</a>,  at &lt; <a href="http://www.sil.org/iso639-3/default.asp">http://www.sil.org/iso639-3/default.asp</a>&gt;,  accessed March 4, 2007.&nbsp; For more about  ISO 639-03 and SIL International, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/blog/blog.php?ID=46">Language Codes and a  &quot;Philosophy of Three-Part Service,&quot;</a> ConsortiumInfo.org, Consider  This #46&lt; http://www.consortiuminfo.org/blog/blog.php?ID=46&gt;.</p>
  </div>
  <div id="ftn22">
    <p class="style2"><a href="#_ftnref22" name="_ftn22" title="" id="_ftn22"> </a> <a name="22" id="22"></a>22. In the  case of open document formats, several American states are obviously  collaborating on a common definition of an open standard.&nbsp; Bills have been introduced in the current  legislative sessions in Minnesota, Texas and California that would require that  documents be created and archived only if they are created in applications that  support XML-based formats that are:<br />
      (1) Interoperable among  diverse internal and external platforms and applications. <br />
      (2) Fully published and available royalty-free. <br />
      (3) Implemented by multiple vendors. <br />
      (4) Controlled by an open industry organization with a well-defined inclusive  process for evolution of the standard.<br />
      For more on these bills and to find links to  their texts, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20070228080638136">And  California Makes Four</a>, ConsortiumInfo.org, The Standards Blog, February 28,  2007, at &lt; http://www.consortiuminfo.org/standardsblog/article.php?story=20070228080638136&gt;.</p>
    <p class="style2"> <a name="23a" id="23a"></a>23. For a more detailed explanation of compliance,  certification and branding in the ICT industry, see the <a href="http://www.consortiuminfo.org/cb/">Certification Testing and Branding</a> section of the ConsortiumInfo.org <a href="http://www.consortiuminfo.org/essentialguide/">Essential Guide to  Standard Setting Organizations and Standards</a>, <em>at</em> &lt;  http://www.consortiuminfo.org/cb/&gt;.</p>
  </div>
</div>
</body>
</html>
