<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>The Essential Guide to Consortia and Standards</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta name="description" content="While standard setting has been an important aspect of industrial society for over a hundred years, the formation of unofficial, fast-acting standard setting and promotional consortia is a more recent phenomenon which is only now beginning to be seriously studied" />
<meta name="keywords" content="standard setting, promotional consortia, structuring of consortia, standardize, intellectual property policies, procedures, founding company, model, best practices, promoter/adopter structurer, joint venture, IPR, " />
<meta name="author" content="Andrew Updegrove" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/screen.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/guide.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/toolsets.css" />
<!-- ALTERNATE -->
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/default.css" title="default" />
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/large.css" title="large" />
<!-- ********* -->
<link rel="home" title="home" href="http://www.consortiuminfo.org" />
<script type="text/javascript">AC_FL_RunContent = 0;</script>
<script type="text/javascript" src="/scripts/AC_RunActiveContent.js"></script>
<script type="text/javascript" src="/scripts/styleswitcher.js"></script>
<script type="text/javascript" src="/scripts/obfuscate.js"></script>
</head>

<body id="bulletin">
	<!-- ****************** -->
	<!--   ACCESSIBILITY    -->
	<!-- ****************** -->
	<?php include '../includes/accessibility.php'; ?>
	
	<!--   SEARCH FORM   -->
	<form class="search" name="form1" method="get" action="http://search.Blossom.com/query/320">
	
	<!-- ************* -->
	<!--   MASTHEAD    -->
	<!-- ************* -->
	<?php include '../includes/masthead_subs.php'; ?>
	
	<!-- *********** -->
	<!--   BANNER    -->
	<!-- *********** -->
	<div id="banner">
		<div class="left">
			<p><a href="/">Home</a> &gt; <a href="/essentialguide/">Guide</a> &gt; Certification Testing And Branding</p>
		</div>
		<div class="right">
			<p><input type="text" name="key" /><input type="submit" name="Submit" value="Search" /> <a href="/search/">Advanced</a></p>
		</div>
		<div class="clear"></div>
	</div>
						
	<!-- ************** -->
	<!--   MAIN BODY    -->
	<!-- ************** -->
	<div class="GuideContent">
	<!-- SKIP/START CONTENT LINK -->
	<a name="startcontent" id="startcontent"></a>
		
		<!-- SIDEBAR CONTENT AREA -->
		<div class="AllSidebar">
			<div>
				<?php include '../includes/clients.php'; ?>			
			</div>
			<div class="AllNav">
				<p class="AllNavTitle">Chapter 7:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section1" title="Introduction">I &ndash; Introduction</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section2" title="Overview">II &ndash; Overview</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section3" title="Certification Processes">III &ndash; Certification Processes</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section4" title="Trademarks and Branding">IV &ndash; Trademarks and Branding</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section5" title="Summary">V &ndash; Summary</a></p>
				<p class="AllNavTitle" style="padding-top:10px">The Essential Guide to Standards:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part1" title="Participating In An SSO">Participating In An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part2" title="Forming And Managing An SSO">Forming And Managing An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part3" title="Law and Policy">Law and Policy</a></p>
			</div>
			<?php include '../includes/toolsets.php'; ?>
		</div>
		
		<!-- BODY CONTENT AREA -->
		<div class="GuideMain">
			<h1>The Essential Guide to Standards</h1>
			<p>The Essential Guide is a book-length handbook for anyone who wants to understand standards and standards development from a hands-on perspective. If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <script language="javascript" type="text/javascript">AuGesAdd();</script> if you have questions about this topic.</p>
			<div class="hr"></div><hr />
			
			<h2>Chapter 7: Certification Testing And Branding</h2>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<blockquote><em><strong>Summary:</strong> While a standard can provide value to a vendor through facilitating the design and production process, its greatest benefit arises when multiple stakeholders are made aware that a product or service complies with that standard. In order for such a benefit to be secured, however, the assertion of compliance must be trusted, and that trust must be validated by actual performance in the marketplace. In some circumstances, awareness of compliance is needed only on a business-to-business basis, while in others consumers must be made aware – or by experience find that they can take for granted – the fact that compliance goals have been achieved. However, the creation of tests to demonstrate compliance, and the conduct of such tests, can be expensive, and not all standard setting situations generate the desire, investment and infrastructure needed to fund neutral third party testing and certification. This is particularly true in the information and communications technology (ICT) industry, in which interoperability among the products of diverse manufacturers is nonetheless an essential requirement. As a result, a variety of techniques have evolved in the trenches to address this need in a situation-specific manner, from self-assertion of compliance with standards, to industry-wide certification programs that support expensive consumer brand-awareness building campaigns. This Guide section surveys the principal certification and branding needs, realities and practices that can be found in the ICT industry today. This article is part of the ConsortiumInfo.org <a href="/essentialguide/">Essential Guide to Standards</a>, which can be found at <a href="/essentialguide/">http://www.consortiuminfo.org/essentialguide/</a>.</em></blockquote>
			<a name="section1"></a><h3>I &ndash; Introduction</h3>
			<p>Standards have value to many constituencies, but their most obvious beneficiaries are those that utilize standards in the production of goods and the delivery of services, and those that consume those deliverables. While vendors often benefit from using standards simply as production tools (e.g., to achieve interoperability between products from the same vendor), the greatest value of a standard to vendors and consumers alike can arise from simply knowing that a product or service complies with a standard.</p>
			<p>For example, performance standards (e.g., how many watts of energy a light bulb will draw, and how many lumens of light it will produce) permit vendors to provide products that customers can easily evaluate, and allow customers to compare prices between competing products. Similarly, vendors increasingly adopt and implement interoperability standards that allow their products to access networks of all types in order to make those products more useful and desirable, and customers rely on built-in "plug and play" interoperability in order to mix and match components of everything from music systems to home wireless networks.</p>
			<p>In order for such benefits to exist, however, customers need to be able to rely on, and therefore trust, the fact that a product that purports to comply with a standard actually does. Such trust can be based upon any of a number of means, including vendor assertions, if the vendor has earned a reputation for trustworthiness, or on third party testing and confirmation of compliance. With respect to that subset of standards that is created by governments (laws and regulations), the assurance of compliance may result from government inspections, licensures and enforcement.</p>
			<p>Private sector assertions of compliance are often loosely referred to as "certification," in the sense that someone (whether the vendor or a third party) is promising that the good or service complies with the standard. More properly, the word "certification" should only be used where a neutral third party is providing the assurance of conformance. Regardless of who is making the guarantee, however, the value is roughly the same, if the claim of compliance is accepted and relied upon in the marketplace.</p>
			<p>That value can be augmented by focusing customer attention on the benefits of purchasing products that comply with a standard. Such building of "brand awareness" in a standard can be just as useful as building customer awareness of an individual vendor's trademarked products. Moreover, the economic burdens of building brand awareness in a standard can be shared among many vendors, thus lowering the per-vendor cost of a promotional campaign by leveraging the efforts of the many campaign participants.</p>
			<p>In this article, I will survey the principal means by which information and communications technology (ICT) industry compliance testing tools are created, the most common types of programs employed to perform and certify successful passage of compliance tests, and the ways that vendors build compliance brand awareness through the promotion of certification programs.</p>
			<a name="section2"></a><h3>II &ndash; Overview</h3>
			<p><strong>2.1 &mdash; Why test and certify?</strong> As with so many other aspects of standards and standard setting, the concept and practice of certification extends back into the dim reaches of antiquity. The first known examples of certification relate to weights and measures, as evidenced by metal ingots stamped with royal seals that attest to purity and weight. The evolution of coinage systems in many societies was a manifestation of the same certification concept, using the impressed (and sometimes idealized) likeness of a ruler on each coin to attest to the exact value (also sometimes idealized) of the precious metal comprising the coin.</p>
			<p>Certification of compliance with standards relating to safety, on the other hand, has roots in the private as well as the public sector. For example, the development of standards to ensure the safe design and building of steam boilers arose not from a government effort to prevent boiler explosions, but from a private vendor initiative launched to reassure both the public as well as insurance underwriters that installing boilers would not lead to disaster. But over time government regulators were happy to incorporate by reference the fruits of such private initiatives into the regulations they created in an effort to maintain public safety.</p>
			<p>By 1984, for example, voluntary compliance standards created by the American Association of Mechanical Engineers (ASME) to ensure that heat sources would automatically shut down before boilers could run dry (and sometimes explode) had been adopted into law by 46 states and all ten Canadian provinces.<sup><a href="#1">1</a></sup> And in the private sector, the ubiquitous Underwriters Laboratories "UL in a circle" mark (and its many related marks) is well recognized by U.S. consumers as a trusted indication that products have been designed to criteria that the UL believes to be conducive to safe usage.<sup><a href="#2">2</a></sup></p>
			<p>In more recent years, certifications of all types have become omnipresent &ndash; attesting to the weight, quality, purity, safety and other significant attributes of goods as diverse as building materials, drugs, foods, appliances, elevators, advanced technology products, services of all types, and more recently, practices such as sustainable forest management. These certifications attest to compliance with the standards promulgated by a wide variety of bodies &ndash; Federal, State, and more recently, regional (e.g., the European Union) governments and agencies, safety testing organizations, accredited private sector standard setting organizations, and unaccredited consortia, trade associations, environmental foundations, and other fora. Within some of these broad categories there may be hundreds of individual standard setting bodies, some of which develop and maintain many, and even thousands, of standards. One site, <a href="http://www.nssn.org/" target="_blank">http://www.nssn.org</a>, tracks the status of some 270,000 current standards worldwide.</p>
			<p>Standards themselves can be of several types, permitting varying ways to comply, as well as different processes to verify compliance. For example, <strong><em>performance</em></strong> standards define required outcomes, but not the design elements required to achieve those outcomes. As a result, they permit a vendor to design a product using a variety of techniques (patented and otherwise), so long as the resulting product meets the established performance measures. The techniques used to certify compliance with such products must therefore accommodate the different types of products designs so utilized.</p>
			<p>Products built to <strong><em>design</em></strong> standards, on the other hand, must conform to more detailed and exacting specifications, so that all electrical plugs of a given type (for example) will fit into all electrical sockets intended to accommodate them. Compliance testing techniques for this type of standard can therefore be as simple as measurements of physical dimensions. A given standard can incorporate both performance and design elements as well as diverse criteria, including the composition of component materials, physical dimensions, minimum outputs and maximum tolerances.</p>
			<p><strong><em>Interoperability</em></strong> standards, from the compliance testing point of view, can be another type of amalgam, in that design elements are specified, but their compliance (as in software) may need to be inferred from performance tests that prove or disprove success in achieving compliance.</p>
			<p><strong>2.2 &mdash; Why brand?</strong>Compliance testing of products is very widely used by vendors to ensure that their products will perform as expected, will meet regulatory requirements, and/or will be safe to use. Certification of compliance also bears an important role in international trade, where the importation of products may be preconditioned on proof of compliance with applicable standards.<sup><a href="#3">3</a></sup> This extra effort taken to demonstrate compliance with standards is usually invisible and unknown to purchasers, or taken for granted by consumers in the case of safety standards in well-regulated societies.</p>
			<p>The reason that vendors do not go to greater lengths to publicize their efforts to achieve compliance or formal certification is because the means required to raise customer awareness are expensive, and compliance may not be sufficiently important to a consumer to warrant the extra marketing and promotional resources required to raise such awareness. But there are several common market situations that may lead vendors to undertake such costs.</p>
			<p><strong>2.2.1 &mdash; Competitive formats.</strong> In today's interconnected world, there is increasing demand for certification mechanisms that can assure consumers as well as vendors that their expectations will be met when they make a purchase, whether they are aware that that expectation relates to a standard or not. Visible evidence of such certification can be especially useful in the consumer realm to convey the message that a product will perform and be usable as desired. This is true where new products are being introduced that rely on interoperability to provide value, and where consumers are aware that multiple, incompatible types of products are being sold that are visually indistinguishable, but for a distinctive logo or label text.</p>
			<p>In the late 1970s and early 1980s, for example, it was essential for video vendors to indicate, and for buyers and renters of videotapes to carefully look for the label stating, whether a given title conformed to the VHS or the Betamax video format. The same is true today as the next generation of DVD players and discs is now being introduced into the marketplace. Just as before, two competing (and incompatible) formats are being promoted, one called HD-DVD, and the second Blu-Ray. Initially, the vendors of each camp will seek to persuade consumers that their technology is superior, and to build brand awareness around their format mark.<sup><a href="#4">4</a></sup> After a given consumer buys a player that conforms to one format or the other, however, the principal value of the format label will not be as a brand, but as a conformance mark on a DVD, in order to allow the consumer to avoid buying or renting a disc that proves to be unreadable on the particular player she now owns.</p>
			<p><strong>2.2.2 &mdash; New networks.</strong> Other common examples of visible certifications, promoted as actual brands but of value to consumers for more utilitarian means, include the logos that appear on ATM machines, informing a user whether a given terminal will accept a credit, debit or bank card from the network (e.g., Star or Cirrus) with which that card is registered. Today, most bank ATMs are compatible with the cards of a wide variety of issuers, and arrangements have been made between banks and those issuers to reconcile accounts behind the scenes for most customers. But initially, these networks were more limited, and the marks displayed on cash machines therefore had a higher value to individuals on the lookout for an ATM that could satisfy their need for instant liquidity.</p>
			<p>Whether or not branding as well as certification makes sense to vendors and service providers - and to what degree &ndash; therefore depends on market circumstances. In the ATM example, there is no tolerance for error, because the results are binary: either the card can or can't be read, from the technical perspective, and the transaction will or will not be accepted, at the commercial level. When someone sees a Cirrus logo on an ATM, they expect their card to be honored, even if the user has no knowledge what the "Cirrus" network is, who designed it, or how it operates. The value that the consumer does appreciate is that there are hundreds of thousands of ATMs worldwide that bear the Cirrus logo, and into which the holder of (for example) a MasterCard can insert that card in order to obtain cash.</p>
			<p><strong>2.2.3 &mdash; Vendor needs.</strong> In the world of non-consumer goods, the standards-based goals of commercial vendors may vary widely. In some circumstances, standards and credible certification mechanisms may make it easier for a new market to develop because one vendor will have a greater degree of confidence that the products reaching the marketplace will indeed be interoperable. Similarly, the existence of certification options may make it more worth a vendor's while to create products that comply with one standard rather than another, not only because the certification option has independent value, but because it knows that other vendors will be more likely to choose the standard supported by certification. Since a standard only becomes useful through wide adoption, implementing the standard supported by certification therefore becomes the safer, as well as the higher value, decision (all other things being equal).</p>
			<p>In this type of situation, there is no incentive to create public brand awareness at all. Instead, a much more targeted, but no less important, campaign is needed to educate the vendors in a given product space that not only a standard, but a supporting certification mechanism is available to reward them for adoption. In many cases, the existence of compliance tests, even without a formal certification program, will still be attractive, because the compliance tests will be useful as tools to assist a vendor in discovering those changes in its product design that are required to achieve interoperability.</p>
			<p><strong>2.2.4 &mdash; Product identification.</strong> The value of certification and branding can also fall somewhere in between. This is because standards "brand awareness" is more common than most consumers might suspect, with much of the public being unaware that a heavily promoted brand utilized by multiple vendors actually relates to a standard. A current example is the explosive use of "WiFi" enabled equipment, from laptops to home network routers, all of which achieve their unique value through compliance with one or more of the IEEE 802.11 family of wireless connectivity standards.</p>
			<p>In this case, the WiFi Alliance, an unaccredited consortium, acts as an auxiliary to IEEE, an American National Standards Institute (ANSI) accredited, global standards development organization (SDO). The WiFi Alliance rapidly creates test suites for each WiFi standard as it is completed, and then offers certification testing to permit vendors to refine their designs to achieve interoperability, and then advertise their compliance through use of WiFi trademarks licensed from the Alliance after their products pass the required tests.</p>
			<p>The result is akin to the "Intel Inside" branding campaign, but with important differences. In the Intel case, Intel customers are able to borrow on the reputation of the best-known semiconductor manufacturer, and Intel benefits from the increased advertising &ndash; but Intel remains in sole control of the design of its chips, and the use and ownership of the "Intel Inside" trademark. With WiFi, the 250 members of the WiFi Alliance control the process of test suite creation, certification testing and brand promotion. To the customer, however, the result is much the same: greater assurance that expectations will be satisfied when a purchase is made. Even if they don't really know why.</p>
			<a name="section3"></a><h3>III &ndash; Certification Processes</h3>
			<p>Except in certain government-regulated areas where determination of compliance must be confirmed on-site (e.g., in the case of building codes and food preparation), certification tests and test facilities must usually be created by the private sector, either under the auspices of an existing standards development organization, by for-profit companies, or by means of a new entity created for that specific purpose.</p>
			<p>In recent decades, more and more ITC standards have been created not by accredited standards development organizations (SDOs), but by unaccredited consortia. However, while a standard setting organization (SSO) of either type may be quite able to fund and manage the development of a standard, the creation of compliance tests is expensive, and SSOs in general, and consortia in particular, are most frequently low-budget operations. Moreover, in the world of SDOs, there is a history of separation between the standards creation process and the compliance testing function, each of which is conducted by a separate organization.</p>
			<p>This can lead to a lack of certification options, especially in the information technology (IT) industry, which is typified not only by expensive research and development costs, but also by briefer product lifespans than is common in many other industries. Because development of a robust test suite implemented in software (as compared to a set of detailed questions attesting to internal design compliance and self-testing) can be quite expensive, that cost is likely to exceed the financial resources of the organization that has created the standard in question, even though the actual process of certification testing might be self-funding once the test itself has been developed.</p>
			<p>In some cases, however, the number of vendors building products to a given standard may be low relative to the cost of creating a test suite to confirm compliance. In such a situation, a private testing service would be unable to recover its development costs to create the test suite needed before it could offer certification services. Consequently, where robust test suites are developed at all, they are often funded by consortium dues or by a government or other grant, or the test suite is developed and contributed by the same member that initiated the creation of the standard to which the test suite relates.</p>
			<p>The same challenges that stand in the way of test suite creation also arise in the context of certification testing. In the case of actual interoperability or software-driven testing, expensive test equipment, facilities and personnel may be required, as well as administrative support. Once again, such costs exceed the budgets, staff and physical resources of many SSOs. On occasion, however, a third party can be found to provide testing services once the development of the test suite itself has been funded or arranged through the consortium's own devices of one type or another.</p>
			<p>As a result of the financial challenges of instituting a formal third-party certification testing program, compliance programs and processes are far from uniform. Certification programs in the ITC space have therefore evolved that fall across a range of increasing cost and credibility, ranging from very low-budget self-assertion (and therefore low trust) programs, to costly third-party programs that may provide much higher credibility and value.</p>
			<p><strong>3.1 &mdash; One on one systems.</strong> The following are representative (although not exhaustive) of the levels of compliance testing and certification that can be found in the ITC industry today where the parties to the process are the vendor and the SSO or a third party verifier.</p>
			<p><strong>3.1.1 &mdash; Self-Assertion without a Test Suite. </strong>At the most modest end of the scale is <strong><em>self-assertion</em></strong>, which is not a certification process at all, in any true sense of the word. In this model, the vendor simply asserts that its product conforms to a given standard, and there is no third party verification of either the result or the means by which the vendor reaches its conclusion. Where this is the best that can be done, it is important for an SSO to make sure that the marketplace understands that no formal certification process is in place, and that only limited credibility should be given to such assertions.</p>
			<p>As a result, the term "certification" should not be used in connection with a self-assertion program. Rather, the implementers of standards in this setting should only be permitted to assert "compliance with", or "conformance to," a standard or specification.<sup><a href="#5">5</a></sup> Self-assertion programs are quite common for primarily informational purposes, notwithstanding the limited level of credibility that they are likely to offer. One reason is that, unlike safety features in consumer safety products, interoperability failures in ICT products do not typically lead to dire consequences, and the government therefore has not to date found it necessary to focus on this area. Further, vendors can acquire an individual reputation over time for being trusted (or not) when they self-assert compliance, since customers will swiftly learn whether or not the product in question is truly interoperable with other equipment or software believed to comply with the same standard.</p>
			<p>Second, a wide range of factors (besides cost) may preclude the ability or interest of an SSO to create a test suite and/or engage a third party testing service. For example, the commercial value of compliance may not be high enough, or the standard itself may not be sufficiently robust to achieve a conclusive result, and therefore compliance with the standard alone would not imply a result that has significant public commercial value. Where cost is the true reason, however, the achievements of the affected organization may be more modest than those of another group that is capable of supporting a full certification program, especially where reliable interoperability is highly important to the end user.</p>
			<p><strong>3.1.2 &mdash; Self-Asserted Compliance (or Self-Certification). </strong>In this model, some type of test suite exists (although it may be a "paper test,"), but the vendor performs the test itself and asserts success, perhaps being required to submit some type of test summary or other affirmative statement that it has successfully completed and passed the test. In some cases, there may be little effort to publicize the fact that a product meets the test, because the test suite has been created primarily as a tool for vendors to use in order to achieve interoperability at a lower cost. In other cases, credibility is an important goal, but the SSO has not been motivated, or able, to arrange for verification. As a result, only a very modest increase in trust may be gained over self-assertion of compliance, since only one leg (thoroughness or rigor of test) has been strengthened, but not the other (independent verification).</p>
			<p><strong>3.1.3 &mdash; Self-Certification with Verification.</strong> If a higher degree of credibility for the certification program is deemed to be desirable, the vendor is required to return some type of evidence of satisfactory test completion to the SSO (or a third party) for verification. The deliverable typically will be a paper or electronic record of the test results, with the credibility of the program relying in part on how stringent and conclusive the test suite provided may be. Again, depending on the consortium's resources and the degree to which vendors are willing to pay certification fees, the report may either be simply filed away to create what is essentially a record of self-assertion, or may be examined for completeness and consistency, but not otherwise directly confirmed by an independent test of the product. Hence, an element of unsupported trust is still involved, and the credibility of the certification is therefore still qualified.</p>
			<p><strong>3.1.4 &mdash; Third Party Testing. </strong> This is the highest standard of formal testing, since the vendor must submit its product to a third party for testing. However, the efficacy of testing may vary widely, being limited in part by the sophistication of the standard to which the test applies (some standards are very detailed and comprehensive, while others are less so), and the effectiveness of the test itself. Hence, a product built to one standard which successfully passes certification testing may indeed "plug and play" with another compliant product, while a product built to another, less comprehensive standard may require further refinements in order to reliably interoperate, even though each has satisfactorily passed the required test. The degree to which a standard is capable of enabling full interoperability is also affected by factors other than technical challenges, including political compromises made during the development of the underlying standard (such as permitting alternate ways to implement a single element of a standard) among members that are, after all, usually competitors.</p>
			<p>In each case, third party testing is almost always performed on representative samples, rather than on each unit sold. As a result, while the design may be proven to meet a standard, any individual unit may fail to meet expectations, due to failings peculiar to that single unit, or run of units affected by a failure of the production process.</p>
			<p>With third party testing, the final results are often submitted to the SSO, which will then issue the actual certification, along with a license to use its trademarks in connection with assertions of satisfactorily passing a certification test. In some cases, the brand of the third party that has tested the product line (e.g., Underwriters Laboratories, Inc.) is of equal or greater value.</p>
			<p><strong>3.2 &mdash; Other Processes. </strong>There are other mechanisms besides certification testing that an SSO may take or arrange to increase the credibility of its standards and/or assist its members and other companies in achieving a high degree of compliance.</p>
			<p><strong>3.2.1 &mdash; Interoperability Testing.</strong> In some cases, a third party testing service may be engaged to run submitted products directly against other compliant products, in addition to (or instead of) running them against the test suite. In others, a consortium may set up such an "interoperability center" itself (usually at a member site or at a trade show) to which members may (or in some cases are required to) bring their hardware and software products and run them against each other, in order to work out final interoperability issues not able to be resolved by means of a test suite.</p>
			<p>The purpose of such testing can be either very secret or very public. In the former case, stringent confidentiality agreements may be utilized, particularly where the testing being conducted relates to products that have not yet been announced in the marketplace, and/or where the failure of a product to demonstrate interoperability could have a negative impact on sales. In this case, the purpose of the exercise is all about compliance confirmation and not at all about branding.</p>
			<p>At the opposite extreme is the very much public "plug fest" at a trade show, where multiple vendors demonstrate the interoperability of their products. In this case, the purpose is entirely brand-related, since no vendor would wish to publicly demonstrate the non-compliance of its products, and confirmation of interoperability is usually therefore tested in advance.</p>
			<p>In each case, although the activity in question may not be part of the formal certification testing process, it provides another example of the way in which an SSO may initiate and coordinate activities in order to lower costs and improve outcomes for its members in support of the standard that it has developed.</p>
			<p><strong>3.2.2 &mdash; Reference Software. </strong>In some cases, an SSO will provide actual software instantiating a specification. The software is often made available in both source code as well as object code form, and is commonly referred to as a reference implementation. Where such software is available (sometimes only to members, and at others as a free download from the consortium's website), an implementer is spared the expense of developing its code to comply with the standard.</p>
			<p>One common reason for the existence and use of reference software is that a member may have already created it for its own purposes, and is willing to make it freely available to all in order to reap some greater benefit from wide adoption of the standard. Another reason may be that a standard has been created in a patent-rich environment, and there is a common benefit to be gained from the availability of an implementation of the standard that is not believed to infringe upon known (at least) intellectual property rights of members, or where infringement in this specific form has been permitted. In this case, saving compliance testing time and expense is a secondary, but automatic, benefit to those that utilize the reference implementation.</p>
			<a name="section4"></a><h3>IV &ndash; Trademarks and Branding</h3>
			<p>While discussing intellectual property concerns in standard setting almost always focuses on patent and copyright issues, trademarks play an essential role as well. The reason is that while patent law may control whether a standard can be implemented, and copyright law protects the text of the standard itself, only trademark law provides the means to control whether or not a vendor is entitled to claim that its products actually comply with a standard.<sup><a href="#6">6</a></sup></p>
			<p><strong>4.1 &mdash; Using Trademarks to Enforce Quality Control.</strong> As noted earlier, standards need to be credible in order to have value. This is because standards are only useful to a customer to motivate a purchase, or to a vendor to secure market advantage, when the promise they make is valid (e.g., a brand request to "buy this because it will work with that" only works if in fact "this" really does work with "that"). Moreover, if a vendor asserts compliance where compliance does not exist, an end user may be unable to tell whether the fault lies with a non-compliant product or with an inadequate standard. As a result, not only the vendor that failed to comply loses credibility, but all products of all vendors that assert compliance with the same standard will lose credibility as well, and the goals of the SSO that created the standard and its members will be defeated.</p>
			<p>False claims of compliance are therefore of great concern to SSOs and to end users alike. Where an SSO gives a name to a standard and the public knows the standard by that name alone, then the SSO may prevent false claims of compliance from being made by withholding the legal right of the offending vendor to refer to the standard in connection with a non-compliant product.<sup><a href="#7">7</a></sup></p>
			<p>While it is not legally necessary to obtain a formal trademark registration in the United States on the name of a standard in order to own all rights to its usage, it is prudent to do so, since the cost is modest in comparison to the benefit of putting the world on notice that the SSO owns the trademark. Since it is widely known that it is very simple to perform an on-line search of issued trademarks, obtaining a trademark registration will also make it far less likely that someone else will begin to use the same, or a confusingly similar, name for its product or service. As a result, there will be less potential that someone else's actions will dilute the value and effectiveness of the SSO's mark, or that the SSO will be put to the trouble and expense of asserting or defending its trademark.</p>
			<p>Since ITC standards are usually intended for global adoption, it is important to undertake a market analysis in order to settle upon a cost-effective strategy for protecting a mark, due to the fact that a commercial-scale, global trademark program would invariably be prohibitively expensive. Fortunately, a trademark convention in Europe now permits a single filing to secure rights in multiple countries, and a very large proportion of sales of certified products are usually expected to occur in a comparatively small number of first world countries. The result is that it is possible to achieve a very meaningful degree of protection by obtaining trademark protection in just the United States, Europe and selected Pacific Rim countries. Such a measured program of trademark registration can be completed within the budget of most SSOs.</p>
			<p><strong>4.2 &mdash; Using Trademarks to Associate Value with Products.</strong> The term "branding" usually connotes a use of trademarks that is broader than simply policing compliance. Rather, it seeks to persuade the buying public that there is added value in compliant products, because they are more likely to perform well for the purchaser. For example, the right to include the familiar "Dolby" brand logo on a product, indicating the use of patented Dolby noise-suppression technology, was a valuable product differentiator in the early days of tape decks. More recently, the earlier noted "Intel Inside" ad campaign provides an example of a brand usage that is intended to promote the goodwill of Intel as much, if not more, than the vendor of the product in which the chip finds a home. In sum, Intel is seeking to create a market perception that its technology represents a "standard of excellence and innovation" with which consumers should associate added value.</p>
			<p>Launching a branding campaign as well as a certification program of course requires a much larger budget. To be effective, such an initiative also requires the active cooperation of SSO members, who should place certification logos on their compliant products, packaging and advertising in order for the program to be truly successful. Often, obtaining the cooperation of the marketing departments of large corporate members in a branding campaign proves to be very difficult, regardless of the fact that the same companies may have invested heavily in creating the standards to which the certification and branding program apply.<sup><a href="#8">8</a></sup></p>
			<p>Nonetheless, as the video format and ATM examples discussed above illustrate, branding may be vital in persuading the marketplace to buy (or, in the case of the credit card, to buy into) new classes of products and services, and the costs of brand creation may therefore prove to be wise, or even unavoidable, investments. Absent such a program in the video example, many consumers might have shied away from purchasing or renting any products at all while the rival vendor communities engaged in their standards war.</p>
			<p>The costs of brand maintenance in such an example may also be finite. After a single standard "wins", or after interoperability issues are resolved between competing standards, the brand may be allowed to languish, as an end-user comes to take interoperability for granted, and expects that all products, regardless of the technology upon which they are based, will be usable in connection with all other logically related products.</p>
			<p>For example, today the user of an ATM is not likely to look for, or even notice, the multiple acceptance network logos on an ATM, because such a high degree of technical interoperability and business reciprocity has been achieved that virtually every ATM will now accept almost any and every card, regardless of the issuer. Similarly, after the VHS format vanquished Betamax, video rental and consumer electronics stores discontinued stocking Betamax products entirely, making the use of the mark "VHS" no longer meaningful in anything other than an historical sense. At that point in each example, the branding process had achieved its goal, although the certification process continued to live on unnoticed by consumers in order to confirm actual compliance with the relevant standard for the benefit of manufacturers.</p>
			<a name="section5"></a><h3>V &ndash; Summary</h3>
			<p>Notwithstanding the costs and constraints associated with developing, administering and participating in standards certification programs, vendors and service providers nonetheless voluntarily implement and comply with hundreds of thousands of standards, because they believe that the benefits of compliance outweigh the costs. Since one of the anticipated benefits in complying with standards is increasing sales through customer awareness of product compliance, vendors are often willing to make promotional investments in conducting standards-based brand awareness campaigns as well.</p>
			<p>When the certification process works best, larger markets for goods and services are created more quickly, and end users are better served by the greater likelihood that their purchase expectations will be fulfilled. While providing conclusive certification testing in every market situation is not necessary, cost constraints will often render this goal infeasible in any event. In response, the marketplace has evolved multiple levels of compliance assertion and testing that can provide both cost effective as well as meaningful comfort in a variety of different situations, to the ultimate benefit of vendors and end users alike.</p>
			<p class="note"><strong>NOTE:</strong> If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a> if you have questions about this topic.</p>
			<p class="center">Copyright 2007 Andrew Updegrove</p>
			<p><strong>End Notes</strong></p>
			<p><a name="1"></a><sup>1</sup> Department of Philosophy and Department of Mechanical Engineering, Texas A&amp;M University, "Engineering Ethics," summarizing facts cited in ASME v. Hydrolevel Corp., at &lt;http://ethics.tamu.edu/ethics/asme/asme1.htm&gt; (accessed July 23, 2006).</p>
			<p><a name="2"></a><sup>2</sup> Like virtually all compliance testing organizations, Underwriters Laboratories does not test and certify every individual product. Instead, it tests samples, and then allows its marks to be displayed on products that the manufacturer attests are consistent with the tested sample. Current UL marks can be viewed at this page of the UL Website: <a href="http://www.ul.com/marks_labels/mark/art.htm#ul">http://www.ul.com/marks_labels/mark/art.htm#ul</a> (accessed July 29, 2006).</p>
			<p><a name="3"></a><sup>3</sup> Prohibiting the use of compliance testing to favor domestic industry by making it difficult, expensive or impossible for foreign goods to be imported is a goal of the World Trade Organization's Agreement on Technical Barriers to Trade. Before the enactment of such laws, countries would frequently require local compliance testing of goods that had already been tested elsewhere instead of respecting the certification already granted by a neutral, but non-domestic, testing service.</p>
			<p><a name="4"></a><sup>4</sup> While each format has its own differentiating features, these features tend to be of greatest interest to distinct stakeholders (e.g., content owners, hardware vendors, software vendors, and so on) rather than to all stakeholders. As a result, if one format is "better" for the consumer, it will only be likely to win the current standards battle by coincidence. For an example of the hundreds &ndash; if not thousands - of articles that have been written over the past several years assessing the advantages and chances of one format over another at any particular point in time (a search of "HD-DVD vs. Blu-Ray features" at Google yields 2,450,000 hits), see: Perenson, Melissa J., <em>More from the Blu-Ray vs. HD-DVD Front</em>. PC World.com (November 15, 2005), at &lt;http://www.pcworld.com/news/article/0,aid,123491,00.asp&gt; As of this writing, it is uncertain which format &ndash; if either &ndash; will ultimately prevail. For an example of a current analysis on that question, see: Belcher, James<strong>, </strong>Blu-ray and HD-DVD: Only One Winner? Or Two Losers? (July 26, 2006) EMarketer.com, at &lt;http://www.emarketer.com/Article.aspx?1004082&gt;.</p>
			<p><a name="5"></a><sup>5</sup> While there is consensus on not using the word "certification" in connection with self-assertions of compliance, there is no general agreement on whether, or how, to use words such as "compliant" and "conformant" across SSOs. As a result, it is important for an SSO to define with precision which word(s) may be used in connection with the performance of what types of tests in connection with its standards, so that it is clear what a vendor is (and more importantly, is not) saying when it uses a permitted term.</p>
			<p><a name="6"></a><sup>6</sup> While the use of trademarks in certification and branding programs has many similarities to the usage of the same tools in connection with building brand awareness in support of proprietary products, there are also important differences, not all of which are immediately obvious. For example, while marks designated as "certification marks" can be registered in some (but not all) countries, it may be appropriate to use trademarks, service marks or certification marks (and sometimes all three) in support of a given standards effort, depending upon the goals and circumstances in a given case. A detailed review of this topic is beyond the scope of this article.</p>
			<p><a name="7"></a><sup>7</sup> Exercising a sufficient degree of "quality control" over a widely used trademark is a sensitive issue for SSOs, which commonly do not have the resources needed to police the usage of their marks to the same extent as commercial entities. As a result, it is essential for an SSO to institute good practices with respect to each standard as soon as it is complete, to prevent members and others from taking actions (such as incorporating the name of a standard into a product name) that could result in the mark becoming generic.</p>
			<p><a name="8"></a><sup>8</sup> One of the first consortia that the author represented was formed to initiate a very ambitious certification-based branding program. The most interested members paid hundreds of thousands of dollars in annual dues to fund the development of sophisticated hardware and software certification suites and the founding and staffing of a sophisticated interoperability testing center. However, few members actually branded their products with certification marks after their products had been proven to be compatible. The author has tried to ensure that every consortium he has helped structure since then has included a marketing committee that is co-equal with the technical committee from the date of formation, in order to make it more likely that both the marketing, as well as the technical management of member companies would be committed to achieving the goals for which the consortium was founded.</p>
			<table class="GuideHelp">
				<tr>
					<td style="padding:12px;" valign="top"><a href="http://www.gesmer.com/attorneys/updegrove.php"><img src="images/guide_updegrove.jpg" width="69" height="106" border="0" alt="" /></a></td>
					<td valign="top">
						<p class="GuideHelpHead">Can We Help You?</p>
						<p class="GuideHelpBody1"><a href="http://www.gesmer.com/">Gesmer Updegrove LLP</a> is, quite simply, the most experienced law firm in the United States when it comes to representing and creating standards development organizations &mdash; <a href="http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST">more than 100</a> &mdash; to date.  If you need advice about participating in the standards development process, representation in standards-related litigation, intellectual property advice, or help creating a brand new SSO or open source foundation, we'd be pleased to help. Contact:</p>
						<p class="GuideHelpBody2">Email: <script language="javascript" type="text/javascript">AuGesAdd();</script><br />Tel: 617-350-6800</p>
					</td>
				</tr>
			</table>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
		</div>
	</div>
<div class="clear"><br /></div>
<!-- *********** -->
<!--   FOOTER    -->
<!-- *********** -->
<?php include '../includes/footer.php'; ?>
</form>
</body>
</html>