<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>The Essential Guide to Consortia and Standards</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta name="description" content="While standard setting has been an important aspect of industrial society for over a hundred years, the formation of unofficial, fast-acting standard setting and promotional consortia is a more recent phenomenon which is only now beginning to be seriously studied" />
<meta name="keywords" content="standard setting, promotional consortia, structuring of consortia, standardize, intellectual property policies, procedures, founding company, model, best practices, promoter/adopter structurer, joint venture, IPR, " />
<meta name="author" content="Andrew Updegrove" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/screen.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/guide.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/toolsets.css" />
<!-- ALTERNATE -->
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/default.css" title="default" />
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/large.css" title="large" />
<!-- ********* -->
<link rel="home" title="home" href="http://www.consortiuminfo.org" />
<script type="text/javascript">AC_FL_RunContent = 0;</script>
<script type="text/javascript" src="/scripts/AC_RunActiveContent.js"></script>
<script type="text/javascript" src="/scripts/styleswitcher.js"></script>
<script type="text/javascript" src="/scripts/obfuscate.js"></script>
</head>

<body id="bulletin">
	<!-- ****************** -->
	<!--   ACCESSIBILITY    -->
	<!-- ****************** -->
	<?php include '../includes/accessibility.php'; ?>
	
	<!--   SEARCH FORM   -->
	<form class="search" name="form1" method="get" action="http://search.Blossom.com/query/320">
	
	<!-- ************* -->
	<!--   MASTHEAD    -->
	<!-- ************* -->
	<?php include '../includes/masthead_subs.php'; ?>
	
	<!-- *********** -->
	<!--   BANNER    -->
	<!-- *********** -->
	<div id="banner">
		<div class="left">
			<p><a href="/">Home</a> &gt; <a href="/essentialguide/">Guide</a> &gt; Forming a Successful SSO Part II</p>
		</div>
		<div class="right">
			<p><input type="text" name="key" /><input type="submit" name="Submit" value="Search" /> <a href="/search/">Advanced</a></p>
		</div>
		<div class="clear"></div>
	</div>
						
	<!-- ************** -->
	<!--   MAIN BODY    -->
	<!-- ************** -->
	<div class="GuideContent">
	<!-- SKIP/START CONTENT LINK -->
	<a name="startcontent" id="startcontent"></a>
		
		<!-- SIDEBAR CONTENT AREA -->
		<div class="AllSidebar">
			<div>
				<?php include '../includes/clients.php'; ?>			
			</div>
			<div class="AllNav">
				<p class="AllNavTitle">Chapter 6:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section1" title="Introduction">I &ndash; Introduction</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section2" title="Structure">II &ndash; Structure</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section3" title="Antitrust Considerations">III &ndash; Antitrust Considerations</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section4" title="Intellectual Property Rights">IV &ndash; Intellectual Property Rights</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section5" title="Tax Considerations">V &ndash; Tax Considerations</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section6" title="Certification and Branding">VI &ndash; Certification and Branding</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section7" title="Summary">VII &ndash; Summary</a></p>
				<p class="AllNavTitle" style="padding-top:10px">The Essential Guide to Standards:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part1" title="Participating In An SSO">Participating In An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part2" title="Forming And Managing An SSO">Forming And Managing An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part3" title="Law and Policy">Law and Policy</a></p>
			</div>
			<?php include '../includes/toolsets.php'; ?>
		</div>
		
		<!-- BODY CONTENT AREA -->
		<div class="GuideMain">
			<h1>The Essential Guide to Standards</h1>
			<p>The Essential Guide is a book-length handbook for anyone who wants to understand standards and standards development from a hands-on perspective. If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <script language="javascript" type="text/javascript">AuGesAdd();</script> if you have questions about this topic.</p>
			<div class="hr"></div><hr />
			<h2>Chapter 6: Forming A Succesful Consortium<br />Part II &mdash; Legal Considerations</h2>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<blockquote><em><strong>Summary:</strong> In <a href="forming1.php">Forming a Successful Consortium &mdash; Part I</a> I reviewed the key business concepts underlying the formation of a successful consortium to develop, promote and/or support standards. In this second and final installment, I will discuss the most important legal considerations to consider in creating and maintaining such organizations, including: issues presented by specific types of activities; common legal structures and the relative virtues and shortcomings of each; optimal jurisdictions for formation; antitrust laws and their implications for operations; tax exemption criteria; the advantages and disadvantages of seeking exemption as a public charity as compared to a trade association;  how to evaluate the advisability of seeking that exemption; intellectual property rights policies and procedures; and issues associated with certification and branding. This article is part of the ConsortiumInfo.org <a href="/essentialguide/">Essential Guide to Standards</a>, which can be found at <a href="/essentialguide/">http://www.consortiuminfo.org/essentialguide/</a>. In particular, you may wish to read the first part of this article, titled <a href="forming1.php">Forming A Successful Consortium Part I &mdash; Business Considerations</a>.</em></blockquote>
			<a name="section1"></a><h3>I &ndash; Introduction</h3>
			<p>In the <a href="/bulletins/nov06.php#feature">first installment</a> of this two-part article, I focused on the business issues and concepts underlying the formation of a successful consortium to develop and/or promote standards.<sup><a href="#1">1</a></sup> In this second and final installment, I will discuss the legal issues that relate to the creation and operation of such organizations.<sup><a href="#2">2</a></sup></p>
			<p>Standard setting organizations (SSOs), whether they be decades-old accredited standards development organizations (SDOs), or any of the more recently formed non-accredited organizations that range from small, invitation-only entities to well-respected, global standard setting consortia such as the W3C, IETF or OASIS, face essentially the same legal issues.<sup><a href="#3">3</a></sup> These issues morph over time, as new laws are passed, new cases reinterpret old laws and decisions, and SSOs enter into new areas of endeavor. For SSOs, as with other businesses, staying on the right side of existing and new legal rules requires ongoing awareness and monitoring.<sup><a href="#4">4</a></sup></p>
			<p>But while the same legal issues are relevant to almost all SSOs, the specific ways in which a given SSO will operate and structure itself in relation to those issues will necessarily be a product of its particular situation: its mission, goals, projected membership and activities, and other variables. In this article, I will review the areas of legal significance with which the founders of a new SSO must be aware, and highlight the types of decisions that SSO founders should make, based upon their unique business plan. The issues addressed, and the solutions suggested, are based upon my experience in helping create more than 50 consortia over the past 18 years. A full list of the SSOs that I have represented can be found at this <a href="http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST">Web page</a>.<sup><a href="#5">5</a></sup></p>
			<a name="section2"></a><h3>II &ndash; Structure</h3>
			<p><strong>2.1 &mdash; Concerns to be addressed.</strong> Standard setting and related activities (e.g., promotion, test-creation and certification testing, public advocacy and training) present a range of concerns that dictate structural decisions. These concerns include the following:</p>
			<p><strong>2.1.1 &mdash; Liability.</strong> While SSOs do not typically engage in high-risk activities, SSO members (and especially corporate members) have an understandable aversion to participating in organizations where the actions or inactions of other members could lead to joint liability. Accordingly, mechanisms intended to eliminate, or at least limit, such an eventuality are essential to facilitating successful recruitment.</p>
			<p><strong>2.1.2 &mdash; Practicalities.</strong> SSOs that are more than minimally active will soon face the need to enter into contracts with third parties such as trade show management companies, public relations firms, and Web hosting services. They may also wish to hire employees. Absent an incorporated entity to sign legally binding agreements, one member or another will need to provide a signature &ndash; and incur the front-line liability on the obligation. Even something as simple as opening a bank account becomes problematic, since a bank will not open an account for an entity that does not have an employer identification number.</p>
			<p><strong>2.1.3 &mdash; Ownership of intellectual property.</strong> SSOs create assets of various types in which intellectual property rights (IPR) may arise &mdash; typically copyrights, trademarks and potentially patentable inventions. But who should own and define use rights to such IPR? On the one hand, individual members do not wish their own ownership rights to be jeopardized when they collaborate in a working group. But on the other, potential implementers will need to be convinced that implementing the resulting specification will not result in potential liability for infringement, or in becoming unduly dependent on the intentions of a single patent owner &ndash; especially if that patent owner is a competitor. As a result, the ownership of assets such as standards, test suites and trademarks is a matter of particular concern, as are the legal mechanisms by which desired outcomes may be guaranteed.</p>
			<p><strong>2.1.4 &mdash; Governance.</strong> Whatever structure is chosen must not only be appropriate to permit efficient and effective operations, but also satisfy the concerns of those that are investing in the creation of the new entity: that it will not stray from its intended purpose, that it will be perceived as "open" (if that is the goal) or permit the founders to remain in control (if openness is not a concern), that no individual member can block or veto necessary actions, and so on.</p>
			<p><strong>2.1.5 &mdash; Ease and cost of formation.</strong> Time spent on formation and dollars spent on lawyers do not advance the goals for which a new organization is formed. Accordingly, the structure chosen should permit as rapid and inexpensive a launch as possible, as well as efficiency in ongoing operation.</p>
			<p><strong>2.2 &mdash; Formation criteria. </strong>&nbsp;Deciding which structure is most appropriate for a new organization will be most heavily influenced by the answers to the following questions, among others:</p>
			<p><strong>2.2.1 &mdash; Duration.</strong> What is the expected duration of the project at hand? Will it be finite, and limited (for example) to the development of a single specification, which will then be offered to another SSO for adoption and long-term maintenance, or will the new organization be founded to create an ongoing series of standards? If the former, the business plan may be less complex, and the needed legal structure more light weight. In the latter, multiple classes of membership, layers of technical process, and a variety of promotional and other activities may be involved, requiring a more robust and detailed governance and operational structure to be enabled and managed through the legal structure.</p>
			<p><strong>2.2.2 &mdash; Membership.</strong> Will the success of the initiative be assured by the participation of a small number of participants, or only by attracting the involvement of a large and diverse membership? Will the value propositions required to attract different types of stakeholders vary greatly? Will any type of stakeholder (e.g., government representatives) be subject to legal constraints on its activities, or that would limit its ability to make the commitments required of a member?</p>
			<p><strong>2.2.3 &mdash; Activities.</strong> What might the new organization wish to do over its expected lifespan? Only develop or promote standards, or also create test suites and conduct compliance testing? Will it wish to support a branding program? Will it need to have international operations and offices? Will it engage in lobbying or other public advocacy activities? Will it generate revenue from other than membership fees? Will it wish to limit its activities only to members, or permit participation by others in some of its activities as well?</p>
			<p><strong>2.2.4 &mdash; Liability profile.</strong> Most standards-related activities are quite benign, but this is not true in all cases, and even in otherwise low-risk situations, where the membership constitutes "market power" under the antitrust laws (e.g., a significant percentage of the competitors in a given product or service space are members), the potential for inadvertent mistakes, as well as the level of potential scrutiny by government regulators, is higher. In such a situation, individual members may wish to maintain tighter control over what can &ndash; and more importantly, what cannot &ndash; be done by the organization and its members without proper prior consideration.</p>
			<p><strong>2.3 &mdash; Available structures.</strong> While there is no "one size fits all" way to structure and manage a consortium, there are reasonably defined variations and best practices to consider before creating one. As a result, a small number of models have evolved upon which nearly all SSOs are founded.&nbsp; In the United States (where the great majority of new SSOs have been formed in the last twenty years), new consortia are almost always based upon one of four legal foundations, each of which has its advantages and disadvantages, requiring detailed explanation. They are as follows:</p>
			<p><strong>2.3.1 &mdash; The "classic" corporate model.</strong> By far and away the largest number of consortia intended to have more than a transitory existence are structured as corporations. Typically, they are formed under the not for profit laws of a jurisdiction, whether or not the founders intend to seek federal or state tax exemption for the consortium.</p>
			<p>The would-be founders of a consortium very frequently believe that a corporation is the last, rather than the first, alternative to consider. The reason is that the formation of a corporation would seem to represent expense, complexity, permanence and burden. In fact, the opposite is almost always the case, due to the simple fact that existing corporate law supplies all of the rules, as well as the solutions, that a non-corporate structure must otherwise create from whole cloth. Moreover, there are some concerns, such as joint liability, which cannot be easily or completely avoided by any non-incorporated means &ndash; yet the simplest corporate structure, if properly maintained, can provide convincing protection to its officers, directors and members.</p>
			<p>Moreover, experienced counsel should already possess a set of model documents that can be easily tailored to the needs of the organization, and which provide all of the statutorily-enforceable rules and provisions other than those which will be unique to the organization. Those documents include the following:</p>
			<ul>
				<li><strong>Certificate of Incorporation</strong>, containing the limited number of rights and rules which by law must be set forth in this public document.<br /><br /></li>
				<li><strong>Detailed Bylaws</strong>, a non-public document that contains the legal and procedural rules of operation, the governance structure, the classes of membership and their rights, and other provisions which enable the day to day operation of the organization (other than the technical process, on which more below).<br /><br /></li>
				<li><strong>Membership Application</strong>, which should be drafted to constitute a legally binding contract between a member and the consortium, and thereby obligating the applicant to abide by the rules of the organization, including its IPR Policy<sup><a href="#6">6</a></sup></li>
			</ul>
			<p>Upon formation of a membership corporation, all of the initial concerns have been satisfied: a liability shield has been created, an entity exists that can create and own IPR, sign contracts, and employ staff (if desired), and a workable governance structure has been provided within a reliably enforceable statutory context. Moreover, if the documents used are already familiar to the members by reason of membership in other consortia built upon the same models, legal review by members will be far faster than would be the case if a custom, non-incorporated model were to be employed.</p>
			<p><strong>2.3.2 &mdash; Limited Liability Corporations.</strong> A small number of consortia have been created based upon this model. Limited liability corporations (usually referred to simply as "LLCs") came into being comparatively recently, but may now be created in every US state, with the enabling rules varying to some extent among jurisdictions. LLCs provide essentially all of the same legal protections and capabilities as the traditional corporation, but under rules that are in some respects more flexible.</p>
			<p>This flexibility provides a mixed blessing. On the one hand, the members of an LLC may "opt out" of certain unavoidable constraints to which all corporations are subject. But on the other, this same flexibility leads to the need to provide for more detailed and customized documentation to accomplish the same results. And, since much more language is now custom rather than closely derivative of statute, there is less certainty as to how a court would construe and enforce that language in the case of a dispute.</p>
			<p>Another result of this customization and lessened certainty of result is that members are more likely to conclude that the close attention of their own counsel must be directed at the formation documents, which can lead to higher formation costs and a delayed launch date for the new organization.</p>
			<p>As a result, and as is the case in many commercial settings, an LLC structure is usually used to form a consortium only when the simpler, traditional corporate structure will not permit some important objective to be satisfied.<sup><a href="#7">7</a></sup></p>
			<p><strong>2.3.3 &mdash; Semi-autonomous, hosted models.</strong> A few SSOs have from time to time decided to offer hosting services to other, typically smaller, standard setting initiatives. This allows a modest SSO to have most of the advantages of being incorporated and staffed, without actually having to take the necessary actions to achieve either status.<sup><a href="#8">8</a></sup> The host typically offers most administrative, and sometimes other, services for a fee. The hosted SSO then adopts it's own, shorter set of bylaws (often using a form provided by the host), as well as its own (or the host's) IPR policy, and commences operations. This arrangement offers a sort of hybrid existence that is mid-way between a working group of an SSO and an independent organization. Like the former, it relies on the host for its infrastructure and services. But like the latter, it is largely autonomous when it comes to governance, setting its dues, charting its technical program, and deciding what other activities, if any, it wishes to include in its programs.</p>
			<p>In addition to the availability of services on demand and the corporate liability shield and tax exemption that may be provided by the host, this hosted option typically permits a new initiative to get up and running quickly. The most common disadvantages that have sometimes been encountered with this model include high cost relative to services rendered and, at times, poor service, especially where the hosting activity was not the primary business of the host.</p>
			<p>In contrast, the service providers that provide hosting activities as their sole business activity focus all of their attention to that function, and as a result may provide superior service at similar, or lower, cost. More typically, they will also assist their customers in becoming incorporated, rather than otherwise (this is advantageous for the SSO, as well, which as a result has greater flexibility in choosing the service provider from which it purchases services).</p>
			<p>The most significant difference between non-profit and for-profit hosts may be that a for-profit host cannot provide tax-exempt status for its customers, providing another reason why their customers typically incorporate, even though they then contract with the host to provide some or all of their administrative, staffing, member support, and other needs.</p>
			<p><strong>2.3.4 &mdash; Non-incorporated models.</strong> By definition, non-incorporated models are more diverse, due to the fact that founders that choose this route are working from a clean slate. That said, non-incorporated initiatives may initially be divided into two groups: the "muddle along" and the documented. Muddle along initiatives, not surprisingly, are generally modest, and may be promotional, educational or otherwise more limited in ambitions than more determined standards development efforts. If the initiative proves to be worthwhile and ongoing, a non-documented effort will usually become incorporated or otherwise documented eventually &ndash; often when the in-house counsel of one or more members becomes aware of what is going on, without benefit of a liability shield.</p>
			<p>Where the decision is made to pay due attention to legal concerns but not incorporate, some sort of legally binding documentation must be created. As with LLCs, this means that more effort must be dedicated to spelling out all aspects of the organization's governance, membership, operations, duration, ownership rights, and other details than would be required if the founders had desired to incorporate.</p>
			<p>Notwithstanding a number of shortcomings (discussed below) of the non-incorporated model, this approach is still common, especially in situations where a limited number of companies wishes to create a specification that may infringe upon patents owned by many or all founding members. In short, the goal of the founders may be to simply add rules relating to joint development activities to a typical cross-license agreement. In this model, a "promoter adopter" structure is often utilized, in which the core members (usually a group formed by invitation only) enter into a "promoter agreement," under which the promoters agree to use a specification contributed by one or more members, or to jointly create a specification needed by all to (for example) create a new product that requires interoperability among all vendor offerings.</p>
			<p>Under the terms of the promoter agreement, each promoter typically provides the group with a royalty-free cross license under all of its necessary patent claims under the specifications created by the organization. The promoter agreement also permits each promoter to sublicense the right to implement the same specification, subject to the patent rights of each promoter. All promoters typically agree to make patent licenses available to all such sublicensees under reasonable and non-discriminatory (RAND) terms.</p>
			<p>The right to implement the specification is provided to third parties under an "adopter agreement," using a mutually agreed upon form. Adopters may or may not still be required to enter into separate patent license agreements with each other promoter. The terms of these licenses may sometimes be more restrictive than might commonly be found in relation to standards that are developed by consortia based upon more open models.</p>
			<p>The promoter-adopter model is popular with a few companies with very large patent portfolios, and is most often found in the market niches occupied by these companies. The advantages of the promoter-adopter model include the following:</p>
			<ul>
				<li>A high degree of certainty regarding patent rights among promoters and adopters (adopters are usually asked to provide a license to their own necessary claims under the specification back to the promoters, or may at least lose their license if they sue any promoter for infringement)<br /><br /></li>
				<li>A light-weight document structure, since the promoter agreement typically provides for all obligations (formation, governance and IPR related) in a single agreement, and the shorter adopter agreement provides all that an adopter needs, other than any direct licenses required by one or more promoters<br /><br /></li>
				<li>A reasonably standardized document package, due in part to the fact that a large percentage of the organizations based upon this model have been founded by a small number of companies.</li>
			</ul>
			<p>The disadvantages of the promoter-adopter model (and all other non-incorporated approaches) are equally significant. They include the following:</p>
			<ul>
				<li>There is less certainty of legal enforceability in general in comparison to the corporate model, since terms must be legally interpreted on their own merit, unlike bylaw provisions, which typically track an enabling statute word for word, and can be interpreted in the context of the voluminous case law that has accumulated over the years.<br /><br /></li>
				<li>Where certainty of result does exist, it is not always welcome. For example, regardless of any language that is included in the operative agreement among the members of an unincorporated consortium, applicable law may deem the arrangement to be equivalent to a partnership, subjecting all members to joint liability not only with respect to the debts or actions of the organization itself, but potentially for the acts or omissions of any single member when that member is arguably acting on behalf of the organization.<br /><br /></li>
				<li>Third parties may be unwilling to accept a signature on behalf of an unincorporated entity. Nor can such an organization easily hire employees.<br /><br /></li>
				<li>Each member's balance sheet would need to carry its allocable share of the profits and losses of the organization.<br /><br /></li>
				<li>If membership is by invitation only, the specifications that are created are inherently more proprietary and less open, at least by appearance, and often in practice.<br /><br /></li>
				<li>If more than a single class of membership is needed, the documentation becomes more complex.</li>
			</ul>
			<p>For these and other reasons, non-incorporated models are less often used than corporate models. When they are, it is often due to one of the following reasons: the founders are only familiar with the unincorporated model; they wrongly believe that forming a corporation would be more expensive and complicated; or the goals of the founders are limited, as when the intention is to create and maintain a single specification.<sup><a href="#9">9</a></sup></p>
			<p><strong>2.4 &mdash; Jurisdiction of formation.</strong>The laws under which a given consortium may be formed, unfortunately, may be determined more as a result of the attorney chosen to represent the new entity than by a conscious weighing of the appropriateness of the laws of one jurisdiction over another. In fact, corporate statutes, and particularly not-for-profit corporate statutes, vary from jurisdiction to jurisdiction. While those statutes have tended to become progressively more similar over time than the opposite, important differences can remain from state to state.</p>
			<p>The reasons for choosing one jurisdiction over another should include the following:</p>
			<ul>
				<li><strong><em>Flexibility:</em></strong> How much freedom is permitted in structuring the entity? If desired, can essentially all powers (other than the election of directors) be vested in a Board of Directors, to provide for speed and ease of governance, or must some powers be shared with members? Must the Board operate according to traditional board rules, or can it provide for different methods of operation (e.g., acting by less than unanimous written consent), in order to facilitate the operations of what are increasingly likely to be virtual organizations with boards of directors drawn from a global membership? For similar reasons, can alternate directors be appointed to substitute for primary directors when the latter cannot attend a meeting?<br /><br /></li>
				<li><strong><em>Familiarity:</em></strong> Consortia typically strive to set global standards, and therefore to attract a global membership. Outside of the US, only the laws of a few states would be familiar with many potential members and their counsel. Even within the US, the laws of small states may be less well known than those that host the headquarters of many Fortune 500 companies.<br /><br /></li>
				<li><strong><em>Extraneous concerns:</em></strong> States vary in the degree to which they differentiate among types of non-profit corporations. As a result, a state that is more concerned with farm co-ops, churches, fraternal organizations and public charities may have a less useful non-profit statute than one that contemplates the needs of business-oriented organizations as well.<br /><br /></li>
				<li><strong><em>Degree of regulation:</em></strong> Some states have more extensive social or other regulations (or just more regulations, full stop).<sup><a href="#10">10</a></sup></li>
			</ul>
			<p>This author has formed over 50 consortia as not for profit membership corporations under Delaware law, for a variety of reasons, including the following:</p>
			<ul>
				<li>Delaware traditionally represents the most advanced and progressive jurisdiction with respect to corporate law.<br /><br /></li>
				<li>Of all US jurisdictions, Delaware law is mostly likely to be familiar to US and foreign lawyers.<br /><br /></li>
				<li>Delaware law provides unique flexibility with respect to the operation of the board of directors of a non-stock corporation, making it easier to conduct the affairs of a consortium with a board that typically includes many busy international executives.<br /><br /></li>
				<li>The differences between Delaware corporations that have stock and those that do not are minor, and almost always provide for additional flexibility.</li>
			</ul>
			<p>Happily, reincorporating in Delaware is neither expensive nor difficult. If the board or management of an existing consortium finds that it has been created under laws that prove to be unduly restrictive, a new corporation can be formed in Delaware, and the existing organization simply merged into the newly created shell.</p>
			<a name="section3"></a><h3>III &ndash; Antitrust Considerations</h3>
			<p>Whether incorporated or not, consortia need to adopt a number of policies at, or not long after, inception. Those policies are necessary to provide further guidance for the conduct of activities, as well as to regulate behavior in order to steer clear of potential liabilities. One of the most important policies relates to compliance with antitrust laws.</p>
			<p>By their nature, SSOs are organizations that bring direct competitors together in the same room for the purposes of engaging in joint action. As a result, the antitrust laws &ndash; and the potential liabilities that can arise from being insufficiently aware of their prohibitions &mdash; are particularly relevant to the operations of SSOs.</p>
			<p>Happily for SSOs, over the last quarter century the antitrust laws in the United States have become progressively more favorable to pro-competitive collaborative activity among competitors. For example, in 1983, Congress passed the National Cooperative Research Act, which was later amended to cover production activities as well (the Act was concurrently renamed the National Cooperative Research and Production Act, and is commonly referred to as the NCRPA).<sup><a href="#11">11</a></sup></p>
			<p>More recently, in December of 2005, Federal Trade Commission Deborah Platt Majoras delivered a policy speech in which she made it clear that the FTC looked with favor on the pro-competitive effects of standard setting in general, and in particular would be open minded in considering appropriately conducted disclosures of licensing terms during the standards process (so call <em>ex ante</em> disclosure).<sup><a href="#12">12</a></sup> On October 30, 2006, the FTC made good on this invitation, and issued a favorable business review letter to the VMEBus International Trade Association (VITA), which had proposed amending its IPR Policy to expressly require <em>ex ante</em> disclosure.<sup><a href="#13">13</a></sup></p>
			<p>All of this good will on the part of the regulators aside, the fact remains that those that engage in standard setting and related activities must be mindful of where the boundaries of permissible behavior are located, because the penalties for overstepping those limits can be severe. Given that consortia operate globally, the antitrust laws of many countries may bear upon their activities, and both the specifics, as well as the underlying social policies, of these laws can and do vary.</p>
			<p><strong>3.1 &mdash; United States Antitrust Laws.</strong> While a comprehensive review of even US antitrust law is far beyond the scope of this article, the following will serve as a brief introduction to the type of concerns that those that would form or participate in SSOs should be aware.</p>
			<p>Broadly stated, the basic objective of the US antitrust laws is to preserve and promote competition and the free enterprise system. These laws are premised on the assumption that private enterprise and free competition are the most efficient ways to allocate resources, to produce goods at the lowest possible prices and to assure the production of high quality products. These laws require that business people make independent business decisions without consultation or agreement with competitors.</p>
			<p>The US antitrust statutes of principal concern to companies and individuals that take part in trade association activities are Section 1 of the Sherman Act and Section 5 of the Federal Trade Commission (&ldquo;FTC&rdquo;) Act. These laws render illegal all contracts, combinations, and conspiracies which are deemed to be in restraint of trade.</p>
			<p>Broadly speaking, the courts have interpreted these laws as prohibiting those contracts and combinations that have the effect of unreasonably restraining trade. A court will, therefore, examine all the facts and circumstances surrounding the conduct in question in order to ascertain whether the contract or combination is in violation of the law by restraining trade unreasonably.</p>
			<p>Many activities are, however, regarded as unreasonable by their very nature and are therefore considered to be illegal &ldquo;per se.&rdquo; Companies and individuals are conclusively presumed to engage in these activities for no other purpose than to restrain trade. Practices within the per se category include agreements to fix prices, agreements to boycott competitors, suppliers or customers, agreements to allocate markets or limit production, and certain tie-in sales. A tie-in sale is one in which the customer is required to purchase an unwanted item in order to purchase the product or service desired.</p>
			<p>The legality of activities of an SSO or other standards-related consortium and its members under the antitrust laws is determined by the application of standards no different from those used to determine the legality of the activities of other groups of persons or firms. Special problems do arise, however, from the fact that a consortium necessarily brings competitors into a joint enterprise, and the act of bringing these competitors together creates the means by which collusive action can more easily be taken in violation of the antitrust laws.</p>
			<p><strong>3.2 &mdash; Penalties for Violations. </strong>The US antitrust laws are enforced at the Federal level by the Antitrust Division of the Department of Justice and the Bureau of Competition of the Federal Trade Commission.&nbsp; State court actions may be brought by U.S. State attorneys-general or injured parties under the antitrust laws of individual states as well.</p>
			<p>A criminal conviction for a federal antitrust law violation may result in stiff fines for a consortium and its members, jail sentences for individuals (including an individual acting in his or her capacity as a corporate employee or officer) who participated in the violation, and a court order disbanding the consortium, or severely limiting its activities. In the past, several foreign nationals have been sentenced to serve time in U.S. prisons, and corporations convicted of such a criminal offense have been fined hundreds of millions of dollars.</p>
			<p>In addition, private persons or firms may sue for damages under the Federal antitrust laws, and a company found liable may be required to pay up to three times the actual damages suffered by the plaintiff, as well as all of the plaintiff's costs of litigation and attorneys' fees.</p>
			<p><strong>3.3 &mdash; Antitrust policies and monitoring.</strong> Given the above, it is not surprising, that consortia, like other trade associations, require antitrust education for Boards of Directors, committee chairs and members, as well as ongoing monitoring by legal counsel. As a result, the necessary capabilities of counsel assisting in the formation and representation of a consortium include knowledge of antitrust laws, and the duties of such counsel at the time of formation include:</p>
			<ul>
				<li>Evaluating the goals and contemplated activities of a prospective organization, and advising on how they may be most appropriately conducted.<br /><br /></li>
				<li>Structuring formation documents in such a way as to protect against abusive activity, and providing for due process where needed to protect members against such abuse.<br /><br /></li>
				<li>Advising on the most cost-effective practices for ongoing legal review, based upon the budget of the new organization.<br /><br /></li>
				<li>Supplying appropriate antitrust policies for adoption by the Board, and antitrust memoranda suitable to alert members to prohibited conduct.</li>
			</ul>
			<p>Following formation, the management of a consortium must take care to abide by the policies adopted, in order to lessen the chance of expensive mistakes.<sup><a href="#14">14</a></sup></p>
			<a name="section4"></a><h3>IV &ndash; Intellectual Property Rights</h3>
			<p><strong>4.1 &mdash; Intellectual Property Rights Policies.</strong> The second area that should be promptly addressed by adoption of a policy relates to IPR. For decades, IPR policies for SSOs were low priority items of little interest (and remain so in many traditional industry sectors). However, beginning with an FTC consent decree agreed to by Dell Computer in 1996, under which Dell gave up any right to charge royalties on patents it had not disclosed in the course of a standard setting activity, those participating in SSOs active in the information and communications technology (ICT) sectors began taking increasing interest in the rules to which they would become subject when they participated in a given SSO.<sup><a href="#15">15</a></sup></p>
			<p>For better or worse, intellectual property rights (and particularly patents) lie at the heart of standard setting and consortium activities. For a variety of reasons &mdash; not the least of which is avoiding liability under antitrust and other laws &mdash; it is essential for a consortium to adopt a carefully written IPR policy to govern its activities.&nbsp; And then, of course, it must follow that policy, rather than relegate it to the status of a document in a drawer.</p>
			<p>To make matters more complex, the actual terms of an IPR policy should be the opposite of what would be desired elsewhere in the commercial world. Newcomers to standard setting must therefore reorient their thinking to accept that giving away rights in some IPR can be more advantageous than charging others for access rights to the same rights. The biggest challenge for some lawyers can therefore be grasping the fact that standard setting is about giving away rights in some IPR in order to make money on other technology. This means that those who would form a consortium must enter into a sort of "through the looking glass" world where patents are impediments rather than tools, royalties are unwanted encumbrances, licenses exist for the sake of disclaiming rights, and competitors are as welcome as partners. It is very hard for many individuals that have lived their lives in the proprietary world of commercial R&amp;D to cross this threshold. Even among those that are expert in the area of standard setting, there is a great diversity of opinion over exactly what an IPR policy should say, although a consensus has emerged regarding what such a policy should cover. And while many small companies take little interest in the details of an IPR policy, lawyers representing companies with large patent portfolios not surprisingly take a great interest in what the individual terms for a specific SSO IPR policy should say, as well as in the exact words used to establish those terms. Because the stakes are so high, few large companies are willing to join a new consortium until the full and final text of the IPR policy of that organization has been agreed upon.</p>
			<p>As a result, creating an IPR policy has become a major hurdle to clear in forming a new consortium, and can seriously delay the launch of a new organization in consequence. A major task for the founders, and the legal counsel selected to assist them in forming a new consortium, is therefore achieving consensus as quickly as possible on the substance and text of that document.<sup><a href="#16">16</a></sup></p>
			<p>In order to put an effective IPR Policy into action, commitments by members must be collected on standard forms at specified points in time during the standard setting process, and then an archive of these materials maintained on a perpetual basis. As a result, a technical and administrative structure (often Web-based) must be created soon after formation in order to enable the proper implementation of the IPR Policy itself.<sup><a href="#17">17</a></sup></p>
			<p><strong>4.2 &mdash; Policies and Procedures of the Technical Committee.</strong> For an SSO, the companion to the IPR Policy is a detailed document setting forth all of the day by day rules of the technical process, such as notice and quorum requirements, meeting rules, chairperson duties, and so on. This is the primary guide for the chairs of committees, and should be sufficiently comprehensive and detailed to provide all of the rules necessary to enable the technical process to function efficiently and effectively.</p>
			<p>Prior to creating such a document, the technical structure of the organization must be designed. For a consortium that wishes to develop and maintain a single standard, the structure will obviously be simple, comprising a single technical committee, possibly with a few working groups operating under it. If work will commence on multiple standards from the beginning, however, attention must be paid to how any contradictions between standards that are evolving simultaneously will be addressed and resolved.<sup><a href="#18">18</a></sup></p>
			<a name="section5"></a><h3>V &ndash; Tax Considerations<sup><a href="#19">19</a></sup></h3>
			<p><strong>5.1 &mdash; Overview.</strong> While most consortia do not operate at any significant profit, there are benefits to obtaining tax-exempt status. The most obvious benefit (apart from not having to pay taxes on most types of income), is that the organization is freed from the chore of seeking to "zero out" its profits at the end of each year. By obtaining exempt status, financial planning for the organization is greatly simplified.  However, if it is impossible to meet the requirements of tax exemption without restricting the activities that would permit the organization to achieve its mission, it is better to forego the small benefit that tax exemption may offer for what are, after all, the typically more or less break-even operations of a consortium.</p>
			<p>It is also possible for a consortium to have it both ways &ndash; conducting its tax exempt activities through a parent organization, and its taxable operations (e.g., a trade show) through a for-profit, taxable subsidiary.</p>
			<p>Happily, the majority of consortia can be formed as federally tax-exempt trade associations without restricting their mission or activities, most advantageously under IRS Section 501(c)(6).<sup><a href="#20">20</a></sup> Some consortia and SDOs have also been formed as public charities under IRS Section 501(c)(3), which offers certain advantages that are rarely advantageous for modern consortia.<sup><a href="#21">21</a></sup> On the other hand, both federal as well as state laws are more restrictive for charities than for trade associations. For example, a public charity in Massachusetts that wished to dissolve would be required to submit its plan of assets distribution to the state attorney general for review, and for final approval by a state court. A trade association would be subject to no such process, nor would it be required to obtain an annual audit at such time as its annual income crossed a certain threshold.</p>
			<p>In order to secure tax exemption, a consortium must prepare and file a detailed application that describes its proposed activities and budget, and which must be accompanied by its bylaws, charter and other documentation. The goal of the application is in large part to describe the "tax exempt purpose" that the organization wishes to pursue. Since the grant of an exemption only applies conclusively to the purpose and proposed activities as described in the application and its attachments, it is important that these activities be described comprehensively. This may mean that in some cases it is prudent to delay filing the application for up to a year, if the full range of activities of the organization may only be determined after public announcement of the new organization, and further recruitment of members.</p>
			<p><strong>5.2 &mdash; Eligibility rules.</strong> A number of criteria control which types of organizations may, and may not, achieve tax exemption.</p>
			<p><strong>5.2.1 &mdash; Qualifiers</strong>. There are a number of steps that must be taken in order to obtain tax-exempt status. As a first step, an organization must be organized in a fashion that will satisfy certain qualification criteria set forth in at least one of the various subsections of Section 501(c) of the Internal Revenue Code. The second step is to file an application with the IRS seeking a ruling that the organization is tax-exempt. While most people are more familiar with charitable and educational organizations exempt under Section 501(c)(3), the vast majority of technology consortia obtain their exempt status instead under Section 501(c)(6). Section 501(c)(6) grants tax-exempt status to:</p>
			<blockquote>&hellip;business leagues, chambers of commerce, real estate boards, boards of trade or professional football leagues&hellip;, not organized for profit and no part of the net earnings of which inures to the benefit of any private shareholder or individual.</blockquote>
			<p>The definition of a business league includes trade associations.</p>
			<p>In order to obtain tax-exempt status under Section 501(c)(6), several tests must be met. First, the organization has to be organized and operated as a not-for-profit. This can be accomplished by incorporating under a nonprofit or nonstock statute. Second, the organization cannot permit any "private inurement." That is, the net earnings of the consortium cannot be distributed to members or shareholders either directly or indirectly (e.g., through dividends or "sweetheart" deals with members).</p>
			<p>Private inurement is not often an issue, but it can arise where members contribute technology in exchange for royalties or license fees that the IRS deems excessive (typically in excess of an arm's-length amount). Another context in which private inurement can arise is where a founding member provides management services in exchange for a management fee. Again, while management and license fees are not impermissible on their face, those fees must be carefully set to avoid being in excess of what would be paid to an unrelated third party for comparable services or property. Typically, even with careful disclosure of all details, the IRS will nevertheless request further details regarding such relationships when they are noted in the exemption application.</p>
			<p>A consortium must also meet the definition of a business league. The statute does not define this term, but IRS regulations and the courts have fleshed out a number of requirements that must be satisfied in order to obtain tax-exempt status under Section 501(c)(6). Those requirements can be summarized as follows:</p>
			<ul>
				<li>The existence of a common business interest,<br /><br /></li>
				<li>The organization must as a primary activity promote this common business interest,<br /><br /></li>
				<li>The activities of the entity must be directed to the improvement of business conditions of one or more lines of business,<br /><br /></li>
				<li>The organization cannot be engaged in a regular business of a kind ordinarily carried on for profit, and<br /><br /></li>
				<li>The primary activities of the entity must not be confined to the performance of particular services for individual members.</li>
			</ul>
			<p>Notwithstanding the numerous tests that must be met in order to be classified as a trade association, the "real" test is whether the trade association is engaging primarily in the conduct of activities which benefit an entire industry as opposed to the interests of the individual members of the association only. With most trade associations, there is a fine line between activities that benefit the specific members and activities that benefit the entire industry in which those members generally operate. The five tests enumerated above are all geared towards making this determination.</p>
			<p>It is the focus on standards that have the potential to better the entire industry that typically qualifies SSOs as tax-exempt trade associations &ndash; provided that they make their standards available to non-members and members alike.&nbsp; This is true even where only members are permitted to play an active role in setting the standards, and may receive a discount in the pricing of certification testing or other services relating to the standards; the reason is that these benefits are viewed as being incidental to the overall benefit to the industry.</p>
			<p>On the other end of the spectrum, an organization that is nothing more than a joint marketing collaborative typically will not qualify as a trade association because its activities are focused on the improvement of business conditions for the individual members themselves and not for a broader industry group. For example, if the organization promulgates and promotes standards for its members only, tax-exempt status would be difficult to achieve because the standards would simply enhance the competitive position of the members vis-&agrave;-vis the industry at large.</p>
			<p>The existence of a common business interest is generally satisfied so long as the consortium represents an established industry and addresses at least one business issue or concern common to the members of that industry. Where the organization represents members of multiple industries, a common business interest can still be found, provided that all of the consortium members have common issues of one type or another. The only distinction between a situation where there is a single clear industry and a situation involving members of multiple industries is that the IRS will generally apply greater scrutiny in determining a common business interest where the membership represents more than one traditional industry.</p>
			<p>Having found a common business purpose, the next requirement is that the organization "promote" the common business interest. Activities that are found to be in the nature of "particular services" to the members or that are considered "unrelated" to industry promotion do not promote the common business interest of its members and weigh against exempt status.</p>
			<p>The simplest example of "promotion" is industry marketing. It is critical to note, however, that the marketing must be of the industry itself and not of the individual member companies. Promotion will not satisfy this requirement where the activities are comprised of simply advertising association member companies' products. For example, a publication consisting of paid advertisements by the association's members is a classic example of an activity that does not adequately promote an industry.</p>
			<p>The third, fourth and fifth requirements are actually very similar and the IRS and the courts have treated them as different ways of saying the same thing. The third requirement is the key to exemption in that the consortium activities must be directed toward the improvement of conditions of one or more lines of business, as distinguished from the performance of particular services for individual members. This characteristic imposes two separate, interrelated requirements: (a) the organization must represent one or mores lines of business, and (b) it must not be primarily directed to performing particular services for individual purposes.</p>
			<p>The "line of business" requirement is quite similar to the industry requirement discussed previously. The IRS has ruled that a trade association can satisfy the "line of business" requirement even though the association members are from diverse industries or professions so long as they focus on particular business issues that are common to members of those diverse industries.</p>
			<p><strong>5.2.2 &mdash; Eligibility Disqualifiers.</strong> The "particular services" proscription is sometimes more problematic for consortia. The principal challenge in this area is to distinguish between association services that chiefly benefit the industry as a whole, but would also provide an incidental benefit to individual members, from those services that are chiefly of value to members and their own businesses, with the industry benefits being subordinate.</p>
			<p>A "particular service" in this context is defined as a benefit that is merely a convenience or economy to members of an association in the operation of their individual businesses. That is, if a trade organization provides members with a low cost, or otherwise more conveniently available service or product that its members would otherwise be expected to obtain in the normal course of their business, then the association may be found to be providing a "particular service to its members." It has been held in one case that "any activity or service&hellip; which would otherwise have to be done by or for the member in order for him to properly to perform his business, must be classified as a particular service." For example, providing insurance or consulting services to the members of an association will typically be treated as a provision of a "particular service" as these would relieve the association members of obtaining the same services on an individual basis from a non-exempt commercial business.</p>
			<p>The mere provision of some "particular services" does not result in a loss of exempt status, but a trade association may not be "primarily" engaged in the provision of particular services. That typically means that so long as less than 50% of the activities and revenue of the association are comprised of "particular services", then the organization may still be treated as exempt under Section 501(c)(6). Even if exempt, however, the fees for the provision of "particular services" (or the dues allocated to those services) are typically treated as "unrelated business taxable income." The organization will be required to pay taxes on this revenue regardless of the organization's overall exempt status.</p>
			<p><strong>5.3 &mdash; Process.</strong> Assuming that all qualification criteria are satisfied, the specifics of obtaining tax-exempt status are fairly straightforward. Following formation, the consortium will file a Form 1024 with the IRS seeking a ruling that its activities result in tax-exempt status. Unlike charitable organizations exempt under Section 501(c)(3), which are required to obtain a favorable ruling from the IRS, the statute does not require a ruling from the IRS that a Section 501(c)(6) organization is exempt. In other words, if the organization otherwise meets all of the qualification criteria, then there is no requirement that a ruling be obtained. Unfortunately, the IRS does not agree with this interpretation of the statute (even though it is quite clear) and takes the position that an organization cannot be exempt without a favorable ruling.</p>
			<p>In order to avoid any dispute, it is therefore standard practice to file a Form 1024 in all cases. This has the added benefit of providing certainty of treatment in the event of an IRS audit. Care must be taken in preparing the Form 1024 because the ruling obtained is based strictly on the facts enumerated. If the consortium engages in other activities, the ruling will not cover those activities and this can cause a loss of exempt status notwithstanding a favorable determination. Accordingly, a supplemental filing should be made whenever there is a significant change in the activities or organizational structure of the consortium after the date of its original application.</p>
			<p><strong>5.4 &mdash; Operations as a Taxable Entity.</strong> If exemption appears to be unlikely, or is denied on application, the consortium will be taxed in the same manner as any other taxable entity. As a result, it is advisable to operate as nearly as possible on a break-even basis until exemption has been granted, or until a decision is made to abandon further efforts to seek exemption after one or more exchanges with the IRS examiner reviewing the exemption application without achieving success. If that decision is made, it should be anticipated that somewhat higher compliance costs will be encountered in connection with making necessary tax filings on an ongoing basis.</p>
			<a name="section6"></a><h3>VI &ndash; Certification and Branding</h3>
			<p>Most technology consortia are formed to promote as well as create standards.<sup><a href="#22">22</a></sup> Promotion will often involve more than simply raising awareness of the existence of standards, because in order to achieve wide adoption, it is necessary for a standard to be well respected as well as well known. This is particularly true in the case of standards created to enable interoperability of products, where such standards enable end-users to assemble systems bought from multiple vendors. Interoperability has become doubly important with the advent of the standards-based Internet and the Web, which enable global communications and information exchange.</p>
			<p>Accordingly, both vendors and users place a high degree of reliance, and therefore value, on compliance with effective standards to ensure that products purchased will "plug and play." The way in which vendors capitalize on this value can be by forming a consortium to test and certify compliance with a standard, and to create good will and brand recognition in a distinctive trademark that indicates such compliance (the "WiFi" brand is a good example). In order to maintain value in the market recognition so created, a mechanism is needed by which the consortium can assert the legal right to prevent false assertions of compliance.</p>
			<p>Consortia, like their commercial members, achieve this result by creating distinctive trademarks and logos that (in this case) relate to a given standard. The consortium also adopts a policy which provides that these same marks may only be used in connection with products that have successfully passed whatever regime it has established to indicate compliance. Where a vendor falsely asserts compliance with a trademarked standard, the consortium can revoke the vendor's right to use the name of the specification and any consortium logos in connection with its products.</p>
			<p>Planning for a proper certification and trademark program is essential to the success of some consortia (e.g., where consumer products are involved). The legal preparations for such a program include the following:</p>
			<ul>
				<li>Conduct of conflict searches in jurisdictions of interest for the trademarks and logos to be used in connection with the program<br /><br /></li>
				<li>Preparation and filing of national and regional trademark applications in targeted jurisdictions<br /><br /></li>
				<li>Creation of test suites, and preparation of license agreements for such suites<br /><br /></li>
				<li>If a third party is to be used for certification testing, negotiation of agreements with such vendor(s)<br /><br /></li>
				<li>Preparation of trademark usage guidelines<br /><br /></li>
				<li>Drafting of trademark licensing agreements for compliance or certification marks and logos</li>
			</ul>
			<p>While trademark searches and registrations need to be undertaken at the time of formation if the related brands have been selected prior to that date, the other actions described above need not be taken until a standard has actually been completed. Nevertheless, the later requirements should be anticipated at the time of formation, as well as any promotional expenses that will need to be incurred in connection with the program. As a result, the need for such an initiative should be assessed before the formal launch of the consortium, and a careful assessment of the costs of such a program should be included in developing the new organization's ongoing budget.<sup><a href="#23">23</a></sup></p>
			<a name="section7"></a><h3>VII &ndash; Summary</h3>
			<p>As the success or failure of a consortium and its standards is in large part driven by the care with which it is structured, it is important to take the time to properly form a consortium from the outset. That structure must then be properly implemented in documentation that provides effective tools for governance, protection from liability, and flexibility of operation. The result should be an effective platform that supports, rather than impedes, the activities of a consortium's members, and allows the new organization to grow and adapt to changing market circumstances.</p>
			<p>The combined experience of the hundreds of already existing consortia that are in operation today has provided a number of well-tested models upon which new organizations should almost always be based. Not only do these models offer real-world examples of successful structures and documentation, but utilizing such antecedents should facilitate recruitment of members that are already members of, and comfortable with, earlier-formed organizations.</p>
			<p>That said, simply copying the membership structure or documents of an existing organization is no more likely to result in success than copying another SSOs standards. In each case, and as demonstrated in the first installment of this article, the most appropriate generic model must be adapted to the goals, target membership, required activities and other unique circumstances of the new initiative, with the legal language following rather than leading the planning process.</p>
			<p class="note"><strong>NOTE:</strong> If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a> if you have questions about this topic.</p>
			<p class="center">Copyright 2007 Andrew Updegrove</p>
			<p><strong>End Notes</strong></p>
			<p><a name="1"></a><sup>1</sup> Part I focused on: defining scope, determining necessary deliverables, identifying and segmenting target membership groups, creating member value propositions, developing budgets and determining appropriate dues structures, designing a staffing model, and adopting key policies, among other considerations. <em>see</em> Updegrove, Andrew, Creating a Successful Consortium &ndash; Part I. ConsortiumInfo.org, Consortium Standards Bulletin, Vol. V, No. 10 (November 2006), at &lt;http://www.consortiuminfo.org/bulletins/nov06.php#feature&gt;. This article is one of a continuing series on creating and participating in standard setting organizations. They are collected as the <a href="/essentialguide/">Essential Guide to Standards Setting Organizations and Standards</a> at the ConsortiumInfo.org site, and can be found at &lt; http://www.consortiuminfo.org/essentialguide/&gt;.</p>
			<p><a name="2"></a><sup>2</sup> It is important for readers to note that this article is summary in nature, non-specific to the law of any particular jurisdiction, and not tailored to the unique goals and circumstances of any individual situation. Accordingly, this article is not intended, and must not be regarded as rendering legal advice to any reader, or to any consortium. Actual legal advice should only be rendered by a qualified attorney that is given the particular facts at hand.</p>
			<p><a name="3"></a><sup>3</sup> There is no universally acknowledged nomenclature for types of standards development and supporting organizations. For example, non-accredited organizations will often have one of the following words in their names: "consortium," "forum," "alliance," or "SIG" (i.e., Special Interest Group), and such organizations are often referred to as a group by one or the same names.&nbsp; For purposes of this article, all non-accredited organizations are referred to collectively as "consortia."</p>
			<p><a name="4"></a><sup>4</sup> Legal issues of ongoing concern to SSOs, as compared to those that are relevant primarily at the time of formation, are dealt with in depth at the <em><a href="/laws/">Laws, Cases and Regulations</a></em> section of the <a href="/essentialguide/">Essential Guide to Standard Setting and Standards</a>, at &lt; http://www.consortiuminfo.org/laws/&gt;.</p>
			<p><a name="5"></a><sup>5</sup> <a href="http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST">http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST</a></p>
			<p><a name="6"></a><sup>6</sup> Preparation of these documents can be made faster and cheaper through the use of appropriate tools. The author uses a formation proposal template that is adapted in consultation with the client, and includes not only guidance on all variable aspects such as membership classes, but also templates for budget, public relations roll out, staffing and launch timetable. A small working group of founders helps complete the proposal template, which is then approved by the full founder group, after which the formation documents can be easily and accurately prepared for final review by the founders and their counsel.</p>
			<p><a name="7"></a><sup>7</sup> One reason that an LLC structure has sometimes been employed by organizations with limited membership is to avoid the duties that directors of a traditional corporation would have to represent the interests of all members. Where this is the goal, language is added to the LLC operating agreement (which acts as the surrogate for corporate bylaws) that explicitly disclaims any such obligations. As a result, each member entitled to appoint a manager of the LLC may instruct its representative to act solely in the interests of the member that appoints her. That individual may then so act, without concerns over personal liability.</p>
			<p><a name="8"></a><sup>8</sup> Two organizations that currently offer such hosting services include The Open Group and the IEEE's ISTO program.</p>
			<p><a name="9"></a><sup>9</sup> The author has often been retained to convert such organizations into incorporated entities, when the shortcomings of the original structure became apparent.</p>
			<p><a name="10"></a><sup>10</sup> Degree of regulation also becomes significant when considering where to base a consortium, regardless of where it is legally formed. For example, the same consortium that has chosen to obtain tax exemption under IRS Section 501(c)(6) as a trade association would not be required to file for a separate tax exemption in Massachusetts &ndash; but would in California.</p>
			<p><a name="11"></a><sup>11</sup> The NCRPA was most recently amended in 2004, to specifically provide a measure of antitrust protection when creating standards &ndash; but only for SSOs, and not for their members. In the opinion of this author, this amendment was as much a step backwards as forwards. <em>see</em> Updegrove, Andrew, <em>What Does 1086 Mean to Consortia?</em> ConsortiumInfo.org, Consortium Standards Bulletin, Vol. III, No. 6 (June 2440), at &lt; http://www.consortiuminfo.org/bulletins/jun04.php#update&gt;.</p>
			<p><a name="12"></a><sup>12</sup> Deborah Platt Majoras, Chairman, Fed. Trade Comm'n, Recognizing the Procompetitive Potential of Royalty Discussions in Standard Setting, address at Standardization and the Law: Developing the Golden Mean for Global Trade 7 (Stanford University, Sept. 23, 2005), &lt;http://www.ftc.gov/speeches/majoras/050923stanford.pdf&gt;.</p>
			<p><a name="13"></a><sup>13</sup> Letter from Thomas O. Barnett, Assistant Att'y Gen., U.S. Dep't of Justice, to Robert A. Skitol (Oct. 30, 2006), http://www.usdoj.gov/atr/public/busreview/219380.pdf; <em>see also </em>Press Release, U.S. Dep't of Justice, Justice Department Will Not Oppose Proposal by Standard-Setting Organization on Disclosure and Licensing of Patents (Oct. 30, 2006), <a href="http://www.usdoj.gov/atr/public/press_releases/2006/219379.pdf">http://www.usdoj.gov/atr/public/press_releases/2006/219379.pdf</a>&gt;.</p>
			<p><a name="14"></a><sup>14</sup> For a very detailed review of the antitrust laws and regulations applicable to SSOs, as well as descriptions of key cases and links to the full text of laws, regulations and cases, see the <em><a href="/laws/">Laws, Cases and Regulations</a></em> section of the <a href="/essentialguide/">Essential Guide to Standard Setting and Standards</a>, at: &lt; http://www.consortiuminfo.org/laws/&gt;.</p>
			<p><a name="15"></a><sup>15</sup> <a href="/laws/#dell"><em>Dell Computers, Inc., </em>Dkt. C-3658 (consent order, May 20, 1996)</a>. This case received wide attention in the press and sharply focused the attention of many companies, for the first time, on SSO IPR policies. The FTC began its investigation when Dell attempted to enforce a patent relating to "VL-bus" technology and centered upon whether the patent was enforceable in light of the fact that, contrary to VESA's IPR policy, a Dell representative had failed to disclose the patent to the Video Electronics Standards Association ("VESA") during the VL-bus standard development process. The defendant brought numerous counterclaims and Dell ultimately settled. As part of the consent decree whose issuance ended the FTC's investigation, Dell agreed that the patents at issue would not be enforced against ML-bus standard implementers, because they had not been disclosed by Dell to VESA.</p>
			<p><a name="16"></a><sup>16</sup> The author has drafted or revised IPR policies for more than 50 consortia, a process that has called upon his training as a certified mediator to a greater extent than any other aspect of his practice. The most convincing test of whether an IPR policy has been created that is as fair as possible for all participating members can be whether everyone is equally unhappy &ndash; but can still live &ndash; with the final policy. Truly, creating an IPR policy is the ultimate exercise in herding cats.</p>
			<p><a name="17"></a><sup>17</sup> For much more information on what an IPR policy should cover, and the variety of opinions on what individual terms should say, see the <em><a href="/ipr/">Intellectual Property Rights Policies</a></em> section of the <a href="/essentialguide/">Essential Guide to Standard Setting and Standards</a>, at &lt; http://www.consortiuminfo.org/ipr/&gt;.</p>
			<p><a name="18"></a><sup>18</sup> For much more detail on designing an effective technical process, see the November 2004 issue of the Consortium Standards Bulletin (<a href="/bulletins/nov04.php">What Makes the Technical Process Work?</a>), Vol. III, No.11, and particularly the Feature article, Updegrove, Andrew, <em><a href="/bulletins/nov04.php#feature">Creating an Effective Technical Process (a Practical Primer)</a></em>, at &lt; http://www.consortiuminfo.org/bulletins/nov04.php#feature&gt;.</p>
			<p><a name="19"></a><sup>19</sup> I am indebted to my former partner and colleague, Kenneth Appleby, for his assistance in preparing an earlier version of this section that appeared in the <em>Essential Guide</em>.</p>
			<p><a name="20"></a><sup>20</sup> This statement demands some qualification. But for an approximately 24-month period spanning 2002 &mdash; 2004, the author's law firm was successful in gaining tax exemption for scores of consortia, beginning in 1989. During this brief interregnum, the senior IRS staff in its Washington office raised a number of objections that had never been raised before. For example, the Service insisted that if more than one SSO was developing standards for a given industry, then none of the SSOs active in that area could claim to be representing "the industry" &ndash; a requirement for achieving exemption. As a result, in an emerging area such as wireless, no SSO would qualify for tax exemption, unless all merged into one. Had the Service applied this same analysis to existing SSOs, many venerable SDOs as well as consortia could have been stripped of their tax-exempt status. Happily, the IRS ceased raising this objection as suddenly (and mysteriously) as it had begun.</p>
			<p><a name="21"></a><sup>21</sup> For example, individual members of 501(c)(3) organizations may be able to deduct their membership fees, while the organizations themselves may send mailings at less than commercial postal prices. Historically, these rights were significant for SDOs with large memberships made up of individuals</p>
			<p><a name="22"></a><sup>22</sup> Some consortia are formed exclusively for the purpose of promoting and/or certifying compliance with standards developed by other organizations (which in this situation typically are SDOs, since accredited SSOs rarely support such activities). One of the most familiar current examples of this practice can be found in the WiFi Alliance, WiMedia Alliance, and WiMax Forum, each of which was formed to expedite the adoption of a wireless standards developed by an IEEE working group.</p>
			<p><a name="23"></a><sup>23</sup> For much more information on how to create and operate a certification and branding program, see the <em><a href="/cb/">Certification Testing and Branding</a></em> section of the <a href="/essentialguide/">Essential Guide to Standard Setting and Standards</a>, at &lt; http://www.consortiuminfo.org/ipr/&gt;.</p>
			<table class="GuideHelp">
				<tr>
					<td style="padding:12px;" valign="top"><a href="http://www.gesmer.com/attorneys/updegrove.php"><img src="images/guide_updegrove.jpg" width="69" height="106" border="0" alt="" /></a></td>
					<td valign="top">
						<p class="GuideHelpHead">Can We Help You?</p>
						<p class="GuideHelpBody1"><a href="http://www.gesmer.com/">Gesmer Updegrove LLP</a> is, quite simply, the most experienced law firm in the United States when it comes to representing and creating standards development organizations &mdash; <a href="http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST">more than 100</a> &mdash; to date.  If you need advice about participating in the standards development process, representation in standards-related litigation, intellectual property advice, or help creating a brand new SSO or open source foundation, we'd be pleased to help. Contact:</p>
						<p class="GuideHelpBody2">Email: <script language="javascript" type="text/javascript">AuGesAdd();</script><br />Tel: 617-350-6800</p>
					</td>
				</tr>
			</table>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
		</div>
	</div>
<div class="clear"><br /></div>
<!-- *********** -->
<!--   FOOTER    -->
<!-- *********** -->
<?php include '../includes/footer.php'; ?>
</form>
</body>
</html>