<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>The Essential Guide to Consortia and Standards</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta name="description" content="While standard setting has been an important aspect of industrial society for over a hundred years, the formation of unofficial, fast-acting standard setting and promotional consortia is a more recent phenomenon which is only now beginning to be seriously studied" />
<meta name="keywords" content="standard setting, promotional consortia, structuring of consortia, standardize, intellectual property policies, procedures, founding company, model, best practices, promoter/adopter structurer, joint venture, IPR, " />
<meta name="author" content="Andrew Updegrove" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/screen.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/guide.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/toolsets.css" />
<!-- ALTERNATE -->
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/default.css" title="default" />
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/large.css" title="large" />
<!-- ********* -->
<link rel="home" title="home" href="http://www.consortiuminfo.org" />
<script type="text/javascript">AC_FL_RunContent = 0;</script>
<script type="text/javascript" src="/scripts/AC_RunActiveContent.js"></script>
<script type="text/javascript" src="/scripts/styleswitcher.js"></script>
<script type="text/javascript" src="/scripts/obfuscate.js"></script>
</head>

<body id="bulletin">
	<!-- ****************** -->
	<!--   ACCESSIBILITY    -->
	<!-- ****************** -->
	<?php include '../includes/accessibility.php'; ?>
	
	<!--   SEARCH FORM   -->
	<form class="search" name="form1" method="get" action="http://search.Blossom.com/query/320">
	
	<!-- ************* -->
	<!--   MASTHEAD    -->
	<!-- ************* -->
	<?php include '../includes/masthead_subs.php'; ?>
	
	<!-- *********** -->
	<!--   BANNER    -->
	<!-- *********** -->
	<div id="banner">
		<div class="left">
			<p><a href="/">Home</a> &gt; <a href="/essentialguide/">Guide</a> &gt; Forming a Successful SSO Part I</p>
		</div>
		<div class="right">
			<p><input type="text" name="key" /><input type="submit" name="Submit" value="Search" /> <a href="/search/">Advanced</a></p>
		</div>
		<div class="clear"></div>
	</div>
						
	<!-- ************** -->
	<!--   MAIN BODY    -->
	<!-- ************** -->
	<div class="GuideContent">
	<!-- SKIP/START CONTENT LINK -->
	<a name="startcontent" id="startcontent"></a>
		
		<!-- SIDEBAR CONTENT AREA -->
		<div class="AllSidebar">
			<div>
				<?php include '../includes/clients.php'; ?>			
			</div>
			<div class="AllNav">
				<p class="AllNavTitle">Chapter 5:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section1" title="Introduction">I &ndash; Introduction</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section2" title="Mission, Scope and Deliverables">II &ndash; Mission, Scope and Deliverables</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section3" title="Members and Value Propositions">III &ndash; Members and Value Propositions</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section4" title="Income Projections and Budgets">IV &ndash; Income Projections and Budgets</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section5" title="Policies and Procedures">V &ndash; Policies and Procedures</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section6" title="Summary">VI &ndash; Summary</a></p>

				<p class="AllNavTitle" style="padding-top:10px">The Essential Guide to Standards:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part1" title="Participating In An SSO">Participating In An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part2" title="Forming And Managing An SSO">Forming And Managing An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part3" title="Law and Policy">Law and Policy</a></p>
			</div>
			<?php include '../includes/toolsets.php'; ?>
		</div>
		
		<!-- BODY CONTENT AREA -->
		<div class="GuideMain">
			<h1>The Essential Guide to Standards</h1>
			<p>The Essential Guide is a book-length handbook for anyone who wants to understand standards and standards development from a hands-on perspective. If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <script language="javascript" type="text/javascript">AuGesAdd();</script> if you have questions about this topic.</p>
			<div class="hr"></div><hr />
			<h2>Chapter 5: Forming A Successful Consortium<br />Part I &mdash; Business Considerations</h2>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<blockquote><em><strong>Summary:</strong> Most standard setting and standards-supporting consortia are formed by individuals with little or no prior experience in creating such entities. Their efforts can be informed by the example of existing organizations (which they often copy without understanding exactly why a particular aspect of a governance structure or a membership class has been set up as it has). One reason for this ad hoc practice is because there is no "how to" manual that sets forth the type of best practices in formation, structure and governance that are likely to enable a new organization to succeed. This Guide section reviews the key areas to be considered, and approaches to be taken, in forming a successful consortium to develop, promote and/or support standards. These areas and methods include defining the optimal scope for the new organization; determining the deliverables that it should create in order to achieve its mission; identifying and segmenting target membership groups whose participation will be needed to not only develop, but result in the adoption, of standards; creating attractive member value propositions for each of these target groups to ensure their participation; developing an adequate budget and determining appropriate dues structures to support that budge; designing a staffing model to serve the needs of the organization; and adopting key policies to support and add credibility to the organization's technical process. This article is part of the ConsortiumInfo.org <a href="/essentialguide/">Essential Guide to Standards</a>, which can be found at <a href="/essentialguide/">http://www.consortiuminfo.org/essentialguide/</a>. In particular, you may wish to read the second part of this article, titled <a href="forming2.php">Forming a Successful Consortium Part II: Legal Considerations</a></em></blockquote>
			<a name="section1"></a><h3>I &ndash; Introduction</h3>
			<p>More than two millennia ago, Archimedes contended that, given a place to stand and a lever long enough, he could move the world. While theoretically feasible, Archimedes' boast was impossible to achieve in real life. Had he used the word "standard," however, his contention would have had both practical as well as theoretical validity.</p>
			<p>For proof of that statement, one need look no farther than the World Wide Web and the many activities that can be accomplished through its use, all of which have been made possible by consortia such as the World Wide Web Consortium (W3C), the Internet Engineering Task Force (IETF) and the Organization for the Advancement of Structured Information Standards (OASIS). The total annual budgets of these organizations combined is less than the operating budget of a town of modest size, and yet their work is transforming the world.</p>
			<p>Given the enormous leverage that these inexpensive efforts have exerted, it is worth asking: <em>How did they do it?</em> And also this: To what extent did elements such as their structure, member composition, specific activities and policies make such successful results more likely?</p>
			<p>If we can answer these questions with precision, we can do a better job of forming the standard setting and standard-supporting organizations that we hope may achieve similarly important goals in the future. Avoiding the failure of a new consortium is also important, because there can be huge direct costs of failure: thousands of corporations commit hundreds of millions of dollars to supporting standards-related organizations, both in dues as well as in human-resource and travel costs, and make strategic bets based on anticipated standards-related outcomes that can run into the billions of dollars. And finally, the fortunes of nations in international trade are increasingly affected by the success or failure of the standard setting efforts launched or supported by domestic corporations. Taken all together, there is much to be gained by determining best practices in forming and operating both standard setting organizations, as well as the other non-profit promotional, certification, advocacy, and other entities that support standards (collectively, "consortia").</p>
			<p>Today there are many hundreds of accredited and unaccredited standard setting organizations (SSOs) and supporting consortia of other types serving the technology sector, and more of these organizations are being formed all the time.<sup><a href="#1">1</a></sup> Some flourish, while others enjoy only middling success, and some fail to gain traction at all. The reasons for success or failure can vary, but as with any other type of organization, there are practices that associate highly with success, and others that are frequently to be observed in connection with the opposite result. Surprisingly, in light of the importance and prevalence of such organizations, the literature on such practices is almost non-existent.</p>
			<p>Happily, there are so many SSOs in existence today that the technical process of standard setting is well understood by large numbers of participants. But while certainly the proper design and operation of a technical process is at the core of the success or failure of an SSO, that process must first be peopled with participants that are skilled and representative of the target marketplace for the standards to be developed. And if the standards, once drafted, are to become widely adopted, the membership should also include (at least) a critical mass of early adopters. And finally, the process must be sufficiently market-aware that the standards, once released, are sufficiently useful and timely that non-members will adopt them as well. To accomplish this result, the participation of end-users and others in the distribution chain besides vendors can be invaluable.</p>
			<p>Achieving this type of comprehensive membership is far from the automatic result of announcing the launch of a new standard setting effort. In fact, a wide variety of critical decisions must be made, and then implemented, in order to persuade target members that are already likely to be overburdened with participation in up to hundreds of existing SSOs that they should join yet another initiative. Once formed, a consortium must have the right business plan in order to succeed, lest it become the latest of the many SSOs that have had to confront the question, "What if you gave a standard and nobody came?"</p>
			<p>Curiously, most standard setting organizations created today are formed in a more or less ad hoc fashion by persons that have typically never been associated with such an endeavor in the past, although they may have been active participants in already established SSOs in a marketing or technical capacity. As a result, absent the advice of more experienced advisors, the founders of a new consortium frequently simply copy another organization with which they are familiar, rather than design an organization that is crafted to address the unique exigencies of the challenge at hand.</p>
			<p>Achieving the wide adoption of standards and accomplishing standards-related goals increasingly requires addressing additional collaborative activities beyond the process of creating the standards themselves. Some of these activities can be performed by the SSO, while others may at times be best performed by independent or affiliated organizations formed for the task. Such organizations may promote the standards set by either accredited standards development organizations (SDOs) or non-accredited consortia, or may create profiles of standards to meet "use cases" that are broader than the scope of any single SSO, or may engage in public advocacy in support of standards or standards-related business objectives.</p>
			<p>This <em>Guide</em> section will outline the key factors to be taken into account and the best practices to follow in designing a successful consortium to pursue any one (or more) of these objectives, based upon the author's anecdotal experience in helping create more than 50 consortia over the past 18 years, as well as his experience in advising many established SSOs in how to restructure themselves mid-career in order to address evolving market situations and member needs. A full list of these organizations can be found at this <a href="http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST">Web page</a>.<sup><a href="#2">2</a></sup></p>
			<p>Next month, I will describe in Part II of this article the legal, tax and more detailed structural issues that must be addressed in order to create the type of new consortium that is most likely to achieve the goals of its founders.</p>
			<a name="section2"></a><h3>II&ndash; Mission, Scope and Deliverables</h3>
			<p><strong>2.1 &mdash; Mission.</strong> The first question that anyone disposed to create a new SSO should ask is this: "Is this consortium really necessary?" After all, with so many existing consortia and SDOs available, it may be that an existing SSO might be both appropriate as well as willing to undertake the work to be accomplished. But despite this profusion of alternatives, it will often be necessary to create a new organization nevertheless.</p>
			<p>The most frequent reasons to launch a new SSO are the following, ranked , from best (e.g., all will benefit from the existence of a new organization) to worst (e.g., the motives for forming the new SSO are purely proprietary on the part of the founders):</p>
			<ul>
				<li><strong><em>New technology:</em></strong> The area needing standardization does not fall within the competency of any existing SSO.<br /><br /></li>
				<li><strong><em>Interest:</em></strong> SSOs have limited staff and budgets, and cannot commission an infinite number of new working groups. As a result, a nominally qualified SSO (or SSOs) may not be willing to commit the necessary resources to the project at hand.<br /><br /></li>
				<li><strong><em>Narrow focus:</em></strong> An otherwise logical SSO only addresses standard setting, and the commercial goals at hand require collaboration in other areas as well (e.g., promotion or certification and branding).<br /><br /></li>
				<li><strong><em>Poor reputation: </em></strong>An otherwise logical SSO to choose has a poorly run or slow technical process.<br /><br /></li>
				<li><strong><em>Blocking:</em></strong> Some SSOs are disproportionately controlled by groups of companies, or in a given case a subset of members may be able to block the formation of a new working group that could benefit their competitors, or which could erode their favorable market position through the introduction of a new standard.<br /><br /></li>
				<li><strong><em>Competition:</em></strong> Competing factions often found multiple SSOs to support opposing standards, each more or less targeted at the same commercial need. This typically occurs in an area of new technology, and can be productive as well as destructive, depending on the situation.<sup><a href="#3">3</a></sup><br /><br /></li>
				<li><strong><em>Challenge:</em></strong> SSOs are frequently formed to challenge an incumbent. When the incumbent is a perfectly useful, adopted standard, the challenge can be anticompetitive (as when a dominant industry player and its allies seek to gain disproportionate influence over the marketplace), or procompetitive, as when the reverse is the goal: to displace a dominant incumbent that is serving the marketplace poorly, either through stagnation in technology, high prices or overly restrictive or abusive licensing terms.</li>
			</ul>
			<p><strong>2.2 &mdash; Scope.</strong> Assuming that the need for a new organization is real, the next question is one of scope. SSOs can be short lived or long, and broadly chartered or narrowly focused. The following are typical, but not exclusive market situations and needs that a new consortium may be formed to address:</p>
			<p><strong>2.2.1 &mdash; Single standard situations.</strong> There is often a need for a single standard to enable a new market or address an isolated need. SSOs that overlap with existing SSOs are frequently formed for such a purpose, where a limited number of vendors perceives a need that is both discrete as well as urgent, and where they believe that a more successful result can be achieved more quickly through a tightly focused effort. If this is the only motivation, then the SSO will often dissolve at the end of the effort, if it is able to find a well-established SSO to take over the completed specification for long-term maintenance.</p>
			<p>Single standard SSOs typically remain in operation for longer periods of time when part of the original motivation is to limit participation to a small set of companies, rather than to create a legitimately open standard. At times, such an SSO will create additional specifications.</p>
			<p>Where the role of the SSO is to be transitory, a more lightweight organization and infrastructure is obviously preferable. Often most or all of the active, as well as the financial, support for such an organization will be provided by the members and/or contracted for from a third party service provider.</p>
			<p><strong>2.2.3 &mdash; Ecosystem SSOs.</strong> While some SSOs evolve from narrowly focused organizations to become much broader in focus,<sup><a href="#4">4</a></sup> others are formed to address much broader missions from the outset. Examples of such organizations include the <a href="http://www.omg.org/">Object Management Group</a> (OMG) and the <a href="http://www.ws-i.org/">Web Services Interoperability Organization</a> (WS-I), each of which was formed to pursue an ambitious goal requiring broad industry buy-in. In the case of OMG, it was to enable and promote a new type of "object oriented" programming that was intended to lower long-term costs of programming through the development and reuse of software "objects." In the case of WS-I, the goal was to enable and promote Web Services as a useful computing model. Accomplishing such ambitious goals in each case required the commitment by major market players and large operating budgets, in contrast to SSOs launched with more modest objectives.<sup><a href="#5">5</a></sup></p>
			<p><strong>2.3 &mdash; Deliverables.</strong> As noted, not all organizations that support standards actually create them. A better perspective to take when creating a new consortium is therefore not to focus on standards as such, but on the business objective that suggests the need for a standard. Sometimes simply creating a standard is sufficient, as when the perceived need for that standard is universal and the path to be taken is non-controversial. In such a case, the consortium formed need only address standard setting activities.</p>
			<p>At other times, however, the challenge of creating a standard is secondary to the difficulty of making it become widely adopted, and a consortium that was formed to set a standard and no more would be inadequate to the need. In this case, a high degree of marketing collaboration among members may be needed to condition the market, or to achieve confidence in the new standard.</p>
			<p>New SSOs will typically accomplish marketing objectives through the same entity that was formed to create standards. In other cases, however, a new organization may be needed to support adoption of a standard created by another organization (typically an SDO) that has no interest in organizing or supporting marketing activities.</p>
			<p>A third example of deliverables relates to branding, and comprises certification test suites, distinctive trademarks, and testing programs. Again, these requirements may be developed through the new organization, or, as with various wireless standards created and under development by the Institute of Electrical and Electronic Engineers (IEEE), through new consortia formed expressly for that task.<sup><a href="#6">6</a></sup></p>
			<p>In summary of this point, in order to launch a successful standards-based organization, a comprehensive effort should be made to identify all links in the chain of activities that will be needed to achieve the ultimate goal of broad adoption. A means of supplying each link must then bedevised, either through individual member efforts coordinated through the new consortium, or by funding and staffing the consortium to address that discrete need. Failing to identify and address any of these links may lead to the partial or complete failure of the standards-based effort.</p>
			<p>Looked at from another perspective, the total ultimate cost of a collaborative standards effort cannot be estimated until all needs are identified and budgeted. As a generality, it is easier to launch a new consortium with a full, convincing, well-documented business plan than to form one that is focused purely on standard setting, and then realize soon after that dues must be increased dramatically in order to achieve a successful result.</p>
			<a name="section3"></a><h3>III&ndash; Members and Value Propositions</h3>
			<p>Consortia are purposefully lightweight operations, with the very largest examples approximating the budget and staff of a modest business.<sup><a href="#7">7</a></sup> The great majority of consortia have annual budgets of less than $1,000,000, and only a few (if any) dedicated staff. In consequence, they are crucially dependent upon leveraging the efforts of their members, since no meaningful amount of direct marketing of their standards is feasible.</p>
			<p>While it would be misleading to state that a consortium that has attracted a membership comprising what an antitrust lawyer would call "market power" will automatically succeed, it's likelihood of success is certainly dramatically enhanced by virtue of attracting such a membership. In contrast, a consortium that fails to attract a significant proportion of the major vendors in its target area as actively participating members will have to try harder and execute more skillfully in order to achieve its objectives.</p>
			<p><strong>3.1 &mdash;  Determining target member types.</strong> Attracting the right types as well as adequate numbers of members is therefore a vital objective for any consortium, but identifying what the "right" overall membership may be in a given case must still be determined. Most succinctly, the "right membership" comprises a significant portion of <em>each class of stakeholder</em> whose active support is needed to achieve broad adoption. Identifying who these stakeholders may be is based upon understanding the sales cycle and sales-gating factors for a given standards-compliant product or service. If it is sold only in connection with other goods, will those goods need to be compliant as well? Will there be expensive switching costs for end-users associated with buying the standards-compliant products? If so, will analysts and integrators be urging end-users to incur these costs? Will active participation by end users themselves be needed in order to raise enthusiasm for such compliant products?</p>
			<p>Depending on the domain of standardization, the classes of core stakeholders may vary. They include the following, ranked in the order in which they are generally most important to an SSO:</p>
			<p><strong>3.1.1 &mdash; Vendors.</strong> Vendors occupy the top position, because they are the proximate consumers of standards (end-users being the ultimate consumers). To state the obvious, it is vendors that either do, or do not, decide to adopt a given standard, and therefore the food chain must begin here, or not at all. As importantly, a vendor that does not adopt a standard under development by one SSO may instead back the competing standard being developed by another. Hands down, the best way to get a vendor to adopt a standard is to secure its participation in developing that standard at the outset. And the best way to get more vendors to become members is to announce the names of those vendors that have already joined, as momentum in membership growth is the strongest indicator of ultimate adoption, creating a self-fulfilling prophecy. In particular, having a convincing number of vendors among the founding group can often make the difference between a new consortium being taken seriously or being ignored, and ultimately to its success or failure. Because of this reality, successful pre-public announcement recruiting is essential.</p>
			<p><strong>3.1.2 &mdash; Market partners.</strong> The success or failure of the standards-compliant products of some types of vendors ("primary adopters") is often dependent upon whether certain downstream, or related, vendors adopt the same standards ("secondary adopters"). Not uncommonly, the commercial motivations of the primary adopters may be significantly greater than those of secondary adopters, who may be indifferent, or even negatively disposed, to implement the same standards. This is particularly true where secondary adopters are best served by a single standard rather than by multiple standards, even if that single standard is a de facto standard (e.g., Windows) rather than an open standard (Linux), because it is cheaper to operate with one standard instead of two (e.g., if an independent software vendor (ISV) is forced to port new versions of its own software to multiple operating systems, and to port its software to each new release of the same operating systems, it will see its development costs multiply rapidly). Examples abound, adding costs to everything from cameras, to printers to audio and digital formats. Unfortunately, the support of secondary adopters is often crucial to the success of a standard, even where adoption is not attractive to such vendors (to continue the example, what good is an operating system without applications to run on it?) As a result, recruiting secondary adopters can be challenging as well as essential.</p>
			<p><strong>3.1.3 &mdash; Government.</strong> Governments (federal, state and local) are huge consumers of technology and other standardized products. Where government employees participate in the creation of a standard, they are more likely to specify the purchase of products that are compliant with that standard. Under the National Technology Transfer and Advancement Act of 1995,<sup><a href="#8">8</a></sup> the United States federal agencies are required not only to use public standards, rather than "government unique" standards, but to participate in their development as well. While budgetary constraints have limited such participation to a degree, it is nonetheless significant.<sup><a href="#9">9</a></sup></p>
			<p><strong>3.1.4 &mdash; End users.</strong> End users that participate in standards development, whether in a voting or non-voting capacity, are more likely to buy products that comply with the standards developed by the SSOs in which they participate. Attracting end users as members, while usually challenging, is often also rewarding.</p>
			<p><strong>3.1.5 &mdash; Universities.</strong> Academic members do not represent a very large market segment for most standardized products, but they do represent thought leadership in some cases, as well as skilled technical participants, and (at times) can provide government or grant funding for supporting activities.</p>
			<p><strong>3.1.6 &mdash; Integrators.</strong> Similarly, integrators are more likely to recommend and work with technology with which they are familiar.</p>
			<p><strong>3.2 &mdash; Value propositions.</strong> The single most important skill in designing a successful consortium is to create a value proposition that accomplishes two crucial objectives: attracting a critical mass of representatives from every important stakeholder class, and (stated baldly) extracting the maximum revenue from each individual member of each such class to the extent necessary to pay the bills of the new consortium. The first objective makes ultimate success more likely, while the second funds the operations needed to make such success possible.</p>
			<p>Achieving these dual objectives involves an analysis and application of the following criteria in light of the specific circumstances at hand:</p>
			<p><strong>3.2.1 &mdash; Value identification:</strong> Consortia can provide value of various types, not all of which are attractive, or attractive to the same degree, to each class of stakeholders. From a programmatic perspective, the following principal categories stand out:</p>
			<ul>
				<li><strong><em>The shape of standards:</em></strong> Why "the shape of standards" instead of simply "standards?" Because one of the principle benefits of being a participant is to have a say on which standards are developed, with which features, and in what order. Without this element (as well as related advantages, such as early access and familiarity with new standards), there is no reason to be a paying participant, as compared to a free-rider that simply accepts and uses the standards that are created by others.<br /><br /></li>
				<li><strong><em>Other Deliverables:</em></strong> Not only standards, but other deliverables may be important to specific types of members. Integrators and analysts as well as vendors may find white papers to be useful, and vendors will often find common marketing collateral to be useful. In some cases, public advocacy materials may be produced and shared, and in others consortium-staffed and organized trade show programming can provide important marketing visibility.<br /><br /></li>
				<li><strong><em>Certification and branding:</em></strong> Market awareness and confidence can be significantly augmented through coordinated certification and branding campaigns. While most of the expenses of such activities will be borne by individual members, it is the SSO that owns the test suite and the brands that members then utilize to identify and promote their products. Including such a program in the mission of a consortium can provide an essential service of high value to vendor members.<sup><a href="#10">10</a></sup><br /><br /></li>
				<li><strong><em>Activities:</em></strong> In addition to participation in standards creation, end users may value opportunities to train their employees. Individual representatives may look forward to networking opportunities at meetings, and augment resumes with chair positions. Public advocacy messaging can be harmonized, and expenses can be shared to promote matters of common concern.</li>
			</ul>
			<p>Since resources will be limited, the business plan for a new consortium should include a determination of which types of activities and deliverables will be most important to achieving success, as well as most appealing to potential members. Some activities, such as certification and branding, can be included in the plan for purposes of recruitment, but will obviously not need to be staffed or funded until the standards themselves have been developed.</p>
			<p>There are other types of value relating to governance and participation that should be noted, because they can be apportioned among different classes of members in order to provide the best match of value to cost (and, as a result, the highest yield in overall membership dues). The process of determining these points is not unlike any other exercise in "yield management," a concept that recognizes that the same product or service can have different values to different types of customers.</p>
			<p>Since consortia cannot usually go as far as airlines do with their yield management techniques (selling equivalent seats on the same flight at different prices to different classes of purchasers at different times), they must therefore "unbundle" the total number of rights and services that they may offer, and then "rebundle" subsets of those rights and privileges to match the objectives of different classes of potential members. The result of this exercise is to provide multiple value propositions (represented by these bundles of rights) at ascending prices, such that there is a bundle that is right for each class.<sup><a href="#11">11</a></sup></p>
			<p>The types of rights that bundle well can be identified and grouped into several categories:</p>
			<ul>
				<li><strong><em>Strategic direction:</em></strong> Rights under this category include determining the scope of operations and which standards or other efforts are to be launched, and granting final approval to the standards developed.<br /><br /></li>
				<li><strong><em>Operational control:</em></strong> This includes hiring and firing management, setting dues, approving liaison relationships, and supervising programming.<br /><br /></li>
				<li><strong><em>Technical influence:</em></strong> Once the overall strategic direction has been determined, there are still many rights that remain to be apportioned that provide a measure of influence over the outcome of consortium projects, including the right to propose new working groups, to offer technology for adoption in working groups, the right to provide a chair for a working group or committee, and the right to vote on adoption of standards and other deliverables.<br /><br /></li>
				<li><strong><em>Technical experience:</em></strong> Many consortium members do not have a stake in specific outcomes, but do have a need to become experienced in utilizing the standards or other deliverables that a consortium may develop. In this case, early access and training provide significant value, and merely being able to participate in technical and marketing processes in a non-voting capacity provides an adequate incentive to participate.<br /><br /></li>
				<li><strong><em>Information:</em></strong> At the bottom of the value stack is simple information, which may include early access to that information.</li>
			</ul>
			<p>Aggregating all of this data, it is possible to create a matrix of member classes and member rights that are likely to appeal to the largest number of potential members. Such a matrix should be unique to the needs of each new organization, but frequently looks something like the matrix set forth below (excluding minor rights in order to more clearly demonstrate significant value points). Prices noted would be typical for an information technology consortium whose mission is deemed to be important to the industry.<sup><a href="#12">12</a></sup></p>
			<ul>
				<li><strong><u>Strategic Member</u>:</strong> Guaranteed board seat, or reasonable likelihood of eventually gaining one, and all privileges of lower categories of membership (other than the right to vote for additional directors); can nominate officers and committee chairs<br /><strong>Appeals to:</strong> Companies (usually vendors) that wish to set the strategic objectives of the consortium<br /><strong>Cost</strong>: $25,000 - $50,000, depending on revenues of member<br /><br /></li>
				<li><strong><u>Technical Committee Member</u>:</strong> &nbsp;Full, voting participation in all technical and marketing processes; as a class, can elect a limited number of board representatives (perhaps with the types of member specified, to ensure diversity of representation); may be invited to provide a committee chair; all privileges of lower categories of membership<br /><strong>Appeals to:</strong> Companies, universities, colleges, and government agencies wishing to influence the standards that are developed<br /><strong>Cost</strong>: $15,000 - $25,000, depending on revenues of member; less for non-commercial members<br /><br /></li>
				<li><strong><u>Advisory Member</u>:</strong> May send one non-voting member to all technical and marketing processes; all privileges of lower categories of membership<br /><strong>Appeals to:</strong> All types of members that wish to participate in, but do not need to influence the design of the standards that are developed, and that wish to have the most timely information regarding technical direction and results<br /><strong>Cost</strong>: $10,000 (regardless of revenues); less for non-commercial members<br /><br /></li>
				<li><strong><u>Informational Member</u>:</strong> Receives periodic information regarding technical and other programs, as well as standards as they are made public<br /><strong>Appeals to:</strong> Academics, consultants, analysts, individuals<br /><strong>Cost</strong>: $250 (regardless of revenues)</li>
			</ul>
			<a name="section4"></a><h3>IV&ndash; Income Projections and Budgets</h3>
			<p>Setting a budget and projecting income present something of a chicken and egg dilemma for new consortia: what will it cost to provide the programs, services and deliverables needed to attract the members that are willing to pay enough to fund those same line items?</p>
			<p><strong>4.1 &mdash; Income projections.</strong> Assuming that the mission for a new organization is sound, projecting its potential income requires estimating three principal variables: the size of the potential target population of members by class (on which more later); the percentage of representatives of each class that is likely to join over the first several years; and the appropriate and feasible price point for each membership class. Each is worth examining in some detail.</p>
			<p><strong>4.1.1 &mdash; Target population.</strong> Not surprisingly, different consortia will have target markets of potential members that will vary in size. For example, the number of operating system vendors is far smaller than the number of business software developers. Consortia that can appeal to multiple types of potential members (e.g., vendors, integrators, end users, government and so on) are also more likely to be able to attract sufficient active and economic participation to achieve their goals.</p>
			<p><strong>4.1.2 &mdash; Percentage participation.</strong> Different domains have different levels of typical participation. It is easy to review the Websites of other organizations that are active in the same domain to determine what level of participation to expect from those that are doing business or are otherwise active in the sector(s) in question.</p>
			<p><strong>4.1.3 &mdash; Price points.</strong> From a dues point of view, the census of potential members will also vary.Some domains will include many large vendors that are used to paying significant amounts for high level memberships, while others will be populated only by small vendors that would not be willing to pay more than a few thousand dollars each, even to gain a board seat in the new organization. Different classes of members also have different dues expectations. For example, government and academic members are typically willing (and able) to pay far less to participate in an SSO than commercial members. Finally, different missions have different levels of strategic importance to potential members, with the result that some large vendors would be wiling to pay as much as a $1million a year to achieve objectives that are vital to their own strategic plans.</p>
			<p>Some of these variations are commonly addressed by charging different amounts for the same rights, much as the airline does with the price of an otherwise fungible airline seat. Most typically, this is addressed by charging less by class of member, and also by charging less within a single class of member, based upon revenues. The reason why such practices are deemed to be acceptable by those that pay more is because it is recognized that broad participation by certain types of members that cannot afford expensive memberships or that may not be highly motivated to participate may be instrumental to success. As a result, the larger commercial entities (who often also have the greatest stake in a favorable outcome) often subsidize the participation of these other types of members.</p>
			<p>The following are examples of such differential pricing:</p>
			<ul>
				<li><strong><em><u>Revenue based differentiation</u>:</em></strong> Where large vendors need the participation of small vendors, dues may be apportioned by ability to pay, with the exact price breaks depending on the target census of the industry in question. The following differentiation nwould be typical for the top level of participation of a consortium (Strategic membership, in the matrix used above) that wishes to attract the smallest to the largest companies in a market sector with target companies of all sizes:</li>
			</ul>
			<table class="EssGuideT1">
				<tr>
					<td valign="top"><p><strong>Revenues</strong></p></td>
					<td valign="top"><p><strong>Dues</strong></p></td>
				</tr>
				<tr>
					<td valign="top"><p>Over $1 billion</p></td>
					<td valign="top"><p>$50,000</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Over $500 MM/under $1 B</p></td>
					<td valign="top"><p>40,000</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Over $100 MM/under $500 MM</p></td>
					<td valign="top"><p>30,000</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Under $100 MM</p></td>
					<td valign="top"><p>25,000</p></td>
				</tr>
			</table>
			<p>Using the above concepts (as well as the dues and membership pages of multiple other consortia), it is possible in any given situation to estimate amounts that would be appropriate to charge to participate in each class of a new consortium.</p>
			<ul>
				<li><strong><em>Class based differentiation</em></strong>: For the same consortium, second level participation (Technical membership, in the above example) might be priced as follows:</li>
			</ul>
			<table class="EssGuideT1">
				<tr>
					<td valign="top"><p><strong>Class</strong></p></td>
					<td valign="top"><p><strong>Dues</strong></p></td>
				</tr>
				<tr>
					<td valign="top"><p>Commercial</p></td>
					<td valign="top"><p>$10,000 - $25,000,depending on revenues</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Government</p></td>
					<td valign="top"><p>3,000</p></td>
				</tr>
				<tr>
					<td valign="top"><p>University</p></td>
					<td valign="top"><p>2,000</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Other non-profit</p></td>
					<td valign="top"><p>1,000</p></td>
				</tr>
			</table>
			<p>Since new consortia are rarely announced unless and until a credible group of founding members has been assembled on a confidential basis, all of the assumptions made in the course of framing out a membership structure can be tested during the initial recruitment process. Usually the decisions made at this stage , if carefully considered, prove to be durable in practice.</p>
			<p><strong>4.2 &mdash; Budgets.</strong> A surprising number of consortia operate on very small budgets, with the majority operating on income of less than $500,000 a year, and the great majority on less than $1,000,000. In fact, the process of standard setting is not expensive, and has become less so since conference calls and Web based platforms have become available. Principal costs include the following:</p>
			<p><strong>4.2.1 &mdash; Staff.</strong> There are four principal models for staffing a consortium, in increasing order of cost:</p>
			<ul>
				<li><strong><em>All volunteer:</em></strong> In this model, virtually all required services are provided by members on a volunteer basis, with some members providing administrative services, others hosting meetings, and one member or another taking terms hosting conference calls and the like. Only limited services are purchased in the market place, such as accounting, design and printing of marketing collateral, and legal services. For consortia that set or maintain only one standard that is not in competition with another standard or with a dominant de facto standard, this model can be quite adequate, and there are many such organizations with total annual budgets in the $25,000 to $50,000 range. Where the program is more ambitious or urgent, however, this model usually falls short.<br /><br /></li>
				<li><strong><em>Secretariat:</em></strong> A few consortia have adopted a model borrowed from the world of accredited standard setting. In this model, one member (as compared to one national standard setting organization, in the accredited model) volunteers to function as the "Secretariat," providing most or all administrative and other services, either without charge, or for payments derived from the fees of other members. In some organizations, the Secretariat role rotates among members. Dues costs of organizations operating under this model can be relatively low, if the Secretariat is not reimbursed.<br /><br /></li>
				<li><strong><em>Outsourced:</em></strong> Many consortia outsource all of their needs to a management company. Depending on the service provider, nearly all services are provided by a single vendor, including marketing, administration, bookkeeping, call and meeting hosting and much more. Such full service providers frequently provide a mix of full-time, dedicated staff to serve large individual clients, supplemented by the shared services of other employees where full-time services are not required.<!--<sup><a href="#13">13</a></sup>--> Other management companies provide only core services, and then sub-contract for those services that they do not provide themselves. The range of costs for this model can range from very low (e.g., $25,000 a year) to very large, since virtually all costs may flow through the management company.<br /><br /></li>
				<li><strong><em>Dedicated:</em></strong> The largest consortia often choose to lease their own offices (sometimes on multiple continents) and hire their own dedicated staff, purchasing only the same types of services externally (e.g., legal and audit) that any other staffed business of comparable size would normally purchasein the market. Except where dedicated staff are seconded by a member (often in lieu of dues), the base line budget for a consortium with dedicated staff is likely to begin at $250,000, since it is unlikely that a full-time staff person would be hired unless significant additional costs would be incurred as well, and the first hire is usually an Executive Director rather than a low level administrative person. Organizations with multiple, full time employees typically have budgets that range from $500,000 on up.</li>
			</ul>
			<p>In fact, most consortia incorporate two or more of these approaches. As with other businesses, fully burdened staff costs for non-volunteer or seconded staff include taxes and benefits.</p>
			<p><strong>4.2.2 &mdash; Communications.</strong> Communications include a variety of expenses, some or all of which can be provided by members or by others for a fee:</p>
			<ul>
				<li><strong><em>Website development and hosting:</em></strong> The core platform for most technology consortia today is the organization's Website, and accordingly the proper design, hosting and maintenance of that resource should be a priority. For a small consortium maintaining a single standard, the site can be modest, but for an active consortium with multiple activities that wishes to have an archive, on line voting, multiple simultaneous password protected sections, and more, the complexity and cost of the Website can become a significant expense.<sup><a href="#14">14</a></sup><br /><br /></li>
				<li><strong><em>Conference call and Webex hosting:</em></strong> Some consortia have many working group calls per week. If not hosted by members, this can become a significant expense.<br /><br /></li>
				<li><strong><em>Member communications:</em></strong> Most active consortia have electronic newsletters and other ways to maintain touch with their members.<br /><br /></li>
				<li><strong><em>Tradeshows:</em></strong> Larger consortia sometimes have their own tradeshow booths, with all of the resulting design, shipping and storage costs. Others will simply encourage their members to display a consortium logo in their own booths, and keep a stack of consortium marketing collateral on their countertops.</li>
			</ul>
			<p><strong>4.2.3 &mdash; Marketing and Public relations.</strong> While consortia do not have the budgets to do significant marketing, they do typically undertake at least the following activities:</p>
			<ul>
				<li><strong><em>Press releases:</em></strong> A typical consortium will issue from a few to dozens of press releases a year. Consortia often also post member news relating to their standards compliant products and services at the consortium site as well.<br /><br /></li>
				<li><strong><em>Marketing collateral:</em></strong> For use by members and the consortium at trade shows and in other situations.<br /><br /></li>
				<li><strong><em>White papers:</em></strong> Sometimes issued in connection with trade shows or special issues of trade journals.<br /><br /></li>
				<li><strong><em>Marketing studies:</em></strong> These are more cheaply purchased jointly than individually, although it is not always easy to negotiate shared use with the research firm.<br /><br /></li>
				<li><strong><em>Speaking engagements:</em></strong> One role of dedicated staff is to speak regularly at trade shows. Consortia also often volunteer to propose topics and put together panels at trade shows in order to highlight their areas of activity.<br /><br /></li>
				<li><strong><em>Article placements and interviews:</em></strong> For all the usual reasons.</li>
			</ul>
			<p>A good management company will often provide or contract out for many of these services, often at a lower cost than a PR firm would charge.</p>
			<p><strong>4.2.4 &mdash; Other.</strong> Other principal line items include the following:</p>
			<ul>
				<li><strong><em>Hardware, software and Internet access:</em></strong> IT costs in equipment and maintenance obviously scale with staff.<br /><br /></li>
				<li><strong><em>Accounting and legal:</em></strong> Most consortia of a certain size will commission an annual audit (and if they are registered with the IRS as a public charity rather than a trade association, will be required to do so). Legal services can range from modest to significant, depending on such factors as antitrust risk, number of staff, frequency of entering into significant contracts, need to create and revise intellectual property rights policies, and other activities of legal sensitivity.<br /><br /></li>
				<li><strong><em>Insurance:</em></strong> Most consortia should plan on obtaining Directors and Officers insurance, as it is quite inexpensive for non-profits (e.g., $3,000 - $5,000 for $1 to $2 million in coverage), but the policy needs to be reviewed and negotiated carefully so that the risks of greatest concern are not excluded by the insurer. Consortia with staff should also plan on obtaining normal business coverages as well.<br /><br /></li>
				<li><strong><em>Travel:</em></strong> Member travel is invariably at the cost of the member, but staff travel can become a significant budget item. Staff travel principally relates to speaking, support at in-person member meetings, and member recruitment and retention.</li>
			</ul>
			<p>Despite this lengthy series of line items, most consortia are able to accomplish their missions within the resources available. That being said, those that can afford dedicated staff (whether direct hired, or retained through a management company) are more likely to achieve their missions in competitive, fast moving settings.</p>
			<a name="section5"></a><h3>V &ndash; Policies and Procedures</h3>
			<p>SSOs succeed or fail with the credibility of their standards. As a result, the policies that an SSO adopts can have a major influence on whether its standards are adopted readily or not at all.</p>
			<p><strong>5.1 &mdash; Openness.</strong> Except in the case where the founding members of a new SSO control the majority of the marketplace, making adoption by all others a given, an SSO can do itself irreparable harm by being insufficiently open in its policies. Absent such a policy, non-members may be loath to adopt what they perceive to be standards over which they have no control, and which may be manipulated to their disadvantage. For current purposes, "openness" is the product of the following policies:<sup><a href="#15">15</a></sup></p>
			<ul>
				<li><strong><em>Membership criteria:</em></strong> Membership criteria should be no more restrictive than necessary to ensure an efficient process.<br /><br /></li>
				<li><strong><em>Costs of participation:</em></strong> To the extent possible while still spreading costs fairly and accomplishing objectives, dues required to participate in all meaningful activities should be made acceptable to all classes of stakeholders.<br /><br /></li>
				<li><strong><em>Member acceptance:</em></strong> All applicants that meet the established criteria should be automatically admitted in any category to which they choose to apply.<br /><br /></li>
				<li><strong><em>Governance:</em></strong> The Board or other governing body should not be controlled in the long term by the founders, although founding members will typically hold the initial seats. The board should also represent all classes of stakeholders, regardless of whether each class can afford a top-level membership.<br /><br /></li>
				<li><strong><em>Technical Participation:</em></strong> All members of eligible classes should be entitled to participate equally in technical and other activities.<br /><br /></li>
				<li><strong><em>Transparency:</em></strong> At minimum, all standards should be posted for public comment prior to adoption. Some consortia make all of the minutes and other proceedings of their working groups public from the beginning of a technical process.<br /><br /></li>
				<li><strong><em>Adoption:</em></strong> All standards should be available for implementation by non-members as well as members on a non-discriminatory basis.</li>
			</ul>
			<p><strong>5.2 &mdash; Intellectual property rights.</strong> Technology standards increasingly exist under a cloud of contention involving patent claims, usually referred to under the generic phrase "intellectual property rights", or simply "IPR." Members have two competing concerns when they join an SSO: that they will accidentally become bound to license a patent through failure to disclose it in timely fashion, and that some other member will deliberately cause a standard to infringe upon their undisclosed patent. The result is that members (especially those with very large patent portfolios) on the one hand want to make an IPR policy lax enough to permit them to avoid accidental commitments, while tough enough to prevent others from embedding IPR in a standard, only to assert their "submarine patent" against adopters at a later date and demand extortionate licensing fees. The unhappy result is that IPR policies today are not as tough as they could be, although the trend is to make them more demanding.<sup><a href="#16">16</a></sup></p>
			<p>Regardless of the lack of perfection of current IPR policies, it is a fact today that most large vendors will not join a new consortium until an IPR policy has been negotiated and adapted to that they find to be acceptable. This truism applies even to a new SSO's founders, providing the major impediment to speedily forming a new consortium. Given that different companies have strongly held opinions on even minor language variations in IPR policies, the rather perverse mark of a successful effort to draft an IPR policy for a new SSO today is whether everyone is equally unhappy with the final result.<sup><a href="#17">17</a></sup></p>
			<p><strong>5.3 &mdash; Technical process.</strong> As the technical process is at the core of an SSO, the proper design of the supporting structure for standard setting in a new consortium is crucial. There are, of course, countless examples to choose from, and they are not all the same. Some processes, as can be expected, have proven to be more effective and efficient than others, and some will prove to be better suited to certain types of standards or situations than others. Accordingly, designing and documenting the process for a new SSO should not be a haphazard matter of cloning the documentation and rules of another randomly selected organization, regardless of whether some of the founders are familiar with that process.<sup><a href="#18">18</a></sup></p>
			<p>The staffing of a technical process is equally important, as good results are crucially dependent upon the neutral, effective leadership of the chairs of each committee and working group.</p>
			<a name="section6"></a><h3>VI &ndash; Summary</h3>
			<p>Consortia have now enjoyed a successful existence in significant numbers of nearly twenty years. With approximately 500 in operation in the information and communications technology industry at any point in time, there is therefore a wide range of examples and experience upon which to draw in forming a new organization. Examining the collective successes and failures of these organizations can provide clear guidance on how to structure a consortium that is biased towards achieving its objectives.</p>
			<p>The information in this article has rarely, if ever, been collected in one convenient place, but is still summary in nature. As a result, those charged with creating a new organization would be well advised to seek the guidance of those that have created successful organizations in the past, and to review the Websites of those successful consortia that already exist in their targeted domain space. If these tools are used, there is every reason to assume that a new standards-related organization that is otherwise based upon a sound business case can be designed to be well-poised to meet its objectives.</p>
			<p class="note"><strong>NOTE:</strong> If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a> if you have questions about this topic.</p>
			<p class="center">Copyright 2007 Andrew Updegrove</p>
			<p><strong>End Notes</strong></p>
			<p><a name="1"></a><sup>1</sup> For a list of almost 500 accredited and non-accredited standard setting organizations addressing the information and communications technology and related industry niches, see the <a href="/links/">Standard Setting Organization and Standards List</a> at this site, at &lt;http://www.consortiuminfo.org/links/&gt;. All Websites sited in this article were accessed November 26 &ndash; 29, 2006.</p>
			<p><a name="2"></a><sup>2</sup> <a href="http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST">http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST</a></p>
			<p><a name="3"></a><sup>3</sup> An example of productive competition can be found in the emergence and competition of multiple standards and SSOs in the wireless networking space. The most successful competitors proved to be Bluetooth and WiFi, each of which found significant commercial followings for the uses to which each was best suited, although both standards (and at least one other that was supported by its own SSO, called HomeRF) initially competed head to head for use in the same applications. For more on this and other standards wars, both good and bad, <em>see</em> Updegrove, Andrew, <em>Standards Wars: Situations, Strategies and Outcomes</em>. ConsortiumInfo.org, Consortium Standards Bulletin, Vol. V, No. 3 (March 2006), at &lt;http://www.consortiuminfo.org/bulletins/mar06.php#feature&gt;.</p>
			<p><a name="4"></a><sup>4</sup> Two examples represented by the author are <a href="http://www.opengeospatial.org/">Open Geospatial Consortium</a> (OGC) and the <a href="http://www.oasis-open.org/home/index.php">Organization for the Advancement of Structured Information Standards</a> (OASIS), each of which is now more than a decade old and has a large number of active working groups addressing many technical challenges. Each organization originally had a more narrowly defined set of objectives.</p>
			<p><a name="5"></a><sup>5</sup> Each organization adopted a novel approach as well. In contrast to most SSOs, OMG does not so much develop standards as extract them from already-available products, in order to ensure that its standards can have immediate market impact. For its part, WS-I does not create standards at all, but instead creates profiles of standards (developed by other SSOs) to address "use cases" in order to speed adoption and add credibility to the Web Services computing model.</p>
			<p><a name="6"></a><sup>6</sup> These organizations include the WiFi Alliance (supporting the 802.11 "WiFi" standard), the WiMedia Alliance (supporting ultra-wideband, or UWB, standards), and the WiMax forum (supporting the 802.16 standard).</p>
			<p><a name="7"></a><sup>7</sup> There have been rare examples of consortia with over 100 employees, such as the Open Software Foundation in the 1990s, but OSF developed code as well as standards. At most times, the largest consortia have a paid staff of around 25 (and consortia with this many employess are few in number), with rare outliers (such as the W3C today) having significantly more.</p>
			<p><a name="8"></a><sup>8</sup> National Technology Transfer and Advancement Act of 1995, 15 U.S.C. &sect; 3701 (1995).</p>
			<p><a name="9"></a><sup>9</sup> For a detailed review of the involvement of the U.S. government in standard setting, <em>see</em> Updegrove, Andrew, <em>A Work in Progress: Government Support for Standard Setting in the United States: 1984 &ndash; 2004</em>, ConsortiumInfo.org, Consortium Standards Bulletin, Vol. IV, No. 1 (January 2005), at &lt;<a href="/bulletins/jan05.php#feature">http://www.consortiuminfo.org/bulletins/jan05.php#feature</a>&gt;, and sources cited therein.</p>
			<p><a name="10"></a><sup>10</sup> For a detailed treatment of the broad range of SSO certification and branding activities employed in the information and communications technology industry, see Updegrove, Andrew, <em><a href="/bulletins/july06.php#feature">Standards Compliance Certification and Branding in the Information and Communications Technology Sector</a></em>, ConsortiumInfo.org, Consortium Standards Bulletin, Vol. V, No. 7 (July 2006), at &lt;http://www.consortiuminfo.org/bulletins/july06.php#feature&gt;</p>
			<p><a name="11"></a><sup>11</sup> The exercise is not dissimilar to the traditional strategy of an automotive manufacturer that strives to offer different models, at different price points, and with different capabilities, in order to have one or more sales offerings that are "right" for every possible car or truck buyer.</p>
			<p><a name="12"></a><sup>12</sup> Attentive regular readers will recognize that this is the same matrix I used as an example in the <a href="/bulletins/oct06.php#feature">feature article</a> of the October 2006 issue of the Consortium Standards Bulletin, <em>at</em> &lt; http://www.consortiuminfo.org/bulletins/oct06.php#feature&gt;</p>
			<!--<p><a name="13"></a><sup>13</sup> One such full-service management provider is Wakefield, Massachusetts based <a href="http://www.virtualmgmt.com/">Virtual, Inc.</a>, whose range of services can be found <a href="http://www.virtualmgmt.com/services/index.asp">here</a>: &lt;http://www.virtualmgmt.com/services/index.asp&gt;&nbsp; For many years, a large number of my consortium clients have retained Virtual to provide some or all of their management services.</p>-->
			<p><a name="14"></a><sup>14</sup> The most sophisticated and ubiquitous SSO Websites today are provided by Portland Oregon based <a href="http://www.kavi.com/home">Kavi, Inc.</a>, which provides Websites exclusively for association use. Recently, Kavi added features custom designed for use by accredited SSOs, to facilitate the periodic audits by ANSI that are required to maintain their accreditation. The current Kavi client list can be found <a href="http://www.kavi.com/clients/">here</a>: &lt;http://www.kavi.com/clients/&gt;</p>
			<p><a name="15"></a><sup>15</sup> "Openness," of course, is not only in the eye of the beholder, but hostage to the writer of the definition &ndash; and there are many. For a fuller discussion of the many definitions of "openness," see the <a href="/bulletins/mar05.php">March 2005 issue</a> of the Consortium Standards Bulletin (Vol. IV, No. 3), at &lt; Vol. III, No. 11), at &lt;<a href="/bulletins/nov04.php">http://www.consortiuminfo.org/bulletins/nov04.php</a>&gt;, and in particular in the feature article, <a href="/bulletins/mar05.php#feature">The Many Faces of "Open"</a> at &lt;http://www.consortiuminfo.org/bulletins/mar05.php#feature&gt;.</p>
			<p><a name="16"></a><sup>16</sup> For more on the current trend to make IPR disclosures more effective, see the June 2006 issue of the Consortium Standards Bulletin (Vol. 5, No. 6), which focuses on <a href="/bulletins/jun06.php">The Great Ex Ante Debate</a>, at &lt;http://www.consortiuminfo.org/bulletins/jun06.php&gt;.</p>
			<p><a name="17"></a><sup>17</sup> For a detailed description of the terms of, as well as the compromises demanded by, IPR policies, see the <a href="/ipr/">Intellectual Property Rights</a> section of the ConsortiumInfo.org <a href="/essentialguide/">Essential Guide to Standard Setting Organizations and Standards</a>, <em>at</em> <a href="/ipr/">http://www.consortiuminfo.org/ipr/</a>.</p>
			<p><a name="18"></a><sup>18</sup> Detailing the design of a successful technical process would exceed the scope of this article, but is addressed in detail in the November 2004 issue of the <a href="/bulletins/nov04.php">Consortium Standards Bulletin</a> (Vol. III, No. 11), at &lt;http://www.consortiuminfo.org/bulletins/nov04.php&gt;, and in particular in the feature article, <a href="/bulletins/nov04.php#feature">Creating an SSO Technical Process (a Practical Primer)</a> at &lt;http://www.consortiuminfo.org/bulletins/nov04.php#feature&gt;, and in an interview with the CTOs of three prominent SSOs, <a href="/bulletins/nov04.php#trends">Making the Technical Process Work (an Insiders' View)</a>, at &lt;http://www.consortiuminfo.org/bulletins/nov04.php#trends&gt;.</p>
			<table class="GuideHelp">
				<tr>
					<td style="padding:12px;" valign="top"><a href="http://www.gesmer.com/attorneys/updegrove.php"><img src="images/guide_updegrove.jpg" width="69" height="106" border="0" alt="" /></a></td>
					<td valign="top">
						<p class="GuideHelpHead">Can We Help You?</p>
						<p class="GuideHelpBody1"><a href="http://www.gesmer.com/">Gesmer Updegrove LLP</a> is, quite simply, the most experienced law firm in the United States when it comes to representing and creating standards development organizations &mdash; <a href="http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST">more than 100</a> &mdash; to date.  If you need advice about participating in the standards development process, representation in standards-related litigation, intellectual property advice, or help creating a brand new SSO or open source foundation, we'd be pleased to help. Contact:</p>
						<p class="GuideHelpBody2">Email: <script language="javascript" type="text/javascript">AuGesAdd();</script><br />Tel: 617-350-6800</p>
					</td>
				</tr>
			</table>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
		</div>
	</div>
<div class="clear"><br /></div>
<!-- *********** -->
<!--   FOOTER    -->
<!-- *********** -->
<?php include '../includes/footer.php'; ?>
</form>
</body>
</html>