<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>The Essential Guide to Consortia and Standards</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta name="description" content="While standard setting has been an important aspect of industrial society for over a hundred years, the formation of unofficial, fast-acting standard setting and promotional consortia is a more recent phenomenon which is only now beginning to be seriously studied" />
<meta name="keywords" content="standard setting, promotional consortia, structuring of consortia, standardize, intellectual property policies, procedures, founding company, model, best practices, promoter/adopter structurer, joint venture, IPR, " />
<meta name="author" content="Andrew Updegrove" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/screen.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/guide.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/toolsets.css" />
<!-- ALTERNATE -->
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/default.css" title="default" />
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/large.css" title="large" />
<!-- ********* -->
<link rel="home" title="home" href="http://www.consortiuminfo.org" />
<script type="text/javascript">AC_FL_RunContent = 0;</script>
<script type="text/javascript" src="/scripts/AC_RunActiveContent.js"></script>
<script type="text/javascript" src="/scripts/styleswitcher.js"></script>
<script type="text/javascript" src="/scripts/obfuscate.js"></script>
</head>

<body id="bulletin">
	<!-- ****************** -->
	<!--   ACCESSIBILITY    -->
	<!-- ****************** -->
	<?php include '../includes/accessibility.php'; ?>
	
	<!--   SEARCH FORM   -->
	<form class="search" name="form1" method="get" action="http://search.Blossom.com/query/320">
	
	<!-- ************* -->
	<!--   MASTHEAD    -->
	<!-- ************* -->
	<?php include '../includes/masthead_subs.php'; ?>
	
	<!-- *********** -->
	<!--   BANNER    -->
	<!-- *********** -->
	<div id="banner">
		<div class="left">
			<p><a href="/">Home</a> &gt; <a href="/essentialguide/">Guide</a> &gt; Intellectual Property Rights And Standard Setting</p>
		</div>
		<div class="right">
			<p><input type="text" name="key" /><input type="submit" name="Submit" value="Search" /> <a href="/search/">Advanced</a></p>
		</div>
		<div class="clear"></div>
	</div>
						
	<!-- ************** -->
	<!--   MAIN BODY    -->
	<!-- ************** -->
	<div class="GuideContent">
	<!-- SKIP/START CONTENT LINK -->
	<a name="startcontent" id="startcontent"></a>
		
		<!-- SIDEBAR CONTENT AREA -->
		<div class="AllSidebar">
			<div>
				<?php include '../includes/clients.php'; ?>			
			</div>
			<div class="AllNav">
				<p class="AllNavTitle">Chapter 4:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section1" title="Introduction">I &ndash; Introduction</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section2" title="The Placid Past">II &ndash; The Placid Past</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section3" title="The Turbulent Present">III &ndash; The Turbulent Present</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section4" title="IPR Policy Coverage and Implementation">IV &ndash; IPR Policy Coverage and Implementation</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section5" title="Patent Issues">V &ndash; Patent Issues</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section6" title="Current Issues and Trends">VI &ndash; Current Issues and Trends</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section7" title="Summary">VII &ndash; Summary</a></p>
				<p class="AllNavTitle" style="padding-top:10px">The Essential Guide to Standards:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part1" title="Participating In An SSO">Participating In An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part2" title="Forming And Managing An SSO">Forming And Managing An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part3" title="Law and Policy">Law and Policy</a></p>
			</div>
			<?php include '../includes/toolsets.php'; ?>
		</div>
		
		<!-- BODY CONTENT AREA -->
		<div class="GuideMain">
			<h1>The Essential Guide to Standards</h1>
			<p>The Essential Guide is a book-length handbook for anyone who wants to understand standards and standards development from a hands-on perspective. If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <script language="javascript" type="text/javascript">AuGesAdd();</script> if you have questions about this topic.</p>
			<div class="hr"></div><hr />
			<h2>Chapter 4: Intellectual Property Rights And Standard Setting</h2>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<blockquote><em><strong>Summary:</strong> Intellectual property rights (IPR), and particularly patent claims, provide special challenges to standards developers.  Following adoption of standard, members may be unwilling to share implementation rights on licensing terms that are conducive to wide adoption of the standard (or at all).  Or, during the development phase, they may secretly seek to ensure that a standard will infringe their undisclosed patent claims, in order to reap a harvest of royalties when those rights are revealed after the marketplace has already been locked in.  Externally, there will often be patent claims that are essential to the implementation of a standards, but whose owners have little or no incentive to make their valuable IPR available on acceptable terms (or at all).  As a result, standard setting organizations must have IPR policies that are designed to minimize - although they cannot totally eliminate - such problems.  In this article, I briefly review: the history of IPR issues; the changes in the standard setting landscape that are accentuating IPR concerns today; the ways in which IPR (and particularly patent claims) give rise to concerns for standards developers and implementers; the documents that comprise an appropriate IPR management regime; and finally those areas in which IPR policies are most significantly being challenged and reworked today. This article is part of the ConsortiumInfo.org <a href="/essentialguide/">Essential Guide to Standards</a>, which can be found at <a href="/essentialguide/">http://www.consortiuminfo.org/essentialguide/</a>.</em></blockquote>
			<a name="section1"></a><h3>I &ndash; Introduction</h3>
			<p>The need to deal with intellectual property rights &mdash; principally copyrights and patents &mdash; lie at the core of standard setting.  At the most basic level, the standards, reference software, compliance test suites, white papers, and other common deliverables that standard setting organizations (SSOs) create are themselves copyrightable works, and can be sold by SSOs, if desired, in order to defray some or all of the costs of their production.  At the level of implementation, standards that dictate technical design features (as compared to performance standards that only specify output parameters, or physical interoperability standards, which deal with otherwise arbitrary characteristics such as physical dimensions) have the potential to require the infringement of patents owned by members and non-members.  Patent infringement has more significant economic implications, since the owner of a patent can require the payment of a per-product fee to implement a standard, or can withhold permission to implement the standard at all.</p>
			<p>Every SSO therefore needs a set of rules that addresses IPR in order to ensure that the SSO owns its work product upon completion, and to decrease the risk that its completed standards will encounter IPR-based impediments to broad implementation.  Those rules typically address questions such as whether and when patent claims must be disclosed, so that participants will know whether all members (at least) will make available any essential patents claims on what are traditionally referred to as "reasonable and non-discriminatory" (or RAND) terms.</p>
			<p>Achieving agreement on what such policies should state, and on the process rules under which they are implemented, can be as contentious a process as creating standards with high commercial impact.  Differences of opinion on specific tenets and terms exist not only between individual companies, but also between industries and sometimes among nations.  In recent years, the importance of patents in some sectors, and particularly in the information and communications technology (ICT) industries, has focused increased attention on IPR policies.  That attention has made existing SSOs reexamine their rules, and made it all but impossible to form a new SSO until the founders have agreed upon the IPR policy that the new organization will adopt.</p>
			<p>In this article, I will survey the changes in the standard setting landscape that are accentuating IPR concerns today; the ways in which IPR (and particularly patent claims) give rise to concerns for standards developers and implementers; the documents that comprise an appropriate IPR management regime; some of the SSOs that have grappled with difficult IPR issues today, and the changes that they have made to their IPR policies; and finally those areas in which IPR policies are most significantly being challenged and reworked today.  But first, I will briefly describe the more peaceful days and uniform policies that prevailed before things began to change.</p>
			<a name="section2"></a><h3>II &ndash; The Placid Past</h3>
			<p>For the first hundred years of standard setting, IPR concerns were relatively easily addressed, because most participants in the standard setting process had roughly similar views on how the rights of inventors and standards implementers should be balanced.  During that time period, rules were developed that were reasonably uniform across the world of standard setting, minimizing (if not eliminating) the degree to which owning and sharing IPR complicated the standard setting process.</p>
			<p>The relative lack of friction that prevailed during these years also arose from the fact that individual setting organizations often constituted independent ecosystems, with little reason to interact with each other.  These organizations could develop rules of behavior under otherwise substantially similar IPR policies that were well understood by their members.  In some SSOs, those rules might be highly tolerant of including IPR in a standard that would result in implementers needing to pay royalties to one owner or another, while in others, such an outcome would be seen as very undesirable.  Moreover, a single standards organization often served all of the standards needs of an industry niche.  As a result, many or all of the standards that a given group of industry participants might need in order to build their products were developed within a single, independent organization, and thus subject to the same set of rules and expectations.</p>
			<p>Until recently, standards in most organizations were created by career professionals, who knew each other and collaborated over long periods of time on standards, allowing many potential issues to be identified early in the process, and for differences to therefore be resolved more amicably.  In addition, a large percentage of the standards created in traditional industries were unlikely, or indeed unable, to infringe anything that was patentable (e.g., a standard that sets light bulb wattage increments of 40, 60, 75 and so on, or a standard that dictates the gauges of electrical wiring).</p>
			<p>Standard setting also occurred primarily at the national level.  Indeed, national standards were often created, or at least used, expressly to make it more difficult for foreign vendors to enter the domestic marketplace.  In such a situation, infringement of patents could be considered a favorable attribute of a standard.  But in either event, only IPR issues of national relevance were of concern.</p>
			<p>For all of these reasons, addressing IPR was a comparatively easy challenge, and did not consume a great deal of time on the part of standard setting organizations, virtually all of which were accredited standards development organizations (SDOs) that were, in addition, required to comply with a single high-level set of IPR rules in order to obtain and maintain accredited status.  To the extent that rules varied from organization to organization within the boundaries permitted by such overall rules, these distinctions were not likely to cause problems, due to the level of isolation (noted above) that tended to exist between industry niches, and therefore between those that might be affected by any differences.</p>
			<p>Because of this same insularity, cross licenses were often easy to arrange among the traditional leaders of a given industry.  And so on, in a process common to matured industries that have an interest in sorting things out, and which have evolved common strategies and practices that to create orderly and predictable market conditions within which to compete.  In many SSOs, IPR disputes were therefore unknown, and many members were only dimly aware of the specifics of the IPR policies of the SSOs in which they participated &mdash; assuming those policies had specifics at all.  Many such policies were in fact only one or two pages of high-level statements of principle, or simple references to, or adoption of, the policies mandated by the accrediting authority to which they were subject.</p>
			<p>In short, standard setting could progress apace with relatively little concern over IPR, either curing or after the adoption of a standard.</p>
			<a name="section3"></a><h3>III &ndash; The Turbulent Present</h3>
			<p><strong>3.1 &mdash; A changing landscape.</strong> This placid picture began to deteriorate as the ICT industry evolved with increasing rapidity in the 1980s.  During these years and after, ICT came to play an ever-larger role in the world economy, and new SSOs (mostly unaccredited organizations referred to generally as "consortia") began to proliferate to create the standards (and in particular, interoperability standards) demanded by these new technologies.  The standards that these new SSOs created applied to technical areas that were often the subject of intense patent activity, although not uniformly so.  Software was not yet patentable in the United States in the early years of this progression, and therefore SSOs setting standards for microprocessors and hardware had concerns not shared by the many consortia that sprang up to create software standards.<sup><a href="#1">1</a></sup></p>
			<p>The industries that filed these patents were also used to asserting them aggressively, in order to defend their right to recoup their often significant research and development costs, and to reap the profits they expected to earn on such investments.  Many also had internal cultures that granted high status, and sometimes large bonuses as well, upon those that were successful in acquiring the most patents.</p>
			<p>The convergence of technologies in single devices and business situations caused further problems, as standards broke out of their sectoral silos.  Now, standards that required license fees to implement might be needed in situations where such costs were regarded as intolerable.  To make matters worse, a new business model arose that involved the creation of patentable inventions for the sole purpose of generating license fees, rather than to protect the designs of products that the patent owners themselves manufactured.  Companies adopting this model profit only from fees paid by third parties, and those license fees can increase dramatically if a patented invention, by accident or design, finds its way into a widely adopted standard.  Moreover, since the patent owner (or "troll," as such a business is often unaffectionately called) does not build anything that can infringe someone else's patent, there is no potential to resolve disputes through negotiating a cross license.</p>
			<p>As a result, private parties began to sue companies they believed to have abused the standard setting process by failing to disclose their patent claims, and to complain to government regulators as well.  When this occurred, companies with large patent portfolios were at a loss to know whether to be more reassured or fearful, since the only way to be sure that they disclosed a relevant patent claim would be to conduct a search of their patent portfolios.  Since some companies participate in hundreds of SSOs, institutionalizing such a practice would be prohibitively expensive.  Not surprisingly, these companies strongly resisted any IPR policy change that might suggest that such a search should become a practical necessity.  At the same time, they were concerned that they might inadvertently fail to disclose a patent, and either lose the ability to profit from it, or be fined if they tried to do so.</p>
			<p>Small companies, or companies with few patents, had different concerns.  Not only could they easily determine whether or not they had an essential patent, but they also would be unlikely to negotiate a cost-free cross license with a large competitor that owned a patent infringed by a standard, although its other large competitors could.  Accordingly, companies with few patents focused instead on the potential for a patent owner to hide its patent until a standard was widely adopted, and then extort high license fees after the industry had become "locked in," and unable to redesign the standard in order to avoid a commercial tax upon the sale of compliant implementations.</p>
			<p>These issues first attracted wide concern in 1996, when Dell Computer entered into a consent decree with the Federal Trade Commission in the United States.   That investigation was brought in response to private party complaints that Dell had participated in a standard setting process hosted by the Video Electronics Standards Association (VESA), and had failed to disclose that it owned a patent that it believed would be infringed by any implementation of the standard under consideration.  Only after the adoption of that standard and its initial commercialization did Dell identify its patent and assert a right to require royalties. The FTC concluded that such behavior was a violation of the antitrust laws, and as part of the consent decree, Dell agreed that it would grant a royalty-free license to any implementer of the standard; it was also required to subject itself to oversight in its standards-related activities for a period of ten years.    Had Dell disclosed its patent during the course of the adoption process, it could have stated its intention to require a royalty from implementers, and the working group would have had the opportunity to decide whether to rewrite the standard in such a way as to avoid infringement, or to knowingly adopt the standard subject to the royalty requirement.</p>
			<p>The impact of the Dell consent decree was substantial, as news of the facts and the significant penalty became widely known.  This was less because the integrity of the standards development process had been upheld, but because Dell had contended that it's representative in VESA did not know of the patent in question, and that its failure to disclose was inadvertent.</p>
			<p>Regardless of the truth or falsity of Dell's defense, the possibility of making an innocent mistake seemed all too real to large patent holders.<sup><a href="#2">2</a></sup> From the date the consent decree was announced until the present, scrutiny of IPR policies has steadily increased.  In recent years, litigation and investigations have again been launched, based upon similar patters of alleged conduct.  The most prominent example involves a semiconductor design company called Rambus, Inc.  Rambus has been mired in litigation with multiple semiconductor manufacturers for most of the current decade, and also been convicted of creating an illegal monopoly by the FTC.  More recently, telecommunications giants QUALCOMM Incorporated  and Broadcom Corporation have been locked in combat, in part over Broadcom's accusation that Qualcomm has engaged in conduct reminiscent of  Rambus.<sup><a href="#3">3</a></sup></p>
			<p>Today, however, some owners of large patent portfolios are shifting their focus away from the possible consequences of an inadvertent failure to disclose an essential patent to a different concern: whether the products they hope to build will be taxed with such high levels of patent fees that they cease to be commercially viable.  This is in response to a variety of current trends, including convergence, the increasing number of patent filings in some areas, the possibility that the troll business model will proliferate, and the rising importance of open source software.  Several of these trends bear mention in greater detail:</p>
			<p><strong>3.1.1 &mdash; Patent thickets.</strong> The number and density of "patent thickets" (i.e., areas of intense patent activity that focus on commercially important technologies) is increasing.  When standards are created in areas that have thickets, it is almost impossible not to infringe upon one or more patents.  One consequence is that such a standard may provide an economic advantage to companies that can cross license their essential patents at no cost among themselves, while those that do not hold relevant patents must pay royalties.  Where the patent owner is a troll, the playing field is level as among all competitors, because all must pay, but the cost in license fees may impede adoption of the standard.</p>
			<p><strong>3.1.2 &mdash; Convergence.</strong> A single device or service may now include many more standardized technologies than in the past.  A mobile device that incorporates a camera, video, PDA functions, a Web browser, text messaging and wireless, for example, will implement hundreds of standards.  If even a small percentage requires payment of royalties, the device may become uneconomical to produce.  Where no royalties are involved, a manufacturer may still be forced to negotiate and enter into many license agreements, each with its own terms. </p>
			<p><strong>3.1.3 &mdash; Open source software.</strong> The phrase "open source software" implies that the actual source code of the software will be available under one of a number of different licenses that have been accepted by the Open Source Institute (OSI) as meeting its requirements for being designated as such.  Those terms demand, at minimum, that the source code (i.e., code that can be easily understood by a developer, as compared to object code, which is readily "understood only by a computer) must be made available to the licensee.  Many licenses, such as the GNU General Public License, or GPL, have additional requirements, such as requiring that someone that modifies and sells software received under that license must make those modifications available under the GPL as well.  The GPL also prohibits including any license terms deemed to be inconsistent with its own.</p>
			<p>When open source software needs to implement standards, parts of the resulting code may necessarily infringe upon patent claims that are essential to the standard.  If the standard so implemented permits the patent owner to require license terms that are prohibited under the open source software license, a conflict occurs.  As a result, open source community advocates, as well as those commercial entities that are increasingly basing their business models around open source software, do not wish standards that are important to open source implementations to be created under IPR policies that would permit license terms to be imposed that are incompatible with the requirements of popular open source software licenses.  The only way to lessen the likelihood of that outcome is by adjusting the IPR policy of the SSO creating the standard to so provide.</p>
			<p>For all of these reasons and more, the IPR rules and policies under which SSOs operate today are matters of line-by-line concern to many standard setting participants.</p>
			<a name="section4"></a><h3>IV &ndash; IPR Policy Coverage and Implementation</h3>
			<p>While the members of different SSOs will take different paths in creating and deploying an IPR regime, the subject areas that each organization must face are common to all.</p>
			<p><strong>4.1 &mdash; Coverage.</strong> Each IPR policy that provides comprehensive IPR protection needs to address the following subject areas:</p>
			<p><strong>4.1.1 &mdash; Copyright.</strong> Copyright issues under IPR policies are comparatively simple.  The near-universal practice is to provide that if a member contributes any material for inclusion in a standard, it retains ownership in that contribution, but irrevocably (a) licenses the SSO to make the contribution available to other members for purposes of considering its inclusion in a standard, (b) licenses the SSO to distribute the eventual standard with the contribution included, in whole or in part,  and (c) agrees that the SSO will own the copyright in the final standard into which the contribution is incorporated.<sup><a href="#4">4</a></sup></p>
			<p>The main controversy involving copyright involves not the terms to be used, but the ability of an SSOs right to enforce its copyright when a standard has been referenced by, or incorporated into law.  The issue is of significance to SDOs, and not consortia, because the great majority of the former derive significant, and in some cases the majority of their operating revenues from sales of their standards, while the latter rarely charge for their standards at all.  In general, there is no question that those SSOs that wish to charge for access to their standards may do so.  But in 2003, in a case called <em>Southern Building Code Congress International v. Veeck</em>, the U.S. Court of Appeals for the Fifth Circuit handed down a decision that caused a great deal of consternation among SDOs.  In what has come to be simply referred to as "the Veeck case", the matter at issue was a Texas building code that referenced a standard, and the matter arose when someone posted a copy of the referenced standard on a public Web site.  The owner of the standard thereupon sued, alleging that it was unjust to require the purchase of a standard that a builder would be legally obligated to implement. </p>
			<p>The holding captured the immediate attention of the SDO community nationwide, despite the fact that it was binding only in the Fifth Circuit, and even though it related only to standards referenced, or incorporated into statute.  The reason was the fear that the ruling might be extended to all standards.  Following the decision, the SDO sought the intercession of the Supreme Court, which declined to hear the case, despite the fact that at least two other Circuits had issued opinions that reached different conclusions.<sup><a href="#5">5</a></sup> The holding of the lower court therefore remains binding in the Fifth Circuit - as well as a precedent that courts in other circuits may decide to follow, even if they are not legally bound to do so. As a result of the Supreme Court deciding not to hear the appeal, uncertainty will continue regarding whether other courts will follow (or not) the Fifth Circuit's reasoning, and if so, whether they will do so in a more limited or comprehensive fashion. </p>
			<p><strong>4.1.2 &mdash; Trademark.</strong> Trademark rules under IPR policies are also non-controversial.  All policies agree that members retain ownership of their trademarks, and SSOs retain ownership of theirs.  Trademarks are particularly important to SSOs that conduct, or authorize the operation of, certification testing, because a license to a well maintained trademark must be obtained by a product or service provider as a precondition to holding their goods or services out as being in compliance with the trademarked standard.<sup><a href="#6">6</a></sup></p>
			<p><strong>4.1.3 &mdash; Patents.</strong> Simplicity ends with patents, and as a result 90% of the language, and almost 100% of the controversy, surrounds the rules that relate to so-called "essential claims."  These issues will be dealt with in detail in Section IV below.</p>
			<p><strong>4.1.4 &mdash; Confidentiality.</strong>IPR policies usually deal with confidentiality in one of two ways: by either establishing rules for describing what is entitled to be maintained in confidence, or by declaring that nothing is to considered confidential.  The latter approach is more common, and is indicative of an organization that maintains "best practices" in creating what are understood to be "open standards."<sup><a href="#7">7</a></sup></p>
			<p>That said, there is often a distinction between whether information will be public, and if so, when it will be made so available.  In part, this is a reflection of economic concerns, since early access to the text of an evolving standard can have commercial value, and thus provide an incentive to become a member.  In addition, those that can view the text and direction of a standard under development could surreptitiously seek to file patent applications on inventions inspired by the evolving standard.  If the evolving standard is visible only to members that are bound to disclose any relevant patents or patent applications, then such a result can be avoided (at least to the extent that members abide by the rules).</p>
			<p>But if the emerging text is available to all, then a non-member could file, or amend, a patent application to place it in the way of implementers without violating any rules at all.  For this reason, many SSOs limit access to an evolving specification to members alone, and sometimes only to those that have enrolled in the working group that is producing it, until a later date.  For some SSOs, that later date is after final adoption, while for most it is when the draft standard is in near-final form.  At that point, many SSOs post the draft for public, as well as member, comment.  Those comments will usually be technical, but may also include a warning by a patent owner that implementation might result in infringement of its patent, or an alert by someone else that it is aware of a patent of possible concern.</p>
			<p><strong>4.2 &mdash; Implementation.</strong> IPR policies are most often deployed in one of two ways: either by a Board (and sometimes member) adopted policy, or by inclusion in the application that each member must sign to become a member.  In the former case, a member signs a much shorter application, but that application includes language that makes all Board-adopted policies binding upon each member.<sup><a href="#8">8</a></sup></p>
			<p>IPR policies, however deployed, tend to be high-level documents.  As a result, a more detailed set of policies and procedures is also required, in order to provide the many procedural rules necessary to guide multiple standards working groups in creating and reconciling the standards being created, in setting rules of quorum and voting, and so on.<sup><a href="#9">9</a></sup></p>
			<p>As court cases have consistently indicated, it is essential that an IPR policy, once adopted, be consistently described and enforced.<sup><a href="#10">10</a></sup> Similarly, in order for commitments that members make to be of reliable use in the future, they must be clearly stated.<sup><a href="#11">11</a></sup> The documentation that instantiates an IPR regime must therefore be carefully drafted and maintained.</p>
			<p>The final suite of documents to both institute and implement an IPR regime, and their functions, are commonly as follows:</p>
			<table class="EssGuideT1">
				<tr>
					<td valign="top"><p><strong>Document</strong></p></td>
					<td valign="top"><p><strong>Function</strong></p></td>
				</tr>
				<tr>
					<td valign="top"><p>Membership Application</p></td>
					<td valign="top"><p>A binding contract between the SSO and the member, that requires the member to obey the IPR Policy and all related rules and procedures</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Bylaw language</p></td>
					<td valign="top"><p>A section of this document gives the Board the authority to adopt, amend and administer the IPR Policy and all related rules and procedures</p></td>
				</tr>
				<tr>
					<td valign="top"><p>IPR Policy</p></td>
					<td valign="top"><p>A set of high-level rules that address all crucial patent, copyright and trademark issues</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Assertion Forms</p></td>
					<td valign="top"><p>A set of short forms used to disclose IPR and to commit to licensing choices.  One form must be completed in connection with, and must accompany, any submission made by a member for possible inclusion in a standard, and a similar form must be completed by every member of a working group at the time that it votes to recommend a draft standard for adoption (some SSOs require non-working group members that vote to adopt a standard to complete a form as well).  The forms contain language that tracks the IPR policy, and a member may only select which licensing statement it chooses to make, and not change the language of the commitment itself.  Exhibits are provided for the disclosure of essential patent claims, and the portion of a draft standard to which they relate</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Rules of Procedure</p></td>
					<td valign="top"><p>The "bylaws" of the technical process</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Trademark Guidelines</p></td>
					<td valign="top"><p>Rules of usage for SSO trademarks</p></td>
				</tr>
				<tr>
					<td valign="top"><p>Trademark License</p></td>
					<td valign="top"><p>As needed, if a compliance or certification mark program is put into place</p></td>
				</tr>
			</table>
			<a name="section5"></a><h3>V &ndash; Patent Issues</h3>
			<p>By far and away the most difficult IPR issues that SSOs must address involve patent claims.  Unlike other types of IPR, patent claims can often only be designed around with great difficulty.  Sometimes, patent claims can represent complete roadblocks to a solution, either because no alternative approach is technically possible, or economically feasible, to implement.</p>
			<p>As a result, SSOs go to great lengths to avoid knowingly adopting specifications that infringe upon the patent claims of a member or third party that is not willing to cooperate.  At worst, such a patent owner may be unwilling to provide a license to anyone that wishes to implement the standard, or may only be willing to provide a license to some, but not all would-be implementers.  Almost as seriously, the patent owner may wish to charge a fee or impose other terms that would impede or preclude wide adoption.</p>
			<p>Unfortunately, there are two reasons why it is impossible to totally avoid the potential for inadvertent patent infringement:  first, conducting patent searches for every standard on a worldwide basis would be both prohibitively expensive, as well as ineffective in avoiding allegations of infringement, because patent owners will often have different opinions about the coverage of their patents than will third parties.  Second, only a small percentage of the holders of affected patents will typically be members of a given SSO, or even implementers of its standards.  Consequently, simply asking those members that are willing to act in good faith whether they have any patents of concern can reveal at best only some of the patents that may be infringed by any given standard.  Even then, a response from an individual to the best of her knowledge regarding the reach of the patent portfolio of their multinational employer provides only minor comfort at best.</p>
			<p>Nor can SSO members be required to conduct internal patent searches, since the companies that participate in the largest numbers of SSOs own thousands, and even tens of thousands, of patents.  As already noted, no SSO would find itself politically able to impose such a requirement unless its membership included only those with few, or not, patents.  Indeed, almost all IPR policies for this reason include a very specific term stating that no member shall ever be required to conduct a formal patent search by reason of its participation in the SSO.</p>
			<p>Even if all of these problems could be resolved as to members under IPR policies and rules, non-member patent owners would still be free to act as they wished, and could therefore at best only be cajoled, rather than compelled, into providing license rights to all would-be implementers on RAND terms for any patent claims that might be infringed by a standard.</p>
			<p>Despite this discouraging landscape, SSOs nevertheless do what they can to craft IPR policies intended to clear the field of problems involving at least member-owned patents, and in particular to prevent any game playing by members that might otherwise seek to "plant" patent claims in a standard in order to reap future economic rewards.</p>
			<p>Achieving consensus on the rules underlying such policies can be a daunting challenge, however, due to the great value that most companies associate with their patents, and the variety of opinions that they hold on how best to protect that value in the context of standard setting.  As a result, and absent special concerns, it is usually sensible for an SSO to adopt as mainstream a policy as possible, since the middle ground represented by such a policy will likely be the only feasible meeting point for conflicting viewpoints.  Where an SSO strays from this middle ground, it sometimes finds that its mission may be hampered, or even defeated, due to its inability to attract a broad membership.</p>
			<p>It is therefore essential that those who are tasked with drafting an IPR policy understand the positions that individual companies are likely to take on specific IPR policy terms, and the legal and practical concerns that underlie these positions.  Sadly, after stating that all patent claims must be available on at least RAND terms, it becomes difficult to achieve consensus on almost everything else.</p>
			<p>The issues that lead to this diversity of viewpoint may be usefully sorted and analyzed under the familiar headings of "Who", "What", "When", "Where" and "Why." </p>
			<p><strong>5.1 &mdash; Who?  </strong>Some SSO participants believe that it is sufficient to collect licensing commitments only from those members that directly participate in creating a standard, since these are the patent owners that are able to actively "game" the system, either passively, by failing to disclose their patent claims, or actively, by pushing the process towards adopting a standard which would entitle them to levy a royalty.  This requirement to make a binding commitment to license, or to disclose the possibility that a RAND license might not be forthcoming, makes obvious sense from a practical perspective.<sup><a href="#13">13</a></sup> However, other SSO members may believe that a licensing commitment should be required of every member of the SSO, whether or not it chooses to participate directly in a given process.  The practical effect of such a requirement is that the circle of safety is expanded simply by requiring the commitments of more potential patent owners.  More significantly, if non-participating members have access to specification drafts as they mature, those non-participating members could file patent applications that track the evolving standard.  Unless required to disclose such patent applications, those members that were acting in good faith could later be taken by surprise.</p>
			<p>Other SSO members believe that the rules should reach still farther, and insist that any implementer of a standard - whether a member or not - should grant all other implementers a cross license of its own patent claims to the extent necessary to avoid infringement.  The impact of this position may impede implementation of a standard, however, since most standards need promotion before they become pervasively adopted, and many implementers may have very low motivations to adopt a standard at all.  Where a cross license is required, such non-member companies may choose not to implement the standard at all.</p>
			<p>Of course, such a mandatory cross license is not likely to capture someone that has truly bad intentions in any event, as such a patent owner may intend to reap a far higher return from taxing all implementers than through implementing the standard itself.  As a result, a standard may be unlikely to receive much benefit - but can be severely impaired - by a broad cross license requirement.  In the case of standards that are relevant to software, such a mandatory cross license term would violate the terms of many open source licenses as well, and thus any standard that was created under an IPR policy that permitted patent owners to require such a cross license would be unacceptable to the developers of the open source software.</p>
			<p>For all of these reasons, the most common method of addressing this concern under IPR policies is to permit what has come to be called a "defensive suspension" term in licenses of essential patent claims.  Under this licensing term, a patent claim owner that has agreed to provide a license to implementers of a standard on RAND terms is entitled to revoke the license of any implementer that asserts its own patent under non-RAND terms.  This levels the playing field for further negotiation, and is considered to be consistent with a RAND licensing commitment.</p>
			<p><strong>5.2 &mdash; Who (II)?</strong> A related issue briefly alluded to above is whether an assertion by a member representative that she has no patent claims to disclose should be limited to the knowledge of the individual alone, or should extend to the deemed knowledge of her corporate employer (the actual member) as well.  For a large multinational company with perhaps thousands of engineers participating in hundreds of standards working groups, this prospect represents an IPR manager's nightmare, unless a decision has already been made by the corporate member that it is willing to make all patents available on RAND terms &mdash; assuming that RAND terms are all that the IPR policy requires (and not royalty-free licensing).  On the other hand, an assertion to the personal knowledge of a single employee that she is unaware of any potential for infringement is useful only to the extent that it helps preclude conscious misbehavior.  While that is an important result, it is less useful than an undertaking that a member will never assert a patent at all on other than on RAND terms.</p>
			<p>As a result, many IPR policies acknowledge that <em>disclosures</em> are made only to the knowledge of the individual participant, but may still require the member to <em>commit</em> to a given course of action, if it later becomes aware of a patent claim that might be infringed.  Regardless of which approach is taken with respect to eventual disclosure, a well thought through IPR policy (or the procedural document supporting that policy) will contain a term stating that the member will become irrevocably bound to make a disclosure and licensing statement at the end of the process once it has participated in a working group for some period of time (e.g., 60 days).  Otherwise, a member could attend a working group in public, and file patent applications in private, until just before the requirement to put its IPR cards on the table matured, and then drop out, only to reveal its "submarine patents" after the standard had become widely adopted.<sup><a href="#14">14</a></sup></p>
			<p><strong>5.3 &mdash; What?  </strong>There is also a difference of opinion over what rights a patent holder must grant.  Some believe that, in at least some situations, royalty free licenses should be required from every company that participates in the adoption process.  The most fervent champions of free licensing would require every member of an SSO to agree to grant a license to whatever standards may be developed while they are a member (although most would permit a member to resign to avoid this result in a given situation).  Not surprisingly, such a comprehensive rule would lead many technology companies to refuse to participate in an SSO with a broad development mission, unless participating in the work of that SSO was extremely important to their business.</p>
			<p>While not uncommon, such a rule is found mostly in organizations with small memberships, comprising only companies that have much to gain by creating the standard.  Unless the member companies control a large portion of the marketplace, however, the rule can be self-defeating, since other stakeholders that are needed to support the standard, but who have less to gain from its adoption, are often unwilling to agree to so strict a term.</p>
			<p><strong>5.4 &mdash; When?</strong> While most SSOs require that licensing commitments be made towards the end of the standards development process, others require commitments to be given earlier in order to clear the way for smooth final approval of the standard under development. This is a sensitive issue, because many companies are not willing to commit to grant a license until they have had the opportunity to conduct some degree of internal investigation to discover what, if any, valuable technology rights may be involved.  Also, they may wish to assess whether the resulting standard will be highly favorable to their business, and therefore whether any lost licensing opportunity will be outweighed by the benefits anticipated from broad adoption.  If a commitment to license, and especially a commitment to license on a royalty free basis, must be made at the time of joining a working group (or soon after), the right to evaluate probable benefits thus becomes limited.  Finally, companies often fear that if they make a licensing commitment in advance, they may be trapped by competitors that conspire to include valuable IPR owned by the first company in the resulting standard.</p>
			<p>For companies with substantial patent portfolios and the desire to participate in many standard setting efforts, early decision making is therefore an issue of significance.  Conversely, other companies (and particularly companies with small, easily searched patent portfolios) may be unwilling to spend months on helping develop a draft standard, only to learn at the time that a vote to adopt is taken that a participant has a blocking patent, and is unwilling to make rights under that patent available on acceptable terms.  Companies that endorse this viewpoint have concluded that the standards that are developed are more important to them than maximizing the commercial return on their patent portfolios, so long as they can reserve the right to charge a royalty on any of their IPR that may eventually be found to be covered by a finally adopted standard.<sup><a href="#15">15</a></sup></p>
			<p><strong>5.5 &mdash; Where?</strong> Once a standard has been adopted that requires a vendor to obtain one or more licenses as a precondition to implementation, the question arises where and how an implementer can obtain those rights.  In an ideal world, all of those rights could be obtained at the Web site of the SSO that developed the standard, along with the SSO's permission relating to the standard itself.  In fact, patent owners rarely permit an SSO to sublicense patent claims, and the SSO therefore may only grant rights in the copyright that it owns in the standard itself.  This is typically accomplished using a short and simple "clickwrap" license, which exists principally to exclude any warranties of any type (e.g., as to ownership, non-infringement, and so on).</p>
			<p>Where any member or third party has asserted the right to require a royalty and/or to precondition implementation upon other license terms (e.g., it may want a defensive suspension right), a would-be implementer most go direct to the patent owner to obtain the necessary rights. Typically, the standard setting body does not become directly involved with the terms of such licenses, and never takes a position as to whether an asserted patent claim is indeed essential, it will usually provide a list of those patent owners that claim that a license is required, together with contact information for such owners.</p>
			<p>At times, there are so many patents that are asserted against a single standard (as can occur when a standard overlies one of the "patent thickets" referred to above), the owners of those patents will sometimes form a patent "pool."  In such a case, an administrator is retained to manage the licensing and economic terms on behalf of all of the patent owners.  This allows an implementer to pay a single fee, and sign a single license, in order to obtain all required rights relating to the underlying patents.  The fees are then divided among the pool participants, according to a mutually agreed upon formula.</p>
			<p>Regardless of the licensing arrangements that relate to patents underlying a standard, a license that forbids the implementer to sublicense can have an adverse impact under many open source software licenses.  Such a restriction will not be problematic for an implementer that wishes to build an application for internal use only.  But if it is a vendor that wishes to sell that application, then the terms of many open source license agreements would be violated if its customers were obligated to return to the patent owner for their own license (and even if that license could be obtained free of charge).</p>
			<p><strong>5.6 &mdash; How?</strong> The great majority of IPR policies in existence today still rely upon RAND licensing commitments.  A reasonable and important question, therefore, is what exactly does "RAND" mean, and what terms would be considered to be acceptable under a license intended to meet such a commitment?   Perhaps surprisingly, SSOs almost never try to define exactly what either "reasonable" or "non-discriminatory" is intended to mean.  Even more surprisingly, until recently there have been relatively few disputes litigated between patent owners and implementers over these terms.<sup><a href="#16">16</a></sup> Most SSOs have shrunk from becoming involved in such disputes, since they lack the resources or the will to take an active part.</p>
			<p>Despite this overall reluctance for any party involved to tackle the RAND definition issue, the popularity of the simple RAND rubric continues, giving rise not only to obvious questions (e.g., how high can a royalty be before it becomes "unreasonable?"), but to more subtle ones as well, such as whether it is discriminatory to charge a cross license partner nothing to implement a standard, while charging a royalty to the competitor of the partner with whom the patent owner does not have a patent license.  If such a position does not represent discrimination, then the second company will be at a price disadvantage to the first.<sup><a href="#17">17</a></sup></p>
			<p><strong>5.7 &mdash; Why?</strong> Another interesting question relates to why given companies take particular positions on certain issues.  A simple explanation is that it is difficult for a company to step outside the realities of its familiar proprietary world and assume the mind-set necessary to give away something (i.e., valuable IPR underlying a standard) in order to gain something of greater commercial value.  One often under-appreciated benefit is the luxury of making a safe strategic decision (e.g., for a manufacturer, knowing in advance that it is committing to what will prove to be the "VHS" rather than the "Betamax" standard).  Thus enabled, it can compete with other SSO members in making better and more appealing products based on the adopted standard, and address a more swiftly and surely developing market for those products.  Even long-term participants in the standards process can sometimes catch themselves taking a position that is inconsistent with consortium goals, simply out of habit.  The most enlightened and successful participants in standard setting (in this author's opinion) are therefore those that most thoroughly "get" the fact that they have far more to gain from the success of a standard than they could expect to gain in patent royalties on any underlying patents.</p>
			<p>Another cause of confusion and insistence on unnecessary and counterproductive positions is the superficial similarity between commercial joint ventures and SSOs.  In the former, a small number of companies forms an alliance under a joint development agreement to create a product or other deliverable that the participants can then sell, or otherwise exploit.  In this type of activity, it is typical for all participants to cross license all patent claims to each other that would be infringed by a joint created specification, and to permit each other to sublicense implementation rights to third parties as well.  But the core cross-license rights are usually restricted to the small number of "by invitation only" participants, that wish to keep control of the design, as well as the most lucrative commercial benefits, to themselves.</p>
			<p>In an SSO, however, the goal is to create a standard that is adopted and implemented by as many companies as possible.  As a result, every implementer is given equal rights to every other implementer, as an incentive to participate in the ever widening pool of adopters.<br /> <br /> While both types of efforts involve multiple competitors gathering to agree on technology solutions, there are several significant differences.  First, the participants in a commercial joint venture are highly motivated to achieve a carefully defined and limited common goal, and are therefore willing to share all IPR needed to achieve that goal.  Similarly, their partners are highly motivated to gain access to the same rights, and are therefore willing to enter into sublicenses and agree to payment terms.  The legal vehicle employed by the joint venture participants - a contract - is appropriate, since few or no new members are expected to join, and the founding members are not expected to leave until the goal has been achieved.  Finally, there is no need to create a pretense of "openness."</p>
			<p>In sharp contrast, an SSO needs to allow members to join and leave, and needs to make it as easy and attractive as possible for non-members of many stripes to adopt and implement its standards.  A key component in achieving this goal is to be structured and operate in as "open" a way as possible, to negate any appearance that one or more companies can unduly influence the eventual nature or availability of its standards, thus giving them a commercial advantage over other implementers.</p>
			<p>Since most individuals who represent companies in SSO activities - and even those who are tasked with forming new consortia - have limited knowledge about the theory and practice of SSO formation and operation, it is easy for them to assume that whatever previous organization they have participated in represents the gold standard of structure and governance.  One unfortunate outcome of this reality is the surprisingly large number of consortia that have been formed on the more restrictive commercial joint development model, even where the tight controls and high demands of that model were unnecessary.  Where this has occurred, the result has usually been to hamper, rather than lead to, the success of the organization.<sup><a href="#18">18</a></sup></p>
			<a name="section6"></a><h3>VI &ndash; Current Issues and Trends</h3>
			<p>Thus far, this article has described the general shape of IPR policies, positions and solutions that have prevailed over the past decade.  Today, however, some participants in the standard setting community are calling for significant changes in IPR policies and practice.  Topics currently under discussion include the following:</p>
			<p><strong>6.1 &mdash; Ex ante disclosure.</strong> The basic concept behind <em>ex ante</em> disclosure is "earlier is better, and more is better."  In practice, what that means is permitting or requiring those that are involved in creating a standard to state more than just whether they have patents, and whether they are willing to license them on RAND terms, but what those terms are in greater detail.</p>
			<p>The very topic of <em>ex ante</em> disclosure causes alarm for many, due in part to antitrust concerns.  For decades, those that participated in standard setting activities have been instructed by their lawyers to never make any mention of prices in a room populated with competitors.  While certainly it is true that the actual negotiation of prices could have dire results, representatives of both the Federal Trade Commission as well as the Department of Justice have made statements in the last two years indicating that <em>ex ante</em> disclosure, properly undertaken, could be looked at favorably by the regulators, and in fact could have procompetitive, rather than anticompetitive, effects.</p>
			<p>Recently, two ANSI accredited SSOs, the IEEE and VITA, have drafted amendments to their IPR policies that would permit (in the case of IEEE) and require (in the case of VITA) the disclosure of the terms upon which essential patent claims would be licensed under a draft standard, if finally adopted.   Both organizations submitted requests to the FTC for "business review letters," under which the FTC would evaluate the SSOs proposed <em>ex ante</em> procedures.  In each case, the FTC responded favorably. The guidance provided in those letters, as well as in any letters that may issued to other SSOs in the future, will be very useful to those SSOs that wish to consider similar amendments.</p>
			<p>The IEEE and VITA policies will also be reviewed in the context of the rules of the American National Standards Institute (ANSI), the accreditor of each SSO.  That review will be conducted by the ANSI Executive Standards Council (ExSC), the appointed body for the task under the ANSI Essential Requirements: Due Process Requirements for American National Standards.<sup><a href="#19">19</a></sup>  As with the FTC business review letters, the results of these reviews will be instructive for other ANSI accredited SSOs that may wish to amend their own policies and procedures.</p>
			<p>The overall topic of <em>ex ante</em> disclosure, however, is a difficult one, and there is a wide variety of opinion regarding the advisability of wide-scale adoption of changes to permit such disclosures.  Some very large companies, particularly in the information technology sector, are strongly in favor of such changes, while others in the same market space are opposed.  The reasons for such opposition range from concerns over antitrust exposure, to the belief that such disclosures will not prove to be useful, to a desire to retain as much freedom of movement as possible in order to maximize licensing returns.<sup><a href="#20">20</a></sup></p>
			<p><strong>6.2 &mdash; Royalty free licensing.</strong> There has long been a preference in many sectors for adopting standards that would successfully avoid infringing patents that would have price tags attached.  With the advent of the Web, this objective became more determined in some organizations, and in particular in the World Wide Web Consortium (W3C), an organization with a broad technical program, a very large membership (including most of the largest IT companies in the world), and an important mission.  Those who participated in the revision committee at the W3C endured a marathon, three-year process that eventually resulted (in May of 2003) in an amended IPR policy intended to make it nearly impossible to finally approve a standard that knowingly would result in the requirement of paying a royalty or other fee to a patent owner.<sup><a href="#21">21</a></sup></p>
			<p>The arduous process followed by the W3C involved the business and legal representatives of many of the largest technology companies in the world, and marked something of a watershed.  Prior to the approval of the new policy, such an outcome would be been difficult to imagine, but afterwards, other SSOs could more seriously consider adopting policies that either mandated the same result, or permitted individual working groups to operate under a similar rule set.  The Organization for the Advancement of Structured Information Standards (OASIS) took this approach in an amended policy (which itself took two and a half years to complete) that was adopted on April 15, 2005.<sup><a href="#22">22</a></sup></p>
			<p><strong>6.3 &mdash; Open source licensing.  </strong>Many of the licenses under which "open source" software, and in particular "free and open source software" (FOSS), prohibit certain types of conduct on the part of anyone that wishes to commercially redistribute a software product that includes the open source software, whether in whole or in part.  As has already been mentioned, some of those prohibitions relate to terms that would be otherwise acceptable in licenses that apply to patents underlying the implementation of open standards.</p>
			<p>The result has been not only a periodic clash between advocates of open source licensing and developers of open standards, but further complications for the already difficult process of achieving consensus over IPR policy rules.<sup><a href="#23">23</a></sup>  When OASIS adopted the new IPR policy noted above, it added a track under which a given working group could decide to create a standard under rules conducive to open source implementations (it also included tracks that allow only RAND-free implementations, and finally a third track, that would allow RAND-royalty assertions).<sup><a href="#24">24</a></sup></p>
			<p><strong>6.4 &mdash; Harmonization.</strong> Given the difficulty of achieving consensus on IPR policy terms and the great amount of effort that negotiations over such terms can consume, several recent initiatives have been directed at harmonizing, or at least better understanding, IPR terms.</p>
			<p>One such effort has been underway in a subcommittee of the American Bar Association for over two and a half years.  During this period, attorneys have been meeting regularly by telephone and in person to create an illustrative IPR policy, with annotations explaining the rationale behind common IPR policy terms.  One important goal of this project is to permit new SSOs, as well as existing SSOs that wish to upgrade their IPR policies, to more easily achieve consensus over what their own IPR policy should state.</p>
			<p>Another effort relates to making it less confusing and burdensome to participate in multiple SSOs.  On March 19, 2007, the three "Big I's" of global standardization, the International Organization for Standardization (ISO), the International Electrotechnical Commission (IEC) and the International Telecommunication Union (ITU), jointly announced that they had "harmonized" and "aligned" their respective patent policies.<sup><a href="#25">25</a></sup></p>
			<p><strong>6.5 &mdash; RAND specificity.</strong> Although no specific actions are known to this author to be underway, the vagueness of a RAND declaration is becoming the subject of increasing criticism, as well as litigation, as earlier noted.  While mandatory <em>ex ante</em> disclosure requirements could moot the need for RAND declarations entirely in some SSOs, it is possible that other SSOs may someday decide to more precisely define exactly what RAND should mean instead, in order to narrow the scope for potential downstream surprises.</p>
			<a name="section7"></a><h3>VII &ndash; Summary</h3>
			<p>It would be an extreme understatement to suggest that the technology industry has reached a state of clear consensus on what constitutes the ideal IPR Policy.  A single example from the author's experience will demonstrate how elusive a goal such a state of universal enlightenment could prove to be.  Not long ago, I spoke separately with two in-house attorneys from the same company, on the same day, relating to the IPR policies of two different consortia.  In each case, the lawyer to whom I spoke was adamant in his contention that his company could not, and would not, join any SSO with an IPR policy that included the language in question.  The problem was, of course, that the language under discussion in each case was essentially the same, while the positions taken by the two attorneys were completely opposite.</p>
			<p>The good news is that awareness of the issues at stake in IPR policies has risen remarkably, in part due to the fact that several high-profile cases involving standard setting abuse have been recently litigated.  While this increased attention has brought more stakeholders into the discussion, and therefore has slowed the process of achieving consensus, that same dialogue has served to make those participating in these discussions better versed regarding common IPR policy concerns, as well as better acquainted with the compromise terms upon which these concerns are most likely to be resolved. </p>
			<p>Notwithstanding this relative progress, it will likely remain a challenge for each SSO to craft an IPR policy that all of its members can live with, and which can still facilitate the achievement of standard setting goals.  While the process of promulgating a robust policy can hardly be described as recreational, it is a task that cannot be avoided by any new consortium that wishes to recruit members.  Similarly, every existing SSO that has not reviewed its IPR policy in recent years would be well advised to subject its process and rules to a critical analysis, with the goal of purging it of ambiguities and to bring it up to date with current member expectations.</p>
			<p>For an existing consortium, tackling an overhaul of current policies will inevitably be a challenge.  But for the members of a new consortium, there is an advantage for tackling the process while their numbers are few, and consensus is therefore more easily achieved.  Thus, the virtue of facing up to a rather thankless chore early on will be rewarded by an easier path to a successful conclusion.  Those who shrink from that chore will inevitably face a much more difficult task down the road.</p>
			<p class="note"><strong>NOTE:</strong> If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a> if you have questions about this topic.</p>
			<p class="center">Copyright 2007 Andrew Updegrove</p>
			<p><strong>End Notes</strong></p>
			<p><a name="1"></a><sup>1</sup> Perhaps this fact explains the two major models that arose to create ICT standards outside of the accredited process during these years: the "promoter-adopter" model that was very frequently employed (and still is) in the microprocessor industry, and the incorporated, nonprofit membership organization that was almost always employed in the software space.  The former model can accurately be described as a "by invitation only" cross-license, with right to sub-license, contractual arrangement that usually relates to a single standard, while the latter is a more flexible creation that usually allows anyone to join, and which is well suited to create many standards over time.  The promoter-adopter model therefore allows close controls to be maintained over patent rights, while the structure of the latter usually has a very simple membership application, and therefore must rely upon the adoption and administration of an IPR policy to address patent issues.</p>
			<p><a name="2"></a><sup>2</sup> The Consent Decree itself is somewhat ambiguous, and does not clearly state that Dell knowingly withheld disclosure.  Whether this vagueness is due to any uncertainty on the part of the FTC, or simply reflects negotiation between the parties, is unknown to this author.  The practical effect, however, may have been to raise greater alarm among other standards process participants.  For a brief summary of the case, see &lt;http://www.consortiuminfo.org/laws/#dell&gt;.  For the full text of the Decision and Order, see &lt;http://cyber.law.harvard.edu/seminar/internet-client/readings/Week10/ftc_complete.doc&gt;.</p>  
			<p><a name="3"></a><sup>3</sup> The many private suits and public prosecutions involving Rambus would require thousands of words to summarize.  For a short summary and the most recent developments in the FTC's action against Rambus, see Updegrove, Andrew, <a href="/bulletins/feb07.php#update">FTC Caps Rambus Royalties</a>, ConsortiumInfo.org, Consortium Standards Bulletin, Vol. VI, No. 2, February , 2007, at &lt;http://www.consortiuminfo.org/bulletins/feb07.php#update&gt;, and sources sited therein.  The most recent activity in the Qualcomm suit is summarized at Updegrove, Andrew, <a href="/standardsblog/article.php?story=20070323094639964">Federal Court Convicts Qualcomm in a "Son of Rambus" Suit</a>, ConsortiumInfo.org, The Standards Blog, March 23, 2007, at &lt;http://www.consortiuminfo.org/standardsblog/article.php?story=20070323094639964&gt;.</p> 
			<p><a name="4"></a><sup>4</sup> Typical copyright license language in an IPR policy might read as follows (the example is taken from the current version of the policy template the author has used in assisting over 60 SSO clients create or upgrade an IPR policy):</p> <p>"Each Submitter that contributes copyrighted materials to the Consortium shall retain copyright ownership of its original work, while at the same time granting the Consortium a non-exclusive, irrevocable, worldwide, perpetual, royalty-free license under the Submitter's copyrights in its Submission to reproduce, distribute, publish, display, perform, and create derivative works of the Submission based on that original work for the purpose of developing a Draft Specification, Specification or Other Work Product under the Consortium's own copyright."</p>
			<p><a name="5"></a><sup>5</sup> As noted in the brief filed with the Supreme Court by the SDO in the Veeck case, "Does the government's decision to make the copyrighted proposals binding place the copyrighted material in the public domain? The First Circuit said maybe. The Second and Ninth Circuits said no. And nine of fifteen Fifth Circuit judges said yes."</p> 
			<p><a name="6"></a><sup>6</sup> For a detailed examination of trademarks, certification and branding, see Updegrove, Andrew, <a href="/cb/">Certification Testing and Branding</a>, the Essential Guide to Standard Setting Organizations and Standard Setting, ConsortiumInfo.org, at &lt;http://www.consortiuminfo.org/cb/&gt;</p>
			<p><a name="7"></a><sup>7</sup> The question of what constitutes an "open standard" is at best an open question, upon which there are many opinions (and definitions).  For more on this topic, see the <a href="/bulletins/mar05.php#editorial">Editorial</a>, <a href="/bulletins/mar05.php#feature">Feature Article</a> and <a href="/bulletins/mar05.php#trends">Trends Article</a> in the March 2005 issue of the Consortium Standards Bulletin, titled <a href="/bulletins/mar05.php">What Does "Open" Mean?</a> (Vol. IV, No. 3), at &lt;http://www.consortiuminfo.org/bulletins/mar05.php&gt;.</p>
			<p><a name="8"></a><sup>8</sup> The author favors the former approach, in part because it makes the membership application less intimidating.  The application provides that the Board can unilaterally amend the policy as required over time, but also provides that no such amendment may be retroactive, and can only go into effect after at least 60 days notice has been given to the membership.  This allows any member that objects to the change to resign its membership.</p> 
			<p><a name="9"></a><sup>9</sup> For much more on creating an SSO technical process, and the rules required to operate it, see Updegrove, Andrew, <a href="/creating_an_sso_process/">Creating a Standard Setting Organization Technical Process (a Practical Primer)</a>, ConsortiumInfo.org, <a href="/essentialguide/">The Essential Guide to Standard Setting Organizations and Standards</a>, at &lt;http://www.consortiuminfo.org/creating_an_sso_process/&gt;</p>
			<p><a name="10"></a><sup>10</sup> Rambus was successful in some, but not all, of the suits in which it was involved largely as a result of convincing the finder of facts that the JEDEC IPR policy was vague and inconsistently described to JEDEC members.</p>
			<p><a name="11"></a><sup>11</sup> When asked to assist a new client in revising its IPR policies and procedures, the author has often found that members have been permitted to use whatever language they wished when disclosing patent claims that might be infringed by a standard, and in making licensing commitments.  Frequently, those commitments were so vague and brief as to be legally unenforceable, whether by accident or design.</p>
			<p><a name="12"></a><sup>12</sup> The text of this section has been adapted and updated from the oral and written testimony presented by the author before the Department of Justice and the Federal Trade Commission at hearings held on April 18, 2002 on the topics of consortia and standard setting, titled <a href="http://www.ftc.gov/opp/intellect/020418updegrove1.pdf">Is There a Need for Government Regulation of Standard Setting?</a>. The original text of that testimony may be found at &lt;http://www.ftc.gov/opp/intellect/020418updegrove1.pdf&gt;.</p>
			<p><a name="13"></a><sup>13</sup> While a typical IPR policy will require a member to make a binding commitment that it will license its essential claims on RAND terms if it is disposed to do so, it does not require a member to decide at that point in time that it definitively would <i>refuse</i> to do so.  Instead, the policy will phrase a negative choice in terms of reserving the right to withhold a RAND license.  The reason that a more definitive statement is not required is that, for all practical purposes, a "maybe" is as unhelpful as a "no."</p> 
			<p><a name="14"></a><sup>14</sup> This is the specific behavior in which Rambus was found to have engaged.</p>
			<p><a name="15"></a><sup>15</sup> This has been the public position of IBM, the owner of one of the largest patent portfolios in the world, for some years.</p>
			<p><a name="16"></a><sup>16</sup> At least two disputes have been in the courts this year, however, involving the application of a RAND commitment to specific licensing terms.  The first involves QUALCOMM Corporation, as licensor, and six mobile wireless technology companies, each of which has filed a complaint with the European Commission, alleging that Qualcomm is violating EU competition law and failing to meet the commitments it made to international standards bodies to license its technology on fair, reasonable and non- discriminatory terms.  See, <a href="http://www.broadcom.com/press/release.php?id=774809">Leading mobile wireless technology companies call on European Commission to investigate Qualcomm's anti-competitive conduct</a>, at &lt;http://www.broadcom.com/press/release.php?id=774809&gt;.  A second and similar suit was recently brought by Foundry Networks, Inc. against Alcatel, Inc., relating to an IEEE standard.  See, Updegrove, Andrew,<a href="/standardsblog/article.php?story=20060808090427739"> Foundry Networks Files "Son of Rambus" Suit Against Alcatel</a>, ConsortiumInfo.org, The Standards Blog, August 8, 2006, at &lt;http://www.consortiuminfo.org/standardsblog/article.php?story=20060808090427739&gt;.  This case was settled and dismissed last week under an order of dismissal that binds both parties to keep the terms of the settlement confidential.  No helpful guidance on the true meaning of RAND will therefore be forthcoming from this court, unfortunately.</p>
			<p><a name="17"></a><sup>17</sup> For further examples of problems with RAND usage, see Updegrove, Andrew, <a href="/bulletins/jun06.php#blog">Microsoft, Adobe and the Murky World of "RAND,"</a> ConsortiumInfo.org, The Standards Blog, June 7, 2006, at &lt;http://www.consortiuminfo.org/bulletins/jun06.php#blog&gt;.</p>
			<p><a name="18"></a><sup>18</sup> When this is later realized, such an organization often restructures itself, and adopts a more open model.  I have assisted in several such latter day conversions, all of which were followed by increased success for the SSOs involved.</p>
			<p><a name="19"></a><sup>19</sup> The review process for SSOs that develop American National Standards is described in Section 4.1.3 of the Essential Requirements, which  provides in part as follows:</p>
			<p>Whenever any revision is made to a standards developer's procedures on record at ANSI, the ExSC shall be notified and provided with a detailed description of the changes. If the changes are considered by the ExSC to be non&#8209;substantive, the standards developer will be notified and, upon such notification, may begin to operate under the revised procedures.  If the changes are considered by the ExSC to be substantive, notice of these changes shall appear in <i>Standards Action</i> with a call for comment. Copies of the revised procedures shall be made available by the applicant to any party, upon request.  If a developer submits their procedures in an electronic format and authorizes ANSI to post them on <i>ANSI Online</i> for purposes of public review, then the associated call for comment period in ANSI's <i>Standards Action </i>shall be 30 days and shall be announced as such.</p> 
			<p><a href="http://publicaa.ansi.org/sites/apdl/Documents/Standards%20Activities/American%20National%20Standards/Procedures,%20Guides,%20and%20Forms/Essential%20Requirements%20Jan3107.doc">Essential Requirements</a> (January 2007), Section 4.1.3, page 14.</p> 
			<p><a name="20"></a><sup>20</sup> For a much longer analysis of ex ante issues and recent events, see Updegrove, Andrew, <a href="/bulletins/jun06.php#feature">Ex Ante Disclosure: Risks, Rewards, Process and Alternatives, ConsortiumInfo.org, Consortium</a> Standards Bulletin, Vol. V, No. 6 (June 2006), at &lt;http://www.consortiuminfo.org/bulletins/jun06.php#feature&gt;, and sources cited therein, as well as the other articles in the same issue.</p>
			<p><a name="21"></a><sup>21</sup> Section 2 of the W3C Patent Policy now provides as follows:</p>
			<p>In order to promote the widest adoption of Web standards, W3C seeks to issue Recommendations that can be implemented on a <a href="http://www.w3.org/Consortium/#def-RF">Royalty-Free</a> (RF) basis. Subject to the conditions of this policy, W3C will not approve a Recommendation if it is aware that <a href="http://www.w3.org/Consortium/#def-essential">Essential Claims</a> exist which are not available on Royalty-Free terms.<sup>21</sup></p> 
			<p>W3C Patent Policy 20 May 2003, at <a href="http://www.w3.org/Consortium/Patent-Policy-20030520.html">http://www.w3.org/Consortium/Patent-Policy-20030520.html</a>. The current policy, incorporating minor changes, was adopted with insubstantial amendments on February 5, 2004, and can be found at &lt;http://www.w3.org/Consortium/Patent-Policy-20040205/&gt;.</p> 
			<p><a name="22"></a><sup>22</sup> OASIS Intellectual Property Rights (IPR) Policy, adopted April 15, 2005, at &lt;http://www.oasis-open.org/who/intellectualproperty.php&gt;.</p> 
			<p><a name="23"></a><sup>23</sup> For more on the efforts to reconcile the needs of the open source and open standards communities, see the following prior issues of the Consortium Standards Bulletin:  <a href="/bulletins/may06.php">Bridging the Open Source- Open Standards Divide</a>, Vol. V, No. 5 (May 2006), at &lt;http://www.consortiuminfo.org/bulletins/may06.php&gt; and What Does "Open" Mean?,  Vol. IV, No. 3 (March 2005), at &lt;http://www.consortiuminfo.org/bulletins/mar05.php&gt;.</p> 
			<p><a name="24"></a><sup>24</sup> In exchange for its troubles, open source advocates led by Larry Rosen issued a call to <a href="http://perens.com/Articles/OASIS.html">boycott OASIS standards</a>, because OASIS had not converted its entire IPR policy to the open-source friendly rule set.  This Call to Action may be viewed at <a href="http://perens.com/Articles/OASIS.html">http://perens.com/Articles/OASIS.html</a>.  While much in the news in 2005, this issue seems to have inexplicably faded from view more recently.  Presumably, this is a temporary lull rather than a permanent truce, given that real issues underlying these concerns remain to be resolved.</p>
			<p><a name="25"></a><sup>25</sup> See the following ITU press release: <a href="http://www.itu.int/newsroom/press_releases/2007/05.html">IEC, ISO and ITU, the world's leading developers of international standards agree on common patent policy</a>, at &lt;http://www.itu.int/newsroom/press_releases/2007/05.html&gt;. The press release describes the action taken as follows:</p>
			<p>The world's leading international standards organizations have adopted a harmonized approach to address the inclusion of patented technology in standards. IEC (International Electrotechnical Commission), ISO (International Organization for Standardization) and ITU, under the banner of the World Standards Cooperation (WSC), have aligned their policies which allow for commercial entities to contribute the fruits of their research and development (R&amp;D) activity safe in the knowledge that their intellectual property rights are respected.</p>
			<table class="GuideHelp">
				<tr>
					<td style="padding:12px;" valign="top"><a href="http://www.gesmer.com/attorneys/updegrove.php"><img src="images/guide_updegrove.jpg" width="69" height="106" border="0" alt="" /></a></td>
					<td valign="top">
						<p class="GuideHelpHead">Can We Help You?</p>
						<p class="GuideHelpBody1"><a href="http://www.gesmer.com/">Gesmer Updegrove LLP</a> is, quite simply, the most experienced law firm in the United States when it comes to representing and creating standards development organizations &mdash; <a href="http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST">more than 100</a> &mdash; to date.  If you need advice about participating in the standards development process, representation in standards-related litigation, intellectual property advice, or help creating a brand new SSO or open source foundation, we'd be pleased to help. Contact:</p>
						<p class="GuideHelpBody2">Email: <script language="javascript" type="text/javascript">AuGesAdd();</script><br />Tel: 617-350-6800</p>
					</td>
				</tr>
			</table>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
		</div>
	</div>
<div class="clear"><br /></div>
<!-- *********** -->
<!--   FOOTER    -->
<!-- *********** -->
<?php include '../includes/footer.php'; ?>
</form>
</body>
</html>