<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>The Essential Guide to Consortia and Standards</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta name="description" content="While standard setting has been an important aspect of industrial society for over a hundred years, the formation of unofficial, fast-acting standard setting and promotional consortia is a more recent phenomenon which is only now beginning to be seriously studied" />
<meta name="keywords" content="standard setting, promotional consortia, structuring of consortia, standardize, intellectual property policies, procedures, founding company, model, best practices, promoter/adopter structurer, joint venture, IPR, " />
<meta name="author" content="Andrew Updegrove" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/screen.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/guide.css" />
<link rel="stylesheet" type="text/css" media="screen, projection" href="/consortiuminfo2017/css/toolsets.css" />
<!-- ALTERNATE -->
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/default.css" title="default" />
<link rel="alternate stylesheet" type="text/css" href="/consortiuminfo2017/css/large.css" title="large" />
<!-- ********* -->
<link rel="home" title="home" href="http://www.consortiuminfo.org" />
<script type="text/javascript">AC_FL_RunContent = 0;</script>
<script type="text/javascript" src="/scripts/AC_RunActiveContent.js"></script>
<script type="text/javascript" src="/scripts/styleswitcher.js"></script>
<script type="text/javascript" src="/scripts/obfuscate.js"></script>
</head>

<body id="bulletin">
	<!-- ****************** -->
	<!--   ACCESSIBILITY    -->
	<!-- ****************** -->
	<?php include '../includes/accessibility.php'; ?>
	
	<!--   SEARCH FORM   -->
	<form class="search" name="form1" method="get" action="http://search.Blossom.com/query/320">
	
	<!-- ************* -->
	<!--   MASTHEAD    -->
	<!-- ************* -->
	<?php include '../includes/masthead_subs.php'; ?>
	
	<!-- *********** -->
	<!--   BANNER    -->
	<!-- *********** -->
	<div id="banner">
		<div class="left">
			<p><a href="/">Home</a> &gt; <a href="/essentialguide/">Guide</a> &gt; Laws, Cases and Regulations</p>
		</div>
		<div class="right">
			<p><input type="text" name="key" /><input type="submit" name="Submit" value="Search" /> <a href="/search/">Advanced</a></p>
		</div>
		<div class="clear"></div>
	</div>
						
	<!-- ************** -->
	<!--   MAIN BODY    -->
	<!-- ************** -->
	<div class="GuideContent">
	<!-- SKIP/START CONTENT LINK -->
	<a name="startcontent" id="startcontent"></a>
		
		<!-- SIDEBAR CONTENT AREA -->
		<div class="AllSidebar">
			<div>
				<?php include '../includes/clients.php'; ?>			
			</div>
			<div class="AllNav">
				<p class="AllNavTitle">Chapter 10:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section1" title="Introduction to Antitrust Law">I &ndash; Introduction to Antitrust Law</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section2" title="Antitrust Laws Enacted and Enforced in the United States">II &ndash; Antitrust Laws Enacted and Enforced in the United States</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section3" title="Regulations and Guidelines">III &ndash; Regulations and Guidelines</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section4" title="Agencies">IV &ndash; Agencies</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section5" title="Antitrust Cases">V &ndash; Antitrust Cases</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section6" title="Articles and Essays">VI &ndash; Articles and Essays</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="#section7" title="Other Resources">VII &ndash; Other Resources</a></p>
				<p class="AllNavTitle" style="padding-top:10px">The Essential Guide to Standards:</p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part1" title="Participating In An SSO">Participating In An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part2" title="Forming And Managing An SSO">Forming And Managing An SSO</a></p>
				<p class="AllNavLink">&raquo;&nbsp;<a href="/essentialguide/index.php#part3" title="Law and Policy">Law and Policy</a></p>
			</div>
			<?php include '../includes/toolsets.php'; ?>
		</div>
		
		<!-- BODY CONTENT AREA -->
		<div class="GuideMain">
			<h1>The Essential Guide to Standards</h1>
			<p>The Essential Guide is a book-length handbook for anyone who wants to understand standards and standards development from a hands-on perspective. If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <script language="javascript" type="text/javascript">AuGesAdd();</script> if you have questions about this topic.</p>
			<div class="hr"></div><hr />
			
			<h2>Chapter 10: Laws, Cases and Regulations</h2>
			<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
			<blockquote><em><strong>Summary:</strong> The development and implementation of standards conveys great societal benefits when properly conducted, but can also provide the means by which powerful vendors, or alliances of vendors, can take advantage of the standards development infrastructure to further their own commercial interests at the expense of others. As a result, governments have created laws and regulations in order to both encourage as well as regulate standards related activities. Over time, courts have applied these laws and regulations to specific disputes, resulting in a growing body of case law that can be consulted for additional guidance. It is important for in-house and outside counsel advising those that participate in standards development and deployment to understand the resulting rules of conduct that arises from this case law. This article reviews the principal United States laws, regulations and cases that are relevant to standard setting, and provides links to the full text of these materials wherever possible. This article is part of the ConsortiumInfo.org <a href="/essentialguide/">Essential Guide to Standards</a>, which can be found at <a href="/essentialguide/">http://www.consortiuminfo.org/essentialguide/</a>. In particular, you may wish to read the preceding article, titled <a href="government.php">Government Issues and Policy</a>.</em></blockquote>
			<a name="section1"></a><h3>I &ndash; Introduction to Antitrust Law</h3>
			<p>Adhering to United States, state and international antitrust laws is a necessary concern for consortia and other standards developing organizations ("SDOs"). Antitrust risk is inherent in the very concept of a consortium or SDO. Because these organizations are almost always formed by competitive (or potentially competitive) business entities, the risk of improper collusion is never far away. The potential for a problem is made greater by the fact that the antitrust laws are general in nature (violation often being a matter of court interpretation), and therefore it may not be obvious to participants with innocent intent that they have "crossed the line" into areas of potential liability.</p>
			<p>Fortunately, most consortia begin their journey with a strong tailwind in the United States of governmental approval. Congress and the courts have acknowledged that standard setting, even among otherwise bitter competitors, is fundamentally pro-competitive. As the Fifth Circuit Court of Appeals stated in <a href="#512"><em>Consolidated Metal Products v. American Petroleum Institute</em> in 1988</a>:</p>
			<blockquote>A trade association by its nature involves collective action by competitors. Nonetheless, a trade association is not by its nature a "walking conspiracy", its every denial of some benefit amounting to an unreasonable restraint of trade. In particular, it has long been recognized that the establishment and monitoring of trade standards is a legitimate and beneficial function of trade associations.</blockquote>
			<p>Despite this protective (and almost presumptive) patina of protection, SDOs and standards setting consortia have the potential at all times to cross the line and attract either a government or a private suit. Organizations engaged in consortium and standards development activities must understand antitrust law basics, and understand how the courts and antitrust enforcement agencies apply these laws, since the consequences of failing to do so can be nothing less than catastrophic for consortia, their member companies and even individuals.</p>
			<p>In the sections below, we provide a brief introduction to the major components of U.S. antitrust law. However, the reader must be warned that this area of law is fast evolving and complex. Hence, the operation of a consortium requires careful monitoring and counsel.</p>
			<p><strong>1.1 &mdash; Overview of US Antitrust Laws.</strong> The courts are fond of describing the antitrust laws broadly, in almost constitutional terms. The courts state (to paraphrase) that the objective of the US antitrust laws is to preserve and promote competition and the free enterprise system. Of course this, by itself, tells almost nothing to someone seeking to learn how to comply with the laws. In fact, the only way to gain a useful understanding of the antitrust laws is to examine the cases where the courts, over the past century (and more) have determined on a case-by-case basis what conduct does or does not pass muster under these laws.</p>
			<p>The problem that consortia are most likely to face is the appearance or reality of improper collusion. At their core, the courts interpret the antitrust laws to presume that competition (a good thing) is best encouraged if buyers and sellers (and in more recent times licensors and licensees) make business decisions independent of each other. If decisions are made by competitors working together, whether they agree on prices, divide and allocate markets, restrict product features, set conditions of sale, or arbitrarily agree who is "in" and who is "out" of a standards organization (all bad things), the purchasing public will be presumed to suffer in consequence. Its suffering will result from higher prices and fewer choices.</p>
			<p><strong>1.2 &mdash; Enforcement of the Antitrust Laws.</strong> Interest in enforcing the federal antitrust laws (which is, by far, where most of the official action lies, since the states rarely have sufficient resources to prosecute cases of this nature) is so high that not one, but two, agencies have been assigned responsibility for sharing the duties. Both the Antitrust Division of the Department of Justice (the "Antitrust Division") and the Bureau of Competition of the Federal Trade Commission (the "FTC") are armed and ready to challenge mergers, prosecute price fixers, and set economic antitrust policy.</p>
			<p>It is important to note that federal enforcement actions against consortia and their members have been extremely rare. This is a tribute to the legal motives and careful self-monitoring of most consortia. Nevertheless, when an enforcement action arrives it comes with potentially great impact. The Antitrust Division and the FTC (together sometimes referred to below as the "Agencies") may impose both civil and criminal penalties. Criminal convictions may result in stiff fines for consortia and their members, jail sentences for individuals who participate in such violations (including individuals who participate solely in their capacities as corporate employees or officers) and court orders disbanding or severely limiting the activities of consortia. Therefore, while the risk is small (at least historically), the consequences of a violation are great, and therefore exercising caution is vital.</p>
			<p>Antitrust violations also expose consortia and other SDOs to civil suit. Under federal law, private persons or firms may sue for damages due to antitrust law violations. Moreover, companies found liable for such violations may be required to pay up to three times the actual damages suffered by the plaintiff, as well as all of the plaintiff's litigation costs and attorneys' fees. Finally, while it is relatively rare, U.S. State Attorneys General may bring both state and federal court actions.</p>
			<p><strong>1.3 &mdash; National Cooperative Research and Production Act of 1993.</strong> Fortunately, the founders of consortia may sometimes take advantage of a statutory "safe harbor" created by Congress to encourage some types of innovative research and production activities. The full name of the legislation which created this safe harbor is the National Cooperative Research and Production Act of 1993, or "NCRPA", for short. In enacting the NCRPA, Congress attempted to strike a balance between deterrence of anticompetitive business practices and the recognition that consortia and other joint research and development ventures often serve important roles in the business community. Thus, the NCRPA clarifies how antitrust laws apply to joint ventures, such as consortia, and encourages joint research and development by providing some protection to participants in these activities. As noted above, participants in a joint venture found to be in violation of the United States federal antitrust laws can be assessed triple damages. A consortium can seek some protection from this harsh remedy by filing a notification with the U.S. Department of Justice that it wishes to register under the NCRPA. Consortia that make the appropriate filings with the DOJ, and meet certain other criteria, will have any damages awarded against them in an antitrust suit limited to actual damages. For this reason, many U.S.-based consortia opt to make such NCRPA compliance filings. Notwithstanding the above, however, consortia and other SDOs should not let the protection they may be entitled to if they violate the antitrust laws but are in compliance with the NCRPA lull them into a false sense of security with respect to the antitrust laws generally. Even without treble damages, penalties for such violations can be stiff.</p>
			<p><strong>1.4 &mdash; Federal Guidelines.</strong> Since the antitrust statutes themselves are insufficient detailed to properly instruct businesses in how to conduct their affairs, the Antitrust Division and the FTC have published extensive guidelines on how to comply with the federal antitrust laws. Among these are several that are particularly relevant to consortia. The guidelines for collaborations among competitors for horizontal mergers and acquisitions, and for non-horizontal (or "vertical") mergers are important. When taken together, these guidelines provide significant guidance as to how the Agencies are likely to approach a variety of antitrust issues, which are relevant to consortia as well, since the practical effect of some consortium activities can potentially replicate the impact of a merger. The guidelines also provide insight into the analytical processes utilized by the Agencies in determining whether to undertake an antitrust challenge. Factors central to the different analyses throughout the guidelines include pre-collaboration/merger market power (i.e. how great a percentage of a given market the goods or services of the involved companies comprise), the impact of a given collaboration/merger on the market and subsequent market entry by other market participants, as compared to any efficiencies which must be gained as a result of the collaboration/merger.</p>
			<p><strong>1.5 &mdash; "Per Se Illegality" and the "Rule of Reason."</strong> The courts divide antitrust violations into two broad categories: those that are per se illegal, and those judged by the "rule of reason" test, which examines the anticompetitive effect of a practice to determine legality or illegality.</p>
			<p>Conduct that is illegal per se, as the name suggests, in considered to be illegal regardless of any justification offered by the participants. No matter how laudatory the purpose or innocent the intent, certain activities are presumed to be so intrinsically pernicious that they are placed in a separate regulatory class. These practices include agreements to fix prices, agreements to boycott competitors, suppliers or customers, agreements to allocate markets or limit production and, under certain circumstances, "tying" arrangements, i.e., where a seller will only sell you Product A (which you want) if you also agree to buy Product B (in which you have no interest).</p>
			<p>In the case of all other violations, the courts are required to examine all of the facts and circumstances involved, and determine whether the conduct's harmful effects are justified by its business justifications. In the language of the antitrust laws, this is spoken of as applying a "rule of reason" analysis.</p>
			<p>Consortia and other SDOs confront special problems in fitting under one of these two umbrellas. While they want their activities to be judged under the rule of reason test (if they must be judged at all), they are often forced, by their very nature, to engage in activities which potentially approach the unfriendly domain of per se illegality.</p>
			<p><strong>1.6 &mdash; Some Situations Where the Courts Have Found Liability.</strong> It goes almost without saying that if a consortium which is used as a vehicle for price fixing or the overt exclusion of a competitor (via a boycott), the members face the potential for strict antitrust penalties. However, these situations are extremely rare. When discovered, they have great potential to attract government prosecution as well as treble damage civil suits.</p>
			<p>The more interesting (and for consortium members more important) cases involve conduct that is not intentionally harmful, but is perceived to have a negative competitive impact. For example, the standard-setting process is subject to abuse when a group of industry participants with a common interest agree on a product standard that excludes a new technology. An example of this problem is illustrated by the Supreme Court case of <a href="#ahic"><em>Allied Tube &amp; Conduit Corp. v. Indian Head, Inc</em>., 486 U.S. 492 (1988)</a>, where the plaintiff successfully claimed that the members of a standards-setting trade association conspired to defeat adoption of the plaintiff's new technology. The plaintiff's case arose when certain members of the National Fire Protection Association (who were also long time members of the steel industry) improperly "packed" an Association meeting with steel industry sympathizers and voted down the plaintiff's proposal to include plastic as an approved material for making electrical conduit under the National Electrical Code. Until that time, the code permitted only the use of steel conduit. Holding in favor of the plaintiff, and finding that standard-setting procedures should be based on objective criteria judged through fair procedures, this case (and cases of a similar nature) reminds consortia not only that standard-setting rules must be set in a fair manner, but that the courts will look behind the rules, to ensure that the members are not unfairly skewing the process.</p>
			<p>Consortia can also stumble into boycott-like situations, even when the refusal to deal is not directed at a competitor. A good example of this problem appears in another Supreme Court case, <a href="http://caselaw.lp.findlaw.com/scripts/getcase.pl?navby=case&amp;court=us&amp;vol=476&amp;page=447"><em>F.T.C. v. Indiana Federation of Dentists, </em>476 U.S. 447 (1986)</a>. In that case, a trade association comprised of dentists collectively passed a rule under which each member was required to agree that he or she would withhold patient x-rays from insurance companies. This was not a boycott in the traditional sense (the conduct was not intended to exclude a competitor), and therefore the Supreme Court evaluated it under the rule of reason test, rather than as a per se violation. Nevertheless, after examining the Federation's market power, the common interests of its members, and the mandatory (as opposed to voluntary) nature of the Federation rule, the Court found that the Federation of dentists had violated the antitrust laws.</p>
			<p>Another major area of antitrust concern arises in the context of intellectual property rights, or "IPR", policies. These policies <a href="/ipr/">discussed extensively elsewhere on this site</a> establish the terms under which members will contribute their technology to, or may withhold it from inclusion in a consortium's technology standards.</p>
			<p>A problem most often arises under IPR policies in connection with so-called "submarine patents", when a consortium member contributes its technology, or votes to accept another member's submission of technology, but fails to advise that it has a pending patent. Later, when the submarine patent issues, the patent holder seeks payment for the use of its technology. This issue arose in a relatively recent FTC action culminating in a settlement agreement with Dell Computer. <a href="#dell"><em>Dell Computers, Inc., </em>Dkt. C-3658 (consent order, May 20, 1996)</a>. This case received wide attention in the press and sharply focused the attention of many companies, for the first time, on consortium IPR policies. The FTC began its investigation when Dell attempted to enforce a patent relating to "VL-bus" technology and centered upon whether the patent was enforceable in light of the fact that, contrary to VESA's IPR policy, a Dell representative had failed to disclose the patent to the Video Electronics Standards Association ("VESA") during the VL-bus standard development process. The defendant brought numerous counterclaims and Dell ultimately settled. As part of the consent decree whose issuance ended the FTC's investigation, Dell agreed that the patents at issue were unenforceable because they were not disclosed to VESA.</p>
			<p>More recently, IPR policies have been relevant in the context of patent ownership disclosures by <a href="#rambus1"><em>Rambus, Inc.</em></a> and <a href="images/sun.pdf"><em>Sun Microsystems, Inc.</em></a> The Rambus case arose when Rambus was a member of the Joint Electron Devices Engineering Council ("JEDEC"). In litigation arising from participation in the JEDEC standards-development process, it was alleged that Rambus failed to disclose certain patent applications relating to SDRAM that were pending during its JEDEC membership and while JEDEC was developing an industry standard for SDRAM. Disclosure of the relevant IPR was required of all members under the JEDEC IPR policy. Prior to the adoption of the standard, Rambus resigned its JEDEC membership and thereafter successfully extracted license fees from several manufacturers who implemented the SDRAM standard. When Rambus sued Infineon for infringement of the submarine SDRAM patents, however, the court found against Rambus and held that Rambus had committed fraud with respect to its failure to disclose its IPR, as required under JEDEC policy. The FTC's investigation of Rambus is ongoing and Rambus has now been accused of fraud in federal courts in both Delaware and Virginia as a result of its conduct.</p>
			<p>On January 26, 2003, two out three judges sitting on a panel of the United States Court of Appeals of the Federal Circuit -- which has jurisdiction over all appeals from US patent cases -- vacated the lower court's finding of fraud in Infineon v. Rambus, to the surprise and consternation of many. (See <em><a href="#rambus2">Rambus, Inc. v. Infineon Technologies AG</a>, et al</em>., 318 F.3d 1081 (Fed. Cir. January 29, 2003).)</p>
			<p>The Sun Microsystems controversy arose under similar circumstances involving submarine patents after Sun participated in a JEDEC panel that drafted a dual inline memory module (DIMM) interface standard for a 64-bit memory bus line. Although JEDEC policy required Sun to disclose all relevant IPR as a participant in the standards-development process, Sun did not disclose certain related patents and a pending patent application, then sued Kingston Technologies Co. (one of several memory module manufacturers that licensed various Sun patents under royalty arrangements, including the patents in question, from Sun) for patent infringement and royalties. As in Rambus, the alleged infringer counterclaimed that the patent holder's conduct constituted an illegal restraint of trade, and the FTC thereafter launched a probe into Sun's behavior as a potential violation of Section 5 of the Federal Trade Commission Act. Sun settled the Kingston case in February of 2001, dropping the infringement suit and royalty demands, disavowing the patents in question, abandoning its sole pending patent application which claimed priority to the disavowed patents and waiving royalties that Kingston had been paying to Sun for unrelated patents covering Sun's Sparcstation workstations and servers. Whether or not the settlement and related disclaimers were actually intended to defuse the FTC's burgeoning investigation, it appears to have had precisely that effect. The FTC, formally closed its inquiry in November, 2001, stating that, "notwithstanding the fact that the Commission had serious questions about the propriety of [Sun's] conduct", Sun's settlement actions led the FTC to conclude that the inquiry was "no longer in the public interest."</p>
			<p>As a clear word of caution to standards-development participants who might find some level of comfort in Sun's apparent success at averting an FTC antitrust investigation by disclaiming submarine patents, however, the Commission concluded its closing letter by stating that "the Commission emphasizes that continued investigation and prosecution may well be warranted in future cases in which potentially anticompetitive conduct is discontinued and corrective action taken during the pendency of a Commission investigation."</p>
			<p><strong>1.7 &mdash; Conclusion.</strong> In the business world, the antitrust laws are too often forgotten, misunderstood or not understood at all. A tutorial on the basics do's and don't of antitrust compliance is essential for every consortium or SDO. In some cases, where the risks of inadvertent violation are deemed to be particularly high, constant antitrust monitoring by legal counsel is a necessity.</p>
			<p>That having been said, the following sources provide additional information for those who wish to develop a deeper understanding of the antitrust laws, the government agencies that enforce the those laws, and the administrative guidance and case law available to assist consortia and other SDOs in operating within the constraints of the antitrust laws.</p>
			<a name="section2"></a><h3>II &ndash; Antitrust Laws Enacted and Enforced in the United States</h3>
			<p>Since first promulgated by Congress in 1890, the Sherman Antitrust Act has been the centerpiece of US antitrust law enforcement. Although various other federal statutes, such as the Clayton Act, the Federal Trade Commission Act and the Robinson-Patman Antidiscrimination Act have been enacted since that time, the Sherman Act continues to provide the basis for the vast majority of antitrust challenges in the US today. For brief annotations of the most important antitrust statutes and links to the full text of each, please follow the links below:</p>
			<p><strong>2.1 &mdash; </strong><a href="/antitrust/sherman.php">Sherman Antitrust Act of 1890.</a></p>
			<p><strong>2.2 &mdash; </strong><a href="/antitrust/clayton.php">Clayton Act of 1914.</a></p>
			<p><strong>2.3 &mdash; </strong><a href="/antitrust/rob-pat.php">Robinson-Patman Antidiscrimination Act of 1936</a>.</p>
			<p><strong>2.4 &mdash; </strong><a href="/antitrust/celler.php">Celler-Kefauver Antimerger Act</a>.</p>
			<p><strong>2.5 &mdash; </strong><a href="/antitrust/ftc.php">Federal Trade Commission Act of 1914</a>.</p>
			<p><strong>2.6 &mdash; </strong><a href="/antitrust/wilson.php">Wilson Tariff Act</a>.</p>
			<p><strong>2.7 &mdash; </strong><a href="/antitrust/ncrpa.php">National Cooperative Research and Production Act of 1993</a>.</p>
			<p><strong>2.8 &mdash; </strong>For other Statutes affecting antitrust prosecutions <a href="http://www.usdoj.gov/atr/foia/divisionmanual/ch2.htm">click here</a> and scroll down to "B. Statutes Affecting Antitrust Prosecutions."</p>
			<a name="section3"></a><h3>III &ndash; Regulations and Guidelines</h3>
			<p>To review antitrust regulations and guidelines, please follow the links below.</p>
			<p><strong>3.1 &mdash; </strong><a href="http://www.ftc.gov/os/2000/04/ftcdojguidelines.pdf">Antitrust Guidelines for Collaborations Among Competitors.</a> This set of guidelines was issued in April of 2000. They explain how the Agencies analyze various antitrust issues that arise when business competitors collaborate and address issues that arise within the context of horizontal mergers and acquisitions, including joint ventures and strategic alliances. Additionally, they provide an analytical framework to assist businesses in assessing the risk that they may become subject to an antitrust challenge due to their collaboration with competitive businesses.</p>
			<p><strong>3.2 &mdash; </strong><a href="http://www.usdoj.gov/atr/public/guidelines/horiz_book/toc.html">Horizontal Merger Guidelines.</a> These guidelines were first issued in April of 1992 and revised in April of 1997. They outline the Agencies' then-current enforcement policies and analytical framework with respect to horizontal acquisitions and mergers subject to provisions of the Sherman Act, Clayton Act and FTC Act. Ultimately oriented toward determining whether a particular merger is likely to create or enhance market power or to facilitate its exercise, the analytical process set forth in these guidelines focuses on an assessment of the following factors: 1) market concentration following the merger, 2) potential adverse competitive effects of the merger, 3) whether market entry by the merged entities might significantly impact the ability of others to enter the market, 4) efficiencies to be gained through the merger and 5) the likelihood of failure of either merger party in the absence of the merger.</p>
			<p><strong>3.3 &mdash; </strong><a href="http://www.usdoj.gov/atr/public/guidelines/2614.htm">Non-Horizontal Merger Guidelines</a>. The Non-Horizontal Merger Guidelines were originally issued by the Antitrust Division as Section 4 of the "U.S. Department of Justice Merger Guidelines" in June of 1984. These guidelines describe the primary theories upon which the Antitrust Division is likely to challenge non-horizontal mergers as well as the central factors considered by the Division in deciding whether to undertake an antitrust challenge. Factors included in the Division's discussion are pre-merger market concentration, conditions of entry, entry advantages and market share, as well as efficiencies likely to manifest themselves due to the merger.</p>
			<p><strong>3.4 &mdash; </strong><a href="http://public.ansi.org/ansionline/Documents/Standards%20Activities/American%20National%20Standards/Procedures,%20Guides,%20and%20Forms/PATPOL.DOC">Guidelines for Implementation of the ANSI Patent Policy: An Aid to More Efficient and Effective Standards Development In Fields That May Involve Patented Technology.</a> While ANSI is not a governmental entity, it has perhaps the oldest comprehensive IPR policy, and this policy has been an influential in the adoption of policies by many other consortia. The ANSI Guidelines are intended to assist voluntary standards developers, and those that participate in the standards development process, in understanding and implementing the ANSI Patent Policy. Drafted by a task force formed by ANSI for the purpose of studying the Patent Policy, ANSI states that these Guidelines seek to encourage the early disclosure and identification of patents that may relate to standards under development in order to promote greater efficiency in standards development.</p>
			<p><strong>3.5 &mdash; </strong><a href="http://www.ftc.gov/bc/compguide">FTC Antitrust Law Primer.</a> The FTC has prepared an eight section online "booklet" to assist readers in developing an understanding of the antitrust laws. The booklet is intended to help readers understand how the antitrust laws benefit consumers, how the antitrust laws affect business operators, and what will and will not violate the antitrust laws. The booklet also answers frequently asked antitrust questions and describes how markets can be kept competitive. Connect to the booklet by clicking any of the eight links below.</p>
			<ul>
				<li><a href="http://www.ftc.gov/bc/compguide/preface.htm">Preface</a><br /><br /></li>
				<li><a href="http://www.ftc.gov/bc/compguide/antitrst.htm">An Antitrust Primer</a><br /><br /></li>
				<li><a href="http://www.ftc.gov/bc/compguide/illegal.htm">Illegal Business Practices</a><br /><br /></li>
				<li><a href="http://www.ftc.gov/bc/compguide/maintain.htm">Maintaining or Creating a Monopoly</a><br /><br /></li>
				<li><a href="http://www.ftc.gov/bc/compguide/mergers.htm">Mergers</a><br /><br /></li>
				<li><a href="http://www.ftc.gov/bc/compguide/discrim.htm">Price Discrimination</a><br /><br /></li>
				<li><a href="http://www.ftc.gov/bc/compguide/question.htm">Federal Trade Commission Frequently Asked Questions</a><br /><br /></li>
				<li><a href="http://www.ftc.gov/bc/compguide/keep.htm">Keeping Markets Competitive</a></li>
			</ul>
			<a name="section4"></a><h3>IV &ndash; Agencies</h3>
			<p>To visit the websites of the various US antitrust law enforcement agencies, please follow the links below.</p>
			<p><strong>4.1 &mdash; </strong><a href="http://www.usdoj.gov/atr/">Antitrust Division of the Department of Justice.</a> The Antitrust Division of the U.S. Department of Justice shares responsibility for enforcing the US antitrust laws and regulations with the Bureau of Competition of the Federal Trade Commission. The Antitrust division states its mission to be the promotion and protection of the competitive business process and the American economy through antitrust law enforcement. The Division prosecutes violations of the antitrust laws in virtually all industries and levels of business, including manufacturing, transportation, distribution and marketing by bringing criminal suits or leading civil suits against offenders.</p>
			<p><strong>4.2 &mdash; </strong><a href="http://www.ftc.gov/">Federal Trade Commission.</a> The Bureau of Competition of the Federal Trade Commission shares responsibility for enforcing the US antitrust laws and regulations with the Antitrust Division of the U.S. Department of Justice. The Bureau is a consumer protection agency mandated by the FTC Act to protect the marketplace from unfair methods of competition, and to prevent unfair or deceptive acts or practices that harm consumers. The Bureau has authority to file cases in both federal court and special administrative forums.</p>
			<p><strong>4.3 &mdash; </strong><a href="http://www.usdoj.gov/atr/cases.html">Current Antitrust Case Filings with the Department of Justice.</a> This web page contains electronic versions of selected documents filed by the Antitrust Division since December, 1994. Cases are listed alphabetically by the last name of individual defendants, by company name, or by the entity's first name. Amicus Curiae briefs are listed by Plantiff's name. The web page also contains links to appellate briefs and other Antitrust Division web pages.</p>
			<a name="section5"></a><h3>V &ndash; Antitrust Cases</h3>
			<p>As mentioned above, federal enforcement actions against consortia and their members have been extremely rare, and therefore the case law addressing consortia and other SDOs within the antitrust context is sparse. Nonetheless, several important decisions and consent decrees within the past two decades have begun to set the parameters for safe (as in, not violative of the antitrust laws) standard setting activities. Summaries of these seminal cases, along with links to the actual decisions or consent decrees, as the case may be, follow below:</p>
			<p><a name="dell"></a><strong>5.1 &mdash; </strong><a href="http://cyber.law.harvard.edu/seminar/internet-client/readings/week10/ftc_complete.doc"> <em>In re Dell Computer Corp.</em>, 121 F.T.C. 616, FTC LEXIS 291 (May 20 1996).</a> This matter arose in connection with the standard development process for the "VL-bus", a mechanism that transfers instructions between a computer's central processing unit and its peripheral devices. Dell and certain other computer manufacturers were members of the Video Electronics Standards Association ("VESA"), a standards-setting consortium creating a standard for the VL-bus. During the standard development process, although Dell had applied for a patent (the "'481 patent") that would be infringed by those who implemented the VL-bus standard, Dell maintained in writing through one of its representatives that it had no intellectual property rights that would be infringed by implementation of the subject standard. After the standard was approved, Dell sought to enforce its '481 patent rights against various VL-bus manufacturers who had implemented the standard the standard was approvedand allegedly had infringed the patent.</p>
			<p>In settlement of alleged violations of federal law prohibiting unfair or deceptive acts or practices and unfair methods of competition, Dell agreed to a consent decree issued by the FTC prohibiting Dell from undertaking to enforce the '481 patent against manufacturers who had already implemented the VL-bus standard or against those who manufacture, use or sell computer equipment that incorporates the VL-bus standard in the future. It also agreed that, for a period of ten years, it would not attempt to enforce any patent right required to use or implement an industry standard if it had intentionally failed to disclose such right during the relevant standard setting process. Finally, Dell agreed to report to the FTC for a period of ten years regarding its compliance with the consent decree.</p>
			<p>The Dell case was something of a thunderbolt to the standards setting community because Dell as a company had been held responsible for the representations of a single individual. Until the consent decree was issued, many companies had taken a very casual attitude towards the rules of standard setting bodies, even though the policies of some consortia did in fact purport to hold companies to the representations of their representatives.</p>
			<p>The Dell consent decree has attracted notice also because its holding is somewhat murky as to whether the FTC actually believed that Dell had deliberately "gamed" the system, or had merely failed to take the VESA IPR policy seriously.</p>
			<p><strong>5.2 &mdash; </strong><a href="/antitrust/stdi.php"> <em>Stambler v. Diebold, Inc.,</em> 11 U.S.P.Q.2d (BNA) 1709 (E.D.N.Y. 1988), aff'd, 11 U.S.P.Q.2d 1709 (Fed. Cir. 1988).</a> This claim arose when Stambler, a patent owner, attempted to enforce his patent covering the use of personal identification numbers in activating automatic bank teller machines. Ten years prior to filing suit, after Stambler had obtained the patent, Stambler had been a member of an ANSI committee, working towards the development of standards in this area. At that time, however, Stambler failed to notify ANSI of his patent rights and left the committee, despite the fact that he apparently knew that implementation of the standards proposed by the committee would infringe his patent.</p>
			<p>Relying on the doctrine of legal estoppel, the court held that Stambler had a duty to disclose the patent and, failing that duty by remaining silent, could not later assert the patent rights in question. Such silence, the court determined, reasonably could be interpreted as indicating Stambler's abandonment of any associated patent enforcement rights. Poignantly, the court commented that Stambler "could not remain silent while an entire industry implemented the proposed standard and then, when the standards were adopted, assert that his patent covered what manufactures believed to be an open and available standard."</p>
			<p><strong>5.3 &mdash; </strong><a href="/antitrust/toro.php"><em>Townshend v. Rockwell Int'l Corp.</em>, 55 U.S.P.Q.2D (BNA) 1011; 2000-1 Trade Cas. (CCH) 72,890 (N.D. Cal. March 28, 2000).</a> This case arose when plaintiff sued defendant for infringement of its patent relating to 56k modem technology. Prior to suit, the International Telecommunications Union ("ITU"), of which both parties were members, had considered and adopted a standard for 56k modem technology, which necessarily included use of plaintiff's patented technology. In accordance with ITU policy, during the standard approval process plaintiff notified the ITU of its patent rights and expressed a willingness to license its technology to users who wished to implement the standard on reasonable terms. Prior to adoption of the standard, plaintiff submitted its proposed license terms to the ITU, and subsequently, the standard was adopted. Following adoption of the standard, defendant refused to comply with the license terms, claiming they were discriminatory, unfair, and unreasonable.</p>
			<p>Plaintiff sued defendant alleging patent infringement and defendant, by way of counterclaim, alleged improper conduct by the plaintiff under &sect;&sect; 1 and 2 of the Sherman Act and asserted that plaintiff had denied access to its technology by "conditioning the availability of the technology on reciprocal dealing, by extracting cross-licenses at fixed, artificially low rates and by attempting to double-charge [the defendant] and its customers by requiring them each to pay a separate license fee&hellip;."</p>
			<p>The court dismissed the defendant's counterclaims on the pleadings, holding that defendant had not sufficiently alleged injury to competition. In particular, the court noted that although the ITU Policy required plaintiff to waive its patent rights or grant licenses on reasonable terms, it left negotiation of specific license terms to the parties. Accordingly, the court held: First, because "a patent holder is permitted under the antitrust laws to completely exclude others from practicing his or her technology," the proposition of specific license terms alone (reasonable or unreasonable) would not constitute an antitrust law violation. Second, without reaching the question whether the plaintiff's proposed terms were in fact unfair, the court held that the proposed terms could not support an antitrust law violation because: "a patent owner's pursuit of optimum royalty income is not an act in restraint of trade", "cross-licensing is considered a pro-competitive practice because it can facilitate the integration of complementary technologies" and " a patent owner has the legal right to refuse to license his or her patent on any terms".</p>
			<p><strong>5.4 &mdash; </strong><a href="http://caselaw.lp.findlaw.com/scripts/getcase.pl?navby=case&amp;court=us&amp;vol=486&amp;page=492"><em>Allied Tube &amp; Conduit Corp. v. Indian Head, Inc.</em>, 486 U.S. 492 (1988).</a><a name="ahic"></a> The National Fire Protection Association (the "NFPA") sets and publishes fire protection standards through a member voting process. Standards approved by a majority of NFPA members are generally adopted into state law and include the National Electric Code (the "Code"). In 1980, the Code permitted the use of steel, but not plastic electrical conduit.</p>
			<p>The defendant was the Nation's largest steel conduit manufacturer and a NFPA member. Allied Tube, a plastic electrical conduit manufacturer, had proposed the inclusion of plastic electrical conduit in the 1981 Code and received preliminary approval by a panel of the NFPA. Prior to the 1980 meeting at which the final NFPA vote occurred, however, the defendant and other steel industry and NFPA members agreed to "pack" the NFPA with new members in order to defeat the proposal. The proposal was rejected by a membership that included 230 such "new" members and Allied Tube sued in Federal Court, alleging unreasonable restraints on trade, in violation of &sect; 1 of the Sherman Act.</p>
			<p>Reversing the opinion of the Court of Appeals, the US Supreme Court held for Allied Tube, rejecting defendant's argument that it was immune from the antitrust laws under what is commonly referred to as the Noerr-Penington doctrine (which, in effect, makes "concerted efforts to restrain or monopolize trade by petitioning government officials" immune from the antitrust laws). In doing so, the court made clear that although standards development activities, by their nature, may provide a heightened opportunity for anticompetitive behaviors, "private standard-setting programs can be procompetitive when they are based on the merits of objective expert judgments and through procedures that prevent the standard-setting process from being biased by members with economic interests in stifling competition". Responding to the defendant's asserted defense, the Court made clear that whether or not a standard developed by a private entity or organization is adopted into law is not determinative of whether that private entity's conduct is immune from the antitrust laws. Rather, the scope of protection afforded by Noerr-Penington "depends . . . on the source, context, and nature of the anticompetitive restraint at issue."</p>
			<p><strong>5.5 &mdash; </strong><a href="http://www.weil.com/wgm/cwgmhomep.nsf/Files/ASSE+ORDER/$file/ASSE+ORDER.pdf"><em>In the Matter of American Society of Sanitary Engineering,</em> Dkt. C-3169, 106 F.T.C. 324 (1985).</a> The consent decree in this case points out the FTC's willingness to require SDOs to include new and innovative technologies in their standards when there is no reasonable justification or basis for rejecting such new technologies. The American Society of Sanitary Engineering ("ASSE"), an influential private trade association in the plumbing industry, adopted standards and seals of approval relating to a wide variety of plumbing devices, and compliance with its standards was often a critical prerequisite to entry into the plumbing market. This case arose in connection with an innovative anti-backflow valve for toilets, designed by J.H. Industries. Although the J.H. product did not comply with the ASSE standard, J.H. established that its product worked equally with respect to preventing backflow and that its product may in fact have performed better in several respects. When ASSE failed to modify the existing standard to include the J.H. product, the FTC brought an antitrust challenge under Section 5 of the FTC Act, complaining that ASSE had no reasonable justification for rejecting the innovative design and that "an innovative product has been excluded from various geographic markets." As a result, the complaint alleged, "building code and regulatory officials and buyers of toilet tank fill valves have been misled to believe that the product will not perform adequately."</p>
			<p>A subsequent consent decree accordingly required ASSE to modify the existing standard to permit the approval of the J.H. product. Specifically, the decree provided that modification of the standard was necessary if it could be reasonably shown that the new product "adequately meets the implicit or explicit performance goals required by the existing standard" and that no reasonable standard-setting justification exists to disallow inclusion of the new technology in the standard. As this clearly suggests, an SDO's use of the standards development process to exclude competitors with innovative patent-protected products from the market could risk antitrust challenge.</p>
			<p><strong>5.6 &mdash; </strong><a href="http://caselaw.lp.findlaw.com/scripts/getcase.pl?navby=case&amp;court=us&amp;vol=456&amp;page=556"> <em>American Society of Mechanical Engineers v. Hydrolevel Corp</em>., 456 U.S. 556 (1982).</a> This case addresses the law of agency as applied to SDOs in the antitrust context. The American Society of Mechanical Engineers ("ASME") is a non-profit member organization that, like ASSE (above), promulgates standards with respect to its industry, in this case, mechanical engineering. Its codes and standards are highly influential in the industry and often, compliance with such codes present an important prerequisite for successful entry into the market. Among the ASME members at the time of the case was McDonnell &amp; Miller, Inc. ("MMI"), which manufactured and sold a safety device for water boilers. MMI's vice president ("James") was also the vice chairman of the ASME subcommittee charged with drafting, revising and interpreting the ASME code section relating to the MMI device.</p>
			<p>After learning that one of MMI's customers switched to a competing device manufactured and marketed by Respondent, Hydrolevel Corp., James met with ASME subcommittee chairman Hardin and other MMI officials. Following the meeting, MMI wrote a letter to ASME, which was referred to the subcommittee chairman (Hardin), and which essentially requested ASME's opinion as to whether the competing product was in compliance with the ASME code. ASME's "unofficial response" was prepared by Hardin, on AMSE stationary, signed by a full-time ASME employee and effectively declared that the Hydrolevel product was unsafe. Thereafter, Hydrolevel suffered significant market impairment as MMI's sales force began using the unofficial opinion to discourage potential Hydrolevel customers. When Hydrolevel learned of James' connection with the subcommittee and unofficial opinion, it sued ASME under the antitrust laws, alleging violations of Sherman Act &sect;&sect; 1 and 2.</p>
			<p>The US Supreme Court found in favor of Hydrolevel, affirming the opinion of the Court of Appeals on the grounds that ASME was liable for the acts of its agents committed with apparent authority. In rendering its opinion, the Court recognized that the general laws of agency apply in the antitrust context and that the antitrust cause of action should be interpreted as being "at least as broad as a plaintiff's right to sue for analogous torts, absent indications that the antitrust laws are not intended to reach so far". Further, it noted that "a rule that imposes liability on the standard-setting organization -- which is best situated to prevent antitrust violations through the abuse of its reputation -- is most faithful to the congressional intent that the private right of action deter antitrust violations." Finally, the Court concluded, "even if the agents act[ed] without any intent to aid petitioner . . . petitioner should be encouraged to eliminate the anticompetitive practices of all its agents acting with apparent authority, especially those who use their positions in petitioner solely for their own benefit or the benefit of their employers."</p>
			<p><a name="rambus1"></a><strong>5.7 &mdash; </strong>One of the most closely followed situations in recent years involves a technology licensing company named Rambus, Inc. ("Rambus"). Rambus designs and licenses computer memory systems and is the owner of patents covering RDRAM and SDRAM technologies. Rambus does not manufacture these technologies, but instead licenses its patents to semiconductor manufacturers. As noted above, Rambus was a member of the Joint Electron Devices Engineering Council ("JEDEC"). A number or law suits and a federal investigation have arisen in connection with that membership, as described below.</p>
			<p><strong>5.7.1 &mdash; </strong>Rambus, Inc. v. Infineon Technologies AG, et al., 164 F. Supp. 2d 743 (E.D. Va. August 9, 2001). At the time the case arose, Rambus and Infineon were both members of JEDEC. JEDEC was formed to develop industry-wide technical standards for semiconductor products including standards to ensure interoperability of Dynamic Random Access Memory ("DRAM") products. JEDEC's IPR policy was aimed at avoiding the inclusion of patented technology in its standards, and therefore it required members to disclose patents and patent applications that related to JEDEC's standard setting activities. JEDEC's members signed an agreement that required them to license any patented technology that was included in a standard "under reasonable terms and conditions that are demonstrably free of any unfair discrimination."</p>
			<p>Rambus joined JEDEC as a member in December of 1991 and its representatives regularly attended meetings of the JEDEC committee working on the SDRAM standard until December of 1996. Rambus had one patent and four patent applications relating to SDRAM while it was a member. Rambus resigned its membership by a letter dated June 17, 1996, but during its membership, Rambus never disclosed its patent applications to JEDEC or Infineon. The four patents at issue in this case were issued between 1997 and 1999.</p>
			<p>Following adoption of the standard, Rambus was successful in extracting licensing fees and royalties from several manufacturers that included the Rambus patents in their products when implementing the SDRAM standard. Infineon, however, refused to pay such royalties and Rambus sued Infineon for infringement of four of its patents covering SDRAM technologies. Infineon counterclaimed, asserting, among other things, that Rambus had committed fraud while a member of JEDEC by failing to disclose its patents at that time. The Court found that Rambus' patents were not infringed. Infineon's counterclaims of fraud went to a jury trial, and the jury found in favor of Infineon, awarding $1 for each fraud claim and $3,500,000 in punitive damages to Infineon. The Court later reduced the amount of punitive damages to $350,000. On appeal to the US District Court for the Eastern District of Virginia, the Court overturned the jury's constructive fraud verdict, but upheld the actual fraud verdict with respect to Rambus' failure to disclose its patent applications covering SDRAM technology.</p>
			<p>In rendering its decision, the Appeals Court reasoned that Rambus had a duty to disclose its patent applications under JEDEC policy and that such disclosure was consistent with past JEDEC practice regardless of whether it was required under the policy. Additionally, the Court found that despite Rambus' contention that its pending patents at the time it was a member of JEDEC did not cover the subject technology, Rambus executives themselves had provided sufficient evidence that the patent applications did in fact relate to the JEDEC work and that Rambus actually expanded its patent applications to include the technology discussed at JEDEC meetings.</p>
			<p>Rambus also argued that it had no intent to mislead, but rather that it mistakenly believed that it had no duty to disclose. The Court, however, found that in light of pointed discussions between Rambus and patent counsel regarding disclosure and e-mails among Rambus executives discussing the proper tack to take at JEDEC meetings, there was sufficient evidence to show such intent. Finally, the Court held that Infineon's reliance on Rambus' non-disclosure was reasonable. The Court based this conclusion on the fact that Rambus had continually failed to disclose its patent applications, despite Infineon's repeated efforts at raising such concerns (including direct questions at a JEDEC meeting).</p>
			<p>Rambus appealed its case to the US Court of Appeals for the Federal Circuit and oral arguments began on June 6, 2002. Among other things, Rambus is appealing the fraud verdict and the District Court's finding that the Rambus SDRAM patents were not violated.</p>
			<p><a name="rambus2"></a><strong>5.7.2 </strong>&mdash; In<a href="images/rambus2.pdf"> <em>Rambus, Inc. v. Infineon Technologies AG, et al</em>., 318 F.3d 1081 (Fed. Cir. January 29, 2003)</a>, and to the surprise of many, two out of three judges sitting on a three-judge panel of the Appeals Court did not agree with the Trial Court in almost anything that they had decided to the benefit of Infineon. Instead, the Court vacated the lower court's finding of noninfringement and remanded this aspect of the case for further consideration by the trial court, using a narrower and more complex analytical method laid down by the Appeals Court. The Appeals Court panel majority also held that Rambus had no duty to disclose its patent applications, and therefore could not have committed fraud (no matter how unwholesome its conduct may have been). Finally, it vacated the attorney's fees award, and directed the trial court to reconsider any award of costs in light of the other holdings of the Appeals Court.</p>
			<p><strong>5.7.3 &mdash; </strong>On February 26, 2003, Infineon filed a petition with the Appeals Court, asking the entire court rehear the case. Lucash, Gesmer &amp; Updegrove LLP, the host of this website, filed an <a href="images/amicus.pdf">Amicus Curiae brief</a> in support of that motion.</p>
			<p><strong>5.7.4 &mdash; </strong>In the meantime, on June 19, 2002 the FTC announced that it would file antitrust charges against Rambus in connection with the Company's failure to disclose patents during the standard-setting process. A spokesperson for the FTC stated that the Agency was sending a message to members of the technology industry that, "If you are going to take part in a standards process, be mindful to abide by the ground rules and to participate in good faith." The FTC initially began investigating Rambus as early as 2001 on grounds that its failure to disclose patents during the standards development process might constitute an unreasonable restraint on trade. Notably, it was reported on June 19, 2002 that "Industry sources questioned by the FTC told EBN last week that the agency is looking into formulating a rule requiring all participants in an industry open-standards committee to disclose their pending patent applications." See <a href="http://www.ebnonline.com/digest/story/OEG20010601S0070.%20">http://www.ebnonline.com/digest/story/OEG20010601S0070.</a></p>
			<p><strong>5.8 &mdash; </strong><a href="/antitrust/ados.php"><em>Addamax Corporation v. Open Software Foundation, Inc.</em>, 888 F. Supp 274 (1995).</a> In this case, Addamax Corporation ("Addamax"), a producer of computer security systems, filed suit against the Open Software Foundation, Inc. ("OSF"), a joint venture of computer manufacturers, and two of OSF's founders, Digital Equipment Corporation and Hewlett-Packard Company, alleging antitrust violations.</p>
			<p>OSF is a not-for profit corporation, whose membership is open to corporations, non-profits, academic institutions, governmental agencies and other business entities. It was formed to "undertake cooperative research, experimentation and development activities &#133; to allow users to more easily mix and match computers and software from different suppliers."</p>
			<p>OSF undertook to develop new computer operating systems, and for this purpose, purchased and integrated existing technologies through a bidding process. Addamax was one of two companies to respond to a Request for Technology for security programs. Addamax was not selected, and then filed suit claiming that it lost the bid because OSF had rigged the bidding process to favor specific companies and technologies. Addamax claimed that it was effectively shut out of the market because the technology selected by OSF became the industry standard.</p>
			<p>The Court rejected Addamax's request to apply a "per se" antitrust standard of review. At least in part, this was because Addamax lacked evidence that OSF's adoption of its security standard had an anticompetitive effect on the market. Nonetheless, the court found a sufficient basis to find for Addamax under a "rule of reason" antitrust analysis and therefore allowed the case to proceed to trial. Specifically, the court found that a trial was warranted in light of significant factual questions regarding the market power of OSF, the anticompetitive effects of OSF's business and conduct, and the anticompetitive effects of OSF's original formation.</p>
			<p>Following the case above, the practical end to the lawsuit came when the presiding judge ordered a bench trial limited to issues of damages and culpability, and the parties then stipulated that the issue of damages would be resolved first. Following testimony, the judge ruled that OSF's conduct was not a material cause of the damages sustained by Addamax and, essentially, that Addamax's own poor performance in the marketplace had condemned it to economic failure. See Addamax Corp. v. Open Software Foundation, 964 F. Supp. 549 (D. Mass. 1997). Hence, the actual guilt or innocence of OSF became academic, and a trail on the merits was never held. The First Circuit then affirmed the district court's finding in 1998. See Addamax Corp. v. Open Software Foundation, 152 F.3d 48 (1st Cir. 1998).</p>
			<p><strong>5.9 &mdash; </strong><a href="/antitrust/rbpg.php"><em>Radiant Burners, Inc., v. Peoples Gas Light &amp; Coke Co. et al.,</em> 364 U.S. 656; 81 S. Ct. 365; 5 L. Ed. 2d 358; 1961 Trade Cas. (CCH) 69,896 (1960).</a> This case from the early 1960s helped to define the parameters of the "per se" antitrust violation analysis. Respondent, American Gas Association (AGA), was a membership association that tested the safety, utility and durability of gas burners and affixed seals of approval to burners that passed its tests. Additionally, the AGA and its gas utility members were in the business of selling gas, which they apparently would not sell for use with unapproved burners. Petitioner manufactured and sold ceramic gas burners, known as "Radiant Burners", and was twice denied the AGA seal of approval, despite its contention that Radiant Burners were safer, more efficient and at least as durable as AGA approved burners. Petitioner sued Respondent and alleged that respondent and ten of its members had combined and conspired to restrain interstate commerce in the manufacture, sale, and use of gas burners by withholding its seal of approval from petitioner's product and refusing to provide gas, in violation of Sherman Act &sect;1.</p>
			<p>The district court dismissed the case for failure to state a claim upon which relief could be granted and the Court of Appeals for the Seventh Circuit affirmed. The Court of Appeals reasoned that because "no boycott, conspiracy to boycott or other form of per se violation is established by the alleged facts", the Sherman Act would provide relief "only under circumstances where there is such general injury to the competitive process that the public at large suffers economic harm." Finding no appreciable change in the number of burners purchased due to respondent's conduct, the Court of Appeals affirmed the dismissal of the lower court.</p>
			<p>The Supreme Court reversed, holding that the complaint "clearly shows one type of trade restraint and public harm that the Sherman Act forbids," namely, that "petitioner cannot sell its gas burners . . ." and its "purchasers cannot buy gas for use in those burners." It concluded that respondent's conduct is by its nature unduly restrictive, has a monopolistic tendency, and violates the antitrust laws. The Court concluded, "As such [respondent's conduct] is not to be tolerated merely because the victim is just one manufacturer whose business is so small that his destruction makes little difference to the economy."</p>
			<p><strong>5.10 &mdash; </strong><a href="/antitrust/wlme.php"><em>Wang Laboratories, Inc. v. Mitsubishi Electronics America, Inc. and Mitsubishi Electric Corporation</em>, 103 F.3d 1571; 41 U.S.P.Q.2D (BNA) 1263 (Fed. Cir. 1997).</a> Although this case does not directly implicate antitrust issues, it raises questions central to the activities of SDOs and others who engage in the standards development process. At issue in this case were two patents regarding a particular design for single in-line memory modules ("SIMMs"). Wang and the original inventor (a Wang employee, who assigned his rights to the invention to Wang) applied for a patent in 1983. Shortly before that time, Wang held a press conference in which the company introduced the technology at a widely covered press conference. At the conference, Wang expressed its hope that the SIMMs would become the memory module industry standard and noted the struggle it anticipated in order to persuade the Joint Electronic Device Council ("JEDEC"), a committee of the Electronic Industries Association charged with setting industry standards, to adopt the SIMMs technology. Additionally, Wang noted at that time that it did not intend to produce the SIMMs itself, but rather, intended to encourage others to produce it. Importantly, Wang also stated that it "was not seeking to patent the SIMMs, that no licensing agreements were involved for the companies approached by Wang to make SIMMs, and that SIMM makers could sell their products to third parties."</p>
			<p>Later in 1983, Wang began concerted and sustained efforts to have JEDEC adopt SIMMs as the industry standard. Its efforts persisted through 1986, and in the interim, Wang aggressively sought out and obtained the cooperation of several manufacturers, among them Mitsubishi, to begin mass producing and marketing the SIMMs. During that period, Wang never mentioned its pending patents to JEDEC or Mitsubishi, nor did it discuss its intention to execute licenses and receive royalties from the manufacturers. JEDEC finally adopted the SIMMs in 1986 and the patents issued in 1987 and 1988. The basis for this case arose in 1989, when Wang sent a letter to Mistubishi, accusing it of infringing both patents, following which Wang sued Mitsubishi in 1992.</p>
			<p>Affirming a jury verdict against Wang, the US Court of Appeals for the Federal Circuit held that Wang's conduct had created an implied license for Mitsubishi to use the SIMMs technology. The court bolstered its holding with a finding that "the entire course of conduct between the parties over a six-year period led Mitsubishi to infer consent to manufacture and sell the patented products" and that, "as a matter of law, Mitsubishi properly inferred consent to [use] Wang's patents." Further, the court found that Mitsubishi had supplied sufficient consideration to Wang to warrant a finding of a license. In sum, the court noted, "Wang consented to Mitsubishi's use of the invention, granted the right to make, use, or sell the patented SIMMs without interference from Wang, and received consideration." That being the case, the court concluded that Mitsubishi had an irrevocable royalty-free license and there was no infringement.</p>
			<p><strong>5.11 &mdash; </strong><a href="/antitrust/weit.php"><em>Winbond Electronics Corp. v. International Trade Commission</em> 262 F.3d 1363 (Fed. Cir. 2001).</a> Like Wang, above, this case does not directly implicate antitrust issues. Nonetheless, it is instructive for SDOs because it helps define the lengths to which courts may be willing to go to find an implied license in the commitments or promises made by patent holders during the course of standards development. The case itself centered around a dispute among Amtel (petitioner, and assignee to the patent rights in question) and several alleged infringers (the respondents) as to the enforceability of a patent for encoding identifying information (a "Silicon Signature") directly within a silicon memory chip.</p>
			<p>The Silicon Signature technology was originally developed by SEEQ Technologies, Inc. and subsequently assigned to Amtel. During its development, SEEQ proposed to JEDEC that it adopt the Silicon Signature as an industry standard. During its discussions with JEDEC, SEEQ committed to licensing its patent to those who implemented the standard on a royalty-free basis, provided that JEDEC in fact adopted the standard. Ultimately, JEDEC did not adopt the standard and Amtel marketed the product.</p>
			<p>The cause of action in this case arose when Amtel filed a complaint with the U.S. International Trade Commission (the "Commission") alleging that Winbond, Macronix and Sanyo (the respondents) had violated section 337 of the Tariff Act of 1930, as amended, "by importing, selling for importation or selling in the US chips that infringed the Amtel patent." The respondents contended that the patent was invalid for lack of proper authorship in the patent application and that, even if it was valid, SEEQ's discussions with JEDEC had created an implied license to use the technology royalty-free.</p>
			<p>Following two administrative hearings, two Commission hearings and an Amtel filing with the USPTO for a correction of authorship, the case made its way to the Court of Appeals for the Federal Circuit. Ultimately, the Circuit Court affirmed the final decision of the Commission, finding that the Amtel patent was valid and that the respondents were in fact not entitled to an implied license under theories of either equitable or legal estoppel, acquiescence or due to SEEQ's conduct. Importantly for SDOs and other entities engaged in the standards development process, the Court found that the conditional promise made by Amtel to JEDEC did not supply the necessary basis upon which to rest the creation of an implied license. Thus, the Court found, "because JEDEC did not accept the Silicon Signature as a standard, the Commission correctly found that SEEQ did not give an affirmative grant of consent or permission to make, use, or sell the claimed invention."</p>
			<p><a name="512"></a><strong>5.12 &mdash; </strong><a href="/antitrust/cmpvapi.php"><em>Consolidated Metal Products, Inc. v. American Petroleum Institute</em>, 846 F.2d 284, 1988-1 Trade Cas. (CCH) P68,051 (5th Cir. 1988).</a> In this case, the Fifth Circuit Court of Appeals affirmed a district court summary judgment decision against Consolidated Metal Products, Inc. ("CMPI") regarding CMPI's contention that the American Petroleum Institute ("API") had delayed trade standard certification to certain equipment manufactured by Consolidated and thereby excluded it from the market in violation of Section 1 of the Sherman Act.</p>
			<p>CMPI was a manufacturer of oil well equipment, including "sucker rods", which are part of the equipment used to pump oil from wells having low natural pressure. API was the only domestic standards-setting body for oil field equipment. Manufacturers who applied to API for product approval and were successful received (for an annual fee) a license to display API's monogram on their products. The API certification monogram has commercial value in that its use enhances product sales, but API approval is not required by law.</p>
			<p>By 1981, CMPI had begun to manufacture and sell three-piece sucker rods, which were coupled by threaded joints, whereas conventional sucker rods were manufactured as single piece units. CMPI applied for API approval on June 1, 1981 and was shifted from committee to committee within API and ultimately denied approval due to certain non-specification tensile strength characteristics. A dispute and additional discussions followed, and ultimately, after CMPI threatened to sue API, API revised its specification and approved the CMPI product on April 15, 1983. Seven days later, CMPI filed suit against API and others, alleging that the delay in certification constituted a conspiracy in restraint of trade to exclude CMPI from the market.</p>
			<p>The Court held that API's conduct did not constitute an antitrust violation under either the per se illegality test or the Rule of Reason test. Noting that CMPI had offered no evidence to show that API's certification process constituted a "group boycott" and had failed to allege that sucker rod users were in any way constrained from buying CMPI's products, the Court held that "a trade association that evaluates products and issues opinions, without constraining others to follow its recommendations, does not per se violate [Sherman Act] section 1 when, for whatever reason, it fails to evaluate a product favorably to the manufacturer." Turning to the "Rule of Reason" test, the Court commented that although "a trade association, by its nature, involves collective action by competitors . . . a trade association is not by its nature a 'walking conspiracy'," as contended by CMPI. Further, the Court noted, "a showing that the defendants harmed the plaintiffs is not enough to prove a violation of section 1 under the rule of reason. It is a natural part of a competitive market that products, firms, and -- sometimes -- entire sectors of the economy fail. A plaintiff does not have a claim under the rule of reason simply because others refuse to promote, approve, or buy its products." Rather, the Court concluded, "the 'reasonableness' of a restraint is judged by its general effect on the market, not by the circumstances of a particular application." Finding no conspiracy, nothing unreasonable in the fact that the accreditation was delayed (other than that the delay itself may have been a business error on the part of API), and no discernable anticompetitive market effect, the Court held that API's conduct did not violation the Sherman Act.</p>
			<a name="section6"></a><h3>VI &ndash; Articles and Essays</h3>
			<p>The interface between law, standards and economics has become the source of an increasing number of articles. The following articles have been written by some of the academic and legal authors who have focused most carefully on this area.</p>
			<p><strong>6.1 &mdash; </strong>Mark A. Lemley, <em><a href="http://econ.tau.ac.il/papers/applied/0109037.pdf">Antitrust, Intellectual Property and Standard -Setting Organizations</a></em>, University of California at Berkeley. In this article, Mark Lemley attempts to fill the void in current literature regarding SDOs and their policies regarding intellectual property. Based upon the author's survey of intellectual property policies of numerous such organizations, primarily in the industries of computer networking and telecommunications, he provides a background discussion of these organizations, discusses the value of standards development in network markets, demonstrates the diversity among such organizations as to treatment of intellectual property, addresses the impact of antitrust laws on these organizations and their intellectual property policies, analyzes several unresolved legal issues regarding the applicability and enforcement of intellectual property policies for such organizations and offers relevant suggestions to scholars, law-makers and SDOs.</p>
			<p><strong>6.2 &mdash; </strong>Debra A. Valentine, <a href="http://www.ftc.gov/speeches/other/dvisraelspeech.htm"><em>Industry Self-Regulation and Antitrust Enforcement: An Evolving Relationship</em></a>, Address at the IDC Campus, Herzlia, Israel, (May 24, 1998). This article addresses the relationship between antitrust enforcement and industry self-regulation in the United States. The author begins with a brief description of the evolution of the government's approach to industry cooperation - from visceral opposition near the turn of the century to an increased receptiveness in recent years that acknowledges the benefits of industry cooperation on at least some levels. The author then surveys three seminal cases in the area of industry self-regulation that highlight the contours of government antitrust enforcement policy.</p>
			<p><strong>6.3 &mdash; </strong>Dr. Carl Cargill, <a href="http://www.house.gov/science/cargill_091300.htm"><em>Evolutionary Pressures in Standardization: Considerations on ANSI's National Standards Strategy</em></a><em>,</em> Address Before the U.S. House of Representatives Science Committee, Technology Subcommittee (September 13, 2000). This paper was delivered by Dr. Cargill to the U.S. House of Representatives, Subcommittee on Technology, Committee on Science on September 13, 2000. Dr. Cargill first describes the history, evolution and mechanisms of change of SDOs, moving from trade associations at the turn of the century to national formal organizations, international formal organizations, consortia and most recently, trade alliances. The author then offers a critique of the standards development process often utilized by SDOs and presents an alternative model. Finally, Dr. Cargill addresses the role of government in the standardization process, arguing that the government must be empowered to address issues specific to today's "web based standardization environment," including issues arising from monopoly, anti-trust, and intellectual property law.</p>
			<p><strong>6.4 &mdash; </strong>Venable Melissa Landau Steinman<em>, <a href="http://www.incits.org/archive/2000/it000771/steinman.pdf">Standards, Intellectual Property and Antitrust</a>, </em>Speech for NCITS TC Officer's Symposium (October 17, 2000). This article suggests that although IP rights present certain barriers to the efficient development of standards, such barriers are not insurmountable and must be addressed early in the standards development process. The article begins with an overview of the developmental history of SDOs, moves to a general discussion of the legal framework in which such organizations operate today, and then analyses several post hoc and proactive legal means of addressing and/or avoiding legal issues that typically arise at the intersection of standards development procedure, IP rights and antitrust law. With that analysis in mind, the author urges readers to be proactive in undertaking standards development activities, and in particular, to pay attention to issues such as process, disclosure, and licensing at the outset of the standards development process.</p>
			<p><strong>6.5 &mdash; </strong>Timothy J. Muris, <a href="http://www.ftc.gov/speeches/muris/intellectual.htm">Competition and Intellectual Property Policy: The Way Ahead,</a> Prepared Remarks at the American Bar Association, Antitrust Section Fall Forum, Washington, DC (November 15, 2001). In this speech, Timothy J. Muris, Chairman of the Federal Trade Commission describes his views as to the new initiative the antitrust agencies (the FTC and the Antitrust Division of the Department of Justice) should take to enhance their understanding of how to manage issues involving competition and intellectual property law and policy and to harmonize existing doctrines in a way that maximizes consumer benefits. He then reviews recent developments in relevant law and policy, as well as current FTC initiatives that should benefit from hearings to be held by these agencies on the relationship between competition and intellectual property. The speech contains a segment devoted to SDOs in which Mr. Muris notes a need on the part of the agencies to increase their understanding of the standards development process in order to address anti-competitive practices in this area, while at the same time being sensitive to the need for such standardization in today's global economy.</p>
			<p><strong>6.6 &mdash; </strong>Robert F. Leibenluft, <a href="http://www.ftc.gov/bc/adops/fahctlet.htm">Federal Trade Commission Letter to Paul L. Yde</a> (April 17, 1997). Given that standards developing bodies are typically controlled by entities with horizontal business relationships, they are by their nature deemed to involve concerted action. Thus, such bodies are subject to scrutiny under the antitrust laws. Although this letter specifically concerns standards development and accreditation activities pertaining to the collection, processing, and transplantation of hematopoietic progenitor cells by the Foundation for the Accreditation of Hematopoietic Cell Therapy, the "Analysis" section (beginning roughly half way through the document) provides an excellent example of the analysis performed by the Federal Trade Commission in assessing whether such standards development activities are in fact anticompetitive. In the process, the letter highlights several "red flags" the FTC typically looks for when making antitrust determinations.</p>
			<p><strong>6.7 &mdash; </strong>Eleanor M. Fox &amp; Robert Pitofsky, <a href="http://www.iie.com/publications/chapters_preview/56/7iie1664.pdf">United States</a>, in Global Competition Policy 250 (Edward M. Graham &amp; J. David Richardson, eds. 1997). This chapter, written by Eleanor Fox and Robert Pitofsky (Robert Pitofsky is the current Commissioner of the FTC), provides an excellent primer on the history, structure and interpretation of US antitrust laws, with a special emphasis on the interaction between US antitrust laws and global competition. Chapter subsections address a broad spectrum of issues including the goals of US antitrust and competition policy, US antitrust statutes (federal and state), US antitrust enforcement, special issues involving potentially significant global market impact, trade and investment policies, national security issues, treatment of US and foreign transactions under US law, the reach of US antitrust laws overseas, and treaties. For a table of contents and links to other chapters of Global Competition Policy, please <a href="http://www.iie.com/publications/pub.cfm?pub_id=56&amp;noprice=yes">click here.</a></p>
			<a name="section7"></a><h3>VII &ndash; Other Resources</h3>
			<p><strong>7.1 &mdash; </strong><a href="http://www.ansi.org">American National Standards Institute.</a> ANSI administers and coordinates the U.S. voluntary standardization and conformity assessment system. Its website regularly includes materials and links to other online resources relating to standards development and antitrust law.</p>
			<p><strong>7.2 &mdash; </strong><a href="http://www.gtwassociates.com">GTW Associates.</a> This site follows US and international cases and other developments relating to antitrust laws and standards development. It includes helpful articles, links and other standards resources.</p>
			<p><strong>7.3 &mdash; </strong>For links to a wide variety of other available antitrust web sites, please <a href="http://www.usdoj.gov/atr/contact/otheratr.htm">click here</a>.</p>
			<p><strong>7.4 &mdash; </strong>For an excellent general antitrust resource, please see the <a href="http://www.abanet.org/antitrust/home.html">ABA's Antitrust Section web site.</a></p>
			<p><strong>7.5 &mdash; </strong>A <a href="http://www.compcom.co.za/thelaw/thelaw_glossary.asp?level=3">glossary</a> of antitrust terms.</p>
			<p class="note"><strong>NOTE:</strong> If you participate in the standards development process or are a member of the management of a standard setting organization, please feel free to contact <a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a> if you have questions about this topic.</p>
			<p class="center">Copyright 2007 Andrew Updegrove</p>
			<table class="GuideHelp">
				<tr>
					<td style="padding:12px;" valign="top"><a href="http://www.gesmer.com/attorneys/updegrove.php"><img src="images/guide_updegrove.jpg" width="69" height="106" border="0" alt="" /></a></td>
					<td valign="top">
						<p class="GuideHelpHead">Can We Help You?</p>
						<p class="GuideHelpBody1"><a href="http://www.gesmer.com/">Gesmer Updegrove LLP</a> is, quite simply, the most experienced law firm in the United States when it comes to representing and creating standards development organizations &mdash; <a href="http://www.gesmer.com/practice_areas/consortium.php#CLIENTLIST">more than 100</a> &mdash; to date.  If you need advice about participating in the standards development process, representation in standards-related litigation, intellectual property advice, or help creating a brand new SSO or open source foundation, we'd be pleased to help. Contact:</p>
						<p class="GuideHelpBody2">Email: <script language="javascript" type="text/javascript">AuGesAdd();</script><br />Tel: 617-350-6800</p>
					</td>
				</tr>
			</table>
			<p><a class="returntotop" href="#startcontent" title="return to beginning of content">return to top</a></p>
		</div>
	</div>
<div class="clear"><br /></div>
<!-- *********** -->
<!--   FOOTER    -->
<!-- *********** -->
<?php include '../includes/footer.php'; ?>
</form>
</body>
</html>