				<!-- ******************* -->
				<!--   FEATURE ARTICLE   -->
				<!-- ******************* -->
				<h3>A Proposal for a New Type of<br />Global Standards Certification</h3>
				<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
				<blockquote class="openingquote"><em><strong>Abstract:&nbsp;</strong>The traditional standards infrastructure was developed over more than a century to meet the needs of developed nations for standards for implementation in physical products. That infrastructure created standards at the national level that could be adopted for global use by one of a number of organizations that evolved to serve the needs of defined market sectors. In modern times, the information technology sector largely opted out of this structure, choosing to develop standards through organizations with global, rather than national, memberships, and only occasionally submitting standards for approval by traditional global organizations. Later, but to a lesser extent, the communications technology sector followed suit. Today with the ongoing process of globalization, the advent of the Internet and the Web, and the redeployment of most commercial, financial and government services over these new global networks, there is a need not only for a new global standards body to ensure the vitality of ITC standards creation, but for the availability of new types of institutional certifications for consortia and accredited standards organizations as well. Such certifications could provide additional information to differentiate one organization, and its standards, from another, offering governments and end-users with the ability to drive standard setting in more commercially and socially useful directions, thereby increasing choice, and fostering important social goals such as free trade, energy conservation and sustainability of resources. In this article, I identify these needs, and propose new structures that could be created to pursue these salutary results.</em></blockquote>
				<p><strong><em>Introduction:&nbsp;</em></strong>The standard setting infrastructure of today includes numerous differentiated but interconnected pieces. At the global level, it includes well-established standard setting organizations, each with its variously narrow (e.g., telecommunications or food) or broad (just about everything else) domain of operation, trade agreements that impose standards-related obligations, and mechanisms for resolving trade disputes based upon violations of those rules.</p>
				<p>At the national level, there exists a diverse range of approaches and institutions, from the sector-specific, nationally accredited standards development organizations found in the United States, to the government coordinated efforts of countries such as Germany and China. But regardless of the model, each of these nations is entitled to representation in the major global institutions, such as the <a href="http://www.iso.org/iso/home.htm">International Organization for Standardization</a> (ISO), founded in 1947, the <a href="http://www.iec.ch/">International Electrotechnical Commission</a> (IEC), founded in 1906, the <a href="http://www.itu.int/net/home/index.aspx">International Telecommunication Union</a> (ITU), which traces its origins to 1865 and now operates under the aegis of the United Nations, and the <a href="http://www.codexalimentarius.net/web/index_en.jsp">Codex Alimentarius</a>, founded in 1963 by two United Nations agencies to develop food standards.</p>
				<p>While in some cases national participation in these global bodies is at the government level (as with the ITU) and in others via whatever public or private sector organization has become recognized internationally as the representative of a nation (as with ISO), the structure is hierarchical and democratic, and in many ways the processes are similar.</p>
				<p>In consequence, this long-evolving structure has achieved great legitimacy. Those standards that are finally adopted by the global bodies are often preferentially selected for procurement use, especially by governments (as with the ISO and IEC), and even become the basis for international agreements (as with the radio frequencies set by the ITU).</p>
				<p>But in addition to this orderly and symmetrical infrastructure a second standard setting regime has evolved over the last twenty years, which operates along similar but not always identical process rules, and which largely addresses the information and communications technology (ICT) sector. These organizations began to be formed in the mid 1980s due to the failure of the existing standards infrastructure to meet the perceived needs of the information technology (IT) industry. Most of the resulting organizations seek to set standards for global adoption, although some address national or regional needs. Organizations of this type, usually referred to as fora, alliances, SIGS (for "special interest groups"), or most frequently, consortia, now number in the <a href="http://www.consortiuminfo.org/links/">many hundreds</a>.</p>
				<p>While most such organizations (I will use the word "consortia" to refer to all of them) were initially formed to achieve narrow goals, or even to develop and maintain a single standard, many now cover technical domains that are very wide, and may host fifty or more working groups at any point in time. These consortia have become as well-respected and institutionalized as their accredited peers, which in some cases have lost influence and standards market share to these new competitors. In the case of the IT industry in particular, consortia have become the venue of choice for the development of the majority of new standards.</p>
				<p>Over time, a degree of formal and informal integration has evolved between the traditional infrastructure and this new, less structured population of non-accredited organizations. At the informal level, both consortia and accredited organizations establish liaison relationships with those organizations that have similar or overlapping missions with little regard to the nature of these neighbors. And on the formal level, some traditional global organizations have established mechanisms whereby a consortium may introduce one of its standards for consideration and approval. In so doing, the consortium may achieve a degree of stature for a standard that can lead to broader uptake, in particular by government users.</p>
				<p>While helpful, these bridges provide an incomplete solution for the needs of the ITC industry, and indeed for the achievement of certain international trade goals and matters of social equity for developing nations. Moreover, because there is no accrediting process for consortia, there is no easy way to tell (for example) what influence may have been brought to bear upon the creation of a given standard, or how much protection the intellectual property rights policy (IPR) of the organization that created it may offer against later unpleasant surprises. In this article, I will explore these areas of deficiency, and suggest new mechanisms that could provide the pieces to complete the evolution of a fully-functional, global, consortium-based standards development infrastructure.</p>
				<p><strong>I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Issues and Opportunities</strong></p>
				<p>As can be inferred from the very brief historical and structural overview above, there are some elements of standards development that are generic, and others that are sufficiently sector-specific to generate the need for independent organizations. At the micro level, this generates roughly similar peer organizations that differ primarily in the specific industry niche that they serve. At the macro level, there are sufficient differences between the realities of certain major industrial groupings (food, telecommunications, and manufacturing) that several, rather than one global organization exist, although this is partly as a result of historical forces as well.</p>
				<p>That the IT industry should have forked off from a system that was already highly evolved before the computer industry became well launched is therefore not surprising, if only because the speed of innovation and the lifespan of technology generations is far shorter in IT than in farm machinery, abrasives and plumbing fixtures. Moreover, while globalization is now profoundly affecting all areas of industry, the need for universal adoption of ITC standards continues to outstrip the need for single-solutions in many other industries, in part due to the advent of the Internet and the Web, but also because of the degree to which interoperability standards can accelerate and expand opportunity.</p>
				<p>Regardless of whether the causes for the original schism remain prevalent today (many would say that the speed of standards development within both accredited organizations and consortia, for example, is now roughly equal), it seems highly unlikely that any reunion of the two systems will occur, or that the vendors that are the major instigators of new standards projects will suddenly decide to preferentially bring their work to accredited organizations rather than consortia. Nor are they likely to seek accredited status within the traditional system for the new consortia that they create.</p>
				<p>There are several reasons for this final conclusion: first, there are now hundreds of consortia with global membership already in existence that offer a one-step path to global implementation. Any perceived affiliation with a single country (e.g., as a result of becoming accredited by a national body) would undercut the perception of geographic impartiality that such a goal demands. Many of these organizations, such as the World Wide Web Consortium (W3C), Organization for the Advancement of Structured Information Standards (OASIS) and Open Geospatial Consortium (OGC) are well staffed, well funded, well respected, and expert in their respective domain areas. Moreover, consortia have a greater freedom in setting their processes and policies relating to intellectual property rights (IPR) than do organizations that are accredited by (for example) the American National Standards Institute (ANSI).</p>
				<p>For all these reasons and more, it makes sense for consortia to continue to evolve in such a way as to optimize their value to the ITC sector, and for the organizations formed to serve the needs of more traditional industries not to strain their own processes and policies to serve so broad a range of industries as to serve none of them well. The result is that the ITC industry needs to continue to follow its own way, and to complete the evolution of its own stand alone infrastructure in any remaining ways necessary.</p>
				<p>Completing the build out of the consortium-based standards development infrastructure would permit a number of current problems to be addressed, as well as provide solutions for concerns that no existing standard structure, accredited or otherwise, is currently equipped to offer, and I will discuss these issues next.</p>
				<p><strong><em>Issues:&nbsp;</em></strong>The ITC world is characterized by dynamism of many types. Consequently, the demands and expectations that are placed upon the standards development infrastructure change over time, and often rapidly. The consortium infrastructure has already adapted to this reality in many ways, including by accommodating a wide range of membership, governance and financial structures and by creating "metaconsortia" that create not standards, but profiles of standards that can address complex market demands (instantiated in the form of "business cases") that cannot be met by any single standard setting body. But new issues continue to arise, including the following:</p>
				<ol>
					<li><strong><em>"<u>Openness</u>:"&nbsp;</em></strong>The traditional world of standards development has evolved a detailed process and rule set that is intended to accomplish a number of meritorious goals, one of which is to attempt to ensure that the interests of all stakeholders are identified and met. The result is a unitary definition of "openness" that is well suited for the originally intended use, but which is proving to be too inflexible to meet the needs of the ICT world. For example, new industry methodologies, such as open source development, are based upon very different, merit-based, fully transparent models that do not always welcome non-technical input.<br /><br /></li>
					<li><strong><em><u>Credibility</u>:&nbsp;</em></strong>While consortia have the benefit of flexibility, they also have the burden of establishing their credentials as truly open organizations, due to the absence of any outside accrediting authority to vouch for their processes and policies. At the same time, ISO/IEC Joint Technical Committee 1 (JTC1), the main body for the adoption of IT standards for both ISO and IEC, has been as willing to accept as Publicly Available Standards, or through a similar program called the Fast Track process, standards that have been developed by all types of processes, from very accessible and open consortia with quite large memberships, such as OASIS, to others, such as ECMA, that have much smaller and less diverse memberships, and rules that permit existing members to vote on whether or not to accept new vendors into full voting membership, to single-vendor developed standards, such as Adobe's Portable Document Format, that may or may not have been the subject of a consortium vetting process at all. Once these specifications are accepted by JTC1, the obligation of the National Bodies of eligible members is to work towards adoption, regardless of the degree of industry input that went into the original creation of the specification in question. The resulting standards, if finally approved, all have equal approval status in the marketplace, regardless of their origins, because the scope of review is purely technical.<br /><br /></li>
					<li><strong><em><u>Process</u>:&nbsp;</em></strong>The current progress of DIS 29500, a document format standard introduced by ECMA to JTC1 via the Fast Track process and based upon Microsoft's OOXML specification, has been the subject of many complaints of process abuse in National Bodies throughout the world. These recent events highlight weaknesses in trust-based processes that are not usually subjected to such pressure. At the same time, the publicity that these events have attracted has also drawn attention to significant variations in the rules employed by National Bodies around the world, demonstrating that concepts of openness vary considerably. Many National Bodies, for example, do not make public the deliberations or votes of their non-elected members, thus denying citizens the ability to know how or why their nation voted as it did. Once again, the final result will be binary: either a specification will be approved or it will not.<br /><br /></li>
					<li><strong><em><u>IPR</u>:&nbsp;</em></strong>The traditional standards development model strikes a balance between the rights of patent owners, on the one hand, and standards implementers and end users, on the other. This balance generally disfavors, but does not prohibit, the inclusion of technology that, if implemented, would infringe upon patents, so long as the IPR is available to would be implementers on "reasonable and non-discriminatory," or RAND, terms. The result is that sometimes implementers must pay royalties or other fees to patent owners. Many participants in the ICT industry are becoming less tolerant of the need not only to pay patent fees, but to enter into multiple license agreements as well in order to implement a standard. Indeed, some ITC products, such as mobile devices, now implement so many different technologies and capabilities (and therefore standards) that the theoretical economic burden of obtaining necessary license rights, if most such standards bore royalty obligations, would exceed the value to end users of the device many times over. While patent pools alleviate this burden in some cases, the creation and operation of such tools adds complexity, and the creation of a pool does not invariably result in the capture of all patent claims. Finally, some technology areas, such as the Web, have evolved strong royalty-free cultures that have been instrumental in achieving their explosive success. Similarly, open source software under most commonly utilized licenses could not implement many RAND standards at all. Consortia such as the W3C, OASIS and others have amended their IPR policies in such a way as to ensure, to the greatest extent possible, the creation of royalty free standards that can be implemented in open source software, either in every case (as with the W3C) or on an elective working group by working group basis (as with OASIS). Currently, a similar policy would violate the accrediting rules of ANSI.<br /><br /></li>
					<li><strong><em><u>Disclosure</u>:&nbsp;</em></strong>A related problem involves when, and to what degree of detail, the existence of patent claims and related licensing terms must be disclosed during the standard setting process. Some multinational IT companies have advocated that standards organizations should be free to permit or require early and detailed disclosure of patent claims and terms, in order to allow organizations to approve standards that can be implemented with the least bureaucratic and economic cost. In pursuit of that goal, they have urged antitrust regulators in the U.S. (with success) to clarify the pro-competitive potential for such "ex ante" disclosure, and also lobbied IT standards organizations (once more with success), such as VITA and IEEE, to amend their policies to require or permit such disclosure, respectively.<br /><br /></li>
					<li><strong><em><u>Free trade</u>:&nbsp;</em></strong>Currently, most ITC patents are owned by major, multinational corporations headquartered in the developed world, while most ITC products are manufactured in developing countries that are patent-poor. Many such products are built to multiple standards, some of which require manufacturers to make patent license payments, which can be substantial. The result is that the vendors based in developed nations reap large profit margins on such products, while those in developing nations realize very small ones. A predictable result is that China is increasingly creating "home grown" standards that reverse the patent payment stream. A final and equally predictable result is the existence of trade disputes over such standards, based upon the Agreement on Technical Barriers to Trade under the WTO. Such disputes can be expected to increase and sustain until vendors based in emerging nations become as adept at participating in standards development activities as their competitors in developed nations, and until their patent portfolios swell sufficiently in size to give them equal negotiating power.<br /><br /></li>
					<li><strong><em><u>Other criteria</u>:&nbsp;</em></strong>While some standards can be created expressly to achieve societal goals, such as energy efficiency, the process of global standards approval itself is most often values neutral.<sup>1</sup> As a result, while individual organizations may create programs to certify that products are energy efficient, or that the economics of coffee production have been fair at the grower level, or that the wood in a piece of furniture has been harvested on a sustainable basis, additional areas of concern such as these are not currently addressed within the existing global standards bodies in a systemic fashion.<br /><br /></li>
				</ol>
				<p><strong><em>Opportunities:&nbsp;</em></strong>At the same time, there are real opportunities that could be taken advantage of if a more multi-faceted global standards infrastructure were to be put in place. These favorable results could be achieved through free market, rather than regulatory, forces, using the very substantial power of government procurement, which has the ability to influence the standards-based behavior of major ITC vendors.<sup>2</sup></p>
				<p>This could be achieved through the following devices:</p>
				<ol>
					<li><strong><em><u>Process improvement</u>:&nbsp;</em></strong>It is not uncommon today for there to be more than one globally-approved standard to address the same basic task. While the needless duplication of standards is an issue in itself, the situation is not likely to be resolved at any time in the near future. Moreover, while standards may overlap for some purposes, there may be differences in market needs and applications that make one alternative uniquely suited for some purposes and not others, further increasing the incidence of duplication.<sup>3</sup> The result is that an implementer may have a choice between two globally approved standards, and no policy reason or statutory imperative to choose one over the other.<br /><br />At the same time, one of the two alternatives may have been the product of a very open industry collaborative effort, while the other may be essentially a re-packaged, single-vendor specification contributed by a company with a monopoly position in the relevant market, and this power may be perpetuated through wide uptake of the standard. If an "openness rating system" existed, a government would have an incentive to adopt a policy that directed its agencies to preferentially choose products based upon the standard that was created through the more open process. The result would be that vendors would have a greater incentive to direct their standards efforts to organizations that received minimum grades, and the overall process quality of widely used standards would increase.<br /><br /></li>
					<li><strong><em><u>Social criteria</u>:&nbsp;</em></strong>Currently consortium standards are almost uniformly values-neutral, because with rare exceptions (such as the W3C), consortia do not include any degree of social consciousness in their charters. Since there is no way for a given organization to demonstrate that it meets social goals, there is less incentive to craft standards that achieve other than technical objectives. With both the reality as well as the intractability of global warming now established, it is clear that there will be no single solution, magic bullet approach to slowing down, let alone avoiding a significant degree of climate change. As a result, a multiplicity of solutions will be needed, one of which will be energy efficiency, both in production of products as well as in the design of products themselves. A readily available set of standards, conjoined with an easily satisfied conformity testing process and clear purchasing preferences on the part of government and other purchasers would once again provide both the tools, as well as the market incentives, for creating more environmentally responsible standards where there is a technical opportunity to do so.<br /><br /></li>
					<li><strong><em><u>IPR approach</u>:&nbsp;</em></strong>A clear ranking of IPR process and rules alternatives, and a means of accrediting compliance with these options, would enable governments to steer the market towards standards that were not only available on a RAND basis, but free as well. This would have the effect of lowering the prospect for trade disputes, particularly if the WTO were to amend the Agreement on Technical Barriers to Trade to require international use of only standards that were royalty-free. Consortia that adopted rules that were highly intolerant of other than FRAND (free, as well as reasonable and non-discriminatory) patent assertions should therefore attract the participation of vendors from developing countries, because the standards issued by such organizations could be implemented on a more level playing field than those created by royalty-tolerant organizations.<br /><br /></li>
					<li><strong><em><u>Neutrality and representation</u>:&nbsp;</em></strong>Development processes can be lenient or strict, with the latter incurring costs in bureaucracy, time and effort. A strict process would be unduly burdensome in most cases, but could be valuable in others, to ensure vendor neutrality and the avoidance of undue influence. Similarly, those involved in a process can be self-selecting and narrow, or recruited and broadly representative. Currently there is a bias towards pursuing some standards efforts through accredited bodies due to their commitment to participation by all types of stakeholders.<sup>4</sup> However, even for these organizations, actual breadth of responsibility may be low, due to lack of interest on the part of (for example) end users, and the burdens of participation. Nonetheless, with the advent of the Web, there is the opportunity for much greater involvement on at least a comment basis by a broader range of stakeholders, and those consortia that put processes and mechanisms in place to enable such input could be recognized, giving them a greater ability to compete for standards work in areas such as public safety and public health.<br /><br /></li>
				</ol>
				<p><strong>II&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Creating the Infrastructure</strong></p>
				<p>As can be seen from the above, there is a wide range of practices and results that could potentially be impacted by the exercise of government purchasing, as compared to regulatory action. When socially conscious consumer purchasing is added into the mix in areas such as energy conservation, the cumulative effect on standards development practices could be substantial &mdash; assuming that there was an infrastructure in place that provided standards by which consortia could be judged, and a means to audit compliance with those standards. Such a structure might be constructed as follows:</p>
				<p><strong><em>A new "Big I":&nbsp;</em></strong>A new global organization would be needed that would be oriented towards consortia, but available to all interested standard settings organizations. It would have an appropriate name, such as the International Standardization Foundation (ISF). The ISF would have a balanced governing council of relevant stakeholders: governments, vendors and NGOs, among others, and might have additional Advisory Boards and committees made up of individual categories of stakeholders. It would perform and host a number of functions:</p>
				<ol>
					<li><strong><em><u>Standard setting</u>:&nbsp;</em></strong>The ISF would host committees formed to create specific standards within its area of competence, and maintain those standards and committees on an ongoing basis.<br /><br /></li>
					<li><strong><em><u>Charter accrediting bodies</u>:&nbsp;</em></strong>The ISF would develop criteria for accrediting bodies, and charter suitable organizations to perform that function on a regional basis.<br /><br /></li>
					<li><strong><em><u>Registry</u>:&nbsp;</em></strong>The ISF would maintain a master registry of the certification status of audited organizations.<br /><br /></li>
					<li><strong><em><u>Liaison</u>:&nbsp;</em></strong>The ISF would maintain appropriate liaison relationships with existing global standards bodies, UN agencies, and other organizations relevant to its mission.<br /><br /></li>
					<li><strong><em><u>Education</u>:&nbsp;</em></strong>The ISF would host committees focusing on other relevant initiatives, such as best practices.<br /><br /></li>
					<li><strong><em><u>Advocacy</u>:&nbsp;</em></strong>The ISF could, if desired by its members, take public positions on issues such as patent reform, and draft and distribute white papers and sponsored research.<br /><br /></li>
					<li><strong><em><u>Branding</u>:&nbsp;</em></strong> The ISF would own and license certification marks in support of its mission. Standards organizations would be entitled to use these logos to indicate their certification, and products compliant with standards created under certified programs could also bear logos where advantageous (e.g., in the case of energy efficiency).<br /><br /></li>
					<li><strong><em><u>Communication</u>:&nbsp;</em></strong> Unlike accredited organizations, consortia do not have a forum in which to gather to discuss matters of common concern, trade information and best practices, and receive training.<br /><br /></li>
				</ol>
				<p><strong><em>New standards:&nbsp;</em></strong>ISF committees would create both institutional and process standards, including the following:</p>
				<ol>
					<li><strong><em><u>Openness</u>:&nbsp;</em></strong>Standards to assess processes regarding eligibility, reasonability of membership costs by type of stakeholder for technical voting membership, transparency of process, and similar practices and policy issues.<br /><br /></li>
					<li><strong><em><u>IPR</u>:&nbsp;</em></strong>Alternate standards that may be chosen depending upon the goals of the organization, differentiating on key features such as <em>ex ante</em> disclosure, FRAND vs. RAND, and compatibility with open source licenses.<br /><br /></li>
					<li><strong><em><u>Social criteria</u>:&nbsp;</em></strong>Energy efficiency, carbon output, sustainability, FRAND, etc.<br /><br /></li>
				</ol>
				<p><strong><em>Accrediting bodies:&nbsp;</em></strong>Accrediting organizations would be created (or existing organizations accredited) to audit compliance with the new standards. In order to avoid the appearance of any bias towards a single country or region, there should at minimum be three accrediting organization: one in North America, one in Europe, and one in Asia. Already existing organizations (e.g., ANSI in North America) that already possess auditing expertise would be eligible to become accredited to fulfill this role.</p>
				<p><strong>III&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Desired Outcomes</strong></p>
				<p>If such a system were in place today and governments demonstrated a procurement preference for standards produced by well-rated organizations, what positive changes might we expect to see?</p>
				<p><strong><em><u>Existing organizations</u>:&nbsp;</em></strong>Once a third party means of differentiating organizations was available, existing well-run, open organizations willing to make minor changes to their processes would logically seek to gain recognition of their superior status. Those that were poorly run, maintained closed membership policies, or used IPR policies likely to lead to unpredictable results would be motivated to choose between revamping their operations or see their reputations, membership, and standards uptake suffer accordingly.</p>
				<p><strong><em><u>New organizations</u>:&nbsp;</em></strong>New organizations as they were formed would have an incentive to structure themselves based upon the best practices and certification guidelines issued by the ISF. Potential members would be able to make more informed decisions about whether or not to join a new organization, depending upon whether it had, or had not, formed itself with an eye towards achieving certification.</p>
				<p><strong><em><u>Developing countries</u>:&nbsp;</em></strong>Vendors in developing countries would logically gravitate towards those organizations that were FRAND and "open" certified, because the standards developed by such organizations would be more likely to offer a level playing field. Governments of developing countries would be less likely to launch "home grown" standards efforts in competition with global standards, where new efforts were launched in FRAND/Open organizations, rather than RAND organizations.</p>
				<p><strong><em><u>Interoperation with other "I"s</u>:&nbsp;</em></strong>Certification by the ISF would complement, rather than compete, with preexisting standards organizations, because the ISF would certify <em>standards organizations</em>, and not <em>standards</em>. The major difference that existing organizations might see would be that the progress of standards from certified organizations through their own approval processes would be smoother and swifter, as a result of their higher quality and lower likelihood of undue influence by a single vendor or group of vendors.</p>
				<p><strong><em><u>Government procurement</u>:&nbsp;</em></strong>Interested governments would have a richer, multidimensional set of criteria to employ in order to motivate, rather than regulate, standards development, permitting governments (for example) to promote or facilitate openness, open source software development, energy efficiency, sustainability, free trade, and other worthy goals.</p>
				<p><strong><em><u>Social impact</u>:&nbsp;</em></strong>Vendors would have new incentives to create socially beneficial standards, and consumers would have new ways to exercise social awareness by purchasing certification-branded products.</p>
				<p><strong>IV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Summary</strong></p>
				<p>ICT products and services, and therefore ICT standards, are becoming increasingly essential to every facet of modern life, from health and safety to the operations of government, education, commerce, the financial markets and much more. In consequence, optimizing the infrastructure that creates these standards should be a matter of common concern. But without standards to define improvements optimization would be difficult. Similarly, without ways to measure progress and market incentives to reward it, there will be no motivation for standards organizations and their vendor members to upgrade their processes, or to align their goals with those of society.</p>
				<p>Today there is no mechanism available to measure traditional standards organizations in areas such as openness in other than a binary fashion, and in the case of consortia, there are no mechanisms or metrics of any kind to either measure or motivate their processes, policies or standards, other than to the extent that they can offer their final standards for approval by organizations such as ISO and the IEC.</p>
				<p>Notwithstanding this lack of tools, the evolutionary experience of consortia over the last twenty years has been remarkable, not only when measured by the number of organizations founded and standards created and implemented, but also by the creativity displayed in devising new structures and solutions.</p>
				<p>While it would be counterproductive to inhibit future evolution and innovation, it would be beneficial to build vertically upon the horizontal structure already in existence in order to maximize the value that consortia continue to create. The same structure developed to serve consortium needs could be of equal utility to traditional standards organizations seeking to differentiate themselves and the standards they create. Less directly, a new "I" could provide a healthy dose of competition to existing global standards organizations, which have had little incentive to innovate or streamline their operations for some time.</p>
				<p>Creating a new global organization and accrediting a handful of existing standards bodies to serve as regional accrediting organizations would be neither a difficult nor an expensive task, and the ongoing maintenance of such a body would not be burdensome. As with most standards organizations, the costs could be borne primarily by the vendors that would make the greatest use of its services, and that could hope to gain increased sales of goods and services benefited by standards that were more widely and swiftly adopted.</p>
				<p>Viewed from a historical perspective that takes into account both the evolution of the existing global standards bodies as well as the explosive phenomenon of consortium formation, it is clear that a new global body could be useful, and perhaps has been needed for some time. It is to be hoped that an effort to assess interest in the formation of such an organization may be mounted sooner rather than later, for the benefit of end-users, vendors, and indeed society at large.</p>
				<p class="center">Copyright 2007 Andrew Updegrove</p>
				<p>End Notes</p>
				<p><sup>1&nbsp;</sup>There are exceptions. In recent years, ISO has undertaken the creation of standards for corporate responsibility.</p>
				<p><sup>2&nbsp;</sup>A current demonstration of this dynamic is the submission of Microsoft of its OOXML format to ECMA, and then to ISO/IEC JTC1, after OASIS secured adoption of its OpenDocument Format by the same body.</p>
				<p><sup>3&nbsp;</sup>Indeed, when new technologies are evolving rapidly and product cycles are short, it can be useful for a standards "competition" to result, allowing both products and standards to evolve in parallel, rather than in sequence, with market processes determining which standard "wins."</p>
				<p><sup>4&nbsp;</sup>For example, the U.S. Congress chartered ANSI, and not one of the many existing IT consortia, to manage the process of creating new standards for electronic health records, in part due to the importance of such work to ordinary citizens, and the desire to ensure that those who would be affected by the deliverables of this initiative would have an opportunity to be heard.</p>

