				<!-- ******************* -->
				<!--   FEATURE ARTICLE   -->
				<!-- ******************* -->
				<h3>A Proposal to Recognize the Special Status of<br />"Civil ICT Standards"</h3>
				<p class="center"><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></p>
				<blockquote class="openingquote"><em><strong>Abstract:&nbsp;</strong>In modern times, civil rights have enjoyed increasing protection, although the exact balance between the rights of the individual and those of society as a whole has been found at different points at different times, and among different societies.  Advances in technology, beginning with the printing press, have played a role in this process.  Today, civil rights such as freedom of speech, freedom of assembly, and the ability to fully interact with government are increasingly being exercised through the use of information and communications technology (ICT), rather than in person.  As this process accelerates, attention must be paid to how such "Civil ICT Rights" can be exercised, so that they are not compromised, diminished, or only selectively, rather than universally, available.  Special attention will need to be paid to the development and adoption of technical standards as well, because they will play an essential role in protecting Civil ICT Rights.  In this article, I make the case for recognizing the existence and importance of what I call "Civil ICT Standards," and argue that the development of Civil ICT Standards, in contrast to purely technical standards, requires more stringent rules and processes, so that our Civil ICT Rights can be protected and preserved.</em></blockquote>
				<p><strong><em>Introduction:&nbsp;</em></strong>The rise of civil society has been enabled by developments in diverse disciplines, from the mastery of agriculture (which made life in more complex, settled communities possible) to the evolution of systems of weights and measures, to facilitate business exchanges.   Many of these innovations were permanent, in the sense that once their benefits were realized, further development came in the form of increasing refinement and expansion of the original concepts, in processes that continue to this day.</p>
				<p>But other, equally important concepts were based upon assumptions that were philosophical, or class based, or otherwise susceptible to subjective forces.  Chief among them, from the standpoint of importance to the stability of society, were systems of laws and of governance, because while each was essential, its implementation could be, and has been, highly variable.</p>
				<p>For example:  inherent in both laws and governmental systems is the concept of balancing the rights of individuals with the needs of society as a whole.  With the rise of more hierarchical societies, consolidation of valuable property in fewer hands, and the development of governance systems based upon kingship, the rights assigned to the classes at the bottom of the pyramid radically declined from those that they had enjoyed in tribal societies led by consensus-acknowledged leaders.  The laws created by the elites, not surprisingly, also reflected this reality,  assigning more rights to the classes that created the laws and had the power to enforce them.</p>
				<div class="calloutright">
					<p>Much as a constitution or bill of rights establishes and balances the basic rights of an individual in civil society, standards codify the points where proprietary technologies touch each other, and where the passage of information is negotiated.</p>
				</div>
				<p>Other societies (notably the Greeks and, derivatively, the Romans) evolved legal systems that acknowledged greater rights in the individual &mdash; or at least those individuals that had the good luck to be born into the ranks of citizens of the state.   Only in very recent times have concepts such as universal human rights and the democratic selection of leaders by all, regardless of gender, education, or social status, achieved the same level of acceptance that they enjoyed in many hunter-gatherer societies.</p>
				<p>Striking the desired (and subjective) balance between the rights of the individual (to do as she pleases) with the rights of the state (to ensure the welfare of all individuals as a whole), however, has been highly variable from nation to nation.  This balancing has been periodically adjusted and recorded in what have commonly come to be referred to as "Bills of Rights."  These watershed documents include (in the Western tradition) such important agreements as the English Magna Carta (1215), the French Declaration of the Rights of Man and of the Citizen (1789), and the United States Bill of Rights (which amended the United States Constitution, when ratified in 1991).  Each of these documents augmented the rights of the individual at the expense of the state, while remaining aware of the importance of protecting society as well.</p>
				<p>While this trend has been largely linear across all societies over sufficiently meaningful periods of time, it has not been uniform among them.  The balancing of the rights of the individual in comparison to those of society has of course been artificially skewed towards the state (a more proper reference than "society," in this context) in authoritarian and totalitarian societies.  But even demonstrably "free" societies display significant variation today in law based upon the values and philosophies of their individual societies.  Those differences are manifested in various ways, such as the level of individual income taxation deemed to be acceptable, the legal test adopted to constitute the libel of public officials in the press, whether or not an individual can display evidence of religious association, and what an individual can and cannot do on their own private property.</p>
				<p>The ability to enjoy individual rights in modern times has also benefited from, as well as become dependent upon, technological innovation.  The concept of freedom of speech, for example, gained far greater scope with the invention of the printing press, because ideas and positions could be much more widely disseminated by persons other than governmental or religious authorities.  Similarly, the right of assembly became ever more meaningful as transportation systems became more sophisticated, inexpensive and available.</p>
				<p>In more modern times, information technology, and then the Internet, has reshaped the exercise of many civil rights, from the right to vote (via various electronic, and not always foolproof, scanning and tabulating devices), to right to petition government (via the Internet), to the exercise of the freedoms of speech, freedom of assembly and freedom of religious expression &mdash; sometimes all at once &mdash; via an ever-expanding variety of information and communications technology (ICT) based channels.</p>
				<p>This extension of the exercise of human rights to ICT based platforms has occurred with a swiftness that is without precedent.  Indeed, a greater and greater percentage of the exercise of civil rights is accomplished via such means on (literally) a daily basis in developed nations, and the process may be even more dramatic in developing nations as "smartphones" and other inexpensive, mobile devices become deployed by the hundreds of millions in just the next few years.</p>
				<p>But just as a newspaper could historically be silenced by a court order or seizure of its offices by government action, or its voice muffled by overly restrictive laws, so also can a Web site be blocked, or the ability of an individual to interact with her government be restricted to only such technical means as that government chooses to support.</p>
				<p>As government and private interests each move increasingly to ITC platforms, the traditional means of exercising valued civil rights will gradually be eliminated.  Perhaps as a result of the speed with which this process is occurring, however, very little attention has been paid (other than in the context of voting) to the deficiencies that new virtual platforms, business models and governmental portals may have, as compared to their historical in-person and paper based analogues.  Only recently has the realization begun to dawn that, just as the lack of handicapped access to a polling station can deny the vote to someone with a physical handicap, so also can a government portal Web browser that does not support accessibility standards.</p>
				<p>Governments are now becoming more aware of such concerns, and beginning to look for ways in which the benefits of ICT can be adopted without sacrificing, or compromising, civil rights.  But they are also realizing that the new bottles into which this old wine is being poured are quite different in important but technically subtle respects, presenting new issues, and demanding competence in technology areas that are new and unfamiliar to them.  It is also leading them to examine whether activities that have to date been primarily within the domain of private industry may require government attention, oversight, or even regulation.</p>
				<p>This examination by government will once again involve rebalancing the rights of individuals with society.  More importantly, it will also require a three-way rebalancing of the rights of commercial interests with those of individuals and society as a whole.  To the extent that this process does not occur organically in the private sector, governments will need to act to bring about behavior deemed to be desirable, either through direct action (i.e., through new regulations), or less coercively, by actions such as adopting preferences in government procurement.</p>
				<p>In this article, I will explore the impact of our increasing transformation from a society in which civil rights are exercised in person, to one in which those same rights can only be fully exercised electronically.  I suggest that this transition leads to the need to recognize a new concept that I will call "Civil ICT Rights."  More specifically, I will describe the increasingly crucial role that certain ICT technical standards will play in determining whether or not we are able to fully exercise our Civil ICT Rights.  I will also identify this subset of standards, which I will refer to as "Civil ICT Standards."  Finally, I will seek to demonstrate why I believe that the current standard setting infrastructure is inadequate to reliably create Civil ICT Standards of a quality and openness that I believe are essential to protect our increasingly important Civil ICT Rights.</p>
				<p><strong>I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Digitization of Civil Rights</strong></p>
				<p>We are entering an era in which IT technology is to society as earlier very different modalities were to human rights.  In this new interconnected world, virtually every civic, commercial, and expressive human activity will be fully or partially exercisable only via the Internet, the Web and the applications that are resident on, or interface with, these resources.  And in the Third World, the ability to accelerate one's progress to true equality of opportunity will be mightily dependent on whether one has the financial and technical means to lay hold of this great equalizer.</p>
				<div class="calloutright">
					<p>This is where standards enter the picture, because standards are where policy and technology touch at the most intimate level.</p>
				</div>
				<p>Not surprisingly, with these new and wonderful technical possibilities come real risks and responsibilities.  In order to avoid the former and assume the latter, questions of social policy enter the picture, because where the unconstrained forces of the market place will lead may not be where the best interests of society will lie.</p>
				<p>In the dawn of the computer age, when only isolated mainframes lived in major corporations and research labs, such a concern barely existed, if at all.   But as the world becomes more interconnected, more virtual, and more dependent on ICT, public policy relating to ICT will become as important, if not more, than existing policies that relate to freedom of travel (often now being replaced by virtual experiences), freedom of speech (increasingly expressed on line), freedom of access (affordable broadband or otherwise, and suited to the needs of those with physical disabilities), and freedom to create (open versus closed systems, the ability to create mashups under Creative Commons licenses, and so on).</p>
				<p>This is where standards enter the picture, because standards are where policy and technology touch at the most intimate level.</p>
				<p><strong><em>The emergence of Civil ICT Rights:</em></strong> Much as a constitution or bill of rights establishes and balances the basic rights of an individual in civil society, standards codify the points where proprietary technologies touch each other, and where the passage of information is negotiated.</p>
				<p>In this way, standards can protect &mdash; or not &mdash; the rights of the individual to fully participate in the highly technical environment into which the world is now evolving.  Among other rights, standards can guarantee:</p>
				<ol>
					<li>That any citizen can use any product or service, proprietary or open, that she desires when interacting with her government.<br /><br /></li>
					<li>That any citizen can use any product or service when interacting with any other citizen, and to exercise every civil right.<br /><br /></li>
					<li>That any entrepreneur can have equal access to marketplace opportunities at the technical, standards-mediated level, independent of the market power of existing incumbents.<br /><br /></li>
					<li>That any person, advantaged or disadvantaged, and anywhere in the world, can have equal access to the Internet and the Web in the most available and inexpensive method possible.<br /><br /></li>
					<li>That any owner of data can have the freedom to create, store, and move that data anywhere, any time, throughout her lifetime, without risk of capture, abandonment or loss due to dependence upon a single vendor.</li>
				</ol>				
				<p>We can, therefore, aptly refer to such technology-enabled &mdash; and therefore also technologically vulnerable &mdash; rights as Civil ICT Rights.  Having recognized this vulnerability, we must also pause a moment to ask: what will life be like in the future if Civil ICT Rights are not protected, as paper and other fixed media disappear, as information becomes available exclusively on line, and as history itself becomes hostage to technology?</p>
				<p><strong>II&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Vulnerability of Civil ICT Rights</strong></p>
				<p><strong><em>The document format test case:<sup>1</sup></em></strong> On March 29, the final step in the process whereby a document format designated as DIS 29500 in ISO/IEC JTC1, the <strong><em>de jure</em></strong>  standards committee within which such technology standards are considered, came to a close.  DIS 29500 is based upon the OfficeOpen XML (OOXML) formats developed by Microsoft for implementation in Office 2007, the significantly updated version of its flagship office productivity software package.  The specification for these formats had earlier been submitted by Microsoft to a standards body called Ecma, which in turn revised, approved, and submitted the resulting standard (now called Ecma 376) to JTC 1 under what is referred to as the "Fast Track" process.</p>
				<p>What ensued has been the most hotly contested standards battle in recent memory, but for more than just the usual commercial reasons.  At the factual core of the issue is the fact that another document format, earlier developed by the Organization for the Advancement of Structured Information Systems (OASIS), and popularly known as the Open Document Format (ODF), had already been submitted to, and approved by the same joint committee of ISO/IEC.</p>
				<p>The contest between ODF and OOXML has been extensively reported in countless articles, interviews and blog posts from around the world.  Supporters of OOXML point to the fact that Microsoft's historically closed product architecture is now more open, and that developers can now more easily, and on a more level playing field, develop products that interoperate with Office.  They can also develop new stand alone products that utilize OOXML independently.</p>
				<p>Opponents of OOXML point to the fact that ODF had already been approved by ISO/IEC JTC1 as ISO/IEC 26300, that ODF is already implemented in multiple proprietary, as well as free, open source office suites, and that OOXML is not fully implemented in even one product (Office 2007 will need to be revised to comply with the final version of DIS 29500).  They also contend that its primary use will be to perpetuate the dominance of a single vendor, that Ecma 376 was deeply flawed when submitted to JTC1, that the Fast Track process was inadequate to address the many flaws identified in the comments submitted, and that the consideration and voting processes that followed in many National Bodies were marred by alleged misconduct intended to sway national votes in favor of approval (Microsoft has said that it believes that opponents of OOXML, and in particular IBM, engaged in similar conduct).</p>
				<p>At minimum, the following facts would be agreed upon by both sides.  As initially submitted to JTC1, Ecma 376 comprised over 6,000 pages.  Objections raised during an initial one month "contradictions" period were deemed not to require action, while in the five month examination and voting period that followed, some 1,100 separate comments were submitted by many of the 87 countries that participated in the evaluation of OOXML.  Irregularities were also alleged in many countries, including "stacking" of various committees with employees or business partners of individual companies.  In one case (Sweden), Microsoft admitted that an employee had offered to compensate companies indirectly (through marketing incentives) for the cost of joining the committee entitled to vote on OOXML.<sup>2</sup></p>
				<p>At the end of the five month voting period, OOXML failed to receive sufficient votes to be approved.  Under established rules, Ecma then created a document that proposed resolutions to the comments submitted during the voting period, either by finding them unnecessary to address, or by proposing a suggested remedy.  That document ran to over 2,300 pages.  A one-week "Ballot Resolution Meeting" (BRM) was held to consider the c. 1,100 comments (less than 200 of which were non-controversial typographical corrections and the like) in Geneva, Switzerland, from February 25 &mdash; 29, 2008.  At that meeting, only a small percentage of the substantive, proposed resolutions were fully discussed and voted upon.  For lack of time, the remainder were addressed by allowing each participating delegation to vote to approve, disapprove or abstain on any individual resolution, while assigning a default position (choosing among the same positions) for any that it did not specifically address.</p>
				<p>Once more, there was serious disagreement over the results.  Microsoft and other OOXML supporters pointed to the fact that OOXML was now significantly improved from the original specification, and that any interested party could participate in the further evolution of the originally proprietary specification.  Opponents contended that OOXML still contained many serious flaws, that the Fast Track process, and particularly the BRM, had not applied the same level of quality assurance that had historically been followed applied in ISO/IEC JTC1, and that irregularities had once again occurred when the National Bodies considered whether or not to change their original votes.</p>
				<p>While the final vote has not been announced as of this writing,  a sufficient number of National Bodies are known to have changed their votes to approve OOXML &mdash; provided that a sufficient number of thus far-unannounced votes have switched in the other direction.  To complicate matters, it appears certain that multiple challenges might be brought to the vote in individual National Bodies (Norway has already requested that its own vote be disregarded until an internal investigation is complete), that a review of the entire process by ISO/IEC would be demanded by some, and that many were left with the opinion that the historically collegial <em>de jure</em> process had proven to be inadequate to the very significant commercial pressures that had been brought to bear upon it, from beginning to end during the Fast Track process.</p>
				<p><strong><em>Why open document formats matter:</em></strong> Had this been a simple standards war in the grand tradition (and there have been many bitter contests in the past), the news coverage would have been far more limited, and the conflict could be expected to drop quickly from public sight.  But a number of factors distinguish this still ongoing standards war from its predecessors.  Within those factors can be found the attributes that distinguish an important Civil ICT Standard from its purely technical brethren.</p>
				<p>Those factors include the following:</p>
				<ol>
					<li><strong><em><u>Access</u>:</em></strong> Early on, it was realized that electronic documents are far more at risk to loss over time than paper records, and that these risks include the rapid passing of a format into obsolescence, just as audio formats (eight track, cassette, CD and so on) have passed out of common use with increasing rapidity.  Given the need for easy access to text records over extremely long periods of time, governments have come to grasp the importance of adopting a document format standard that would prove to be widely adopted and be easy to maintain (and therefore likely to be maintained) over similarly long periods of time.<br /><br /></li>
					<li><strong><em><u>Accessibility</u>:</em></strong> Public awareness of the open document format contest began in August of 2005, when the Information Technology Department (ITD) of the Commonwealth of Massachusetts announced that it would adopt procurement guidelines that called for purchasing only ODF-compliant office productivity products.  Because Microsoft had announced that it would not support ODF, this would mean replacing as many as 50,000 copies of Office by an initially planned deadline of January 1, 2007.  The ITD's announcement brought to light the question of whether ODF-compliant products were as accessible to those with disabilities as Office, which is supported by a variety of third-party software products that augment its accessibility.  This was particularly important, because governments have gone to greater lengths than most private businesses to accommodate, and hire, those with disabilities.  In fact, it was found that ODF products were not as accessible at that time.  In response, both OASIS and many of the proprietary and open source developers of ODF compliant products accelerated their efforts to eliminate the gap.<br /><br /></li>
					<li><strong><em><u>Competitive concerns</u>:</em></strong> Microsoft Office is hugely dominant in the marketplace today.  Adopting a format that provided the basis for wide adoption in a way that did not provide a special advantage to Microsoft, and then directing government purchasing power towards products implementing that standard, could introduce incentives to the marketplace that could (and already has) reintroduced competitiveness into an important market niche where it has been notably absent for almost twenty years.<br /><br /></li>
					<li><strong><em><u>Convergence and broadening of "openness" concepts</u>:</em></strong> The number of people supporting the concept of free, open source software (FOSS, or FLOSS, for free/libre open source software) has grown to be very large, and continues to grow rapidly, embracing not only software developers, but also others (technically sophisticated and otherwise) who believe in the freedoms that FLOSS can enable.  At the same time, popular concepts and methods of achieving "openness" have already broadened, most significantly to involve content as well.  As one example of this trend, the amount of text, photo, video and audio content now being made available under the various licenses created (in many languages) by <a href="http://creativecommons.org/">CreativeCommons.org</a> is increasing geometrically.  And now, with the great debate over ODF and OOXML, public consciousness of the vital role that open standards can play (and therefore the importance of the process by which they are created) has risen greatly as well.<br /><br /></li>
					<li><strong><em><u>The right to choose</u>:</em></strong> As more and more citizens become technically sophisticated, their desire to obtain and use the technical tools of their choosing (including FLOSS) has increased dramatically, a trend that can be expected to increase.  More and more of these citizens do not wish to be told which tools they must purchase in order to interact with their own government.<br /><br /></li>
				</ol>
				<p>The result of this convergence is that a significant number of legislators and citizens came to recognize, at least in this instance, that whatever standard becomes widely adopted will have a different sort of impact upon them than any that they have been aware of before.  This, in turn, focused their attention on how the standards development and adoption process operates, whose interests are primarily served along the way, and whether that process succeeded or failed in serving their own interests in the case of open document formats.</p>
				<p><strong><em>Developing a definition of Civil ICT Standards:</em></strong> Although no specific terms or criteria have thus far been used publicly to articulate why, and which, open document formats stand on a different plane from WiFi specifications, such a differentiation seems clear.  I would submit that the core difference is that such standards are essential to the electronic exercise of one or more civil rights, and hence the choice of the name "Civil ICT Standards" to describe them.</p>
				<p>Standards in this class today comprise only a small, but vitally significant percentage of all standards.  But they demand special attention in their selection and protection in their use, because their impact is both fundamental and far reaching.  And, since some standards (like document formats) are intended for very long term use, it is more than usually important to select them carefully.</p>
				<p>A number of existing Civil ICT Standards can already be readily identified.  By way of example, they include those that enable universal global access in native character sets (the Unicode) and the basic standards upon which the Internet and the Web are based.  In the future, Civil ICT Standards will include those that relate to health records, privacy, security, electronic voting, federated identity, and much more.  Over time, they will become both more numerous as well as more important.</p>
				<p><strong>III&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Moving Towards a Civil ICT Rights and Standards System</strong></p>
				<p><strong><em>Recognition:</em></strong> Before Civil ICT Standards are likely to be given special attention, their existence must become widely recognized.  The ODF-OOXML contest supplies a convenient litmus for assessing initial attitudes on this subject.</p>
				<p>For some, technical issues and the past proprietary practices of Microsoft either outweighed, or obscured the special characteristics of document formats.  A prominent example can be found in Patrick Durusau, the ISO/IEC Project Editor for ISO 26300 (ODF), who came out in favor of adoption of OOXML after the close of the BRM, focusing on the progress that had been made with the OOXML specification rather than on whether OOXML had had all of its technical imperfections resolved,<sup>3</sup> or whether it would lead to effective competition in the marketplace at all.<sup>4</sup>  From this point of view, the primary goal seems to be to negotiate better terms while continuing to live within an already existing ecosystem with a dominant vendor at its center.  Other OOXML proponents viewed public concerns over document formats as being simply a cover for aggressive tactics by Microsoft's rivals.<sup>5</sup></p>
				<p>There are many individuals around the world that would bridle at the implication that they have simply been the puppets of Microsoft's enemies.  For those that take this view, the successful vote to adopt OOXML was a step away from, rather than a way to advance towards, a future in which Civil ICT Rights are guaranteed.</p>
				<p><strong><em>Process controls:</em></strong> If a consensus arises around the concept that there is a separate class of standards that should enjoy special attention and protection because of a unique relationship to Civil ICT Rights, then the next step is to determine whether the existing standards development and adoption infrastructure is equal to that task.</p>
				<p>The first question that arises in that context is whether Civil ICT Standards should be under the control of government, the private sector, or in some manner shared.  At the one extreme, there is self-regulation by industry, and at the other there is legislation leading to government regulation.  But the former is subject to proprietary pressures and usually does not include meaningful participation by all stakeholders (especially end users), while the latter is slow, cumbersome, and still subject to lobbying by commercial interests.</p>
				<p>Already, there is a broad spectrum of practice in place, that extends from <em>de facto</em> standards developed by one or a few vendors, to  government regulations, with purely technical specifications being the subject matter in the former case, and standards relating to safety and public health falling more typically into the latter category.</p>
				<p>In between, there are many variations, from consortia, to the quasi-governmental ISO and IEC, in which participation is by National Bodies, to the ITU, a treaty organization in which participation is at the national government level.  Where along this continuum should authority over Civil ICT Standards come to rest?</p>
				<p>Given the speed with which technological advancement occurs, a case can be made for allowing Civil ICT Standards to continue to be developed by the existing consortia and accredited bodies in which they are now addressed.  However, as the ODF-OOXML experience has shown, that infrastructure at minimum needs to be "ruggedized" to withstand the onslaught that sometimes descends upon it when significant commercial interests are at stake.  And perhaps it needs to be more substantially overhauled as well, due to the fact that the tenets upon which its structure is based are not necessarily identical to those upon which Civil ICT Standards need to rely.</p>
				<p>The following are a few examples of concerns that arose in the course of the OOXML Fast Track process that are worth revisiting in this context:</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Quality:</em></strong> In the case of most standards, a poor job in development is likely to be followed by weak adoption.  However, this will not always be true.  In the case of OOXML, the relative success or failure of the Fast Track process to deliver a quality product will likely have little or no impact on uptake in products that form part of the Microsoft Office ecosystem, due to the pre-existing dominance of Office in the marketplace.  In the case of a purely technical standard, the consequences for society in general and the individual in particular for such a result may be low.  In the case of a Civil ICT Standard, however, the consequences could be far higher, and therefore, I would submit, the quality controls should be more stringent.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Influence:</em></strong> There have been many allegations of undue influence being asserted on those that cast votes in their respective National Bodies.  Whether or not you believe that a call from Steve Ballmer, the Chief Executive Officer of Microsoft, to the United States Secretary of Commerce to discuss the vote of the National Information and Standards Institute (NIST) as a member of the OOXML voting body, may conceivably be a matter of opinion.  But I would submit that the reported ability of a single Microsoft employee to block a vote by a National Body to disapprove OOXML represents a failure of the rules of that National Body to protect against the self-interested actions of a single vendor.<sup>6</sup>  While it is true that vendors often bring significant technical knowledge, and therefore value, to the standards development and adoption process, such an example indicates the need for additional rules to guard against the abuse of such rights of participation.</p>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;<strong><em>Transparency:</em></strong> Most governmental activities operate under rules of transparency to the public, in order to ensure that citizens are fully informed, and fully protected.  Nominally, the formal standards development process pays lip service to the same value.  However, in the breach, the rules are far different.  No one other than National Body delegates and representatives of Ecma and ISO were permitted to attend the BRM, and the audio record has not been made publicly available.  The only written minutes and record released are minimal in the extreme,  comprising only a few pages of text to reflect the activities of a full week of meetings.  Those who attended were also requested not to divulge what had transpired, although many declined to be bound by this request.<sup>7</sup> Even the proposed resolutions that were prepared by Ecma for consideration at the BRM were posted to a Website to which only limited National Body access was granted. Similar practices and rules abound in multiple National Bodies as well.</p>
				<p>While it is true that there are some valid reasons for the genesis of this practice (delegates from small vendors may rightly fear reprisals from large vendors upon whom they are dependent if they vote in the "wrong way"), such secrecy should be regarded as clearly incompatible with the creation and adoption of Civil ICT Standards.  Moreover, there are global consortia, such as OASIS (the developer of ODF), that have created hotly contested standards, and yet operate on a fully transparent basis, posting detailed minutes of all meetings to the public portion of its Web site, conducting all discussions in open electronic fora, and posting review drafts of all proposed standards for public comment prior to adoption.  Given the importance of transparency and the ability of organizations such as OASIS to conduct a successful process, greater transparency should clearly be required in the creation of Civil ICT Standards.</p>
				<p><strong><em>The role of government:</em></strong> There is ample evidence that the status that a standard can attain, and the value that certain purchases place on such credentials, can have a very substantial impact on the conduct of even the most dominant and powerful vendors in the world.  In the case of document formats, we have seen that the non-legislative action of a single US state &mdash; Massachusetts &mdash; dramatically accelerated the credibility of ODF, motivated enormous efforts on the part of many individual as well as commercial supporters to support that standard, and forced Microsoft to take open document formats far more seriously than it is likely to have done otherwise.  Increasing interest in the importance of document formats by other governments (and regulators), especially in Europe, has further motivated supporters of both formats, and brought about more movement by Microsoft.</p>
				<p>When governments commit to procure only software based upon truly open document formats implemented by multiple competing products, that promise tells both proprietary and open source developers that a sufficiently large market will exist to reward the substantial effort required to produce robust and compliant products.  Such governments have provided the first credible incentive for market participants to compete on the desktop in almost two decades.  This in turn has provided incentives to Microsoft to more aggressively innovate there as well, rather than simply seek to maintain its installed base while maximizing profits.  One need only look to the historical intervals between releases of a product such as Internet Explorer to see this predictable dynamic at work.</p>
				<p>During the ODF-OOXML contest, some OOXML proponents have contended that standards-based government procurement preferences and legislative requirements are in some way undesirable.  In fact, such actions by governments are entirely consistent with their role, as demonstrated by long-standing past practice.  In the United States, for example, government contractors alone must abide by a wide variety of rules that are intended to pursue social goals, such as encouraging minority hiring and other rules that require the preferential award of contracts to women and minority owned businesses.  The goal of each is to help historically disadvantaged classes of individuals gain equal access to good jobs, and to successfully launch businesses of their own.</p>
				<p>However, these salutary results can only be achieved if the standards that achieve the necessary status are worthy of the benefits that they can bring to society.  If that status becomes too easily available, then the legitimacy of the process is lost, as are the benefits that it could otherwise provide.</p>
				<p><strong>IV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Conclusions and Recommendations</strong></p>
				<p>If the existence and importance of Civil ICT Rights and Civil ICT Standards becomes recognized, then I believe that one, or a combination, of three avenues could be employed to protect the former, and properly develop the latter.</p>
				<p><strong><em>ISO/IEC/National Body Reform:</em></strong> In the wake of the ODF-OOXML contest, the existing de jure standards infrastructure would need to undergo a concerted and determined process of self-review, with the commitment to institute new rules to avoid a repeat of the OOXML experience just witnessed.  ISO 9001 might indeed serve as an excellent and apt reference point in this process.  It should not be necessary to change the rules for standards those that continue to be developed and discussed in less contentious settings, given that a serious failure of the system is a rare exception rather than the rule.<sup>8</sup></p>
				<p>The following are samples of nominally intrusive rules that could be considered for use where Civil ICT Standards are involved:</p>
				<ol>
					<li>Set more stringent rules for standards that hope to receive preference in government procurement.<br /><br /></li>
					<li>Provide a mechanism whereby interested parties can assert Civil ICT Standard status for a given type of specification, for determination by a neutral, in the case of disagreement.<br /><br /></li>
					<li>Provide for "circuit breakers" that can interrupt the normal process and appeal for a determination of the issue at hand, when warranted and necessary.  A right to have appealed the appropriateness of the Fast Track process for a 6000 page specification at the very beginning would have avoided many of the issues and less than desirable results that followed.<br /><br /></li>
					<li>Require more than one fully compliant implementation of a proposed Civil ICT Standard before it can be submitted for consideration.<br /><br /></li>
					<li>Utilize a more stringent set of rules and requirements relating to transparency and avoidance of undue influence, at both the National Body as well as the ISO/IEC level</li>
				</ol>
				<p><strong><em>Form a new global body:</em></strong> In a previous issue of <em>Standards Today</em><sup>9</sup>, I reviewed areas of weakness in the existing infrastructure for developing ICT standards, and made a proposal for a new type of entity that would not replace either the existing consortium or de jure standards development systems.  Instead, it would create standards by which standard setting organizations of both types (SSOs) could be judged (and, indeed, ISO and IEC as well).  Those standards could address the quality, openness, broadness of representation, and other relevant attributes of SSOs, thus providing a more rational basis whereby their work product could be judged by governments, customers, and communities of interest.  SSOs and standards could also be rated on other criteria, such as the environmental impact of their standards.</p>
				<p>Once such standards existed, market forces could be expected to assert themselves, with governments and some customers giving greater respect to standards from more highly rated SSOs, and to standards that had met openness, representation, and other relevant process criteria.  Over time, SSOs in general could be expected to improve, in order to gain access to the best available work (SSOs have competitors, too), and to ensure the widest uptake of their standards.  Indeed, there are hundreds of standards bodies of this type already in existence, certifying the credentials of all manner of professionals and the ethics, processes and other activities of businesses of all types.  Needless to say, specifications would only be eligible for adoption by ISO or IEC as Civil ICT Standards if they had been created by organizations that satisfied the appropriate ratings.</p>
				<p><strong><em>Involve government:</em></strong> Unless one of the two alternatives suggested above, or some other equally efficacious method, is applied by the private sector, there will be no other way to influence the marketplace other than by government action.  And, in fact, this has already begun to occur, through the exercise of the very significant procurement power of some governments.  It was, after all, the decision of one small commonwealth in the United States that at initially ignited the document format standards war.  And irrespective of the adoption of OOXML, it can be expected that citizens in some cases may advocate for, and governments in other cases may prefer, to implement ODF rather than OOXML for a variety of reasons that relate to how the OOXML process was conducted, and in order to influence future activities in the marketplace.</p>
				<p>Of course, if governments become convinced that Civil ICT Rights are as important as historical civil rights, then governments may become just as involved in their creation, adoption, and enforcement as their constitutional analogs.  If governments do come to such a conclusion and the private sector has not taken up the challenge to protect such rights through its own action, then they will have to cope with the regulatory consequences.</p>
				<p><strong><em>Summary:</em></strong> I am convinced that today we have a problem that requires attention.  Although Microsoft might have hoped otherwise, OOXML has provided clear evidence of the existence of a dangerous inability on the part of the traditional standard setting infrastructure to satisfactorily address Civil ICT Standards in the face of fierce commercial actions.  This flaw in the existing system is in urgent need for a solution.</p>
				<p>The fresh memory of the contentious, severely flawed, and very publicly reported process that has just ended should assist us by providing the incentives needed to begin to grapple with the difficult issues that stand between where we are today, and where we need to be.  I believe that it is very important that we do so successfully, and soon, because the speed of technological innovation and adoption is far outrunning the recognition and protective of Civil ICT Rights and Civil ICT Standards.</p>
				<p>Nor should it fail to be mentioned that the stakes for society are even higher than I have thus far suggested, because the questions raised in the context of Civil ICT Standards extend beyond the field of ICT.  Standards of equal importance are urgently needed in areas such as global warming, and will tell us what we can and cannot do except at our peril, how we will determine whether we are winning or losing that battle, and how we can protect our environment from further degradation.  Unless the private sector adopts higher standards and more rigorous processes of its own, government will be forced to intercede here as well &mdash; but only after much long term damage has already been done.</p>
				<p>So it is we see that what happened in ISO/IEC JTC1 and in National Bodies around the world was about far more than whether Microsoft would win and IBM and its allies lose, or vis-versa, even if that has been the immediate and superficial result.  In a larger sense, the battle that has just ended has been about fundamental human rights, about not only seizing but also securing the opportunities of the future for the benefit of all.  Only by thinking clearly and deeply about these larger issues will we be able to adapt the practices of the past to meet the challenges of a future that has already arrived, whether we wish to realize it or not.</p>
				<p class="center">Copyright 2008 Andrew Updegrove</p>
				<p>End Notes</p>
				<p><sup>1</sup> It should be noted that while the following summary is intended to be objective, I have been a consistent and vocal advocate for denying ISO/IEC JTC1 adoption of OOXML, for reasons that include my belief that approval will support continued domination of the desktop by a single vendor, thereby diminishing the competition and innovation that widespread adoption of ODF may bring, the inappropriateness of the Fast Track process for so large and initially flawed a specification, leading to low quality in the final result, the fact that approval will reward Microsoft's continuing refusal to support ODF natively, proposing its own standard instead, and the likelihood that approval under such circumstances will encourage, rather than discourage, similar conduct by Microsoft and other vendors in the future.</p>
				<p><sup>2</sup> In February, the Wall Street Journal reported that European regulators were inquiring into whether Microsoft had violated antitrust laws during the voting period. See, Forelle, Charls, <a href="http://online.wsj.com/article/SB120242867034452081.html?mod=technology_main_whats_news">Microsoft's Office Push Scrutinized by EU</a>, February 8, 2008, at http://online.wsj.com/article/SB120242867034452081.html?mod=technology_main_whats_news accessed March 30, 2008.</p>				
				<p><sup>3</sup> In one of several open letters, he referred to the OOXML process, with all of its flaws, as a "Poster Child for Standards Development," and criticized OOXML opponents <a href="http://www.durusau.net/publications/OpenXMLPosterChild.pdf">as follows</a>: "The OpenVMS project has made a large amount of progress in terms of the openness of its project development. Objections that do not recognize that are focusing on what they want to see and not what is actually happening with OpenXML." See, http://www.durusau.net/publications/OpenXMLPosterChild.pdf, accessed March 30, 2008</p>
				<p><sup>4</sup> In an interview, <a href="http://www.bibfor.theoconsult.de/?p=39">Durusau noted</a>: "The other question that only time will answer is whether OOXML will be so complex and lengthy that it will have a universe of adopters of 1." See, http://www.bibfor.theoconsult.de/?p=39, accessed March 30, 2008.</p>
				<p><sup>5</sup> Jonathan Zuck, president of the Association for Competitive Technology, which represents 4,000 businesses in the United States and Europe, including Microsoft, and supports ISO/IEC adoption of OOXML, stated: "This is a purely commercial battle masquerading as a principled debate over opendocument standards." See, O'Brien, Kevin, <a href="http://www.iht.com/articles/2008/03/30/technology/msft31.php">Vote on a Web Standard to Close to Call</a>, International Herald Tribune, March 30, 2008, at http://www.iht.com/articles/2008/03/30/technology/msft31.php, accessed March 30, 2008.</p>
				<p><sup>6</sup> The vote to which I allude was taken in the first round of voting, which ended on September 2, 2007, and was reported to me by the chair of the committee in question. The vote was 8 to 1 in favor of disapproval, and was held within a National Body whose rules require unanimity of vote in order to record a position. The result was that the National Body registered a vote of "Abstain." Note that under the complex voting rules that apply in ISO/IEC JTC1, abstentions are disregarded, and thus can be almost as useful to securing adoption as a vote to approve.</p>
				<p><sup>7</sup> I have collected excerpts and links from nine first-hand accounts of delegates representing a total of seven National Bodies <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20080309054524379#delegates">here:</a> http://www.consortiuminfo.org/standardsblog/article.php?story=20080309054524379#delegates</p>
				<p><sup>8</sup> That said, I believe that the rules should change systemically in areas such as transparency and the exercise of undue influence through methods such as "stacking" committees.</p>
				<p><sup>9</sup> See, <a href="http://www.consortiuminfo.org/bulletins/oct07.php#feature">A Proposal for a New Type of Global Standards Certification</a>, ConsortiumInfo.org, Standards Today, Vol. VI, No. 8, October-November 2007, at http://www.consortiuminfo.org/bulletins/oct07.php#feature</p>