<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
<style type="text/css">
<!--
.style10 {font-family: Arial, Helvetica, sans-serif; color: #000000; font-size: 16px; font-weight: bold; }
.style2 {font-family: Arial, Helvetica, sans-serif;

	font-size: 12px;
}
-->
</style>
<script type="text/javascript" src="/scripts/obfuscate.js"></script>
</head>

<body>
<p align="center" class="style10"><strong>INTELLECTUAL PROPERTY RIGHTS AND STANDARD SETTING</strong></p>
<blockquote>
  <p align="center" class="style10"><font size="2" face="Arial, Helvetica, sans-serif"><strong><a href="http://www.gesmer.com/attorneys/updegrove.php">Andrew Updegrove</a></strong></font></p>
  <table width="436" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
      <td width="436" valign="top" class="style2"><strong><em>Abstract:</em></strong><em>&nbsp;</em>
        <em>Intellectual  property rights (IPR), and particularly patent claims, provide special  challenges to standards developers.&nbsp;  Following adoption of standard, members may be unwilling to share  implementation rights on licensing terms that are conducive to wide adoption of  the standard (or at all).&nbsp; Or, during  the development phase, they may secretly seek to ensure that a standard will  infringe their undisclosed patent claims, in order to reap a harvest of  royalties when those rights are revealed after the marketplace has already been  locked in.&nbsp; Externally, there will often  be patent claims that are essential to the implementation of a standards, but  whose owners have little or no incentive to make their valuable IPR available  on acceptable terms (or at all).&nbsp; As a  result, standard setting organizations must have IPR policies that are designed  to minimize - although they cannot totally eliminate - such problems.&nbsp; In this article, I briefly review: the  history of IPR issues; the changes in the standard setting landscape that are  accentuating IPR concerns today; the ways in which IPR (and particularly patent  claims) give rise to concerns for standards developers and implementers; the  documents that comprise an appropriate IPR management regime; and finally those  areas in which IPR policies are most significantly being challenged and  reworked today.</em></td>
    </tr>
  </table>
</blockquote>
<p>&nbsp;</p>
<p><span class="style10"><strong><em>Introduction:</em></strong>&nbsp;</span> <span class="style2">The need to  deal with intellectual property rights &ndash; principally copyrights and patents &ndash;  lie at the core of standard setting.&nbsp; At  the most basic level, the standards, reference software, compliance test  suites, white papers, and other common deliverables that standard setting  organizations (SSOs) create are themselves copyrightable works, and can be sold  by SSOs, if desired, in order to defray some or all of the costs of their  production.&nbsp; At the level of  implementation, standards that dictate technical design features (as compared  to performance standards that only specify output parameters, or physical  interoperability standards, which deal with otherwise arbitrary characteristics  such as physical dimensions) have the potential to require the infringement of  patents owned by members and non-members.&nbsp;  Patent infringement has more significant economic implications, since  the owner of a patent can require the payment of a per-product fee to implement  a standard, or can withhold permission to implement the standard at all.</span></p>
<p class="style2">Every SSO therefore needs a  set of rules that addresses IPR in order to ensure that the SSO owns its work  product upon completion, and to decrease the risk that its completed standards  will encounter IPR-based impediments to broad implementation.&nbsp; Those rules typically address questions such  as whether and when patent claims must be disclosed, so that participants will  know whether all members (at least) will make available any essential patents  claims on what are traditionally referred to as &quot;reasonable and  non-discriminatory&quot; (or RAND) terms.</p>
<p class="style2">Achieving agreement on what  such policies should state, and on the process rules under which they are  implemented, can be as contentious a process as creating standards with high  commercial impact.&nbsp; Differences of  opinion on specific tenets and terms exist not only between individual  companies, but also between industries and sometimes among nations.&nbsp; In recent years, the importance of patents  in some sectors, and particularly in the information and communications  technology (ICT) industries, has focused increased attention on IPR  policies.&nbsp; That attention has made  existing SSOs reexamine their rules, and made it all but impossible to form a  new SSO until the founders have agreed upon the IPR policy that the new  organization will adopt.</p>
<p class="style2">In this article, I will  survey the changes in the standard setting landscape that are accentuating IPR  concerns today; the ways in which IPR (and particularly patent claims) give  rise to concerns for standards developers and implementers; the documents that  comprise an appropriate IPR management regime; some of the SSOs that have grappled  with difficult IPR issues today, and the changes that they have made to their  IPR policies; and finally those areas in which IPR policies are most  significantly being challenged and reworked today.&nbsp; But first, I will briefly describe the more peaceful days and  uniform policies that prevailed before things began to change.</p>
<p class="style10"><strong>I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Placid Past</strong></p>
<p class="style2">For the first hundred years  of standard setting, IPR concerns were relatively easily addressed, because  most participants in the standard setting process had roughly similar views on  how the rights of inventors and standards implementers should be balanced.&nbsp; During that time period, rules were  developed that were reasonably uniform across the world of standard setting, minimizing  (if not eliminating) the degree to which owning and sharing IPR complicated the  standard setting process.</p>
<p class="style2">The relative lack of  friction that prevailed during these years also arose from the fact that  individual setting organizations often constituted independent ecosystems, with  little reason to interact with each other.&nbsp;  These organizations could develop rules of behavior under otherwise  substantially similar IPR policies that were well understood by their members.&nbsp; In some SSOs, those rules might be highly  tolerant of including IPR in a standard that would result in implementers  needing to pay royalties to one owner or another, while in others, such an  outcome would be seen as very undesirable.&nbsp;  Moreover, a single standards organization often served all of the  standards needs of an industry niche.&nbsp;  As a result, many or all of the standards that a given group of industry  participants might need in order to build their products were developed within  a single, independent organization, and thus subject to the same set of rules  and expectations.</p>
<p class="style2">Until recently, standards in  most organizations were created by career professionals, who knew each other  and collaborated over long periods of time on standards, allowing many  potential issues to be identified early in the process, and for differences to  therefore be resolved more amicably.&nbsp; In  addition, a large percentage of the standards created in traditional industries  were unlikely, or indeed unable, to infringe anything that was patentable  (e.g., a standard that sets light bulb wattage increments of 40, 60, 75 and so  on, or a standard that dictates the gauges of electrical wiring).</p>
<p class="style2">Standard setting also  occurred primarily at the national level.&nbsp;  Indeed, national standards were often created, or at least used,  expressly to make it more difficult for foreign vendors to enter the domestic  marketplace.&nbsp; In such a situation,  infringement of patents could be considered a favorable attribute of a  standard.&nbsp; But in either event, only IPR  issues of national relevance were of concern.</p>
<p class="style2">For all of these reasons,  addressing IPR was a comparatively easy challenge, and did not consume a great  deal of time on the part of standard setting organizations, virtually all of  which were accredited standards development organizations (SDOs) that were, in  addition, required to comply with a single high-level set of IPR rules in order  to obtain and maintain accredited status.&nbsp;  To the extent that rules varied from organization to organization within  the boundaries permitted by such overall rules, these distinctions were not  likely to cause problems, due to the level of isolation (noted above) that  tended to exist between industry niches, and therefore between those that might  be affected by any differences.</p>
<p class="style2">Because of this same  insularity, cross licenses were often easy to arrange among the traditional  leaders of a given industry.&nbsp; And so on,  in a process common to matured industries that have an interest in sorting  things out, and which have evolved common strategies and practices that to  create orderly and predictable market conditions within which to compete.&nbsp; In many SSOs, IPR disputes were therefore  unknown, and many members were only dimly aware of the specifics of the IPR  policies of the SSOs in which they participated &ndash; assuming those policies had  specifics at all.&nbsp; Many such policies  were in fact only one or two pages of high-level statements of principle, or  simple references to, or adoption of, the policies mandated by the accrediting  authority to which they were subject.</p>
<p class="style2">In short, standard setting  could progress apace with relatively little concern over IPR, either curing or  after the adoption of a standard.</p>
<p class="style10"><strong>II&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Turbulent Present</strong></p>
<p><span class="style10"><strong><em>A changing landscape:</em></strong>&nbsp;</span> <span class="style2">This placid  picture began to deteriorate as the ICT industry evolved with increasing  rapidity in the 1980s.&nbsp; During these  years and after, ICT came to play an ever-larger role in the world economy, and  new SSOs (mostly unaccredited organizations referred to generally as  &quot;consortia&quot;) began to proliferate to create the standards (and in  particular, interoperability standards) demanded by these new  technologies.&nbsp; The standards that these  new SSOs created applied to technical areas that were often the subject of  intense patent activity, although not uniformly so.&nbsp; Software was not yet patentable in the United States in the early  years of this progression, and therefore SSOs setting standards for  microprocessors and hardware had concerns not shared by the many consortia that  sprang up to create software standards. <a href="#1">1</a> </span><a href="#_ftn1" name="_ftnref1" title="" id="_ftnref1"> </a></p>
<p class="style2">The industries that filed  these patents were also used to asserting them aggressively, in order to defend  their right to recoup their often significant research and development costs,  and to reap the profits they expected to earn on such investments.&nbsp; Many also had internal cultures that granted  high status, and sometimes large bonuses as well, upon those that were  successful in acquiring the most patents.</p>
<p class="style2">The convergence of  technologies in single devices and business situations caused further problems,  as standards broke out of their sectoral silos.&nbsp; Now, standards that required license fees to implement might be  needed in situations where such costs were regarded as intolerable.&nbsp; To make matters worse, a new business model  arose that involved the creation of patentable inventions for the sole purpose  of generating license fees, rather than to protect the designs of products that  the patent owners themselves manufactured.&nbsp;  Companies adopting this model profit only from fees paid by third  parties, and those license fees can increase dramatically if a patented  invention, by accident or design, finds its way into a widely adopted  standard.&nbsp; Moreover, since the patent  owner (or &quot;troll,&quot; as such a business is often unaffectionately  called) does not build anything that can infringe someone else's patent, there  is no potential to resolve disputes through negotiating a cross license.</p>
<p class="style2">As a result, private parties  began to sue companies they believed to have abused the standard setting  process by failing to disclose their patent claims, and to complain to  government regulators as well.&nbsp; When  this occurred, companies with large patent portfolios were at a loss to know  whether to be more reassured or fearful, since the only way to be sure that  they disclosed a relevant patent claim would be to conduct a search of their patent  portfolios.&nbsp; Since some companies  participate in hundreds of SSOs, institutionalizing such a practice would be  prohibitively expensive.&nbsp; Not  surprisingly, these companies strongly resisted any IPR policy change that  might suggest that such a search should become a practical necessity.&nbsp; At the same time, they were concerned that  they might inadvertently fail to disclose a patent, and either lose the ability  to profit from it, or be fined if they tried to do so.&nbsp; </p>
<p class="style2">Small companies, or  companies with few patents, had different concerns.&nbsp; Not only could they easily determine whether or not they had an  essential patent, but they also would be unlikely to negotiate a cost-free  cross license with a large competitor that owned a patent infringed by a  standard, although its other large competitors could.&nbsp; Accordingly, companies with few patents focused instead on the  potential for a patent owner to hide its patent until a standard was widely  adopted, and then extort high license fees after the industry had become  &quot;locked in,&quot; and unable to redesign the standard in order to avoid a  commercial tax upon the sale of compliant implementations.</p>
<p class="style2">  These  issues first attracted wide concern in 1996, when Dell Computer entered into a  consent decree with the Federal Trade Commission in the United States.&nbsp;&nbsp; That investigation was brought in response  to private party complaints that Dell had participated in a standard  setting process hosted by the Video Electronics Standards Association (VESA),  and had failed to disclose that it owned a patent that it believed would be  infringed by any implementation of the standard under consideration.&nbsp; Only after the adoption of that standard and  its initial commercialization did Dell identify its patent and assert a right  to require royalties. The FTC concluded that such behavior was a violation of  the antitrust laws, and as part of the consent decree, Dell agreed that it  would grant a royalty-free license to any implementer of the standard; it was also  required to subject itself to oversight in its standards-related activities for  a period of ten years.&nbsp; &nbsp;&nbsp;Had Dell disclosed its patent during the course of the adoption  process, it could have stated its intention to require a royalty from  implementers, and the working group would have had the opportunity to decide  whether to rewrite the standard in such a way as to avoid infringement, or to  knowingly adopt the standard subject to the royalty requirement. </p>
<p class="style2">  The  impact of the Dell consent decree was substantial, as news of the facts and the  significant penalty became widely known.&nbsp;  This was less because the integrity of the standards development process  had been upheld, but because Dell had  contended that it's representative in VESA did not know of the patent in  question, and that its failure to disclose was inadvertent.&nbsp; </p>
<p class="style2">Regardless of the truth or  falsity of Dell's defense, the possibility of making an innocent mistake seemed  all too real to large patent holders. <a href="#2">2</a> <a href="#_ftn2" name="_ftnref2" title="" id="_ftnref2"> </a>&nbsp; From the date the consent decree was  announced until the present, scrutiny of IPR policies has steadily  increased.&nbsp; In recent years, litigation  and investigations have again been launched, based upon similar patters of  alleged conduct.&nbsp; The most prominent  example involves a semiconductor design company called Rambus, Inc.&nbsp; Rambus has been mired in litigation with  multiple semiconductor manufacturers for most of the current decade, and also  been convicted of creating an illegal monopoly by the FTC.&nbsp; More recently, telecommunications giants  QUALCOMM Incorporated&nbsp; and Broadcom  Corporation have been locked in combat, in part over Broadcom's accusation that  Qualcomm has engaged in conduct reminiscent of&nbsp;  Rambus. <a href="#3">3</a> <a href="#_ftn3" name="_ftnref3" title="" id="_ftnref3"> </a></p>
<p class="style2">Today, however, some owners  of large patent portfolios are shifting their focus away from the possible  consequences of an inadvertent failure to disclose an essential patent to a  different concern: whether the products they hope to build will be taxed with  such high levels of patent fees that they cease to be commercially viable.&nbsp; This is in response to a variety of current  trends, including convergence, the increasing number of patent filings in some  areas, the possibility that the troll business model will proliferate, and the  rising importance of open source software.&nbsp;  Several of these trends bear mention in greater detail:</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong class="style10"><em>Patent thickets:</em></strong>&nbsp; <span class="style2">The number and density of &quot;patent thickets&quot; (i.e.,  areas of intense patent activity that focus on commercially important  technologies) is increasing.&nbsp; When  standards are created in areas that have thickets, it is almost impossible not  to infringe upon one or more patents.&nbsp;  One consequence is that such a standard may provide an economic  advantage to companies that can cross license their essential patents at no  cost among themselves, while those that do not hold relevant patents must pay  royalties.&nbsp; Where the patent owner is a  troll, the playing field is level as among all competitors, because all must  pay, but the cost in license fees may impede adoption of the standard.&nbsp; </span></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="style10"><strong><em>Convergence</em></strong><em>:</em>&nbsp;</span> <span class="style2">A single device or service may now include  many more standardized technologies than in the past.&nbsp; A mobile device that incorporates a camera, video, PDA functions,  a Web browser, text messaging and wireless, for example, will implement  hundreds of standards.&nbsp; If even a small  percentage requires payment of royalties, the device may become uneconomical to  produce.&nbsp; Where no royalties are  involved, a manufacturer may still be forced to negotiate and enter into many  license agreements, each with its own terms. </span></p>
<p><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="style10">Open source software:</span></em></strong><span class="style10">&nbsp;</span> <span class="style2">The phrase &quot;open source software&quot;  implies that the actual source code of the software will be available under one  of a number of different licenses that have been accepted by the Open Source  Institute (OSI) as meeting its requirements for being designated as such.&nbsp; Those terms demand, at minimum, that the  source code (i.e., code that can be easily understood by a developer, as  compared to object code, which is readily &quot;understood only by a computer)  must be made available to the licensee.&nbsp;  Many licenses, such as the GNU General Public License, or GPL, have  additional requirements, such as requiring that someone that modifies and sells  software received under that license must make those modifications available  under the GPL as well.&nbsp; The GPL also  prohibits including any license terms deemed to be inconsistent with its own.</span></p>
<p class="style2">When open source software  needs to implement standards, parts of the resulting code may necessarily  infringe upon patent claims that are essential to the standard.&nbsp; If the standard so implemented permits the  patent owner to require license terms that are prohibited under the open source  software license, a conflict occurs.&nbsp; As  a result, open source community advocates, as well as those commercial entities  that are increasingly basing their business models around open source software,  do not wish standards that are important to open source implementations to be  created under IPR policies that would permit license terms to be imposed that  are incompatible with the requirements of popular open source software  licenses.&nbsp; The only way to lessen the  likelihood of that outcome is by adjusting the IPR policy of the SSO creating  the standard to so provide.</p>
<p class="style2">For all of these reasons and  more, the IPR rules and policies under which SSOs operate today are matters of  line-by-line concern to many standard setting participants.</p>
<p class="style10"><strong>III&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; IPR Policy Coverage and Implementation</strong></p>
<p class="style2">While the members of  different SSOs will take different paths in creating and deploying an IPR  regime, the subject areas that each organization must face are common to  all.&nbsp; </p>
<p><strong class="style10"><em>Coverage:</em></strong>&nbsp; <span class="style2">Each IPR  policy that provides comprehensive IPR protection needs to address the  following subject areas:</span></p>
<p><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="style10">Copyright:</span></em></strong>&nbsp; <span class="style2">Copyright  issues under IPR policies are comparatively simple.&nbsp; The near-universal practice is to provide that if a member contributes  any material for inclusion in a standard, it retains ownership in that  contribution, but irrevocably (a) licenses the SSO to make the contribution  available to other members for purposes of considering its inclusion in a  standard, (b) licenses the SSO to distribute the eventual standard with the  contribution included, in whole or in part,&nbsp;  and (c) agrees that the SSO will own the copyright in the final standard  into which the contribution is incorporated.<a href="#_ftn1" name="_ftnref1" title="" id="_ftnref1"> </a><a href="#4">4</a></span></p>
<p><span class="style2">The main controversy involving copyright involves not  the terms to be used, but the ability of an SSOs right to enforce its copyright  when a standard has been referenced by, or incorporated into law.&nbsp; The issue is of significance to SDOs, and  not consortia, because the great majority of the former derive significant, and  in some cases the majority of their operating revenues from sales of their  standards, while the latter rarely charge for their standards at all.&nbsp; In general, there is no question that those  SSOs that wish to charge for access to their standards may do so.&nbsp; But in 2003, in a case called&nbsp; <em>Southern  Building Code Congress International v. Veeck, the </em>U.S. Court of  Appeals for the Fifth Circuit handed down a decision that caused a great deal  of consternation among SDOs.&nbsp; In what  has come to be simply referred to as &quot;the Veeck case&quot;, the matter at  issue was a Texas building code that referenced a standard, and the matter  arose when someone posted a copy of the referenced standard on a public Web  site.&nbsp; The owner of the standard  thereupon sued, alleging that it was unjust to require the purchase of a  standard that a builder would be legally obligated to implement. </span></p>
<p class="style2">  The  holding captured the immediate attention of the SDO community nationwide,  despite the fact that it was binding only in the Fifth Circuit, and even though  it related only to standards referenced, or incorporated into statute.&nbsp; The reason was the fear that the ruling  might be extended to all standards.&nbsp;  Following the decision, the SDO sought the intercession of the Supreme  Court, which declined to hear the case, despite the fact that at least two  other Circuits had issued opinions that reached different conclusions. <a href="#5">5</a> <a href="#_ftn2" name="_ftnref2" title="" id="_ftnref2"> </a>&nbsp; The holding of the lower court therefore  remains binding in the Fifth Circuit - as well as a precedent that courts in  other circuits may decide to follow, even if they are not legally bound to do  so. As a result of the Supreme Court deciding not to hear the appeal,  uncertainty will continue regarding whether other courts will follow (or not)  the Fifth Circuit's reasoning, and if so, whether they will do so in a more  limited or comprehensive fashion. </p>
<p><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="style10">Trademark:</span></em></strong>&nbsp; <span class="style2">Trademark  rules under IPR policies are also non-controversial.&nbsp; All policies agree that members retain ownership of their  trademarks, and SSOs retain ownership of theirs.&nbsp; Trademarks are particularly important to SSOs that conduct, or  authorize the operation of, certification testing, because a license to a well  maintained trademark must be obtained by a product or service provider as a  precondition to holding their goods or services out as being in compliance with  the trademarked standard.<a href="#_ftn3" name="_ftnref3" title="" id="_ftnref3"> </a> <a href="#6">6</a> </span></p>
<p><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="style10">Patents:</span></em></strong><span class="style10">&nbsp;</span> <span class="style2">Simplicity  ends with patents, and as a result 90% of the language, and almost 100% of the  controversy, surrounds the rules that relate to so-called &quot;essential claims.&quot;&nbsp; These issues will be dealt with in detail in  Section IV below.</span></p>
<p><strong><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="style10">Confidentiality: </span></em></strong><span class="style2">IPR policies usually deal with confidentiality in one of two ways: by  either establishing rules for describing what is entitled to be maintained in  confidence, or by declaring that nothing is to considered confidential.&nbsp; The latter approach is more common, and is  indicative of an organization that maintains &quot;best practices&quot; in  creating what are understood to be &quot;open standards.&quot; <a href="#7">7</a> <a href="#_ftn4" name="_ftnref4" title="" id="_ftnref4"> </a></span></p>
<p class="style2">That  said, there is often a distinction between whether information will be public,  and if so, when it will be made so available.&nbsp;  In part, this is a reflection of economic concerns, since early access  to the text of an evolving standard can have commercial value, and thus provide  an incentive to become a member.&nbsp; In  addition, those that can view the text and direction of a standard under  development could surreptitiously seek to file patent applications on  inventions inspired by the evolving standard.&nbsp;  If the evolving standard is visible only to members that are bound to  disclose any relevant patents or patent applications, then such a result can be  avoided (at least to the extent that members abide by the rules).&nbsp; </p>
<p class="style2">But  if the emerging text is available to all, then a non-member could file, or  amend, a patent application to place it in the way of implementers without  violating any rules at all.&nbsp; For this  reason, many SSOs limit access to an evolving specification to members alone,  and sometimes only to those that have enrolled in the working group that is  producing it, until a later date.&nbsp; For  some SSOs, that later date is after final adoption, while for most it is when  the draft standard is in near-final form.&nbsp;  At that point, many SSOs post the draft for public, as well as member,  comment.&nbsp; Those comments will usually be  technical, but may also include a warning by a patent owner that implementation  might result in infringement of its patent, or an alert by someone else that it  is aware of a patent of possible concern.</p>
<p><span class="style10"><strong><em>Implementation:</em></strong>&nbsp;</span> <span class="style2">IPR policies are  most often deployed in one of two ways: either by a Board (and sometimes  member) adopted policy, or by inclusion in the application that each member  must sign to become a member.&nbsp; In the  former case, a member signs a much shorter application, but that application  includes language that makes all Board-adopted policies binding upon each  member. <a href="#8">8</a> <a href="#_ftn5" name="_ftnref5" title="" id="_ftnref5"> </a></span></p>
<p class="style2">IPR  policies, however deployed, tend to be high-level documents.&nbsp; As a result, a more detailed set of policies  and procedures is also required, in order to provide the many procedural rules  necessary to guide multiple standards working groups in creating and  reconciling the standards being created, in setting rules of quorum and voting,  and so on. <a href="#9">9</a> <a href="#_ftn6" name="_ftnref6" title="" id="_ftnref6"> </a></p>
<p class="style2">As  court cases have consistently indicated, it is essential that an IPR policy,  once adopted, be consistently described and enforced. <a href="#10">10</a> <a href="#_ftn7" name="_ftnref7" title="" id="_ftnref7"> </a>&nbsp; Similarly, in order for commitments that  members make to be of reliable use in the future, they must be clearly stated. <a href="#11">11</a> <a href="#_ftn8" name="_ftnref8" title="" id="_ftnref8"> </a>&nbsp; The documentation that instantiates an IPR  regime must therefore be carefully drafted and maintained.</p>
<p class="style2">The  final suite of documents to both institute and implement an IPR regime, and  their functions, are commonly as follows:</p>
<table border="1" align="center" cellpadding="2" cellspacing="0">
  <tr>
    <td width="154" valign="top" class="style10"><p align="center"><strong>Document</strong></p></td>
    <td width="436" valign="top" class="style10"><p align="center"><strong>Function</strong></p></td>
  </tr>
  <tr>
    <td width="154" valign="top" class="style2"><p>Membership    Application</p></td>
    <td width="436" valign="top" class="style2"><p>A    binding contract between the SSO and the member, that requires the member to    obey the IPR Policy and all related rules and procedures</p></td>
  </tr>
  <tr>
    <td width="154" valign="top" class="style2"><p>Bylaw    language</p></td>
    <td width="436" valign="top" class="style2"><p>A    section of this document gives the Board the authority to adopt, amend and    administer the IPR Policy and all related rules and procedures</p></td>
  </tr>
  <tr>
    <td width="154" valign="top" class="style2"><p>IPR    Policy</p></td>
    <td width="436" valign="top" class="style2"><p>A    set of high-level rules that address all crucial patent, copyright and    trademark issues</p></td>
  </tr>
  <tr>
    <td width="154" valign="top" class="style2"><p>Assertion    Forms</p></td>
    <td width="436" valign="top" class="style2"><p>A    set of short forms used to disclose IPR and to commit to licensing    choices.&nbsp; One form must be completed    in connection with, and must accompany, any submission made by a member for    possible inclusion in a standard, and a similar form must be completed by    every member of a working group at the time that it votes to recommend a    draft standard for adoption (some SSOs require non-working group members that    vote to adopt a standard to complete a form as well).&nbsp; The forms contain language that tracks the    IPR policy, and a member may only select which licensing statement it chooses    to make, and not change the language of the commitment itself.&nbsp; Exhibits are provided for the disclosure    of essential patent claims, and the portion of a draft standard to which they    relate</p></td>
  </tr>
  <tr>
    <td width="154" valign="top" class="style2"><p>Rules    of Procedure</p></td>
    <td width="436" valign="top" class="style2"><p>The    &quot;bylaws&quot; of the technical process</p></td>
  </tr>
  <tr>
    <td width="154" valign="top" class="style2"><p>Trademark    Guidelines</p></td>
    <td width="436" valign="top" class="style2"><p>Rules    of usage for SSO trademarks</p></td>
  </tr>
  <tr>
    <td width="154" valign="top" class="style2"><p>Trademark    License</p></td>
    <td width="436" valign="top" class="style2"><p>As    needed, if a compliance or certification mark program is put into place</p></td>
  </tr>
</table>
<p><strong class="style10">IV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Patent  Issues</strong><a href="#_ftn9" name="_ftnref9" title="" id="_ftnref9"> </a> <a href="#12">12</a></p>
<p>  <span class="style2">By  far and away the most difficult IPR issues that SSOs must address involve  patent claims.&nbsp; Unlike other types of  IPR, patent claims can often only be designed around with great  difficulty.&nbsp; Sometimes, patent claims  can represent complete roadblocks to a solution, either because no alternative  approach is technically possible, or economically feasible, to implement.</span></p>
<p class="style2"> As  a result, SSOs go to great lengths to avoid knowingly adopting specifications  that infringe upon the patent claims of a member or third party that is not  willing to cooperate.&nbsp; At worst, such a  patent owner may be unwilling to provide a license to anyone that wishes to  implement the standard, or may only be willing to provide a license to some,  but not all would-be implementers.&nbsp;  Almost as seriously, the patent owner may wish to charge a fee or impose  other terms that would impede or preclude wide adoption. </p>
<p class="style2"> Unfortunately,  there are two reasons why it is impossible to totally avoid the potential for  inadvertent patent infringement:&nbsp; first,  conducting patent searches for every standard on a worldwide basis would be  both prohibitively expensive, as well as ineffective in avoiding allegations of  infringement, because patent owners will often have different opinions about  the coverage of their patents than will third parties.&nbsp; Second, only a small percentage of the  holders of affected patents will typically be members of a given SSO, or even  implementers of its standards.&nbsp;  Consequently, simply asking those members that are willing to act in  good faith whether they have any patents of concern can reveal at best only  some of the patents that may be infringed by any given standard.&nbsp; Even then, a response from an individual to  the best of her knowledge regarding the reach of the patent portfolio of their  multinational employer provides only minor comfort at best.&nbsp; </p>
<p class="style2"> Nor  can SSO members be required to conduct internal patent searches, since the  companies that participate in the largest numbers of SSOs own thousands, and  even tens of thousands, of patents.&nbsp; As  already noted, no SSO would find itself politically able to impose such a  requirement unless its membership included only those with few, or not,  patents.&nbsp; Indeed, almost all IPR  policies for this reason include a very specific term stating that no member  shall ever be required to conduct a formal patent search by reason of its  participation in the SSO.&nbsp; </p>
<p class="style2">  Even  if all of these problems could be resolved as to members under IPR policies and  rules, non-member patent owners would still be free to act as they wished, and  could therefore at best only be cajoled, rather than compelled, into providing  license rights to all would-be implementers on RAND terms for any patent claims  that might be infringed by a standard.</p>
<p class="style2"> Despite  this discouraging landscape, SSOs nevertheless do what they can to craft IPR  policies intended to clear the field of problems involving at least  member-owned patents, and in particular to prevent any game playing by members  that might otherwise seek to &quot;plant&quot; patent claims in a standard in  order to reap future economic rewards.</p>
<p class="style2"> Achieving  consensus on the rules underlying such policies can be a daunting challenge,  however, due to the great value that most companies associate with their  patents, and the variety of opinions that they hold on how best to protect that  value in the context of standard setting.&nbsp;  As a result, and absent special concerns, it is usually sensible for an  SSO to adopt as mainstream a policy as possible, since the middle ground  represented by such a policy will likely be the only feasible meeting point for  conflicting viewpoints.&nbsp; Where an SSO  strays from this middle ground, it sometimes finds that its mission may be  hampered, or even defeated, due to its inability to attract a broad membership. </p>
<p class="style2"> It  is therefore essential that those who are tasked with drafting an IPR policy  understand the positions that individual companies are likely to take on  specific IPR policy terms, and the legal and practical concerns that underlie  these positions.&nbsp; Sadly, after stating  that all patent claims must be available on at least RAND terms, it becomes  difficult to achieve consensus on almost everything else.&nbsp; </p>
<p class="style2"> The  issues that lead to this diversity of viewpoint may be usefully sorted and  analyzed under the familiar headings of &quot;Who&quot;, &quot;What&quot;,  &quot;When&quot;, &quot;Where&quot; and &quot;Why.&quot; </p>
<p class="style2"><span class="style10"><strong><em>Who?</em></strong></span><strong>&nbsp; </strong>Some SSO participants believe that  it is sufficient to collect licensing commitments only from those members that  directly participate in creating a standard, since these are the patent owners  that are able to actively &quot;game&quot; the system, either passively, by  failing to disclose their patent claims, or actively, by pushing the process  towards adopting a standard which would entitle them to levy a royalty.&nbsp; This requirement to make a binding  commitment to license, or to disclose the possibility that a RAND license might  not be forthcoming, makes obvious sense from a practical perspective.<a href="#13">13</a><a href="#_ftn10" name="_ftnref10" title="" id="_ftnref10"> </a>&nbsp; However, other SSO members may believe that  a licensing commitment should be required of every member of the SSO, whether  or not it chooses to participate directly in a given process.&nbsp; The practical effect of such a requirement  is that the circle of safety is expanded simply by requiring the commitments of  more potential patent owners.&nbsp; More  significantly, if non-participating members have access to specification drafts  as they mature, those non-participating members could file patent applications  that track the evolving standard.&nbsp;  Unless required to disclose such patent applications, those members that  were acting in good faith could later be taken by surprise. </p>
<p class="style2"> Other  SSO members believe that the rules should reach still farther, and insist that  any implementer of a standard - whether a member or not - should grant all  other implementers a cross license of its own patent claims to the extent  necessary to avoid infringement.&nbsp; The  impact of this position may impede implementation of a standard, however, since  most standards need promotion before they become pervasively adopted, and many  implementers may have very low motivations to adopt a standard at all.&nbsp; Where a cross license is required, such  non-member companies may choose not to implement the standard at all.&nbsp; </p>
<p class="style2"> Of  course, such a mandatory cross license is not likely to capture someone that  has truly bad intentions in any event, as such a patent owner may intend to  reap a far higher return from taxing all implementers than through implementing  the standard itself.&nbsp; As a result, a  standard may be unlikely to receive much benefit - but can be severely impaired  - by a broad cross license requirement.&nbsp;  In the case of standards that are relevant to software, such a mandatory  cross license term would violate the terms of many open source licenses as  well, and thus any standard that was created under an IPR policy that permitted  patent owners to require such a cross license would be unacceptable to the  developers of the open source software.</p>
<p class="style2"> For  all of these reasons, the most common method of addressing this concern under  IPR policies is to permit what has come to be called a &quot;defensive  suspension&quot; term in licenses of essential patent claims.&nbsp; Under this licensing term, a patent claim  owner that has agreed to provide a license to implementers of a standard on  RAND terms is entitled to revoke the license of any implementer that asserts  its own patent under non-RAND terms.&nbsp;  This levels the playing field for further negotiation, and is considered  to be consistent with a RAND licensing commitment. </p>
<p><strong class="style10"><em>Who  (II)?</em></strong><em>&nbsp; </em><span class="style2">A related issue  briefly alluded to above is whether an assertion by a member representative  that she has no patent claims to disclose should be limited to the knowledge of  the individual alone, or should extend to the deemed knowledge of her corporate  employer (the actual member) as well.&nbsp;  For a large multinational company with perhaps thousands of engineers  participating in hundreds of standards working groups, this prospect represents  an IPR manager's nightmare, unless a decision has already been made by the  corporate member that it is willing to make all patents available on RAND terms  &ndash; assuming that RAND terms are all that the IPR policy requires (and not  royalty-free licensing).&nbsp; On the other  hand, an assertion to the personal knowledge of a single employee that she is  unaware of any potential for infringement is useful only to the extent that it  helps preclude conscious misbehavior.&nbsp;  While that is an important result, it is less useful than an undertaking  that a member will never assert a patent at all on other than on RAND terms.</span></p>
<p class="style2">  As  a result, many IPR policies acknowledge that <em>disclosures</em> are made only  to the knowledge of the individual participant, but may still require the  member to <em>commit</em> to a given course of action, if it later becomes aware  of a patent claim that might be infringed.&nbsp;  Regardless of which approach is taken with respect to eventual  disclosure, a well thought through IPR policy (or the procedural document  supporting that policy) will contain a term stating that the member will become  irrevocably bound to make a disclosure and licensing statement at the end of  the process once it has participated in a working group for some period of time  (e.g., 60 days).&nbsp; Otherwise, a member  could attend a working group in public, and file patent applications in private,  until just before the requirement to put its IPR cards on the table matured,  and then drop out, only to reveal its &quot;submarine patents&quot; after the  standard had become widely adopted. <a href="#14">14</a> <a href="#_ftn11" name="_ftnref11" title="" id="_ftnref11"> </a> </p>
<p><span class="style10"><strong><em>What?</em></strong></span><em><strong>&nbsp; </strong></em><strong></strong><span class="style2">There is also a difference of  opinion over what rights a patent holder must grant.&nbsp; Some believe that, in at least some situations, royalty free  licenses should be required from every company that participates in the  adoption process.&nbsp; The most fervent  champions of free licensing would require every member of an SSO to agree to  grant a license to whatever standards may be developed while they are a member  (although most would permit a member to resign to avoid this result in a given  situation).&nbsp; Not surprisingly, such a  comprehensive rule would lead many technology companies to refuse to  participate in an SSO with a broad development mission, unless participating in  the work of that SSO was extremely important to their business.&nbsp; </span></p>
<p class="style2">  While  not uncommon, such a rule is found mostly in organizations with small  memberships, comprising only companies that have much to gain by creating the  standard.&nbsp; Unless the member companies  control a large portion of the marketplace, however, the rule can be  self-defeating, since other stakeholders that are needed to support the  standard, but who have less to gain from its adoption, are often unwilling to  agree to so strict a term. </p>
<p><span class="style10"><strong><em>When?</em></strong><em>&nbsp;</em> </span><span class="style2">While most SSOs require that licensing  commitments be made towards the end of the standards development process,  others require commitments to be given earlier in order to clear the way for  smooth final approval of the standard under development. This is a sensitive  issue, because many companies are not willing to commit to grant a license  until they have had the opportunity to conduct some degree of internal  investigation to discover what, if any, valuable technology rights may be  involved.&nbsp; Also, they may wish to assess  whether the resulting standard will be highly favorable to their business, and  therefore whether any lost licensing opportunity will be outweighed by the  benefits anticipated from broad adoption.&nbsp;  If a commitment to license, and especially a commitment to license on a  royalty free basis, must be made at the time of joining a working group (or  soon after), the right to evaluate probable benefits thus becomes limited.&nbsp; Finally, companies often fear that if they  make a licensing commitment in advance, they may be trapped by competitors that  conspire to include valuable IPR owned by the first company in the resulting  standard. </span></p>
<p class="style2">  For  companies with substantial patent portfolios and the desire to participate in  many standard setting efforts, early decision making is therefore an issue of  significance.&nbsp; Conversely, other  companies (and particularly companies with small, easily searched patent  portfolios) may be unwilling to spend months on helping develop a draft  standard, only to learn at the time that a vote to adopt is taken that a  participant has a blocking patent, and is unwilling to make rights under that  patent available on acceptable terms.&nbsp;  Companies that endorse this viewpoint have concluded that the standards  that are developed are more important to them than maximizing the commercial  return on their patent portfolios, so long as they can reserve the right to  charge a royalty on any of their IPR that may eventually be found to be covered  by a finally adopted standard. <a href="#15">15</a> <a href="#_ftn12" name="_ftnref12" title="" id="_ftnref12"> </a> </p>
<p><span class="style10"><strong><em>Where?</em></strong><em>&nbsp;</em></span> <span class="style2">Once a standard has been adopted that  requires a vendor to obtain one or more licenses as a precondition to  implementation, the question arises where and how an implementer can obtain  those rights.&nbsp; In an ideal world, all of  those rights could be obtained at the Web site of the SSO that developed the  standard, along with the SSO's permission relating to the standard itself.&nbsp; In fact, patent owners rarely permit an SSO  to sublicense patent claims, and the SSO therefore may only grant rights in the  copyright that it owns in the standard itself.&nbsp;  This is typically accomplished using a short and simple  &quot;clickwrap&quot; license, which exists principally to exclude any  warranties of any type (e.g., as to ownership, non-infringement, and so  on).&nbsp; </span></p>
<p class="style2">  Where  any member or third party has asserted the right to require a royalty and/or to  precondition implementation upon other license terms (e.g., it may want a  defensive suspension right), a would-be implementer most go direct to the  patent owner to obtain the necessary rights. Typically, the standard setting  body does not become directly involved with the terms of such licenses, and  never takes a position as to whether an asserted patent claim is indeed  essential, it will usually provide a list of those patent owners that claim  that a license is required, together with contact information for such owners.</p>
<p class="style2">  At  times, there are so many patents that are asserted against a single standard  (as can occur when a standard overlies one of the &quot;patent thickets&quot;  referred to above), the owners of those patents will sometimes form a patent  &quot;pool.&quot;&nbsp; In such a case, an  administrator is retained to manage the licensing and economic terms on behalf  of all of the patent owners.&nbsp; This  allows an implementer to pay a single fee, and sign a single license, in order  to obtain all required rights relating to the underlying patents.&nbsp; The fees are then divided among the pool  participants, according to a mutually agreed upon formula.</p>
<p class="style2">  Regardless  of the licensing arrangements that relate to patents underlying a standard, a  license that forbids the implementer to sublicense can have an adverse impact  under many open source software licenses.&nbsp;  Such a restriction will not be problematic for an implementer that  wishes to build an application for internal use only.&nbsp; But if it is a vendor that wishes to sell that application, then  the terms of many open source license agreements would be violated if its  customers were obligated to return to the patent owner for their own license  (and even if that license could be obtained free of charge). </p>
<p><span class="style10"><strong><em>How?</em></strong><em>&nbsp;</em></span> <span class="style2">The great majority of IPR policies in  existence today still rely upon RAND licensing commitments.&nbsp; A reasonable and important question, therefore,  is what exactly does &quot;RAND&quot; mean, and what terms would be considered  to be acceptable under a license intended to meet such a commitment?&nbsp;&nbsp; Perhaps surprisingly, SSOs almost never try  to define exactly what either &quot;reasonable&quot; or  &quot;non-discriminatory&quot; is intended to mean.&nbsp; Even more surprisingly, until recently there have been relatively  few disputes litigated between patent owners and implementers over these terms.<a href="#_ftn13" name="_ftnref13" title="" id="_ftnref13"> </a><a href="#16">16</a>&nbsp; Most SSOs have shrunk from becoming involved  in such disputes, since they lack the resources or the will to take an active  part.&nbsp; <br />
Despite  this overall reluctance for any party involved to tackle the RAND definition  issue, the popularity of the simple RAND rubric continues, giving rise not only  to obvious questions (e.g., how high can a royalty be before it becomes  &quot;unreasonable?&quot;), but to more subtle ones as well, such as whether it  is discriminatory to charge a cross license partner nothing to implement a  standard, while charging a royalty to the competitor of the partner with whom  the patent owner does not have a patent license.&nbsp; If such a position does not represent discrimination, then the  second company will be at a price disadvantage to the first.<a href="#_ftn14" name="_ftnref14" title="" id="_ftnref14"> </a> <a href="#17">17</a></span></p>
<p><span class="style10"><strong><em>Why?</em></strong> </span><span class="style2">Another  interesting question relates to why given companies take particular positions  on certain issues.&nbsp; A simple explanation  is that it is difficult for a company to step outside the realities of its  familiar proprietary world and assume the mind-set necessary to give away  something (i.e., valuable IPR underlying a standard) in order to gain something  of greater commercial value.&nbsp; One often  under-appreciated benefit is the luxury of making a safe strategic decision  (e.g., for a manufacturer, knowing in advance that it is committing to what  will prove to be the &quot;VHS&quot; rather than the &quot;Betamax&quot;  standard).&nbsp; Thus enabled, it can compete  with other SSO members in making better and more appealing products based on  the adopted standard, and address a more swiftly and surely developing market  for those products.&nbsp; Even long-term  participants in the standards process can sometimes catch themselves taking a  position that is inconsistent with consortium goals, simply out of habit.&nbsp; The most enlightened and successful  participants in standard setting (in this author's opinion) are therefore those  that most thoroughly &quot;get&quot; the fact that they have far more to gain  from the success of a standard than they could expect to gain in patent  royalties on any underlying patents. </span></p>
<p>  <span class="style2">Another  cause of confusion and insistence on unnecessary and counterproductive positions  is the superficial similarity between commercial joint ventures and SSOs.&nbsp; In the former, a small number of companies  forms an alliance under a joint development agreement to create a product or  other deliverable that the participants can then sell, or otherwise  exploit.&nbsp; In this type of activity, it  is typical for all participants to cross license all patent claims to each  other that would be infringed by a joint created specification, and to permit  each other to sublicense implementation rights to third parties as well.&nbsp; But the core cross-license rights are  usually restricted to the small number of &quot;by invitation only&quot;  participants, that wish to keep control of the design, as well as the most  lucrative commercial benefits, to themselves.</span></p>
<p class="style2"> In  an SSO, however, the goal is to create a standard that is adopted and  implemented by as many companies as possible.&nbsp;  As a result, every implementer is given equal rights to every other  implementer, as an incentive to participate in the ever widening pool of  adopters.<br />
  <br />
  While both types of efforts involve multiple competitors gathering to agree on  technology solutions, there are several significant differences.&nbsp; First, the participants in a commercial  joint venture are highly motivated to achieve a carefully defined and limited  common goal, and are therefore willing to share all IPR needed to achieve that  goal.&nbsp; Similarly, their partners are  highly motivated to gain access to the same rights, and are therefore willing  to enter into sublicenses and agree to payment terms.&nbsp; The legal vehicle employed by the joint venture participants - a  contract - is appropriate, since few or no new members are expected to join,  and the founding members are not expected to leave until the goal has been  achieved.&nbsp; Finally, there is no need to  create a pretense of &quot;openness.&quot; </p>
<p class="style2"> In  sharp contrast, an SSO needs to allow members to join and leave, and needs to  make it as easy and attractive as possible for non-members of many stripes to  adopt and implement its standards.&nbsp; A  key component in achieving this goal is to be structured and operate in as  &quot;open&quot; a way as possible, to negate any appearance that one or more  companies can unduly influence the eventual nature or availability of its  standards, thus giving them a commercial advantage over other implementers. </p>
<p class="style2"> Since most individuals who  represent companies in SSO activities - and even those who are tasked with  forming new consortia - have limited knowledge about the theory and practice of  SSO formation and operation, it is easy for them to assume that whatever  previous organization they have participated in represents the gold standard of  structure and governance.&nbsp; One  unfortunate outcome of this reality is the surprisingly large number of  consortia that have been formed on the more restrictive commercial joint  development model, even where the tight controls and high demands of that model  were unnecessary.&nbsp; Where this has  occurred, the result has usually been to hamper, rather than lead to, the  success of the organization.<a href="#_ftn15" name="_ftnref15" title="" id="_ftnref15"> </a>&nbsp;<a href="#18">18</a> </p>
<p class="style10"><strong>V&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Current  Issues and Trends</strong></p>
<p class="style2">  Thus  far, this article has described the general shape of IPR policies, positions  and solutions that have prevailed over the past decade.&nbsp; Today, however, some participants in the  standard setting community are calling for significant changes in IPR policies  and practice.&nbsp; Topics currently under  discussion include the following:</p>
<p><strong class="style10"><em>Ex ante disclosure:</em></strong>&nbsp;<span class="style2">  The basic concept behind <em>ex ante</em> disclosure is &quot;earlier is  better, and more is better.&quot;&nbsp; In  practice, what that means is permitting or requiring those that are involved in  creating a standard to state more than just whether they have patents, and  whether they are willing to license them on RAND terms, but what those terms  are in greater detail.</span></p>
<p>  <span class="style2">The  very topic of <em>ex ante</em> disclosure causes alarm for many, due in part to  antitrust concerns.&nbsp; For decades, those  that participated in standard setting activities have been instructed by their  lawyers to never make any mention of prices in a room populated with  competitors.&nbsp; While certainly it is true  that the actual negotiation of prices could have dire results, representatives  of both the Federal Trade Commission as well as the Department of Justice have  made statements in the last two years indicating that <em>ex ante</em> disclosure, properly undertaken, could be looked at favorably by the  regulators, and in fact could have procompetitive, rather than anticompetitive,  effects.</span></p>
<p class="style2"> Recently,  two  ANSI  accredited  SSOs,  the  IEEE  and  VITA, have drafted
amendments  to  their  IPR policies that would permit (in the case of IEEE)
and  require  (in  the case of VITA) the disclosure of the terms upon which
essential  patent  claims  would  be  licensed  under  a draft standard, if
finally  adopted.   Both organizations submitted requests to the Department
of  Justice  for  "business  review  letters,"  under  which  the DOJ would
evaluate  the  SSOs  proposed  ex  ante  procedures.  In each case, the FTC
responded  favorably. The guidance provided in those letters, as well as in
any  letters  that  may  issued  to  other SSOs in the future, will be very
useful to those SSOs that wish to consider similar amendments.</p>
<p class="style2"> The  IEEE and VITA policies will also be reviewed in the context of the rules of the  American National Standards Institute (ANSI), the accreditor of each SSO.&nbsp; That review will be conducted by the ANSI  Executive Standards Council (ExSC), the appointed body for the task under the  ANSI Essential Requirements: Due Process Requirements for American National  Standards. <a href="#19">19</a> <a href="#_ftn1" name="_ftnref1" title="" id="_ftnref1"> </a>&nbsp; As with the DOJ business review letters, the results of these reviews will
be instructive for other ANSI accredited SSOs that may wish to amend their
own policies and procedures.</p>
<p class="style2">  The  overall topic of <em>ex ante</em> disclosure, however, is a difficult one, and  there is a wide variety of opinion regarding the advisability of wide-scale  adoption of changes to permit such disclosures.&nbsp; Some very large companies, particularly in the information  technology sector, are strongly in favor of such changes, while others in the  same market space are opposed.&nbsp; The  reasons for such opposition range from concerns over antitrust exposure, to the  belief that such disclosures will not prove to be useful, to a desire to retain  as much freedom of movement as possible in order to maximize licensing returns.<a href="#_ftn2" name="_ftnref2" title="" id="_ftnref2"> </a><a href="#20">20</a></p>
<p><span class="style10"><strong><em>Royalty free licensing:</em></strong>&nbsp;</span>  <span class="style2">There has long been a preference in many sectors for adopting standards  that would successfully avoid infringing patents that would have price tags  attached.&nbsp; With the advent of the Web,  this objective became more determined in some organizations, and in particular  in the World Wide Web Consortium (W3C), an organization with a broad technical  program, a very large membership (including most of the largest IT companies in  the world), and an important mission.&nbsp;  Those who participated in the revision committee at the W3C endured a  marathon, three-year process that eventually resulted (in May of 2003) in an  amended IPR policy intended to make it nearly impossible to finally approve a  standard that knowingly would result in the requirement of paying a royalty or  other fee to a patent owner.<a href="#_ftn3" name="_ftnref3" title="" id="_ftnref3"> </a> <a href="#21">21</a></span> </p>
<p class="style2">  The  arduous process followed by the W3C involved the business and legal  representatives of many of the largest technology companies in the world, and  marked something of a watershed.&nbsp; Prior  to the approval of the new policy, such an outcome would be been difficult to  imagine, but afterwards, other SSOs could more seriously consider adopting  policies that either mandated the same result, or permitted individual working  groups to operate under a similar rule set.&nbsp;  The Organization for the Advancement of Structured Information Standards  (OASIS) took this approach in an amended policy (which itself took two and a  half years to complete) that was adopted on April 15, 2005.<a href="#_ftn4" name="_ftnref4" title="" id="_ftnref4"> </a> <a href="#22">22</a> </p>
<p><strong class="style10"><em>Open source licensing:</em></strong><strong>&nbsp; </strong><span class="style2">Many of the licenses under which &quot;open source&quot;  software, and in particular &quot;free and open source software&quot; (FOSS),  prohibit certain types of conduct on the part of anyone that wishes to  commercially redistribute a software product that includes the open source  software, whether in whole or in part.&nbsp;  As has already been mentioned, some of those prohibitions relate to  terms that would be otherwise acceptable in licenses that apply to patents  underlying the implementation of open standards.&nbsp; </span></p>
<p class="style2">  The  result has been not only a periodic clash between advocates of open source  licensing and developers of open standards, but further complications for the  already difficult process of achieving consensus over IPR policy rules. <a href="#23">23</a> <a href="#_ftn5" name="_ftnref5" title="" id="_ftnref5"> </a>&nbsp; When OASIS adopted the new IPR policy noted  above, it added a track under which a given working group could decide to  create a standard under rules conducive to open source implementations (it also  included tracks that allow only RAND-free implementations, and finally a third  track, that would allow RAND-royalty assertions).<a href="#_ftn6" name="_ftnref6" title="" id="_ftnref6"> </a> <a href="#24">24</a> </p>
<p><strong class="style10"><em>Harmonization:</em></strong>&nbsp; <span class="style2">Given the  difficulty of achieving consensus on IPR policy terms and the great amount of  effort that negotiations over such terms can consume, several recent  initiatives have been directed at harmonizing, or at least better  understanding, IPR terms.</span></p>
<p class="style2"> One  such effort has been underway in a subcommittee of the American Bar Association  for over two and a half years.&nbsp; During  this period, attorneys have been meeting regularly by telephone and in person  to create an illustrative IPR policy, with annotations explaining the rationale  behind common IPR policy terms.&nbsp; One important  goal of this project is to permit new SSOs, as well as existing SSOs that wish  to upgrade their IPR policies, to more easily achieve consensus over what their  own IPR policy should state.</p>
<p><span class="style2"> Another  effort relates to making it less confusing and burdensome to participate in  multiple SSOs.&nbsp; On March 19, 2007, the  three &quot;Big I's&quot; of global standardization, the International  Organization for Standardization (ISO), the International Electrotechnical  Commission (IEC) and the International Telecommunication Union (ITU), jointly  announced that they had &quot;harmonized&quot; and &quot;aligned&quot; their  respective patent policies.<a href="#_ftn7" name="_ftnref7" title="" id="_ftnref7"> </a> <a href="#25">25</a></span> </p>
<p><span class="style10"><strong><em>RAND specificity:</em></strong>&nbsp;</span>  <span class="style2">Although no specific actions are known to this author to be underway,  the vagueness of a RAND declaration is becoming the subject of increasing  criticism, as well as litigation, as earlier noted.&nbsp; While mandatory <em>ex ante</em> disclosure requirements could moot  the need for RAND declarations entirely in some SSOs, it is possible that other  SSOs may someday decide to more precisely define exactly what RAND should mean  instead, in order to narrow the scope for potential downstream surprises.</span></p>
<p class="style10"><strong>VI&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Summary</strong></p>
<p>  <span class="style2">It  would be an extreme understatement to suggest that the technology industry has  reached a state of clear consensus on what constitutes the ideal IPR  Policy.&nbsp; A single example from the  author's experience will demonstrate how elusive a goal such a state of  universal enlightenment could prove to be.&nbsp;  Not long ago, I spoke separately with two in-house attorneys from the  same company, on the same day, relating to the IPR policies of two different  consortia.&nbsp; In each case, the lawyer to  whom I spoke was adamant in his contention that his company could not, and  would not, join any SSO with an IPR policy that included the language in  question.&nbsp; The problem was, of course,  that the language under discussion in each case was essentially the same, while  the positions taken by the two attorneys were completely opposite.</span></p>
<p class="style2"> The  good news is that awareness of the issues at stake in IPR policies has risen  remarkably, in part due to the fact that several high-profile cases involving  standard setting abuse have been recently litigated.&nbsp; While this increased attention has brought more stakeholders into  the discussion, and therefore has slowed the process of achieving consensus,  that same dialogue has served to make those participating in these discussions  better versed regarding common IPR policy concerns, as well as better  acquainted with the compromise terms upon which these concerns are most likely  to be resolved. </p>
<p class="style2"> Notwithstanding  this relative progress, it will likely remain a challenge for each SSO to craft  an IPR policy that all of its members can live with, and which can still  facilitate the achievement of standard setting goals.&nbsp; While the process of promulgating a robust policy can hardly be  described as recreational, it is a task that cannot be avoided by any new  consortium that wishes to recruit members.&nbsp;  Similarly, every existing SSO that has not reviewed its IPR policy in  recent years would be well advised to subject its process and rules to a  critical analysis, with the goal of purging it of ambiguities and to bring it  up to date with current member expectations. </p>
<p class="style2"> For  an existing consortium, tackling an overhaul of current policies will  inevitably be a challenge.&nbsp; But for the  members of a new consortium, there is an advantage for tackling the process  while their numbers are few, and consensus is therefore more easily  achieved.&nbsp; Thus, the virtue of facing up  to a rather thankless chore early on will be rewarded by an easier path to a  successful conclusion.&nbsp; Those who shrink  from that chore will inevitably face a much more difficult task down the road.</p>
<p class="style2"><a href="/subscribe/"><img src="/images/subscribe-csb.gif" alt="subscribe" width="130" height="25" border="0" /></a></p>
<p align="center" class="style2"><em>Comments? </em> Email: <script language="javascript" type="text/javascript">AuConAdd();</script></p>
<p align="center" class="style2"> Copyright 2007 Andrew Updegrove </p>
<p class="style2"><strong>End Notes</strong></p>
<div class="style2">
  <div id="ftn1"><br />
      1. <a name="1" id="1"></a><a href="#_ftnref1" name="_ftn1" title="" id="_ftn1"> </a> Perhaps this fact explains the two major models that  arose to create ICT standards outside of the accredited process during these  years: the &quot;promoter-adopter&quot; model that was very frequently employed  (and still is) in the microprocessor industry, and the incorporated, nonprofit  membership organization that was almost always employed in the software  space.&nbsp; The former model can accurately  be described as a &quot;by invitation only&quot; cross-license, with right to  sub-license, contractual arrangement that usually relates to a single standard,  while the latter is a more flexible creation that usually allows anyone to  join, and which is well suited to create many standards over time.&nbsp; The promoter-adopter model therefore allows  close controls to be maintained over patent rights, while the structure of the  latter usually has a very simple membership application, and therefore must  rely upon the adoption and administration of an IPR policy to address patent  issues.&nbsp; </div>
  <div id="ftn2">
    <p>2. <a name="2" id="2"></a><a href="#_ftnref2" name="_ftn2" title="" id="_ftn2"> </a> The Consent Decree itself is somewhat ambiguous, and  does not clearly state that Dell knowingly withheld disclosure.&nbsp; Whether this vagueness is due to any  uncertainty on the part of the FTC, or simply reflects negotiation between the  parties, is unknown to this author.&nbsp; The  practical effect, however, may have been to raise greater alarm among other  standards process participants.&nbsp; For a  brief summary of the case, see  &lt;http://www.consortiuminfo.org/laws/#dell&gt;.&nbsp; For the full text of the Decision and Order, see  &lt;http://cyber.law.harvard.edu/seminar/internet-client/readings/Week10/ftc_complete.doc&gt;.</p>
  </div>
  <div id="ftn3">
    <p>3. <a name="3" id="3"></a><a href="#_ftnref3" name="_ftn3" title="" id="_ftn3"> </a> The many private suits and public prosecutions  involving Rambus would require thousands of words to summarize.&nbsp; For a short summary and the most recent  developments in the FTC's action against Rambus, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/feb07.php#update">FTC Caps Rambus  Royalties</a>, ConsortiumInfo.org, Consortium Standards Bulletin, Vol. VI, No.  2, February , 2007, at  &lt;http://www.consortiuminfo.org/bulletins/feb07.php#update&gt;, and sources  sited therein.&nbsp; The most recent activity  in the Qualcomm suit is summarized at Updegrove, Andrew, <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20070323094639964">Federal  Court Convicts Qualcomm in a &quot;Son of Rambus&quot; Suit</a>,  ConsortiumInfo.org, The Standards Blog, March 23, 2007, at  &lt;http://www.consortiuminfo.org/standardsblog/article.php?story=20070323094639964&gt;.</p>
  </div>
</div>
<div class="style2">
  <div id="div">4. <a name="4" id="4"></a><a href="#_ftnref1" name="_ftn1" title="" id="_ftn1"> </a> Typical copyright license language in an IPR policy  might read as follows (the example is taken from the current version of the  policy template the author has used in assisting over 60 SSO clients create or  upgrade an IPR policy):
    <p>&quot;Each Submitter that contributes copyrighted materials to the  Consortium shall retain copyright ownership of its original work, while at the  same time granting the Consortium a non-exclusive, irrevocable, worldwide,  perpetual, royalty-free license under the Submitter&rsquo;s copyrights in its  Submission to reproduce, distribute, publish, display, perform, and create  derivative works of the Submission based on that original work for the purpose  of developing a Draft Specification, Specification or Other Work Product under  the Consortium's own copyright.&quot;</p>
  </div>
  <div id="div2">
    <p>5. <a name="5" id="5"></a><a href="#_ftnref2" name="_ftn2" title="" id="_ftn2"> </a> As noted in the brief filed with the Supreme Court  by the SDO in the Veeck case, &quot;Does the government's decision to make the  copyrighted proposals binding place the copyrighted material in the public  domain? The First Circuit said maybe. The Second and Ninth Circuits said no.  And nine of fifteen Fifth Circuit judges said yes.&rdquo;</p>
  </div>
  <div id="div3">
    <p>6. <a name="6" id="6"></a><a href="#_ftnref3" name="_ftn3" title="" id="_ftn3"> </a> For a detailed examination of trademarks,  certification and branding, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/cb/">Certification Testing and Branding</a>,  the Essential Guide to Standard Setting Organizations and Standard Setting,  ConsortiumInfo.org, at &lt; http://www.consortiuminfo.org/cb/&gt;</p>
  </div>
  <div id="ftn4">
    <p>7. <a name="7" id="7"></a><a href="#_ftnref4" name="_ftn4" title="" id="_ftn4"> </a> The question of what constitutes an &quot;open  standard&quot; is at best an open question, upon which there are many opinions  (and definitions).&nbsp; For more on this  topic, see the <a href="http://www.consortiuminfo.org/bulletins/mar05.php#editorial">Editorial</a>, <a href="http://www.consortiuminfo.org/bulletins/mar05.php#feature">Feature  Article</a> and <a href="http://www.consortiuminfo.org/bulletins/mar05.php#trends">Trends Article</a> in the March 2005 issue of the Consortium Standards Bulletin, titled <a href="http://www.consortiuminfo.org/bulletins/mar05.php">What Does  &quot;Open&quot; Mean?</a> (Vol. IV, No. 3), at &lt;  http://www.consortiuminfo.org/bulletins/mar05.php&gt;.</p>
  </div>
  <div id="ftn5">
    <p>8. <a name="8" id="8"></a><a href="#_ftnref5" name="_ftn5" title="" id="_ftn5"> </a> The author favors the former approach, in part  because it makes the membership application less intimidating.&nbsp; The application provides that the Board can  unilaterally amend the policy as required over time, but also provides that no  such amendment may be retroactive, and can only go into effect after at least  60 days notice has been given to the membership.&nbsp; This allows any member that objects to the change to resign its  membership.</p>
  </div>
  <div id="ftn6">
    <p>9. <a name="9" id="9"></a><a href="#_ftnref6" name="_ftn6" title="" id="_ftn6"> </a> For much more on creating an SSO technical process,  and the rules required to operate it, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/creating_an_sso_process/">Creating a  Standard Setting Organization Technical Process (a Practical Primer)</a>,  ConsortiumInfo.org, <a href="http://www.consortiuminfo.org/essentialguide/">The  Essential Guide to Standard Setting Organizations and Standards</a>, at &lt;  http://www.consortiuminfo.org/creating_an_sso_process/&gt;</p>
  </div>
  <div id="ftn7">
    <p>10. <a name="10" id="10"></a><a href="#_ftnref7" name="_ftn7" title="" id="_ftn7"> </a> Rambus was successful in some, but not all, of the  suits in which it was involved largely as a result of convincing the finder of  facts that the JEDEC IPR policy was vague and inconsistently described to JEDEC  members.</p>
  </div>
  <div id="ftn8">
    <p>11. <a name="11" id="11"></a><a href="#_ftnref8" name="_ftn8" title="" id="_ftn8"> </a> When asked to assist a new client in revising its  IPR policies and procedures, the author has often found that members have been  permitted to use whatever language they wished when disclosing patent claims  that might be infringed by a standard, and in making licensing  commitments.&nbsp; Frequently, those  commitments were so vague and brief as to be legally unenforceable, whether by  accident or design.</p>
  </div>
  <div id="ftn9">
    <p>12. <a name="12" id="12"></a><a href="#_ftnref9" name="_ftn9" title="" id="_ftn9"> </a> The text of this section has been adapted and  updated from the oral and written testimony presented by the author before the Department of Justice and the Federal  Trade Commission at hearings held on April 18, 2002 on the topics of consortia  and standard setting, titled <a href="http://www.ftc.gov/opp/intellect/020418updegrove1.pdf">Is There a Need  for Government Regulation of Standard Setting?</a>. The original text of that  testimony may be found at &lt;  http://www.ftc.gov/opp/intellect/020418updegrove1.pdf&gt;.</p>
  </div>
  <div id="ftn10">
    <p>13. <a name="13" id="13"></a><a href="#_ftnref10" name="_ftn10" title="" id="_ftn10"> </a> While a typical IPR policy will require a member to  make a binding commitment that it will license its essential claims on RAND  terms if it is disposed to do so, it does not require a member to decide at  that point in time that it definitively would <em>refuse</em> to do so.&nbsp; Instead, the policy will phrase a negative  choice in terms of reserving the right to withhold a RAND license.&nbsp; The reason that a more definitive statement  is not required is that, for all practical purposes, a &quot;maybe&quot; is as  unhelpful as a &quot;no.&quot;</p>
  </div>
  <div id="ftn11">
    <p>14. <a name="14" id="14"></a><a href="#_ftnref11" name="_ftn11" title="" id="_ftn11"> </a> This is the specific behavior in which Rambus was  found to have engaged.</p>
  </div>
  <div id="ftn12">
    <p>15. <a name="15" id="15"></a><a href="#_ftnref12" name="_ftn12" title="" id="_ftn12"> </a> This has been the public position of IBM, the owner  of one of the largest patent portfolios in the world, for some years.</p>
  </div>
  <div id="ftn13">
    <p>16. <a name="16" id="16"></a><a href="#_ftnref13" name="_ftn13" title="" id="_ftn13"> </a> At least two disputes have been in the courts this  year, however, involving the application of a RAND commitment to specific  licensing terms.&nbsp; The first involves  QUALCOMM Corporation, as licensor, and six mobile wireless technology  companies, each of which has filed a complaint with the European Commission,  alleging that Qualcomm is violating EU competition law and failing to meet the  commitments it made to international standards bodies to license its technology  on fair, reasonable and non- discriminatory terms.&nbsp; See, <a href="http://www.broadcom.com/press/release.php?id=774809">Leading  mobile wireless technology companies call on European Commission to investigate  Qualcomm's anti-competitive conduct</a>, at &lt;  http://www.broadcom.com/press/release.php?id=774809&gt;.&nbsp; A second and similar suit was recently  brought by Foundry Networks, Inc. against Alcatel, Inc., relating to an IEEE  standard.&nbsp; See, Updegrove, Andrew,<a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20060808090427739"> Foundry Networks Files &quot;Son of Rambus&quot; Suit Against Alcatel</a>,  ConsortiumInfo.org, The Standards Blog, August 8, 2006, at &lt; <a href="http://www.consortiuminfo.org/standardsblog/article.php?story=20060808090427739">http://www.consortiuminfo.org/standardsblog/article.php?story=20060808090427739</a>&gt;.&nbsp; This case was settled and dismissed last  week under an order of dismissal that binds both parties to keep the terms of  the settlement confidential.&nbsp; No helpful  guidance on the true meaning of RAND will therefore be forthcoming from this  court, unfortunately.</p>
  </div>
  <div id="ftn14">
    <p>17. <a name="17" id="17"></a><a href="#_ftnref14" name="_ftn14" title="" id="_ftn14"> </a> For further examples of problems with RAND usage,  see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/jun06.php#blog">Microsoft, Adobe  and the Murky World of &quot;RAND,&quot;</a> ConsortiumInfo.org, The Standards  Blog, June 7, 2006, at &lt; http://www.consortiuminfo.org/bulletins/jun06.php#blog&gt;. </p>
  </div>
  <div id="ftn15">
    <p>18. <a name="18" id="18"></a><a href="#_ftnref15" name="_ftn15" title="" id="_ftn15"> </a> When this is later realized, such an  organization often restructures itself, and adopts a more open model.&nbsp; I have assisted in several such latter day  conversions, all of which were followed by increased success for the SSOs  involved. </p>
  </div>
</div>
<div>
  <div class="style2" id="div4">19. <a name="19" id="19"></a><a href="#_ftnref1" name="_ftn1" title="" id="_ftn1"> </a> The review process for SSOs that develop American  National Standards is described in Section 4.1.3 of the Essential Requirements,  which&nbsp; provides in part as follows:
      <blockquote>
        <p>Whenever  any revision is made to a standards developer&rsquo;s procedures on record at ANSI,  the ExSC shall be notified and provided with a detailed description of the  changes. If the changes are considered by the ExSC to be non&#8209;substantive, the  standards developer will be notified and, upon such notification, may begin to  operate under the revised procedures.&nbsp;  If the changes are considered by the ExSC to be substantive, notice of  these changes shall appear in <em>Standards  Action</em> with a call for comment. Copies of the revised procedures shall be  made available by the applicant to any party, upon request.&nbsp; If a developer submits their procedures in  an electronic format and authorizes ANSI to post them on <em>ANSI Online</em> for purposes of public review, then the associated call  for comment period in ANSI&rsquo;s <em>Standards  Action </em>shall be 30 days and shall be announced as such.</p>
      </blockquote>
    <p><a href="http://publicaa.ansi.org/sites/apdl/Documents/Standards%20Activities/American%20National%20Standards/Procedures,%20Guides,%20and%20Forms/Essential%20Requirements%20Jan3107.doc">Essential  Requirements</a> (January 2007), Section 4.1.3, page 14, <a href="http://publicaa.ansi.org/sites/apdl/Documents/Standards%20Activities/American%20National%20Standards/Procedures,%20Guides,%20and%20Forms/Essential%20Requirements%20Jan3107.doc">available here</a>.</p>
  </div>
  <div class="style2" id="div5">
    <p>20. <a name="20" id="20"></a><a href="#_ftnref2" name="_ftn2" title="" id="_ftn2"> </a> For a much longer analysis of ex ante issues and  recent events, see Updegrove, Andrew, <a href="http://www.consortiuminfo.org/bulletins/jun06.php#feature">Ex Ante  Disclosure: Risks, Rewards, Process and Alternatives, ConsortiumInfo.org,  Consortium</a> Standards Bulletin, Vol. V, No. 6 (June 2006), at &lt; <a href="http://www.consortiuminfo.org/bulletins/jun06.php#feature">http://www.consortiuminfo.org/bulletins/jun06.php#feature</a>&gt;,  and sources cited therein, as well as the other articles in the same issue.</p>
  </div>
  <div class="style2" id="div6">
    <p>21. <a name="21" id="21"></a><a href="#_ftnref3" name="_ftn3" title="" id="_ftn3"> </a> Section 2 of the W3C Patent Policy now provides as follows:</p>
    <blockquote>
      <p>In order to promote the widest adoption of Web  standards, W3C seeks to issue Recommendations that can be implemented on a <a href="http://www.w3.org/Consortium/#def-RF">Royalty-Free</a> (RF) basis.  Subject to the conditions of this policy, W3C will not approve a Recommendation  if it is aware that <a href="http://www.w3.org/Consortium/#def-essential">Essential  Claims</a> exist which are not available on Royalty-Free terms. </p>
    </blockquote>
    <p>W3C Patent Policy 20  May 2003, at &lt; <a href="http://www.w3.org/Consortium/Patent-Policy-20030520.html">http://www.w3.org/Consortium/Patent-Policy-20030520.html</a>&gt;.&nbsp; The current policy, incorporating minor  changes, was adopted with insubstantial amendments on February 5, 2004, and can  be found at &lt; http://www.w3.org/Consortium/Patent-Policy-20040205/&gt;.</p>
  </div>
  <div class="style2" id="div7">
    <p>22. <a name="22" id="22"></a><a href="#_ftnref4" name="_ftn4" title="" id="_ftn4"> </a> OASIS Intellectual Property Rights (IPR) Policy,  adopted April 15, 2005, at &lt;  http://www.oasis-open.org/who/intellectualproperty.php&gt;.</p>
  </div>
  <div class="style2" id="div8">
    <p>23. <a name="23" id="23"></a><a href="#_ftnref5" name="_ftn5" title="" id="_ftn5"> </a> For more on the efforts to reconcile the needs of  the open source and open standards communities, see the following prior issues  of the Consortium Standards Bulletin:&nbsp; <a href="http://www.consortiuminfo.org/bulletins/may06.php">Bridging the Open  Source- Open Standards Divide</a>, Vol. V, No. 5 (May 2006), at &lt; <a href="http://www.consortiuminfo.org/bulletins/may06.php">http://www.consortiuminfo.org/bulletins/may06.php</a>&gt;  and What Does &quot;Open&quot; Mean?,&nbsp;  Vol. IV, No. 3 (March 2005), at  &lt;http://www.consortiuminfo.org/bulletins/mar05.php&gt;. </p>
  </div>
  <div class="style2" id="div9">
    <p>24. <a name="24" id="24"></a><a href="#_ftnref6" name="_ftn6" title="" id="_ftn6"> </a> In exchange for its troubles, open source advocates  led by Larry Rosen issued a call to <a href="http://perens.com/Articles/OASIS.html">boycott OASIS standards</a>,  because OASIS had not converted its entire IPR policy to the open-source  friendly rule set. &nbsp;This Call to Action  may be viewed at &lt; <a href="http://perens.com/Articles/OASIS.html">http://perens.com/Articles/OASIS.html</a>&gt;.&nbsp; While much in the news in 2005, this issue  seems to have inexplicably faded from view more recently.&nbsp; Presumably, this is a temporary lull rather  than a permanent truce, given that real issues underlying these concerns remain  to be resolved.&nbsp; </p>
  </div>
  <div class="style2" id="div10">    25. <a name="25" id="25"></a><a href="#_ftnref7" name="_ftn7" title="" id="_ftn7"> </a> See the following ITU press release: <a href="http://www.itu.int/newsroom/press_releases/2007/05.html">IEC, ISO and  ITU, the world&rsquo;s leading developers of international standards agree on common  patent policy</a>, at &lt;  http://www.itu.int/newsroom/press_releases/2007/05.html&gt;.&nbsp; The press release describes the action taken  as follows:
    <blockquote>
      <p class="style2">The  world&rsquo;s leading international standards organizations have adopted a harmonized  approach to address the inclusion of patented technology in standards. IEC  (International Electrotechnical Commission), ISO (International Organization  for Standardization) and ITU, under the banner of the World Standards  Cooperation (WSC), have aligned their policies which allow for commercial  entities to contribute the fruits of their research and development (R&amp;D)  activity safe in the knowledge that their intellectual property rights are  respected. </p>
    </blockquote>
  </div>
</div>
<p class="style2">&nbsp;</p>
<div><div id="ftn22"></div>
</div>
</body>
</html>
