<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>FEATURE ARTICLE</title>
	</head>

	<body>
				<!-- ******************* -->
				<!--   FEATURE ARTICLE   -->
				<!-- ******************* -->
				<h3>ICT STANDARD SETTING TODAY:<br />A SYSTEM UNDER STRESS</h3>
				<p class="center"><a href="http://www.lpu.com/attorneys/updegrove.shtml">Andrew Updegrove</a></p>
				<blockquote class="openingquote"><strong><em>Abstract:</em></strong>  <em>The modern standards development infrastructure is largely the product of the industrial age, and evolved to address the needs of such an economy.  The requirements of a world that is increasingly based upon information and communications technology, however, are far different, and include demands for faster standards development, less vulnerability to uncooperative owners of necessary patent claims, and a greater need for universal, global adoption of core enabling standards.  These needs have been partially addressed through several organic developments, such as the proliferation of consortia, the evolution of more detailed intellectual property rights policies, and the passage of the World Trade Organization's Technical Barriers to Trade Act.  But the advent of the Internet and the Web, and the continuing introduction of new ICT-based products and services in ever shorter and more frequent product cycles, are exposing the fact that a system that retains strong roots in the 19th century is ill-suited to meet the demands of the 21st.  In this article, I survey some of the areas of inadequacy inherent in the current system, the ways in which society is being impacted by new standards-dependent technologies, and the situations in which governments may feel called upon to intervene.</em> </blockquote>
				<p><strong><em>Introduction:</em></strong>  For most of the first hundred years of the modern era of standard setting, standards developers focused their attention on the attributes of tangible objects.  The standards they developed specified dimensions, materials and other physical attributes, and to the extent that they addressed intangibles, those elements were result-oriented, such as performance and safety.  Similarly, interoperability standards were physical standards, intended to ensure that part A would fit with part B. </p>
				<p>These standards were created by domain experts, and by interested parties within the market niches that produced the products involved.  Usually, problems requiring standards solutions could be addressed within a single standard setting organization (SSO).</p>
				<p>In a world of physical objects, standards development could conveniently lag product development.  Only after screws, steam power and electric lights had proven to be popular did a demand develop for standards to establish common thread gauges, boiler safety guidelines, and light socket dimensions.  Even in the case of networks, the same held true, as railroads, power companies and telephone services were all launched as local enterprises, using available proprietary implementations.  Not until these discrete networks were joined did the need for nationwide interoperability standards arise.</p>
				<p>Such after the fact, non-urgent standard setting could, and sometimes did, have advantages.  For example, products that were inherently well designed and successful were more likely to become the models for de facto or de jure standards.  Similarly, when cycles of innovation are widely spaced and their results long lasting (Edison's light bulbs, in comparison to yesterday's floppy disks, remain in use today), taking time to achieve the best standards result represents a wise investment, due to the length of time that the market will be "locked in" by the decisions made.</p>
				<p>Due to communication, travel and trade constraints, among other causes, most of the SSOs that were founded to meet evolving standards needs were national in scope (with notable exceptions, such as the International Telecommunication Union, or ITU).  But after the Second World War, the internationalization of standards increased under the auspices of several global standards bodies that were formed in addition to the ITU, most notably the International Organization for Standardization (ISO) and International Electrotechnical Commission (IEC).  But domestic standards can be used to protect domestic manufacturers from the competition presented by foreign goods, and at times this provided a disincentive to locally implement useful standards, even after a global authority had adopted them.</p>
				<div class="calloutleft">
					<p>In short, the initial standard setting infrastructure that evolved to serve the needs of the maturing industrial age was adequate, but also limited, to the specific demands that were placed upon it by the commerce of the day.</p>
				</div>
				<p>In a time of primarily performance, material and physical interoperability standards, patent infringement was rarely an issue for most SSOs.  Instead, when intellectual property rights (IPR) were mentioned, if they were mentioned at all, it was copyrights that were usually under discussion, since most SSOs funded their efforts in whole or in part through the sale of paper versions of their work product.  When IPR policies were eventually created and adopted, they were high-level statements of principles, and lacked implementational details.  Moreover, for many standards there was no proprietary advantage to be gained by any stakeholder as a result of a given standard coming out in one way rather than another.</p>
				<p>In short, the initial standard setting infrastructure that evolved to serve the needs of the maturing industrial age was adequate, but also limited, to the specific demands that were placed upon it by the commerce of the day.</p>
				<p>With the advent of the computer age, however, the need arose for new types of consensus-based specifications that have as much in common with non-technical standards as with the historical work products of SSOs (computer languages being an example).  As technological innovation increased in many disciplines, the need for new standards implemented in software, silicon, wireless broadcasts, fiber optics and hardware emerged to serve the needs of (in particular) the information and communications technology (ICT) industries, and that need soon expanded dramatically.  With the explosive success of the Internet, the utility and value of globally accessible, networked products, services and content has today become enormous.</p>
				<div class="calloutleft">
					<p>Our new, networked world holds unprecedented opportunities for those that have hitherto been denied access to modern education, information and opportunities.  It also offers a platform that both public as well as private entities are enthusiastically embracing, resulting in a world where ICT access is becoming a prerequisite to enjoying the full rights and opportunities of society, democracy and the economy.  </p>
				</div>
				<p>Our new, networked world holds unprecedented opportunities for those that have hitherto been denied access to modern education, information and opportunities.  It also offers a platform that both public as well as private entities are enthusiastically embracing, resulting in a world where ICT access is becoming a prerequisite to enjoying the full rights and opportunities of society, democracy and the economy.  That access is only feasible, however, if standards exist to address local character sets, languages, and physical disabilities.  Concerns such as these are far different from those encountered in developing standards for networking, and most existing ICT SSOs are neither interested in, nor even highly aware of, such needs.</p>
				<p>At the same time, single standards can no longer solve many of the problems that new ICT opportunities are presenting, or even suites of standards created by a single SSO.  Instead, increasingly complex collections of standards created by many SSOs, often with very different rules regulating IPR, must be cobbled together in order to do what needs to be done.</p>
				<div class="calloutright">
					<p>Who, then, should &ndash; and who is competent - to develop the standards required to feed the needs of this brave new ICT-enabled world?  Is the traditional standard setting infrastructure adequate to the task, either technically or democratically?  And to the extent that it is not, how, and by whom, and to what result will its shortcomings be addressed?</p>
				</div>
				<p>Who, then, should &ndash; and who is competent - to develop the standards required to feed the needs of this brave new ICT-enabled world?  Is the traditional standard setting infrastructure adequate to the task, either technically or democratically?  And to the extent that it is not, how, and by whom, and to what result will its shortcomings be addressed?</p>
				<p>In this article, I will review some of the principle ways in which the traditional standard setting infrastructure is inadequate to the task of supplying the ICT standards of the future.  I will also describe some of the organic solutions that have already been developed by industry participants, and provide thoughts on how those issues that remain unresolved might be productively addressed.</p>
				<p><strong><em>Standards challenges</em></strong>:  When one examines the ICT standards needs of the future, it becomes immediately apparent that almost none of the dynamics that led to the evolution of the traditional standard setting infrastructure remain unchanged today.  Consider, for example, the following:</p>
				<p><strong><em>Interoperability demands: </em></strong> Unlike physical products, the fruits of ICT technologies require a large number of interoperability standards in order to function and flourish.  This offers vendors the choice of trying to dominate a market, through the creation of a de facto standard (e.g., the VHS video format), and reaping large royalty rewards, or of collaborating with other vendors to develop a consensus-based standard that may more quickly and certainly create a new market that is shared by all.  When vendors choose to roll the dice on the former approach, damaging standards wars can result.</p>
				<p><strong><em>Innovation cycles: </em></strong> As noted, technology generations in many areas are becoming shorter with each cycle.  This results in pressure to create and deploy standards more quickly.  Otherwise, they may be useless by the time that they are released.  As a result, it is less feasible for standards creation to follow product introduction, because the useful life of the standard is short.  The only way to dramatically reduce time to market with a standard is therefore to develop both the standard as well as the products that will comply with it on a concurrent basis.  </p>
				<p>All will be well if those that are interested in a new product space decide to collaborate on a single standard.  But if there are competing technologies, then each may wish   or indeed have no choice, if the technologies are fundamentally different  &ndash; but to create its own standard(s) as a precondition to testing its products in the marketplace.  The result can be either a healthy standards "competition," that enables multiple technologies to test themselves in the marketplace, with each finding its respective niche (as has occurred with the WiFi and Bluetooth standards, which were initially in competition with each other, but have now settled into the respective, non-competitive uses for which each it is best suited) or a standards war between standards that may have little useful differentiation between them in consumers' eyes (as is currently the case with the Blu-Ray and HD-DVD next generation video standards).</p>
				<p><strong><em>Network prevalence:</em></strong>  More and more ICT technologies must be used in connection with networks, but non-proprietary networks cannot form until the standards that enable them are created.  It is axiomatic that the larger a network becomes, the more value can be derived by those that are connected to it.  This drives up the value of both the network as well as the products and services that can be linked to, or provided through, it, and which therefore become more attractive to potential purchasers.  To the extent that one standards solution favors one vendor more than another, an incentive is therefore created to influence the outcome.  In the case of the increasing number of patent "trolls" that develop or purchase IPR solely for the purpose of reaping licensing revenues, placing a patent claim in the way of the implementation of such a standard has the potential to reap huge rewards.</p>
				<div class="calloutleft">
					<p>Technology generations in many areas are becoming shorter with each cycle.  This results in pressure to create and deploy standards more quickly.  Otherwise, they may be useless by the time that they are released.  As a result, it is less feasible for standards creation to follow product introduction, because the useful life of the standard is short.  </p>
				</div>
				<p><strong><em>Freedom from lock-in: </em></strong> End-users have become more conscious of the fact that requiring the implementation of "open standards" in the ICT products they purchase can lead to wider choices, cheaper prices (through competition) and real protection from vendor lock in.  Such standards create opportunities for new entrants into product and service areas, but also threaten incumbents that may currently control those niches.  As a result, some industry participants will have more to gain by blocking and delaying standards efforts than by promoting and supporting them.</p>
				<p><strong><em>IPR infringement:</em></strong>  ICT standards are unusually susceptible to infringing the patents of SSO members, and of greater concern, non-members as well, due to the density of patents that may exist in areas where standardization is most needed.  The result is that standards are increasingly being developed in  areas of intense patent activity, often referred to as "patent thickets."  Because owners of patents infringed by a standard can charge royalties or impose specific license terms on implementers of that standard, they may try and cause such infringement to occur during the development process.  But if SSO IPR policies are tightened to lessen this possibility by requiring all such patents to be disclosed before a standard is adopted, participants with large patent portfolios become concerned that they may be required to undertake burdensome patent searches in order to avoid their IPR from becoming subject to obligatory licensing requirements.</p>
				<p><strong><em>Convergence:</em></strong>  Historically, standards were created and used by the same vendors, allowing those vendors to evolve whatever rules and licensing practices they wished within a single SSO and industry niche.  But in ICT, dozens of capabilities and hundreds of standards can be utilized in a single device (e.g., a state of the art cell phone may have 3G telephone, video, Web browsing, wireless, PDA and other capabilities, may utilize any of a number of operating systems, and can host multiple programs and services).  Some of these standards are based upon patent pools, while others may have been developed by SSOs with strict royalty-free policies.  If even a small fraction of these standards bear royalties, the cost of such a device could become prohibitive.  And if too many IPR owners require unique licenses, the burden of obtaining and negotiating necessary rights can become excessively burdensome.</p>
				<p><strong><em>Globalization:</em></strong>  Trade, travel, production and utilization are increasingly becoming global.  In ICT in particular, the concept of a national standard has become archaic.  As a result, there are great needs as well as great incentives to achieve global consensus on the type of uniform standards that can permit products to be sold and used anywhere.  At the same time, the specific standards that are adopted can favor some participants more than others, and therefore some nations and regions (such as the EU) have incorporated standards into their global trade strategies.  Those governments therefore dedicate resources and government attention toward standards strategies as well, and interweave these considerations into other international policy decisions.</p>
				<p>Other forces can complicate globalization as well.  Some standards bear significant royalty loads, which can empower some parts of the world (e.g., the West) with significant trade advantages, because their vendors can sell high-margin, branded products, while nations in other regions (e.g., emerging countries) are relegated to the status of low-cost, low margin job shops supplying finished goods to the owners of the patents that underlie controlling standards, but unable to sell similar goods, at high margins, directly to end-users.  Such advantages can tempt those with large markets and production capabilities (e.g., China) to create their own domestic standards, in order to level the economic playing field, notwithstanding the constraints on such behavior contained in the Technical Barriers to Trade Act among World Trade Organization member nations.</p>
				<p><strong><em>More complex standards problems:</em></strong>  The problems that require standards solutions today are increasingly large and complex, even where the business case being addressed may appear deceptively simple.  Wirelessly printing a picture from a cell phone camera, for example, requires the use and coordination of a variety of different standards, each of which was created by a different SSO with different considerations in mind.  As a result, printer, camera, mobile device and other vendors must all decide which set of standards could perform the desired task, and then each agree to implement that subset of the resulting standards "profile" that relates to their particular products, before their customers can enjoy the type of simple features that will enrich their product experience &ndash; while also enriching the vendors that wish to sell more printer paper, ink and camera-enabled cell phones.</p>
				<div class="calloutleft">
					<p>The problems that require standards solutions today are increasingly large and complex, even where the business case being addressed may appear deceptively simple.  </p>
				</div>
				<p><strong><em>Standards tools:</em></strong>  Unfortunately, the infrastructural tools available to deal with these challenges are in many respects inadequate to the task.  The ICT standards infrastructure today comprises the following principal parts, with the limitations identified:</p>
				<p><strong><em>Accredited standards development organizations (SDOs):</em></strong>  Nations throughout the world have variously complex systems of domestic SDOs.  In most cases, they are "top down" governmental, or quasi-governmental bodies (as in Germany and China), while others are "bottom up" organizations (as in the United States) formed primarily by private industry and other stakeholders, and accredited by a national body (in the United States, that body for most purposes is the American National Standards Institute, or ANSI).  But while some SDOs, such as ASTM, are becoming global in scope, others remain national.  As a result, they are to an extent in competition with the SDOs of other countries to either create and promote domestic standards, or to promote their standards for adoption (in preference to those of other countries) on a global basis.  In addition, since global adoption is necessarily a two-step process, the time between chartering an SDO working group and final global adoption (often following some period of market implementation) can be protracted.  </p>
				<p>While independent in governance, budget and activities, SDOs have multiple points of contact, both domestically as well as internationally.  In the United States, for example, ANSI runs multiple forums, panels and programs in which both SDO members (corporate, government, university, etc.) as well as SDO management members participate.  Internationally, IEC, ISO and ITU have regular plenaries and other meetings, and multiple committees and other working groups are active on standards activities, all of which are peopled by member representatives from around the globe.</p>
				<p><strong><em>Consortia:</em></strong>  Among all SDOs, only a small number are prominent in the ICT sector.  Non-accredited SSOs ("consortia"), however, have proliferated wildly in the IT, and to a lesser extent, the CT, sectors since the late 1980s.  Today, there are more than 500 such organizations in operation, ranging from small, closed vendor clubs that operate on an invitation only basis, to very large, institutionalized, global, open membership organizations.  Some (such as the Object Management Group (OMG), World Wide Web Consortium (W3C) and the Organization for the Advancement of Structured Information Systems (OASIS) have broad and coordinated programs that can enable the accomplishment of comprehensive technical goals.  But many others have been formed to develop and maintain a single standard.  The largest consortia have dozens of staff, but the vast majority operate on a very limited budget, and have only one or a few full time employees, if they have any human resources at all beyond their members' own staff.</p>
				<p>Unlike SDOs, which have various points of formal contact, there is no umbrella organization of any type for consortia, or other formal means by which they meet en masse to address matters of common interest.  </p>
				<div class="calloutleft">
					<p>Among all SDOs, only a small number are prominent in the ICT sector.  Non-accredited SSOs ("consortia"), however, have proliferated wildly in the IT, and to a lesser extent, the CT, sectors since the late 1980s.  </p>
				</div>
				<p><strong><em>The "Big Is:"</em></strong>  The three best-known global standards bodies &ndash; the ITU, IEC and ISO &ndash; play a variable role in ICT standard setting, with more communications than information technology standards arising in SDOs for eventual international adoption.  Far more IT standards are created today in consortia than in SDOs, and only a small percentage of their standards are introduced to the accredited system, despite the creation of avenues such as the "Publicly Available Standard" (PAS) process for that purpose.  When consortium-developed standards are offered for formal adoption, they are usually submitted to a subcommittee of IEC/ISO Joint Technical Committee 1 (JTC 1), which was originally formed to consider (and still processes) SDO-originated IT standards. </p>
				<p>Because most consortia both court and admit members globally, and due to the fact that consortia are commonly founded by transnational companies in the first instance, they are often able to achieve wide international adoption of their standards without seeking the imprimatur of the global accredited standards infrastructure at all.  Increasingly, however, consortium members are urging these SSOs to qualify as PAS submitters so that particular standards that are of significant interest to particular customer groups (such as European governments) that favor, or require, ISO/IEC standardized products, can achieve that status.</p>
				<p><strong><em>Liaison relationships: </em></strong> These many SDOs and consortia are interlinked by a loose network of one-on-one liaison relationships, each typically formalized by a brief, high level "Memorandum of Understanding," if they are formalized at all.  While these relationships can be adequate for maintaining communication and, to a degree, avoiding needless duplication of activities, they are rarely multi-party, and therefore not typically capable of delivering comprehensive solutions to complex problems (such as the camera/printer example noted above).  Moreover, maintaining such relationships well is time consuming and resource intensive, and a typical ICT SSO may maintain 20 to 40 such arrangements.  An SSO with a large full-time staff can task a full-time employee with managing and maintaining such relationships, but a typical consortium is too lightly resourced to afford a dedicated staff person to such a purpose.  As a result, liaison relationships are frequently served by member volunteers, with a greater risk that any given connection may languish, and that overall cohesiveness will suffer.</p>
				<p><strong><em>Participation:</em></strong>  While both SDOs as well as most consortia espouse many of the same open standards principles, some of those principles are honored to a greater or lesser extent in word rather than in the breach.  In the case of SDOs, which are by definition committed to the participation of all those affecting, and affected by, standards ("stakeholders"), the greatest challenge can be attracting all stakeholders into participation.  After all, creating technical standards is not likely to be of great appeal to the average consumer, nor to consumer advocates or to government personnel with more immediate concerns.  Only a few consortia (such as the W3C) include societal concerns and broad non-commercial participation in their charters at all.  In the case of standards that have only societally neutral elements to be specified, such non-participation is likely to be non-problematic.  But in those areas where the interests of all those affected are not congruent, the absence of a watchdog for the unrepresented can be a cause for concern.</p>
				<div class="calloutleft">
					<p>The modern ICT standards infrastructure is a lightweight, highly distributed, and only loosely connected system.  As such, it is democratic, reasonably responsive, and economically efficient.  But it is also ill-suited to address complex problems, and democratic only for those that find it sufficiently in their self-interest to participate.   </p>
				</div>
				<p>In summary, the modern ICT standards infrastructure is a lightweight, highly distributed, and only loosely connected system.  As such, it is democratic, reasonably responsive, and economically efficient.  But it is also ill-suited to address complex problems, and democratic only for those that find it sufficiently in their self-interest to participate.  Moreover, some SSOs are vulnerable to manipulation by the individual companies, and groups of companies, that are willing to dedicate the time and resources needed to support their operations.  </p>
				<p><strong><em>Societal challenges:</em></strong>  At the same time that challenges are increasing for the ICT standards infrastructure, society, commerce and governments are rushing pell-mell towards greater and greater dependence on ICT in general, and on the Internet and the Web in particular.  With astonishing speed, vital services and facilities, such as international banking, communications, travel, utilities, and, indeed, just about everything else of significance in the modern world, has either been redeployed across the Internet, or has become dependent upon the uninterrupted availability of the Internet for its own viability. </p>
				<p>That viability is in the first instance enabled by the protocols and standards that together support the Internet and the Web.  These specifications function as the synapses through which information flows in what has come to be described as the cyberinfrastructure.  </p>
				<div class="calloutleft">
					<p>With astonishing speed, vital services and facilities, such as international banking, communications, travel, utilities, and, indeed, just about everything else of significance in the modern world, has either been redeployed across the Internet, or has become dependent upon the uninterrupted availability of the Internet for its own viability. </p>
				</div>
				<p>But is the infrastructure that creates and maintains these standards, as well as the many others that enable the services, software, and devices that run on top of the Internet and the Web, the right infrastructure to robustly, democratically and securely support the cyberinfrastructure upon which we are increasingly dependent?  There are multiple reasons to believe that it is not, of which the following are examples:</p>
				<ul>
					<li>Three and a half years after the disastrous events of 9/11 exposed the inadequacy of first responder communications, wireless equipment is still incapable of permitting fire, emergency and police responders to reliably and seamlessly communicate.</li>
					<li>China is developing multiple standards for domestic use in areas such as 3G telephone, wireless communication, and video compression due to perceived inequities in the costs of implementing patent-encumbered global standards, arguably in violation of its obligations under the Technical Barriers to Trade Act.  If this practice becomes more common in China, 1.3 billion of the world's inhabitants will be utilizing different standards than the rest of humanity.</li>
					<li>Governments are becoming aware that their wholesale conversion to electronic document production and archiving is leaving them vulnerable to proprietary lock in, as well as future inability to access documents.  OpenDocument Format (ODF), an OASIS-developed standard, has been adopted as an ISO/IEC standard to meet that concern, and it has been implemented in multiple proprietary and open source products.   At the same time (2007), Microsoft is vigorously lobbying the National Bodies entitled to vote in JTC 1 in order to persuade them to adopt Ecma 376, a specification that describes the Office Open XML formats utilized by Microsoft's Office 2007 productivity suite.  However, these National Bodies are complaining about the degree of pressure that is being brought to bear upon them by Microsoft (and its competitors), as well as the speed at which they are being asked to process a specification that is more than 6,000 pages long.</li>
					<li>The legislatures of four US states are currently considering bills that would mandate the use by government of office software based upon "open document formats."   Similar efforts are ongoing in several European nations.   The bills contain language that is in some ways similar, but in no case identical, representing the prospect of a world of divergent definitions of "open standards."</li>
					<li>SSOs have not been successful in adopting IPR policies that are sufficiently stringent to provide real protection against the emergence of "submarine patents," at least without the need for implementers to engage in hugely expensive defensive litigation against the owners of those patents.</li>
					<li>There is no consensus on the definition of "open standards" at a sufficiently useful level of granularity.  New challenges, such as the increasing popularity of open source software, are widening the gap.</li>
					<li>There is a similar lack of uniformity regarding the terms of IPR policies among SSOs.  To the good, a "one size fits all" approach would be unnecessarily restrictive, but to the bad there are needless inconsistencies as among policies that are each attempting to say the same thing.  This erodes certainly and increases complexity in converging technologies.</li>
					<li>The number of commercial disputes over whether a patent owner that has made a commitment to license that IPR on reasonable and nondiscriminatory (RAND) terms is violating that pledge is increasing.</li>
					<li>The IPR policies of most consortia that develop software are inadequate to ensure the implementation of such standards in open source software.</li>
					<li>There is no mechanism for consumers or other stakeholders to participate or to make their concerns known in most ICT SSOs, despite the increasing impact that ICT standards have on their welfare.</li>
					<li>In countries such as the United States, government remains both disengaged, as well as largely unaware, of the increasing importance of ICT standards outside of traditional telecommunications boundaries.</li>
					<li>The importance of the Internet and the Web has been recognized by the United Nations, which chartered the World Summit on the Information Society (WSIS).  However, that multi-year process became mired in a dispute over the continuing right of the United States government, via the Department of Commerce, to oversee the Internet Corporation on Assigned Numbers and Names (ICANN).  Despite two Summit meetings and the participation of thousands of public, private and nonprofit  representatives from around the world, little concrete action has resulted.  Meanwhile, crucial infrastructural work is being undertaken by a handful of small, under-funded and unsung SSOs such as the Uniforum (which seeks to encode the character sets of all existing and archaic languages) and SIL International (which assigns and maintains numeric codes for those languages).</li>
					<li>While the benefits of the Internet and the Web are being made available to more peoples around the world, little progress has been made thus far in implementing accessibility standards (even by governments), to ensure that those with disabilities will be able to enjoy those benefits wherever they may live.</li>
					<li>Standards continue to be created in "silos" by vendors, while end users increasingly need solutions to larger problems that can only be solved by a more holistic approach.</li>
				</ul>
				<p><strong><em>What is to be done:</em></strong>  To be sure, the standards world has responded in a few instances both organically as well as deliberately.  The following are examples:</p>
				<div class="calloutleft">
					<p>While the benefits of the Internet and the Web are being made available to more peoples around the world, little progress has been made thus far in implementing accessibility standards (even by governments), to ensure that those with disabilities will be able to enjoy those benefits wherever they may live. </p>
				</div>
				<p><strong><em>IPR Policy convergence:</em></strong>  There are multiple efforts ongoing, and even accomplished, to achieve greater uniformity and coherence among IPR policies.  Recently, the ITU, IEC and ISO announced a unified IPR policy.  In the case of open document formats, the ODF Alliance, an organization formed to promote the uptake of ODF by governments, has created a model statute to be utilized as a starting point by governments considering enacting legislation to encourage or require to usage of open document formats.  Each of the four bills now under consideration in the United States is in part modeled on that model, and together they are sufficiently in harmony (at least in their current forms) to provide a usable reference point for both SSOs as well as vendors to meet their requirements.  Finally, a subcommittee of the American Bar Association Science and Technology Section has recently completed a multi-year project directed at creating an extensively annotated IPR policy, in part to assist SSOs in creating IPR policies with more uniform terminology. </p>
				<p><strong><em>Metastandard consortia:</em></strong>  A few consortia have been formed to assemble suites of standards capable of solving complex problems.  The camera/printer business case described above is a real world example, and has been addressed by the Mobile Imaging and Printing Consortium (MIPC), a client of the author's.  Another client, the Network Centric Operations Industry Consortium (NCOIC) is undertaking a far more complex challenge: assembling the standards needed to enable members of the US armed forces and those of US allies to identify themselves to a single network, and gain instantaneous access to information that becomes known to that network.</p>
				<p><strong><em>Simultaneous innovation and standardization:</em></strong>  The commercial rewards anticipated from new technologies have been sufficiently attractive to provide the incentive for industry to invest in standard setting simultaneous with innovation, even where it is far from certain that the resulting standard and products will be successful.  Perhaps the best example of this practice can be found in the case of wireless technologies, where a first wave of innovation gave rise to several contenders to dominate the home network space.  One entrant, called HomeRF, failed, despite being supported by a consortium effort.  Another, WiFi, developed by IEEE, an SDO, succeeded in taking the original prize, while the third, Bluetooth, originally developed by Ericsson Mobile Phones and then supported by the Bluetooth Special Interest Group, failed to establish itself in that space, but has become dominant in mobile and certain other devices.  Now a second wave of standards is reaching the market, targeted at other discrete uses, such as Nearfield Communications, a very short-range standard developed by another client of the author, the NFC Forum, which is being used in (for example) contactless payment cards.  Meanwhile, two competing standards will allow home entertainment and computer peripheral equipment to shed their connecting cables, WiMax will provide intermediate range wireless networks, RFID tags and readers are reaching the supply chain, and mesh network standards are being developed to allow the digital home to become a more sophisticated reality.</p>
				<div class="calloutleft">
					<p>The development of standards "swarms" allows the marketplace to simultaneously innovate, productize and standardize, and at the same time for competing technologies to vie for supremacy in the marketplace.   </p>
				</div>
				<p>The development of such standards "swarms" allows the marketplace to simultaneously innovate, productize and standardize, and at the same time for competing technologies to vie for supremacy in the marketplace.  Absent such behavior, new technology based products and services would reach the marketplace far more slowly, and a less robust and rich range of choices would  be available.</p>
				<p><strong><em>The Future:</em></strong>  Useful though these developments may be, they are evolutionary rather than revolutionary.  They do not fundamentally challenge or reorder any existing power relationships among standards stakeholders, or bring any new stakeholders into the process.  Nor do they significantly identify or serve to address societal interests that are both impacted by ICT progress as well as at risk as the importance of cyberinfrastructure grows.</p>
				<p>This dilemma gives rise to many questions: Is revolutionary change needed, or will the infrastructure of the past in fact be sufficient to address the cyberinfrastructural demands of the future?  And if such change is required, how will it manifest itself?  Will government expand its actions beyond its traditional health and safety related regulatory function?  If so, will it limit its actions to simply leading by example, as it appears to be doing in the case of open document formats?  Or will it in fact expand its regulatory function as well?  Following the completion of the initial phase of the WSIS process, the United Nations retreated, rather than advanced, commissioning the Working Group on Internet Governance (WGIG) more as a discussion group than a new body with a remit to act.  Will that group become more substantive, or will it simply debate?</p>
				<p>The answers to questions such as these may have much to do with public perceptions of the challenges that will need to be addressed, and the importance that is placed upon those challenges.  How these challenges should be viewed and addressed give rise to further questions:</p>
				<ul>
					<li> "	Will Internet access achieve the legal status of a public utility?  Should it?</li>
					<li> "	Will government extend accessibility laws to the Web?  If so, will they defer to SSOs to create not only the standards by which accessibility can be achieved, but also the definition of when it has?</li>
					<li> "	Will eminent domain laws be extended to cover IPR, if that IPR is asserted to block or unduly tax the usage of essential, standards-based ICT services?</li>
					<li> "	Should the development of some ICT standards, such as those that relate to voting, privacy, and medical and financial records, be subject to greater public participation, and if so, how can that participation be achieved?</li>
					<li> "	Will the Technical Barriers to Trade Act and the WTO complaint resolution process adequately address standards-based trade disputes?</li>
					<li> "	Will the United States voluntarily surrender its remaining control over ICANN?</li>
					<li> "	Will ISO/IEC and the National Bodies make their processes more transparent, given that they are exercising a quasi-governmental function (e.g., by making all contradictions, responses and minutes public)?  Should consortia and SDOs be required to do the same for certain types of standards?</li>
					<li> "	Will courts and regulators take a more active interest in standards-related activities (e.g., by imposing stricter duties of good faith and right conduct on standards participants, and permitting stricter penalties when those duties are violated)?</li>
					<li> "	Will governments make it safer to participate in standard setting (e.g., in the United States, by expanding the benefits of the National Cooperative Research and Production Act to participants in standards development, instead of just to SSOs themselves)?</li>
					<li> "	Should government provide greater support for standard setting in the public interest (e.g., by offering tax incentives to participate in SSOs that maintain open processes and provide public participation, or perhaps by subsidizing the operations of such SSOs, where the public interest has been identified as being of importance)?</li>
					<li> "	Will industry create new ways to address convergence, so that a more cohesive, efficient process of standard setting results?</li>
				</ul>
				<div class="calloutleft">
					<p>Will governments make it safer to participate in standard setting (e.g., in the United States, by expanding the benefits of the National Cooperative Research and Production Act to participants in standards development, instead of just to SSOs themselves)? </p>
				</div>
				<p>Given the current status of the standard setting infrastructure, it is difficult to imagine that the concerns underlying many of the questions posed above will be addressed by industry voluntarily.   It is equally difficult to imagine that many of the governmental actions postulated above will occur in the United States, with its laissez-faire, bottom up approach to standard setting.  But it is quite conceivable that they could happen elsewhere, perhaps most obviously in Europe.</p>
				<p><strong><em>Summary:</em></strong>  Governments have already begun to venture into the realm of ICT standards in new ways, most notably as regards open document formats, privacy, and as they relate to open source software.  Whether this is the beginning of an ongoing and extending period of engagement by government in cyberinfrastructure-related matters remains to be seen, but there are logical reasons to assume that it is.  </p>
				<p>How extensive such a movement will be will have much to do with how responsibly and effectively the private sector acts on its own.  Given the history of standard setting to date and the fact that ICT standardization occurs primarily in consortia today, it would appear that at minimum the leading consortia that are influential in creating cyberinfrastructure would be well advised to consider adopting a greater sensitivity to social concerns, if they wish to retain their independence of action when they create standards in that domain.</p>
				<!-- ************* -->
				<p class="center"><em>Comments? </em> Email: <script language="javascript" type="text/javascript">AuConAdd();</script></p>
				<p class="center">Copyright 2007 Andrew Updegrove</p>
	</body>

</html>